const da = {
  AUDIO_GUIDE: {
    BANNER: 'Gratis audioguide',
    PRODUCT_SUFFIX: 'med audioguide',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Autoriseret og pålidelig partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Autoriseret forhandler',
    SUB_TEXT: 'Autentiske oplevelser fra pålidelige og verificerede partnere.',
  },
  REVIEWS: 'anmeldelser',
  AVAILABLE: 'Der er stadig billetter',
  BACK: 'Tilbage',
  BANNER_CTA: 'Køb billetter',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout er et brand, som bruges af millioner af gæster over hele verden, og som tilbyder kuraterede oplevelsesmuligheder til denne seværdighed.',
    NON_PARTNERED_SENSITIVE:
      'Headout er et brand, som bruges af millioner af gæster over hele verden, og som tilbyder kuraterede oplevelsesmuligheder til denne seværdighed. Dette er ikke stedets hjemmeside.',
    PARTNERED_NON_SENSITIVE:
      'Headout er stedets autoriserede og betroede partner og tilbyder kuraterede oplevelsesmuligheder til denne seværdighed.',
    PARTNERED_SENSITIVE:
      'Headout er stedets autoriserede og betroede partner og tilbyder kuraterede oplevelsesmuligheder til denne seværdighed. Dette er ikke stedets hjemmeside.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout er stedets autoriserede og betroede partner og tilbyder et kurateret udvalg af de bedste oplevelsesmuligheder til denne seværdighed.',
  BOOK_NOW_CTA: 'Book nu',
  BOOSTERS: {
    MOST_LOVED: 'Most loved',
    SPECIAL_DEAL: 'Special deal',
    HEADOUT_EXCLUSIVE: 'Kun hos Headout',
  },
  BUY_TICKETS_CTA: 'Køb billetter',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Du kan afbestille disse billetter op til {0} timer, før oplevelsen begynder, og få alle pengene tilbage.',
    CANCELLABLE_ANYTIME:
      'Gratis afbestilling når som helst, før din oplevelse begynder',
    CANCELLABLE_DAYS:
      'Du kan annullere disse billetter op til {0} dage, før oplevelsen begynder, og få alle pengene tilbage.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Disse billetter kan ikke annulleres. De er dog gyldige i en længere periode.',
    HEADING: 'Politik for ændringer',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Disse billetter kan ikke annulleres. De kan dog ombookes op til {0} timer, før oplevelsen begynder.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Disse billetter kan ikke annulleres eller ombookes.',
    VALID_UNTIL_DATE:
      'Disse billetter kan ikke annulleres. Du kan dog bruge dem når som helst før den {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Disse billetter kan ikke annulleres. Du kan dog bruge dem når som helst, inden for de næste {0} dage.',
    VALID_WITHIN_NEXT_MONTHS:
      'Disse billetter kan ikke annulleres. Du kan dog bruge dem når som helst, inden for de næste {0} måneder.',
  },
  CANCELLATION_POLICY_HEADING: 'Afbestillingsregler',
  CASHBACK: '{0} % cashback',
  CASHBACK_INFO:
    'Du får <strong>{0}&nbsp;%</strong> cashback, når du booker denne oplevelse. Din cashback vil automatisk blive indsat på din Headout-konto og kan bruges til enhver fremtidig booking med Headout.',
  CATEGORY_SLIDER_HEADING: 'Kunder, der bookede dette show, har også set',
  CHECK_AVAIL: 'Tjek billetter',
  SELECT_SEATS: 'Vælg pladser',
  CITY_PAGE: {
    BANNER_TITLE: 'De bedste oplevelser i',
    TOP_ATTRACTIONS: 'De vigtigste seværdigheder',
    GO_BEYOND: 'Uden for {0}',
    ALL_DAY_TRIPS: 'Se alle dagsture',
    CITIES_NEARBY: 'Nærliggende byer',
    POPULAR_CATEGORIES: 'Populære kategorier',
    GO_TO_GUIDE: 'Guiden Go-to {0}',
    VIEW_TRAVEL_GUIDE: 'Se rejseguide',
    EXPLORE: 'Udforsk {0}',
    GUIDE_SUBHEADING:
      'Det har aldrig været nemmere at udforske {0}! Vores rejseguide til {0} indeholder alt, hvad du har brug for at vide om byen, lige fra hvad du skal spise, og hvad du skal se, til hvordan du kommer dertil, hvor du kan bo og meget mere!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Generel information',
      WHERE_TO_EAT: 'Hvad skal man spise?',
      WHERE_TO_STAY: 'Hvor skal man bo?',
      THINGS_TO_DO: 'Hvad skal man lave?',
      WEATHER: 'Den bedste årstid',
      NEIGHBOURHOODS: 'Lokalsamfund',
      TRANSPORTATION: 'Transportmuligheder',
      TRIP_PLANNER: 'Rejseplan',
      FAMILY_TRAVEL: 'Rejser med børn',
      TRAVEL_TIPS: 'Rejsetips og -hacks',
      SHOPPING: 'Shopping',
      ART_AND_CULTURE: 'Kunst og kultur',
    },
    MAILER: {
      HEADING: 'Rejseinspiration til {0} direkte i din indbakke',
      SUBHEADING:
        'Udforsk nye byer med kuraterede oplevelser, øjeblikkelig cashback, eksklusive tilbud og vigtige rejsetips!',
    },
  },
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Vi bruger cookies og lignende teknologier til mange formål, herunder for at kunne forbedre din oplevelse på vores websted og til reklameformål.',
    MANAGE_PREFERENCES: 'Administrer',
    PREFERNCES_SAVED: 'Dine præferencer er blevet gemt',
    COOKIES: 'Cookies:',
    ACCEPT: 'OK',
    ALLOW_ALL: 'Tillad alle',
    DENY_ALL: 'Afvis alle',
    HEADING: 'Dit privatliv er vigtigt for os, altid',
    DESCRIPTION:
      '*   Cookies er små filer, som webstedet/platformen placerer på din computer, mobilenhed eller enhver anden elektronisk enhed, og som blandt andet indeholder oplysninger om din browserhistorik.\n*   Vi bruger forskellige typer cookies til at overvåge din brug af vores platform og gemme visse oplysninger, der yderligere hjælper os med at give dig mere personaliserede tjenester. Visse cookies kan blive placeret på din elektroniske enhed på grund af din brug af tjenester, der er tilgængelige på vores platform.\n*   Vi bruger overordnet set to forskellige sæt teknologier under denne overskrift:\n    *   **Cookies eller browsercookies.** Det er en lille fil, der automatisk gemmes på din elektroniske enhed, når du tilgår vores platform. Du kan indstille din browser til at afvise alle cookies. Hvis du ikke accepterer vores cookies, vil du muligvis ikke være i stand til at bruge visse dele af vores platform.\n    *   **Web-beacons.** Også kaldet klare gifs, pixeltags og single-pixel gifs, der er vedhæftet i forskellige dele af vores platform og vores e-mails, der giver os mulighed for at overvåge og forstå brugernes aktivitet.\n*   De cookies, der er gemt på din enhed, kan være "permanente cookies" eller "sessionscookies". Permanente cookies er dem, der forbliver på din enhed, selv når du går offline, mens sessionscookies automatisk slettes, så snart du lukker din webbrowser.\n*   Vi bruger både sessionscookies og permanente cookies til de formål, der er beskrevet nedenfor:\n    *   Nødvendige/essentielle cookies\n        *   _Type:_ Sessionscookies\n        *   _Formål:_ Disse cookies er afgørende for, at du kan få adgang til forskellige dele af platformen, og hvis du ikke tillader disse, kan du muligvis ikke tilgå de tjenester, der er tilgængelige på platformen. Disse cookies hjælper os desuden med at autentificere brugerne og forhindre enhver form for svigagtig aktivitet på platformen.\n    *   Cookiepolitik/Meddelelse om accept af cookies\n        *   _Type:_ Permanente cookies\n        *   _Formål:_ Disse cookies angiver, hvorvidt brugerne har accepteret brugen af cookies.\n    *   Funktionalitetscookies\n        *   _Type:_ Permanente cookies\n        *   _Formål:_ Disse cookies giver os mulighed for at huske de valg, du foretager, når du bruger platformen, f.eks. at huske dine loginoplysninger eller sprogpræferencer. Det overordnede formål med disse cookies er at give dig en mere personlig oplevelse, hver gang du bruger platformen.\n\nAlle begreber, der bruges ovenfor, er defineret i databeskyttelsespolitikken. Læs flere detaljer i [databeskyttelsespolitikken](/privacy-policy/)\n',
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Læs om visumkrav, veksling af valuta, tidszoneforskelle og meget mere, så du kan få en gnidningsfri ankomst og et behageligt ophold.',
    WHERE_TO_EAT:
      'Lad dig forføre af den pulserende, kulinariske scene, prøv nye smage og nyd lokale delikatesser i alle dele af {0}.',
    WHERE_TO_STAY:
      'Oplev de bedste, mest komfortable og bekvemme overnatningssteder i {0}, der gør dit ophold til en mindeværdig oplevelse.',
    THINGS_TO_DO:
      'Oplev et væld af spændende aktiviteter og seværdigheder, der passer til enhver interesse og er garant for en uforglemmelig oplevelse.',
    WEATHER:
      '{0} byder på fortryllende oplevelser hele året rundt, så vær smart, når du planlægger din rejse, og få mest muligt ud af dit besøg.',
    NEIGHBOURHOODS:
      'Lær de forskellige lokalsamfund og de levende kvarterer, som giver {0} sin unikke karakter, at kende.',
    TRANSPORTATION:
      'Kom nemt rundt i {0} ved hjælp af det effektive transportsystem, der giver gode muligheder for at udforske alle byens attraktioner.',
    TRIP_PLANNER:
      'Udnyt din tid i {0} optimalt med omhyggeligt sammensatte rejseplaner, der sikrer, at du får mest muligt ud af hvert øjeblik.',
    FAMILY_TRAVEL:
      'Tag på en familievenligt tur med mange forskellige seværdigheder, parker og underholdningsmuligheder, der henvender sig til børn i alle aldre.',
    TRAVEL_TIPS:
      'Få insidertips og rejse-hacks, der kan forbedre din rejse og gøre dit besøg i {0} til noget helt særligt.',
    SHOPPING:
      'Udforsk et rent shoppingparadis med en bred vifte af butikker, markeder og indkøbscentre, der tilbyder alt fra lokalt kunsthåndværk til eksklusiv mode.',
    ART_AND_CULTURE:
      'Fordyb dig i den rige kunst- og kulturscene med fængslende museer og livlige festivaler, der fejrer {0}s kulturarv.',
  },
  CLOSE: 'Luk',
  COLLECTION_SLICE_HEADING: 'De bedste ting at lave i {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Vælg',
    SELECT_PREFERENCE: 'Vælg din billettype',
    SELECT_OPTION: 'Vælg en valgmulighed',
    SELECT_TICKET: 'Vælg din billet',
  },
  COMPARE_ALL_DETAILS: 'Sammenlign alle detaljer',
  COVID19_ALERT: {
    KEY_TEXT: 'Opdatering vedrørende covid-19',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Du har højeste prioritet for os. Tjek vores hjælpeside for at finde de seneste opdateringer om vores fleksible afbestillingsregler.',
  },
  CURRENCY: 'Valuta',
  CUSTOMER_REVIEW_HEADING: 'Kundeanmeldelser',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioguide',
    DURATION: 'Varighed: {0}',
    EXTENDED_VALIDITY: 'Forlænget gyldighed',
    FLEXIBLE_DURATION: 'Fleksibel varighed',
    FREE_CANCELLATION: 'Gratis afbestilling',
    GUIDED_TOUR: 'Guidet tur',
    HOTEL_PICKUP: 'Afhentning på hotellet',
    INSTANT_CONFIRMATION: 'Øjeblikkelig bekræftelse',
    MEALS_INCLUDED: 'Måltider inkluderet',
    MOBILE_TICKET: 'Mobilbillet',
    SKIP_THE_LINE: 'Spring køen over',
    TRANSFERS: 'Transport inkluderet',
  },
  DURATION: 'Varighed',
  EARLIEST_AVAILABILITY: 'Næste mulighed',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Angiv din e-mail her',
    SIGN_UP: 'Tilmeld dig',
    THANK_YOU: 'Tak skal du have!',
    SUBSCRIBED_MSG: 'Du er nu blevet tilmeldt',
    ERROR_MSG: 'Indtast venligst en gyldig e-mailadresse',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Broadway-teaterbilletter',
    },
    LTT: {
      MB_NAME: 'Teaterbilletter i London',
    },
  },
  EXCLUSIONS: 'Ikke omfattet',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '{0}+ millioner',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100 % sikkerhed',
    HEADING_SUPPORT: 'Hjælpecenter 24x7',
    SUB_HEADING_CUSTOMER: 'Glade kunder på tværs af 10.000+ oplevelser',
    SUB_HEADING_RATING:
      "5.000+ verificerede anmeldelser med 90 % scorer som 'fremragende'",
    SUB_HEADING_SAFE: 'Alle udendørsaktiviteter er 100 % sikre og trygge',
    SUB_HEADING_SUPPORT:
      'Har du spørgsmål? Chat direkte med lokale eksperter hvor som helst, når som helst',
  },
  FLEXIBLE: 'Fleksibel',
  FOOTER: {
    CALL_US: 'Ring til os',
    CHAT_WITH_US: 'Chat med os',
    ABOUT_US: 'Om os',
    COMPANY_DETAILS: 'Oplysninger om virksomheden',
    INFORMATION: 'Information',
    GMAPS_DISCLAIMER:
      'Alle skærmbilleder af kort på denne side er hentet fra Google i overensstemmelse med fair use-princippet. Alle rettigheder til sådanne skærmbilleder ligger hos den specifikke platform, og brug af dem sker udelukkende med henblik på information eller vejledning.',
    DISCLAIMER:
      'Denne hjemmeside er ikke <attraction>s officielle hjemmeside. Den drives af Headout, som arbejder sammen med attraktioner og rejsearrangører om at give utrolige oplevelser via et tryk på en knap.',
    EMAIL_US: 'Send os en e-mail',
    GET_HELP: 'Få hjælp',
    LEGAL: 'Juridiske oplysninger',
    PRIVACY_POLICY: 'Databeskyttelsespolitik',
    QUICK_LINKS: 'Hurtiglinks',
    TERMS_AND_CONDITIONS: 'Vilkår og betingelser',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Skabt med ',
    ALL_OVER_THE: ' over hele ',
    TERMS_OF_USAGE: 'Brugsvilkår',
    GET_HELP_24_7: 'Få hjælp døgnet rundt',
    HELP_CENTER: 'Hjælpecenter',
    COMPANY: 'Firma',
    WE_ACCEPT: 'Vi accepterer',
    DOWNLOAD_HEADOUT: 'Download Headout-appen',
    SCAN_CODES: 'Scan kode',
    STAR_VERIFIED: 'klik for at bekræfte S.T.A.R.-medlemskab',
    OFFICIAL_TICKET_RETAILER: 'Officiel billetforhandler',
  },
  FREE_CANCELLATION: 'Gratis afbestilling',
  FREE_CANCELLATION_SUBTEXT:
    'Vi forstår, at planer kan ændres, så det er gratis at afbestille op til 72 timer før arrangementet.',
  FROM: 'Fra',
  GET_CASHBACK: 'Få {0} % cashback',
  GROUP_TICKETS: 'Gruppebilletter',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '{0}+ millioner glade kunder',
    SUB_TEXT:
      'Kundetilfredshed er vores højeste prioritet. Bliv en del af vores glade kundebase.',
  },
  HEADOUT: 'Headout',
  HELP_CENTER: {
    MAIN_TEXT: 'Døgnåbent hjælpecenter',
    SUB_TEXT:
      'Spørgsmål eller bekymringer? Vi er her for at hjælpe 24/7, på telefon, chat og e-mail.',
  },
  INCLUSIONS: 'Omfattet',
  LANGUAGE: 'Sprog',
  LANGUAGES: {
    ENGLISH: 'Engelsk',
    SPANISH: 'Spansk',
    FRENCH: 'Fransk',
    ITALIAN: 'Italiensk',
    GERMAN: 'Tysk',
    PORTUGUESE: 'Portugisisk',
    NEDERLANDS: 'Hollandsk',
    POLISH: 'Polsk',
    RUSSIAN: 'Russisk',
    DANISH: 'Dansk',
    NORWEGIAN: 'Norsk',
    ROMANIAN: 'Rumænsk',
    SWEDISH: 'Svensk',
    TURKISH: 'Tyrkisk',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Turen findes på {0}',
  LISTICLES: {
    KNOW_MORE: 'Få mere at vide',
    SEATING_CHART: 'Oversigt over siddepladser',
    WHY_BOOK_FROM_US: 'Hvorfor booke hos os?',
  },
  MORE_DETAILS: 'Flere detaljer',
  MORE_CURRENCIES: 'Flere valutaer',
  NEW: 'NYHED',
  NEW_ARRIVAL: 'Helt ny her',
  NEXT_AVAILABLE: 'Næste mulighed: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout er et brand, som bruges af over {0} millioner gæster, og som tilbyder et kurateret udvalg af de bedste oplevelser. Dette er ikke stedets hjemmeside.',
  NO_RESULT_FOUND: 'Hmm, der blev ikke fundet nogen resultater.',
  OFF: 'rabat',
  OPEN_DATED_DESCRIPTOR:
    'Book med fleksibilitet: Du behøver ikke vælge nogen dato',
  OPENING_DATE: 'Åbningsdato',
  OPENING_ON: 'Åbner den',
  OPENS: 'Åbner',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout er stedets autoriserede og betroede partner og tilbyder et kurateret udvalg af de bedste oplevelsesmuligheder til denne seværdighed. Dette er ikke stedets hjemmeside.',
  POPULAR_CURRENCIES: 'Populære valutaer',
  PRICES_STARTING: 'Priser fra',
  PROMO_CODES: {
    APPLY_CODE: 'ANVEND KODE',
    APPLIED: 'ANVENDT',
    TOOL_TIP_INFO: 'Denne rabat anvendes ved kassen',
    DESCRIPTION: {
      ABSOLUTE: 'Få {0} rabat',
      CAPPED: 'Få {0} % rabat, op til {1}',
      PERCENTAGE: 'Få {0} % rabat',
    },
    REMOVE: 'FJERN',
  },
  RATINGS: '{0} bedømmelser',
  READ_MORE: 'Læs mere',
  READ_MORE_TEXT: 'Læs mere',
  READ_LESS: 'Læs mindre',
  VIEW_DETAILS: 'Se detaljer',
  REOPENING: 'Genåbning',
  REOPENING_DATE: 'Dato for genåbning',
  REOPENING_ON: 'Genåbning den',
  REOPENS: 'Åbner igen',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      CTA_URL:
        'https://www.austria.info/en/service-and-facts/coronavirus-information/entry-regulations',
      TEXT: '2G-regler gælder: Adgang til blandt andet indkvartering, kulturinstitutioner og restauranter/barer er kun mulig med bevis for fuld vaccination eller tidligere infektion. En negativ covid-19-test er ikke længere tilstrækkelig.',
    },
    AU_DESCRIPTION: {
      CTA_URL:
        'https://www.smartraveller.gov.au/COVID-19/COVID-19-vaccinations',
      TEXT: 'Besøgende på 16 år og derover skal fremvise bevis for covid-19-vaccination eller medicinsk dispensation. ',
    },
    BANNER_CTA: 'Få mere at vide',
    BERLIN_DESCRIPTION: {
      CTA_URL:
        'https://www.berlin.de/en/news/coronavirus/7081102-6098215-berlin-introduces-extensive-2G-rule.en.html',
      TEXT: '2G-regler gælder: Kun fuldt vaccinerede og raske gæster med bevis for samme gives adgang. Gæster under 18 år og dem, der ikke kan vaccineres af medicinske årsager, skal fremvise et negativt covid-testresultat ved indgangen. De, der ikke kan vaccineres af medicinske årsager, skal også bevise deres manglende evne til at blive vaccineret ved fremvisning af en lægeerklæring ved indgangen.',
    },
    CTA_TEXT: 'Sikkerhedsoplysninger',
    DESCRIPTION_CTA: 'Få mere at vide.',
    EU_DESCRIPTION: {
      CTA_URL:
        'https://www.diplomatie.gouv.fr/en/coming-to-france/coronavirus-advice-for-foreign-nationals-in-france/coronavirus-statements/article/applying-for-a-covid-certificate-if-you-were-vaccinated-abroad-procedure-for',
      TEXT: 'Fra den 21. juli 2021 skal alle besøgende på 12 år og derover fremvise en EU COVID-attest. ',
    },
    EU_HEADING: 'EU COVID-attest påkrævet',
    EU_PREFIX: 'Bemærk: ',
    EXPERIENCE_DESCRIPTION:
      'Denne oplevelses efterlevelse af de bedste sikkerhedsstandarder i overensstemmelse med lokale regler og WHO er verificeret',
    FLAG_TEXT: 'Bedste sikkerhedsstandarder',
    GENERAL_DESCRIPTION:
      'Enhver oplevelse med dette badge har fået verificeret sin efterlevelse af de bedste sikkerhedsstandarder i henhold til de lokale myndigheders sundhedsretningslinjer.',
    HEADING: 'Bedste sikkerhedsstandarder',
    IT_DESCRIPTION: {
      CTA_URL: 'https://www.dgc.gov.it/web/per-cosa-serve.html#viaggi',
      TEXT: 'Fra den 6. august 2021 skal alle besøgende på 11 år og derover fremvise et Green Pass eller en EU COVID-attest. ',
    },
    IT_PREFIX: 'Bemærk: ',
    MOBILE_HEADING: 'Trygge oplevelser',
    MODAL: {
      BADGE_DESCRIPTION:
        'Dette badge på en oplevelse bekræfter, at sikkerhedsstandarderne er blevet verificeret af os.',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Alt udstyr, alle køretøjer og alle områder, hvor man kommer i berøring med mange mennesker, desinficeres efter hver eneste brug. Bare slap af, og nyd oplevelsen.',
          HEADING: 'Alt udstyr og alle overflader desinficeres',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Alt det udstyr, der er til rådighed under din oplevelse, bliver grundigt desinficeret efter hver eneste brug. Hver gang.',
          HEADING: 'Alt udstyr og alle overflader desinficeres',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Alle de køretøjer, der er til rådighed under din oplevelse, bliver grundigt desinficeret efter hver eneste brug. Hver gang.',
          HEADING: 'Alle køretøjer desinficeres',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Som en del af en sikker oplevelse vil du have adgang til håndvask- og sanitetsstationer under al den tid, du er her. Vi har din ryg. ',
          HEADING: 'Der er adgang til håndvask og sanitære faciliteter overalt',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Mundbind er obligatoriske for alle gæster og medarbejdere i denne oplevelse. Det bidrager til, at alle kan have det sjovt og føle sig trygge.',
          HEADING: 'Alle bruger mundbind for din sikkerheds skyld',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Vores partnere, der er blevet verificeret som en sikker oplevelse, følger de lokale regler omkring ansigtsmasker. Hvis det er obligatorisk, skal alle gæster og medarbejdere bruge mundbind. De træffer alle mulige foranstaltninger for at sikre, at du føler dig tilpas og sikker.',
          HEADING: 'Alle bruger mundbind for din sikkerheds skyld',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Mundbind er obligatoriske for alle gæster i denne oplevelse. Det bidrager til, at alle kan have det sjovt og føle sig trygge.',
          HEADING: 'Alle bruger mundbind for din sikkerheds skyld',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Alle medarbejdere ved denne oplevelse bruger ansigtsmasker for at sikre, at du kan få alt det sjove uden alle bekymringerne.',
          HEADING: 'Alle bruger mundbind for din sikkerheds skyld',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Retningslinjerne for fysisk afstand gælder for hele denne oplevelse. Der er indført kapacitetsbegrænsninger for at sikre fysisk afstand.',
          HEADING: 'Retningslinjerne for fysisk afstand følges',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Retningslinjerne for fysisk afstand gælder for hele denne oplevelse. Der er indført kapacitetsbegrænsninger for at sikre fysisk afstand. Ligeledes er store grupper ikke tilladt her.',
          HEADING: 'Retningslinjerne for fysisk afstand følges',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Retningslinjerne for fysisk afstand bliver til hver en tid overholdt under denne oplevelse.',
          HEADING: 'Retningslinjerne for fysisk afstand følges',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Retningslinjerne for fysisk afstand bliver til hver en tid overholdt under denne oplevelse. For at håndhæve dette kan der være fastlagt kapacitetsbegrænsninger og gruppebegrænsninger. Så du kan trække vejret roligt.',
          HEADING: 'Retningslinjerne for fysisk afstand følges',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Retningslinjerne for fysisk afstand bliver til hver en tid overholdt under denne oplevelse. Ligeledes er store grupper ikke tilladt her.',
          HEADING: 'Retningslinjerne for fysisk afstand følges',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Alle gæster får tjekket deres temperatur i starten af oplevelsen for at sikre, at det er sikkert for alle. Alle medarbejdere bliver tjekket for høj temperatur flere gange om dagen.',
          HEADING: 'Temperaturkontrol',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Alle gæster får tjekket deres temperatur i starten af oplevelsen for at sikre, at det er sikkert for alle. ',
          HEADING: 'Temperaturkontrol',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Alle medarbejdere bliver tjekket for høj temperatur flere gange. Medarbejdere, hvis temperatur ligger over den foreskrevne grænse, bliver bedt om at tage hjem, så de kan blive raske.',
          HEADING: 'Temperaturkontrol',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            "Det personale, der står til rådighed under hele oplevelsen, er uddannet i henhold til WHO's retningslinjer og i stand til at håndtere enhver nødsituation, de måtte opleve.",
          HEADING: "Personalet er uddannet i WHO's retningslinjer",
        },
      },
      HEADING: 'Trygge oplevelser',
      SUB_HEADING:
        "Vi arbejder sammen med vores partnere over hele verden for at implementere de bedste sikkerhedsstandarder i henhold til WHO's retningslinjer. Alle de foranstaltninger, der er truffet på stedet, er blevet verificeret og vises her. Det er tid til at nyde verden omkring os igen.",
    },
    NL_DESCRIPTION: {
      CTA_URL:
        'https://www.government.nl/topics/coronavirus-covid-19/covid-certificate',
      TEXT: 'Besøgende på 13 år og derover skal have et covid-certifikat (digitalt eller en trykt kopi), der viser, at de er blevet vaccineret, har fået et negativt testresultat eller for nylig er kommet sig over covid-19. Det er obligatorisk at bruge ansigtsmaske. ',
    },
    SG_DESCRIPTION: {
      CTA_URL: 'https://safetravel.ica.gov.sg/health/vtsg',
      TEXT: 'Fra den 13. oktober 2021 er det udelukkende fuldt vaccinerede besøgende, der må komme ind i grupper på to. Du skal fremvise bevis for din vaccinationsstatus, et aktuelt negativt covid-19-testresultat og/eller eventuel helbredelsesdokumentation før indgang. ',
    },
    SHORT_HEADING: 'De bedste sikkerhedsstandarder',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Sikkerhedsoplysninger',
    EXPERIENCE_DESCRIPTION:
      'Denne oplevelses efterlevelse af de bedste sikkerhedsstandarder i overensstemmelse med lokale regler og WHO er verificeret',
    FLAG_TEXT: 'Bedste sikkerhedsstandarder',
    GENERAL_DESCRIPTION:
      'Dette sted er såkaldt COVID SECURE og følger alle de sikkerhedsforanstaltninger, der anbefales af staten, for at sikre, at du får en sikker teateroplevelse med fysisk afstand.',
    GENERAL_DESCRIPTION_V2:
      'Vi har udviklet det brancheomspændende See it Safely-mærke, så når teatre genåbner, kan du føle dig tryg og sikker ved at vide, at stedet er covid-sikret og følger de seneste retningslinjer fra staten og de udøvende kunstnere.',
    HEADING: 'See it Safely',
    MOBILE_HEADING: 'Trygge oplevelser',
    MORE_CURRENCIES: 'Flere valutaer',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Kun print-selv-billetter og e-billetter vil blive accepteret</li>',
          HEADING: 'Kontaktløse e-billetter',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Beskyttelsesudstyr som f.eks. mundbind er obligatorisk for at komme ind på stedet</li>\n            <li>Alle tilskuere vil blive underkastet temperaturkontrol, før de får adgang til stedet</li>',
          HEADING: 'Forebyggende sikkerhedsforanstaltninger',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Beskyttelsesudstyr som f.eks. mundbind er obligatorisk for at komme ind på stedet</li>\n            <li>Alle tilskuere vil blive underkastet temperaturkontrol, før de får adgang til stedet</li>',
          HEADING: 'Desinficeringsforanstaltninger',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Stedet er blevet redesignet for at minimere kontakten mellem alle tilskuere</li>\n            <li>Forskellige grupper vil sidde hver for sig</li>\n            <li>Forudbestilling af pausesnacks vil blive gjort lettere, hvor det er muligt</li>\n            <li>Kontantløse og papirløse transaktioner anbefales.</li>\n            <li>Alle tilskuere bedes medbringe så få personlige ejendele som muligt, da garderobefaciliteterne kan være lukkede</li>\n            <li>Aktiviteter, såsom at tage billeder med kunstnerne eller skrive autografer, kan være begrænsede</li>\n',
          HEADING: 'Fysisk afstandstiltag',
        },
      },
      HEADING: 'See it Safely',
      SUB_HEADING:
        'Vil du gerne vide, hvad der alt sammen bliver gjort for at beskytte dig? Få mere at vide om de sikkerhedsforanstaltninger og covid-sikkerhedsprotokoller, som teatrene har implementeret for at værne om din sikkerhed.',
    },
    SHORT_HEADING: 'De bedste sikkerhedsstandarder',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Din sikkerhed har stor prioritet for os',
    TEXT: 'Vi har truffet vigtige foranstaltninger for at forbedre renligheden ved at bruge desinfektionsmidler og udføre omfattende og hyppig rengøring af overflader. Menneskemængderne holdes også under kontrol for at undgå overbelastning.',
  },
  SAVE: 'Spar {0} %',
  SAVE_PERCENT: 'Spar {0} %',
  SAVE_UPTO_PERCENT: 'Spar op til {0} %',
  SEE_ALL: 'Se alle',
  SEARCH: 'Søg',
  POPULARITY: 'Popularitet',
  PRICE: 'Pris',
  SEE_MORE_SHOWS: 'Se flere shows',
  SELECT_CITY: 'Vælg by',
  SELECT_SECTION: 'Vælg sektion',
  SEE_ALL_PHOTOS: 'Se alle billeder',
  SHOW_CLOSED: 'Spiller ikke længere',
  SHOW_LESS: 'Vis mindre',
  SHOW_LESS_TEXT: 'Vis mindre',
  SHOW_MORE: 'Vis mere',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Om showet',
    ABOUT_THEATRE: 'Om teatret',
    ADDITIONAL_INFORMATION: 'Yderligere information',
    AGE_LIMIT: 'Aldersgrænse',
    AGE_SUITABILITY: 'Aldersgruppe',
    CRITIC_REVIEW: 'Anmelderne siger',
    ANSWER: ['Sv.-'],
    BLOG_SHOW_PAGE: 'Blog Side om forestillingen',
    BLOG_SUMMARY: 'Blogoversigt',
    BLOG_THEATRE_PAGE: 'Blog Teaterside',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Teatrets salsplan',
    CANCELLATION_AND_REFUNDS: 'Annullering og refundering',
    CANCELLATION_POLICY: 'Afbestillingsregler',
    CAST_AND_CREW: 'Medvirkende og besætning',
    CLOSING_DATE: 'Sidste forestilling',
    CLOSING_DATE_SPECIAL_OFFER: 'Sidste dato for særtilbud',
    DURATION: 'Varighed',
    FACILITIES_AND_ACCESSIBILITY: 'Faciliteter og tilgængelighed',
    FREQUENTLY_ASKED_QUESTIONS: 'Ofte stillede spørgsmål',
    GETTING_THERE: 'Transport',
    GETTING_THERE_MAP_LINK: 'Link til kort over transportmuligheder',
    GOOGLE_MAP: 'Google-kort',
    HIGHLIGHTS: 'Højdepunkter',
    LISTICLE_SHOW_SUMMARY: 'Listicle Resumé af forestillingen',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Hvorfor du skal se showet',
    OPENING_DATE: 'Åbningsdato',
    QUESTION: ['Sp.-'],
    SAFETY_BANNER: 'Sikkerhedsbanner',
    SHOW_DETAILS: 'Detaljer om forestillingen',
    SHOW_TIMINGS: 'Spilletider for forestillingen',
    SHOW_TYPE: 'Forestillingstype',
    SPECIAL_OFFER: 'Særtilbud',
    THE_STORY: 'Historien',
    THEATRE_ADDRESS: 'Teateradresse',
    THEATRE_CAPACITY: 'Teatrets kapacitet',
    THEATRE_NAME: 'Teatrets navn',
    TICKETS: 'Billetter',
    TICKETS_REDEMPTION: 'Indløsning af billetter',
    TOP_SONGS: 'De største sange',
    YOUR_TICKETS: 'Dine billetter',
    ABOUT_CONCERT: 'Om koncerten',
    PROGRAM: 'Program',
  },
  SORT_BY: 'Sortér efter',
  SPECIAL_OFFER: 'Særtilbud',
  THEATRE: 'Teater',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Teatre i nærheden',
    NOW_PLAYING: 'Aktuel',
    UPCOMING_SHOWS: 'Kommende shows',
    PAST_SHOWS: 'Tidligere shows',
    FIND_BEST_SEATS: 'Find de bedste pladser',
  },
  TICKET_CAN_BE_CANCELED:
    'Du kan afbestille op til {hours} timer i forvejen, og få alle pengene tilbage.',
  TICKET_CANNOT_BE_CANCELED:
    'Denne billet kan ikke annulleres, men kan ombookes efter anmodning.',
  TICKETS: 'Billetter',
  TIMINGS: 'Tidspunkter',
  SPECIAL_PRODUCT_HEADING: 'Mest elskede',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Lokale ekspertguider',
    ENGAGING_STORIES: 'Engagerende historier',
    TOP_RATED: 'Topbedømmelse',
  },
  GUIDED_TOUR_REVIEWS: [
    'Vores guide Angela var alletiders og vidste en masse om stedet',
    'Guiden besvarede gerne spørgsmål om turen',
    'Vores guide var alletiders, og hun gav os endda en god frokostanbefaling!',
    'Tilrettelæggelsen og vores guide gjorde oplevelsen rigtig hyggelig',
    'En masse lærerigt indhold. Jeg vil helt sikkert gøre det igen med mine børn',
    'Turen var velorganiseret og havde også den helt rigtige længde',
    'Vores guide kunne virkelig sit kram, og hans passion for historie var tydelig',
    'God guide og tilrettelæggelse! Meget anbefalelsesværdig!!!',
    'Vores guides små fun facts holdt vores alle sammens interesse',
    'Turen gik i et godt tempo og føltes ikke forhastet',
    'Vores guide Maria fandt os de bedste udsigtspunkter',
    'Vores guide berigede vores besøg ud over det, vi ville have opnået på egen hånd',
    'En dybt bevægende tur med stor detaljerigdom, ledet af en passioneret guide',
    'Jeff viste os aspekter af stedet, som vi ellers ville have overset',
  ],
  GUIDES_BANNER:
    'Gå på opdagelse som en lokal med vores superguider, som gæsterne er vilde med.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'En guidet tur er den bedste måde at få mest muligt ud af denne destination på. Vores ekspertguider fungerer som dine lokale venner, der deler historier, insiderperler og rejseanbefalinger.',
    'Vær ikke blot til stede – mærk det på egen krop!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Udsagn fra vores gæster',
  GUIDES: 'Guider',
  TODAY: 'I dag',
  TOMORROW: 'I morgen',
  TOUR_LIST_HEADING: 'Vælg din oplevelse',
  TOUR_LIST_SUB_HEADING:
    'Vælg mellem flere billetter, ture og kombinationsmuligheder fra verificerede partnere',
  UGC: {
    FOLLOW: 'Følg',
    FOLLOW_IG: 'Følg på Instagram',
    HEADING: 'POV: Dit næste eventyr ser sådan ud',
    SUB_HEADING: 'Kurateret med 💜 af Headout',
  },
  UNAVAILABLE: 'Ikke tilgængelig',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Disse billetter er gyldige i en længere periode. De nøjagtige detaljer vil fremgå af billetten.',
    UNTIL_DATE: 'Disse billetter er gyldige indtil {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Disse billetter er gyldige i {0} dage efter købsdatoen.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Disse billetter er gyldige i {0} måneder efter købsdatoen.',
  },
  TABLE_OF_CONTENTS: 'Indhold',
  VIEW_LESS: 'Se mindre',
  VIEW_MORE: 'Se mere',
  WHY_TAKE_THIS_DAY_TRIP: 'Hvorfor du skal tage på denne dagstur?',
  WHY_WATCH: 'Hvorfor du skal ind og se {0}?',
  FIND_ON_MAP: 'Find på kort',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Billetter fra billetkontoret',
        DESCRIPTION: 'Bekræftes øjeblikkeligt på din telefon',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: 'Vælg dine pladser',
        DESCRIPTION: 'Den udsigt, du ønsker, hver gang',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Eksklusive tilbud og rabatter',
        DESCRIPTION: 'Spar stort på {0}s bedste shows',
      },
      BOOK_AND_RELAX: {
        NAME: 'Book og nyd det',
        DESCRIPTION: 'Brugt af {0} millioner gæster, og tallet vokser',
      },
    },
    YOUR_PICK: 'Dit valg',
    BROWSE_BY_CATEGORIES: 'Gennemse efter kategori',
    TOP_WEST_END_SHOWS: 'De bedste West End-forestillinger',
    TOP_THEATRE_SHOWS: 'De bedste shows i {0}',
    TOP_SHOWS: 'De bedste shows',
    SEE_MORE_SHOWS: 'Se {0} flere shows',
    LAST_MINUTE_TICKETS: 'Billetter i sidste øjeblik',
    LOVED_BY_MILLIONS: 'Elsket af millioner',
    TODAY: 'I dag',
    TOMORROW: 'I morgen',
    SEE_ALL: 'Se alle',
    GRAB_YOUR_TICKETS: 'Få fat i dine billetter nu',
  },
  TAG_NAME: {
    BALLET: 'Ballet',
    CABARET: 'Kabaret',
    CHRISTMAS: 'Jul',
    CIRCUS: 'Cirkus',
    CLASSIC: 'Klassisk',
    COMEDY: 'Komedie',
    COMING_SOON: 'Kommer snart',
    CRITICS_CHOICE: 'Anmeldernes valg',
    DANCE: 'Dans',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'Den engelske nationalballet',
    ENGLISH_NATIONAL_OPERA: 'Den engelske nationalopera',
    FANTASY: 'Fantasy',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Immersivt teater',
    JUKEBOX: 'Jukebox',
    KIDS: 'Børn',
    MAGIC: 'Magi',
    MUSICALS: 'Musicals',
    NEW_ARRIVAL: 'Helt ny her',
    OFF_WEST_END: 'Uden for West End',
    OLIVIER_WINNER: 'Vinder af Olivier Award',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomimer',
    PLAYS: 'Teaterstykker',
    ROMANCE: 'Romantik',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Stjerner på scenen',
    THEATRICAL_CONCERT: 'Teaterkoncert',
    TRUE_STORY: 'Sand historie',
    TONY_WINNER: 'Tony-vinder',
    OFF_BROADWAY: 'Off-Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Åh, nej, der er opstået et problem',
    MESSAGE:
      'Vi beklager. Alle oplevelser på denne dato er enten udsolgt eller\n    ikke tilgængelige. Men vi har masser af billetter til andre datoer. Du\n    skal bare være fleksibel.',
    CTA: 'Se alle datoer',
  },
  ALL_DATES: 'Alle datoer',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Hovedmenu',
    EXPLORE: 'Udforsk',
    VISIT: 'Besøg',
    THINGS_TO_DO: 'Ting at lave',
    CITY_ATTRACTIONS: 'Seværdigheder i {0}',
    TOP_THINGS_TO_DO: 'De bedste ting at lave',
    CITY_TOURS: 'Ture i {0}',
    CITY_GUIDE: 'Guide til byen',
    ATTRACTIONS: 'Seværdigheder',
    CRUISES: 'Sejlture',
    THEMES: 'Temaer',
    ABOUT: 'Om',
    TOURS: 'Ture',
    SKIP_THE_LINE: 'Ture uden at stå i kø',
    GUIDED_TOURS: 'Guidede ture',
    NIGHT_TOURS: 'Ture om natten',
    FOOD_TOURS: 'Madture',
    HISTORY: 'Historie',
    ARCHITECTURE: 'Arkitektur',
    DESIGN: 'Design',
    INSIDE: 'Indenfor',
    COLLECTIONS: 'Samlinger',
    PAINTINGS: 'Malerier',
    ANIMALS_EXHIBITS: 'Dyr og udstillinger',
    HABITATS: 'Habitater',
    CONSERVATION: 'Bevarelse',
    PROGRAMMES: 'Programmer',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing-sejlture',
    A2_DINNER_CRUISES: 'Middagssejlture',
    A2_EVENING_CRUISES: 'Aftensejlture',
    A2_LUNCH_CRUISES: 'Frokostsejlture',
    A2_YACHT_TOURS: 'Yachtture',
    PLAN_YOUR_VISIT: 'Planlæg dit besøg',
    TIMINGS: 'Tidspunkter',
    DIRECTIONS: 'Rutevejledning',
    PARKING: 'Parkering',
    ROUTES: 'Ruter',
    REQUIREMENTS: 'Adgangskriterier',
    LOCATION: 'Beliggenhed',
    RULES: 'Regler',
    FAQs: 'Ofte stillede spørgsmål',
    ENTRANCES: 'Adgangsmetoder',
    RESTAURANTS: 'Restauranter',
    FACTS: 'Fakta',
    TIPS: 'Tips',
    MAP: 'Kort',
    RIDES: 'Forlystelser',
    SHOWS: 'Forestillinger',
    DINING: 'Spisning',
    SHOPPING: 'Shopping',
    EVENTS: 'Events',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Jul',
    NEW_YEARS_EVE: 'Nytårsaften',
    TRAVEL_GUIDE: 'Rejseguide',
    TRIP_PLANNER: 'Rejseplanlægger',
    ITINERARY: 'Rejseplan',
    TRAVEL_TIPS: 'Tips til rejser',
    WEATHER: 'Vejret',
    BEST_TIME_TO_VISIT: 'Den bedste årstid',
    JANUARY: 'Januar',
    FEBRUARY: 'Februar',
    MARCH: 'Marts',
    APRIL: 'April',
    MAY: 'Maj',
    JUNE: 'Juni',
    JULY: 'Juli',
    AUGUST: 'August',
    SEPTEMBER: 'September',
    OCTOBER: 'Oktober',
    NOVEMBER: 'November',
    DECEMBER: 'December',
    WHERE_TO_EAT: 'Hvor man kan spise',
    WHERE_TO_STAY: 'Hvor man kan bo',
    NEIGHBOURHOODS: 'Områder',
    FAMILY_TRAVEL: 'Rejse med familien',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivaler og begivenheder',
  },
  BREADCRUMBS: {
    HOME: 'Hjem',
    TRAVEL_GUIDE: 'Rejseguide',
    THINGS_TO_DO: 'Ting at lave i {0}',
    SHOW_NAME_TICKETS: '{0} – billetter',
    LTT_HOME: 'Teaterbilletter i London',
    LTT_VENUE_PAGE_HOME: 'Teatre i London',
    BROADWAY_HOME: 'Billetter til Broadway-shows',
    BROADWAY_VENUE_PAGE_HOME: 'Broadway-teatre',
    VIENNA_CONCERT_HOME: 'Koncertbilletter i Wien',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Koncertsale i Wien',
    ATTRACTIONS: 'Seværdigheder',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing-sejlture',
    A2_DINNER_CRUISES: 'Middagssejlture',
    A2_EVENING_CRUISES: 'Aftensejlture',
    A2_LUNCH_CRUISES: 'Frokostsejlture',
    A2_YACHT_TOURS: 'Yachtture',
    LONDON_THEATRE_NEWS: 'Teaternyheder i London',
    BROADWAY_SHOW_NEWS: 'Nyheder om Broadway-shows',
    NEWS_PAGE: 'Nyhedsside',
    REVIEWS_PAGE_BANNER_HEADING: '{0} anmeldelser',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Café',
    'Dedicated Parking': 'Egen parkeringsplads',
    Elevators: 'Elevatorer',
    Lift: 'Elevator',
    'Wheelchair Accessible': 'Tilgængelig for kørestole',
    Cloakroom: 'Garderobe',
    'Air Conditioning': 'Aircondition',
    WiFi: 'Wi-fi',
    Bar: 'Bar',
    'Water Fountain': 'Drikkefontæne',
    Washrooms: 'Toiletter',
    Toilets: 'Toiletter',
    Binoculars: 'Kikkerter',
    'Adapted Toilets': 'Tilpassede toiletter',
    'Accessible Toilets': 'Tilgængelige toiletter',
    'Assistive Listening System': 'Lydsystem til hørehæmmede',
    'Hearing Assistance': 'Hørehjælp',
    'Booster Cushions': 'Børnesæder',
    Shop: 'Butik',
    'Souvenir Shop': 'Souvenirbutik',
    'Guide Dogs': 'Førerhunde',
    'Baby Changing Facilities': 'Pusleplads',
    'Security Check': 'Sikkerhedskontrol',
    Ramp: 'Rampe',
    'Level Access': 'Niveaufri adgang',
  },
  CALENDAR: {
    FOOTNOTE: '* Alle priser er i {0}',
    PICK_DATE: 'Vælg en dato',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Se den oprindelige anmeldelse på {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Denne anmeldelse er blevet oversat. Vis den oprindelige anmeldelse.',
    TRANSLATE: 'Oversæt anmeldelse til {0}',
    LANGUAGES: {
      EN: 'Engelsk',
      ES: 'Spansk',
      FR: 'Fransk',
      IT: 'Italiensk',
      DE: 'Tysk',
      PT: 'Portugisisk',
      NL: 'Hollandsk',
    },
  },
  SHOW_PAGE_V2: {
    READ_MORE_REVIEWS: 'Læs flere anmeldelser',
    SHOW_MORE_REVIEWS: 'Vis flere anmeldelser',
    ALL_PHOTOS: 'Alle billeder',
    MORE_DATES: 'Flere datoer',
    SELLING_OUT_FAST: 'Snart udsolgt',
    SELECT_TIME_SLOT: 'Vælg en tid',
    SELECT_TIME_SLOT_ERROR: 'Vælg en tid for at fortsætte',
    PRICE_STARTING_FROM: 'Prisen for pladserne starter ved',
    SELECT_SEATS: 'Vælg pladser',
    READ_MORE: 'Læs mere',
    RATINGS_AND_REVIEWS: 'Bedømmelser og anmeldelser',
    READ_DETAILED_REVIEWS: 'Læs detaljerede anmeldelser',
    INTERVAL: 'Interval',
    TWO_PART_SHOW: 'Show i to dele',
    UNTIL_DATE: 'Indtil den {0}',
    AVAILABLE_TIME: 'Tilgængeligt tidspunkt',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Denne oplevelse er kun tilgængelig på nedenstående tidspunkt',
    CONTENT_TABS: {
      ABOUT: 'Om',
      VENUE: 'Sted',
      TICKETS: 'Billetter',
      Reviews: 'Anmeldelser',
    },
    SELECT_SHOW_TIMMING: 'Vælg dit tidspunkt for forestillingen',
    ONLY_ONE_SLOT: 'Kun 1 ledigt tidspunkt på den valgte dato',
    SIMILAR_SHOWS: 'Du vil måske også synes om',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Handling',
      WHAT_CRITICS_THINK: 'Anmeldernes mening',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Ofte stillede spørgsmål om {0}',
      AGE_SUITABILITY_AND_GUIDELINES: 'Vejledning vedrørende alder og indhold',
      CAST_AND_CREATIVES: 'Medvirkende og producere',
    },
  },
  HOHO: {
    HOHO: 'Hop-på-og-hop-af-ture',
    BUS_ROUTES_DETAILS: 'Busruter',
    TOUR_DETAILS: 'Detaljer om turen',
    ROUTES_SCHEDULES: 'Ruter og tidsplaner',
    VALIDITY: 'Gælder for 1 dag',
    VALIDITY_NOTE:
      'Billetten til din oplevelse er gyldig {0} kalenderdag(e). Hvis du bestiller din billet til den 6. maj 2023, er den gyldig indtil den 6. maj 2023, kl. 21.00 PST.',
    BESTSELLER: 'Bestseller',
    SEE_ALL: 'Se alle',
    TIMINGS: 'TIDSPUNKTER',
    FREQUENCY: 'HYPPIGHED',
    DURATION: 'VARIGHED',
    STARTING_LOCATION: 'Startadresse',
    CALENDAR_FOOTNOTE: '* Alle priser er i {0}',
    TOUR_TIMINGS: 'Tidspunkter for turen',
    TOUR_FREQUENCY: 'Turens hyppighed',
    GOT_IT: 'Forstået',
    SELECT_DATE: 'Vælg en dato',
    SELECT_TOUR: 'Vælg turtype',
    VIEW_TOUR_DETAILS: 'Se detaljer om turen',
    BUS_DETAILS: 'FLERE DETALJER',
    VIEW_ROUTES: 'Se alle ruter',
    BUS_ROUTES: 'BUSRUTER',
    ATTRACTIONS_PREVIEW:
      'Den hurtigste måde at se {0}+ af de vigtigste seværdigheder, bl.a.',
    ROUTES: 'Ruter',
    COMBO_SUBTITLE: 'Spar mere med',
    COMBO_TITLE: 'Kombinationstilbud på din Hop-på-og-hop-af-tur',
    COMBO_DWEB_TITLE:
      'Spar mere med kombinationstilbud på din Hop-på-og-hop-af-tur',
    STOPS_AND_ATTRACTIONS: 'Stop og seværdigheder i nærheden',
    HOP_ON_OFF_AT:
      'Vælg selv, på hvilke af disse {0} stop du vil hoppe på og af',
    TIMINGS_FREQUENCY: 'Tider og hyppighed',
    TOUR_DURATION: 'Turens varighed',
    EVERY_X_MINS: 'Hvert {0}',
    VIEW_LOCATION: 'Se placering',
    BANNER_SUBTEXT:
      'Det nemmeste og hurtigste overblik over alle byens vigtigste seværdigheder.',
    TOP_ATTRACTIONS: 'De vigtigste omfattede seværdigheder',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Booking i sidste øjeblik',
        DESCRIPTION: 'Bekræftes øjeblikkeligt på din telefon',
      },
      COST_EFF: {
        NAME: 'Billig udforskning',
        DESCRIPTION: 'Flere vartegn med én billet',
      },
      DAILY_RIDES: {
        NAME: 'Ubegrænset antal ture',
        DESCRIPTION: 'Udforsk byen i dit eget tempo',
      },
      BOOK_RELAX: {
        NAME: 'Book og nyd det',
        DESCRIPTION: 'Brugt af {0} millioner gæster',
      },
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Flersprogede ekspertguider',
    STL: 'Spring-køen-over-adgang',
    PERSONALIZED: 'Personaliseret oplevelse',
    LOCAL_FOOD: 'Lokal mad og kultur',
    MULTILINGUAL_GUIDES: 'Flersprogede guider',
    CULINARY_EXPERTS: 'Kulinariske eksperter',
    SIGHTSEEING: 'Sightseeing og underholdning om bord',
    SIGHTSEEING_MEAL: 'Muligheder for sightseeing og måltider om bord',
    MULTILINGUAL_GT: 'Flersprogede guidede ture',
    AUDIOGUIDE_COMMENTARY: 'Mulighed for audioguide og kommentarspor',
    ALL_TOP_ATTRACTIONS_COVERED: 'Alle vigtigste omfattede seværdigheder',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Fast tidsplan. Ubegrænset antal ture',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Tilgængelig i sidste øjeblik. Øjeblikkelig bekræftelse',
    MULTI_ROUTES: 'Flere rutemuligheder',
    HASSLE_FREE: 'Problemfri booking',
    FREQUENT_DEPARTURES: 'Hyppige afgange',
    ONBOARD_AMENITIES: 'Bedste faciliteter om bord',
    FLEXI_TRAVEL: 'Fleksibel rejse på flere ruter',
    FLEXI_EXCHANGE_CANCEL: 'Fleksible ombytninger og annulleringer',
    EXTRA_DISCOUNT: 'Ekstra rabatter til unge, seniorer og familier',
    PREPAID: 'Bekvem forudbetaling',
    EASY_ACTIVATION: 'Nem aktivering',
    INSTANT_CONNECTIVITY: 'Øjeblikkelig forbindelse med global dækning',
    ROUND_TRIP: 'Transport tur/retur',
    CULTURAL_EXPERIENCE: 'Autentiske kulturelle oplevelser',
    GUARANTEED_SEAT: 'Garanteret plads',
    ONBOARD_WIFI: 'Wi-fi og opladningsporte ombord',
    LUGGAGE_ASSISTANCE: 'Bagagehjælp',
    TOP_ATTRACTIONS: 'Med topattraktioner',
    FREQ_DEP_MULTI_ROUTE: 'Hyppige afgange på flere ruter',
    CHARGING: 'Opladningsstation',
    WIFI: 'Adgang til wi-fi',
    FnB: 'Mad og drikke sælges',
    LUXURY: 'Luksusoplevelse',
    FOOD_DRINK: 'Mad og drikke',
    PANAROMIC: 'Panoramaudsigt over de største seværdigheder',
    PANAROMIC_2: 'Panoramaudsigt',
    PANAROMIC_3: 'Panoramaudsigt under fri himmel',
    BEVERAGES: 'Drikkevarer ombord',
    GOURMET: 'Gourmetmiddag',
    GOURMET_2: 'Gourmetmiddag og -drikkevarer',
    NIGHTTIME: 'Fantastisk udsigt om aftenen',
    ROMANTIC: 'Romantisk atmosfære',
    TRANSFERS: 'Transport inkluderet',
    CERTIFIED_OP: 'Certificeret operatør',
    BIRD_EYE: 'Udsigt i fugleperspektiv',
    MULTI_JUMP: 'Flere springetider',
    EXTREME_ADV: 'Ekstremsport',
    PHOTO_OP: 'Fotomuligheder i flotte omgivelser',
    TOP_ATTRACTIONS_COVERED: 'De største omfattede seværdigheder',
    LOCAL_CULTURE: 'Oplev den lokale kultur',
    EXCLUSIVE_DISC: 'Eksklusive rabatter',
    EFFICIENT_PUBLIC_TRANSIT: 'Effektiv offentlig transport',
    FREQUENT_SERVICE: 'Hyppige afgange',
    PREBOOKING: 'Nem forudbestilling',
    LOCAL_CULTURE_IMM: 'Lokal kulturel fordybelse',
    DISCOVER_HIDDEN: 'Opdag skjulte steder',
    CITY_SIGHTSEEING: 'Sightseeing i byen',
    OFFBEAT_ADV: 'Anderledes eventyr',
    DRINK_DEALS: 'Drikkevaredeals',
    OFFBEAT_EXP: 'Anderledes oplevelse',
    MULTIPLE_VARIETIES: 'Flere sorter inkluderet',
    HIDDEN_GEMS: 'Skjulte perler og anderledes attraktioner',
    EXPLORE_LOCAL: 'Udforsk de lokale kvarterer',
    CUSTOMIZED_TREATMENTS: 'Brugertilpassede behandlinger',
    TRAINED_THERAPISTS: 'Uddannede behandlere',
    HOLISTIC_WELLNESS: 'Holistisk wellness',
    FLEXIBLE_DURATION: 'Fleksibel varighed',
    MULTI_BOAT: 'Flere bådmuligheder',
    SCENIC_ROUTES: 'Naturskønne ruter',
    HANDS_ON: 'Praktisk læring',
    CULTURAL_CULINARY: 'Kulturel og kulinarisk indsigt',
    EXPERT_HOSTS: 'Ekspertværter',
    ADVENTURE_EXPERIENCE: 'Eventyrlig oplevelse',
    EQUIPMENT: 'Udstyr inkluderet',
    SCENIC_FLYOVERS: 'Naturskønne overflyvninger',
    LIVE_COMMENTARY: 'Live-kommentator',
    BEST_AERIAL_VIEWS: 'Bedste udsigt fra luften',
    SAFE_CERT_OP: 'Sikker og certificeret operatør',
    HANDPICKED: 'Håndplukkede ture',
    EFFORTLESS: 'Nem planlægning',
    EXPERT_GUIDES: 'Ekspertguider. Unik indsigt',
    ALL_ATTR_ONE_CARD: 'Alle seværdigheder, ét kort',
    MULTI_CARD: 'Flere kortmuligheder',
    COST_EFF: 'Omkostningseffektivt og praktisk',
    BEST_PRICES: 'Toppriser',
    MULTI_TRANSPORT: 'Flere transportmuligheder',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Alle',
    POPULAR_SUBCATEGORY: 'Populære {0}',
    TOP_CATEGORY: 'De bedste {0}',
    ATTRACTIONS: 'Seværdigheder',
    ALL_SUBCATEGORY: 'Alle {0}',
    BROWSE_BY_CATEGORIES: 'Gennemse efter kategorier',
    TICKETS_FROM: 'Billetter fra',
    PRICE_LOW_HIGH: 'Pris (lav til høj)',
    PRICE_HIGH_LOW: 'Pris (høj til lav)',
    FILTERS: 'Filtre',
    RESET: 'Nulstil',
    APPLY: 'Anvend',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout bruger cookies til at forbedre din oplevelse på hjemmesiden, en byte ad gangen.',
    MOBILE: 'Cookierne arbejder.',
    LEARN_MORE: 'Få mere at vide.',
  },
  SHOW_UNAVAILABLE: 'Show ikke tilgængeligt',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Udvalgte nyheder',
    ALL_NEWS: 'Alle nyheder',
    MORE_READS: 'Mere læsemateriale',
    LOAD_MORE: 'Indlæs mere',
    TRAILERS: 'Trailere',
    GET_YOUR_TICKETS: 'Køb dine billetter',
    POPULAR_SHOWS: 'Populære shows',
    FEATURED: 'Udvalgte',
    RECENT_NEWS: 'Seneste nyheder',
    SHOW_MORE_ARTICLES: 'Vis flere artikler',
    COLLAPSE_ALL: 'Skjul alle',
    REVIEWS: 'Anmeldelser',
    SHOW_ALL_REVIEWS: 'Vis alle anmeldelser',
    MAILER: {
      HEADING: 'De bedste teatertilbud og -nyheder direkte i din indbakke',
      SUBHEADING:
        'Tilmeld dig vores mailingliste for at få de seneste nyheder og de bedste tilbud på teaterforestillinger.',
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: '{0} anmeldelser',
    REVIEWS_COUNT: '{0} anmeldelser',
    AWESOME: 'Fantastisk',
    GOOD: 'God',
    AVERAGE: 'Gennemsnitlig',
    POOR: 'Dårlig',
    TERRIBLE: 'Forfærdelig',
    REVIEW_BY_HEADOUT: 'Her er, hvad vi synes: Anmeldelse skrevet af Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Det siger folk om oplevelsen',
    MOST_RELEVANT: 'Mest relevant',
    RATING_HIGH_TO_LOW: 'Bedømmelse: høj til lav',
    RATING_LOW_TO_HIGH: 'Bedømmelse: lav til høj',
    CRITIC_REVIEWS: 'Anmelderne siger',
    USER_REVIEWS: 'Brugeranmeldelser',
    CONTRIBUTORS_REVIEW: 'Bidragyderens anmeldelse',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Privat transport',
    SHARED_TRANSFERS: 'Deletransport',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Book online',
        DESCRIPTION:
          'Book dine billetter online, og få en hurtig og bekvem bookingoplevelse.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Øjeblikkelig bekræftelse',
        DESCRIPTION:
          'Få øjeblikkelig bekræftelse på din booking af din lufthavnstransportbillet.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Praktisk afhentning',
        DESCRIPTION:
          'Undgå besværet med lange køer: Dit transportmiddel vil afvente din ankomst ved dit valgte opsamlingssted.',
      },
      DROP_OFF: {
        TITLE: 'Aflevering',
        DESCRIPTION: 'Kom hurtigt og komfortabelt frem til din destination.',
      },
    },
    SHARED_TRANSFERS_IN: 'Deletransport i {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      ' En komfortabel og billig transportmulighed for flere passagerer, der rejser til eller fra en lufthavn.',
    PRIVATE_TRANSFERS_IN: 'Privat transport i {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      ' En bekvem, personlig transportservice for enkeltpersoner eller små grupper, der omfatter en komfortabel, direkte tur til og fra en lufthavn.',
    ANYWHERE_IN_THE_CITY: 'Hvor som helst i byen',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Flere mulige køretøjer',
      FREE_CANCELLATION: 'Gratis afbestilling',
    },
    SEAMLESS_TRANSFERS: 'Nem, pålidelig transport i hele verden',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Vælg den bedste lufthavnstransport for dig',
    HASSLE_FREE_TRANSFER: 'Problemfri lufthavnstransport',
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Nem transport i {0} med',
    BUSES: 'busser',
    TRAINS: 'toge',
    PRIVATE_TAXIS: 'private taxaer',
    BUS_TRAIN: 'Bus/tog',
    PRIVATE_TAXI: 'Privat taxa',
    FROM: 'Fra',
    SELECT_PICKUP: 'Vælg afhentning',
    TO: 'Til',
    SELECT_DROPOFF: 'Vælg aflevering',
    ENTER_DESTINATION: 'Angiv din destination',
    ENTER_PICKUP: 'Angiv afhentningssted',
    PICKUP_DATE: 'Afhentningsdato',
    SELECT_DATE: 'Vælg dato',
    PICKUP_TIME: 'Afleveringstid',
    SELECT_TIME: 'Vælg klokkeslæt',
    GUEST: 'Gæst',
    GUESTS: 'Gæster',
    ADD_GUESTS: 'Tilføj gæster',
    ADULT_CHILD: 'Voksen/barn',
    EXPLORE_TRANSFERS: 'Se mere om transport m.m.',
    COMBOS_AND_EXTRAS: 'Kombinationstilbud og ekstratilbud',
    YOUR_RIDE_DOORSTEP: 'Transport helt til dørtrinnet',
    COMFORTABLE_RIDE:
      'Book nemt og bekvemt en privat taxa til og fra større lufthavne i {0}',
    TRUSTED_DRIVERS: 'Pålidelige chauffører',
    RIDES_24_7: 'Transport døgnet rundt',
    FLIGHT_TRACKING: 'Overvågning af fly',
    KNOW_MORE: 'Få mere at vide',
    RESERVE_YOUR_RIDE: 'Reservér din transport',
    TRANSFER_OPTIONS: 'Fundne transportmuligheder',
    TRANSFERS_AVAILABLE_PLURAL: '{0} transportmuligheder',
    TRANSFERS_AVAILABLE_SINGULAR: '1 transportmulighed',
    TRUSTED_PARTNERS: '35+ betroede partnere, {0}',
    WORLDWIDE: 'over hele verden',
    COMFORTABLE_RIDES: 'Behagelig transport',
    FREQUENT_DEPARTURES: 'Hyppige afgange',
    MULTIPLE_TRANSPORT_OPTIONS: 'Flere transportmuligheder',
    AND_MANY_MORE: 'Og meget mere',
    ADD_PICKUP_LOCATION: 'Tilføj afhentningssted',
    ADD_DROPOFF_LOCATION: 'Tilføj afleveringssted',
    SELECT_PICKUP_DATE_AND_TIME: 'Vælg afhentningsdato og -klokkeslæt',
    SELECT_A_DATE: 'Vælg en dato',
    TRAIN_STATION: 'Togstation',
    BUS_STOP: 'Busstoppested',
    ADD_RETURN: 'Tilføj returtransport',
    HEADS_UP: 'Tip!',
    ADDED_RETURN_TRIP: 'Du har tilføjet returtransport!',
    RETURN_NOTE: 'Bemærk, at vi viser returrejsens detaljer i de næste trin.',
    OKAY_I_UNDERSTAND: 'Okay, forstået.',
    SERVING_GUESTS: 'Vi betjener {0} i {1} over hele verden',
    GUESTS_COUNT: '220.000+ gæster',
    CITIES_COUNT: '55+ byer',
    PARNTER_WITH_BEST:
      'Vi samarbejder kun med de bedste partnere, så du er sikret en uforglemmelig oplevelse. Lad os om detaljerne, mens du læner dig tilbage, slapper af og nyder turen',
  },
  PC_EXP: {
    SHOW_INCL: 'Vis vigtig info og det, der er inkluderet',
    CLEAR: 'Fjern',
    ALL_EXPERIENCES: 'Alle oplevelser',
    FILTER_BY_CATEGORIES: 'Filtrer efter kategorier',
    CATEGORIES: 'Kategorier',
    COMBOS: {
      HEADING: 'Alt godt kommer i par. Ligesom vores sparekombinationer.',
      DESCRIPTOR_1: 'Sparedeals',
      DESCRIPTOR_2: 'Bedre rejseplanlægning',
    },
  },
  TOP: 'De bedste {0}',
  VIEW_CALENDAR: 'Se kalender',
  SHOWS_CALENDAR: 'Forestillingskalender',
  IN: 'i',
  SEATS: 'Pladser',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Guide til indhold',
    QUICK_INFORMATION: 'Hurtig information',
    PEAK: 'Højsæson',
    OFF_PEAK: 'Lavsæson',
    ADDRESS: 'ADRESSE',
    RECOMMENDED_DURATION: 'ANBEFALET VARIGHED',
    VISITORS_PER_YEAR: 'BESØGENDE PR. ÅR',
    NUMBER_OF_ENTRANCES: 'ANTAL INDGANGE',
    EXPECTED_WAIT_TIME_STANDARD: 'FORVENTET VENTETID - STANDARD',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE: 'FORVENTET VENTETID - SPRING KØEN OVER',
    UNESCO_YEAR: 'UNESCO-ÅR',
    ARCHITECTURE_STYLE: 'ARKITEKTURTYPE',
    TIMINGS: 'Tidspunkter',
    SIZE_HEIGHT: 'STØRRELSE/HØJDE',
    TICKETS: 'BILLETTER',
    FUN_FACTS: 'Fun facts',
    DID_YOU_KNOW: 'Vidste du det?',
    MORE_INTERESTING_FACTS: 'Flere interessante fakta',
    PLAN_YOUR_VISIT: 'Planlæg dit besøg',
    ALSO_KNOWN_AS: 'Også kendt som',
    FOUNDED_ON: 'Grundlagt den',
    FOUNDED_BY: 'Grundlagt af',
    FROM: 'Fra',
    CLOSED_TODAY: 'Lukket i dag',
    TODAY: 'I dag',
    CLOSED: 'Lukket',
    OPEN: 'Åben',
    LAST_ADMISSION: 'Sidste adgang',
    DAYS: 'Dage',
    BEST_TIME_TO_VISIT: 'Det bedste tidspunkt at besøge',
    WEEKDAY_VS_WEEKEND: 'Hverdag vs. weekend',
    PEAK_VS_LOW_SEASON: 'Højsæson vs. lavsæson',
    PLEASANT: 'Behagelig',
    CROWDED: 'Mange mennesker',
    VERY_CROWDED: 'Overfyldt',
    LOW_SEASON: 'Uden for sæsonen',
    MID_SEASON: 'Mellemsæson',
    PEAK_SEASON: 'Højsæson',
    TO: 'TIL',
    LOWER_TO: 'til',
    LAST_ENTRY: 'sidste adgang',
    SUBATTRACTIONS: 'Underordnede attraktioner',
    INCLUDED_WITH_TICKETS: 'Omfattet af {0}-billetter',
    INCLUDED_WITH_SOME_TICKETS: 'Omfattet af visse {0}-billetter',
    EXPLORE_ALL_POI_TICKETS: 'Udforsk billetter og ture i {0} og {1}',
    EXPLORE_PARENT_TICKETS: 'Udforsk billetter og ture i {0}',
    SELECT_YOUR_EXPERIENCE: 'Vælg din oplevelse',
    OPERATING_HOURS: 'Åbningstid',
    SEE_MORE: 'Se mere',
    MORE_INSIGHTS: 'Mere viden',
  },
  OFF_PERCENT: '{0} % rabat',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Salsplan',
    CAPACITY: 'Kapacitet: {0} pladser',
    WHATS_ON: 'Hvad er der på programmet?',
    CATEGORIES: 'Kategorier',
  },
  NEXT: 'Næste',
  PREVIOUS: 'Forrige',
  ITINERARY: {
    TAB: 'Rejseplan',
    HEADING: 'Plan for oplevelsen',
    VIEW_ITINERARY: 'Se planen',
    PASSES_BY_SECTION_HEADING: 'Kører forbi',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Højdepunkter',
      NEARBY_THINGS_TO_DO: 'Ting at lave i nærheden',
      THINGS_TO_DO: 'Ting at lave',
    },
    STOP_CARD: {
      TITLE: {
        START: 'STARTSTED',
        END: 'SLUTSTED',
        STARTING_POINT: 'STARTSTED',
        STOP: 'STOP',
        ENDING_POINT: 'SLUTSTED',
        PASSING_BY: 'KØRER FORBI',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} mulige startsteder',
        END: '{0} mulige slutsteder',
      },
    },
    GET_DIRECTION: 'Få rutevejledning',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} timer {1} minutter',
        WITHOUT_HOURS: '{0} minutter',
        WITHOUT_MINS: '{0} timer',
      },
      ATTRACTIONS_COUNT: '{0} seværdigheder',
      ACTIVITIES_COUNT: '{0} aktiviteter',
      TOTAL_DURATION: 'SAMLET VARIGHED',
      FREQUENCY: 'HYPPIGHED',
      FIRST_DEPARTURE: 'FØRSTE AFGANG',
      LAST_DEPARTURE: 'SIDSTE AFGANG',
      FIRST_DEPARTURE_TIME: 'FØRSTE AFGANG KL.',
      LAST_DEPARTURE_TIME: 'SIDSTE AFGANG KL.',
      MODE_OF_TRANSPORT: 'TRANSPORTMIDDEL',
      FOOD_AND_DRINKS: 'MAD OG DRIKKE',
    },
    WALK_DURATION: '{0} minutters gang',
    MORE: '{0} flere',
    TIMELINE_VIEW: 'Tidsoversigt',
    MAP_VIEW: 'Kort',
    MAP_OVERLAY: 'Brug CTRL/⌘ + scroll til at bevæge kortet',
    VIEW_EXPERIENCE_MAPPED_OUT: 'Se en komplet oversigt over din oplevelse.',
    OPEN_MAP_VIEW: 'Åbn kort',
    START_POINT_SAME_AS_END_POINT:
      'Dit slutsted ville blive det samme som dit startsted',
  },
  CRUISES: {
    BANNER_HEADING: 'Krydstogt gennem {0} – oplevelser, god mad og afslapning',
    FILTERS: {
      ALL: 'Alle',
      SIGHTSEEING: 'Sightseeing',
      LUNCH: 'Frokost',
      DINNER: 'Middag',
      COMBOS: 'Kombinationstilbud',
    },
    MAP_OVERLAY: 'Klik eller tryk for at bevæge dig rundt på kortet',
    SIGHTS_COVERED: 'Omfattede seværdigheder',
    MENU: 'Menu',
    BOARD_AT: 'Gå om bord kl. {0}',
    BOARDING_POINTS_AVAILABLE: '{0} muligheder',
    VIEW_POPULAR_SIGHTS: 'Se populære seværdigheder såsom {0} {1}',
    X_BOARDING_POINTS: '{0} påstigningssteder',
    BOARDING_POINT: 'Påstigningssted',
    BOARDING_POINTS: 'Påstigningssteder',
    LANDMARKS: 'Vartegn',
    GET_DIRECTIONS: 'Få rutevejledning',
    FOOD_MENU: 'Menu, madvarer',
    X_PAGE: '{0} side',
    X_PAGES: '{0} sider',
    MORE: '+{0} flere',
    PDF: {
      ZOOM_IN: 'Zoom ind',
      ZOOM_OUT: 'Zoom ud',
      FIT_TO_WIDTH: 'Tilpas til bredden',
      RESET_ZOOM: 'Nulstil zoom',
    },
    COMBO_HEADING: 'Betal mindre for mere: kombinationstilbud og city-kort',
  },
  CUSTOM_CTA_EXPERIMENT_TEXT: 'Tjek tilgængelighed',

  CITY_AIRPORT_TRANSFERS: 'Transport til/fra lufthavnen i {0}',
  BANNER_SUBTEXT:
    'Book pålidelig transport til/fra lufthavnen på forhånd, og minimer rejsestressen.',
  BEST_PRICES: 'De bedste priser, uden skjulte gebyrer',
  BEST_PRICES_SUBTEXT:
    'Faste, konkurrencedygtige priser for god service, uden overraskelser.',
  FREE_WAIT_TIME: 'Gratis ventetid, så du ikke skal stresse',
  FREE_WAIT_TIME_SUBTEXT:
    'Takket være vores 45 minutters gratis ventetid behøver du ikke at kigge på uret hele tiden, mens du venter på bagagebåndet',
  COMFORTABLE_RIDE: 'Behagelig transport',
  COMFORTABLE_RIDE_SUBTEXT:
    'Nyd komforten i en af de mange eksklusive køretøjer, der køres af udvalgte, uddannede chauffører.',
  EXCELLENCE_HEADING: 'En pålidelig partner, der leverer varen',
  ACTIVE_CITIES: 'aktive byer i hele verden',
  CUSTOMERS_SERVED: 'betjente kunder',
  YEARS_OF_SERVICE: 'år med fremragende service',
  FIND_YOUR_RIDE: 'Find din perfekte transportmulighed',
  FIND_YOUR_RIDE_SUBTEXT:
    'Vælg en bil, der passer til jeres bagage og antal personer: Vi har alt lige fra minibusser til luksuriøse sedaner',
  TRUST_TOOLTIP_HEADER: 'Hvordan indsamler vi anmeldelser?',
  TRUST_TOOLTIP_CONTENT:
    'Vurderingerne omfatter verificerede anmeldelser fra både Headout-gæster og vores betroede partnere, der driver oplevelsen lokalt. Alle anmeldelser kommer fra rigtige rejsende, der har deltaget i oplevelsen.',
  REVIEW_SECTION_HEADER: 'Hvad vores gæster siger',
  TRUST_VB_TAG: 'Bekræftet booking',
  SNAPSHOTS_SECTION_HEADER: 'Snapshots fra vores gæster',
  AGGREGATED_COUNTRIES:
    'Gæster fra <strong>{0}</strong> og <strong>over {1} andre lande</strong> var vilde med denne oplevelse',
  REVIEW_SECTION: {
    HEADING: 'Millions love heading out with us',
    SORTING: {
      MOST_RELEVANT: 'Mest relevant',
      MOST_RECENT: 'Seneste',
      SORT_BY: 'Sortér efter',
    },
    FILTERING: {
      GREATER_THAN_4: '4+ stjerner',
      EQUAL_TO_3: '3 stjerner',
      LESS_THAN_3: '< 3 stjerner',
      WITH_IMAGES: 'Med billeder',
    },
    EMPTY_STATE: {
      SUB_HEADING:
        'Vi kunne ikke finde nogen anmeldelser, der passer til dine filtre.',
      CTA: 'Vis alle anmeldelser',
    },
    VERIFIED_REVIEW: 'Verificeret partneranmeldelse',
  },
  POWERED_BY: 'fra',
};

export default da;
