const de = {
  AUDIO_GUIDE: {
    BANNER: 'Gratis Audioguide',
    PRODUCT_SUFFIX: '+ Audioguide',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Autorisierter und zuverlässiger Partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Autorisierter Reseller',
    SUB_TEXT: 'Erlebnisse von verifizierten Partnern.',
  },
  AVAILABLE: 'Verfügbar',
  BANNER_CTA: 'Tickets kaufen',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout ist ein Unternehmen, dem weltweit Millionen von Gästen vertrauen und das ausgewählte Erlebnisse für diese Attraktion anbietet.',
    NON_PARTNERED_SENSITIVE:
      'Headout ist ein Unternehmen, dem weltweit Millionen von Gästen vertrauen und das ausgewählte Erlebnisse für diese Attraktion anbietet. Dies ist nicht die Website des Erlebnisortes.',
    PARTNERED_NON_SENSITIVE:
      'Headout ist ein autorisierter und zuverlässiger Partner des Veranstaltungsortes, der ausgewählte Erlebnisse für diese Attraktion anbietet.',
    PARTNERED_SENSITIVE:
      'Headout ist ein autorisierter und zuverlässiger Partner des Veranstaltungsortes, der ausgewählte Erlebnisse für diese Attraktion anbietet. Dies ist nicht die Website des Veranstaltungsortes.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout ist ein autorisierter und zuverlässiger Partner der Attraktion mit einer Auswahl der besten Erlebnisse.',
  BOOK_NOW_CTA: 'Jetzt buchen',
  BUY_TICKETS_CTA: 'Tickets kaufen',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Sie können diese Tickets bis zu {0} Stunden vor Erlebnisbeginn stornieren, um eine vollständige Rückerstattung zu erhalten.',
    CANCELLABLE_ANYTIME: 'Kostenfreie Stornierung vor Beginn Ihres Erlebnisses',
    CANCELLABLE_DAYS:
      'Sie können diese Tickets bis zu {0} Tage vor Beginn des Erlebnisses für eine volle Rückerstattung stornieren.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Diese Tickets können nicht storniert werden. Sie sind jedoch für einen längeren Zeitraum gültig.',
    HEADING: 'Änderungsrichtlinie',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Diese Tickets können nicht storniert werden. Sie können jedoch bis zu {0} Stunden vor Erlebnisbeginn verschoben werden.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Diese Tickets können nicht storniert oder verschoben werden.',
    VALID_UNTIL_DATE:
      'Diese Tickets können nicht storniert werden. Sie können jedoch bis zum {0} verwendet werden.',
    VALID_WITHIN_NEXT_DAYS:
      'Diese Tickets können nicht storniert werden. Sie können jedoch jederzeit innerhalb der nächsten {0} Tage verwendet werden.',
    VALID_WITHIN_NEXT_MONTHS:
      'Diese Tickets können nicht storniert werden. Sie können jedoch jederzeit innerhalb der nächsten {0} Monate verwendet werden.',
  },
  CANCELLATION_POLICY_HEADING: 'Stornierungsfrist',
  CASHBACK: '{0} % Cashback',
  CASHBACK_INFO:
    'Sie erhalten <strong>{0} %</strong> Cashback, wenn Sie dieses Erlebnis buchen. Ihr Cashback wird automatisch Ihrem Headout-Konto gutgeschrieben und kann für zukünftige Buchungen mit Headout verwendet werden.',
  CATEGORY_SLIDER_HEADING:
    'Was sich Zuschauer dieser Show noch angesehen haben',
  CHECK_AVAIL: 'Verfügbarkeit prüfen',
  CITY_PAGE: {
    BANNER_TITLE: 'Erleben Sie die Highlights von',
    TOP_ATTRACTIONS: 'Top-Attraktionen',
    GO_BEYOND: 'Ausflüge von {0}',
    ALL_DAY_TRIPS: 'Alle Tagesausflüge',
    CITIES_NEARBY: 'Städte in der Nähe',
    POPULAR_CATEGORIES: 'Beliebte Kategorien',
    GO_TO_GUIDE: 'Ihr {0} Reiseführer',
    VIEW_TRAVEL_GUIDE: 'Reiseführer anzeigen',
    EXPLORE: '{0} entdecken',
    GUIDE_SUBHEADING:
      'Noch nie war es so einfach, Sehenswürdigkeiten in {0} zu erkunden! In unserem Reiseführer finden Sie alles, was Sie über {0} wissen müssen – von kulinarischen Geheimtipps bis zu Unterkünften und Anreisemöglichkeiten zu beliebten Wahrzeichen.',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Allgemeines',
      WHERE_TO_EAT: 'Kulinarisches',
      WHERE_TO_STAY: 'Unterkünfte',
      THINGS_TO_DO: 'Erlebnisse',
      WEATHER: 'Beste Reisezeit',
      NEIGHBOURHOODS: 'Stadtviertel',
      TRANSPORTATION: 'Nahverkehr',
      TRIP_PLANNER: 'Reiseplan',
      FAMILY_TRAVEL: 'Reisen mit Kindern',
      TRAVEL_TIPS: 'Reisetipps',
      SHOPPING: 'Shoppen',
      ART_AND_CULTURE: 'Kunst und Kultur',
    },
    MAILER: {
      HEADING:
        'Inspirationen für Ihre Reise nach {0} direkt zu Ihrem Posteingang',
      SUBHEADING:
        'Die besten Erlebnisse, Spartipps, Restaurants, Hotels, Infos zum ÖPNV und zu kulturellen Highlights finden Sie hier!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Visabestimmungen, Geldwechsel, Zeitzonenunterschiede und mehr – wichtige Infos für eine reibungslose Ankunft und einen angenehmen Aufenthalt.',
    WHERE_TO_EAT:
      'Kulinarische Köstlichkeiten, exquisite Aromen und lokale Spezialitäten erwarten Sie in {0} an jeder Ecke.',
    WHERE_TO_STAY:
      'Hier finden Sie die besten Unterkünfte für einen bequemen und unvergesslichen Aufenthalt in {0}.',
    THINGS_TO_DO:
      'Spannende Aktivitäten und Attraktionen für Groß und Klein sorgen für eine unvergessliche Zeit.',
    WEATHER:
      'Hier finden Sie wichtige Infos für Ihre Reiseplanung, denn {0} hat das ganze Jahr über zauberhafte Erlebnisse zu bieten.',
    NEIGHBOURHOODS:
      'Entdecken Sie die verschiedenen, lebhaften Viertel, die {0} so besonders machen.',
    TRANSPORTATION:
      'Mit dem öffentlichen Nahverkehr gelangen Sie in {0} schnell und bequem von einer Attraktion zur nächsten.',
    TRIP_PLANNER:
      'Mit unseren sorgfältig ausgewählten Reiseplänen nutzen Sie Ihre Zeit in {0} optimal aus und können jeden Moment vollkommen genießen.',
    FAMILY_TRAVEL:
      'Familienfreundliche Abenteuer mit zahlreichen Attraktionen, Parks und Unterhaltungsmöglichkeiten für alle Altersklassen erwarten Sie.',
    TRAVEL_TIPS:
      'Insider-Tipps und Reise-Hacks garantieren eine außergewöhnliche Reise nach {0}.',
    SHOPPING:
      'Ein Einkaufsparadies mit Boutiquen, Märkten und Einkaufszentren – von lokalem Kunsthandwerk bis zu hochwertiger Mode.',
    ART_AND_CULTURE:
      'Erkunden Sie die reiche Kunst- und Kulturszene von {0} – von faszinierenden Museen bis hin zu lebhaften Festivals.',
  },
  CLOSE: 'Schließen',
  COLLECTION_SLICE_HEADING: 'Top-Erlebnisse in {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Auswählen',
    SELECT_PREFERENCE: 'Wählen Sie die gewünschte Ticketvariante aus',
    SELECT_OPTION: 'Gewünschte Ticketvariante wählen',
    SELECT_TICKET: 'Ticket wählen',
  },
  COMPARE_ALL_DETAILS: 'Alle vergleichen',
  COVID19_ALERT: {
    KEY_TEXT: 'Corona-Update',
    LINK:
      'https://medium.com/headout/coronavirus-ausbruch-stornierungsbedingungen-cec74ac7641b',
    TEXT:
      'Ihr Wohlergehen ist unsere Priorität. Weitere Informationen zu unseren flexiblen Stornierungsbedingungen finden Sie auf der Seite „Hilfe & FAQs“.',
  },
  CURRENCY: 'Währung',
  CUSTOMER_REVIEW_HEADING: 'Zuschauerbewertungen',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioguide',
    DURATION: 'Dauer: {0}',
    EXTENDED_VALIDITY: 'Verlängerte Gültigkeit',
    FLEXIBLE_DURATION: 'Flexible Dauer',
    FREE_CANCELLATION: 'Kostenlose Stornierung',
    GUIDED_TOUR: 'Geführte Tour',
    HOTEL_PICKUP: 'Hotel-Abholung',
    INSTANT_CONFIRMATION: 'Sofortbestätigung',
    MEALS_INCLUDED: 'Inkl. Mahlzeit',
    MOBILE_TICKET: 'Digitale Tickets',
    SKIP_THE_LINE: 'Schnelleinlass',
    TRANSFERS: 'Transfer inklusive',
  },
  DURATION: 'Dauer',
  EARLIEST_AVAILABILITY: 'Früheste verfügbare',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Geben Sie hier Ihre E-Mail-Adresse ein',
    SIGN_UP: 'Anmelden',
    THANK_YOU: 'Vielen Dank!',
    SUBSCRIBED_MSG: 'Sie sind jetzt angemeldet.',
    ERROR_MSG: 'Bitte eine gültige E-Mail-Adresse eingeben.',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Broadway Theater Tickets',
    },
    LTT: {
      MB_NAME: 'London Theater Tickets',
    },
  },
  EXCLUSIONS: 'Nicht enthalten',
  FEATURE_CARD: {
    HEADING_CUSTOMER: 'Über 10 Millionen',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100 % sicher',
    HEADING_SUPPORT: '24-Stunden Support',
    SUB_HEADING_CUSTOMER: 'zufriedene Kunden bei mehr als 10.000 Erlebnissen',
    SUB_HEADING_RATING:
      'Über 5.000 geprüfte Rezensionen mit 90 % ausgezeichneten Bewertungen',
    SUB_HEADING_SAFE: 'Alle Outdoor-Aktivitäten sind 100 % sicher',
    SUB_HEADING_SUPPORT:
      'Haben Sie Fragen? Nutzen Sie unseren Live-Chat, jederzeit und überall',
  },
  FLEXIBLE: 'Flexibel',
  FOOTER: {
    CALL_US: 'Telefon',
    CHAT_WITH_US: 'Live-Chat',
    COMPANY_DETAILS: 'Unternehmensangaben',
    INFORMATION: 'Informationen',
    GMAPS_DISCLAIMER:
      'Alle Screenshots von Karten, die auf dieser Seite zu finden sind, stammen von Google in Übereinstimmung mit dem Fair Use-Prinzip. Alle Rechte an diesen Screenshots liegen bei der jeweiligen Plattform und ihre Verwendung dient ausschließlich zu Informations- und Orientierungszwecken.',
    DISCLAIMER:
      'Diese Website ist nicht die offizielle Website <attraction>. Die Website wird vom Unternehmen Headout betrieben, das mit Veranstaltern für Attraktionen und Touren zusammenarbeitet, um unglaubliche Erlebnisse auf Knopfdruck anzubieten.',
    EMAIL_US: 'E-Mail',
    GET_HELP: 'Hilfe',
    LEGAL: 'Rechtliches',
    PRIVACY_POLICY: 'Datenschutzrichtlinie',
    QUICK_LINKS: 'Quick Links',
    TERMS_AND_CONDITIONS: 'AGB',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Made with ',
    ALL_OVER_THE: ' all over the ',
  },
  FREE_CANCELLATION: 'Kostenlose Stornierung',
  FREE_CANCELLATION_SUBTEXT:
    'Stornierungen sind bis zu 72 Std. im Voraus möglich.',
  FROM: 'ab',
  GET_CASHBACK: '{0} % Cashback sichern',
  GROUP_TICKETS: 'Gruppentickets',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: 'Über 20 Mio. Kunden',
    SUB_TEXT: 'Ihre Zufriedenheit ist unsere oberste Priorität.',
  },
  HELP_CENTER: {
    MAIN_TEXT: '24-Std. Support',
    SUB_TEXT: 'Wir sind rund um die Uhr für Sie erreichbar.',
  },
  INCLUSIONS: 'Inklusive',
  LANGUAGE: 'Sprache',
  LISTICLES: {
    KNOW_MORE: 'Weitere Infos',
    SEATING_CHART: 'Saalplan',
    WHY_BOOK_FROM_US: 'Unsere Vorteile?',
  },
  MORE_DETAILS: 'Mehr anzeigen',
  MORE_CURRENCIES: 'Weitere Währungen',
  NEW: 'NEW',
  NEW_ARRIVAL: 'Neuerscheinungen',
  NEXT_AVAILABLE: 'Verfügbar ab: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout ist ein Unternehmen, dem über 15 Millionen Gäste vertrauen und das eine Auswahl der besten Erlebnisse bietet. Dies ist nicht die Website des Erlebnisortes.',
  NO_RESULT_FOUND: 'Keine Ergebnisse gefunden',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR: 'Flexibel buchen – keine Terminsauswahl nötig',
  OPENING_DATE: 'Eröffnungsdatum',
  OPENING_ON: 'Eröffnung am',
  OPENS: 'Ab',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout ist ein autorisierter und zuverlässiger Partner der Attraktion mit einer Auswahl der besten Erlebnisse. Dies ist nicht die Website der Attraktion.',
  POPULARITY: 'Beliebtheit',
  POPULAR_CURRENCIES: 'Beliebte Währungen',
  PRICE: 'Preis',
  PRICES_STARTING: 'Preise ab',
  PROMO_CODES: {
    APPLY_CODE: 'CODE ANWENDEN',
    APPLIED: 'ANGEWANDT',
    TOOL_TIP_INFO: 'Der Rabatt wird an der Kasse angewandt',
    DESCRIPTION: {
      ABSOLUTE: '{0} Rabatt sichern',
      CAPPED: '{0} % Rabatt für bis zu {1}',
      PERCENTAGE: '{0} % Rabatt sichern',
    },
    REMOVE: 'ENTFERNEN',
  },
  RATINGS: '{0} Bewertungen',
  READ_MORE: 'Weiterlesen',
  READ_MORE_TEXT: 'Mehr anzeigen',
  READ_LESS: 'Weniger anzeigen',
  VIEW_DETAILS: 'Details anzeigen',
  REOPENING: 'Wiedereröffnung',
  REOPENING_DATE: 'Wiedereröffnungsdatum',
  REOPENING_ON: 'Neueröffnung am',
  REOPENS: 'Endlich wieder ab',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT:
        'Es gilt die 2G-Regel: Der Zugang zu Unterkünften, Kultureinrichtungen, Restaurants, Bars usw. ist nur mit einem Impf- oder Genesungsnachweis möglich. Ein negativer Covid-19-Test ist nicht mehr ausreichend.',
    },
    AU_DESCRIPTION: {
      TEXT:
        'Besucher ab 16 Jahren müssen eine COVID-19-Impfung oder eine medizinische Ausnahmegenehmigung vorweisen.',
    },
    BANNER_CTA: 'Weitere Infos',
    BERLIN_DESCRIPTION: {
      TEXT:
        'Es gilt die 2G-Regel: Nur vollständig geimpfte und genesene Besucher mit entsprechendem Nachweis haben Zutritt. Personen unter 18 Jahren oder solche, die aus medizinischen Gründen nicht geimpft werden können, müssen am Eingang ein negatives COVID-Testergebnis sowie einen medizinischen Nachweis über die Impfunfähigkeit vorlegen.',
    },
    CTA_TEXT: 'Sicherheitsvorkehrungen',
    DESCRIPTION_CTA: 'Weitere Infos.',
    EU_DESCRIPTION: {
      TEXT:
        'Ab dem 21. Juli müssen alle Besucher ab 12 Jahren ein COVID-Zertifikat der EU vorlegen.',
    },
    EU_HEADING: 'COVID-Zertifikat der EU erforderlich',
    EU_PREFIX: 'Hinweis: ',
    EXPERIENCE_DESCRIPTION:
      'Dieses Erlebnis entspricht nachweislich den besten Sicherheitsstandards in Übereinstimmung mit den örtlichen Vorschriften und der WHO.',
    FLAG_TEXT: 'Nachweislich sicher',
    GENERAL_DESCRIPTION:
      'Erlebnisse mit diesem Abzeichen halten nachweislich die besten Sicherheitsstandards gemäß den Gesundheitsrichtlinien der örtlichen Regierung ein.',
    HEADING: 'Beste Sicherheitsstandards',
    IT_DESCRIPTION: {
      TEXT:
        'Ab dem 6. August müssen alle Besucher über 11 Jahren einen Grünen Pass oder ein COVID-Zertifikat der EU vorlegen',
    },
    IT_PREFIX: 'Hinweis: ',
    MOBILE_HEADING: 'Sichere Erlebnisse',
    MODAL: {
      BADGE_DESCRIPTION:
        'Erlebnisse mit diesem Abzeichen entsprechen nachweislich den von der Attraktion geprüften Sicherheitsstandards.',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Alle Geräte, Fahrzeuge und häufige Einsatzbereiche werden nach jeder einzelnen Nutzung desinfiziert. Genießen Sie ein sicheres Erlebnis.',
          HEADING: 'Zubehör und Oberflächen werden desinfiziert',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Jegliches Ausrüstungszubehör, das Ihnen bei Ihrem Erlebnis zur Verfügung steht, wird nach jeder Nutzung gründlich desinfiziert – immer und jedes Mal.',
          HEADING: 'Zubehör- und Oberflächendesinfizierung',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Alle Fahrzeuge, die Ihnen bei Ihrem Erlebnis zur Verfügung stehen, werden nach jedem Einsatz gründlich desinfiziert. Immer und jedes Mal',
          HEADING: 'Alle Fahrzeuge werden desinfiziert',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Bei Sicheren Erlebnissen haben Sie die ganze Zeit über Zugang zu Handwasch- und Sanitärstationen. Für Ihre Sicherheit ist gesorgt. ',
          HEADING: 'Sanitäreinrichtungen und Handwaschbecken überall verfügbar',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Alle Gäste und Mitarbeiter müssen bei diesem Erlebnis eine Maske tragen. Auf diese Weise kann jeder das Erlebnis mit höchster Sicherheit genießen.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Unsere Partner, die nachweislich sichere Erlebnisse anbieten, halten sich an die örtlichen Vorschriften bezüglich der Maskenpflicht. Wenn es vorgeschrieben ist, werden alle Gäste und Mitarbeiter Masken tragen. Es werden jegliche Schritte unternommen, um Ihre Sicherheit und Zufriedenheit zu gewährleisten.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Alle Gäste müssen bei diesem Erlebnis eine Maske tragen. Auf diese Weise kann jeder das Erlebnis mit höchster Sicherheit genießen.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Bei diesem Erlebnis tragen alle Mitarbeiter eine Maske, damit Sie den ganzen Spaß sorglos genießen können.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Die Abstandsregelungen werden während des gesamten Erlebnisses eingehalten. Zur Einhaltung des Sicherheitsabstandes ist die Besucherkapazität beschränkt.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Die Abstandsregelungen werden während des gesamten Erlebnisses eingehalten. Zur Einhaltung des Sicherheitsabstandes ist die Besucherkapazität beschränkt und der Eintritt für größere Gruppen untersagt.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Die Abstandsregelungen werden bei diesem Erlebnis jederzeit eingehalten.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Die Abstandsregelungen werden bei diesem Erlebnis jederzeit eingehalten. Zur Einhaltung können Kapazitäten und Gruppengrößen beschränkt werden. Hier können Sie aufatmen.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Die Abstandsregelungen werden während des gesamten Erlebnisses eingehalten. Angesichts dessen ist der Eintritt für größere Gruppen untersagt.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Um die Sicherheit für alle zu gewährleisten, wird bei jedem Gast zu Beginn des Erlebnisses Fieber gemessen. Darüber hinaus wird auch bei allen Mitarbeitern mehrmals täglich Fieber gemessen.',
          HEADING: 'Fiebermessung vor Ort',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Um die Sicherheit für alle zu gewährleisten, wird bei jedem Gast zu Beginn des Erlebnisses Fieber gemessen. ',
          HEADING: 'Fiebermessung vor Ort',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Fiebermessungen werden mehrfach bei allen Mitarbeitern durchgeführt. Mitarbeiter mit einer Temperatur über dem vorgeschriebenen Grenzwert haben keinen Zutritt und werden gebeten, sich zu Hause auszukurieren.',
          HEADING: 'Fiebermessung vor Ort',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Die Mitarbeiter, die während des gesamten Erlebnisses zur Verfügung stehen, sind gemäß den WHO-Richtlinien geschult und auf alle möglichen Notfälle vorbereitet.',
          HEADING: 'Auf WHO-Richtlinien geschultes Personal',
        },
      },
      HEADING: 'Sichere Erlebnisse',
      SUB_HEADING:
        'Wir arbeiten mit unseren Partnern auf der ganzen Welt zusammen, um die besten Sicherheitsstandards gemäß den WHO-Richtlinien umzusetzen. Alle vor Ort getroffenen Maßnahmen wurden überprüft und werden hier angezeigt. Es ist an der Zeit, dass wir unsere Welt wieder genießen.',
    },
    NL_DESCRIPTION: {
      TEXT:
        'Besucher ab 13 Jahren müssen ein COVID-Zertifikat (in digitaler oder gedruckter Form) vorlegen, aus der hervorgeht, dass sie geimpft wurden, ein negatives Testergebnis erhalten haben oder genesen sind. Zudem gilt die Maskenpflicht.',
    },
    SG_DESCRIPTION: {
      TEXT:
        'Seit dem 13. Oktober 2021 können nur noch vollständig geimpfte Besucher in 2er-Gruppen eintreten. Vor dem Einlass muss ein Impf- oder Genesungsnachweis bzw. ein negatives COVID-19-Testergebnis vorgelegt werden.',
    },
    SHORT_HEADING: 'Beste Sicherheitsstandards vor Ort',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Your safety is our priority',
    TEXT:
      "We've taken significant steps to improve cleanliness using disinfectants with comprehensive and frequent surface cleaning. Crowds are also being controlled to prevent congestion.",
  },
  SAVE: '{0} % Rabatt',
  SAVE_PERCENT: '{0} % Rabatt',
  SAVE_UPTO: 'Spare',
  SAVE_UPTO_PERCENT: 'Bis zu {0} % Rabatt',
  SEARCH: 'Suchen',
  SEE_ALL: 'See All',
  SEE_MORE_SHOWS: 'Weitere Shows anzeigen',
  SELECT_CITY: 'Stadt auswählen',
  SELECT_SECTION: 'Tribüne wählen',
  SEE_ALL_PHOTOS: 'Alle Fotos anzeigen',
  SHOW_CLOSED: 'Show geschlossen',
  SHOW_LESS_TEXT: 'Weniger anzeigen',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Die Show',
    ABOUT_THEATRE: 'Das Theater',
    ADDITIONAL_INFORMATION: 'Zusätzliche Informationen',
    AGE_LIMIT: 'Altersbeschränkung',
    AGE_SUITABILITY: 'Altersempfehlung',
    ANSWER: ['A-'],
    BLOG_SHOW_PAGE: 'Blog Show Page',
    BLOG_SUMMARY: 'Blog Zusammenfassung',
    BLOG_THEATRE_PAGE: 'Blog Theater Seite',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Theatersitzplan',
    CANCELLATION_AND_REFUNDS: 'Stornierung und Rückerstattung',
    CANCELLATION_POLICY: 'Stornierungsfrist',
    CAST_AND_CREW: 'Besetzung und Crew',
    CLOSING_DATE: 'Dernière',
    CLOSING_DATE_SPECIAL_OFFER: 'Dernière Sonderangebot',
    DURATION: 'Dauer',
    FACILITIES_AND_ACCESSIBILITY: 'Einrichtungen und Barrierefreiheit',
    FREQUENTLY_ASKED_QUESTIONS: 'Häufig gestellte Fragen',
    GETTING_THERE: 'Wegbeschreibung',
    GETTING_THERE_MAP_LINK: 'Wegbeschreibung Kartenlink',
    GOOGLE_MAP: 'Google Maps',
    HIGHLIGHTS: 'Highlights',
    LISTICLE_SHOW_SUMMARY: 'Listicle Show Zusammenfassung',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Show Highlights',
    OPENING_DATE: 'Premiere',
    QUESTION: ['F-'],
    SAFETY_BANNER: 'Sicherheitsbanner',
    SHOW_DETAILS: 'Details zur Show',
    SHOW_TIMINGS: 'Showzeiten',
    SHOW_TYPE: 'Art der Show',
    SPECIAL_OFFER: 'Sonderangebot',
    THE_STORY: 'Die Handlung',
    THEATRE_ADDRESS: 'Adresse',
    THEATRE_CAPACITY: 'Kapazität',
    THEATRE_NAME: 'Theater',
    TICKETS: 'Tickets',
    TICKETS_REDEMPTION: 'Ticket-Einlösung',
    TOP_SONGS: 'Top Songs',
    YOUR_TICKETS: 'Ihre Tickets',
    ABOUT_CONCERT: 'Das Konzert',
    PROGRAM: 'Programm',
  },
  SORT_BY: 'Sortieren nach',
  THEATRE: 'Theater',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Theater in der Nähe',
    NOW_PLAYING: 'Aktuelle Shows',
    PAST_SHOWS: 'Vergangene Shows',
    FIND_BEST_SEATS: 'Bestplätze finden',
  },
  SPECIAL_OFFER: 'Sonderangebot',
  TICKET_CAN_BE_CANCELED:
    'Dieses Ticket kann bis zu {hours} Stunden vor dem Erlebnis gegen eine volle Rückerstattung storniert werden.',
  TICKET_CANNOT_BE_CANCELED:
    'Dieses Ticket kann nicht storniert, aber auf Anfrage verschoben werden.',
  TICKETS: 'Tickets',
  TIMINGS: 'Zeiten',
  SPECIAL_PRODUCT_HEADING: 'Beliebtestes Erlebnis',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Lokale Experten',
    ENGAGING_STORIES: 'Packende Stories',
    TOP_RATED: 'Top-Bewertungen',
  },
  GUIDED_TOUR_REVIEWS: [
    'Der Reiseleiter war sehr froh, Fragen über die Tour zu beantworten',
    'Die Organisation und unser Führer machten die Erfahrung sehr angenehm',
    'Die Tour war gut organisiert und hatte auch genau die richtige Dauer',
    'Gute Führung und gute Organisation! Werde ich weiterempfehlen!!!',
    'Die Tour verlief in einem guten Tempo und fühlte sich nicht gehetzt an',
    'Unsere Führerin Maria konnte uns die besten Aussichtspunkte besorgen',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Englisch',
    SPANISH: 'Spanisch',
    FRENCH: 'Französisch',
    ITALIAN: 'Italienisch',
    GERMAN: 'Deutsch',
    PORTUGUESE: 'Portugiesisch',
    NEDERLANDS: 'Niederländisch',
    POLISH: 'Polnisch',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Tour verfügbar in {0}',
  GUIDES_BANNER: 'Authentische Erlebnisse mit unseren beliebten Reiseleitern.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Mit geführten Touren machen Sie das Beste aus Ihrer Reise. Unsere fachkundigen Reiseleiter sind Ihre Freunde vor Ort und verraten Ihnen Geschichten, Insidertipps und Reiseempfehlungen.',
    'Besuchen Sie eine Stadt nicht nur – erleben Sie sie!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Das sagen Reisende',
  TODAY: 'heute',
  TOMORROW: 'morgen',
  TOUR_LIST_HEADING: 'Wählen Sie Ihr Erlebnis',
  TOUR_LIST_SUB_HEADING:
    'Hier finden Sie zahlreiche Tickets, Touren und Kombinationen von geprüften Anbietern:',
  UGC: {
    FOLLOW: 'Folgen',
    FOLLOW_IG: 'Auf Instagram folgen',
    HEADING: 'POV: Dein nächstes Abenteuer sieht so aus',
    SUB_HEADING: 'Mit 💜 von Headout kuratiert',
  },
  UNAVAILABLE: 'Nicht verfügbar',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Diese Tickets sind für einen längeren Zeitraum gültig. Genaue Angaben befinden sich auf dem Ticket.',
    UNTIL_DATE: 'Diese Tickets sind bis zum {0} gültig.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Diese Tickets sind ab dem Kaufdatum {0} Tage gültig.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Diese Tickets sind ab dem Kaufdatum {0} Monate gültig.',
  },
  TABLE_OF_CONTENTS: 'Inhaltsverzeichnis',
  VIEW_LESS: 'Weniger anzeigen',
  VIEW_MORE: 'Mehr anzeigen',
  WHY_TAKE_THIS_DAY_TRIP: 'Die Vorteile dieses Tagesausflugs',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Hauptmenü',
    EXPLORE: 'Entdecken',
    VISIT: 'Besuchen',
    THINGS_TO_DO: 'Erlebnisse',
    CITY_ATTRACTIONS: '{0} Sehenswürdigkeiten',
    TOP_THINGS_TO_DO: 'Top-Erlebnisse',
    CITY_TOURS: '{0} Touren',
    CITY_GUIDE: 'City Guide',
    ATTRACTIONS: 'Attraktionen',
    CRUISES: 'Schifffahrten',
    THEMES: 'Themen',
    ABOUT: 'Über',
    TOURS: 'Touren',
    SKIP_THE_LINE_TOURS: 'Schnelleinlass-Touren',
    GUIDED_TOURS: 'Geführte Touren',
    NIGHT_TOURS: 'Touren bei Nacht',
    FOOD_TOURS: 'Food Touren',
    HISTORY: 'Geschichte',
    ARCHITECTURE: 'Architektur',
    DESIGN: 'Design',
    INSIDE: 'Innen',
    COLLECTIONS: 'Sammlungen',
    PAINTINGS: 'Gemälde',
    ANIMALS_EXHIBITS: 'Tiere und Exponate',
    HABITATS: 'Lebensräume',
    CONSERVATION: 'Erhaltung',
    PROGRAMMES: 'Programme',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing-Fahrten',
    A2_DINNER_CRUISES: 'Dinner-Fahrten',
    A2_EVENING_CRUISES: 'Evening Cruises',
    A2_LUNCH_CRUISES: 'Mittagsfahrten',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Besuch planen',
    TIMINGS: 'Öffnungszeiten',
    DIRECTIONS: 'Anfahrt',
    PARKING: 'Parken',
    ROUTES: 'Routen',
    REQUIREMENTS: 'Anforderungen',
    LOCATION: 'Standort',
    RULES: 'Regeln',
    FAQs: 'FAQ',
    ENTRANCES: 'Eingänge',
    RESTAURANTS: 'Restaurants',
    FACTS: 'Fakten',
    TIPS: 'Tipps',
    MAP: 'Karte',
    RIDES: 'Fahrten',
    SHOWS: 'Shows',
    DINING: 'Gastronomie',
    SHOPPING: 'Shoppen',
    EVENTS: 'Events',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Weihnachten',
    NEW_YEARS_EVE: 'Silvester',
    TRAVEL_GUIDE: 'Reiseführer',
    TRIP_PLANNER: 'Reiseplaner',
    ITINERARY: 'Reiseprogramm',
    TRAVEL_TIPS: 'Reisetipps',
    WEATHER: 'Wetter',
    BEST_TIME_TO_VISIT: 'Beste Besuchszeit',
    JANUARY: 'Januar',
    FEBRUARY: 'Februar',
    MARCH: 'März',
    APRIL: 'April',
    MAY: 'Mai',
    JUNE: 'Juni',
    JULY: 'Juli',
    AUGUST: 'August',
    SEPTEMBER: 'September',
    OCTOBER: 'Oktober',
    NOVEMBER: 'November',
    DECEMBER: 'Dezember',
    WHERE_TO_EAT: 'Essen',
    WHERE_TO_STAY: 'Unterkünfte',
    NEIGHBOURHOODS: 'Viertel',
    FAMILY_TRAVEL: 'Familienreisen',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivals und Events',
  },
  WHY_WATCH: 'Auf einen Blick',
  FIND_ON_MAP: 'Auf der Karte anzeigen',
  LTT_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      INSTANT_TICKETS: {
        NAME: 'Sofortige Tickets',
        DESCRIPTION: 'Buchungsbestätigung direkt von der Theaterkasse.',
      },
      PRICES_LOVE: {
        NAME: `Bestpreisgarantie`,
        DESCRIPTION: 'Unschlagbare Preise für die besten Shows.',
      },
      CHOOSE_SEATS: {
        NAME: 'Platzwahl',
        DESCRIPTION: 'Sichern Sie sich die besten Plätze für jede Show.',
      },
      OFFICIAL_LTT: {
        NAME: 'Offizielle London Theater Tickets',
        DESCRIPTION: 'Bei uns sicher und schnell buchen.',
      },
    },
    YOUR_PICK: 'Ihre Auswahl',
    BROWSE_BY_CATEGORIES: 'Kategorien durchstöbern',
    TOP_WEST_END_SHOWS: 'Die besten West End Shows',
    LAST_MINUTE_TICKETS: 'Last-Minute Tickets',
    LOVED_BY_MILLIONS: 'Millionen zufriedene Kunden',
    TODAY: 'Heute',
    TOMORROW: 'Morgen',
    SEE_ALL: 'Alle ansehen',
    GRAB_YOUR_TICKETS: 'Tickets jetzt buchen',
  },
  TAG_NAME: {
    BALLET: 'Ballett',
    CABARET: 'Kabarett',
    CHRISTMAS: 'Weihnachten',
    CIRCUS: 'Zirkus',
    CLASSIC: 'Klassiker',
    COMEDY: 'Comedy',
    COMING_SOON: 'Demnächst verfügbar',
    CRITICS_CHOICE: "Critics' Choice",
    DANCE: 'Tanz',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasy',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Immersives Theater',
    JUKEBOX: 'Jukebox',
    KIDS: 'Kinder',
    MAGIC: 'Zaubershows',
    MUSICALS: 'Musicals',
    NEW_ARRIVAL: 'Neuheiten',
    OFF_WEST_END: 'Off West End',
    OLIVIER_WINNER: 'Olivier Preisträger',
    OPERA: 'Oper',
    PANTOMIMES: 'Englische Pantomime',
    PLAYS: 'Theater',
    ROMANCE: 'Romantik',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Stars on Stage',
    THEATRICAL_CONCERT: 'Theaterkonzert',
    TRUE_STORY: 'Wahre Begebenheiten',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Oh, das hat nicht geklappt',
    MESSAGE: `Schade! Alle Erlebnisse sind an diesem Datum ausverkauft oder nicht verfügbar. Keine Sorge – wir haben noch viele andere Termine zur Auswahl!`,
    CTA: 'Alle Daten anzeigen',
  },
  ALL_DATES: 'Alle Daten',
  BREADCRUMBS: {
    HOME: 'Home',
    TRAVEL_GUIDE: 'Reiseführer',
    THINGS_TO_DO: 'Erlebnisse in {0}',
    SHOW_NAME_TICKETS: '{0} - Tickets',
    LTT_HOME: 'London Theatre Tickets',
    LTT_VENUE_PAGE_HOME: 'Theater in London',
    BROADWAY_HOME: 'Broadway Tickets',
    BROADWAY_VENUE_PAGE_HOME: 'Theater am Broadway',
    VIENNA_CONCERT_HOME: 'Tickets für Wiener Konzerte',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Konzertsäle in Wien',
    ATTRACTIONS: 'Attraktionen',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing-Fahrten',
    A2_DINNER_CRUISES: 'Dinner-Fahrten',
    A2_EVENING_CRUISES: 'Evening Cruises',
    A2_LUNCH_CRUISES: 'Mittagsfahrten',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'London Theatre News',
    BROADWAY_SHOW_NEWS: 'Broadway News',
    NEWS_PAGE: 'Aktuelles',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Café',
    'Dedicated Parking': 'Parkplätze vorhanden',
    Elevators: 'Fahrstuhl',
    Lift: 'Fahrstuhl',
    'Wheelchair Accessible': 'Rollstuhlgerecht',
    Cloakroom: 'Garderobe',
    'Air Conditioning': 'Klimatisiert',
    WiFi: 'WLAN',
    Bar: 'Bar',
    'Water Fountain': 'Trinkbrunnen',
    Washrooms: 'Toiletten',
    Toilets: 'Toiletten',
    Binoculars: 'Operngläser',
    'Adapted Toilets': 'Barrierefreie Toiletten',
    'Accessible Toilets': 'Barrierefreie Toiletten',
    'Assistive Listening System': 'Assistive Hörsysteme',
    'Hearing Assistance': 'Hörhilfen',
    'Booster Cushions': 'Sitzkissen für Kinder',
    Shop: 'Shop',
    'Souvenir Shop': 'Souvenirladen',
    'Guide Dogs': 'Blindenhundefreundlich',
    'Baby Changing Facilities': 'Wickelräume',
    'Security Check': 'Sicherheitskontrolle',
    Ramp: 'Rampe',
    'Level Access': 'Ebener Zugang',
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Fachkundige mehrsprachige Reiseleiter',
    STL: 'Schnelleinlass',
    PERSONALIZED: 'Personalisiertes Erlebnis',
    LOCAL_FOOD: 'Lokale Küche und Kultur erleben',
    MULTILINGUAL_GUIDES: 'Mehrsprachige Reiseleiter',
    CULINARY_EXPERTS: 'Kulinarische Experten treffen',
    SIGHTSEEING: 'Sightseeing + Unterhaltung an Bord',
    MULTILINGUAL_GT: 'Mehrsprachige geführte Touren',
    MULTI_ROUTES: 'Mehrere Routenoptionen',
    HASSLE_FREE: 'Einfache Buchung',
    FREQUENT_DEPARTURES: 'Regelmäßige Abfahrten',
    ONBOARD_AMENITIES: 'Beste Ausstattung an Bord',
    FLEXI_TRAVEL: 'Flexibles Reisen auf mehreren Routen',
    FLEXI_EXCHANGE_CANCEL: 'Flexibler Umtausch und Stornierung',
    EXTRA_DISCOUNT: 'Extra-Rabatte für Jugendliche, Senioren und Familien',
    PREPAID: 'Prepaid-Komfort',
    EASY_ACTIVATION: 'Einfache Aktivierung',
    INSTANT_CONNECTIVITY: 'Sofortige Verbindung mit globaler Abdeckung',
    ROUND_TRIP: 'Hin- und Rücktransfers',
    CULTURAL_EXPERIENCE: 'Authentische kulturelle Erlebnisse',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
    LUGGAGE_ASSISTANCE: 'Hilfe mit Gepäck',
    TOP_ATTRACTIONS: 'Top-Attraktionen inklusive',
    FREQ_DEP_MULTI_ROUTE: 'Häufige Abfahrten auf mehreren Routen',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Alle',
    POPULAR_SUBCATEGORY: 'Beliebte {0}',
    TOP_CATEGORY: 'Top-{0}',
    ATTRACTIONS: 'Attraktionen',
    ALL_SUBCATEGORY: 'Alle {0}',
    BROWSE_BY_CATEGORIES: 'Kategorien durchstöbern',
    TICKETS_FROM: 'Tickets ab',
    PRICE_LOW_HIGH: 'Preis (niedrigster zuerst)',
    PRICE_HIGH_LOW: 'Preis (höchster zuerst)',
    FILTERS: 'Filter',
    RESET: 'Zurücksetzen',
    APPLY: 'Anwenden',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout verwendet Cookies, um Ihnen eine bessere Nutzererfahrung zu bieten.',
    MOBILE: 'Wir verwenden Cookies.',
    LEARN_MORE: 'Mehr Infos.',
  },
  SHOW_UNAVAILABLE: 'Show nicht verfügbar',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Hervorgehoben',
    ALL_NEWS: 'Alle Neuigkeiten',
    MORE_READS: 'Weitere Artikel',
    LOAD_MORE: 'Weitere Artikel laden',
    TRAILERS: 'Alle Trailer',
    GET_YOUR_TICKETS: 'Tickets buchen',
    POPULAR_SHOWS: 'Beliebte Shows',
  },
  HOHO: {
    HOHO: 'Hop-on Hop-off Tickets',
    ROUTE_DETAILS: 'Details zur Route',
    MORE_DETAILS: 'Weitere Infos',
    ROUTES_SCHEDULES: 'Routen und Fahrpläne',
    VALIDITY: 'Gültig für 1 Tag',
    VALIDITY_NOTE:
      'Ihr Erlebnis ist für {0} Kalendertag/e gültig. Wenn Sie Ihr Ticket für den 06.05.2023 buchen, ist es bis zum 06.05.2023 um 21:00 Uhr PST gültig.',
    BESTSELLER: 'Bestseller',
    SEE_ALL: 'Alle anzeigen',
    TIMINGS: 'FAHRZEITEN',
    FREQUENCY: 'HÄUFIGKEIT',
    DURATION: 'DAUER',
    STARTING_LOCATION: 'Startpunkt',
    TOP_ATTRACTIONS: 'Top-Sehenswürdigkeiten der Route',
    CALENDAR_FOOTNOTE: '* Alle Preise sind in {0}',
    GOT_IT: 'Alles klar',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Privattransfers',
    SHARED_TRANSFERS: 'Gemeinschaftstransfers',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Online buchen',
        DESCRIPTION: 'Buchen Sie Ihre Tickets schnell und bequem online.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Sofortbestätigung',
        DESCRIPTION:
          'Sie erhalten eine sofortige Buchungsbestätigung für Ihren Flughafentransfer.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Bequeme Abholung',
        DESCRIPTION:
          'Vergessen Sie lange Wartezeiten. Ihr Fahrzeug wartet bereits am gewählten Abholort auf Sie.',
      },
      DROP_OFF: {
        TITLE: 'Ankunftsort',
        DESCRIPTION: 'Sie erreichen Ihr Ziel schnell und komfortabel.',
      },
    },

    SHARED_TRANSFERS_IN: 'Gemeinschaftstransfers in {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      'Bequeme und kostengünstige Transferdienste für mehrere Fahrgäste, die zu oder von einem Flughafen reisen.',
    PRIVATE_TRANSFERS_IN: 'Privattransfers in {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      'Bequeme und direkte Transferdienste für Einzelpersonen oder kleine Gruppen, die zu und von einem Flughafen reisen.',
    ANYWHERE_IN_THE_CITY: 'Überall in der Stadt',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Verschiedene Fahrzeugoptionen',
      FREE_CANCELLATION: 'Kostenlose Stornierung',
    },
    SEAMLESS_TRANSFERS:
      'Reibungslose und zuverlässige Transfers auf der ganzen Welt',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Wählen Sie den besten Flughafentransfer für Sie',
  },
};

export default de;
