const de = {
  AUDIO_GUIDE: {
    BANNER: 'Gratis Audioguide',
    PRODUCT_SUFFIX: '+ Audioguide',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Autorisierter und zuverlässiger Partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Autorisierter Reseller',
    SUB_TEXT: 'Erlebnisse von verifizierten Partnern.',
  },
  AVAILABLE: 'Verfügbar',
  BANNER_CTA: 'Tickets kaufen',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout ist ein Unternehmen, dem weltweit Millionen von Gästen vertrauen und das ausgewählte Erlebnisse für diese Attraktion anbietet.',
    NON_PARTNERED_SENSITIVE:
      'Headout ist ein Unternehmen, dem weltweit Millionen von Gästen vertrauen und das ausgewählte Erlebnisse für diese Attraktion anbietet. Dies ist nicht die Website des Erlebnisortes.',
    PARTNERED_NON_SENSITIVE:
      'Headout ist ein autorisierter und zuverlässiger Partner des Veranstaltungsortes, der ausgewählte Erlebnisse für diese Attraktion anbietet.',
    PARTNERED_SENSITIVE:
      'Headout ist ein autorisierter und zuverlässiger Partner des Veranstaltungsortes, der ausgewählte Erlebnisse für diese Attraktion anbietet. Dies ist nicht die Website des Veranstaltungsortes.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout ist ein autorisierter und zuverlässiger Partner der Attraktion mit einer Auswahl der besten Erlebnisse.',
  BOOK_NOW_CTA: 'Jetzt buchen',
  BUY_TICKETS_CTA: 'Tickets kaufen',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Sie können diese Tickets bis zu {0} Stunden vor Erlebnisbeginn stornieren, um eine vollständige Rückerstattung zu erhalten.',
    CANCELLABLE_ANYTIME: 'Kostenfreie Stornierung vor Beginn Ihres Erlebnisses',
    CANCELLABLE_DAYS:
      'Sie können diese Tickets bis zu {0} Tage vor Beginn des Erlebnisses für eine volle Rückerstattung stornieren.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Diese Tickets können nicht storniert werden. Sie sind jedoch für einen längeren Zeitraum gültig.',
    HEADING: 'Änderungsrichtlinie',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Diese Tickets können nicht storniert werden. Sie können jedoch bis zu {0} Stunden vor Erlebnisbeginn verschoben werden.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Diese Tickets können nicht storniert oder verschoben werden.',
    VALID_UNTIL_DATE:
      'Diese Tickets können nicht storniert werden. Sie können jedoch bis zum {0} verwendet werden.',
    VALID_WITHIN_NEXT_DAYS:
      'Diese Tickets können nicht storniert werden. Sie können jedoch jederzeit innerhalb der nächsten {0} Tage verwendet werden.',
    VALID_WITHIN_NEXT_MONTHS:
      'Diese Tickets können nicht storniert werden. Sie können jedoch jederzeit innerhalb der nächsten {0} Monate verwendet werden.',
  },
  CANCELLATION_POLICY_HEADING: 'Stornierungsfrist',
  CASHBACK: '{0} % Cashback',
  CASHBACK_INFO:
    'Sie erhalten <strong>{0} %</strong> Cashback, wenn Sie dieses Erlebnis buchen. Ihr Cashback wird automatisch Ihrem Headout-Konto gutgeschrieben und kann für zukünftige Buchungen mit Headout verwendet werden.',
  CATEGORY_SLIDER_HEADING:
    'Was sich Zuschauer dieser Show noch angesehen haben',
  CHECK_AVAIL: 'Verfügbarkeit prüfen',
  CITY_PAGE: {
    BANNER_TITLE: 'Erleben Sie die Highlights von',
    TOP_ATTRACTIONS: 'Top-Attraktionen',
    GO_BEYOND: 'Ausflüge von {0}',
    ALL_DAY_TRIPS: 'Alle Tagesausflüge',
    CITIES_NEARBY: 'Städte in der Nähe',
    POPULAR_CATEGORIES: 'Beliebte Kategorien',
    GO_TO_GUIDE: 'Ihr {0} Reiseführer',
    VIEW_TRAVEL_GUIDE: 'Reiseführer anzeigen',
    EXPLORE: '{0} entdecken',
    GUIDE_SUBHEADING:
      'Noch nie war es so einfach, {0} zu erkunden! In unserem Reiseführer finden Sie alles, was Sie über {0} wissen müssen – von kulinarischen Geheimtipps bis zu Unterkünften und Anreisemöglichkeiten zu beliebten Wahrzeichen.',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Allgemeines',
      WHERE_TO_EAT: 'Kulinarisches',
      WHERE_TO_STAY: 'Unterkünfte',
      THINGS_TO_DO: 'Erlebnisse',
      WEATHER: 'Beste Reisezeit',
      NEIGHBOURHOODS: 'Stadtviertel',
      TRANSPORTATION: 'Nahverkehr',
      TRIP_PLANNER: 'Reiseplan',
      FAMILY_TRAVEL: 'Reisen mit Kindern',
      TRAVEL_TIPS: 'Reisetipps',
      SHOPPING: 'Shoppen',
      ART_AND_CULTURE: 'Kunst und Kultur',
    },
    MAILER: {
      HEADING:
        'Inspirationen für Ihre Reise nach {0} direkt zu Ihrem Posteingang',
      SUBHEADING:
        'Erkunden Sie neue Städte mit ausgewählten Erlebnissen, Cashback, exklusiven Deals und wertvollen Reisetipps!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Visabestimmungen, Geldwechsel, Zeitzonenunterschiede und mehr – wichtige Infos für eine reibungslose Ankunft und einen angenehmen Aufenthalt.',
    WHERE_TO_EAT:
      'Kulinarische Köstlichkeiten, exquisite Aromen und lokale Spezialitäten erwarten Sie in {0} an jeder Ecke.',
    WHERE_TO_STAY:
      'Hier finden Sie die besten Unterkünfte für einen bequemen und unvergesslichen Aufenthalt in {0}.',
    THINGS_TO_DO:
      'Spannende Aktivitäten und Attraktionen für Groß und Klein sorgen für eine unvergessliche Zeit.',
    WEATHER:
      'Hier finden Sie wichtige Infos für Ihre Reiseplanung, denn {0} hat das ganze Jahr über zauberhafte Erlebnisse zu bieten.',
    NEIGHBOURHOODS:
      'Entdecken Sie die verschiedenen, lebhaften Viertel, die {0} so besonders machen.',
    TRANSPORTATION:
      'Mit dem öffentlichen Nahverkehr gelangen Sie in {0} schnell und bequem von einer Attraktion zur nächsten.',
    TRIP_PLANNER:
      'Mit unseren sorgfältig ausgewählten Reiseplänen nutzen Sie Ihre Zeit in {0} optimal aus und können jeden Moment vollkommen genießen.',
    FAMILY_TRAVEL:
      'Familienfreundliche Abenteuer mit zahlreichen Attraktionen, Parks und Unterhaltungsmöglichkeiten für alle Altersklassen erwarten Sie.',
    TRAVEL_TIPS:
      'Insider-Tipps und Reise-Hacks garantieren eine außergewöhnliche Reise nach {0}.',
    SHOPPING:
      'Ein Einkaufsparadies mit Boutiquen, Märkten und Einkaufszentren – von lokalem Kunsthandwerk bis zu hochwertiger Mode.',
    ART_AND_CULTURE:
      'Erkunden Sie die reiche Kunst- und Kulturszene von {0} – von faszinierenden Museen bis hin zu lebhaften Festivals.',
  },
  CLOSE: 'Schließen',
  COLLECTION_SLICE_HEADING: 'Top-Erlebnisse in {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Auswählen',
    SELECT_PREFERENCE: 'Wählen Sie die gewünschte Ticketvariante aus',
    SELECT_OPTION: 'Gewünschte Ticketvariante wählen',
    SELECT_TICKET: 'Ticket wählen',
  },
  COMPARE_ALL_DETAILS: 'Alle vergleichen',
  COVID19_ALERT: {
    KEY_TEXT: 'Corona-Update',
    LINK: 'https://medium.com/headout/coronavirus-ausbruch-stornierungsbedingungen-cec74ac7641b',
    TEXT: 'Ihr Wohlergehen ist unsere Priorität. Weitere Informationen zu unseren flexiblen Stornierungsbedingungen finden Sie auf der Seite „Hilfe & FAQs“.',
  },
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Wir nutzen Cookies und ähnliche Technologien für viele Zwecke, u. a. zur Verbesserung der Website und für Werbung.',
    MANAGE_PREFERENCES: 'Einstellungen',
    PREFERNCES_SAVED: 'Ihre Einstellungen wurden gespeichert',
    ACCEPT: 'Ok',
    ALLOW_ALL: 'Alle akzeptieren',
    DENY_ALL: 'Alle ablehnen',
    HEADING: 'Wir schätzen Ihre Privatsphäre immer',
    COOKIES: 'Kekse:',
    DESCRIPTION: `*   Cookies sind kleine Dateien, die von einer Website/Plattform auf Ihrem Computer, Ihrem Mobilgerät oder einem anderen Gerät platziert werden und unter anderem Einzelheiten zu Ihrem Browserverlauf enthalten.
*   Wir verwenden verschiedene Arten von Cookies, um Ihre Nutzung unserer Plattform zu verfolgen und bestimmte Informationen zu speichern, die uns dabei helfen, Ihnen personalisierte Dienste anzubieten. Bestimmte Cookies können auf Ihrem Gerät platziert werden, wenn Sie die auf unserer Plattform verfügbaren Dienste nutzen.
*   Im Großen und Ganzen setzen wir in diesem Bereich zwei verschiedene Arten von Technologien ein:
    *   **Cookies oder Browser-Cookies.** Es handelt sich um eine kleine Datei, die automatisch auf Ihrem Gerät gespeichert wird, wenn Sie auf unsere Plattform zugreifen. Sie können Ihren Browser anweisen, alle Cookies abzulehnen. Wenn Sie unsere Cookies nicht akzeptieren, können Sie möglicherweise einige Teile unserer Plattform nicht nutzen.
    *   **Web-Beacons.** Auch als Clear Gifs, Pixel-Tags und Single-Pixel-Gifs bezeichnet, die in verschiedenen Bereichen unserer Plattform und unseren E-Mails angebracht sind und uns erlauben, die Aktivitäten der Nutzer zu überwachen und zu verstehen.
*   Bei diesen auf Ihrem Gerät gespeicherten Cookies kann es sich um "permanente" oder "Sitzungs"-Cookies handeln. Dauerhafte Cookies verbleiben auf Ihrem Gerät, auch wenn Sie offline gehen, während Sitzungscookies automatisch gelöscht werden, sobald Sie Ihren Webbrowser schließen.
*   Wir verwenden sowohl Sitzungscookies als auch dauerhafte Cookies für die unten genannten Zwecke:
    *   Notwendige / essentielle Cookies
        *   _Typ:_ Session-Cookies
        *   _Zweck:_ Diese Cookies sind unerlässlich, damit Sie auf verschiedene Bereiche der Plattform zugreifen können, und wenn diese nicht erlaubt sind, können Sie möglicherweise nicht auf die auf der Plattform verfügbaren Dienste zugreifen. Diese Cookies helfen uns außerdem dabei, die Nutzer zu authentifizieren und jegliche Art von betrügerischen Aktivitäten auf der Plattform zu verhindern.
    *   Cookies Politik / Hinweis Akzeptanz Cookies
        *   _Typ:_ Dauerhafte Cookies
        *   _Zweck:_ Diese Cookies identifizieren, ob der Benutzer die Verwendung von Cookies akzeptiert hat.
    *   Funktionalität Cookies
        *   _Typ:_ Dauerhafte Cookies
        *   _Zweck:_ Diese Cookies ermöglichen es uns, die von Ihnen bei der Nutzung der Plattform getroffenen Entscheidungen zu speichern, z. B. Ihre Anmeldedaten oder Ihre Spracheinstellung. Der Hauptzweck dieser Cookies besteht darin, Ihnen jedes Mal, wenn Sie die Plattform nutzen, ein personalisiertes Erlebnis zu bieten.

_Alle oben in Großbuchstaben geschriebenen Begriffe sind in der Datenschutzrichtlinie definiert. Für ein detailliertes Verständnis lesen Sie bitte die_ [_Datenschutzrichtlinie_](/privacy-policy/)`,
  },
  CURRENCY: 'Währung',
  CUSTOMER_REVIEW_HEADING: 'Zuschauerbewertungen',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioguide',
    DURATION: 'Dauer: {0}',
    EXTENDED_VALIDITY: 'Verlängerte Gültigkeit',
    FLEXIBLE_DURATION: 'Flexible Dauer',
    FREE_CANCELLATION: 'Kostenlose Stornierung',
    GUIDED_TOUR: 'Geführte Tour',
    HOTEL_PICKUP: 'Hotel-Abholung',
    INSTANT_CONFIRMATION: 'Sofortbestätigung',
    MEALS_INCLUDED: 'Inkl. Mahlzeit',
    MOBILE_TICKET: 'Digitale Tickets',
    SKIP_THE_LINE: 'Schnelleinlass',
    TRANSFERS: 'Transfer inklusive',
    MULTILINGUAL_AUDIO_GUIDE: 'Mehrsprachiger Audioguide',
    LIVE_GUIDE: 'Live-Reiseleiter',
  },
  DURATION: 'Dauer',
  EARLIEST_AVAILABILITY: 'Früheste verfügbare',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Geben Sie hier Ihre E-Mail-Adresse ein',
    SIGN_UP: 'Anmelden',
    THANK_YOU: 'Vielen Dank!',
    SUBSCRIBED_MSG: 'Sie sind jetzt angemeldet.',
    ERROR_MSG: 'Bitte eine gültige E-Mail-Adresse eingeben.',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Broadway Theater Tickets',
    },
    LTT: {
      MB_NAME: 'London Theater Tickets',
    },
  },
  EXCLUSIONS: 'Nicht enthalten',
  FEATURE_CARD: {
    HEADING_CUSTOMER: 'Über 10 Millionen',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100 % sicher',
    HEADING_SUPPORT: '24-Stunden Support',
    SUB_HEADING_CUSTOMER: 'zufriedene Kunden bei mehr als 10.000 Erlebnissen',
    SUB_HEADING_RATING:
      'Über 5.000 geprüfte Rezensionen mit 90 % ausgezeichneten Bewertungen',
    SUB_HEADING_SAFE: 'Alle Outdoor-Aktivitäten sind 100 % sicher',
    SUB_HEADING_SUPPORT:
      'Haben Sie Fragen? Nutzen Sie unseren Live-Chat, jederzeit und überall',
  },
  FLEXIBLE: 'Flexibel',
  FOOTER: {
    CALL_US: 'Telefon',
    CHAT_WITH_US: 'Live-Chat',
    COMPANY_DETAILS: 'Unternehmensangaben',
    ABOUT_US: 'Über uns',
    INFORMATION: 'Informationen',
    GMAPS_DISCLAIMER:
      'Alle Screenshots von Karten, die auf dieser Seite zu finden sind, stammen von Google in Übereinstimmung mit dem Fair Use-Prinzip. Alle Rechte an diesen Screenshots liegen bei der jeweiligen Plattform und ihre Verwendung dient ausschließlich zu Informations- und Orientierungszwecken.',
    DISCLAIMER:
      'Diese Website ist nicht die offizielle Website <attraction>. Die Website wird vom Unternehmen Headout betrieben, das mit Veranstaltern für Attraktionen und Touren zusammenarbeitet, um unglaubliche Erlebnisse auf Knopfdruck anzubieten.',
    EMAIL_US: 'E-Mail',
    GET_HELP: 'Hilfe',
    LEGAL: 'Rechtliches',
    PRIVACY_POLICY: 'Datenschutzrichtlinie',
    QUICK_LINKS: 'Quick Links',
    TERMS_AND_CONDITIONS: 'AGB',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Made with ',
    ALL_OVER_THE: ' all over the ',
    TERMS_OF_USAGE: 'Nutzungsbedingungen',
    GET_HELP_24_7: '24-Std. support',
    HELP_CENTER: 'Hilfe',
    COMPANY: 'die Firma',
    WE_ACCEPT: 'ZAHLUNGSOPTIONEN',
    DOWNLOAD_HEADOUT: 'Laden Sie die Headout-App herunter',
    SCAN_CODES: 'Code scannen',
    STAR_VERIFIED: 'Klicken und S.T.A.R. Mitgliedschaft anzeigen',
    OFFICIAL_TICKET_RETAILER: 'OFFIZIELLER TICKETVERKÄUFER',
  },
  FREE_CANCELLATION: 'Kostenlose Stornierung',
  FREE_CANCELLATION_SUBTEXT:
    'Stornierungen sind bis zu 72 Std. im Voraus möglich.',
  FROM: 'ab',
  GET_CASHBACK: '{0} % Cashback sichern',
  GROUP_TICKETS: 'Gruppentickets',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: 'Über 20 Mio. Kunden',
    SUB_TEXT: 'Ihre Zufriedenheit ist unsere oberste Priorität.',
  },
  HELP_CENTER: {
    MAIN_TEXT: '24-Std. Support',
    SUB_TEXT: 'Wir sind rund um die Uhr für Sie erreichbar.',
  },
  INCLUSIONS: 'Inklusive',
  LANGUAGE: 'Sprache',
  LISTICLES: {
    KNOW_MORE: 'Weitere Infos',
    SEATING_CHART: 'Saalplan',
    WHY_BOOK_FROM_US: 'Unsere Vorteile?',
  },
  MORE_DETAILS: 'Mehr anzeigen',
  MORE_CURRENCIES: 'Weitere Währungen',
  NEW: 'NEU',
  NEW_ARRIVAL: 'Neuerscheinungen',
  NEXT_AVAILABLE: 'Verfügbar ab: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout ist ein Unternehmen, dem über 15 Millionen Gäste vertrauen und das eine Auswahl der besten Erlebnisse bietet. Dies ist nicht die Website des Erlebnisortes.',
  NO_RESULT_FOUND: 'Keine Ergebnisse gefunden',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR: 'Flexibel buchen – keine Terminsauswahl nötig',
  OPENING_DATE: 'Eröffnungsdatum',
  OPENING_ON: 'Eröffnung am',
  OPENS: 'Ab',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout ist ein autorisierter und zuverlässiger Partner der Attraktion mit einer Auswahl der besten Erlebnisse. Dies ist nicht die Website der Attraktion.',
  POPULARITY: 'Beliebtheit',
  POPULAR_CURRENCIES: 'Beliebte Währungen',
  PRICE: 'Preis',
  PRICES_STARTING: 'Preise ab',
  PROMO_CODES: {
    APPLY_CODE: 'CODE ANWENDEN',
    APPLIED: 'ANGEWANDT',
    TOOL_TIP_INFO: 'Der Rabatt wird an der Kasse angewandt',
    DESCRIPTION: {
      ABSOLUTE: '{0} Rabatt sichern',
      CAPPED: '{0} % Rabatt für bis zu {1}',
      PERCENTAGE: '{0} % Rabatt sichern',
    },
    REMOVE: 'ENTFERNEN',
  },
  RATINGS: '{0} Bewertungen',
  READ_MORE: 'Weiterlesen',
  READ_MORE_TEXT: 'Mehr anzeigen',
  READ_LESS: 'Weniger anzeigen',
  VIEW_DETAILS: 'Details anzeigen',
  REOPENING: 'Wiedereröffnung',
  REOPENING_DATE: 'Wiedereröffnungsdatum',
  REOPENING_ON: 'Neueröffnung am',
  REOPENS: 'Endlich wieder ab',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT: 'Es gilt die 2G-Regel: Der Zugang zu Unterkünften, Kultureinrichtungen, Restaurants, Bars usw. ist nur mit einem Impf- oder Genesungsnachweis möglich. Ein negativer Covid-19-Test ist nicht mehr ausreichend.',
    },
    AU_DESCRIPTION: {
      TEXT: 'Besucher ab 16 Jahren müssen eine COVID-19-Impfung oder eine medizinische Ausnahmegenehmigung vorweisen.',
    },
    BANNER_CTA: 'Weitere Infos',
    BERLIN_DESCRIPTION: {
      TEXT: 'Es gilt die 2G-Regel: Nur vollständig geimpfte und genesene Besucher mit entsprechendem Nachweis haben Zutritt. Personen unter 18 Jahren oder solche, die aus medizinischen Gründen nicht geimpft werden können, müssen am Eingang ein negatives COVID-Testergebnis sowie einen medizinischen Nachweis über die Impfunfähigkeit vorlegen.',
    },
    CTA_TEXT: 'Sicherheitsvorkehrungen',
    DESCRIPTION_CTA: 'Weitere Infos.',
    EU_DESCRIPTION: {
      TEXT: 'Ab dem 21. Juli müssen alle Besucher ab 12 Jahren ein COVID-Zertifikat der EU vorlegen.',
    },
    EU_HEADING: 'COVID-Zertifikat der EU erforderlich',
    EU_PREFIX: 'Hinweis: ',
    EXPERIENCE_DESCRIPTION:
      'Dieses Erlebnis entspricht nachweislich den besten Sicherheitsstandards in Übereinstimmung mit den örtlichen Vorschriften und der WHO.',
    FLAG_TEXT: 'Nachweislich sicher',
    GENERAL_DESCRIPTION:
      'Erlebnisse mit diesem Abzeichen halten nachweislich die besten Sicherheitsstandards gemäß den Gesundheitsrichtlinien der örtlichen Regierung ein.',
    HEADING: 'Beste Sicherheitsstandards',
    IT_DESCRIPTION: {
      TEXT: 'Ab dem 6. August müssen alle Besucher über 11 Jahren einen Grünen Pass oder ein COVID-Zertifikat der EU vorlegen',
    },
    IT_PREFIX: 'Hinweis: ',
    MOBILE_HEADING: 'Sichere Erlebnisse',
    MODAL: {
      BADGE_DESCRIPTION:
        'Erlebnisse mit diesem Abzeichen entsprechen nachweislich den von der Attraktion geprüften Sicherheitsstandards.',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Alle Geräte, Fahrzeuge und häufige Einsatzbereiche werden nach jeder einzelnen Nutzung desinfiziert. Genießen Sie ein sicheres Erlebnis.',
          HEADING: 'Zubehör und Oberflächen werden desinfiziert',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Jegliches Ausrüstungszubehör, das Ihnen bei Ihrem Erlebnis zur Verfügung steht, wird nach jeder Nutzung gründlich desinfiziert – immer und jedes Mal.',
          HEADING: 'Zubehör- und Oberflächendesinfizierung',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Alle Fahrzeuge, die Ihnen bei Ihrem Erlebnis zur Verfügung stehen, werden nach jedem Einsatz gründlich desinfiziert. Immer und jedes Mal',
          HEADING: 'Alle Fahrzeuge werden desinfiziert',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Bei Sicheren Erlebnissen haben Sie die ganze Zeit über Zugang zu Handwasch- und Sanitärstationen. Für Ihre Sicherheit ist gesorgt. ',
          HEADING: 'Sanitäreinrichtungen und Handwaschbecken überall verfügbar',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Alle Gäste und Mitarbeiter müssen bei diesem Erlebnis eine Maske tragen. Auf diese Weise kann jeder das Erlebnis mit höchster Sicherheit genießen.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Unsere Partner, die nachweislich sichere Erlebnisse anbieten, halten sich an die örtlichen Vorschriften bezüglich der Maskenpflicht. Wenn es vorgeschrieben ist, werden alle Gäste und Mitarbeiter Masken tragen. Es werden jegliche Schritte unternommen, um Ihre Sicherheit und Zufriedenheit zu gewährleisten.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Alle Gäste müssen bei diesem Erlebnis eine Maske tragen. Auf diese Weise kann jeder das Erlebnis mit höchster Sicherheit genießen.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Bei diesem Erlebnis tragen alle Mitarbeiter eine Maske, damit Sie den ganzen Spaß sorglos genießen können.',
          HEADING: 'Maskenpflicht zu Ihrer Sicherheit',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Die Abstandsregelungen werden während des gesamten Erlebnisses eingehalten. Zur Einhaltung des Sicherheitsabstandes ist die Besucherkapazität beschränkt.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Die Abstandsregelungen werden während des gesamten Erlebnisses eingehalten. Zur Einhaltung des Sicherheitsabstandes ist die Besucherkapazität beschränkt und der Eintritt für größere Gruppen untersagt.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Die Abstandsregelungen werden bei diesem Erlebnis jederzeit eingehalten.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Die Abstandsregelungen werden bei diesem Erlebnis jederzeit eingehalten. Zur Einhaltung können Kapazitäten und Gruppengrößen beschränkt werden. Hier können Sie aufatmen.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Die Abstandsregelungen werden während des gesamten Erlebnisses eingehalten. Angesichts dessen ist der Eintritt für größere Gruppen untersagt.',
          HEADING: 'Abstandsregelungen werden befolgt',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Um die Sicherheit für alle zu gewährleisten, wird bei jedem Gast zu Beginn des Erlebnisses Fieber gemessen. Darüber hinaus wird auch bei allen Mitarbeitern mehrmals täglich Fieber gemessen.',
          HEADING: 'Fiebermessung vor Ort',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Um die Sicherheit für alle zu gewährleisten, wird bei jedem Gast zu Beginn des Erlebnisses Fieber gemessen. ',
          HEADING: 'Fiebermessung vor Ort',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Fiebermessungen werden mehrfach bei allen Mitarbeitern durchgeführt. Mitarbeiter mit einer Temperatur über dem vorgeschriebenen Grenzwert haben keinen Zutritt und werden gebeten, sich zu Hause auszukurieren.',
          HEADING: 'Fiebermessung vor Ort',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Die Mitarbeiter, die während des gesamten Erlebnisses zur Verfügung stehen, sind gemäß den WHO-Richtlinien geschult und auf alle möglichen Notfälle vorbereitet.',
          HEADING: 'Auf WHO-Richtlinien geschultes Personal',
        },
      },
      HEADING: 'Sichere Erlebnisse',
      SUB_HEADING:
        'Wir arbeiten mit unseren Partnern auf der ganzen Welt zusammen, um die besten Sicherheitsstandards gemäß den WHO-Richtlinien umzusetzen. Alle vor Ort getroffenen Maßnahmen wurden überprüft und werden hier angezeigt. Es ist an der Zeit, dass wir unsere Welt wieder genießen.',
    },
    NL_DESCRIPTION: {
      TEXT: 'Besucher ab 13 Jahren müssen ein COVID-Zertifikat (in digitaler oder gedruckter Form) vorlegen, aus der hervorgeht, dass sie geimpft wurden, ein negatives Testergebnis erhalten haben oder genesen sind. Zudem gilt die Maskenpflicht.',
    },
    SG_DESCRIPTION: {
      TEXT: 'Seit dem 13. Oktober 2021 können nur noch vollständig geimpfte Besucher in 2er-Gruppen eintreten. Vor dem Einlass muss ein Impf- oder Genesungsnachweis bzw. ein negatives COVID-19-Testergebnis vorgelegt werden.',
    },
    SHORT_HEADING: 'Beste Sicherheitsstandards vor Ort',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Your safety is our priority',
    TEXT: "We've taken significant steps to improve cleanliness using disinfectants with comprehensive and frequent surface cleaning. Crowds are also being controlled to prevent congestion.",
  },
  SAVE: '{0} % Rabatt',
  SAVE_PERCENT: '{0} % Rabatt',
  SAVE_UPTO: 'Spare',
  SAVE_UPTO_PERCENT: 'Bis zu {0} % Rabatt',
  SEARCH: 'Suchen',
  SEE_ALL: 'Alle ansehen',
  SEE_MORE_SHOWS: 'Weitere Shows anzeigen',
  SELECT_CITY: 'Stadt auswählen',
  SELECT_SECTION: 'Tribüne wählen',
  SEE_ALL_PHOTOS: 'Alle Fotos anzeigen',
  SHOW_CLOSED: 'Show geschlossen',
  SHOW_LESS_TEXT: 'Weniger anzeigen',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Die Show',
    ABOUT_THEATRE: 'Das Theater',
    ADDITIONAL_INFORMATION: 'Zusätzliche Informationen',
    AGE_LIMIT: 'Altersbeschränkung',
    AGE_SUITABILITY: 'Altersempfehlung',
    ANSWER: ['A-'],
    BLOG_SHOW_PAGE: 'Blog Show Page',
    BLOG_SUMMARY: 'Blog Zusammenfassung',
    BLOG_THEATRE_PAGE: 'Blog Theater Seite',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Theatersitzplan',
    CANCELLATION_AND_REFUNDS: 'Stornierung und Rückerstattung',
    CANCELLATION_POLICY: 'Stornierungsfrist',
    CAST_AND_CREW: 'Besetzung und Crew',
    CLOSING_DATE: 'Dernière',
    CLOSING_DATE_SPECIAL_OFFER: 'Dernière Sonderangebot',
    DURATION: 'Dauer',
    FACILITIES_AND_ACCESSIBILITY: 'Einrichtungen und Barrierefreiheit',
    FREQUENTLY_ASKED_QUESTIONS: 'Häufig gestellte Fragen',
    GETTING_THERE: 'Wegbeschreibung',
    GETTING_THERE_MAP_LINK: 'Wegbeschreibung Kartenlink',
    GOOGLE_MAP: 'Google Maps',
    HIGHLIGHTS: 'Highlights',
    LISTICLE_SHOW_SUMMARY: 'Listicle Show Zusammenfassung',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Show Highlights',
    OPENING_DATE: 'Premiere',
    QUESTION: ['F-'],
    SAFETY_BANNER: 'Sicherheitsbanner',
    SHOW_DETAILS: 'Details zur Show',
    SHOW_TIMINGS: 'Showzeiten',
    SHOW_TYPE: 'Art der Show',
    SPECIAL_OFFER: 'Sonderangebot',
    THE_STORY: 'Die Handlung',
    THEATRE_ADDRESS: 'Adresse',
    THEATRE_CAPACITY: 'Kapazität',
    THEATRE_NAME: 'Theater',
    TICKETS: 'Tickets',
    TICKETS_REDEMPTION: 'Ticket-Einlösung',
    TOP_SONGS: 'Top Songs',
    YOUR_TICKETS: 'Ihre Tickets',
    ABOUT_CONCERT: 'Das Konzert',
    PROGRAM: 'Programm',
  },
  SORT_BY: 'Sortieren nach',
  THEATRE: 'Theater',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Theater in der Nähe',
    NOW_PLAYING: 'Aktuelle Shows',
    UPCOMING_SHOWS: 'Kommende Shows',
    PAST_SHOWS: 'Vergangene Shows',
    FIND_BEST_SEATS: 'Bestplätze finden',
  },
  SPECIAL_OFFER: 'Sonderangebot',
  TICKET_CAN_BE_CANCELED:
    'Dieses Ticket kann bis zu {hours} Stunden vor dem Erlebnis gegen eine volle Rückerstattung storniert werden.',
  TICKET_CANNOT_BE_CANCELED:
    'Dieses Ticket kann nicht storniert, aber auf Anfrage verschoben werden.',
  TICKETS: 'Tickets',
  TIMINGS: 'Zeiten',
  SPECIAL_PRODUCT_HEADING: 'Beliebtestes Erlebnis',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Lokale Experten',
    ENGAGING_STORIES: 'Packende Stories',
    TOP_RATED: 'Top-Bewertungen',
  },
  GUIDED_TOUR_REVIEWS: [
    'Der Reiseleiter war sehr froh, Fragen über die Tour zu beantworten',
    'Die Organisation und unser Führer machten die Erfahrung sehr angenehm',
    'Die Tour war gut organisiert und hatte auch genau die richtige Dauer',
    'Gute Führung und gute Organisation! Werde ich weiterempfehlen!!!',
    'Die Tour verlief in einem guten Tempo und fühlte sich nicht gehetzt an',
    'Unsere Führerin Maria konnte uns die besten Aussichtspunkte besorgen',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Englisch',
    SPANISH: 'Spanisch',
    FRENCH: 'Französisch',
    ITALIAN: 'Italienisch',
    GERMAN: 'Deutsch',
    PORTUGUESE: 'Portugiesisch',
    NEDERLANDS: 'Niederländisch',
    POLISH: 'Polnisch',
    RUSSIAN: 'Russisch',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Tour verfügbar in {0}',
  GUIDES_BANNER: 'Authentische Erlebnisse mit unseren beliebten Reiseleitern.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Mit geführten Touren machen Sie das Beste aus Ihrer Reise. Unsere fachkundigen Reiseleiter sind Ihre Freunde vor Ort und verraten Ihnen Geschichten, Insidertipps und Reiseempfehlungen.',
    'Besuchen Sie eine Stadt nicht nur – erleben Sie sie!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Das sagen Reisende',
  TODAY: 'heute',
  TOMORROW: 'morgen',
  TOUR_LIST_HEADING: 'Wählen Sie Ihr Erlebnis',
  TOUR_LIST_SUB_HEADING:
    'Hier finden Sie zahlreiche Tickets, Touren und Kombinationen von geprüften Anbietern:',
  UGC: {
    FOLLOW: 'Folgen',
    FOLLOW_IG: 'Auf Instagram folgen',
    HEADING: 'POV: Dein nächstes Abenteuer sieht so aus',
    SUB_HEADING: 'Mit 💜 von Headout kuratiert',
  },
  UNAVAILABLE: 'Nicht verfügbar',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Diese Tickets sind für einen längeren Zeitraum gültig. Genaue Angaben befinden sich auf dem Ticket.',
    UNTIL_DATE: 'Diese Tickets sind bis zum {0} gültig.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Diese Tickets sind ab dem Kaufdatum {0} Tage gültig.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Diese Tickets sind ab dem Kaufdatum {0} Monate gültig.',
  },
  TABLE_OF_CONTENTS: 'Inhaltsverzeichnis',
  VIEW_LESS: 'Weniger anzeigen',
  VIEW_MORE: 'Mehr anzeigen',
  WHY_TAKE_THIS_DAY_TRIP: 'Die Vorteile dieses Tagesausflugs',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Hauptmenü',
    EXPLORE: 'Entdecken',
    VISIT: 'Besuchen',
    THINGS_TO_DO: 'Erlebnisse',
    CITY_ATTRACTIONS: '{0} Sehenswürdigkeiten',
    TOP_THINGS_TO_DO: 'Top-Erlebnisse',
    CITY_TOURS: '{0} Touren',
    CITY_GUIDE: 'City Guide',
    ATTRACTIONS: 'Attraktionen',
    CRUISES: 'Schifffahrten',
    THEMES: 'Themen',
    ABOUT: 'Über',
    TOURS: 'Touren',
    SKIP_THE_LINE: 'Schnelleinlass-Touren',
    GUIDED_TOURS: 'Geführte Touren',
    NIGHT_TOURS: 'Touren bei Nacht',
    FOOD_TOURS: 'Food Touren',
    HISTORY: 'Geschichte',
    ARCHITECTURE: 'Architektur',
    DESIGN: 'Design',
    INSIDE: 'Innen',
    COLLECTIONS: 'Sammlungen',
    PAINTINGS: 'Gemälde',
    ANIMALS_EXHIBITS: 'Tiere und Exponate',
    HABITATS: 'Lebensräume',
    CONSERVATION: 'Erhaltung',
    PROGRAMMES: 'Programme',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing-Fahrten',
    A2_DINNER_CRUISES: 'Dinner-Fahrten',
    A2_EVENING_CRUISES: 'Evening Cruises',
    A2_LUNCH_CRUISES: 'Mittagsfahrten',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Besuch planen',
    TIMINGS: 'Öffnungszeiten',
    DIRECTIONS: 'Anfahrt',
    PARKING: 'Parken',
    ROUTES: 'Routen',
    REQUIREMENTS: 'Anforderungen',
    LOCATION: 'Standort',
    RULES: 'Regeln',
    FAQs: 'FAQ',
    ENTRANCES: 'Eingänge',
    RESTAURANTS: 'Restaurants',
    FACTS: 'Fakten',
    TIPS: 'Tipps',
    MAP: 'Karte',
    RIDES: 'Fahrten',
    SHOWS: 'Shows',
    DINING: 'Gastronomie',
    SHOPPING: 'Shoppen',
    EVENTS: 'Events',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Weihnachten',
    NEW_YEARS_EVE: 'Silvester',
    TRAVEL_GUIDE: 'Reiseführer',
    TRIP_PLANNER: 'Reiseplaner',
    ITINERARY: 'Reiseprogramm',
    TRAVEL_TIPS: 'Reisetipps',
    WEATHER: 'Wetter',
    BEST_TIME_TO_VISIT: 'Beste Besuchszeit',
    JANUARY: 'Januar',
    FEBRUARY: 'Februar',
    MARCH: 'März',
    APRIL: 'April',
    MAY: 'Mai',
    JUNE: 'Juni',
    JULY: 'Juli',
    AUGUST: 'August',
    SEPTEMBER: 'September',
    OCTOBER: 'Oktober',
    NOVEMBER: 'November',
    DECEMBER: 'Dezember',
    WHERE_TO_EAT: 'Essen',
    WHERE_TO_STAY: 'Unterkünfte',
    NEIGHBOURHOODS: 'Viertel',
    FAMILY_TRAVEL: 'Familienreisen',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivals und Events',
  },
  WHY_WATCH: 'Auf einen Blick {0}?',
  FIND_ON_MAP: 'Auf der Karte anzeigen',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Tickets von der Theaterkasse',
        DESCRIPTION: 'Sofortige Bestätigung aufs Handy',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Beste Platzwahl`,
        DESCRIPTION: 'Immer die gewünschte Sicht',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Exklusive Deals und Rabatte',
        DESCRIPTION: `Die größten Shows zum kleinsten Preis`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Einfache Buchung',
        DESCRIPTION: '25 Millionen zufriedene Gäste',
      },
    },
    YOUR_PICK: 'Ihre Auswahl',
    BROWSE_BY_CATEGORIES: 'Kategorien durchstöbern',
    TOP_WEST_END_SHOWS: 'Die besten West End Shows',
    TOP_THEATRE_SHOWS: 'Die besten {0} Shows',
    TOP_SHOWS: 'Top-Shows',
    SEE_MORE_SHOWS: '{0} weitere Shows anzeigen',
    LAST_MINUTE_TICKETS: 'Last-Minute Tickets',
    LOVED_BY_MILLIONS: 'Millionen zufriedene Kunden',
    TODAY: 'Heute',
    TOMORROW: 'Morgen',
    SEE_ALL: 'Alle ansehen',
    GRAB_YOUR_TICKETS: 'Jetzt Tickets buchen',
  },
  TAG_NAME: {
    BALLET: 'Ballett',
    CABARET: 'Kabarett',
    CHRISTMAS: 'Weihnachten',
    CIRCUS: 'Zirkus',
    CLASSIC: 'Klassiker',
    COMEDY: 'Komödie',
    COMING_SOON: 'Demnächst verfügbar',
    CRITICS_CHOICE: "Critics' Choice",
    DANCE: 'Tanz',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasy',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Immersives Theater',
    JUKEBOX: 'Jukebox',
    KIDS: 'Kinder',
    MAGIC: 'Zaubershows',
    MUSICALS: 'Musicals',
    NEW_ARRIVAL: 'Neuheiten',
    OFF_WEST_END: 'Off West End',
    OLIVIER_WINNER: 'Olivier Preisträger',
    OPERA: 'Oper',
    PANTOMIMES: 'Englische Pantomime',
    PLAYS: 'Theater',
    ROMANCE: 'Romantik',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Stars on Stage',
    THEATRICAL_CONCERT: 'Theaterkonzert',
    TRUE_STORY: 'Wahre Begebenheiten',
    TONY_WINNER: 'Tony Awards-Gewinner',
    OFF_BROADWAY: 'Off Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Oh, das hat nicht geklappt',
    MESSAGE: `Schade! Alle Erlebnisse sind an diesem Datum ausverkauft oder nicht verfügbar. Keine Sorge – wir haben noch viele andere Termine zur Auswahl!`,
    CTA: 'Alle Daten anzeigen',
  },
  ALL_DATES: 'Alle Daten',
  BREADCRUMBS: {
    HOME: 'Home',
    TRAVEL_GUIDE: 'Reiseführer',
    THINGS_TO_DO: 'Erlebnisse in {0}',
    SHOW_NAME_TICKETS: '{0} - Tickets',
    LTT_HOME: 'London Theatre Tickets',
    LTT_VENUE_PAGE_HOME: 'Theater in London',
    BROADWAY_HOME: 'Broadway Tickets',
    BROADWAY_VENUE_PAGE_HOME: 'Theater am Broadway',
    VIENNA_CONCERT_HOME: 'Tickets für Wiener Konzerte',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Konzertsäle in Wien',
    ATTRACTIONS: 'Attraktionen',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing-Fahrten',
    A2_DINNER_CRUISES: 'Dinner-Fahrten',
    A2_EVENING_CRUISES: 'Evening Cruises',
    A2_LUNCH_CRUISES: 'Mittagsfahrten',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'London Theatre News',
    BROADWAY_SHOW_NEWS: 'Broadway News',
    NEWS_PAGE: 'Aktuelles',
    REVIEWS_PAGE_BANNER_HEADING: 'Rezensionen für {0}',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Café',
    'Dedicated Parking': 'Parkplätze vorhanden',
    Elevators: 'Fahrstuhl',
    Lift: 'Fahrstuhl',
    'Wheelchair Accessible': 'Rollstuhlgerecht',
    Cloakroom: 'Garderobe',
    'Air Conditioning': 'Klimatisiert',
    WiFi: 'WLAN',
    Bar: 'Bar',
    'Water Fountain': 'Trinkbrunnen',
    Washrooms: 'Toiletten',
    Toilets: 'Toiletten',
    Binoculars: 'Operngläser',
    'Adapted Toilets': 'Barrierefreie Toiletten',
    'Accessible Toilets': 'Barrierefreie Toiletten',
    'Assistive Listening System': 'Assistive Hörsysteme',
    'Hearing Assistance': 'Hörhilfen',
    'Booster Cushions': 'Sitzkissen für Kinder',
    Shop: 'Shop',
    'Souvenir Shop': 'Souvenirladen',
    'Guide Dogs': 'Blindenhundefreundlich',
    'Baby Changing Facilities': 'Wickelräume',
    'Security Check': 'Sicherheitskontrolle',
    Ramp: 'Rampe',
    'Level Access': 'Ebener Zugang',
  },
  CALENDAR: {
    FOOTNOTE: '* Alle Preise sind in {0}',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Originale Bewertung auf {0} anzeigen',
    VIEW_ORIGINAL_NO_LANG:
      'Diese Bewertung ist übersetzt. Originale Bewertung anzeigen.',
    TRANSLATE: 'Bewertung auf {0} übersetzen',
    LANGUAGES: {
      EN: 'Englisch',
      ES: 'Spanisch',
      FR: 'Französisch',
      IT: 'Italienisch',
      DE: 'Deutsch',
      PT: 'Portugiesisch',
      NL: 'Niederländisch',
    },
  },
  SHOW_PAGE_V2: {
    SELLING_OUT_FAST: 'Hohe Nachfrage',
    INTERVAL: 'Pause',
    TWO_PART_SHOW: 'Vorstellung in 2 Teilen',
    READ_MORE_REVIEWS: 'Weitere Bewertungen lesen',
    SHOW_MORE_REVIEWS: 'Weitere Bewertungen anzeigen',
    ALL_PHOTOS: 'Alle Fotos',
    MORE_DATES: 'Weitere Daten',
    SELECT_TIME_SLOT: 'Zeitfenster wählen',
    SELECT_TIME_SLOT_ERROR: 'Zeitfenster zum Fortfahren auswählen',
    PRICE_STARTING_FROM: 'Sitzplätze ab',
    SELECT_SEATS: 'Plätze auswählen',
    READ_MORE: 'Weiterlesen',
    RATINGS_AND_REVIEWS: 'Bewertungen und Rezensionen',
    READ_DETAILED_REVIEWS: 'Ausführliche Bewertungen lesen',
    UNTIL_DATE: 'Bis {0}',
    AVAILABLE_TIME: 'Verfügbare Zeit',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Dieses Erlebnis ist nur zur folgenden Zeit verfügbar',
    CONTENT_TABS: {
      ABOUT: 'Die Show',
      VENUE: 'Spielstätte',
      TICKETS: 'Tickets',
      Reviews: 'Bewertungen',
    },
    SELECT_SHOW_TIMMING: 'Showzeiten auswählen',
    ONLY_ONE_SLOT: 'Nur 1 Zeitfenster am gewählten Datum verfügbar',
    SIMILAR_SHOWS: 'Ähnliche Shows',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Handlung',
      AGE_SUITABILITY_AND_GUIDELINES:
        'Altersempfehlung und weitere Richtlinien',
      WHAT_CRITICS_THINK: 'Das sagen Kritiker',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Häufig gestellte Fragen',
      CAST_AND_CREATIVES: 'Besetzung und Crew',
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Fachkundige mehrsprachige Reiseleiter',
    STL: 'Schnelleinlass',
    PERSONALIZED: 'Personalisiertes Erlebnis',
    LOCAL_FOOD: 'Lokale Küche und Kultur erleben',
    MULTILINGUAL_GUIDES: 'Mehrsprachige Reiseleiter',
    CULINARY_EXPERTS: 'Kulinarische Experten treffen',
    SIGHTSEEING: 'Sightseeing + Unterhaltung an Bord',
    SIGHTSEEING_MEAL: 'Sightseeing und Essen an Bord',
    MULTILINGUAL_GT: 'Touren in mehreren Sprachen',
    AUDIOGUIDE_COMMENTARY: 'Mit Audioguide und Kommentaren',
    ALL_TOP_ATTRACTIONS_COVERED: 'Mit allen Top-Sehenswürdigkeiten',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Regelmäßige Abfahrten. Unbegrenzte Fahrten',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Last-Minute-Verfügbarkeit. Sofortbestätigung',
    MULTI_ROUTES: 'Mehrere Routenoptionen',
    HASSLE_FREE: 'Einfache Buchung',
    FREQUENT_DEPARTURES: 'Regelmäßige Abfahrten',
    ONBOARD_AMENITIES: 'Beste Ausstattung an Bord',
    FLEXI_TRAVEL: 'Flexibles Reisen auf mehreren Routen',
    FLEXI_EXCHANGE_CANCEL: 'Flexibler Umtausch und Stornierung',
    EXTRA_DISCOUNT: 'Extra-Rabatte für Jugendliche, Senioren und Familien',
    PREPAID: 'Prepaid-Komfort',
    EASY_ACTIVATION: 'Einfache Aktivierung',
    INSTANT_CONNECTIVITY: 'Sofortige Verbindung mit globaler Abdeckung',
    ROUND_TRIP: 'Hin- und Rücktransfers',
    CULTURAL_EXPERIENCE: 'Authentische kulturelle Erlebnisse',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
    LUGGAGE_ASSISTANCE: 'Hilfe mit Gepäck',
    TOP_ATTRACTIONS: 'Top-Attraktionen inklusive',
    FREQ_DEP_MULTI_ROUTE: 'Häufige Abfahrten auf mehreren Routen',
    CHARGING: 'Ladestation',
    WIFI: 'WLAN-Zugang',
    FnB: 'Speisen + Getränke verfügbar',
    LUXURY: 'Luxuserlebnis',
    FOOD_DRINK: 'Essen und Trinken',
    PANAROMIC: 'Panoramablick auf Top-Attraktionen',
    PANAROMIC_2: 'Panoramablicke',
    PANAROMIC_3: 'Panoramablicke vom offenen Deck',
    BEVERAGES: 'Getränke an Bord',
    GOURMET: 'Gourmet-Essen',
    GOURMET_2: 'Gourmetgerichte und Getränke',
    NIGHTTIME: 'Spektakuläre Aussichten bei Nacht',
    ROMANTIC: 'Romantisches Ambiente',
    TRANSFERS: 'Inklusive Transfer',
    CERTIFIED_OP: 'Zertifizierter Betrieb',
    BIRD_EYE: 'Malerische Aussichten',
    MULTI_JUMP: 'Mehrere Sprungzeiten',
    EXTREME_ADV: 'Extremes Abenteuer',
    PHOTO_OP: 'Malerische Fotomotive',
    TOP_ATTRACTIONS_COVERED: 'Top-Attraktionen entdecken',
    LOCAL_CULTURE: 'Lokale Kultur erleben',
    EXCLUSIVE_DISC: 'Exklusive Rabatte',
    EFFICIENT_PUBLIC_TRANSIT: 'Effizienter Nahverkehr',
    FREQUENT_SERVICE: 'Häufige Fahrten',
    PREBOOKING: 'Einfache Vorabbuchung',
    LOCAL_CULTURE_IMM: 'Lokale Kultur erleben',
    DISCOVER_HIDDEN: 'Geheimtipps entdecken',
    CITY_SIGHTSEEING: 'Sightseeing in der Stadt',
    OFFBEAT_ADV: 'Ausgefallenes Abenteuer',
    DRINK_DEALS: 'Getränke Deals',
    OFFBEAT_EXP: 'Ausgefallenes Erlebnis',
    MULTIPLE_VARIETIES: 'Mehrere Sorten inklusive',
    HIDDEN_GEMS: 'Geheimtipps und ausgefallene Attraktionen',
    EXPLORE_LOCAL: 'Lokale Viertel entdecken',
    CUSTOMIZED_TREATMENTS: 'Personalisierte Behandlungen',
    TRAINED_THERAPISTS: 'Ausgebildete Therapeuten',
    HOLISTIC_WELLNESS: 'Pures Wohlfühlerlebnis',
    FLEXIBLE_DURATION: 'Flexible Dauer',
    MULTI_BOAT: 'Verschiedene Boote verfügbar',
    SCENIC_ROUTES: 'Malerische Routen',
    HANDS_ON: 'Praktisches Lernen',
    CULTURAL_CULINARY: 'Kulturelle und kulinarische Einblicke',
    EXPERT_HOSTS: 'Fachkundige Gastgeber',
    ADVENTURE_EXPERIENCE: 'Abenteuererlebnis',
    EQUIPMENT: 'Inklusive Ausrüstung',
    SCENIC_FLYOVERS: 'Sorgenfreie Überführung',
    LIVE_COMMENTARY: 'Live-Kommentar',
    BEST_AERIAL_VIEWS: 'Die besten Flugaussichten',
    SAFE_CERT_OP: 'Sicherer, zertifizierter Betrieb',
    HANDPICKED: 'Erlesene Touroptionen',
    EFFORTLESS: 'Einfache Planung',
    EXPERT_GUIDES: 'Einzigartige Einblicke durch Experten',
    ALL_ATTR_ONE_CARD: 'Alle Attraktionen mit einer Karte',
    MULTI_CARD: 'Verschiedene Karten zur Auswahl',
    COST_EFF: 'Kostengünstig und praktisch',
    EASY_BEST: 'Einfache Buchung zu Bestpreisen',
    INSTANT_MOBILE: 'Sofortige digitale Tickets',
    MULTI_TRANSPORT: 'Verschiedene Transferdienste',
    BEST_PRICES: 'Bestpreise',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Alle',
    POPULAR_SUBCATEGORY: 'Beliebte {0}',
    TOP_CATEGORY: 'Top-{0}',
    ATTRACTIONS: 'Attraktionen',
    ALL_SUBCATEGORY: 'Alle {0}',
    BROWSE_BY_CATEGORIES: 'Kategorien durchstöbern',
    TICKETS_FROM: 'Tickets ab',
    PRICE_LOW_HIGH: 'Preis (niedrigster zuerst)',
    PRICE_HIGH_LOW: 'Preis (höchster zuerst)',
    FILTERS: 'Filter',
    RESET: 'Zurücksetzen',
    APPLY: 'Anwenden',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout verwendet Cookies, um Ihnen eine bessere Nutzererfahrung zu bieten.',
    MOBILE: 'Wir verwenden Cookies.',
    LEARN_MORE: 'Mehr Infos.',
  },
  SHOW_UNAVAILABLE: 'Show nicht verfügbar',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Hervorgehoben',
    ALL_NEWS: 'Alle Neuigkeiten',
    MORE_READS: 'Weitere Artikel',
    LOAD_MORE: 'Weitere Artikel laden',
    TRAILERS: 'Alle Trailer',
    GET_YOUR_TICKETS: 'Tickets buchen',
    POPULAR_SHOWS: 'Beliebte Shows',
    MAILER: {
      HEADING:
        'Deals und Neuigkeiten der Theaterwelt direkt zu Ihrem Posteingang',
      SUBHEADING: `Abonnieren Sie unseren Newsletter, um Neuigkeiten und Angebote für Shows vor allen anderen zu erhalten!`,
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: 'Rezensionen für {0}',
    REVIEWS_COUNT: '{0} Rezensionen',
    AWESOME: 'Ausgezeichnet',
    GOOD: 'Gut',
    AVERAGE: 'Mittelmäßig',
    POOR: 'Schlecht',
    TERRIBLE: 'Furchtbar',
    REVIEW_BY_HEADOUT: 'Unsere Meinung – Rezension von Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Von anderen Gästen',
    MOST_RELEVANT: 'Relevanteste',
    RATING_HIGH_TO_LOW: 'Höchste Rezension',
    RATING_LOW_TO_HIGH: 'Niedrigste Rezension',
    CRITIC_REVIEWS: 'Rezensionen von Kritikern',
    USER_REVIEWS: 'Rezensionen von Nutzern',
    CONTRIBUTORS_REVIEW: 'Rezension des Verfassers',
  },
  HOHO: {
    HOHO: 'Hop-on Hop-off Tickets',
    BUS_ROUTES_DETAILS: 'Routen',
    TOUR_DETAILS: 'Details zur Tour',
    ROUTES_SCHEDULES: 'Routen und Fahrpläne',
    VALIDITY: 'Gültig für 1 Tag',
    VALIDITY_NOTE:
      'Ihr Erlebnis ist für {0} Kalendertag/e gültig. Wenn Sie Ihr Ticket für den 06.05.2023 buchen, ist es bis zum 06.05.2023 um 21:00 Uhr PST gültig.',
    BESTSELLER: 'Bestseller',
    SEE_ALL: 'Alle anzeigen',
    TIMINGS: 'FAHRZEITEN',
    FREQUENCY: 'HÄUFIGKEIT',
    DURATION: 'DAUER',
    STARTING_LOCATION: 'Startpunkt',
    CALENDAR_FOOTNOTE: '* Alle Preise sind in {0}',
    TOUR_TIMINGS: 'Tourzeiten',
    TOUR_FREQUENCY: 'Häufigkeit',
    GOT_IT: 'Alles klar',
    SELECT_DATE: 'Select a date',
    SELECT_TOUR: 'Select Tour Type',
    VIEW_TOUR_DETAILS: 'View tour details',
    BUS_DETAILS: 'MORE DETAILS',
    VIEW_ROUTES: 'View all routes',
    BUS_ROUTES: 'BUS ROUTES',
    ATTRACTIONS_PREVIEW: 'Fastest way to view {0}+ top attractions including',
    ROUTES: 'Routen',
    COMBO_SUBTITLE: 'Sparen Sie mehr mit',
    COMBO_TITLE: 'Kombi-Angebote für Ihre Hop-on-Hop-off-Tour',
    COMBO_DWEB_TITLE:
      'Sparen Sie mehr mit Kombi-Angeboten für Ihre Hop-on-Hop-off tour',
    STOPS_AND_ATTRACTIONS: 'Haltestellen und Attraktionen',
    HOP_ON_OFF_AT: 'Steigen Sie an diesen {0} Stationen ein/aus',
    TIMINGS_FREQUENCY: 'Fahrzeiten und Häufigkeit',
    TOUR_DURATION: 'Dauer der Tour',
    EVERY_X_MINS: 'Every {0}',
    VIEW_LOCATION: 'Standort anzeigen',
    BANNER_SUBTEXT:
      'Die bequemste und schnellste Art, um alle Wahrzeichen der Stadt zu sehen.',
    TOP_ATTRACTIONS: 'Top-Attraktionen',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Last-Minute Buchung',
        DESCRIPTION: 'Sofortige Bestätigung aufs Handy',
      },
      COST_EFF: {
        NAME: 'Günstiges Erkunden',
        DESCRIPTION: 'Mehrere Wahrzeichen mit einem Ticket',
      },
      DAILY_RIDES: {
        NAME: 'Täglich unbegrenzte Fahrten',
        DESCRIPTION: 'Entdecken Sie die Stadt in Ihrem Tempo',
      },
      BOOK_RELAX: {
        NAME: 'Buchen und entspannen',
        DESCRIPTION: '22 Millionen zufriedene Gäste',
      },
    },
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Privattransfers',
    SHARED_TRANSFERS: 'Gemeinschaftstransfers',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Online buchen',
        DESCRIPTION: 'Buchen Sie Ihre Tickets schnell und bequem online.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Sofortbestätigung',
        DESCRIPTION:
          'Sie erhalten eine sofortige Buchungsbestätigung für Ihren Flughafentransfer.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Bequeme Abholung',
        DESCRIPTION:
          'Vergessen Sie lange Wartezeiten. Ihr Fahrzeug wartet bereits am gewählten Abholort auf Sie.',
      },
      DROP_OFF: {
        TITLE: 'Ankunftsort',
        DESCRIPTION: 'Sie erreichen Ihr Ziel schnell und komfortabel.',
      },
    },

    SHARED_TRANSFERS_IN: 'Gemeinschaftstransfers in {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      'Bequeme und kostengünstige Transferdienste für mehrere Fahrgäste, die zu oder von einem Flughafen reisen.',
    PRIVATE_TRANSFERS_IN: 'Privattransfers in {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      'Bequeme und direkte Transferdienste für Einzelpersonen oder kleine Gruppen, die zu und von einem Flughafen reisen.',
    ANYWHERE_IN_THE_CITY: 'Überall in der Stadt',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Verschiedene Fahrzeugoptionen',
      FREE_CANCELLATION: 'Kostenlose Stornierung',
    },
    SEAMLESS_TRANSFERS:
      'Reibungslose und zuverlässige Transfers auf der ganzen Welt',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Wählen Sie den besten Flughafentransfer für Sie',
    HASSLE_FREE_TRANSFER: 'Reibungsloser Flughafentransfer',

    // New experiment (AT LP)
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Bequeme Flughafentransfers in {0} mit dem',
    BUSES: 'Bus',
    TRAINS: 'Zug',
    PRIVATE_TAXIS: 'einem Privattaxi',
    BUS_TRAIN: 'Bus/Zug',
    PRIVATE_TAXI: 'Privattaxi',

    FROM: 'Von',
    TO: 'Nach',
    SELECT_PICKUP: 'Abholort auswählen',
    SELECT_DROPOFF: 'Zielort auswählen',
    ENTER_DESTINATION: 'Zielort angeben',
    ENTER_PICKUP: 'Abholort eingeben',
    PICKUP_DATE: 'Abholdatum',
    SELECT_DATE: 'Datum wählen',
    PICKUP_TIME: 'Abholzeit',
    SELECT_TIME: 'Zeit wählen',
    GUESTS: 'Gäste',
    GUEST: 'Gast',

    ADD_GUESTS: 'Anzahl Gäste',

    EXPLORE_TRANSFERS: 'Erkunden Sie Transfers und mehr',
    COMBOS_AND_EXTRAS: 'Kombi-Deals',

    YOUR_RIDE_DOORSTEP: 'Ihre Fahrt, direkt von Ihrer Haustür',
    COMFORTABLE_RIDE:
      'Buchen Sie ein bequemes Privattaxi zu und von den Hauptflughäfen in {0}',
    TRUSTED_DRIVERS: 'Zuverlässige Fahrer',
    RIDES_24_7: 'Fahrten rund um die Uhr',
    FLIGHT_TRACKING: 'Live-Flugstatus für Fahrer',
    KNOW_MORE: 'Weitere Infos',
    RESERVE_YOUR_RIDE: 'Fahrt reservieren',
    TRANSFER_OPTIONS: 'Gefundene Transfers',
    TRANSFERS_AVAILABLE_PLURAL: '{0} Transfers verfügbar',
    TRANSFERS_AVAILABLE_SINGULAR: '1 Transfer verfügbar',

    TRUSTED_PARTNERS: 'Über 35 zuverlässige Partner {0}',
    WORLDWIDE: 'weltweit',
    COMFORTABLE_RIDES: 'Komfortable Fahrten',
    FREQUENT_DEPARTURES: 'Häufige Abfahrten',
    MULTIPLE_TRANSPORT_OPTIONS: 'Zahlreiche Transferoptionen',
    AND_MANY_MORE: 'Und viele mehr',

    ADD_PICKUP_LOCATION: 'Abholort angeben',
    ADD_DROPOFF_LOCATION: 'Zielort angeben',
    SELECT_PICKUP_DATE_AND_TIME: 'Abholdatum und -zeit auswählen',
    SELECT_A_DATE: 'Datum auswählen',

    TRAIN_STATION: 'Bahnhof',
    BUS_STOP: 'Bushaltestelle',

    ADD_RETURN: 'Rückfahrt hinzufügen',
    HEADS_UP: 'Achtung!',
    ADDED_RETURN_TRIP: 'Sie haben eine Rückfahrt hinzugefügt.',
    RETURN_NOTE:
      'Die Details zur Rückfahrt werden in den nächsten Schritten angezeigt.',
    OKAY_I_UNDERSTAND: 'Alles klar',

    SERVING_GUESTS: 'Mehr als {0} aus über {1} weltweit',
    GUESTS_COUNT: '220.000 zufriedene Gäste',
    CITIES_COUNT: '55 Städten',
    PARNTER_WITH_BEST:
      'Wir arbeiten mit den besten Partnern zusammen, um Ihnen ein perfektes Erlebnis zu bieten. Wir kümmern uns um den Transfer – Sie lehnen sich zurück und genießen die Fahrt.',
  },
  PC_EXP: {
    SHOW_INCL: 'Inklusivleistungen und wichtige Infos',
    CLEAR: 'Zurücksetzen',
    ALL_EXPERIENCES: 'Alle Erlebnisse',
    FILTER_BY_CATEGORIES: 'Nach Kategorien filtern',
    CATEGORIES: 'Kategorien',
    COMBOS: {
      HEADING: 'Alle guten Dinge sind zwei. Genau wie unsere Kombi-Erlebnisse.',
      DESCRIPTOR_1: 'Super Sparangebote',
      DESCRIPTOR_2: 'Bessere Reiseplanung',
    },
  },
  TOP: 'Top-{0}',
  VIEW_CALENDAR: 'Kalender anzeigen',
  SHOWS_CALENDAR: 'Show-Kalender',
  IN: 'im',
  SEATS: 'Plätze',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Inhaltsverzeichnis',
    QUICK_INFORMATION: 'Schnelle Infos',
    PEAK: 'Stoßzeiten',
    OFF_PEAK: 'Nebenzeiten',
    ADDRESS: 'ADRESSE',
    RECOMMENDED_DURATION: 'EMPFOHLENE DAUER',
    VISITORS_PER_YEAR: 'BESUCHER PRO JAHR',
    NUMBER_OF_ENTRANCES: 'ANZAHL DER EINGÄNGE',
    EXPECTED_WAIT_TIME_STANDARD: 'VORAUSSICHTLICHE WARTEZEIT – STANDARD',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE:
      'VORAUSSICHTLICHE WARTEZEIT – SCHNELLEINLASS',
    UNESCO_YEAR: 'UNESCO BEITRITTSJAHR',
    ARCHITECTURE_STYLE: 'ARCHITEKTURSTIL',
    TIMINGS: 'Zeiten',
    SIZE_HEIGHT: 'GRÖSSE/HÖHE',
    TICKETS: 'TICKETS',
    FUN_FACTS: 'Lustige Fakten',
    DID_YOU_KNOW: 'Schon gewusst?',
    MORE_INTERESTING_FACTS: 'Weitere interessante Fakten',
    PLAN_YOUR_VISIT: 'Besuch planen',
    ALSO_KNOWN_AS: 'Auch bekannt als',
    FOUNDED_ON: 'Gegründet auf',
    FOUNDED_BY: 'Gegründet von',
    FROM: 'Ab',
    CLOSED_TODAY: 'Heute geschlossen',
    TODAY: 'Heute',
    CLOSED: 'Geschlossen',
    OPEN: 'Geöffnet',
    LAST_ADMISSION: 'Letzter Einlass',
    DAYS: 'Tage',
    BEST_TIME_TO_VISIT: 'Beste Besuchszeit:',
    WEEKDAY_VS_WEEKEND: 'Wochentag vs Wochenende',
    PEAK_VS_LOW_SEASON: 'Hochsaison vs Nebensaison',
    PLEASANT: 'Angenehm',
    CROWDED: 'Überfüllt',
    VERY_CROWDED: 'Sehr überfüllt',
    LOW_SEASON: 'Nebensaison',
    MID_SEASON: 'Mittelsaison',
    PEAK_SEASON: 'Hochsaison',
    TO: 'BIS',
    LOWER_TO: 'bis',
    LAST_ENTRY: 'letzter eintrag',
    SUBATTRACTIONS: 'Unterattraktionen',
    INCLUDED_WITH_TICKETS: 'In den {0} Tickets enthalten',
    INCLUDED_WITH_SOME_TICKETS: 'In manchen {0} Tickets enthalten',
    EXPLORE_ALL_POI_TICKETS: '{0} & {1} tickets und touren',
    OPERATING_HOURS: 'Öffnungszeiten',
    SEE_MORE: 'Mehr anzeigen',
    MORE_INSIGHTS: 'Mehr Einblicke',
    SELECT_YOUR_EXPERIENCE: 'Wählen Sie Ihr Erlebnis aus',
  },
  OFF_PERCENT: '{0} % Rabatt',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Sitzplan',
    CAPACITY: 'Zuschauer: {0} Plätze',
    WHATS_ON: 'Programm',
    CATEGORIES: 'Kategorien',
  },
  NEXT: 'Weiter',
  PREVIOUS: 'Zurück',
  ITINERARY: {
    TAB: 'Plan',
    HEADING: 'Erlebnisplan',
    VIEW_ITINERARY: 'Plan anzeigen',
    PASSES_BY_SECTION_HEADING: 'Entlang der Route',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Highlights',
      NEARBY_THINGS_TO_DO: 'Erlebnisse in der Nähe',
      THINGS_TO_DO: 'Erlebnisse',
    },
    STOP_CARD: {
      TITLE: {
        START: 'STARTPUNKT',
        END: 'ENDPUNKT',
        STARTING_POINT: 'STARTPUNKT',
        STOP: 'HALTEPUNKT',
        ENDING_POINT: 'ENDPUNKT',
        PASSING_BY: 'TEIL DER ROUTE',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} Startpunkte verfügbar',
        END: '{0} Endpunkte verfügbar',
      },
    },
    GET_DIRECTION: 'Wegbeschreibung',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} Std. {1} Min.',
        WITHOUT_HOURS: '{0} Min.',
        WITHOUT_MINS: '{0} Std.',
      },
      ATTRACTIONS_COUNT: '{0} Attraktionen',
      ACTIVITIES_COUNT: '{0} Aktivitäten',
      TOTAL_DURATION: 'Gesamtzeit',
      FREQUENCY: 'Häufigkeit',
      FIRST_DEPARTURE: 'Erste Abfahrt',
      LAST_DEPARTURE: 'Letzte Abfahrt',
      FIRST_DEPARTURE_TIME: 'Erste Abfahrtszeit',
      LAST_DEPARTURE_TIME: 'Letzte Abfahrtszeit',
      MODE_OF_TRANSPORT: 'Transportmittel',
      FOOD_AND_DRINKS: 'Essen und Getränke',
    },
    WALK_DURATION: '{0} zu Fuß',
    MORE: '{0} mehr',
    TIMELINE_VIEW: 'Zeitstrahl',
    MAP_VIEW: 'Karte',
    MAP_OVERLAY: 'Verschieben Sie die Karte mit Strg/⌘ + scrollen',
    VIEW_EXPERIENCE_MAPPED_OUT:
      'Schauen Sie sich Ihr Erlebnis auf der Karte an.',
    OPEN_MAP_VIEW: 'Karte öffnen',
    START_POINT_SAME_AS_END_POINT:
      'Der Endpunkt ist derselbe wie der Startpunkt',
  },
  CRUISES: {
    BANNER_HEADING: 'Schifffahrten in {0}: entdecken, essen, entspannen',
    FILTERS: {
      ALL: 'Alle',
      SIGHTSEEING: 'Sightseeing',
      LUNCH: 'Mittagessen',
      DINNER: 'Abendessen',
      COMBOS: 'Kombitickets',
    },
    MAP_OVERLAY: 'Verschieben Sie die Karte durch Klicken oder Tippen',
    SIGHTS_COVERED: 'Sehens- würdigkeiten',
    MENU: 'Speise- karte',
    BOARD_AT: 'Boarding: {0}',
    BOARDING_POINTS_AVAILABLE: '{0} mögliche Einstiegsstellen',
    VIEW_POPULAR_SIGHTS: 'Beliebte Sehenswürdigkeiten: {0} {1}',
    X_BOARDING_POINTS: '{0} Einstiegsstellen',
    BOARDING_POINT: 'Einstiegsstelle',
    BOARDING_POINTS: 'Einstiegsstellen',
    LANDMARKS: 'Wahrzeichen',
    GET_DIRECTIONS: 'Wegbeschreibung',
    FOOD_MENU: 'Speisekarte',
    X_PAGE: '{0} Seite',
    X_PAGES: '{0} Seiten',
    MORE: 'und {0} weitere',
    PDF: {
      ZOOM_IN: 'Heranzoomen',
      ZOOM_OUT: 'Herauszoomen',
      FIT_TO_WIDTH: 'Vollbild',
      RESET_ZOOM: 'Zoom zurücksetzen',
    },
    COMBO_HEADING: 'Mehr für weniger: Kombideals und City Cards',
  },
  CUSTOM_CTA_EXPERIMENT_TEXT: 'Tickets buchen',
};

export default de;
