const es = {
  AUDIO_GUIDE: {
    BANNER: 'Audioguía gratuita',
    PRODUCT_SUFFIX: 'con audioguía',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Colaborador autorizado y de confianza',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Distribuidor autorizado',
    SUB_TEXT:
      'Experiencias auténticas proporcionadas por socios autorizados y de confianza.',
  },
  AVAILABLE: 'Disponible',
  BANNER_CTA: 'Comprar entradas',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout es una marca en la que confían millones de clientes de todo el mundo y que ofrece las mejores experiencias para disfrutar de esta atracción.',
    NON_PARTNERED_SENSITIVE:
      'Headout es una marca en la que confían millones de clientes de todo el mundo y que ofrece experiencias seleccionadas para disfrutar de esta atracción. Este no es el sitio web del recinto.',
    PARTNERED_NON_SENSITIVE:
      'Headout es un socio autorizado y de confianza que ofrece las mejores experiencias para disfrutar de esta atracción.',
    PARTNERED_SENSITIVE:
      'Headout es un socio autorizado y de confianza que ofrece experiencias seleccionadas para disfrutar de esta atracción. Este no es el sitio web del recinto.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout es un socio de confianza de la atracción, autorizado para ofrecer una selección de las mejores experiencias.',
  BOOK_NOW_CTA: 'Reserva ahora',
  BUY_TICKETS_CTA: 'Comprar entradas',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Puedes cancelar estas entradas hasta {0} horas antes del comienzo de la experiencia y recibir un reembolso completo.',
    CANCELLABLE_ANYTIME:
      'Cancelación gratuita en cualquier momento antes del comienzo de tu experiencia',
    CANCELLABLE_DAYS:
      'Puedes cancelar estas entradas hasta {0} días antes del comienzo de la experiencia y recibir un reembolso completo.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Estas entradas no se pueden cancelar. Sin embargo, son válidas durante un periodo de tiempo prolongado.',
    HEADING: 'Política de modificaciones',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Estas entradas no se pueden cancelar. Sin embargo, se pueden reprogramar hasta {0} horas antes del comienzo de la experiencia.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Estas entradas no se pueden cancelar ni reprogramar.',
    VALID_UNTIL_DATE:
      'Estas entradas no se pueden cancelar. Sin embargo, puedes utilizarlas en cualquier momento hasta el {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Estas entradas no se pueden cancelar. Sin embargo, puedes utilizarlas en cualquier momento dentro de los siguientes {0} días.',
    VALID_WITHIN_NEXT_MONTHS:
      'Estas entradas no se pueden cancelar. Sin embargo, puedes utilizarlas en cualquier momento dentro de los próximos {0} meses.',
  },
  CANCELLATION_POLICY_HEADING: 'Política de cancelación',
  CASHBACK: '{0} % en Cashback',
  CASHBACK_INFO:
    'Recibirás <strong>{0} %</strong> en créditos al reservar esta experencia. Los créditos se agregarán automáticamente a tu cuenta de Headout y los podrás usar para futuras reservas con nosotros.',
  CATEGORY_SLIDER_HEADING:
    'Los clientes que reservaron este espectáculo también vieron',
  CHECK_AVAIL: 'Ver disponibilidad',
  CITY_PAGE: {
    BANNER_TITLE: 'Vive lo mejor de',
    TOP_ATTRACTIONS: 'Atracciones principales',
    GO_BEYOND: 'Explorar más allá de {0}',
    ALL_DAY_TRIPS: 'Ver todas las excursiones de un día',
    CITIES_NEARBY: 'Ciudades cercanas',
    POPULAR_CATEGORIES: 'Categorías populares',
    GO_TO_GUIDE: 'Guía para ir a {0}',
    VIEW_TRAVEL_GUIDE: 'Ver guía de viaje',
    EXPLORE: 'Explora {0}',
    GUIDE_SUBHEADING:
      '¡Explorar {0} nunca ha sido tan fácil! Nuestra guía de viaje a {0} tiene todo lo que necesitas saber sobre la ciudad, desde qué comer y qué ver hasta cómo llegar, dónde alojarte y ¡mucho más!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Información general',
      WHERE_TO_EAT: 'Qué comer',
      WHERE_TO_STAY: 'Dónde alojarse',
      THINGS_TO_DO: 'Qué hacer',
      WEATHER: 'Mejor época para ir',
      NEIGHBOURHOODS: 'Barrios',
      TRANSPORTATION: 'Cómo moverse',
      TRIP_PLANNER: 'Plan de viaje',
      FAMILY_TRAVEL: 'Viajar con niños',
      TRAVEL_TIPS: 'Consejos de viaje',
      SHOPPING: 'Compras',
      ART_AND_CULTURE: 'Arte y cultura',
    },
    MAILER: {
      HEADING:
        'Inspiración para viajar a {0} directamente en tu bandeja de entrada',
      SUBHEADING:
        'Explora nuevas ciudades con experiencias seleccionadas, cashback al instante, ofertas exclusivas y consejos esenciales de viaje.',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Infórmate sobre los requisitos de visado, el cambio de moneda, las diferencias horarias y mucho más para asegurarte una llegada sin complicaciones y una estancia agradable.',
    WHERE_TO_EAT:
      'Deléitate con la exquisita escena culinaria, probando distintos sabores y disfrutando de las delicias locales en cada rincón de {0}.',
    WHERE_TO_STAY:
      'Descubre los mejores alojamientos en {0}, que ofrecen comodidad, confort y una experiencia memorable para tu estancia.',
    THINGS_TO_DO:
      'Experimenta una variedad de emocionantes actividades y atracciones para todos los gustos que garantizan momentos inolvidables.',
    WEATHER:
      'Planifica bien tu viaje y aprovecha al máximo tu visita, ya que {0} ofrece experiencias estupendas durante todo el año.',
    NEIGHBOURHOODS:
      'Conoce las diferentes comunidades locales y los vibrantes barrios que dan a {0} su carácter único.',
    TRANSPORTATION:
      'Desplázate por {0} con facilidad utilizando su eficaz sistema de transporte, que ofrece cómodas opciones para explorar todas sus atracciones.',
    TRIP_PLANNER:
      'Aprovecha al máximo tu tiempo en {0} con itinerarios seleccionados que te permiten sacar el mayor partido a cada momento.',
    FAMILY_TRAVEL:
      'Vive una aventura con numerosas atracciones aptas para ir en familia, parques y opciones de entretenimiento para niños de todas las edades.',
    TRAVEL_TIPS:
      'Descubre consejos de viaje para hacer que tu visita a {0} sea excepcional.',
    SHOPPING:
      'Explora un paraíso de compras con una gran variedad de boutiques, mercados y centros comerciales, que ofrecen desde artesanía local hasta moda de alta costura.',
    ART_AND_CULTURE:
      'Sumérgete en la escena artística y cultural, desde cautivadores museos a vibrantes festivales que resaltan el patrimonio de {0}.',
  },
  CLOSE: 'Cerrar',
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Utilizamos cookies y tecnologías similares para muchos propósitos, entre ellos mejorar tu experiencia en nuestra página web y personalizar nuestros anuncios.',
    MANAGE_PREFERENCES: 'Ajustes',
    PREFERNCES_SAVED: 'Se han guardado tus preferencias',
    ACCEPT: 'Aceptar',
    ALLOW_ALL: 'Permitir todo',
    DENY_ALL: 'Denegar todo',
    COOKIES: 'Galletas:',
    HEADING: 'Siempre valoramos su privacidad',
    DESCRIPTION: `*   Las cookies son pequeños archivos colocados en su ordenador, dispositivo móvil o cualquier otro dispositivo por el sitio web/plataforma, que contienen los detalles de su historial de navegación entre sus muchos usos.
*   Utilizamos diferentes tipos de cookies para hacer un seguimiento de su uso de nuestra plataforma y almacenar cierta información que nos ayuda a ofrecerle servicios más personalizados. Algunas cookies pueden instalarse en su dispositivo debido a su uso de los servicios disponibles en nuestra plataforma.
*   A grandes rasgos, utilizamos dos conjuntos diferentes de tecnologías bajo este epígrafe:
    *   **Cookies o Cookies de Navegador.** Es un pequeño archivo que se coloca automáticamente en Su Dispositivo cuando Usted accede a Nuestra Plataforma. Puede indicar a su navegador que rechace todas las Cookies. En caso de que no acepte nuestras cookies, es posible que no pueda utilizar algunas partes de nuestra plataforma.
    *   **Balizas web.** También denominados gifs transparentes, etiquetas de píxel y gifs de píxel único que se adjuntan en varias secciones de nuestra plataforma y nuestros correos electrónicos y que nos permiten supervisar y comprender la actividad de los usuarios.
*   Estas Cookies almacenadas en su dispositivo pueden ser "persistentes" o "de sesión". Las Cookies persistentes son las que permanecen en su dispositivo incluso cuando se desconecta, mientras que las Cookies de sesión se eliminan automáticamente en cuanto cierra su navegador web.
*   Utilizamos tanto cookies de sesión como cookies persistentes para los fines que se indican a continuación:
    *   Cookies necesarias / esenciales
        *   _Tipo:_ Cookies de sesión
        *   _Finalidad:_ Estas Cookies son esenciales para que Usted pueda acceder a diferentes secciones de la Plataforma y, si no se permiten, es posible que no pueda acceder a los servicios disponibles en la Plataforma. Además, estas cookies nos ayudan a autenticar a los Usuarios y a evitar cualquier tipo de actividad fraudulenta en la Plataforma.
    *   Política de Cookies / Aviso Aceptación Cookies
        *   _Tipo:_ Cookies persistentes
        *   _Finalidad:_ Estas Cookies identifican si los Usuarios han aceptado el uso de Cookies.
    *   Cookies de funcionalidad
        *   _Tipo:_ Cookies persistentes
        *   _Finalidad:_ Estas Cookies nos permiten recordar las elecciones que realiza cuando utiliza la Plataforma, como recordar sus datos de inicio de sesión o su preferencia de idioma. El objetivo principal de estas Cookies es proporcionarle una experiencia más personalizada cada vez que utilice la Plataforma.

_Todos los términos utilizados en mayúsculas se definen en la Política de privacidad. Para más información, consulte_ [_la Política de privacidad_](/privacy-policy/)`,
  },
  COLLECTION_SLICE_HEADING: 'Las mejores cosas que hacer en {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Seleccionar',
    SELECT_PREFERENCE: 'Selecciona la opción deseada',
    SELECT_OPTION: 'Selecciona la opción deseada',
    SELECT_TICKET: 'Selecciona tu entrada',
  },
  COMPARE_ALL_DETAILS: 'Compara los detalles',
  COVID19_ALERT: {
    KEY_TEXT: 'Aviso COVID-19',
    LINK: 'https://medium.com/headout/epidemia-de-coronavirus-pol%C3%ADtica-de-cancelaci%C3%B3n-e577f63d5553',
    TEXT: 'Tú eres nuestra prioridad. Por favor, consulta nuestra página de ayuda para conocer las últimas actualizaciones sobre las políticas de cancelación.',
  },
  CURRENCY: 'Monedas',
  CUSTOMER_REVIEW_HEADING: 'Reseñas de los clientes',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioguía',
    DURATION: 'Duración: {0}',
    EXTENDED_VALIDITY: 'Validez ampliada',
    FLEXIBLE_DURATION: 'Duración flexible',
    FREE_CANCELLATION: 'Cancelación gratuita',
    GUIDED_TOUR: 'Visita guiada',
    HOTEL_PICKUP: 'Traslados de Hotel',
    INSTANT_CONFIRMATION: 'Confirmación instantánea',
    MEALS_INCLUDED: 'Comidas incluidas',
    MOBILE_TICKET: 'Entradas en el móvil',
    SKIP_THE_LINE: 'Acceso sin colas',
    TRANSFERS: 'Traslados incluidos',
  },
  DURATION: 'Duración',
  EARLIEST_AVAILABILITY: 'Siguiente disponible',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Introduce aquí tu correo electrónico',
    SIGN_UP: 'Suscribirme',
    THANK_YOU: '¡Gracias!',
    SUBSCRIBED_MSG: 'Te has suscrito',
    ERROR_MSG: 'Introduce un correo electrónico válido',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Entradas para el teatro en Broadway',
    },
    LTT: {
      MB_NAME: 'Entradas para el teatro en Londres',
    },
  },
  EXCLUSIONS: 'No incluye',
  FEATURE_CARD: {
    HEADING_CUSTOMER: 'Más de 10 millones',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100% seguro',
    HEADING_SUPPORT: 'Centro de atención al cliente 24/7',
    SUB_HEADING_CUSTOMER:
      'de clientes satisfechos que han disfrutado de más de 10 000 experiencias',
    SUB_HEADING_RATING:
      'Más de 5000 experiencias cuentan con una puntuación excelente del 90%',
    SUB_HEADING_SAFE: 'Todas las actividades al aire libre son 100% seguras',
    SUB_HEADING_SUPPORT:
      '¿Tienes alguna pregunta? Chatea con nuestros expertos locales donde sea y cuando sea',
  },
  FLEXIBLE: 'Flexible',
  FOOTER: {
    CALL_US: 'Teléfono',
    CHAT_WITH_US: 'Chat en vivo',
    COMPANY_DETAILS: 'Sobre la empresa',
    INFORMATION: 'Información',
    GMAPS_DISCLAIMER:
      'Todas las imágenes de mapas que aparecen en esta página proceden de Google de acuerdo con el principio de "uso legítimo". Todos los derechos sobre dichas imágenes corresponden a la plataforma mencionada, y su uso tiene fines exclusivamente informativos u orientativos.',
    DISCLAIMER:
      'Este sitio no es el sitio web oficial <attraction>. Este sitio es operado por Headout quien trabaja de la mano con operadores turísticos para ofrecer experiencias increíbles en un sólo clic.',
    EMAIL_US: 'Correo electrónico',
    GET_HELP: 'Ayuda',
    LEGAL: 'Información legal',
    PRIVACY_POLICY: 'Política de privacidad',
    QUICK_LINKS: 'Enlaces directos',
    TERMS_AND_CONDITIONS: 'Términos y condiciones',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Hecho con ',
    ALL_OVER_THE: ' desde todo el ',
    TERMS_OF_USAGE: 'Términos de Uso',
    GET_HELP_24_7: 'Atención 24/7',
    HELP_CENTER: 'Centro de asistencia',
    COMPANY: 'Empresa',
    WE_ACCEPT: 'OPCIONES DE PAGO',
    DOWNLOAD_HEADOUT: 'Descarga la aplicación Headout',
    SCAN_CODES: 'escanear el código',
    STAR_VERIFIED: 'Haz clic para verificar la suscripción a S.T.A.R.',
    OFFICIAL_TICKET_RETAILER: 'Distribuidor Oficial de Entradas',
  },
  FREE_CANCELLATION: 'Cancelación gratuita',
  FREE_CANCELLATION_SUBTEXT:
    'Si cambias de planes, puedes cancelar hasta con 72 horas de antelación.',
  FROM: 'a partir de',
  GET_CASHBACK: 'Consigue {0} % en cashback',
  GROUP_TICKETS: 'Visita en grupo',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '+20 millones de clientes',
    SUB_TEXT: 'Tu satisfacción es nuestra prioridad. Únete a nosotros.',
  },
  HELP_CENTER: {
    MAIN_TEXT: 'Atención al cliente 24/7',
    SUB_TEXT:
      '¿Tienes alguna pregunta? Contáctanos por teléfono, chat o correo electrónico.',
  },
  INCLUSIONS: 'Incluye',
  LANGUAGE: 'Idioma',
  LISTICLES: {
    KNOW_MORE: 'Leer más',
    SEATING_CHART: 'Mapa de asientos',
    WHY_BOOK_FROM_US: '¿Por qué reservar con Headout?',
  },
  MORE_DETAILS: 'Más detalles',
  MORE_CURRENCIES: 'Otras monedas',
  NEW: 'Nuevo',
  NEW_ARRIVAL: 'Novedades',
  NEXT_AVAILABLE: 'Próxima disponible: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout es una marca en la que confían más de 15 millones de clientes y que ofrece una selección de las mejores experiencias. Este no es el sitio oficial de la sede de la experiencia.',
  NO_RESULT_FOUND: 'No se ha encontrado ningún resultado',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR: 'Plan flexible: reserva sin fecha fija',
  OPENING_DATE: 'Fecha de estreno',
  OPENING_ON: 'Se estrena el',
  OPENS: 'Abre',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout es un socio de confianza de la atracción, autorizado para ofrecer una selección de las mejores experiencias. Este no es el sitio web de la atracción.',
  POPULARITY: 'Popularidad',
  POPULAR_CURRENCIES: 'Monedas más frecuentes',
  PRICE: 'Precio',
  PRICES_STARTING: 'Precios desde',
  PROMO_CODES: {
    APPLIED: 'APLICADO',
    APPLY_CODE: 'APLICAR CÓDIGO',
    DESCRIPTION: {
      ABSOLUTE: 'Descuento de {0}',
      CAPPED: '{0} % de descuento, hasta {1}',
      PERCENTAGE: '{0} % de descuento',
    },
    REMOVE: 'ELIMINAR',
    TOOL_TIP_INFO: 'El descuento se aplicará al realizar el pago',
  },
  RATINGS: '{0} Calificaciones',
  READ_MORE: 'Leer más',
  READ_MORE_TEXT: 'Leer más',
  READ_LESS: 'Ver menos',
  VIEW_DETAILS: 'Ver detalles',
  REOPENING: 'Reapertura',
  REOPENING_DATE: 'Fecha de reapertura',
  REOPENING_ON: 'Reabre el',
  REOPENS: 'Reabre',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT: 'Se aplican las normas ""2G"": el acceso al alojamiento, a las instituciones culturales y a los restaurantes/bares, entre otros, solo es posible con una prueba de vacunación completa o prueba de recuperación de la enfermedad. Una prueba COVID-19 negativa ya no es suficiente.',
    },
    AU_DESCRIPTION: {
      TEXT: 'Los visitantes mayores de 16 años deben presentar una prueba de vacunación contra el COVID-19 o una exención médica.',
    },
    BANNER_CTA: 'Leer más',
    BERLIN_DESCRIPTION: {
      TEXT: 'Se aplican las normas "2G": solo se permitirá el acceso a los visitantes totalmente vacunados y a los visitantes con prueba de recuperación de la enfermedad. Las personas menores de 18 años o las que no puedan vacunarse por razones médicas deberán presentar a la entrada un resultado negativo de la prueba COVID. En el caso de las personas que no puedan vacunarse por motivos médicos, deberán también presentar a la entrada un certificado médico que demuestre su imposibilidad de vacunarse.',
    },
    CTA_TEXT: 'Estándares de Seguridad',
    DESCRIPTION_CTA: 'Más información.',
    EU_DESCRIPTION: {
      TEXT: 'A partir del 21 de julio de 2021, todos los visitantes mayores de 12 años deben presentar un certificado COVID de la UE.',
    },
    EU_HEADING: 'Se requiere el certificado COVID de la UE',
    EU_PREFIX: 'Atención: ',
    EXPERIENCE_DESCRIPTION:
      'Se ha verificado que esta experiencia cumple con los estándares de seguridad más estrictos, conforme a las regulaciones locales y de la OMS.',
    FLAG_TEXT: 'Seguridad Verificada',
    GENERAL_DESCRIPTION:
      'Cualquier experiencia con esta insignia ha sido verificada y cumple con los más estrictos estándares de seguridad impuestos por las autoridades sanitarias locales.',
    HEADING: 'Estándares de Seguridad',
    IT_DESCRIPTION: {
      TEXT: 'A partir del 6 de agosto de 2021, todos los visitantes mayores de 11 años deben presentar un pase verde o un certificado COVID de la UE.',
    },
    IT_PREFIX: 'Importante : ',
    MOBILE_HEADING: 'Experiencias Seguras',
    MODAL: {
      BADGE_DESCRIPTION:
        'Cualquier experiencia con esta insignia confirma que se han verificado los estándares de higiene y seguridad.',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Todos los equipos, vehículos y áreas de alto contacto se desinfectan minuciosamente después de cada uso. Sólo siéntate y disfruta de tu experiencia.',
          HEADING:
            'Todos los equipos y superficies son constantemente desinfectados',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Todos los equipos disponibles durante tu experiencia se desinfectan minuciosamente después de cada uso. Siempre.',
          HEADING:
            'Todos los equipos y superficies son constantemente desinfectados',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Todos los vehículos disponibles durante tu experiencia se desinfectan minuciosamente después de cada uso. Siempre',
          HEADING: 'Todos los vehículos son constantemente desinfectados',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Esta experiencia ha sido clasificada con la insignia Seguridad Verificada, por lo que tendrás acceso a estaciones de aseo y saneamiento durante todo el tiempo de tu visita. No te preocupes, tu seguridad es primero.',
          HEADING: 'Instalaciones sanitarias y estaciones de aseo disponibles',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'El uso de mascarillas es obligatorio tanto para los participantes como para el personal encargado de esta experiencia. Esto ayuda a que todos se diviertan, con la máxima seguridad y protección.',
          HEADING: 'Por seguridad, todos deben usar mascarillas',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Nuestros socios verificados con la insignia "Seguridad Verificada" siguen las regulaciones locales sobre el uso de mascarillas. En caso de ser obligatorio, todos los participantes y personal deberán llevar mascarilla. Se tomarán todas las medidas posibles para asegurar tu comodidad y seguridad',
          HEADING:
            'Por seguridad, todos los participantes deben usar mascarillas',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'El uso de mascarillas es obligatorio para todos los participantes en esta experiencia. Esto ayuda a que todos se diviertan con la máxima seguridad.',
          HEADING:
            'Por seguridad, todos los participantes deben usar mascarillas',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Todo el personal encargado de esta experiencia debe llevar mascarillas para asegurar que puedas tener toda la diversión, sin ninguna preocupación.',
          HEADING: 'Todo el personal debe usar mascarillas por seguridad',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Las pautas de distanciamiento social son aplicables en todo momento durante esta experiencia. Se han establecido restricciones de capacidad para asegurar el distanciamiento social.',
          HEADING:
            'Las pautas de distanciamiento social se siguen en todo momento',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Las pautas de distanciamiento social se cumplen en todo momento durante esta experiencia. Se han establecido restricciones de capacidad para asegurar el distanciamiento social. En el mismo sentido, no se permite el ingreso de grupos grandes en esta experiencia.',
          HEADING:
            'Las pautas de distanciamiento social se siguen en todo momento',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Las pautas de distanciamiento social se cumplen en todo momento durante esta experiencia.',
          HEADING:
            'Las pautas de distanciamiento social se siguen en todo momento',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Las pautas de distanciamiento social se cumplen en todo momento durante esta experiencia. Por lo tanto, puede haber restricciones de capacidad y límites de grupo en el sitio. Relájate y disfruta de tu visita.',
          HEADING:
            'Las pautas de distanciamiento social se siguen en todo momento',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Las pautas de distanciamiento social se cumplen en todo momento durante esta experiencia. Por lo tanto, no se permite el ingreso de grupos grandes en esta experiencia.',
          HEADING:
            'Las pautas de distanciamiento social se siguen en todo momento',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'A todos los participantes se les revisará la temperatura corporal al comienzo de la experiencia para garantizar la seguridad de todos. A todos el personal se les revisa la temperatura varias veces al día.',
          HEADING: 'Controles de temperatura en sitio',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'A todos los participantes se les revisará la temperatura corporal al comienzo de la experiencia para garantizar la seguridad de todos.',
          HEADING: 'Controles de temperatura en sitio',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'A todo el personal se les revisa la temperatura varias veces al día. Cualquier miembro de personal que supere el límite prescrito de temperatura corporal, no se le permite la entrada al sitio y se le pide que se quede en casa para recuperarse.',
          HEADING: 'Controles de temperatura en sitio',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'El personal encargado de tu experiencia está capacitado conforme a las directrices de la OMS y equipado para hacer frente a cualquier emergencia que se presente.',
          HEADING:
            'El personal está capacitado conforme a las directrices de la OMS',
        },
      },
      HEADING: 'Experiencias Seguras',
      SUB_HEADING:
        'Trabajamos de cerca con nuestros socios locales para cumplir con los mejores estándares de higiene y seguridad, según las directrices de la OMS. Todas las medidas implementadas durante tu visita han sido verificadas y a continuación te las presentamos. Es hora de volver a disfrutar del mundo que nos rodea.',
    },
    NL_DESCRIPTION: {
      TEXT: 'Los visitantes mayores de 13 años deben presentar un certificado COVID (digital o impreso) que demuestre que han sido vacunados, o bien una prueba con un resultado negativo o prueba de recuperación reciente de COVID-19. Es obligatorio llevar una mascarilla facial.',
    },
    SG_DESCRIPTION: {
      TEXT: 'A partir del 13 de octubre de 2021, solo podrán entrar visitantes totalmente vacunados en grupos de 2. Tendrás que mostrar una prueba de vacunación, un resultado negativo reciente de la prueba COVID-19 y/o certificado de recuperación antes de la entrada.',
    },
    SHORT_HEADING: 'Los mejores estándares de seguridad en vigor',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Información de seguridad',
    EXPERIENCE_DESCRIPTION:
      'Esta experiencia sigue las normas de seguridad de acuerdo con la normativa local y la OMS',
    FLAG_TEXT: 'La mejor seguridad',
    GENERAL_DESCRIPTION:
      'Este recinto es seguro durante COVID y sigue todas las medidas de sanidad recomendadas por el gobierno para garantizar que disfrutes de una experiencia de teatro segura y con distanciamiento social.',
    GENERAL_DESCRIPTION_V2:
      'Hemos desarrollado la marca Asiste con confianza, de modo que cuando los teatros vuelvan a abrir, puedas sentirte confiado y seguro sabiendo que el local es seguro ante COVID y que seguirá las últimas directrices del gobierno y de las artes escénicas.',
    HEADING: 'Asiste con confianza',
    MOBILE_HEADING: 'Experiencias seguras',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Solo se aceptarán entradas impresas y entradas electrónicas</li>',
          HEADING: 'Entradas electrónicas sin contacto',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Es obligatorio el uso de equipos de protección, como mascarillas, para entrar en el recinto.</li>\n            <li>Todos los asistentes serán sometidos a controles de temperatura antes de entrar en el recinto</li>',
          HEADING: 'Medidas preventivas de seguridad',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Es obligatorio el uso de equipos de protección, como mascarillas, para entrar en el recinto.</li>\n            <li>Todos los asistentes serán sometidos a controles de temperatura antes de entrar en el recinto</li>',
          HEADING: 'Medidas de higiene',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>El recinto se ha rediseñado para minimizar el contacto entre todos los espectadores</li>\n            <li>Los distintos grupos se sentarán por separado</li>\n            <li>Siempre que sea posible, se facilitará el pedido anticipado de tentempiés en los intermedios.</li>\n            <li>Se recomiendan las transacciones sin efectivo.</li>\n            <li>Se solicita a todos los espectadores que reduzcan al mínimo sus pertenencias, ya que el guardarropa puede estar cerrado.</li>\n            <li>Actividades como hacerse fotos con los artistas o firmar autógrafos pueden estar restringidas</li>\n            ',
          HEADING: 'Medidas de distanciamiento social',
        },
      },
      HEADING: 'Asiste con confianza',
      SUB_HEADING:
        '¿Te preguntas qué medidas se han implementado para garantizar tu seguridad? Infórmate sobre las medidas de higiene y los protocolos de COVID que los teatros han implantado para garantizar tu seguridad.',
    },
    SHORT_HEADING: 'Con las mejores normas de seguridad',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Tu seguridad es nuestra prioridad',
    TEXT: 'Hemos tomado las medidas de higiene necesarias para limpiar con frecuencia el lugar mediante el uso de desinfectantes y productos de limpieza profesional. Se han implementado medidas para controlar el ingreso de visitantes y evitar aglomeraciones.',
  },
  SAVE: 'Ahorra {0}%',
  SAVE_PERCENT: 'Ahorra {0}%',
  SAVE_UPTO: 'Ahorra hasta un',
  SAVE_UPTO_PERCENT: 'Ahorra hasta un {0}%',
  SEARCH: 'Buscar',
  SEE_ALL: 'Ver todo',
  SEE_MORE_SHOWS: 'Ver más espectáculos',
  SELECT_CITY: 'Selecciona una ciudad',
  SELECT_SECTION: 'Elegir sección',
  SEE_ALL_PHOTOS: 'Ver todas las fotos',
  SHOW_CLOSED: 'El espectáculo ha finalizado',
  SHOW_LESS_TEXT: 'Mostrar menos',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Sobre el espectáculo',
    ABOUT_THEATRE: 'Sobre el teatro',
    ADDITIONAL_INFORMATION: 'Información adicional',
    AGE_LIMIT: 'Límite de edad',
    AGE_SUITABILITY: 'Edades',
    ANSWER: ['R-', 'A-'],
    BLOG_SHOW_PAGE: 'Blog del espectáculo',
    BLOG_SUMMARY: 'Blog - Resumen',
    BLOG_THEATRE_PAGE: 'Blog del teatro',
    BLOG_THEATRE_SEATING_PLAN: 'Blog - Plan de asientos del teatro',
    CANCELLATION_AND_REFUNDS: 'Cancelación y reembolso',
    CANCELLATION_POLICY: 'Política de cancelación',
    CAST_AND_CREW: 'Reparto y equipo',
    CLOSING_DATE: 'Última fecha',
    CLOSING_DATE_SPECIAL_OFFER: 'Fecha de cierre de la oferta especial',
    DURATION: 'Duración',
    FACILITIES_AND_ACCESSIBILITY: 'Instalaciones y accesibilidad',
    FREQUENTLY_ASKED_QUESTIONS: 'Preguntas frecuentes',
    GETTING_THERE: 'Cómo llegar',
    GETTING_THERE_MAP_LINK: 'Ver en el mapa',
    GOOGLE_MAP: 'Mapa de Google',
    HIGHLIGHTS: 'Lo más destacado',
    LISTICLE_SHOW_SUMMARY: 'Listicle Resumen del espectáculo',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle ¿Por qué verlo?',
    OPENING_DATE: 'Fecha de estreno',
    QUESTION: ['P-', 'Q-'],
    SAFETY_BANNER: 'Banner de seguridad',
    SHOW_DETAILS: 'Detalles del espectáculo',
    SHOW_TIMINGS: 'Horarios',
    SHOW_TYPE: 'Tipo de espectáculo',
    SPECIAL_OFFER: 'Oferta especial',
    THE_STORY: 'La historia',
    THEATRE_ADDRESS: 'Dirección',
    THEATRE_CAPACITY: 'Capacidad',
    THEATRE_NAME: 'Teatro',
    TICKETS: 'Entradas',
    TICKETS_REDEMPTION: 'Canje de entradas',
    TOP_SONGS: 'Canciones principales',
    YOUR_TICKETS: 'Tus entradas',
    ABOUT_CONCERT: 'El concierto',
    PROGRAM: 'Programa',
  },
  SORT_BY: 'Ordenar por',
  THEATRE: 'Teatro',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Teatros cercanos',
    NOW_PLAYING: 'En cartelera',
    UPCOMING_SHOWS: 'Próximos espectáculos',
    PAST_SHOWS: 'Espectáculos pasados',
    FIND_BEST_SEATS: 'Buscar los mejores asientos',
  },
  SPECIAL_OFFER: 'Oferta especial',
  TICKET_CAN_BE_CANCELED:
    'Puedes cancelar hasta {hours} horas de antelación para obtener un reembolso total.',
  TICKET_CANNOT_BE_CANCELED:
    'Estas entradas no pueden ser canceladas, pero pueden ser reprogramadas si se solicita.',
  TICKETS: 'Entradas',
  TIMINGS: 'Horarios',
  SPECIAL_PRODUCT_HEADING: 'Lo más recomendado',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Guías locales expertos',
    ENGAGING_STORIES: 'Historias cautivadoras',
    TOP_RATED: 'Con mejor valoración',
  },
  GUIDED_TOUR_REVIEWS: [
    'Nuestra guía, Angela, era estupenda y conocía perfectamente el lugar',
    'El guía estuvo encantado de responder a las preguntas sobre la visita',
    'Nuestra guía fue estupenda e incluso nos recomendó un buen almuerzo',
    'La organización y nuestro guía hicieron que la experiencia fuera muy agradable',
    'Mucho contenido educativo, seguro que repetiré con mis hijos',
    'La excursión estuvo bien organizada y además duró el tiempo justo',
    'Nuestro guía sabía muy bien lo que hacía y su pasión por la historia era evidente',
    '¡Buen guía y buena organización! ¡¡¡Lo recomendaré!!!',
    'La visita transcurrió a buen ritmo y sin prisas',
    'Jeff nos mostró aspectos del lugar que nos habríamos perdido de otra manera',
    'La experiencia del tour fue muy buena, todo estuvo bien gestionado',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Inglés',
    SPANISH: 'Español',
    FRENCH: 'Francés',
    ITALIAN: 'Italiano',
    GERMAN: 'Alemán',
    PORTUGUESE: 'Portugués',
    NEDERLANDS: 'Neerlandés',
    POLISH: 'Polaco',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Recorrido disponible en {0}',
  GUIDES_BANNER: 'Explora como un lugareño junto a nuestros guías favoritos.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Una visita guiada es la mejor manera de aprovechar al máximo este destino. Nuestros guías expertos serán tus compañeros de viaje y compartirán contigo historias, secretos y recomendaciones.',
    'No solo visites la ciudad, ¡vívela!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Qué dicen los viajeros',
  TODAY: 'hoy',
  TOMORROW: 'mañana',
  TOUR_LIST_HEADING: 'Selecciona tu experiencia',
  TOUR_LIST_SUB_HEADING:
    'Elige entre una gran variedad de entradas, tours y ofertas de agencias turísticas verificadas',
  UGC: {
    FOLLOW: 'Seguir',
    FOLLOW_IG: 'Seguir en Instagram',
    HEADING: 'POV: tu próxima aventura podría verse así',
    SUB_HEADING: 'Experiencias seleccionadas con 💜 por Headout',
  },
  UNAVAILABLE: 'No disponible',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Estas entradas son válidas durante un periodo de tiempo prolongado. Los detalles exactos se mencionarán en la entrada.',
    UNTIL_DATE: 'Estas entradas son válidas hasta el {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Estas entradas son válidas durante {0} días a partir de la fecha de compra.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Estas entradas son válidas durante {0} meses a partir de la fecha de compra.',
  },
  TABLE_OF_CONTENTS: 'Contenido',
  VIEW_LESS: 'Ver menos',
  VIEW_MORE: 'Leer más',
  WHY_TAKE_THIS_DAY_TRIP: '¿Por qué vale la pena hacer este viaje de 1 día?',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Menú principal',
    EXPLORE: 'Explora',
    VISIT: 'Visita',
    THINGS_TO_DO: 'Qué hacer',
    CITY_ATTRACTIONS: 'Atracciones en {0}',
    TOP_THINGS_TO_DO: 'Las mejores cosas que hacer',
    CITY_TOURS: 'Tours en {0}',
    CITY_GUIDE: 'Guía de la ciudad',
    ATTRACTIONS: 'Atracciones',
    CRUISES: 'Cruceros',
    THEMES: 'Temas',
    ABOUT: 'Descubre',
    TOURS: 'Visitas',
    SKIP_THE_LINE: 'Visitas sin colas',
    GUIDED_TOURS: 'Visitas guiadas',
    NIGHT_TOURS: 'Visitas nocturnas',
    FOOD_TOURS: 'Tours gastronómicos',
    HISTORY: 'Historia',
    ARCHITECTURE: 'Arquitectura',
    DESIGN: 'Diseño',
    INSIDE: 'Interior',
    COLLECTIONS: 'Colecciones',
    PAINTINGS: 'Pinturas',
    ANIMALS_EXHIBITS: 'Animales y exposiciones',
    HABITATS: 'Hábitats',
    CONSERVATION: 'Conservación',
    PROGRAMMES: 'Programas',
    A2_SIGHTSEEING_CRUISES: 'Cruceros panorámicos',
    A2_DINNER_CRUISES: 'Cruceros con cena',
    A2_EVENING_CRUISES: 'Evening Cruises',
    A2_LUNCH_CRUISES: 'Cruceros con almuerzo',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Planifica tu visita',
    TIMINGS: 'Horario',
    DIRECTIONS: 'Cómo llegar',
    PARKING: 'Parking',
    ROUTES: 'Rutas',
    REQUIREMENTS: 'Requisitos',
    LOCATION: 'Ubicación',
    RULES: 'Normas',
    FAQs: 'Preguntas frecuentes',
    ENTRANCES: 'Accesos',
    RESTAURANTS: 'Restaurantes',
    FACTS: 'Curiosidades',
    TIPS: 'Consejos',
    MAP: 'Mapa',
    RIDES: 'Atracciones',
    SHOWS: 'Espectáculos',
    DINING: 'Gastronomía',
    SHOPPING: 'Compras',
    EVENTS: 'Eventos',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Navidad',
    NEW_YEARS_EVE: 'Nochevieja',
    TRAVEL_GUIDE: 'Guía de viaje',
    TRIP_PLANNER: 'Planificador de viaje',
    ITINERARY: 'Itinerario',
    TRAVEL_TIPS: 'Consejos de viaje',
    WEATHER: 'El tiempo',
    BEST_TIME_TO_VISIT: 'Mejor época para visitar',
    JANUARY: 'Enero',
    FEBRUARY: 'Febrero',
    MARCH: 'Marzo',
    APRIL: 'Abril',
    MAY: 'Mayo',
    JUNE: 'Junio',
    JULY: 'Julio',
    AUGUST: 'Agosto',
    SEPTEMBER: 'Septiembre',
    OCTOBER: 'Octubre',
    NOVEMBER: 'Noviembre',
    DECEMBER: 'Diciembre',
    WHERE_TO_EAT: 'Dónde comer',
    WHERE_TO_STAY: 'Dónde alojarse',
    NEIGHBOURHOODS: 'Barrios',
    FAMILY_TRAVEL: 'Viajar en familia',
    TRANSPORTATION: 'Transporte',
    FESTIVALS_EVENTS: 'Festivales y eventos',
  },
  WHY_WATCH: '¿Por qué verlo? {0}?',
  FIND_ON_MAP: 'Ver en el mapa',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Entradas de taquilla',
        DESCRIPTION: 'Confirmación instantánea al móvil',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Elige tus asientos`,
        DESCRIPTION: 'Siempre la vista que quieras',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Ofertas y descuentos exclusivos',
        DESCRIPTION: `Los mejores espectáculos al mejor precio`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Reserva sencilla',
        DESCRIPTION: '25 millones de clientes satisfechos',
      },
    },
    YOUR_PICK: 'Tu elección',
    BROWSE_BY_CATEGORIES: 'Buscar por categorías',
    TOP_WEST_END_SHOWS: 'Los mejores espectáculos del West End',
    TOP_THEATRE_SHOWS: '{0}: los mejores espectáculos',
    TOP_SHOWS: 'Destacados',
    SEE_MORE_SHOWS: 'Ver {0} espectáculos más',
    LAST_MINUTE_TICKETS: 'Entradas de última hora',
    LOVED_BY_MILLIONS: 'A millones les encanta',
    TODAY: 'Hoy',
    TOMORROW: 'Mañana',
    SEE_ALL: 'Ver todo',
    GRAB_YOUR_TICKETS: 'Consigue ya tus entradas',
  },
  TAG_NAME: {
    BALLET: 'Ballet',
    CABARET: 'Cabaret',
    CHRISTMAS: 'Navidad',
    CIRCUS: 'Circo',
    CLASSIC: 'Clásico',
    COMEDY: 'Comedia',
    COMING_SOON: 'Próximamente',
    CRITICS_CHOICE: 'Premiado por la crítica',
    DANCE: 'Danza',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'Ballet Nacional de Inglaterra',
    ENGLISH_NATIONAL_OPERA: 'Ópera Nacional Inglesa',
    FANTASY: 'Fantasía',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Teatro inmersivo',
    JUKEBOX: 'Jukebox',
    KIDS: 'Infantil',
    MAGIC: 'Magia',
    MUSICALS: 'Musicales',
    NEW_ARRIVAL: 'Novedad',
    OFF_WEST_END: 'Fuera del West End',
    OLIVIER_WINNER: 'Ganador de un Olivier',
    OPERA: 'Ópera',
    PANTOMIMES: 'Pantomimas',
    PLAYS: 'Obras de teatro',
    ROMANCE: 'Romance',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Estrellas en escena',
    THEATRICAL_CONCERT: 'Concierto teatral',
    TRUE_STORY: 'Basado en una historia real',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Vaya, parece que tenemos un problema',
    MESSAGE: `Todas las experiencias están agotadas o no están disponibles en esta fecha. Pero si tus planes son flexibles, tenemos muchas otras fechas entre las que puedes elegir.`,
    CTA: 'Ver todas las fechas',
  },
  ALL_DATES: 'Todas las fechas',
  BREADCRUMBS: {
    HOME: 'Inicio',
    TRAVEL_GUIDE: 'Guía de viaje',
    THINGS_TO_DO: 'Qué hacer en {0}',
    SHOW_NAME_TICKETS: '{0} - Entradas',
    LTT_HOME: 'Entradas para el teatro en Londres',
    LTT_VENUE_PAGE_HOME: 'Teatros en Londres',
    BROADWAY_HOME: 'Entradas para espectáculos de Broadway',
    BROADWAY_VENUE_PAGE_HOME: 'Teatros en Broadway',
    VIENNA_CONCERT_HOME: 'Entradas para conciertos en Viena',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Salas de conciertos en Viena',
    ATTRACTIONS: 'Atracciones',
    A2_SIGHTSEEING_CRUISES: 'Cruceros panorámicos',
    A2_DINNER_CRUISES: 'Cruceros con cena',
    A2_EVENING_CRUISES: 'Evening Cruises',
    A2_LUNCH_CRUISES: 'Cruceros con almuerzo',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'Novedades del teatro de Londres',
    BROADWAY_SHOW_NEWS: 'Novedades de los espectáculos de Broadway',
    NEWS_PAGE: 'Novedades',
    REVIEWS_PAGE_BANNER_HEADING: 'Reseñas de {0}',
  },
  AMENITIES: {
    Restaurant: 'Restaurante',
    Cafe: 'Café',
    'Dedicated Parking': 'Aparcamiento',
    Elevators: 'Ascensor',
    Lift: 'Ascensor',
    'Wheelchair Accessible': 'Accesible en silla de ruedas',
    Cloakroom: 'Guardarropa',
    'Air Conditioning': 'Aire acondicionado',
    WiFi: 'WiFi',
    Bar: 'Bar',
    'Water Fountain': 'Fuente',
    Washrooms: 'Lavabos',
    Toilets: 'Aseos',
    Binoculars: 'Prismáticos',
    'Adapted Toilets': 'Aseos adaptados',
    'Accessible Toilets': 'Aseos accesibles',
    'Assistive Listening System': 'Sistema de escucha asistida',
    'Hearing Assistance': 'Asistencia auditiva',
    'Booster Cushions': 'Cojines elevadores',
    Shop: 'Tienda',
    'Souvenir Shop': 'Tienda de recuerdos',
    'Guide Dogs': 'Perros guía',
    'Baby Changing Facilities': 'Cambiadores para bebés',
    'Security Check': 'Control de seguridad',
    Ramp: 'Rampa',
    'Level Access': 'Acceso a nivel',
  },
  CALENDAR: {
    FOOTNOTE: '*Todos los precios están en {0}',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Ver la reseña original en {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Esta reseña ha sido traducida. Ver la reseña original.',
    TRANSLATE: 'Traducir la reseña en {0}',
    LANGUAGES: {
      EN: 'inglés',
      ES: 'español',
      FR: 'francés',
      IT: 'italiano',
      DE: 'alemán',
      PT: 'portugués',
      NL: 'neerlandés',
    },
  },
  SHOW_PAGE_V2: {
    SELLING_OUT_FAST: 'Se agota rápido',
    INTERVAL: 'Intermedio',
    TWO_PART_SHOW: 'Espectáculo de dos partes',
    READ_MORE_REVIEWS: 'Leer más reseñas',
    SHOW_MORE_REVIEWS: 'Mostrar más reseñas',
    ALL_PHOTOS: 'Todas las fotos',
    MORE_DATES: 'Más fechas',
    SELECT_TIME_SLOT: 'Selecciona una franja horaria',
    SELECT_TIME_SLOT_ERROR: 'Selecciona una franja horaria para continuar',
    PRICE_STARTING_FROM: 'Precio de los asientos a partir de',
    SELECT_SEATS: 'Seleccionar asientos',
    READ_MORE: 'Leer más',
    RATINGS_AND_REVIEWS: 'Valoraciones y reseñas',
    READ_DETAILED_REVIEWS: 'Leer reseñas completas',
    UNTIL_DATE: 'Hasta {0}',
    AVAILABLE_TIME: 'Horario disponible',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Esta experiencia solo está disponible en el siguiente horario',
    CONTENT_TABS: {
      ABOUT: 'El espectáculo',
      VENUE: 'Lugar',
      TICKETS: 'Entradas',
      Reviews: 'Reseñas',
    },
    SELECT_SHOW_TIMMING: 'Selecciona la hora del espectáculo',
    ONLY_ONE_SLOT:
      'Solo hay 1 franja horaria disponible en la fecha seleccionada',
    SIMILAR_SHOWS: 'También te puede interesar',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Historia',
      AGE_SUITABILITY_AND_GUIDELINES: 'Edad recomendada y otras indicaciones',
      WHAT_CRITICS_THINK: 'Opinión de los críticos',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Preguntas frecuentes',
      CAST_AND_CREATIVES: 'Reparto y equipo',
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Guías multilingües expertos',
    STL: 'Acceso sin colas',
    PERSONALIZED: 'Experiencia personalizada',
    LOCAL_FOOD: 'Descubre la comida y la cultura locales',
    MULTILINGUAL_GUIDES: 'Guías multilingües',
    CULINARY_EXPERTS: 'Conoce a los expertos culinarios',
    SIGHTSEEING: 'Puntos de interés y entretenimiento a bordo',
    SIGHTSEEING_MEAL: 'Visita turística y comidas incluidas',
    MULTILINGUAL_GT: 'Tours guiados multilingües',
    AUDIOGUIDE_COMMENTARY: 'Audioguía y comentarios disponibles',
    ALL_TOP_ATTRACTIONS_COVERED: 'Cubre todas las atracciones principales',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Salidas frecuentes. Viajes ilimitados',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Disponibilidad de última hora. Confirmación instantánea',
    MULTI_ROUTES: 'Múltiples opciones de ruta',
    HASSLE_FREE: 'Reserva sin complicaciones',
    FREQUENT_DEPARTURES: 'Salidas frecuentes',
    ONBOARD_AMENITIES: 'Los mejores servicios a bordo',
    FLEXI_TRAVEL: 'Viajes flexibles en múltiples rutas',
    FLEXI_EXCHANGE_CANCEL: 'Cambios y cancelaciones flexibles',
    EXTRA_DISCOUNT: 'Descuentos adicionales para jóvenes, mayores y familias',
    PREPAID: 'Cómodo prepago',
    EASY_ACTIVATION: 'Activación sencilla',
    INSTANT_CONNECTIVITY: 'Conectividad instantánea con cobertura mundial',
    ROUND_TRIP: 'Traslados de ida y vuelta',
    CULTURAL_EXPERIENCE: 'Experiencias culturales auténticas',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
    LUGGAGE_ASSISTANCE: 'Asistencia con el equipaje',
    TOP_ATTRACTIONS: 'Principales atracciones incluidas',
    FREQ_DEP_MULTI_ROUTE: 'Salidas frecuentes en rutas múltiples',
    CHARGING: 'Estación de carga',
    WIFI: 'Acceso a wifi',
    FnB: 'Comidas y bebidas disponibles',
    LUXURY: 'Experiencia de lujo',
    FOOD_DRINK: 'Comidas y bebidas',
    PANAROMIC: 'Vistas panorámicas de las principales atracciones',
    PANAROMIC_2: 'Vistas panorámicas',
    PANAROMIC_3: 'Vistas panorámicas',
    BEVERAGES: 'Bebidas a bordo',
    GOURMET: 'Comida gourmet',
    GOURMET_2: 'Cena gourmet y bebidas',
    NIGHTTIME: 'Vistas nocturnas',
    ROMANTIC: 'Ambiente romántico',
    TRANSFERS: 'Traslados incluidos',
    CERTIFIED_OP: 'Operación certificada',
    BIRD_EYE: 'Vistas panorámicas',
    MULTI_JUMP: 'Múltiples horas de salto',
    EXTREME_ADV: 'Aventura extrema',
    PHOTO_OP: 'Oportunidades fotográficas',
    TOP_ATTRACTIONS_COVERED: 'Incluye las principales atracciones',
    LOCAL_CULTURE: 'Experimenta la cultura local',
    EXCLUSIVE_DISC: 'Descuentos exclusivos',
    EFFICIENT_PUBLIC_TRANSIT: 'Transporte público eficiente',
    FREQUENT_SERVICE: 'Servicio frecuente',
    PREBOOKING: 'Fácil reserva previa',
    LOCAL_CULTURE_IMM: 'Inmersión en la cultura local',
    DISCOVER_HIDDEN: 'Descubre lugares ocultos',
    CITY_SIGHTSEEING: 'Puntos de interés en la ciudad',
    OFFBEAT_ADV: 'Experiencia fuera de lo común',
    DRINK_DEALS: 'Ofertas en bebidas',
    OFFBEAT_EXP: 'Experiencia fuera de lo común',
    MULTIPLE_VARIETIES: 'Incluye múltiples variedades',
    HIDDEN_GEMS: 'Joyas ocultas y atracciones poco comunes',
    EXPLORE_LOCAL: 'Explora los barrios locales',
    CUSTOMIZED_TREATMENTS: 'Tratamientos personalizados',
    TRAINED_THERAPISTS: 'Terapeutas calificados',
    HOLISTIC_WELLNESS: 'Bienestar integral',
    FLEXIBLE_DURATION: 'Duración flexible',
    MULTI_BOAT: 'Múltiples opciones de barco',
    SCENIC_ROUTES: 'Rutas panorámicas',
    HANDS_ON: 'Aprendizaje práctico',
    CULTURAL_CULINARY: 'Perspectiva cultural y culinaria',
    EXPERT_HOSTS: 'Anfitriones especializados',
    ADVENTURE_EXPERIENCE: 'Experiencia de aventura',
    EQUIPMENT: 'Equipo incluido',
    SCENIC_FLYOVERS: 'Traslados sin complicaciones',
    LIVE_COMMENTARY: 'Comentarios en directo',
    BEST_AERIAL_VIEWS: 'Las mejores vistas aéreas',
    SAFE_CERT_OP: 'Actividades seguras y certificadas',
    HANDPICKED: 'Tours y actividades cuidadosamente seleccionados',
    EFFORTLESS: 'Planificación sencilla',
    EXPERT_GUIDES: 'Información exclusiva de guías expertos',
    ALL_ATTR_ONE_CARD: 'Acceso a todas las atracciones con solo una tarjeta',
    MULTI_CARD: 'Diferentes tarjetas para elegir',
    COST_EFF: 'Económico y práctico',
    EASY_BEST: 'Reserva sencilla. Mejores precios',
    INSTANT_MOBILE: 'Confirmación instantánea. Billetes en el móvil',
    MULTI_TRANSPORT: 'Múltiples opciones de transporte',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Todo',
    POPULAR_SUBCATEGORY: '{0} más populares',
    TOP_CATEGORY: '{0}: las mejores experiencias',
    ATTRACTIONS: 'Atracciones',
    ALL_SUBCATEGORY: '{0}: todas las experiencias',
    BROWSE_BY_CATEGORIES: 'Buscar por categorías',
    TICKETS_FROM: 'Entradas desde',
    PRICE_LOW_HIGH: 'Precio (de menor a mayor)',
    PRICE_HIGH_LOW: 'Precio (de mayor a menor)',
    FILTERS: 'Filtros',
    RESET: 'Eliminar',
    APPLY: 'Aplicar',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout utiliza cookies para mejorar tu experiencia en el sitio web.',
    MOBILE: 'Utilizamos cookies.',
    LEARN_MORE: 'Más información.',
  },
  SHOW_UNAVAILABLE: 'Espectáculo no disponible',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Noticias destacadas',
    ALL_NEWS: 'Todas las novedades',
    MORE_READS: 'Leer más',
    LOAD_MORE: 'Ver más',
    TRAILERS: 'Todos los tráilers',
    GET_YOUR_TICKETS: 'Consigue tus entradas',
    POPULAR_SHOWS: 'Espectáculos populares',
    FEATURED: 'Destacado',
    RECENT_NEWS: 'Artículos recientes',
    SHOW_MORE_ARTICLES: 'Ver más artículos',
    COLLAPSE_ALL: 'Ocultar todo',
    REVIEWS: 'Reseñas',
    SHOW_ALL_REVIEWS: 'Ver todas las reseñas',
    MAILER: {
      HEADING:
        'Las mejores ofertas y novedades sobre teatro directamente en tu bandeja de entrada',
      SUBHEADING: `Únete a nuestra lista de correo y recibe actualizaciones y las mejores ofertas en espectáculos teatrales.`,
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: 'Reseñas de {0}',
    REVIEWS_COUNT: '{0} reseñas',
    AWESOME: 'Excelente',
    GOOD: 'Bueno',
    AVERAGE: 'Regular',
    POOR: 'Malo',
    TERRIBLE: 'Pésimo',
    REVIEW_BY_HEADOUT: 'Nuestra opinión: reseña de Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Lo que dice la gente',
    MOST_RELEVANT: 'Lo más relevante',
    RATING_HIGH_TO_LOW: 'Valoración: de mejor a peor',
    RATING_LOW_TO_HIGH: 'Valoración: de peor a mejor',
    CRITIC_REVIEWS: 'Reseñas de la crítica',
    USER_REVIEWS: 'Reseñas de los usuarios',
    CONTRIBUTORS_REVIEW: 'Reseña del autor',
  },
  HOHO: {
    HOHO: 'Billetes de autobús turístico',
    BUS_ROUTES_DETAILS: 'Rutas',
    TOUR_DETAILS: 'Detalles del tour',
    ROUTES_SCHEDULES: 'Rutas y horarios',
    VALIDITY: 'Válido durante 1 día',
    VALIDITY_NOTE:
      'Tu experiencia es válida durante {0} día(s) natural(es). Si reservas tu billete para el 6 de mayo de 2023- este será válido hasta el 6 de mayo de 2023, a las 21:00 PST.',
    BESTSELLER: 'Lo más vendido',
    SEE_ALL: 'Ver todo',
    TIMINGS: 'HORARIO',
    FREQUENCY: 'FRECUENCIA',
    DURATION: 'DURACIÓN',
    STARTING_LOCATION: 'Punto de partida',
    TOP_ATTRACTIONS: 'Atracciones principales',
    CALENDAR_FOOTNOTE: '*Todos los precios están en {0}',
    GOT_IT: 'Vale',
    TOUR_TIMINGS: 'Horarios',
    TOUR_FREQUENCY: 'Frecuencia',
    SELECT_DATE: 'Select a date',
    SELECT_TOUR: 'Select Tour Type',
    VIEW_TOUR_DETAILS: 'View tour details',
    BUS_DETAILS: 'MORE DETAILS',
    VIEW_ROUTES: 'View all routes',
    BUS_ROUTES: 'BUS ROUTES',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Traslados privados',
    SHARED_TRANSFERS: 'Traslados compartidos',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Reserva en línea',
        DESCRIPTION:
          'Disfruta de una experiencia cómoda y rápida reservando en línea.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Confirmación instantánea',
        DESCRIPTION:
          'Recibe confirmación instantánea al reservar tus billetes de traslado.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Servicio de recogida',
        DESCRIPTION:
          'Evita las largas colas, ya que el vehículo de traslado te esperará en el punto de recogida seleccionado.',
      },
      DROP_OFF: {
        TITLE: 'Lugar de destino',
        DESCRIPTION: 'Desplázate a tu destino de forma rápida y cómoda.',
      },
    },

    SHARED_TRANSFERS_IN: 'Traslados compartidos en {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      'Una opción de transporte cómoda y rentable para múltiples pasajeros viajando desde o hacia el aeropuerto.',
    PRIVATE_TRANSFERS_IN: 'Traslados privados en {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      'Un servicio de transporte cómodo y personalizado para particulares o grupos pequeños, que ofrece un viaje cómodo y directo desde o hacia el aeropuerto.',
    ANYWHERE_IN_THE_CITY: 'Cualquier lugar de la ciudad',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Múltiples opciones de vehículo',
      FREE_CANCELLATION: 'Cancelación gratuita',
    },
    SEAMLESS_TRANSFERS: 'Traslados cómodos y confiables en todo el mundo',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Elige el mejor traslado de aeropuerto para ti',
    HASSLE_FREE_TRANSFER: 'Traslados de aeropuerto sin complicaciones',

    // New experiment (AT LP)
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Traslados al aeropuerto de {0} en',
    BUSES: 'autobús',
    TRAINS: 'tren',
    PRIVATE_TAXIS: 'taxi privado',
    BUS_TRAIN: 'Bus/Tren',
    PRIVATE_TAXI: 'Taxi privado',

    FROM: 'From',
    SELECT_PICKUP: 'Seleccionar lugar de recogida',
    TO: 'To',
    SELECT_DROPOFF: 'Seleccionar destino',
    ENTER_DESTINATION: 'Introduce tu destino',
    PICKUP_DATE: 'Fecha de recogida',
    SELECT_DATE: 'Elegir fecha',
    PICKUP_TIME: 'Hora de recogida',
    SELECT_TIME: 'Elegir hora',
    GUESTS: 'Guests',
    ADD_GUESTS: 'Pasajeros',
    EXPLORE_TRANSFERS: 'Información de los traslados',
    COMBOS_AND_EXTRAS: 'Ofertas combo',

    YOUR_RIDE_DOORSTEP: 'Traslados desde la puerta de tu casa',
    COMFORTABLE_RIDE:
      'Reserva un taxi privado desde y hacia los aeropuertos principales de {0}',
    TRUSTED_DRIVERS: 'Conductores fiables',
    RIDES_24_7: 'Traslados disponibles 24/7',
    FLIGHT_TRACKING: 'Seguimiento de los vuelos',
    KNOW_MORE: 'Más información',
    RESERVE_YOUR_RIDE: 'Reserva tu traslado',
    TRANSFER_OPTIONS: 'Traslados encontrados',
    TRANSFERS_AVAILABLE_PLURAL: '{0} traslados disponibles',
    TRANSFERS_AVAILABLE_SINGULAR: '1 traslado disponible',

    TRUSTED_PARTNERS: 'Más de 35 socios de confianza',
    WORLDWIDE: '',
    COMFORTABLE_RIDES: 'Viajes cómodos',
    FREQUENT_DEPARTURES: 'Salidas frecuentes',
    MULTIPLE_TRANSPORT_OPTIONS: 'Múltiples opciones de traslado',
    AND_MANY_MORE: 'Y mucho más',

    ADD_PICKUP_LOCATION: 'Elige el lugar de recogida',
    ADD_DROPOFF_LOCATION: 'Elige el destino',
    SELECT_PICKUP_DATE_AND_TIME: 'Selecciona la fecha y hora de recogida',
    SELECT_A_DATE: 'Selecciona la fecha',

    TRAIN_STATION: 'Estación de tren',
    BUS_STOP: 'Parada de autobús',

    ADD_RETURN: 'Añadir vuelta',
    HEADS_UP: '¡Atención!',
    ADDED_RETURN_TRIP: 'Has añadido un viaje de ida y vuelta.',
    RETURN_NOTE:
      'Los detalles del viaje de vuelta se mostrarán en los próximos pasos.',
    OKAY_I_UNDERSTAND: 'Vale',

    SERVING_GUESTS: 'Más de {0} satisfechos en más de {1} del mundo',
    GUESTS_COUNT: '220 000 clientes',
    CITIES_COUNT: '55 ciudades',
    PARNTER_WITH_BEST:
      'Nos asociamos solo con los mejores para asegurarnos de que tengas una experiencia inolvidable. Nosotros nos ocupamos de todo, así que relájate y disfruta del viaje.',
  },
  PC_EXP: {
    SHOW_INCL: 'Qué incluye e información importante',
    CLEAR: 'Restablecer',
    ALL_EXPERIENCES: 'Todas las experiencias',
    FILTER_BY_CATEGORIES: 'Filtrar por categorías',
    CATEGORIES: 'Categorías',
    COMBOS: {
      HEADING: 'Lo bueno viene por dos. Como nuestros combos de ahorro.',
      DESCRIPTOR_1: 'Ofertas de ahorro',
      DESCRIPTOR_2: 'Planifica mejor tu viaje',
    },
  },
  TOP: 'Lo más destacado en: {0}',
  VIEW_CALENDAR: 'Ver calendario',
  SHOWS_CALENDAR: 'Calendario de los espectáculos',
  IN: 'en',
  SEATS: 'Asientos',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Guía de contenido',
    QUICK_INFORMATION: 'En breve',
    PEAK: 'horas punta',
    OFF_PEAK: 'fuera de horas punta',
    ADDRESS: 'DIRECCIÓN',
    RECOMMENDED_DURATION: 'DURACIÓN RECOMENDADA',
    VISITORS_PER_YEAR: 'VISITANTES AL AÑO',
    NUMBER_OF_ENTRANCES: 'NÚMERO DE ACCESOS',
    EXPECTED_WAIT_TIME_STANDARD: 'TIEMPO DE ESPERA PREVISTO - ESTÁNDAR',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE:
      'TIEMPO DE ESPERA PREVISTO - ACCESO SIN COLAS',
    UNESCO_YEAR: 'AÑO DE INSCRIPCIÓN A LA UNESCO',
    ARCHITECTURE_STYLE: 'ESTILO ARQUITECTÓNICO',
    TIMINGS: 'Horarios',
    SIZE_HEIGHT: 'TAMAÑO/ALTURA',
    TICKETS: 'ENTRADAS',
    FUN_FACTS: 'Datos curiosos',
    DID_YOU_KNOW: '¿Lo sabías?',
    MORE_INTERESTING_FACTS: 'Más datos de interés',
    PLAN_YOUR_VISIT: 'Planifica tu visita',
    ALSO_KNOWN_AS: 'También conocido como',
    FOUNDED_ON: 'Fundado en',
    FOUNDED_BY: 'Fundado por',
    FROM: 'Desde',
    CLOSED_TODAY: 'Cerrado hoy',
    TODAY: 'Hoy',
    CLOSED: 'Cerrado',
    OPEN: 'Abrir',
    LAST_ADMISSION: 'Última Admisión',
    DAYS: 'Días',
    BEST_TIME_TO_VISIT: 'Mejor época para visitar',
    WEEKDAY_VS_WEEKEND: 'Día laborable vs Fin de semana',
    PEAK_VS_LOW_SEASON: 'Temporada alta vs Temporada baja',
    PLEASANT: 'Agradable',
    CROWDED: 'Concurrido',
    VERY_CROWDED: 'Muy concurrido',
    LOW_SEASON: 'Temporada baja',
    MID_SEASON: 'Temporada moderada',
    PEAK_SEASON: 'Temporada alta',
    TO: 'A',
    LAST_ENTRY: 'última entrada',
    SUBATTRACTIONS: 'Sub-Atracciones',
    MORE_INSIGHTS: 'Más información',
  },
  OFF_PERCENT: '{0} % de descuento',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Plano de asientos',
    CAPACITY: 'Capacidad: {0} asientos',
    WHATS_ON: 'En cartelera',
    CATEGORIES: 'Categorías',
  },
  CURATED_VIDEO_BANNER: {
    HEADING: '¿No sabes qué experiencia elegir?',
    SUB_HEADING: 'Pues ve este vídeo para hacerte una idea.',
    WATCH_VIDEO: 'Ver vídeo',
  },
};
export default es;
