const fr = {
  AUDIO_GUIDE: {
    BANNER: 'Audioguide gratuit',
    PRODUCT_SUFFIX: 'avec audioguide',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Partenaire autorisé et de confiance',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Revendeur agréé',
    SUB_TEXT: 'Expériences authentiques de partenaires fiables et vérifiés.',
  },
  AVAILABLE: 'Disponible',
  BANNER_CTA: 'Voir nos offres',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout est une marque à laquelle des millions de visiteurs dans le monde font confiance et qui propose des expériences de qualité pour profiter du lieu.',
    NON_PARTNERED_SENSITIVE:
      "Headout est une marque à laquelle des millions de personnes dans le monde font confiance et qui propose des expériences de qualité pour profiter du lieu. Ceci n'est pas le site web du lieu.",
    PARTNERED_NON_SENSITIVE:
      'Headout est un partenaire autorisé et de confiance du site, qui propose des expériences de qualité pour profiter du lieu.',
    PARTNERED_SENSITIVE:
      "Headout est un partenaire autorisé et de confiance du site, qui propose des expériences de qualité pour profiter du lieu. Ceci n'est pas le site web du lieu.",
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout est un partenaire agréé et de confiance qui propose une sélection des meilleures expériences pour profiter de cette attraction.',
  BOOK_NOW_CTA: 'Réserver',
  BUY_TICKETS_CTA: 'Voir nos offres',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Vous pouvez annuler ces billets jusqu’à {0} heures avant le début de l’expérience et bénéficiez d’un remboursement complet.',
    CANCELLABLE_ANYTIME:
      'Annulation gratuite à tout moment avant le début de votre activité',
    CANCELLABLE_DAYS:
      'Vous pouvez annuler ces billets jusqu’à {0} jours avant le début de l’expérience et obtenir un remboursement complet.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Ces billets ne peuvent pas être annulés. Cependant, ils sont valables pour une période prolongée.',
    HEADING: 'Politique de modification',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Ces billets ne peuvent pas être annulés. Cependant, ils peuvent être reportés jusqu’à {0} heures avant le début de l’expérience.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Ces billets ne peuvent être ni annulés ni reportés.',
    VALID_UNTIL_DATE:
      'Ces billets ne peuvent pas être annulés. Cependant, vous pouvez les utiliser à tout moment jusqu’au {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Ces billets ne peuvent pas être annulés. Toutefois, vous pouvez les utiliser à tout moment pendant les {0} prochains jours.',
    VALID_WITHIN_NEXT_MONTHS:
      'Ces billets ne peuvent pas être annulés. Cependant, vous pouvez les utiliser à tout moment durant les {0} prochains mois.',
  },
  CANCELLATION_POLICY_HEADING: "Politique d'annulation",
  CASHBACK: 'Cashback de {0} %',
  CASHBACK_INFO:
    'Vous recevrez <strong>{0} %</strong> de crédits Headout en réservant cette activité. Votre réduction sera automatiquement créditée sur votre compte Headout et pourra être utilisée pour toute réservation future avec Headout.',
  CATEGORY_SLIDER_HEADING:
    'Les client·es qui ont réservé ce spectacle ont également vu',
  CHECK_AVAIL: 'Vérifier la disponibilité',
  CITY_PAGE: {
    BANNER_TITLE: 'Meilleures offres pour les expériences à',
    TOP_ATTRACTIONS: 'Meilleures attractions',
    GO_BEYOND: 'Aller au-delà de {0}',
    ALL_DAY_TRIPS: 'Voir toutes les escapades',
    CITIES_NEARBY: 'Villes à proximité',
    POPULAR_CATEGORIES: 'Catégories populaires',
    GO_TO_GUIDE: 'Guide pratique de {0}',
    VIEW_TRAVEL_GUIDE: 'Voir le guide de voyage',
    EXPLORE: 'Explorer {0}',
    GUIDE_SUBHEADING:
      "Explorer {0} n'a jamais été aussi facile ! Notre guide de voyage de {0} couvre tout ce que vous devez savoir sur la ville, de ce qu'il faut manger et ce qu'il faut y voir à comment s'y rendre, où se loger et bien plus !",
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Bon à savoir',
      WHERE_TO_EAT: 'Restauration',
      WHERE_TO_STAY: 'Hébergement',
      THINGS_TO_DO: 'Choses à faire',
      WEATHER: 'Meilleure période pour visiter',
      NEIGHBOURHOODS: 'Quartiers',
      TRANSPORTATION: 'Transport',
      TRIP_PLANNER: 'Plan de voyage',
      FAMILY_TRAVEL: 'Voyager avec des enfants',
      TRAVEL_TIPS: 'Trucs et astuces de voyage',
      SHOPPING: 'Boutiques',
      ART_AND_CULTURE: 'Arts et culture',
    },
    MAILER: {
      HEADING:
        'Des idées de voyage pour {0} directement dans votre boîte de réception',
      SUBHEADING:
        'Découvrez de nouvelles villes avec des expériences exclusives, des réductions, des offres exclusives et des conseils de voyage précieux !',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      "Renseignez-vous sur les conditions d'obtention d'un visa, les monnaies d'échange, les différences de fuseaux horaires et bien d'autres choses encore afin de faciliter votre arrivée et de rendre votre séjour agréable..",
    WHERE_TO_EAT:
      'Savourez une cuisine variée, des arômes de toutes sortes et des spécialités locales aux quatre coins de {0}.',
    WHERE_TO_STAY:
      'Découvrez les meilleurs hébergements de {0}, alliant confort, commodité et souvenirs inoubliables.',
    THINGS_TO_DO:
      'Profitez des nombreuses activités et attractions passionnantes qui répondront à vos attentes et vous feront passer un moment exceptionnel.',
    WEATHER:
      "Planifiez votre voyage judicieusement et profitez au maximum de votre visite, car {0} vous fait vivre des expériences magiques tout au long de l'année.",
    NEIGHBOURHOODS:
      'Apprenez à connaître les diverses communautés locales et les quartiers dynamiques qui confèrent à {0} son caractère unique.',
    TRANSPORTATION:
      'Parcourez {0} en douceur grâce à son système de transport efficace, qui vous offre des options pratiques pour découvrir toutes ses attractions.',
    TRIP_PLANNER:
      'Maximisez votre temps à {0} grâce à des itinéraires soigneusement élaborés, qui vous permettront de profiter au maximum de chaque instant.',
    FAMILY_TRAVEL:
      "Partez à l'aventure en famille grâce aux nombreuses attractions, parcs et activités de divertissement qui s'adressent aux enfants de tous âges.",
    TRAVEL_TIPS:
      "Faites le plein de conseils et d'astuces pour rendre votre visite à {0} vraiment exceptionnelle..",
    SHOPPING:
      "Explorez des boutiques, des marchés et des centres commerciaux où vous trouverez tout, de l'artisanat local à la mode de luxe, et qui sont un véritable paradis pour les amateurs de shopping.",
    ART_AND_CULTURE:
      'Découvrez une scène artistique et culturelle exceptionnelle, des musées fascinants aux festivals animés célébrant le patrimoine de {0}.',
  },
  CLOSE: 'Fermer',
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Nous utilisons des cookies et des technologies similaires à de nombreuses fins, notamment pour améliorer votre expérience sur notre site et pour les publicités.',
    MANAGE_PREFERENCES: 'Configuration',
    PREFERNCES_SAVED: 'Vos préférences ont été sauvegardées.',
    ACCEPT: 'Ok',
    ALLOW_ALL: 'Autoriser tout',
    DENY_ALL: 'Refuser tout',
    HEADING: `Nous accordons toujours de l'importance à votre vie privée`,
    COOKIES: 'Cookies :',
    DESCRIPTION: `*   Les cookies sont de petits fichiers placés sur votre ordinateur, votre appareil mobile ou tout autre appareil par le site Web/la plate-forme, contenant les détails de votre historique de navigation parmi ses nombreuses utilisations.
*   Nous utilisons différents types de cookies pour suivre votre utilisation de notre Plateforme et stocker certaines informations qui nous aident à vous fournir des services plus personnalisés. Certains cookies peuvent être placés sur votre appareil en raison de votre utilisation des services disponibles sur notre plate-forme.
*   D'une manière générale, nous utilisons deux ensembles différents de technologies dans ce cadre :
    *   Il s'agit d'un petit fichier qui est automatiquement placé sur votre appareil lorsque vous accédez à notre plate-forme. Vous pouvez configurer votre navigateur pour qu'il refuse tous les cookies. Dans ce cas, si Vous n'acceptez pas Nos Cookies, Il se peut que Vous ne puissiez pas utiliser certaines parties de Notre Plateforme.
    *   **Balises Web.** Également appelés " pixels invisibles ", " pixel tags " et " single-pixel gifs ", ils sont attachés à diverses sections de notre plate-forme et de nos courriels, ce qui nous permet de surveiller et de comprendre l'activité des utilisateurs.
*   Ces cookies stockés sur votre appareil peuvent être des cookies "persistants" ou des cookies "de session". Les cookies persistants sont ceux qui restent sur votre appareil même lorsque vous êtes hors ligne, tandis que les cookies de session sont automatiquement supprimés dès que vous fermez votre navigateur web.
*   Nous utilisons des cookies de session et des cookies persistants aux fins décrites ci-dessous :
    *   Cookies nécessaires / essentiels
        *   _Type :_ Cookies de session
        *   _Objectif :_ Ces cookies sont essentiels pour vous permettre d'accéder aux différentes sections de la plate-forme et, s'ils ne sont pas autorisés, vous risquez de ne pas pouvoir accéder aux services disponibles sur la plate-forme. Ces cookies nous aident également à authentifier les utilisateurs et à prévenir toute activité frauduleuse sur la plate-forme.
    *   Politique en matière de cookies / Avis Acceptation des cookies
        *   _Type :_ Cookies persistants
        *   _Objectif :_ ces cookies permettent de déterminer si les utilisateurs ont accepté l'utilisation de cookies.
    *   Cookies de fonctionnalité
        *   _Type :_ Cookies persistants
        *   _Objectif :_ Ces cookies nous permettent de nous souvenir des choix que vous faites lorsque vous utilisez la plate-forme, par exemple de vos données de connexion ou de vos préférences linguistiques. L'objectif principal de ces cookies est de vous offrir une expérience plus personnalisée à chaque fois que vous utilisez la plate-forme.

_Tous les termes en majuscules utilisés ci-dessus sont définis dans la politique de confidentialité. Pour une compréhension détaillée, veuillez vous référer à la politique de_ [_confidentialité._](/privacy-policy/)`,
  },
  COLLECTION_SLICE_HEADING: 'Meilleures choses à faire à {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Sélectionner',
    SELECT_PREFERENCE: 'Indiquez votre préférence',
    SELECT_OPTION: 'Sélectionnez votre option',
    SELECT_TICKET: 'Sélectionnez votre billet',
  },
  COMPARE_ALL_DETAILS: 'Comparer tous les détails',
  COVID19_ALERT: {
    KEY_TEXT: 'Mise à jour concernant la COVID-19',
    LINK: 'https://medium.com/headout/%C3%A9pid%C3%A9mie-de-coronavirus-politique-dannulation-595a47a8bb50',
    TEXT: `Vous êtes notre priorité. Veuillez consulter notre page d'assistance pour connaître les dernières mises à jour de nos politiques d'annulation flexibles.`,
  },
  CURRENCY: 'Devise',
  CUSTOMER_REVIEW_HEADING: 'Avis des client·es',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioguide',
    DURATION: 'Durée : {0}',
    EXTENDED_VALIDITY: 'Validité prolongée',
    FLEXIBLE_DURATION: 'Durée flexible',
    FREE_CANCELLATION: 'Annulation gratuite',
    GUIDED_TOUR: 'Visite guidée',
    HOTEL_PICKUP: `Départ depuis l'hôtel`,
    INSTANT_CONFIRMATION: 'Confirmation immédiate',
    MEALS_INCLUDED: 'Repas inclus',
    MOBILE_TICKET: 'Billets mobiles',
    SKIP_THE_LINE: 'Coupe-file',
    TRANSFERS: 'Navettes incluses',
  },
  DURATION: 'Durée',
  EARLIEST_AVAILABILITY: 'Prochaine disponibilité : ',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Saisissez votre adresse e-mail ici',
    SIGN_UP: "S'inscrire",
    THANK_YOU: 'Merci !',
    SUBSCRIBED_MSG: 'Vous êtes maintenant inscrit·e',
    ERROR_MSG: 'Veuillez saisir une adresse e-mail valide',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Billets de théâtre pour Broadway',
    },
    LTT: {
      MB_NAME: 'Billets de théâtre pour Londres',
    },
  },
  EXCLUSIONS: 'Non inclus',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '+ de 10 millions',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100 % sûr',
    HEADING_SUPPORT: "Centre d'aide 24/7",
    SUB_HEADING_CUSTOMER:
      'de client·es satisfait·es à travers + de 10 000 expériences',
    SUB_HEADING_RATING:
      '+ de 5 000 avis vérifiés avec 90 % de notes excellentes',
    SUB_HEADING_SAFE: 'Toutes les activités de plein air sont sûres à 100 %',
    SUB_HEADING_SUPPORT:
      'Une question ? Discutez en ligne avec des experts locaux, partout et à tout moment',
  },
  FLEXIBLE: 'Flexible',
  FOOTER: {
    CALL_US: 'Appelez-nous',
    CHAT_WITH_US: 'Chattez avec nous',
    COMPANY_DETAILS: 'Notre entreprise',
    INFORMATION: 'Informations',
    GMAPS_DISCLAIMER:
      "Toutes les captures d'écran des cartes figurant sur cette page proviennent de Google, conformément au droit à l'utilisation équitable. Tous les droits relatifs à ces captures d'écran appartiennent à la plateforme concernée, et leur utilisation est uniquement destinée à des fins d'information ou d'orientation.",
    DISCLAIMER: `Ce site n'est pas le site officiel <attraction>. Il est géré par Headout et travaille en collaboration avec des attractions et des tour-opérateurs pour vous offrir des expériences incroyables en un clic !`,
    EMAIL_US: 'Contactez-nous',
    GET_HELP: 'Aide',
    LEGAL: 'Légal',
    PRIVACY_POLICY: 'Politique de confidentialité',
    QUICK_LINKS: 'Raccourcis',
    TERMS_AND_CONDITIONS: 'Conditions générales',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Fait avec ',
    ALL_OVER_THE: ' à travers le ',
    TERMS_OF_USAGE: `Conditions d'utilisation`,
    GET_HELP_24_7: `Obtenir de l'aide 24/7`,
    HELP_CENTER: 'Assistance',
    COMPANY: 'Entreprise',
    WE_ACCEPT: 'Moyens de paiement',
    DOWNLOAD_HEADOUT: `Téléchargez l'application Headout`,
    SCAN_CODES: 'Scannez les code',
    STAR_VERIFIED: `Cliquez pour vérifier l'adhésion à S.T.A.R.`,
    OFFICIAL_TICKET_RETAILER: 'Revendeur Officiel de Billets',
  },
  FREE_CANCELLATION: 'Annulation gratuite',
  FREE_CANCELLATION_SUBTEXT: `Nous savons que les plans changent. Annulez jusqu'à 72 h à l'avance.`,
  FROM: 'à partir de',
  GET_CASHBACK: 'Recevez un cashback de {0} %',
  GROUP_TICKETS: 'Billets de groupe',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '+ de 20 millions de client·e·s',
    SUB_TEXT:
      'La satisfaction de nos client·e·s est notre priorité. Rejoignez le club !',
  },
  HELP_CENTER: {
    MAIN_TEXT: "Centre d'assistance 24h/7j",
    SUB_TEXT:
      'Une question ? Nous sommes disponibles par téléphone, chat et e-mail.',
  },
  INCLUSIONS: 'Inclus',
  LANGUAGE: 'Langue',
  LISTICLES: {
    KNOW_MORE: 'En savoir plus',
    SEATING_CHART: 'Plan de la salle',
    WHY_BOOK_FROM_US: 'Pourquoi choisir Headout ?',
  },
  MORE_DETAILS: `En savoir plus`,
  MORE_CURRENCIES: 'Autres devises',
  NEW: 'Nouveau',
  NEW_ARRIVAL: 'Nouveautés',
  NEXT_AVAILABLE: 'Prochaine disponibilité: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    "Headout est une marque de confiance qui a servi plus de 15 millions de personnes et qui propose une sélection des meilleures expériences. Ceci n'est pas le site web du lieu.",
  NO_RESULT_FOUND: 'Aucun résultat trouvé',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR:
    'Réservez avec flexibilité - Pas besoin de choisir une date',
  OPENING_DATE: 'Première date',
  OPENING_ON: 'Ouverture le',
  OPENS: 'Ouvre',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    "Headout est un partenaire agréé et de confiance qui propose une sélection des meilleures expériences pour profiter de cette attraction. Ceci n'est pas le site Web de l'attraction.",
  POPULARITY: 'Popularité',
  POPULAR_CURRENCIES: 'Devises principales',
  PRICE: 'Prix',
  PRICES_STARTING: 'À partir de',
  PROMO_CODES: {
    APPLIED: 'APPLIQUÉ',
    APPLY_CODE: 'APPLIQUER LE CODE',
    DESCRIPTION: {
      ABSOLUTE: 'Réduction de {0}',
      CAPPED: "Réduction de {0} %, jusqu'à {1}",
      PERCENTAGE: 'Réduction de {0} %',
    },
    REMOVE: 'SUPPRIMER',
    TOOL_TIP_INFO: 'Cette réduction sera appliquée lors du paiement',
  },
  RATINGS: '{0} Notes',
  READ_MORE: 'En savoir plus',
  READ_MORE_TEXT: 'En savoir plus',
  READ_LESS: 'Voir moins',
  VIEW_DETAILS: 'Voir les détails',
  REOPENING: 'Réouverture',
  REOPENING_DATE: 'Date de réouverture',
  REOPENING_ON: 'Réouverture le',
  REOPENS: 'Réouvre',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT: "La règle 2G s'applique : l'accès aux établissements d'hébergement, aux institutions culturelles et aux restaurants/bars, entre autres, n'est possible que sur présentation d'une preuve de vaccination complète ou d'une infection passée. Un test Covid-19 négatif n'est plus suffisant.",
    },
    AU_DESCRIPTION: {
      TEXT: "Les visiteurs et visiteuses âgé·es de 16 ans et plus doivent présenter une preuve de vaccination contre la COVID-19 ou un certificat d'exemption médicale.",
    },
    BANNER_CTA: 'En savoir plus',
    BERLIN_DESCRIPTION: {
      TEXT: "La règle 2G s'applique : seules les personnes complètement vaccinées et guéries, sur présentation d'un jpass sanitaire, auront accès à l'établissement. Les personnes de moins de 18 ans ou celles et ceux qui ne peuvent pas être vacciné·es pour des raisons médicales doivent présenter à l'entrée un résultat négatif à la test COVID-19. Les personnes qui ne peuvent pas être vaccinées pour des raisons médicales doivent également prouver leur incapacité à se faire vacciner au moyen d'un certificat médical à l'entrée.",
    },
    CTA_TEXT: 'Détails des mesures de sécurité et sanitaires',
    DESCRIPTION_CTA: 'En savoir plus.',
    EU_DESCRIPTION: {
      TEXT: "À partir du 21 juillet 2021, tous les visiteurs et visiteuses âgé·es de 12 ans et plus devront présenter un certificat COVID de l'UE.",
    },
    EU_HEADING: 'Certificat COVID numérique UE requis',
    EU_PREFIX: 'Attention : ',
    EXPERIENCE_DESCRIPTION:
      "Cette expérience a été vérifiée et respecte les normes de sécurité et sanitaires, conformément aux réglementations locales et aux directives de l'OMS.",
    FLAG_TEXT: 'Protection renforcée',
    GENERAL_DESCRIPTION:
      'Toute expérience affichant ce badge a été vérifiée et est conforme aux normes de sécurité établies par les autorités locales en matière de santé.',
    HEADING: 'Normes de sécurité et sanitaires en vigueur',
    IT_DESCRIPTION: {
      TEXT: "À partir du 6 août 2021, tous les visiteurs et visiteuses âgé·es de 11 ans et plus devront présenter un pass sanitaire ou un certificat COVID de l'UE.",
    },
    IT_PREFIX: 'Important : ',
    MOBILE_HEADING: 'Expériences conformes aux normes sanitaires',
    MODAL: {
      BADGE_DESCRIPTION:
        'Ce badge atteste que les normes de sécurité et sanitaires ont été vérifiées par pour cette expérience.',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Tous les équipements, les véhicules et les espaces à forte fréquentation sont nettoyés après chaque utilisation. Détendez-vous et profitez de votre séjour et visite.',
          HEADING: 'Tous les équipements et espaces sont désinfectés',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Tous les équipements mis à votre disposition au cours de votre visite sont soigneusement nettoyés après chaque utilisation.',
          HEADING: 'Tous les équipements et espaces sont désinfectés',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Tous les véhicules mis à votre disposition pendant votre séjour sont soigneusement nettoyés après chaque utilisation.',
          HEADING: 'Tous les véhicules sont désinfectés',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            "Pour toute expérience conforme aux normes sanitaires, vous aurez accès à des installations sanitaires et à des points d'eau pour vous laver les mains tout au long de votre visite. Nous avons tout prévu.",
          HEADING:
            'Des installations sanitaires et pour se laver les mains sont disponibles partout',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Le port du masque est obligatoire pour tous les visiteurs et membres du personnel de cette expérience. Cette mesure assure ainsi à chacun de passer un bon moment en toute sécurité.',
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            "Nos partenaires qui ont été vérifiés en tant qu'expérience conforme aux normes sanitaires appliquent les réglementations locales en vigueur concernant le port du masque. Si le port du masque est obligatoire, tous les visiteurs et membres du personnel en porteront un. Nos partenaires prennent toutes les mesures possibles pour assurer votre confort et votre sécurité.",
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Le port du masque est obligatoire pour tous les visiteurs de cette expérience. Cette mesure assure ainsi à chacun de passer un bon moment en toute sécurité.',
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Tous les membres du personnel qui travaillent sur ce site portent un masque de protection pour que vous puissiez vous amuser sans aucun souci.',
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Les expériences conformes aux normes sanitaires respectent en tout temps les lignes directrices en matière de distance sociale. Afin de faire respecter ces directives, il se peut que la capacité du lieu soit restreinte et que des limites de groupe soient mises en place.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Les expériences conformes aux normes sanitaires respectent en tout temps les lignes directrices en matière de distance sociale. Afin de faire respecter ces directives, il se peut que la capacité du lieu soit restreinte et que des limites de groupe soient mises en place. Par ailleurs, les grands groupes ne sont pas autorisés.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Tout au long de votre visite, les lignes directrices en matière de distance sociale sont respectées.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            "Les expériences classées sans risque respectent en tout temps les lignes directrices en matière de distance sociale. Afin de faire respecter ces directives, il se peut que la capacité du lieu soit restreinte et que des limites de groupe soient mises en place. Nous faisons en sorte que vous vous sentiez à l'aise.",
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Tout au long de votre visite, les lignes directrices en matière de distance sociale sont respectées. Par ailleurs, les grands groupes ne sont pas autorisés.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            "La température de tous les visiteurs sera prise au début de l'expérience afin de garantir la sécurité de tous. Tous les membres du personnel sont examinés à plusieurs reprises pour vérifier si leur température est élevée.",
          HEADING: 'Contrôles de température en vigueur',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            "La température de tous les visiteurs sera prise au début de l'expérience afin de garantir la sécurité de tous.",
          HEADING: 'Contrôles de température en vigueur',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Tous les membres du personnel sont examinés à plusieurs reprises pour vérifier si leur température est élevée. Les employés dont la température est supérieure à la limite prescrite ne peuvent entrer sur le site et sont priés de rester chez eux pour un prompt rétablissement.',
          HEADING: 'Contrôles de température en vigueur',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            "Le personnel présent tout au long de votre visite est formé aux directives de l'OMS et équipé pour faire face à toute situation d'urgence éventuelle.",
          HEADING: "Le personnel est formé aux directives de l'OMS",
        },
      },
      HEADING: 'Expériences conformes aux normes sanitaires',
      SUB_HEADING:
        "Headout collabore avec ses partenaires dans le monde entier pour appliquer les normes de sécurité et sanitaires conformément aux directives de l'OMS. Toutes les mesures prises sur le terrain ont été vérifiées et sont indiquées ici. Il est grand temps de profiter à nouveau du monde qui nous entoure.",
    },
    NL_DESCRIPTION: {
      TEXT: "Les visiteurs et visiteuses âgé·es de 13 ans et plus doivent être en possession d'un certificat COVID (copie numérique ou imprimée) attestant de leur vaccination, d'un résultat négatif au test ou de leur rétablissement récent de la COVID-19. Le port d'un masque est obligatoire.",
    },
    SG_DESCRIPTION: {
      TEXT: "À partir du 13 octobre 2021, seul·es les visiteurs et visiteuses entièrement vacciné·es pourront entrer par groupes de 2. Vous devrez présenter une preuve de votre statut vaccinal, un résultat négatif récent du test COVID-19 et/ou tout document de rétablissement avant l'entrée.",
    },
    SHORT_HEADING: 'Toutes les normes de sécurité et sanitaires en vigueur',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Votre sécurité est notre priorité.',
    TEXT: "Nous avons pris des mesures importantes pour améliorer la propreté des lieux au moyen de désinfectants et de nettoyages approfondis et fréquents des surfaces. Nous contrôlons également la fréquentation afin d'éviter tout encombrement.",
  },
  SAVE: 'Économisez {0} %',
  SAVE_PERCENT: 'Économisez {0} %',
  SAVE_UPTO: "Économisez jusqu'à",
  SAVE_UPTO_PERCENT: "Économisez jusqu'à {0} %",
  SEARCH: 'Rechercher',
  SEE_ALL: 'Voir tout',
  SEE_MORE_SHOWS: 'Voir plus de spectacles',
  SELECT_CITY: 'Sélectionner une ville',
  SELECT_SECTION: 'Sélectionner une tribube',
  SEE_ALL_PHOTOS: 'Voir toutes les photos',
  SHOW_CLOSED: 'Spectacle terminé',
  SHOW_LESS_TEXT: 'Voir moins',
  SHOW_PAGE: {
    ABOUT_SHOW: 'À propos du spectacle',
    ABOUT_THEATRE: 'À propos du théâtre',
    ADDITIONAL_INFORMATION: 'Informations supplémentaires',
    AGE_LIMIT: "Limite d'âge",
    AGE_SUITABILITY: "Limite d'âge",
    ANSWER: ['R-', 'A-'],
    BLOG_SHOW_PAGE: 'Page du spectacle du blog',
    BLOG_SUMMARY: 'Résumé du blog',
    BLOG_THEATRE_PAGE: 'Page du théâtre du blog',
    BLOG_THEATRE_SEATING_PLAN: 'Plan du théâtre du blog',
    CANCELLATION_AND_REFUNDS: 'Annulation et remboursements',
    CANCELLATION_POLICY: "Politique d'annulation",
    CAST_AND_CREW: "Les acteurs et l'équipe",
    CLOSING_DATE: 'Date de clôture',
    CLOSING_DATE_SPECIAL_OFFER: 'Offre spéciale pour la date de clôture',
    DURATION: 'Durée',
    FACILITIES_AND_ACCESSIBILITY: 'Installations et accessibilité',
    FREQUENTLY_ASKED_QUESTIONS: 'Foire aux questions',
    GETTING_THERE: "Comment s'y rendre",
    GETTING_THERE_MAP_LINK: "Comment s'y rendre",
    GOOGLE_MAP: 'Google Map',
    HIGHLIGHTS: 'Points forts',
    LISTICLE_SHOW_SUMMARY: 'Listicle Résumé du spectacle',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Pourquoi faut-il voir le spectacle',
    OPENING_DATE: "Date d'ouverture",
    QUESTION: ['Q-'],
    SAFETY_BANNER: 'Bannière de sécurité',
    SHOW_DETAILS: 'Informations sur le spectacle',
    SHOW_TIMINGS: 'Horaires des représentations',
    SHOW_TYPE: 'Type de spectacle',
    SPECIAL_OFFER: 'Offre spéciale',
    THE_STORY: "L'histoire",
    THEATRE_ADDRESS: 'Adresse du théâtre',
    THEATRE_CAPACITY: 'Capacité du théâtre',
    THEATRE_NAME: 'Nom du théâtre',
    TICKETS: 'Billets',
    TICKETS_REDEMPTION: 'Échange des billets',
    TOP_SONGS: 'Meilleures chansons',
    YOUR_TICKETS: 'Vos billets',
    ABOUT_CONCERT: 'Le concert',
    PROGRAM: 'Programme',
  },
  SORT_BY: 'Trier par',
  THEATRE: 'Théâtre',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Théâtres dans le coin',
    NOW_PLAYING: `À l'affiche`,
    UPCOMING_SHOWS: 'Prochains spectacles',
    PAST_SHOWS: 'Anciens spectacles',
    FIND_BEST_SEATS: 'Trouver les meilleures places',
  },
  SPECIAL_OFFER: 'Offre spéciale',
  TICKET_CAN_BE_CANCELED: `Vous pouvez annuler jusqu'à {hours} heures à l'avance pour un remboursement complet.`,
  TICKET_CANNOT_BE_CANCELED:
    'Ce billet ne peut être annulé mais peut être reporté sur demande.',
  TICKETS: 'Billets',
  TIMINGS: 'Horaires',
  SPECIAL_PRODUCT_HEADING: 'Expérience adorée',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Guides expert·es',
    ENGAGING_STORIES: 'Récits captivants',
    TOP_RATED: 'La mieux notée',
  },
  GUIDED_TOUR_REVIEWS: [
    'Notre guide Angela était formidable et connaissait parfaitement les lieux',
    'Le guide était très heureux de répondre aux questions concernant la visite',
    'Notre guide était formidable et nous a même recommandé un excellent déjeuner!',
    "L'organisation et notre guide ont rendu l'expérience très agréable",
    'Beaucoup de contenu éducatif, je le referai sûrement avec mes enfants',
    "La visite a été bien organisée et a duré le temps qu'il fallait",
    'Bon guide et bonne organisation! A recommander!!!',
    'Notre guide, Maria, a réussi à nous trouver les meilleurs points de vue',
    'Visite détaillée et émouvante menée par un guide passionné',
    "Jeff nous a montré des aspects du lieu que nous n'aurions pas vus autrement",
    '',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Anglais',
    SPANISH: 'Espagnol',
    FRENCH: 'Français',
    ITALIAN: 'Italien',
    GERMAN: 'Allemand',
    PORTUGUESE: 'Portugais',
    NEDERLANDS: 'Néerlandais',
    POLISH: 'Polonais',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Visite disponible en {0}',
  GUIDES_BANNER: 'Vivez une expérience authentique avec nos super guides.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Une visite guidée est le meilleur moyen de découvrir cette destination. Nos guides expert·es sont vos partenaires locaux : ils partagent avec vous histoires, secrets et conseils.',
    'Ne vous contentez pas de visiter, vivez l’expérience !',
  ],
  HEAR_FROM_OUR_GUESTS: 'Avis de nos visiteurs',
  TODAY: "aujourd'hui",
  TOMORROW: 'demain',
  TOUR_LIST_HEADING: `Sélectionnez l'offre qui vous plaît`,
  TOUR_LIST_SUB_HEADING:
    'Choisissez parmi une multitude de billets, visites guidées et offres combo proposés par des agences de tourisme.',
  UGC: {
    FOLLOW: 'Suivre',
    FOLLOW_IG: 'Suivre sur Instagram',
    HEADING: 'POV : Voici à quoi ressemble votre prochaine aventure',
    SUB_HEADING: 'Sélectionnée avec 💜 par Headout',
  },
  UNAVAILABLE: 'Indisponible',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Ces billets sont valables pour une durée prolongée. Les détails exacts seront indiqués sur le billet.',
    UNTIL_DATE: 'Ces billets sont valables jusqu’au {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Ces billets sont valables pendant {0} jours à compter de la date d’achat.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Ces billets sont valables pendant {0} mois à compter de la date d’achat.',
  },
  TABLE_OF_CONTENTS: 'Sommaire',
  VIEW_LESS: 'Voir moins',
  VIEW_MORE: 'En savoir plus',
  WHY_TAKE_THIS_DAY_TRIP: 'Les avantages de cette excursion',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Menu principal',
    EXPLORE: 'Explorer',
    VISIT: 'Visiter',
    THINGS_TO_DO: 'Choses à faire',
    CITY_ATTRACTIONS: 'Que faire à {0}',
    TOP_THINGS_TO_DO: 'Meilleures choses à faire',
    CITY_TOURS: 'Visites de {0}',
    CITY_GUIDE: 'Guide de la ville',
    ATTRACTIONS: 'Attractions',
    CRUISES: 'Croisières',
    THEMES: 'Thèmes',
    ABOUT: 'À propos',
    TOURS: 'Visites',
    SKIP_THE_LINE: 'Visites coupe-file',
    GUIDED_TOURS: 'Visites guidées',
    NIGHT_TOURS: 'Visites en soirée',
    FOOD_TOURS: 'Visites culinaires',
    HISTORY: 'Histoire',
    ARCHITECTURE: 'Architecture',
    DESIGN: 'Conception',
    INSIDE: 'Intérieur',
    COLLECTIONS: 'Collections',
    PAINTINGS: 'Tableaux',
    ANIMALS_EXHIBITS: 'Animaux et expositions',
    HABITATS: 'Habitats',
    CONSERVATION: 'Conservation',
    PROGRAMMES: 'Programmes',
    A2_SIGHTSEEING_CRUISES: 'Croisières promenade',
    A2_DINNER_CRUISES: 'Dîners-croisières',
    A2_EVENING_CRUISES: 'Croisières en soirée',
    A2_LUNCH_CRUISES: 'Déjeuners-croisières',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Planifier votre visite',
    TIMINGS: 'Horaires',
    DIRECTIONS: "Comment s'y rendre",
    PARKING: 'Parking',
    ROUTES: 'Itinéraires',
    REQUIREMENTS: 'Spécifications',
    LOCATION: 'Emplacement',
    RULES: 'Règles',
    FAQs: 'FAQ',
    ENTRANCES: 'Entrées',
    RESTAURANTS: 'Restaurants',
    FACTS: 'Anecdotes',
    TIPS: 'Conseils',
    MAP: 'Plan',
    RIDES: 'Manèges',
    SHOWS: 'Spectacles',
    DINING: 'Restauration',
    SHOPPING: 'Boutiques',
    EVENTS: 'Événements',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Noël',
    NEW_YEARS_EVE: 'Nouvel An',
    TRAVEL_GUIDE: 'Carnet de voyage',
    TRIP_PLANNER: 'Planificateur de voyage',
    ITINERARY: 'Itinéraire',
    TRAVEL_TIPS: 'Conseils de voyage',
    WEATHER: 'Météo',
    BEST_TIME_TO_VISIT: 'Meilleur moment pour visiter',
    JANUARY: 'Janvier',
    FEBRUARY: 'Février',
    MARCH: 'Mars',
    APRIL: 'Avril',
    MAY: 'Mai',
    JUNE: 'Juin',
    JULY: 'Juillet',
    AUGUST: 'Août',
    SEPTEMBER: 'Septembre',
    OCTOBER: 'Octobre',
    NOVEMBER: 'Novembre',
    DECEMBER: 'Décembre',
    WHERE_TO_EAT: 'Où manger',
    WHERE_TO_STAY: 'Où séjourner',
    NEIGHBOURHOODS: 'Quartiers',
    FAMILY_TRAVEL: 'Voyages en famille',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivals et événements',
  },
  WHY_WATCH: 'Pourquoi faut-il le voir {0}?',
  FIND_ON_MAP: 'Trouver sur la carte',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Billets de guichet',
        DESCRIPTION: 'Confirmation directe sur votre téléphone',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Choisissez vos sièges`,
        DESCRIPTION: 'Profitez de la vue que vous désirez',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Offres et réductions exclusives',
        DESCRIPTION: `Les meilleurs spectacles à petit prix`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Réservez en toute simplicité',
        DESCRIPTION: '25 millions de spectateurs satisfaits',
      },
    },
    YOUR_PICK: 'Votre choix',
    BROWSE_BY_CATEGORIES: 'Explorer par catégories',
    TOP_WEST_END_SHOWS: 'Les meilleurs spectacles de West End',
    TOP_THEATRE_SHOWS: '{0} : les meilleurs spectacles',
    TOP_SHOWS: 'Meilleurs spectacles',
    SEE_MORE_SHOWS: 'Voir {0} spectacles en plus',
    LAST_MINUTE_TICKETS: 'Billets de dernière minute',
    LOVED_BY_MILLIONS: 'Aimés par des millions de personnes',
    TODAY: `Aujourd'hui`,
    TOMORROW: 'Demain',
    SEE_ALL: 'Voir tout',
    GRAB_YOUR_TICKETS: 'Achetez vos billets maintenant',
  },
  TAG_NAME: {
    BALLET: 'Spectacles de ballet',
    CABARET: 'Cabaret',
    CHRISTMAS: 'Noël',
    CIRCUS: 'Cirque',
    CLASSIC: 'Classique',
    COMEDY: 'Comédie',
    COMING_SOON: 'Prochainement',
    CRITICS_CHOICE: 'Choix de la critique',
    DANCE: 'Danse',
    DISNEY: 'Disney',
    DRAMA: 'Drame',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantaisie',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Théâtre immersif',
    JUKEBOX: 'Jukebox',
    KIDS: 'Enfants',
    MAGIC: 'Spectacle de magie',
    MUSICALS: 'Comédies musicales',
    NEW_ARRIVAL: 'Nouveautés',
    OFF_WEST_END: 'Hors West End',
    OLIVIER_WINNER: "Lauréat d'Olivier",
    OPERA: 'Opéras',
    PANTOMIMES: 'Pantomimes',
    PLAYS: 'Pièces de théâtre',
    ROMANCE: "Histoire d'amour",
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Avec célébrités',
    THEATRICAL_CONCERT: 'Concert théâtral',
    TRUE_STORY: 'Basé sur une histoire vraie',
    TONY_WINNER: 'Lauréat des Tony Awards',
    OFF_BROADWAY: 'Hors Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Oups, nous avons un problème',
    MESSAGE: `Oh non ! Toutes les expériences proposées à cette date sont soit épuisées, soit indisponibles. Mais nous pouvons vous en proposer plusieurs à d'autres dates. Vous avez amplement le choix !`,
    CTA: 'Voir les dates disponibles',
  },
  ALL_DATES: 'Toutes les dates',
  BREADCRUMBS: {
    HOME: 'Accueil',
    TRAVEL_GUIDE: 'Guide de voyage',
    THINGS_TO_DO: 'Que faire à {0}',
    SHOW_NAME_TICKETS: '{0} - Billets',
    LTT_HOME: 'Billets de théâtre à Londres',
    LTT_VENUE_PAGE_HOME: 'Théâtres à Londres',
    BROADWAY_HOME: 'Billets pour les spectacles de Broadway',
    BROADWAY_VENUE_PAGE_HOME: 'Théâtres de Broadway',
    VIENNA_CONCERT_HOME: 'Billets de concert à Vienne',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Salles de concert à Vienne',
    ATTRACTIONS: 'Attractions',
    A2_SIGHTSEEING_CRUISES: 'Croisières promenade',
    A2_DINNER_CRUISES: 'Dîners-croisières',
    A2_EVENING_CRUISES: 'Croisières en soirée',
    A2_LUNCH_CRUISES: 'Déjeuners-croisières',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'Actualités des théâtres de Londres',
    BROADWAY_SHOW_NEWS: 'Actualités des spectacles de Broadway',
    NEWS_PAGE: 'Actualités',
    REVIEWS_PAGE_BANNER_HEADING: 'Avis sur {0}',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Café',
    'Dedicated Parking': 'Parking réservé',
    Elevators: 'Ascenseur',
    Lift: 'Ascenseur',
    'Wheelchair Accessible': 'Accès en fauteuil roulant',
    Cloakroom: 'Vestiaire',
    'Air Conditioning': 'Air conditionné',
    WiFi: 'WiFi',
    Bar: 'Bar',
    'Water Fountain': "Fontaine d'eau",
    Washrooms: 'Toilettes',
    Toilets: 'Toilettes',
    Binoculars: 'Jumelles',
    'Adapted Toilets': 'Toilettes adaptées',
    'Accessible Toilets': 'Toilettes accessibles',
    'Assistive Listening System': "Système d'écoute assistée",
    'Hearing Assistance': 'Assistance auditive',
    'Booster Cushions': "Coussins d'appoint",
    Shop: 'Boutique',
    'Souvenir Shop': 'Boutique de souvenirs',
    'Guide Dogs': 'Chiens guides',
    'Baby Changing Facilities': 'Espace de change pour bébés',
    'Security Check': 'Contrôle de sécurité',
    Ramp: "Rampe d'accès",
    'Level Access': 'Accès au niveau',
  },
  CALENDAR: {
    FOOTNOTE: '* Tous les prix sont en {0}',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Voir le commentaire original en {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Ce commentaire est traduit. Voir le commentaire original.',
    TRANSLATE: 'Traduire le commentaire en {0}',
    LANGUAGES: {
      EN: 'anglais',
      ES: 'espagnol',
      FR: 'français',
      IT: 'italien',
      DE: 'allemand',
      PT: 'portugais',
      NL: 'néerlandais',
    },
  },
  SHOW_PAGE_V2: {
    SELLING_OUT_FAST: 'Bientôt épuisé',
    INTERVAL: 'Entracte',
    TWO_PART_SHOW: 'Spectacle en deux parties',
    READ_MORE_REVIEWS: 'Lire plus d’avis',
    SHOW_MORE_REVIEWS: 'Afficher plus d’avis',
    ALL_PHOTOS: 'Toutes les photos',
    MORE_DATES: 'Plus de dates',
    SELECT_TIME_SLOT: 'Sélectionner un créneau horaire',
    SELECT_TIME_SLOT_ERROR: 'Sélectionner un créneau horaire pour continuer',
    PRICE_STARTING_FROM: 'Prix des places à partir de',
    SELECT_SEATS: 'Sélectionner vos places',
    READ_MORE: 'En savoir plus',
    RATINGS_AND_REVIEWS: 'Notes et avis',
    READ_DETAILED_REVIEWS: 'Lire les avis détaillés',
    UNTIL_DATE: 'Jusqu’au {0}',
    AVAILABLE_TIME: 'Créneau horaire disponible',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Cette expérience est disponible uniquement à l’heure indiquée ci-dessous',
    CONTENT_TABS: {
      ABOUT: 'À propos',
      VENUE: 'Lieu',
      TICKETS: 'Billets',
      Reviews: 'Critiques',
    },
    SELECT_SHOW_TIMMING: "Sélectionner l'heure du spectacle",
    ONLY_ONE_SLOT:
      "Il n'y a qu'un seul créneau horaire disponible à la date sélectionnée",
    SIMILAR_SHOWS: 'Vous pourriez aussi aimer',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Histoire',
      AGE_SUITABILITY_AND_GUIDELINES: 'Âge et autres indications',
      WHAT_CRITICS_THINK: 'Ce que pensent les critiques',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Foire aux questions',
      CAST_AND_CREATIVES: "Les acteurs et l'équipe",
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Guides multilingues spécialisés',
    STL: 'Accès coupe-file',
    PERSONALIZED: 'Expérience personnalisée',
    LOCAL_FOOD: 'Cuisine et culture locales',
    MULTILINGUAL_GUIDES: 'Guides multilingues',
    CULINARY_EXPERTS: 'Rencontre avec des gastronomes',
    SIGHTSEEING: 'Visites et divertissements à bord',
    SIGHTSEEING_MEAL: 'Visite touristique et choix de repas à bord',
    MULTILINGUAL_GT: 'Visites guidées en plusieurs langues',
    AUDIOGUIDE_COMMENTARY: 'Audioguide et commentaires disponibles',
    ALL_TOP_ATTRACTIONS_COVERED: 'Avec toutes les principales attractions',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Horaire régulier. Trajets illimités',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Disponibilité de dernière minute. Confirmation rapide',
    MULTI_ROUTES: 'Plusieurs itinéraires',
    HASSLE_FREE: 'Réservation en toute simplicité',
    FREQUENT_DEPARTURES: 'Départs fréquents',
    ONBOARD_AMENITIES: 'Meilleurs services à bord',
    FLEXI_TRAVEL: 'Voyage flexible sur plusieurs itinéraires',
    FLEXI_EXCHANGE_CANCEL: 'Échanges et annulations flexibles',
    EXTRA_DISCOUNT:
      'Réductions supplémentaires pour les jeunes, les seniors et les familles',
    PREPAID: 'Service de prépaiement',
    EASY_ACTIVATION: 'Activation facile',
    INSTANT_CONNECTIVITY: 'Connectivité immédiate avec une couverture mondiale',
    ROUND_TRIP: 'Navettes aller-retour',
    CULTURAL_EXPERIENCE: 'Expériences culturelles authentiques',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
    LUGGAGE_ASSISTANCE: 'Aide pour les bagages',
    TOP_ATTRACTIONS: 'Principales attractions incluses',
    FREQ_DEP_MULTI_ROUTE: 'Départs fréquents sur plusieurs itinéraires',
    CHARGING: 'Borne de recharge',
    WIFI: 'Accès au Wi-Fi',
    FnB: 'Nourriture et boissons',
    LUXURY: 'Expérience de luxe',
    FOOD_DRINK: 'Nourriture et boissons',
    PANAROMIC: 'Vues panoramiques des principales attractions',
    PANAROMIC_2: 'Vues panoramiques',
    PANAROMIC_3: 'Vues panoramiques à ciel ouvert',
    BEVERAGES: 'Boissons à bord',
    GOURMET: 'Dîner gastronomique',
    GOURMET_2: 'Dîner gastronomique et boissons',
    NIGHTTIME: 'Vues splendides de nuit',
    ROMANTIC: 'Ambiance romantique',
    TRANSFERS: 'Navettes comprises',
    CERTIFIED_OP: 'Opérations certifiées',
    BIRD_EYE: 'Vue aérienne',
    MULTI_JUMP: 'Plusieurs horaires de saut',
    EXTREME_ADV: 'Aventure extrême',
    PHOTO_OP: 'Possibilités de photos panoramiques',
    TOP_ATTRACTIONS_COVERED: 'Attractions principales',
    LOCAL_CULTURE: 'Découverte de la culture locale',
    EXCLUSIVE_DISC: 'Réductions exclusives',
    EFFICIENT_PUBLIC_TRANSIT: 'Transports publics efficaces',
    FREQUENT_SERVICE: 'Service fréquente',
    PREBOOKING: "Réservation à l'avance facile",
    LOCAL_CULTURE_IMM: 'Immersion dans la culture locale',
    DISCOVER_HIDDEN: 'Découverte de lieux cachés',
    CITY_SIGHTSEEING: 'Visites de la ville',
    OFFBEAT_ADV: 'Expérience insolite',
    DRINK_DEALS: 'Offres sur les boissons',
    OFFBEAT_EXP: 'Expérience insolite',
    MULTIPLE_VARIETIES: 'Variétés locales incluses',
    HIDDEN_GEMS: 'Trésors cachés et attractions insolites',
    EXPLORE_LOCAL: 'Découverte des quartiers locaux',
    CUSTOMIZED_TREATMENTS: 'Soins personnalisés',
    TRAINED_THERAPISTS: 'Thérapeutes qualifiés',
    HOLISTIC_WELLNESS: 'Bien-être intégrals',
    FLEXIBLE_DURATION: 'Durée flexible',
    MULTI_BOAT: 'Plusieurs options de bateaux',
    SCENIC_ROUTES: 'Itinéraires panoramiques',
    HANDS_ON: 'Apprentissage pratique',
    CULTURAL_CULINARY: 'Culture et gastronomie',
    EXPERT_HOSTS: 'Hôtes spécialisés',
    ADVENTURE_EXPERIENCE: 'Aventure',
    EQUIPMENT: 'Équipement inclus',
    SCENIC_FLYOVERS: 'Survols de paysages',
    LIVE_COMMENTARY: 'Commentaires en direct',
    BEST_AERIAL_VIEWS: 'Meilleures vues aériennes',
    SAFE_CERT_OP: 'Activités sûres et certifiées',
    HANDPICKED: 'Visites/options soigneusement choisies',
    EFFORTLESS: 'Planification simple',
    EXPERT_GUIDES: 'Guides expert·es. Informations uniques',
    ALL_ATTR_ONE_CARD: 'Toutes les attractions en une seule carte',
    MULTI_CARD: 'Plusieurs options de cartes',
    COST_EFF: 'Bon rapport qualité/prix et pratique',
    EASY_BEST: 'Réservation facile aux meilleurs prix',
    INSTANT_MOBILE: 'E-billets avec confirmation rapide',
    MULTI_TRANSPORT: 'Plusieurs options de transport',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Tout',
    POPULAR_SUBCATEGORY: '{0} : les expériences populaires',
    TOP_CATEGORY: '{0} : les meilleures expériences',
    ATTRACTIONS: 'Attractions',
    ALL_SUBCATEGORY: '{0} : toutes les expériences',
    BROWSE_BY_CATEGORIES: 'Parcourir par catégories',
    TICKETS_FROM: 'Billets à partir de',
    PRICE_LOW_HIGH: 'Prix (du plus bas au plus haut)',
    PRICE_HIGH_LOW: 'Prix (du plus haut au plus bas)',
    FILTERS: 'Filtres',
    RESET: 'Réinitialiser',
    APPLY: 'Appliquer',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout utilise des cookies pour améliorer votre visite du site Web.',
    MOBILE: 'Nous utilisons des cookies.',
    LEARN_MORE: 'En savoir plus.',
  },
  SHOW_UNAVAILABLE: 'Spectacle indisponible',
  NEWS_PAGE: {
    FEATURED_NEWS: 'On en parle',
    ALL_NEWS: 'Tous les articles',
    MORE_READS: "Plus d'articles",
    LOAD_MORE: `Voir plus d'articles`,
    TRAILERS: 'Toutes les bandes-annonces',
    GET_YOUR_TICKETS: 'Achetez vos billets',
    POPULAR_SHOWS: 'Spectacles populaires',
    FEATURED: ' À la une',
    RECENT_NEWS: 'Derniers articles',
    SHOW_MORE_ARTICLES: `Afficher plus d'articles`,
    COLLAPSE_ALL: 'Réduire tout',
    REVIEWS: 'Avis',
    SHOW_ALL_REVIEWS: 'Voir tous les avis',
    MAILER: {
      HEADING:
        'Les meilleures offres de théâtre et actualités tout droit dans votre boîte de réception',
      SUBHEADING: `Inscrivez-vous à notre liste pour recevoir les dernières informations et les offres les plus intéressantes sur les spectacles et pièces de théâtre.`,
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: 'Avis sur {0}',
    REVIEWS_COUNT: '{0} avis',
    AWESOME: 'Génial',
    GOOD: 'Bon',
    AVERAGE: 'Moyenne',
    POOR: 'Mauvais',
    TERRIBLE: ' Très mauvais ',
    REVIEW_BY_HEADOUT: 'Ce que nous en pensons : Avis de Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Ce que les gens en disent',
    MOST_RELEVANT: 'Pertinence',
    RATING_HIGH_TO_LOW: 'Par ordre décroissant',
    RATING_LOW_TO_HIGH: 'Par ordre croissant',
    CRITIC_REVIEWS: 'Avis de la critique',
    USER_REVIEWS: 'Avis des spectateurs',
    CONTRIBUTORS_REVIEW: 'Avis de le rédaction',
  },
  HOHO: {
    HOHO: 'Billets Hop-On Hop-Off',
    BUS_ROUTES_DETAILS: 'Itinéraires',
    TOUR_DETAILS: 'Détails du tour',
    ROUTES_SCHEDULES: 'Itinéraires et horaires',
    VALIDITY: 'Valable pour 1 jour',
    VALIDITY_NOTE:
      "Votre expérience est valable pour {0} jour(s) calendaire(s). Si vous réservez votre billet pour le 6 mai 2023, votre billet sera valable jusqu'au 6 mai 2023 à 21 h PST.",
    BESTSELLER: 'Plus vendu',
    SEE_ALL: 'Tout voir',
    TIMINGS: 'HORAIRES',
    FREQUENCY: 'FRÉQUENCE',
    DURATION: 'DURÉE',
    STARTING_LOCATION: 'Lieu de départ',
    CALENDAR_FOOTNOTE: '* Tous les prix sont en {0}',
    GOT_IT: "J'ai compris",
    TOUR_TIMINGS: 'Horaires',
    TOUR_FREQUENCY: 'Fréquence',
    SELECT_DATE: 'Select a date',
    SELECT_TOUR: 'Select Tour Type',
    VIEW_TOUR_DETAILS: 'View tour details',
    BUS_DETAILS: 'MORE DETAILS',
    VIEW_ROUTES: 'View all routes',
    BUS_ROUTES: 'BUS ROUTES',
    ATTRACTIONS_PREVIEW: 'Fastest way to view {0}+ top attractions including',
    ROUTES: 'Routes',
    COMBO_SUBTITLE: 'Économisez davantage avec',
    COMBO_TITLE: 'Offres combinées sur votre circuit Hop-on Hop-off',
    COMBO_DWEB_TITLE:
      'Économisez davantage grâce aux offres combinées sur votre circuit Hop-on Hop-off',
    STOPS_AND_ATTRACTIONS: 'Arrêts et attractions à proximité',
    HOP_ON_OFF_AT: "Montez et descendez à l'un de ces {0} arrêts.",
    TIMINGS_FREQUENCY: 'Horaires et fréquence',
    TOUR_DURATION: 'Durée du tour',
    EVERY_X_MINS: 'Every {0}',
    VIEW_LOCATION: 'Voir le lieu',
    BANNER_SUBTEXT:
      'Le moyen le plus pratique et le plus rapide de visiter les principales attractions de la ville.',
    TOP_ATTRACTIONS: 'Principales attractions',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Réservation en dernière minute',
        DESCRIPTION: 'Confirmation directe sur votre portable',
      },
      COST_EFF: {
        NAME: 'Exploration à moindre coût',
        DESCRIPTION: 'Plusieurs monuments avec un seul billet',
      },
      DAILY_RIDES: {
        NAME: 'Trajets illimités tous les jours',
        DESCRIPTION: 'Explorez la ville à votre rythme',
      },
      BOOK_RELAX: {
        NAME: 'Réservez et profitez',
        DESCRIPTION: '22 millions de personnes satisfaites',
      },
    },
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Navettes privées',
    SHARED_TRANSFERS: 'Navettes partagées',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Réservation en ligne',
        DESCRIPTION:
          "Réservez vos billets en ligne et profitez d'une expérience rapide et pratique.",
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Confirmation immédiate',
        DESCRIPTION:
          "Recevez une confirmation directement après la réservation de votre navette d'aéroport.",
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Prise en charge pratique',
        DESCRIPTION:
          "Évitez les longues files d'attente grâce à votre navette qui vous attendra au point de prise en charge que vous aurez choisi.",
      },
      DROP_OFF: {
        TITLE: "Lieu d'arrivée",
        DESCRIPTION:
          'Rejoignez votre destination rapidement et confortablement.',
      },
    },

    SHARED_TRANSFERS_IN: 'Navettes partagées à {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      'Un moyen de transport confortable et économique pour plusieurs passagers voyageant vers ou depuis un aéroport.',
    PRIVATE_TRANSFERS_IN: 'Navettes privées à {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      'Un moyen de transport pratique et personnalisé pour les personnes seules ou les petits groupes, offrant un trajet confortable et direct depuis et vers un aéroport.',
    ANYWHERE_IN_THE_CITY: "N'importe où dans la ville",
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Multiples options de véhicules',
      FREE_CANCELLATION: 'Annulation gratuite',
    },
    SEAMLESS_TRANSFERS: 'Navettes rapides et fiables à travers le monde',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      "Choisissez la navette d'aéroport qui vous convient le mieux",
    HASSLE_FREE_TRANSFER: 'Navette aéroport en toute tranquillité',

    // New experiment (AT LP)
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Navettes aéroportuaires à {0} en',
    BUSES: 'bus',
    TRAINS: 'bus',
    PRIVATE_TAXIS: 'taxi privé',
    BUS_TRAIN: 'Bus / train',
    PRIVATE_TAXI: 'Taxi privé',

    FROM: 'Depuis',
    TO: 'Vers',
    SELECT_PICKUP: 'Sélectionnez le ramassage',
    SELECT_DROPOFF: 'Sélectionner le dépôt',
    ENTER_DESTINATION: 'Saisissez votre destination',
    ENTER_PICKUP: "Saisir le lieu d'enlèvement",
    PICKUP_DATE: 'Date de départ',
    SELECT_DATE: 'Choix de date',
    PICKUP_TIME: 'Heure de départ',
    SELECT_TIME: "Choix d'heure",
    GUESTS: 'Invités',
    GUEST: 'Invité',
    ADD_GUESTS: 'Ajouter invités',
    ADULT_CHILD: 'Adulte(s)/Enfant(s)',
    EXPLORE_TRANSFERS: 'Parcourir les navettes',
    COMBOS_AND_EXTRAS: 'Combos et options',

    YOUR_RIDE_DOORSTEP: 'Votre trajet depuis chez vous',
    COMFORTABLE_RIDE:
      'Réservez un taxi privé confortable de/vers les principaux aéroports de {0}.',
    TRUSTED_DRIVERS: 'Chauffeur·e·s de confiance',
    RIDES_24_7: 'Trajets disponibles 24/7',
    FLIGHT_TRACKING: 'Suivi des vols',
    KNOW_MORE: 'En savoir plus',
    RESERVE_YOUR_RIDE: 'Réserver votre trajet',
    TRANSFER_OPTIONS: 'Options de navettes trouvées',
    TRANSFERS_AVAILABLE_PLURAL: '{0} navettes disponibles',
    TRANSFERS_AVAILABLE_SINGULAR: '1 navette disponible',

    TRUSTED_PARTNERS: '+ de 35 partenaires {0}',
    WORLDWIDE: 'à travers le monde',
    COMFORTABLE_RIDES: 'Trajets confortables',
    FREQUENT_DEPARTURES: 'Départs fréquents',
    MULTIPLE_TRANSPORT_OPTIONS: 'Plusieurs options de transport',
    AND_MANY_MORE: 'Et plus encore',

    ADD_PICKUP_LOCATION: 'Ajouter un lieu de prise en charge',
    ADD_DROPOFF_LOCATION: 'Ajouter un lieu de dépose',
    SELECT_PICKUP_DATE_AND_TIME: "Choisir la date et l'heure de départ",
    SELECT_A_DATE: 'Sélectionner la date',

    TRAIN_STATION: 'Gare ferroviaire',
    BUS_STOP: 'Arrêt de bus',

    ADD_RETURN: 'Ajouter un retour',
    HEADS_UP: 'Attention !',
    ADDED_RETURN_TRIP: 'Vous avez ajouté un trajet retour.',
    RETURN_NOTE:
      'Nous afficherons les détails du trajet de retour dans les prochaines étapes.',
    OKAY_I_UNDERSTAND: "Oui, c'est compris",

    SERVING_GUESTS: '{0} servies dans {0} à travers le monde.',
    GUESTS_COUNT: 'Plus de 220 000 personnes',
    CITIES_COUNT: '55 villes',
    PARNTER_WITH_BEST:
      'Nous collaborons avec les meilleurs pour vous faire vivre une expérience inoubliable. Nous nous occupons des détails pendant que vous vous détendez et profitez du voyage.',
  },
  PC_EXP: {
    SHOW_INCL: 'Inclusions et infos importantes',
    CLEAR: 'Annuler',
    ALL_EXPERIENCES: 'Toutes les expériences',
    FILTER_BY_CATEGORIES: 'Filtrer par catégories',
    CATEGORIES: 'Catégories',
    COMBOS: {
      HEADING:
        'Toutes les bonnes choses vont de pair. Tout comme nos offres combinées.',
      DESCRIPTOR_1: 'Offres avantageuses',
      DESCRIPTOR_2: 'Meilleure préparation de votre voyage',
    },
  },
  TOP: 'Le meilleur des : {0}',
  VIEW_CALENDAR: 'Voir le calendrier',
  SHOWS_CALENDAR: 'Calendrier des spectacles du West End',
  IN: 'en',
  SEATS: 'Sièges',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Guide pratique',
    QUICK_INFORMATION: 'En bref',
    PEAK: 'heures de pointe',
    OFF_PEAK: 'heures creuses',
    ADDRESS: 'ADRESSE',
    RECOMMENDED_DURATION: 'DURÉE RECOMMANDÉE',
    VISITORS_PER_YEAR: 'VISITEURS PAR AN',
    NUMBER_OF_ENTRANCES: "NOMBRE D'ENTRÉES",
    EXPECTED_WAIT_TIME_STANDARD: "TEMPS D'ATTENTE ESTIMÉ - NORMAL",
    EXPECTED_WAIT_TIME_SKIP_THE_LINE:
      "TEMPS D'ATTENTE ESTIMÉ - ACCÈS COUPE-FILE",
    UNESCO_YEAR: "INSCRIPTION À L'UNESCO",
    ARCHITECTURE_STYLE: "STYLE D'ARCHITECTURE",
    TIMINGS: 'Horaires',
    SIZE_HEIGHT: 'TAILLE/HAUTEUR',
    TICKETS: 'DES BILLETS',
    FUN_FACTS: 'Anecdotes',
    DID_YOU_KNOW: 'Le saviez-vous ?',
    MORE_INTERESTING_FACTS: "Plus d'anecdotes",
    PLAN_YOUR_VISIT: 'Planifier votre visite',
    ALSO_KNOWN_AS: 'Aussi connu comme',
    FOUNDED_ON: 'Fondé en',
    FOUNDED_BY: 'Fondé par',
    FROM: 'À partir de',
    CLOSED_TODAY: "Fermé aujourd'hui",
    TODAY: "Aujourd'hui",
    CLOSED: 'Fermé',
    OPEN: 'Ouvrir',
    LAST_ADMISSION: 'Dernière Admission',
    DAYS: 'Jours',
    BEST_TIME_TO_VISIT: 'Meilleure période pour visiter',
    WEEKDAY_VS_WEEKEND: 'Jour de semaine vs Week-end',
    PEAK_VS_LOW_SEASON: 'Haute saison vs Basse saison',
    PLEASANT: 'Agréable',
    CROWDED: 'Fréquenté',
    VERY_CROWDED: 'Très fréquenté',
    LOW_SEASON: 'Basse saison',
    MID_SEASON: 'Saison intermédiaire',
    PEAK_SEASON: 'Haute saison',
    TO: 'AU',
    TO_LOWER: 'au',
    LAST_ENTRY: 'dernière entrée',
    SUBATTRACTIONS: 'Sous-Attraits',
    INCLUDED_WITH_TICKETS: 'Inclus avec les billets pour {0}',
    INCLUDED_WITH_SOME_TICKETS: 'Inclus avec certains billets pour {0}',
    EXPLORE_ALL_POI_TICKETS: 'Parcourez les billets et visites pour {0}',
    OPERATING_HOURS: 'Horaires',
    SEE_MORE: 'Voir plus',
    MORE_INSIGHTS: 'En savoir plus',
    SELECT_YOUR_EXPERIENCE: 'Sélectionnez votre expérience',
  },
  OFF_PERCENT: '{0} % de réduction',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Plan de la salle',
    CAPACITY: 'Capacity: {0} places',
    WHATS_ON: `À l'affiche`,
    CATEGORIES: 'Catégories',
  },
  NEXT: 'Prochaine étape',
  PREVIOUS: 'Précédent',
  ITINERARY: {
    TAB: 'Itinéraire',
    HEADING: "Itinéraire de l'expérience",
    VIEW_ITINERARY: "Voir l'itinéraire",
    PASSES_BY_SECTION_HEADING: 'À voir en cours de route',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Points forts',
      NEARBY_THINGS_TO_DO: 'Choses à faire à proximité',
      THINGS_TO_DO: 'Choses à faire',
    },
    STOP_CARD: {
      TITLE: {
        START: 'Point de départ',
        END: "Point d'arrivée",
        STARTING_POINT: 'POINT DE DÉPART',
        STOP: 'ARRÊT',
        ENDING_POINT: "POINT D'ARRIVÉE",
        PASSING_BY: 'PASSE PAR',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} points de départ disponibles',
        END: "{0} points d'arrivée disponibles",
      },
    },
    GET_DIRECTION: "Comment s'y rendre",
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} h {1} min',
        WITHOUT_HOURS: '{0} min',
        WITHOUT_MINS: '{0} h',
      },
      ATTRACTIONS_COUNT: '{0} attractions',
      ACTIVITIES_COUNT: '{0} activités',
      TOTAL_DURATION: 'Durée totale',
      FREQUENCY: 'Fréquence',
      FIRST_DEPARTURE: 'Premier départ',
      LAST_DEPARTURE: 'Dernier départ',
      FIRST_DEPARTURE_TIME: 'Première heure de départ',
      LAST_DEPARTURE_TIME: 'Dernière heure de départ',
      MODE_OF_TRANSPORT: 'Mode de transport',
      FOOD_AND_DRINKS: 'Nouriture et boissons',
    },
    WALK_DURATION: '{0} à pied',
    MORE: '{0} de plus',
    TIMELINE_VIEW: 'Itinéraire',
    MAP_VIEW: 'Carte',
    MAP_OVERLAY: "Déplacez la carte à l'aide de CTRL/⌘ + votre souris",
    VIEW_EXPERIENCE_MAPPED_OUT: 'Regardez votre expérience sur la carte.',
    OPEN_MAP_VIEW: 'Ouvrir la carte',
    START_POINT_SAME_AS_END_POINT:
      "Votre point d'arrivée sera le même que votre point de départ.",
  },
  CRUISES: {
    BANNER_HEADING: 'Croisière à travers {0} : découverte, détente et dîner',
    FILTERS: {
      ALL: 'Tout',
      SIGHTSEEING: 'Visites',
      LUNCH: 'Déjeuner',
      DINNER: 'Dîner',
      COMBOS: 'Combos',
    },
    MAP_OVERLAY: 'Appuyez ou cliquez pour déplacer la carte',
    SIGHTS_COVERED: 'Sites inclus',
    MENU: 'Menu',
    BOARD_AT: 'Embarquement à {0}',
    BOARDING_POINTS_AVAILABLE: '{0} disponibles',
    VIEW_POPULAR_SIGHTS: 'Vue de sites populaires tels que {0} {1}',
    X_BOARDING_POINTS: "{0} points d'embarquement",
    BOARDING_POINT: "Point d'embarquement",
    BOARDING_POINTS: "Points d'embarquement",
    LANDMARKS: 'Monuments',
    GET_DIRECTIONS: "Comment s'y rendre",
    FOOD_MENU: 'Menu',
    X_PAGE: '{0} page',
    X_PAGES: '{0} pages',
    MORE: '+{0} plus',
    PDF: {
      ZOOM_IN: 'Zoomer',
      ZOOM_OUT: 'Dézoomer',
      FIT_TO_WIDTH: 'Rétablir',
      RESET_ZOOM: 'Réinitialiser',
    },
    COMBO_HEADING:
      "Plus d'expériences à moindre coût : offres combo et Pass touristiques",
  },
};
export default fr;
