const fr = {
  AUDIO_GUIDE: {
    BANNER: 'Audioguide gratuit',
    PRODUCT_SUFFIX: 'avec audioguide',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Partenaire autorisé et de confiance',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Revendeur agréé',
    SUB_TEXT: 'Expériences authentiques de partenaires fiables et vérifiés.',
  },
  AVAILABLE: 'Disponible',
  BANNER_CTA: 'Voir nos offres',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout est une marque à laquelle des millions de visiteurs dans le monde font confiance et qui propose des expériences de qualité pour profiter du lieu.',
    NON_PARTNERED_SENSITIVE:
      "Headout est une marque à laquelle des millions de personnes dans le monde font confiance et qui propose des expériences de qualité pour profiter du lieu. Ceci n'est pas le site web du lieu.",
    PARTNERED_NON_SENSITIVE:
      'Headout est un partenaire autorisé et de confiance du site, qui propose des expériences de qualité pour profiter du lieu.',
    PARTNERED_SENSITIVE:
      "Headout est un partenaire autorisé et de confiance du site, qui propose des expériences de qualité pour profiter du lieu. Ceci n'est pas le site web du lieu.",
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout est un partenaire agréé et de confiance qui propose une sélection des meilleures expériences pour profiter de cette attraction.',
  BOOK_NOW_CTA: 'Réserver',
  BUY_TICKETS_CTA: 'Voir nos offres',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Vous pouvez annuler ces billets jusqu’à {0} heures avant le début de l’expérience et bénéficiez d’un remboursement complet.',
    CANCELLABLE_ANYTIME:
      'Annulation gratuite à tout moment avant le début de votre activité',
    CANCELLABLE_DAYS:
      'Vous pouvez annuler ces billets jusqu’à {0} jours avant le début de l’expérience et obtenir un remboursement complet.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Ces billets ne peuvent pas être annulés. Cependant, ils sont valables pour une période prolongée.',
    HEADING: 'Politique de modification',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Ces billets ne peuvent pas être annulés. Cependant, ils peuvent être reportés jusqu’à {0} heures avant le début de l’expérience.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Ces billets ne peuvent être ni annulés ni reportés.',
    VALID_UNTIL_DATE:
      'Ces billets ne peuvent pas être annulés. Cependant, vous pouvez les utiliser à tout moment jusqu’au {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Ces billets ne peuvent pas être annulés. Toutefois, vous pouvez les utiliser à tout moment pendant les {0} prochains jours.',
    VALID_WITHIN_NEXT_MONTHS:
      'Ces billets ne peuvent pas être annulés. Cependant, vous pouvez les utiliser à tout moment durant les {0} prochains mois.',
  },
  CANCELLATION_POLICY_HEADING: "Politique d'annulation",
  CASHBACK: 'Cashback de {0} %',
  CASHBACK_INFO:
    'Vous recevrez <strong>{0} %</strong> de crédits Headout en réservant cette activité. Votre réduction sera automatiquement créditée sur votre compte Headout et pourra être utilisée pour toute réservation future avec Headout.',
  CATEGORY_SLIDER_HEADING:
    'Les client·es qui ont réservé ce spectacle ont également vu',
  CHECK_AVAIL: 'Vérifier la disponibilité',
  CITY_PAGE: {
    BANNER_TITLE: 'Meilleures offres pour les expériences à',
    TOP_ATTRACTIONS: 'Meilleures attractions',
    GO_BEYOND: 'Aller au-delà de {0}',
    ALL_DAY_TRIPS: 'Voir toutes les escapades',
    CITIES_NEARBY: 'Villes à proximité',
    POPULAR_CATEGORIES: 'Catégories populaires',
    GO_TO_GUIDE: 'Guide pratique de {0}',
    VIEW_TRAVEL_GUIDE: 'Voir le guide de voyage',
    EXPLORE: 'Explorer {0}',
    GUIDE_SUBHEADING:
      "Explorer les sites de {0} n'a jamais été aussi facile ! Notre guide de voyage de {0} couvre tout ce que vous devez savoir sur la ville, des bonnes adresses où manger aux endroits à voir, en passant par les meilleurs itinéraires pour s'y rendre, les bons plans pour dormir et bien d'autres choses !",
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Bon à savoir',
      WHERE_TO_EAT: 'Restauration',
      WHERE_TO_STAY: 'Hébergement',
      THINGS_TO_DO: 'Choses à faire',
      WEATHER: 'Meilleure période pour visiter',
      NEIGHBOURHOODS: 'Quartiers',
      TRANSPORTATION: 'Transport',
      TRIP_PLANNER: 'Plan de voyage',
      FAMILY_TRAVEL: 'Voyager avec des enfants',
      TRAVEL_TIPS: 'Trucs et astuces de voyage',
      SHOPPING: 'Boutiques',
      ART_AND_CULTURE: 'Arts et culture',
    },
    MAILER: {
      HEADING:
        'Des idées pour visiter {0} directement dans votre boîte de réception.',
      SUBHEADING:
        'Les meilleures choses à faire, les bons plans, les transports en commun, les meilleurs restaurants et hôtels, les conseils culturels et plus encore.!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      "Renseignez-vous sur les conditions d'obtention d'un visa, les monnaies d'échange, les différences de fuseaux horaires et bien d'autres choses encore afin de faciliter votre arrivée et de rendre votre séjour agréable..",
    WHERE_TO_EAT:
      'Savourez une cuisine variée, des arômes de toutes sortes et des spécialités locales aux quatre coins de {0}.',
    WHERE_TO_STAY:
      'Découvrez les meilleurs hébergements de {0}, alliant confort, commodité et souvenirs inoubliables.',
    THINGS_TO_DO:
      'Profitez des nombreuses activités et attractions passionnantes qui répondront à vos attentes et vous feront passer un moment exceptionnel.',
    WEATHER:
      "Planifiez votre voyage judicieusement et profitez au maximum de votre visite, car {0} vous fait vivre des expériences magiques tout au long de l'année.",
    NEIGHBOURHOODS:
      'Apprenez à connaître les diverses communautés locales et les quartiers dynamiques qui confèrent à {0} son caractère unique.',
    TRANSPORTATION:
      'Parcourez {0} en douceur grâce à son système de transport efficace, qui vous offre des options pratiques pour découvrir toutes ses attractions.',
    TRIP_PLANNER:
      'Maximisez votre temps à {0} grâce à des itinéraires soigneusement élaborés, qui vous permettront de profiter au maximum de chaque instant.',
    FAMILY_TRAVEL:
      "Partez à l'aventure en famille grâce aux nombreuses attractions, parcs et activités de divertissement qui s'adressent aux enfants de tous âges.",
    TRAVEL_TIPS:
      "Faites le plein de conseils et d'astuces pour rendre votre visite à {0} vraiment exceptionnelle..",
    SHOPPING:
      "Explorez des boutiques, des marchés et des centres commerciaux où vous trouverez tout, de l'artisanat local à la mode de luxe, et qui sont un véritable paradis pour les amateurs de shopping.",
    ART_AND_CULTURE:
      'Découvrez une scène artistique et culturelle exceptionnelle, des musées fascinants aux festivals animés célébrant le patrimoine de {0}.',
  },
  CLOSE: 'Fermer',
  COLLECTION_SLICE_HEADING: 'Meilleures choses à faire à {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Sélectionner',
    SELECT_OPTION: 'Sélectionnez votre option',
    SELECT_TICKET: 'Sélectionnez votre billet',
  },
  COMPARE_ALL_DETAILS: 'Comparer tous les détails',
  COVID19_ALERT: {
    KEY_TEXT: 'Mise à jour concernant la COVID-19',
    LINK: 'https://medium.com/headout/%C3%A9pid%C3%A9mie-de-coronavirus-politique-dannulation-595a47a8bb50',
    TEXT: `Vous êtes notre priorité. Veuillez consulter notre page d'assistance pour connaître les dernières mises à jour de nos politiques d'annulation flexibles.`,
  },
  CURRENCY: 'Devise',
  CUSTOMER_REVIEW_HEADING: 'Avis des client·es',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioguide',
    DURATION: 'Durée : {0}',
    EXTENDED_VALIDITY: 'Validité prolongée',
    FLEXIBLE_DURATION: 'Durée flexible',
    FREE_CANCELLATION: 'Annulation gratuite',
    GUIDED_TOUR: 'Visite guidée',
    HOTEL_PICKUP: `Départ depuis l'hôtel`,
    INSTANT_CONFIRMATION: 'Confirmation immédiate',
    MEALS_INCLUDED: 'Repas inclus',
    MOBILE_TICKET: 'Billets mobiles',
    SKIP_THE_LINE: 'Coupe-file',
    TRANSFERS: 'Navettes incluses',
  },
  DURATION: 'Durée',
  EARLIEST_AVAILABILITY: 'Prochaine disponibilité : ',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Saisissez votre adresse e-mail ici',
    SIGN_UP: "S'inscrire",
    THANK_YOU: 'Merci !',
    SUBSCRIBED_MSG: 'Vous êtes maintenant inscrit·e',
    ERROR_MSG: 'Veuillez saisir une adresse e-mail valide',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Billets de théâtre pour Broadway',
    },
    LTT: {
      MB_NAME: 'Billets de théâtre pour Londres',
    },
  },
  EXCLUSIONS: 'Non inclus',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '+ de 10 millions',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100 % sûr',
    HEADING_SUPPORT: "Centre d'aide 24/7",
    SUB_HEADING_CUSTOMER:
      'de client·es satisfait·es à travers + de 10 000 expériences',
    SUB_HEADING_RATING:
      '+ de 5 000 avis vérifiés avec 90 % de notes excellentes',
    SUB_HEADING_SAFE: 'Toutes les activités de plein air sont sûres à 100 %',
    SUB_HEADING_SUPPORT:
      'Une question ? Discutez en ligne avec des experts locaux, partout et à tout moment',
  },
  FLEXIBLE: 'Flexible',
  FOOTER: {
    CALL_US: 'Appelez-nous',
    CHAT_WITH_US: 'Chattez avec nous',
    COMPANY_DETAILS: 'Notre entreprise',
    DISCLAIMER: `Ce site n'est pas le site officiel <attraction>. Il est géré par Headout et travaille en collaboration avec des attractions et des tour-opérateurs pour vous offrir des expériences incroyables en un clic !`,
    EMAIL_US: 'Contactez-nous',
    GET_HELP: 'Aide',
    LEGAL: 'Légal',
    PRIVACY_POLICY: 'Politique de confidentialité',
    QUICK_LINKS: 'Raccourcis',
    TERMS_AND_CONDITIONS: 'Conditions générales',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Fait avec ',
    ALL_OVER_THE: ' à travers le ',
  },
  FREE_CANCELLATION: 'Annulation gratuite',
  FREE_CANCELLATION_SUBTEXT: `Nous savons que les plans changent. Annulez jusqu'à 72 h à l'avance.`,
  FROM: 'à partir de',
  GET_CASHBACK: 'Recevez un cashback de {0} %',
  GROUP_TICKETS: 'Billets de groupe',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '+ de 18 millions de client·e·s',
    SUB_TEXT:
      'La satisfaction de nos client·e·s est notre priorité. Rejoignez le club !',
  },
  HELP_CENTER: {
    MAIN_TEXT: "Centre d'assistance 24h/7j",
    SUB_TEXT:
      'Une question ? Nous sommes disponibles par téléphone, chat et e-mail.',
  },
  INCLUSIONS: 'Inclus',
  LANGUAGE: 'Langue',
  LISTICLES: {
    KNOW_MORE: 'En savoir plus',
    SEATING_CHART: 'Plan de la salle',
    WHY_BOOK_FROM_US: 'Pourquoi choisir Headout ?',
  },
  MORE_DETAILS: `En savoir plus`,
  MORE_CURRENCIES: 'Autres devises',
  NEW: 'NEW',
  NEW_ARRIVAL: 'Nouveautés',
  NEXT_AVAILABLE: 'Prochaine disponibilité: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    "Headout est une marque de confiance qui a servi plus de 15 millions de personnes et qui propose une sélection des meilleures expériences. Ceci n'est pas le site web du lieu.",
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR:
    'Réservez avec flexibilité - Pas besoin de choisir une date',
  OPENING_DATE: 'Première date',
  OPENING_ON: 'Ouverture le',
  OPENS: 'Ouvre',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    "Headout est un partenaire agréé et de confiance qui propose une sélection des meilleures expériences pour profiter de cette attraction. Ceci n'est pas le site Web de l'attraction.",
  POPULARITY: 'Popularité',
  POPULAR_CURRENCIES: 'Devises principales',
  PRICE: 'Prix',
  PRICES_STARTING: 'À partir de',
  PROMO_CODES: {
    APPLIED: 'APPLIQUÉ',
    APPLY_CODE: 'APPLIQUER LE CODE',
    DESCRIPTION: {
      ABSOLUTE: 'Réduction de {0}',
      CAPPED: "Réduction de {0} %, jusqu'à {1}",
      PERCENTAGE: 'Réduction de {0} %',
    },
    REMOVE: 'SUPPRIMER',
    TOOL_TIP_INFO: 'Cette réduction sera appliquée lors du paiement',
  },
  RATINGS: '{0} Notes',
  READ_MORE: 'En savoir plus',
  READ_MORE_TEXT: 'En savoir plus',
  READ_LESS: 'Voir moins',
  VIEW_DETAILS: 'Voir les détails',
  REOPENING: 'Réouverture',
  REOPENING_DATE: 'Date de réouverture',
  REOPENING_ON: 'Réouverture le',
  REOPENS: 'Réouvre',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT: "La règle 2G s'applique : l'accès aux établissements d'hébergement, aux institutions culturelles et aux restaurants/bars, entre autres, n'est possible que sur présentation d'une preuve de vaccination complète ou d'une infection passée. Un test Covid-19 négatif n'est plus suffisant.",
    },
    AU_DESCRIPTION: {
      TEXT: "Les visiteurs et visiteuses âgé·es de 16 ans et plus doivent présenter une preuve de vaccination contre la COVID-19 ou un certificat d'exemption médicale.",
    },
    BANNER_CTA: 'En savoir plus',
    BERLIN_DESCRIPTION: {
      TEXT: "La règle 2G s'applique : seules les personnes complètement vaccinées et guéries, sur présentation d'un jpass sanitaire, auront accès à l'établissement. Les personnes de moins de 18 ans ou celles et ceux qui ne peuvent pas être vacciné·es pour des raisons médicales doivent présenter à l'entrée un résultat négatif à la test COVID-19. Les personnes qui ne peuvent pas être vaccinées pour des raisons médicales doivent également prouver leur incapacité à se faire vacciner au moyen d'un certificat médical à l'entrée.",
    },
    CTA_TEXT: 'Détails des mesures de sécurité et sanitaires',
    DESCRIPTION_CTA: 'En savoir plus.',
    EU_DESCRIPTION: {
      TEXT: "À partir du 21 juillet 2021, tous les visiteurs et visiteuses âgé·es de 12 ans et plus devront présenter un certificat COVID de l'UE.",
    },
    EU_HEADING: 'Certificat COVID numérique UE requis',
    EU_PREFIX: 'Attention : ',
    EXPERIENCE_DESCRIPTION:
      "Cette expérience a été vérifiée et respecte les normes de sécurité et sanitaires, conformément aux réglementations locales et aux directives de l'OMS.",
    FLAG_TEXT: 'Protection renforcée',
    GENERAL_DESCRIPTION:
      'Toute expérience affichant ce badge a été vérifiée et est conforme aux normes de sécurité établies par les autorités locales en matière de santé.',
    HEADING: 'Normes de sécurité et sanitaires en vigueur',
    IT_DESCRIPTION: {
      TEXT: "À partir du 6 août 2021, tous les visiteurs et visiteuses âgé·es de 11 ans et plus devront présenter un pass sanitaire ou un certificat COVID de l'UE.",
    },
    IT_PREFIX: 'Important : ',
    MOBILE_HEADING: 'Expériences conformes aux normes sanitaires',
    MODAL: {
      BADGE_DESCRIPTION:
        'Ce badge atteste que les normes de sécurité et sanitaires ont été vérifiées par pour cette expérience.',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Tous les équipements, les véhicules et les espaces à forte fréquentation sont nettoyés après chaque utilisation. Détendez-vous et profitez de votre séjour et visite.',
          HEADING: 'Tous les équipements et espaces sont désinfectés',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Tous les équipements mis à votre disposition au cours de votre visite sont soigneusement nettoyés après chaque utilisation.',
          HEADING: 'Tous les équipements et espaces sont désinfectés',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Tous les véhicules mis à votre disposition pendant votre séjour sont soigneusement nettoyés après chaque utilisation.',
          HEADING: 'Tous les véhicules sont désinfectés',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            "Pour toute expérience conforme aux normes sanitaires, vous aurez accès à des installations sanitaires et à des points d'eau pour vous laver les mains tout au long de votre visite. Nous avons tout prévu.",
          HEADING:
            'Des installations sanitaires et pour se laver les mains sont disponibles partout',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Le port du masque est obligatoire pour tous les visiteurs et membres du personnel de cette expérience. Cette mesure assure ainsi à chacun de passer un bon moment en toute sécurité.',
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            "Nos partenaires qui ont été vérifiés en tant qu'expérience conforme aux normes sanitaires appliquent les réglementations locales en vigueur concernant le port du masque. Si le port du masque est obligatoire, tous les visiteurs et membres du personnel en porteront un. Nos partenaires prennent toutes les mesures possibles pour assurer votre confort et votre sécurité.",
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Le port du masque est obligatoire pour tous les visiteurs de cette expérience. Cette mesure assure ainsi à chacun de passer un bon moment en toute sécurité.',
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Tous les membres du personnel qui travaillent sur ce site portent un masque de protection pour que vous puissiez vous amuser sans aucun souci.',
          HEADING: 'Pour votre sécurité, tout le monde porte un masque',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Les expériences conformes aux normes sanitaires respectent en tout temps les lignes directrices en matière de distance sociale. Afin de faire respecter ces directives, il se peut que la capacité du lieu soit restreinte et que des limites de groupe soient mises en place.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Les expériences conformes aux normes sanitaires respectent en tout temps les lignes directrices en matière de distance sociale. Afin de faire respecter ces directives, il se peut que la capacité du lieu soit restreinte et que des limites de groupe soient mises en place. Par ailleurs, les grands groupes ne sont pas autorisés.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Tout au long de votre visite, les lignes directrices en matière de distance sociale sont respectées.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            "Les expériences classées sans risque respectent en tout temps les lignes directrices en matière de distance sociale. Afin de faire respecter ces directives, il se peut que la capacité du lieu soit restreinte et que des limites de groupe soient mises en place. Nous faisons en sorte que vous vous sentiez à l'aise.",
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Tout au long de votre visite, les lignes directrices en matière de distance sociale sont respectées. Par ailleurs, les grands groupes ne sont pas autorisés.',
          HEADING: 'La distance sociale est respectée',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            "La température de tous les visiteurs sera prise au début de l'expérience afin de garantir la sécurité de tous. Tous les membres du personnel sont examinés à plusieurs reprises pour vérifier si leur température est élevée.",
          HEADING: 'Contrôles de température en vigueur',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            "La température de tous les visiteurs sera prise au début de l'expérience afin de garantir la sécurité de tous.",
          HEADING: 'Contrôles de température en vigueur',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Tous les membres du personnel sont examinés à plusieurs reprises pour vérifier si leur température est élevée. Les employés dont la température est supérieure à la limite prescrite ne peuvent entrer sur le site et sont priés de rester chez eux pour un prompt rétablissement.',
          HEADING: 'Contrôles de température en vigueur',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            "Le personnel présent tout au long de votre visite est formé aux directives de l'OMS et équipé pour faire face à toute situation d'urgence éventuelle.",
          HEADING: "Le personnel est formé aux directives de l'OMS",
        },
      },
      HEADING: 'Expériences conformes aux normes sanitaires',
      SUB_HEADING:
        "Headout collabore avec ses partenaires dans le monde entier pour appliquer les normes de sécurité et sanitaires conformément aux directives de l'OMS. Toutes les mesures prises sur le terrain ont été vérifiées et sont indiquées ici. Il est grand temps de profiter à nouveau du monde qui nous entoure.",
    },
    NL_DESCRIPTION: {
      TEXT: "Les visiteurs et visiteuses âgé·es de 13 ans et plus doivent être en possession d'un certificat COVID (copie numérique ou imprimée) attestant de leur vaccination, d'un résultat négatif au test ou de leur rétablissement récent de la COVID-19. Le port d'un masque est obligatoire.",
    },
    SG_DESCRIPTION: {
      TEXT: "À partir du 13 octobre 2021, seul·es les visiteurs et visiteuses entièrement vacciné·es pourront entrer par groupes de 2. Vous devrez présenter une preuve de votre statut vaccinal, un résultat négatif récent du test COVID-19 et/ou tout document de rétablissement avant l'entrée.",
    },
    SHORT_HEADING: 'Toutes les normes de sécurité et sanitaires en vigueur',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Votre sécurité est notre priorité.',
    TEXT: "Nous avons pris des mesures importantes pour améliorer la propreté des lieux au moyen de désinfectants et de nettoyages approfondis et fréquents des surfaces. Nous contrôlons également la fréquentation afin d'éviter tout encombrement.",
  },
  SAVE: 'Économisez {0} %',
  SAVE_PERCENT: 'Économisez {0} %',
  SAVE_UPTO: "Économisez jusqu'à",
  SAVE_UPTO_PERCENT: "Économisez jusqu'à {0} %",
  SEARCH: 'Rechercher',
  SEE_ALL: 'See All',
  SEE_MORE_SHOWS: 'Voir plus de spectacles',
  SELECT_CITY: 'Sélectionner une ville',
  SELECT_SECTION: 'Sélectionner une tribube',
  SEE_ALL_PHOTOS: 'Voir toutes les photos',
  SHOW_CLOSED: 'Spectacle terminé',
  SHOW_LESS_TEXT: 'Voir moins',
  SHOW_PAGE: {
    ABOUT_SHOW: 'À propos du spectacle',
    ABOUT_THEATRE: 'À propos du théâtre',
    ADDITIONAL_INFORMATION: 'Informations supplémentaires',
    AGE_LIMIT: "Limite d'âge",
    AGE_SUITABILITY: "Limite d'âge",
    ANSWER: ['R-', 'A-'],
    BLOG_SHOW_PAGE: 'Page du spectacle du blog',
    BLOG_SUMMARY: 'Résumé du blog',
    BLOG_THEATRE_PAGE: 'Page du théâtre du blog',
    BLOG_THEATRE_SEATING_PLAN: 'Plan du théâtre du blog',
    CANCELLATION_AND_REFUNDS: 'Annulation et remboursements',
    CANCELLATION_POLICY: "Politique d'annulation",
    CAST_AND_CREW: "Les acteurs et l'équipe",
    CLOSING_DATE: 'Date de clôture',
    CLOSING_DATE_SPECIAL_OFFER: 'Offre spéciale pour la date de clôture',
    DURATION: 'Durée',
    FACILITIES_AND_ACCESSIBILITY: 'Installations et accessibilité',
    FREQUENTLY_ASKED_QUESTIONS: 'Foire aux questions',
    GETTING_THERE: "Comment s'y rendre",
    GETTING_THERE_MAP_LINK: "Comment s'y rendre",
    GOOGLE_MAP: 'Google Map',
    HIGHLIGHTS: 'Points forts',
    LISTICLE_SHOW_SUMMARY: 'Listicle Résumé du spectacle',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Pourquoi faut-il voir le spectacle',
    OPENING_DATE: "Date d'ouverture",
    QUESTION: ['Q-'],
    SAFETY_BANNER: 'Bannière de sécurité',
    SHOW_DETAILS: 'Informations sur le spectacle',
    SHOW_TIMINGS: 'Horaires des représentations',
    SHOW_TYPE: 'Type de spectacle',
    SPECIAL_OFFER: 'Offre spéciale',
    THE_STORY: "L'histoire",
    THEATRE_ADDRESS: 'Adresse du théâtre',
    THEATRE_CAPACITY: 'Capacité du théâtre',
    THEATRE_NAME: 'Nom du théâtre',
    TICKETS: 'Billets',
    TICKETS_REDEMPTION: 'Échange des billets',
    TOP_SONGS: 'Meilleures chansons',
    YOUR_TICKETS: 'Vos billets',
    ABOUT_CONCERT: 'Le concert',
    PROGRAM: 'Programme',
  },
  SORT_BY: 'Trier par',
  THEATRE: 'Théâtre',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Théâtres dans le coin',
    NOW_PLAYING: `À l'affiche`,
    PAST_SHOWS: 'Anciens spectacles',
    FIND_BEST_SEATS: 'Trouver les meilleures places',
  },
  SPECIAL_OFFER: 'Offre spéciale',
  TICKET_CAN_BE_CANCELED: `Vous pouvez annuler jusqu'à {hours} heures à l'avance pour un remboursement complet.`,
  TICKET_CANNOT_BE_CANCELED:
    'Ce billet ne peut être annulé mais peut être reporté sur demande.',
  TICKETS: 'Billets',
  TIMINGS: 'Horaires',
  SPECIAL_PRODUCT_HEADING: 'Expérience adorée',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Guides expert·es',
    ENGAGING_STORIES: 'Récits captivants',
    TOP_RATED: 'La mieux notée',
  },
  GUIDED_TOUR_REVIEWS: [
    'Notre guide Angela était formidable et connaissait parfaitement les lieux',
    'Le guide était très heureux de répondre aux questions concernant la visite',
    'Notre guide était formidable et nous a même recommandé un excellent déjeuner!',
    "L'organisation et notre guide ont rendu l'expérience très agréable",
    'Beaucoup de contenu éducatif, je le referai sûrement avec mes enfants',
    "La visite a été bien organisée et a duré le temps qu'il fallait",
    'Bon guide et bonne organisation! A recommander!!!',
    'Notre guide, Maria, a réussi à nous trouver les meilleurs points de vue',
    'Visite détaillée et émouvante menée par un guide passionné',
    "Jeff nous a montré des aspects du lieu que nous n'aurions pas vus autrement",
    '',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Anglais',
    SPANISH: 'Espagnol',
    FRENCH: 'Français',
    ITALIAN: 'Italien',
    GERMAN: 'Allemand',
    PORTUGUESE: 'Portugais',
    NEDERLANDS: 'Néerlandais',
    POLISH: 'Polonais',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Visite disponible en {0}',
  GUIDES_BANNER: 'Vivez une expérience authentique avec nos super guides.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Une visite guidée est le meilleur moyen de découvrir cette destination. Nos guides expert·es sont vos partenaires locaux : ils partagent avec vous histoires, secrets et conseils.',
    'Ne vous contentez pas de visiter, vivez l’expérience !',
  ],
  HEAR_FROM_OUR_GUESTS: 'Avis de nos visiteurs',
  TODAY: "aujourd'hui",
  TOMORROW: 'demain',
  TOUR_LIST_HEADING: `Sélectionnez l'offre qui vous plaît`,
  TOUR_LIST_SUB_HEADING:
    'Choisissez parmi une multitude de billets, visites guidées et offres combo proposés par des agences de tourisme.',
  UGC: {
    FOLLOW: 'Suivre',
    FOLLOW_IG: 'Suivre sur Instagram',
    HEADING: 'POV : Voici à quoi ressemble votre prochaine aventure',
    SUB_HEADING: 'Sélectionnée avec 💜 par Headout',
  },
  UNAVAILABLE: 'Indisponible',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Ces billets sont valables pour une durée prolongée. Les détails exacts seront indiqués sur le billet.',
    UNTIL_DATE: 'Ces billets sont valables jusqu’au {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Ces billets sont valables pendant {0} jours à compter de la date d’achat.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Ces billets sont valables pendant {0} mois à compter de la date d’achat.',
  },
  TABLE_OF_CONTENTS: 'Sommaire',
  VIEW_LESS: 'Voir moins',
  VIEW_MORE: 'En savoir plus',
  WHY_TAKE_THIS_DAY_TRIP: 'Les avantages de cette excursion',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Menu principal',
    EXPLORE: 'Explorer',
    VISIT: 'Visiter',
    THINGS_TO_DO: 'Choses à faire',
    CITY_ATTRACTIONS: 'Que faire à {0}',
    TOP_THINGS_TO_DO: 'Meilleures choses à faire',
    CITY_TOURS: 'Visites de {0}',
    CITY_GUIDE: 'Guide de la ville',
    ATTRACTIONS: 'Attractions',
    CRUISES: 'Croisières',
    THEMES: 'Thèmes',
    ABOUT: 'À propos',
    TOURS: 'Visites',
    SKIP_THE_LINE_TOURS: 'Visites coupe-file',
    GUIDED_TOURS: 'Visites guidées',
    NIGHT_TOURS: 'Visites en soirée',
    FOOD_TOURS: 'Visites culinaires',
    HISTORY: 'Histoire',
    ARCHITECTURE: 'Architecture',
    DESIGN: 'Conception',
    INSIDE: 'Intérieur',
    COLLECTIONS: 'Collections',
    PAINTINGS: 'Tableaux',
    ANIMALS_EXHIBITS: 'Animaux et expositions',
    HABITATS: 'Habitats',
    CONSERVATION: 'Conservation',
    PROGRAMMES: 'Programmes',
    A2_SIGHTSEEING_CRUISES: 'Croisières promenade',
    A2_DINNER_CRUISES: 'Dîners-croisières',
    A2_EVENING_CRUISES: 'Croisières en soirée',
    A2_LUNCH_CRUISES: 'Déjeuners-croisières',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Planifier votre visite',
    TIMINGS: 'Horaires',
    DIRECTIONS: "Comment s'y rendre",
    PARKING: 'Parking',
    ROUTES: 'Itinéraires',
    REQUIREMENTS: 'Spécifications',
    LOCATION: 'Emplacement',
    RULES: 'Règles',
    FAQs: 'FAQ',
    ENTRANCES: 'Entrées',
    RESTAURANTS: 'Restaurants',
    FACTS: 'Anecdotes',
    TIPS: 'Conseils',
    MAP: 'Plan',
    RIDES: 'Manèges',
    SHOWS: 'Spectacles',
    DINING: 'Restauration',
    SHOPPING: 'Boutiques',
    EVENTS: 'Événements',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Noël',
    NEW_YEARS_EVE: 'Nouvel An',
    TRAVEL_GUIDE: 'Carnet de voyage',
    TRIP_PLANNER: 'Planificateur de voyage',
    ITINERARY: 'Itinéraire',
    TRAVEL_TIPS: 'Conseils de voyage',
    WEATHER: 'Météo',
    BEST_TIME_TO_VISIT: 'Meilleur moment pour visiter',
    JANUARY: 'Janvier',
    FEBRUARY: 'Février',
    MARCH: 'Mars',
    APRIL: 'Avril',
    MAY: 'Mai',
    JUNE: 'Juin',
    JULY: 'Juillet',
    AUGUST: 'Août',
    SEPTEMBER: 'Septembre',
    OCTOBER: 'Octobre',
    NOVEMBER: 'Novembre',
    DECEMBER: 'Décembre',
    WHERE_TO_EAT: 'Où manger',
    WHERE_TO_STAY: 'Où séjourner',
    NEIGHBOURHOODS: 'Quartiers',
    FAMILY_TRAVEL: 'Voyages en famille',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivals et événements',
  },
  WHY_WATCH: 'Pourquoi faut-il le voir',
  FIND_ON_MAP: 'Trouver sur la carte',
  LTT_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      INSTANT_TICKETS: {
        NAME: 'Vos billets immédiatement',
        DESCRIPTION: 'Confirmation directe de la billetterie.',
      },
      PRICES_LOVE: {
        NAME: `Les meilleurs prix garantis`,
        DESCRIPTION: 'Prix imbattables pour des spectacles incontournables.',
      },
      CHOOSE_SEATS: {
        NAME: 'Le choix de vos sièges',
        DESCRIPTION: 'Obtenez les meilleures places pour tous les spectacles.',
      },
      OFFICIAL_LTT: {
        NAME: 'Les billets officiels des théâtres de Londres',
        DESCRIPTION: 'Réservez rapidement et en toute sécurité avec nous.',
      },
    },
    YOUR_PICK: 'Votre choix',
    BROWSE_BY_CATEGORIES: 'Explorer par catégories',
    TOP_WEST_END_SHOWS: 'Les meilleurs spectacles de West End',
    LAST_MINUTE_TICKETS: 'Billets de dernières minutes',
    LOVED_BY_MILLIONS: 'Aimés par des millions de personnes',
    TODAY: `Aujourd'hui`,
    TOMORROW: 'Demain',
    SEE_ALL: 'Voir tout',
    GRAB_YOUR_TICKETS: 'Achetez vos billets maintenant',
  },
  TAG_NAME: {
    BALLET: 'Spectacles de ballet',
    CABARET: 'Cabaret',
    CHRISTMAS: 'Noël',
    CIRCUS: 'Cirque',
    CLASSIC: 'Classique',
    COMEDY: 'Comédie',
    COMING_SOON: 'Prochainement',
    CRITICS_CHOICE: 'Choix de la critique',
    DANCE: 'Danse',
    DISNEY: 'Disney',
    DRAMA: 'Drame',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantaisie',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Théâtre immersif',
    JUKEBOX: 'Jukebox',
    KIDS: 'Enfants',
    MAGIC: 'Spectacle de magie',
    MUSICALS: 'Comédies musicales',
    NEW_ARRIVAL: 'Nouveautés',
    OFF_WEST_END: 'Hors West End',
    OLIVIER_WINNER: "Lauréat d'Olivier",
    OPERA: 'Opéras',
    PANTOMIMES: 'Pantomimes',
    PLAYS: 'Pièces de théâtre',
    ROMANCE: "Histoire d'amour",
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Avec célébrités',
    THEATRICAL_CONCERT: 'Concert théâtral',
    TRUE_STORY: 'Basé sur une histoire vraie',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Oups, nous avons un problème',
    MESSAGE: `Oh non ! Toutes les expériences proposées à cette date sont soit épuisées, soit indisponibles. Mais nous pouvons vous en proposer plusieurs à d'autres dates. Vous avez amplement le choix !`,
    CTA: 'Voir les dates disponibles',
  },
  ALL_DATES: 'Toutes les dates',
  BREADCRUMBS: {
    HOME: 'Accueil',
    TRAVEL_GUIDE: 'Guide de voyage',
    THINGS_TO_DO: 'Que faire à {0}',
    SHOW_NAME_TICKETS: '{0} - Billets',
    LTT_HOME: 'Billets de théâtre à Londres',
    LTT_VENUE_PAGE_HOME: 'Théâtres à Londres',
    BROADWAY_HOME: 'Billets pour les spectacles de Broadway',
    BROADWAY_VENUE_PAGE_HOME: 'Théâtres de Broadway',
    VIENNA_CONCERT_HOME: 'Billets de concert à Vienne',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Salles de concert à Vienne',
    ATTRACTIONS: 'Attractions',
    A2_SIGHTSEEING_CRUISES: 'Croisières promenade',
    A2_DINNER_CRUISES: 'Dîners-croisières',
    A2_EVENING_CRUISES: 'Croisières en soirée',
    A2_LUNCH_CRUISES: 'Déjeuners-croisières',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'Actualités des théâtres de Londres',
    BROADWAY_SHOW_NEWS: 'Actualités des spectacles de Broadway',
    NEWS_PAGE: 'Actualités',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Café',
    'Dedicated Parking': 'Parking réservé',
    Elevators: 'Ascenseur',
    Lift: 'Ascenseur',
    'Wheelchair Accessible': 'Accès en fauteuil roulant',
    Cloakroom: 'Vestiaire',
    'Air Conditioning': 'Air conditionné',
    WiFi: 'WiFi',
    Bar: 'Bar',
    'Water Fountain': "Fontaine d'eau",
    Washrooms: 'Toilettes',
    Toilets: 'Toilettes',
    Binoculars: 'Jumelles',
    'Adapted Toilets': 'Toilettes adaptées',
    'Accessible Toilets': 'Toilettes accessibles',
    'Assistive Listening System': "Système d'écoute assistée",
    'Hearing Assistance': 'Assistance auditive',
    'Booster Cushions': "Coussins d'appoint",
    Shop: 'Boutique',
    'Souvenir Shop': 'Boutique de souvenirs',
    'Guide Dogs': 'Chiens guides',
    'Baby Changing Facilities': 'Espace de change pour bébés',
    'Security Check': 'Contrôle de sécurité',
    Ramp: "Rampe d'accès",
    'Level Access': 'Accès au niveau',
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Guides multilingues spécialisés',
    STL: 'Accès coupe-file',
    PERSONALIZED: 'Expérience personnalisée',
    LOCAL_FOOD: 'Cuisine et culture locales',
    MULTILINGUAL_GUIDES: 'Guides multilingues',
    CULINARY_EXPERTS: 'Rencontre avec des gastronomes',
    SIGHTSEEING: 'Visites et divertissements à bord',
    MULTILINGUAL_GT: 'Visites guidées en plusieurs langues',
    MULTI_ROUTES: 'Plusieurs itinéraires',
    HASSLE_FREE: 'Réservation en toute simplicité',
    FREQUENT_DEPARTURES: 'Départs fréquents',
    ONBOARD_AMENITIES: 'Meilleurs services à bord',
    FLEXI_TRAVEL: 'Voyage flexible sur plusieurs itinéraires',
    FLEXI_EXCHANGE_CANCEL: 'Échanges et annulations flexibles',
    EXTRA_DISCOUNT:
      'Réductions supplémentaires pour les jeunes, les seniors et les familles',
    PREPAID: 'Service de prépaiement',
    EASY_ACTIVATION: 'Activation facile',
    INSTANT_CONNECTIVITY: 'Connectivité immédiate avec une couverture mondiale',
    ROUND_TRIP: 'Navettes aller-retour',
    CULTURAL_EXPERIENCE: 'Expériences culturelles authentiques',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout utilise des cookies pour améliorer votre visite du site Web.',
    MOBILE: 'Nous utilisons des cookies.',
    LEARN_MORE: 'En savoir plus.',
  },
  SHOW_UNAVAILABLE: 'Spectacle indisponible',
  NEWS_PAGE: {
    FEATURED_NEWS: 'On en parle',
    ALL_NEWS: 'Tous les articles',
    MORE_READS: "Plus d'articles",
    LOAD_MORE: `Voir plus d'articles`,
    TRAILERS: 'Toutes les bandes-annonces',
    GET_YOUR_TICKETS: 'Achetez vos billets',
    POPULAR_SHOWS: 'Spectacles populaires',
  },
};
export default fr;
