const it = {
  AUDIO_GUIDE: {
    BANNER: 'Audio-guida gratuita',
    PRODUCT_SUFFIX: 'con audio-guida',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Un partner autorizzato e affidabile',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Rivenditore autorizzato',
    SUB_TEXT:
      'Esperienze autentiche fornite da partner verificati e affidabili.',
  },
  AVAILABLE: 'Disponibile',
  BANNER_CTA: 'Scopri le nostre offerte',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout è un marchio di cui si fidano milioni di utenti in tutto il mondo, che offre esperienze di qualità per vivere al meglio questa attrazione.',
    NON_PARTNERED_SENSITIVE:
      "Headout è un marchio di cui si fidano milioni di utenti in tutto il mondo, che offre esperienze di qualità per vivere al meglio questa attrazione. Questo non è il sito web dell'attrazione.",
    PARTNERED_NON_SENSITIVE:
      "Headout è un partner autorizzato e fidato dell'attrazione, che offre esperienze di qualità per poterla vivere al meglio.",
    PARTNERED_SENSITIVE:
      "Headout è un partner autorizzato e fidato dell'attrazione, che offre esperienze di qualità per poterla vivere al meglio. Questo non è il sito web dell'attrazione.",
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout è uno dei partner di fiducia di questa attrazione ufficialmente autorizzati a offrire una selezione delle migliori esperienze disponibili.',
  BOOK_NOW_CTA: 'Prenota ora',
  BUY_TICKETS_CTA: 'Scopri le nostre offerte',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      "Puoi cancellare questi biglietti fino a {0} ore prima dell'inizio dell'esperienza e ottenere un rimborso completo.",
    CANCELLABLE_ANYTIME:
      "Cancellazione gratuita in qualsiasi momento prima dell'inizio dell'esperienza",
    CANCELLABLE_DAYS:
      "Puoi cancellare questi biglietti fino a {0} giorni prima dell'inizio dell'esperienza e ottenere un rimborso completo.",
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Questi biglietti non possono essere cancellati. Tuttavia, i biglietti sono validi per un periodo di tempo prolungato.',
    HEADING: 'Polizza di modifica dei biglietti',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      "Questi biglietti non possono essere cancellati. Tuttavia, i biglietti possono essere riprogrammati fino a {0} ore prima dell'inizio dell'esperienza.",
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Questi biglietti non possono essere cancellati o riprogrammati.',
    VALID_UNTIL_DATE:
      'Questi biglietti non possono essere cancellati, ma puoi usarli in qualsiasi momento fino alla seguente data: {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Questi biglietti non possono essere cancellati, ma puoi usarli in qualsiasi momento entro i prossimi {0} giorni.',
    VALID_WITHIN_NEXT_MONTHS:
      'Questi biglietti non possono essere cancellati, ma puoi usarli in qualsiasi momento entro i prossimi {0} mesi.',
  },
  CANCELLATION_POLICY_HEADING: 'Polizza di cancellazione',
  CASHBACK: '{0} % di Cashback',
  CASHBACK_INFO:
    'Quando prenoti questa esperienza, riceverai un Cashback del <strong>{0} %</strong>. Il tuo Cashback verrà automaticamente accreditato sul tuo account Headout e potrai utilizzarlo per qualsiasi futura prenotazione con noi.',
  CATEGORY_SLIDER_HEADING:
    'I clienti che hanno prenotato questo spettacolo hanno visto anche',
  CHECK_AVAIL: 'Verifica disponibilità',
  CITY_PAGE: {
    BANNER_TITLE: 'Scopri il meglio di',
    TOP_ATTRACTIONS: 'Le attrazioni top',
    GO_BEYOND: 'Oltre {0}',
    ALL_DAY_TRIPS: 'Vedi tutte le gite di un giorno',
    CITIES_NEARBY: ' Città vicine',
    POPULAR_CATEGORIES: 'Categorie popolari',
    GO_TO_GUIDE: 'Guida per andare a {0}',
    VIEW_TRAVEL_GUIDE: 'Vedi la guida di viaggio',
    EXPLORE: 'Scopri {0}',
    GUIDE_SUBHEADING:
      'Visitare {0} non è mai stato più facile! La nostra guida di viaggio per {0} contiene tutto ciò che devi sapere: cosa magiare, cosa vedere, come arrivare e molto altro ancora!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Informazioni generali',
      WHERE_TO_EAT: 'Cosa mangiare',
      WHERE_TO_STAY: 'Dove alloggiare',
      THINGS_TO_DO: 'Cosa fare',
      WEATHER: 'Miglior periodo per le visite',
      NEIGHBOURHOODS: 'Comunità locale',
      TRANSPORTATION: 'Come spostarsi',
      TRIP_PLANNER: 'Programma di viaggio',
      FAMILY_TRAVEL: 'Viaggiare con bambini',
      TRAVEL_TIPS: 'Consigli e suggerimenti di viaggio',
      SHOPPING: 'Shopping',
      ART_AND_CULTURE: 'Arte e cultura',
    },
    MAILER: {
      HEADING:
        'Consigli per un viaggio a {0}, direttamente nella tua casella di posta',
      SUBHEADING:
        'Scopri nuove città con esperienze selezionate, cashback istantaneo, offerte esclusive e consigli imperdibili!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Informati sui requisiti per il visto, sul cambio di valuta, sul fuso orario e molto altro ancora per un soggiorno piacevole e senza intoppi.',
    WHERE_TO_EAT:
      'Lasciati coinvolgere dalla vivace scena culinaria, assaporando piatti diversi e gustando le prelibatezze locali in ogni angolo di {0}.',
    WHERE_TO_STAY:
      "Scopri gli alloggi migliori a {0}, che offrono comfort e convenienza per un'esperienza di viaggio unica.",
    THINGS_TO_DO:
      'Partecipa a tante attività e non lasciarti scappare attrazioni uniche, in grado di soddisfare tutti i gusti.',
    WEATHER:
      "Pianifica la tua visita e approfittane, perché {0} offre esperienze incantevoli durante tutto l'anno.",
    NEIGHBOURHOODS:
      'Fai la conoscenza di diverse comunità locali e visita quartieri vivaci che rendono {0} inimitabile.',
    TRANSPORTATION:
      "Visita {0} con facilità grazie all'efficiente sistema di trasporti, che offre comode opzioni per scoprire tutte le sue attrazioni.",
    TRIP_PLANNER:
      'Ottimizza il tuo tempo a {0} con itinerari accuratamente curati, che ti permetteranno di goderti al meglio ogni momento.',
    FAMILY_TRAVEL:
      "Parti per un'avventura perfetta per famiglie grazie alle attrazioni, ai parchi e alle opzioni di intrattenimento adatti ai bambini di tutte le età.",
    TRAVEL_TIPS:
      'Non perderti i consigli di viaggio e i trucchi per rendere il tuo viaggio e la tua visita a {0} davvero eccezionale.',
    SHOPPING:
      "Entra nel paradiso dello shopping: boutique, mercati e centri commerciali offrono di tutto, dall'artigianato locale all'alta moda.",
    ART_AND_CULTURE:
      'Immergiti nella ricca scena artistica e culturale, fatta di affascinanti musei e vivaci festival che mettono in mostra il patrimonio di {0}.',
  },
  CLOSE: 'Chiudi',
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Usiamo cookie e tecnologie simili per molti scopi, tra cui migliorare la tua esperienza sul nostro sito e annunci pubblicitari. ',
    MANAGE_PREFERENCES: 'Gestisci',
    PREFERNCES_SAVED: 'Le tue preferenze sono state salvate.',
    ACCEPT: 'Accetta',
    ALLOW_ALL: 'Consenti tutti',
    DENY_ALL: 'Rifiuta tutti',
  },
  COLLECTION_SLICE_HEADING: 'Le migliori cose da fare a {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Seleziona',
    SELECT_PREFERENCE: "Seleziona l'opzione che preferisci",
    SELECT_OPTION: 'Seleziona la variante desiderata',
    SELECT_TICKET: 'Seleziona il tuo biglietto',
  },
  COMPARE_ALL_DETAILS: 'Confronta tutti i dettagli',
  COVID19_ALERT: {
    KEY_TEXT: 'Aggiornamento riguardo COVID-19',
    LINK: 'https://medium.com/headout/epidemia-coronavirus-polizza-di-cancellazione-e7abdfb20451',
    TEXT: 'La nostra priorità sei tu. Consulta la nostra pagina di aiuto per trovare gli ultimi aggiornamenti sulle nostre politiche di cancellazione flessibili.',
  },
  CURRENCY: 'Valuta',
  CUSTOMER_REVIEW_HEADING: 'Recensioni dei clienti',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audio-guida',
    DURATION: 'Durata: {0}',
    EXTENDED_VALIDITY: 'Validità estesa',
    FLEXIBLE_DURATION: 'Durata flessibile',
    FREE_CANCELLATION: 'Cancellazione gratuita',
    GUIDED_TOUR: 'Tour guidato',
    HOTEL_PICKUP: 'Servizio di Prelievo in Hotel',
    INSTANT_CONFIRMATION: 'Conferma Istantanea',
    MEALS_INCLUDED: 'Pasti inclusi',
    MOBILE_TICKET: 'Biglietti per cellulari',
    SKIP_THE_LINE: 'Salta la Coda',
    TRANSFERS: 'Trasferimenti inclusi',
    MULTILINGUAL_AUDIO_GUIDE: 'Audio-guida in più lingue',
    LIVE_GUIDE: 'Guida dal vivo',
    FLEXIBLE_CANCELLATION: 'Cancellazione flessibile',
  },
  DURATION: 'Durata',
  EARLIEST_AVAILABILITY: 'Prima disponibilità',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Inserisci la tua e-mail qui',
    SIGN_UP: 'Iscriviti',
    THANK_YOU: 'Grazie!',
    SUBSCRIBED_MSG: "L'iscrizione è avvenuta con successo",
    ERROR_MSG: 'Inserisci un indirizzo e-mail valido',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Biglietti per il teatro a Broadway',
    },
    LTT: {
      MB_NAME: 'Biglietti per il teatro a Londra',
    },
  },
  EXCLUSIONS: 'Servizi esclusi',
  FEATURE_CARD: {
    HEADING_CUSTOMER: 'Oltre {0} milioni',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100% sicuro',
    HEADING_SUPPORT: 'Assistenza 24/7',
    SUB_HEADING_CUSTOMER: 'Di clienti soddisfatti, più di 10.000 esperienze',
    SUB_HEADING_RATING:
      'Oltre 5.000 recensioni verificate, con un giudizio Eccellente nel 90%',
    SUB_HEADING_SAFE: "Tutte le attività all'esterno sono completamente sicure",
    SUB_HEADING_SUPPORT:
      'Hai domande? Chatta dal vivo con i nostri esperti, quando vuoi, da dove vuoi',
  },
  FLEXIBLE: 'Flessibile',
  FOOTER: {
    CALL_US: 'Chiamaci',
    CHAT_WITH_US: 'Chatta con noi',
    COMPANY_DETAILS: 'Dettagli sulla società',
    ABOUT_US: 'Chi siamo',
    INFORMATION: 'Informazioni',
    GMAPS_DISCLAIMER:
      'Tutte le schermate delle mappe presenti in questa pagina provengono da Google in conformità con il principio di utilizzo legittimo. Tutti i diritti relativi a tali schermate appartengono alla piattaforma specifica e il loro utilizzo è esclusivamente a scopo informativo o orientativo.',
    DISCLAIMER:
      'Questo non è il sito internet ufficiale della seguente attrazione: <attraction>. Questo sito è gestito da Headout e lavora con attrazioni e tour operator per fornire esperienze incredibili al tocco di un pulsante.',
    EMAIL_US: 'Contattaci via E-mail',
    GET_HELP: 'Aiuto',
    LEGAL: 'Informazioni legali',
    PRIVACY_POLICY: 'Informativa sulla privacy',
    QUICK_LINKS: 'Link diretti',
    TERMS_AND_CONDITIONS: `Termini e condizioni d'uso`,
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Creato con ',
    ALL_OVER_THE: ' in tutto il ',
    TERMS_OF_USAGE: `Termini d'uso`,
    GET_HELP_24_7: 'Assistenza 24/7',
    HELP_CENTER: ' Centro di assistenza',
    COMPANY: 'Azienda',
    WE_ACCEPT: 'Metodi di Pagmento Accettati',
    DOWNLOAD_HEADOUT: `Scarica l'app Headout`,
    SCAN_CODES: 'scannerizza i codici',
    STAR_VERIFIED: `Clicca per verificare l'iscrizione a S.T.A.R.`,
    OFFICIAL_TICKET_RETAILER: 'Rivenditor Ufficiale di Biglietti',
  },
  FREE_CANCELLATION: 'Cancellazione gratuita',
  FREE_CANCELLATION_SUBTEXT: `Sappiamo che i piani possono cambiare: cancella gratuitamente fino a 72 ore prima.`,
  FROM: 'A partire da',
  GET_CASHBACK: 'Ottieni {0} % di cashback',
  GROUP_TICKETS: 'Biglietti di gruppo',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '{0} milioni di clienti',
    SUB_TEXT: 'La tua soddisfazione è la nostra priorità. Unisciti a noi.',
  },
  HELP_CENTER: {
    MAIN_TEXT: 'Assistenza 24/7',
    SUB_TEXT:
      'Hai domande? Devi modificare il biglietto? Contattaci via telefono, e-mail o chat.',
  },
  INCLUSIONS: 'Inclusioni',
  LANGUAGE: 'Lingua',
  LISTICLES: {
    KNOW_MORE: 'Altre informazioni',
    SEATING_CHART: 'Mappa dei posti a sedere',
    WHY_BOOK_FROM_US: 'Perché vale la pena prenotare con noi?',
  },
  MORE_DETAILS: 'Altri dettagli',
  MORE_CURRENCIES: 'Altre valute',
  NEW: 'Novità',
  NEW_ARRIVAL: 'Nuovi arrivi',
  NEXT_AVAILABLE: 'Prossimo disponibile: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    "Headout è scelto da oltre {0} milioni di persone per trovare una selezione curata delle migliori esperienze. Questo non è il sito ufficiale dell'attrazione.",
  NO_RESULT_FOUND: 'Non è stato trovato nessun risultato',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR:
    'Prenota con flessibilità: non è necessario selezionare la data',
  OPENING_DATE: 'Data di apertura',
  OPENING_ON: 'Apertura',
  OPENS: 'Apre',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    "Headout è uno dei partner di fiducia di questa attrazione ufficialmente autorizzati a offrire una selezione delle migliori esperienze disponibili. Questo non è il sito web dell'attrazione.",
  POPULARITY: 'Popolarità',
  POPULAR_CURRENCIES: 'Valute più usate',
  PRICE: 'Prezzo',
  PRICES_STARTING: 'Prezzi a partire da',
  PROMO_CODES: {
    APPLY_CODE: 'APPLICA IL CODICE',
    APPLIED: 'APPLICATO',
    TOOL_TIP_INFO: 'Questo sconto sarà applicato al check-out',
    DESCRIPTION: {
      ABSOLUTE: 'Sconto di {0}',
      CAPPED: 'Sconto del {0}%, fino a {1}',
      PERCENTAGE: 'Sconto del {0}%',
    },
    REMOVE: 'RIMUOVI',
  },
  RATINGS: '{0} Recensioni',
  READ_MORE: 'Leggi tutto',
  READ_MORE_TEXT: 'Leggi tutto',
  READ_LESS: 'Leggi meno',
  VIEW_DETAILS: 'Visualizza dettagli',
  REOPENING: 'Riapertura',
  REOPENING_DATE: 'Data di riapertura',
  REOPENING_ON: 'Riapertura',
  REOPENS: 'Riapre',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT: "Si applicano i regolamenti 2G: l'accesso agli alloggi, alle istituzioni culturali, ai ristoranti/bar e altri ritrovi pubblici è possibile solo se si esibisce la prova di completata vaccinazione o di guarigione da infezione pregressa. Mostrare un test Covid-19 dall'esito negativo non è più sufficiente.",
    },
    AU_DESCRIPTION: {
      TEXT: "I visitatori dai 16 anni in su devono mostrare una prova di avvenuta vaccinazione COVID-19 o un'esenzione medica.",
    },
    BANNER_CTA: 'Leggi tutto',
    BERLIN_DESCRIPTION: {
      TEXT: "Si applica il regolamento 2G: potranno accedere solo gli ospiti completamente vaccinati o guariti e dotati di certificato comprovante lo stato di guarigione o avvenuta vaccinazione. Gli ospiti sotto i 18 anni o coloro che non possono essere vaccinati per motivi medici devono presentare all'ingresso un risultato negativo del test per COVID. Coloro che non possono essere vaccinati per ragioni mediche devono dimostrare all'ingresso la loro impossibilità di essere vaccinati per mezzo di un certificato medico.",
    },
    CTA_TEXT: 'Dettagli Sulla Sicurezza',
    DESCRIPTION_CTA: 'Per saperne di più.',
    EU_DESCRIPTION: {
      TEXT: 'Dal 21 luglio 2021 tutti i visitatori dai 12 anni in su devono presentare un certificato EU COVID.',
    },
    EU_HEADING: "Certificato COVID dell'UE richiesto",
    EU_PREFIX: 'Nota bene: ',
    EXPERIENCE_DESCRIPTION:
      "Questa esperienza è stata certificata per l'implementazione dei migliori standard di sicurezza in accordo con le linee guida dell'OMS",
    FLAG_TEXT: 'Sicurezza Verificata',
    GENERAL_DESCRIPTION:
      'Ogni esperienza contrassegnata da questo stemma è conforme ai migliori standard di sicurezza imposti dalle direttive sanitarie del governo locale.',
    HEADING: 'I più alti standard di sicurezza',
    IT_DESCRIPTION: {
      TEXT: 'Dal 6 agosto 2021, tutti i visitatori dagli 11 anni in su dovranno presentare un Green Pass o un certificato EU COVID.',
    },
    IT_PREFIX: 'Avviso : ',
    MOBILE_HEADING: 'Esperienze Sicure',
    MODAL: {
      BADGE_DESCRIPTION:
        "Questo stemma applicato a un'esperienza conferma che i suoi standard di sicurezza sono stati verificati da noi",
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Tutte le attrezzature, i veicoli e le aree ad alto rischio di contatto vengono disinfettate dopo ogni singolo utilizzo. Puoi partecipare alle attività senza nessuna preoccupazione.',
          HEADING:
            'Tutte le attrezzature e le superfici vengono disinfettate regolarmente',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Tutte le attrezzature disponibili durante la tua esperienza vengono accuratamente igienizzate dopo ogni singolo utilizzo. Sempre.',
          HEADING:
            'Tutte le attrezzature e le superfici vengono disinfettate regolarmente',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Tutti i veicoli disponibili durante la tua esperienza vengono accuratamente igienizzati dopo ogni singolo utilizzo. Sempre.',
          HEADING: 'Tutti i veicoli vengono disinfettati regolarmente',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            "Durante un'esperienza sicura, avrai accesso alle stazioni di lavaggio per le mani e alle stazioni igienico-sanitarie per tutto il tempo che trascorrerai nell'attività. Ci pensiamo noi a provvedere tutto il necessario per una visita sicura.",
          HEADING:
            'Strutture igienico-sanitarie e disinfettante per le mani disponibili in tutti i luoghi visitabili',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Le maschere sono obbligatorie per tutti gli ospiti e i membri dello staff in questa esperienza. Questo accorgimento sanitario permette a tutti i partecipanti di divertirsi in piena sicurezza.',
          HEADING: 'Tutti indossano maschere per garantire la tua sicurezza',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            "I nostri partner certificati con lo stemma \"Esperienza Sicura\" seguono rigorosamente le normative locali in vigore per quanto riguarda l'utilizzo di maschere facciali. Quando l'utilizzo delle maschere è obbligatorio, tutti gli ospiti e i membri dello staff indosseranno maschere per tutta la durata dell'esperienza. I nostri partner faranno tutto il possibile per garantire il tuo comfort e la tua sicurezza.",
          HEADING: 'Tutti indossano maschere per garantire la tua sicurezza',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Le maschere sono obbligatorie per tutti gli ospiti che partecipano a questa esperienza. Questo accorgimento sanitario permette a tutti i partecipanti di divertirsi in piena sicurezza.',
          HEADING: 'Tutti indossano maschere per garantire la tua sicurezza',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            "Tutti i membri dello staff di questa esperienza indossano maschere facciali per garantirti un'esperienza divertente e priva di preoccupazioni.",
          HEADING: 'Tutti indossano maschere per garantire la tua sicurezza',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Le linee guida per il distanziamento sociale vengono imposte e rispettate per tutta la durata di questa esperienza. Sono in vigore restrizioni al numero di turisti presenti nello stesso tempo per permettere un efficace distanziamento sociale.',
          HEADING:
            'Le linee guida per il distanziamento sociale vengono osservate alla lettera',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            "Le linee guida per il distanziamento sociale vengono imposte e rispettate per tutta la durata di questa esperienza. Sono in vigore restrizioni al numero di persone che hanno accesso all'esperienza per garantire un distanziamento sociale efficace. Per lo stesso motivo, gruppi di ospiti troppo numerosi non sono ammessi all'esperienza.",
          HEADING:
            'Le linee guida per il distanziamento sociale vengono osservate alla lettera',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Le linee guida per il distanziamento sociale vengono imposte e rispettate per tutta la durata di questa esperienza. Potrai Visitare in tutta sicurezza.',
          HEADING:
            'Le linee guida per il distanziamento sociale vengono osservate alla lettera',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            "Le linee guida per il distanziamento sociale vengono imposte e rispettate per tutta la durata di questa esperienza. Per far rispettare queste norme potrebbero esserci delle restrizioni al numero di partecipanti e alla dimensione dei gruppi che hanno accesso all'attività.",
          HEADING:
            'Le linee guida per il distanziamento sociale vengono osservate alla lettera',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            "Le linee guida per il distanziamento sociale vengono imposte e rispettate per tutta la durata di questa esperienza. Per lo stesso motivo, gruppi di ospiti troppo numerosi non sono ammessi all'esperienza.",
          HEADING:
            'Le linee guida per il distanziamento sociale vengono osservate alla lettera',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            "La temperatura corporea di tutti gli ospiti verrà controllata all'inizio dell'esperienza per garantire la sicurezza di tutti. Tutti i membri del personale vengono controllati più volte al giorno per controllare l'insorgere di febbre e temperature elevate.",
          HEADING: 'Controlli della temperatura corporea alle attrazioni',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            "La temperatura corporea di tutti gli ospiti verrà controllata all'inizio dell'esperienza per garantire la sicurezza di tutti.",
          HEADING: 'Controlli della temperatura corporea alle attrazioni',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Tutti i membri del personale vengono controllati più volte per verificare la presenza di temperature corporee elevate. I membri dello staff che superano la soglia di sicurezza per la temperatura corporea vengono immediatamente obbligati a stare a casa per rimettersi in salute.',
          HEADING: 'Controlli della temperatura corporea alle attrazioni',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            "Il personale disponibile durante tutta l'esperienza è stato addestrato per lavorare in pieno rispetto delle linee guida dell'OMS ed è equipaggiato per gestire qualsiasi emergenza.",
          HEADING:
            "Il personale è stato istruito su come seguire alla lettera le linee guida dell'OMS",
        },
      },
      HEADING: 'Esperienze Sicure',
      SUB_HEADING:
        "Stiamo lavorando con i nostri partner in tutto il mondo per implementare i migliori standard di sicurezza in accordo con le linee guida dell'OMS. Tutte le misure adottate sul campo sono state verificate: le puoi vedere elencate in questa sezione. È tempo di godersi di nuovo il mondo che ci circonda.",
    },
    NL_DESCRIPTION: {
      TEXT: "I visitatori dai 13 anni in su devono presentarsi con un certificato COVID (copia digitale o stampata) che dimostri l'avvenuta vaccinazione oppure un risultato negativo del test antigenico o un documento che certifichi l'avvenuta guarigione da COVID-19. Indossare una maschera facciale è obbligatorio.",
    },
    SG_DESCRIPTION: {
      TEXT: 'Dal 13 ottobre 2021 solo i visitatori completamente vaccinati potranno entrare in gruppi di 2. Dovrai mostrare la prova dello stato di avvenuta vaccinazione, un risultato negativo recente del test antigenico COVID-19, e/o qualsiasi documentazione per lo stato di avvenuta guarigione prima di entrare.',
    },
    SHORT_HEADING: 'I migliori standard di sicurezza in vigore',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'La tua sicurezza è la nostra priorità',
    TEXT: 'Abbiamo implementato misure di sicurezza per migliorare la pulizia degli ambienti utilizzando disinfettanti tramite pulizie frequenti di tutye le superfici che entrano in contatto col pubblico. Inoltre, il numero di accessi giornaliero è ora regolamentato per evitare assembramenti.',
  },
  SAVE: 'Risparmi il  {0}%',
  SAVE_PERCENT: 'Risparmia il {0}%',
  SAVE_UPTO: 'Risparmi fino al',
  SAVE_UPTO_PERCENT: 'Risparmia fino al {0}%',
  SEARCH: 'Cerca',
  SEE_ALL: 'Vedi tutto',
  SEE_MORE_SHOWS: 'Guarda altri spettacoli',
  SELECT_CITY: 'Seleziona città',
  SELECT_SECTION: 'Seleziona tribuna',
  SEE_ALL_PHOTOS: 'Vedi tutte le foto',
  SHOW_CLOSED: 'Spettacolo terminato',
  SHOW_LESS_TEXT: 'Mostra meno',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Informazioni sullo spettacolo',
    ABOUT_THEATRE: 'Dettagli sul teatro',
    ADDITIONAL_INFORMATION: 'Informazioni aggiuntive',
    AGE_LIMIT: 'Limite di età',
    AGE_SUITABILITY: 'Limiti di età',
    ANSWER: ['R-', 'A-'],
    BLOG_SHOW_PAGE: 'Blog - Pagina dedicata allo show',
    BLOG_SUMMARY: 'Blog - Riassunto dell show',
    BLOG_THEATRE_PAGE: 'Blog - Pagina dedicata al teatro',
    BLOG_THEATRE_SEATING_PLAN: 'Blog - Mappa dei posti a sedere del teatro',
    CANCELLATION_AND_REFUNDS: 'Cancellazioni e rimborsi',
    CANCELLATION_POLICY: 'Polizza di cancellazione',
    CAST_AND_CREW: 'Cast e troupe',
    CLOSING_DATE: 'Data di chiusura',
    CLOSING_DATE_SPECIAL_OFFER: "Data di chiusura dell'offerta speciale",
    DURATION: 'Durata',
    FACILITIES_AND_ACCESSIBILITY: 'Servizi e accessibilità',
    FREQUENTLY_ASKED_QUESTIONS: 'Domande frequenti',
    GETTING_THERE: 'Come arrivare',
    GETTING_THERE_MAP_LINK:
      'Come arrivare - Link alla mappa delle direzioni stradali',
    GOOGLE_MAP: 'Direzioni stradali di Google Maps',
    HIGHLIGHTS: 'Punti salienti',
    LISTICLE_SHOW_SUMMARY: 'Listicle Riassunto dello spettacolo',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Perché vale la pena vedere questo show',
    OPENING_DATE: 'Data di apertura',
    QUESTION: ['D-', 'Q-'],
    SAFETY_BANNER: 'Banner di sicurezza',
    SHOW_DETAILS: 'Dettagli dello spettacolo',
    SHOW_TIMINGS: 'Orari degli spettacoli',
    SHOW_TYPE: 'Tipo di spettacolo',
    SPECIAL_OFFER: 'Offerta speciale',
    THE_STORY: 'La storia',
    THEATRE_ADDRESS: 'Indirizzo del teatro',
    THEATRE_CAPACITY: 'Numero di posti a sedere',
    THEATRE_NAME: 'Nome del teatro',
    TICKETS: 'Biglietti',
    TICKETS_REDEMPTION: 'Riscatto dei biglietti',
    TOP_SONGS: 'Canzoni più famose',
    YOUR_TICKETS: 'I tuoi biglietti',
    ABOUT_CONCERT: 'Il concerto',
    PROGRAM: 'Programma',
  },
  SORT_BY: 'Ordina per',
  THEATRE: 'Teatro',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Teatri vicini',
    NOW_PLAYING: 'Spettacoli in corso',
    UPCOMING_SHOWS: 'Spettacoli in arrivo',
    PAST_SHOWS: 'Spettacoli passati',
    FIND_BEST_SEATS: 'Trova i posti migliori',
  },
  SPECIAL_OFFER: 'Offerta speciale',
  TICKET_CAN_BE_CANCELED: `Puoi cancellare fino a {hours} ore in anticipo sull'orario prenotato per ottenere un rimborso completo.`,
  TICKET_CANNOT_BE_CANCELED:
    'Questo biglietto non può essere annullato ma può essere riprogrammato su richiesta.',
  TICKETS: 'Biglietti',
  TIMINGS: 'Orari',
  SPECIAL_PRODUCT_HEADING: 'Esperienze più amate',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Guide locali esperte',
    ENGAGING_STORIES: 'Storie coinvolgenti',
    TOP_RATED: 'Esperienze popolari',
  },
  GUIDED_TOUR_REVIEWS: [
    'La nostra guida Angela è stata fantastica e piena di conoscenze sul luogo',
    'La guida è stata molto felice di rispondere alle domande sul tour',
    'La nostra guida è stata fantastica e ci ha anche consigliato un ottimo pranzo',
    "L'organizzazione e la nostra guida hanno reso l'esperienza molto piacevole",
    'Un sacco di contenuti educativi, lo rifarò sicuramente con i miei figli',
    'Il tour è stato ben organizzato e con la giusta durata',
    'Ottima guida e buona organizzazione! Lo raccomando!!!',
    'Il tour si è svolto a un buon ritmo e non è stato affrettato',
    'Jeff ci ha mostrato aspetti del locale che altrimenti ci sarebbero sfuggiti',
    "L'esperienza del tour è stata molto buona, tutto è stato ben gestito",
    '',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Inglese',
    SPANISH: 'Spagnolo',
    FRENCH: 'Francese',
    ITALIAN: 'Italiano',
    GERMAN: 'Tedesco',
    PORTUGUESE: 'Portoghese',
    NEDERLANDS: 'Olandese',
    POLISH: 'Polacco',
    RUSSIAN: 'Russo',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Tour disponibile in {0}',
  GUIDES_BANNER: "Vivi un'esperienza autentica con le nostre guide esperte!",
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Un tour guidato è il modo migliore per scoprire al meglio questa destinazione. Le nostre guide esperte ti accompagneranno, ti racconteranno storie e curiosità e ti daranno consigli.',
    'Molto più di una semplice visita!',
  ],
  HEAR_FROM_OUR_GUESTS: 'I viaggiatori dicono',
  TODAY: 'oggi',
  TOMORROW: 'domani',
  TOUR_LIST_HEADING: 'Seleziona la tua esperienza',
  TOUR_LIST_SUB_HEADING:
    'Scegli tra una varietà di biglietti, tour e opzioni combinate fornite da operatori verificati',
  UGC: {
    FOLLOW: 'Segui',
    FOLLOW_IG: 'Segui su Instagram',
    HEADING: 'La tua prossima avventura ti accoglierà così',
    SUB_HEADING: 'Esperienze selezionate con 💜 da Headout',
  },
  UNAVAILABLE: 'Non disponibile',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Questi biglietti offrono una durata estesa. I dettagli saranno riportati sul biglietto.',
    UNTIL_DATE: 'Questi biglietti sono validi fino al giorno {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Questi biglietti sono validi per {0} giorni a partire dalla data di acquisto.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Questi biglietti sono validi per {0} mesi a partire dalla data di acquisto.',
  },
  TABLE_OF_CONTENTS: 'Sommario',
  VIEW_LESS: 'Mostra meno',
  VIEW_MORE: 'Leggi tutto',
  WHY_TAKE_THIS_DAY_TRIP: 'Perché vale la pena partecipare a questa gita?',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Menu principale',
    EXPLORE: 'Esplora',
    VISIT: 'Visita',
    THINGS_TO_DO: 'Cose da fare',
    CITY_ATTRACTIONS: 'Attrazioni a {0}',
    TOP_THINGS_TO_DO: 'Le migliori cose da fare',
    CITY_TOURS: 'Tour a {0}',
    CITY_GUIDE: 'Guida della città',
    ATTRACTIONS: 'Attrazioni',
    CRUISES: 'Crociere',
    THEMES: 'Temi',
    ABOUT: 'Informazioni',
    TOURS: 'Tour',
    SKIP_THE_LINE: 'Tour Salta la Coda',
    GUIDED_TOURS: 'Tour guidati',
    NIGHT_TOURS: 'Tour serali',
    FOOD_TOURS: 'Tour gastronomici',
    HISTORY: 'Storia',
    ARCHITECTURE: 'Architettura',
    DESIGN: 'Design',
    INSIDE: 'Interni',
    COLLECTIONS: 'Collezioni',
    PAINTINGS: 'Dipinti',
    ANIMALS_EXHIBITS: 'Mostre e animali',
    HABITATS: 'Habitat',
    CONSERVATION: 'Conservazione',
    PROGRAMMES: 'Programmi',
    A2_SIGHTSEEING_CRUISES: 'Crociere panoramiche',
    A2_DINNER_CRUISES: 'Crociere con cena',
    A2_EVENING_CRUISES: 'Crociere serali',
    A2_LUNCH_CRUISES: 'Crociere con pranzo',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Pianifica la tua visita',
    TIMINGS: 'Orari',
    DIRECTIONS: 'Direzioni',
    PARKING: 'Parcheggio',
    ROUTES: 'Percorsi',
    REQUIREMENTS: 'Requisiti',
    LOCATION: 'Posizione',
    RULES: 'Regole',
    FAQs: 'Domande frequenti',
    ENTRANCES: 'Ingressi',
    RESTAURANTS: 'Ristoranti',
    FACTS: 'Curiosità',
    TIPS: 'Consigli',
    MAP: 'Mappa',
    RIDES: 'Giostre',
    SHOWS: 'Spettacoli',
    DINING: 'Ristoranti',
    SHOPPING: 'Shopping',
    EVENTS: 'Eventi',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Natale',
    NEW_YEARS_EVE: 'Capodanno',
    TRAVEL_GUIDE: 'Guida di viaggio',
    TRIP_PLANNER: 'Pianificatore del viaggio',
    ITINERARY: 'Itinerario',
    TRAVEL_TIPS: 'Consigli di viaggio',
    WEATHER: 'Meteo',
    BEST_TIME_TO_VISIT: 'Il periodo migliore per viaggiare',
    JANUARY: 'Gennaio',
    FEBRUARY: 'Febbraio',
    MARCH: 'Marzo',
    APRIL: 'Aprile',
    MAY: 'Maggio',
    JUNE: 'Giugno',
    JULY: 'Luglio',
    AUGUST: 'Agosto',
    SEPTEMBER: 'Settembre',
    OCTOBER: 'Ottobre',
    NOVEMBER: 'Novembre',
    DECEMBER: 'Dicembre',
    WHERE_TO_EAT: 'Dove mangiare',
    WHERE_TO_STAY: 'Dove dormire',
    NEIGHBOURHOODS: 'Quartieri',
    FAMILY_TRAVEL: 'Viaggi in famiglia',
    TRANSPORTATION: 'Trasporti',
    FESTIVALS_EVENTS: 'Festival ed eventi',
  },
  WHY_WATCH: 'Perché guardare {0}?',
  FIND_ON_MAP: 'Mappa',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Biglietti del botteghino',
        DESCRIPTION: 'Conferma istantanea sul cellulare',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Scegli i posti`,
        DESCRIPTION: 'La vista che desideri, sempre',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Offerte e sconti esclusivi',
        DESCRIPTION: `Grandi sconti sui migliori spettacoli a {0}`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Prenotazione semplice',
        DESCRIPTION: '{0} milioni di clienti soddisfatti',
      },
    },
    YOUR_PICK: 'La tua scelta',
    BROWSE_BY_CATEGORIES: 'Sfoglia per categorie',
    TOP_WEST_END_SHOWS: 'I migliori spettacoli al West End',
    TOP_THEATRE_SHOWS: '{0}: gli spettacoli da non perdere',
    TOP_SHOWS: 'Gli spettacoli principali',
    SEE_MORE_SHOWS: 'Guarda {0} altri spettacoli',
    LAST_MINUTE_TICKETS: 'Biglietti last minute',
    LOVED_BY_MILLIONS: 'Amato da milioni di persone',
    TODAY: 'Oggi',
    TOMORROW: 'Domani',
    SEE_ALL: 'Vedi tutto',
    GRAB_YOUR_TICKETS: 'Prendi subito i biglietti',
  },
  TAG_NAME: {
    BALLET: 'Balletti',
    CABARET: 'Cabaret',
    CHRISTMAS: 'Natale',
    CIRCUS: 'Circo',
    CLASSIC: 'Classico',
    COMEDY: 'Commedia',
    COMING_SOON: 'In arrivo',
    CRITICS_CHOICE: 'Acclamati',
    DANCE: 'Danza',
    DISNEY: 'Disney',
    DRAMA: 'Dramma',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasia',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Teatro immersivo',
    JUKEBOX: 'Jukebox',
    KIDS: 'Bambini',
    MAGIC: 'Magia',
    MUSICALS: 'Musical',
    NEW_ARRIVAL: 'Nuovi arrivi',
    OFF_WEST_END: 'Fuori dal West End',
    OLIVIER_WINNER: "Vincitore dell'Olivier",
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomime',
    PLAYS: 'Show teatrali',
    ROMANCE: "Storie d'amore",
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Star sul palco',
    THEATRICAL_CONCERT: 'Concerto teatrale',
    TRUE_STORY: 'Una storia vera',
    TONY_WINNER: 'Vincitore del Tony',
    OFF_BROADWAY: 'Fuori da Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'C’è un piccolo problema',
    MESSAGE: `Oh, no! Tutte le esperienze disponibili per questa data sono esaurite o non disponibili. Ma ci sono tante altre date tra cui scegliere: basta che tu sia flessibile.`,
    CTA: 'Guarda tutte le date',
  },
  ALL_DATES: 'Tutte le date',
  BREADCRUMBS: {
    HOME: 'Home',
    TRAVEL_GUIDE: 'Guida di viaggio',
    THINGS_TO_DO: 'Cose da fare a {0}',
    SHOW_NAME_TICKETS: '{0} - Biglietti',
    LTT_HOME: 'Biglietti per il teatro a Londra',
    LTT_VENUE_PAGE_HOME: 'Teatri a Londra',
    BROADWAY_HOME: 'Biglietti per Broadway',
    BROADWAY_VENUE_PAGE_HOME: 'Teatri a Broadway',
    VIENNA_CONCERT_HOME: 'Biglietti per concerti a Vienna',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Sale da concerto a Vienna',
    ATTRACTIONS: 'Attrazioni',
    A2_SIGHTSEEING_CRUISES: 'Crociere panoramiche',
    A2_DINNER_CRUISES: 'Crociere con cena',
    A2_EVENING_CRUISES: 'Crociere serali',
    A2_LUNCH_CRUISES: 'Crociere con pranzo',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'News sui teatri di Londra',
    BROADWAY_SHOW_NEWS: 'News sui teatri di Broadway',
    NEWS_PAGE: 'Novità',
    REVIEWS_PAGE_BANNER_HEADING: 'Recensioni su {0}',
  },
  AMENITIES: {
    Restaurant: 'Ristorante',
    Cafe: 'Caffetteria',
    'Dedicated Parking': 'Parcheggio dedicato',
    Elevators: 'Ascensori',
    Lift: 'Ascensore',
    'Wheelchair Accessible': 'Accessibile alle sedie a rotelle',
    Cloakroom: 'Guardaroba',
    'Air Conditioning': 'Aria condizionata',
    WiFi: 'WiFi',
    Bar: 'Bar',
    'Water Fountain': "Distributore d'acqua",
    Washrooms: 'Servizi igienici',
    Toilets: 'Bagni',
    Binoculars: 'Binocoli',
    'Adapted Toilets': 'Servizi igienici adattati',
    'Accessible Toilets': 'Servizi igienici accessibili',
    'Assistive Listening System': 'Sistema di ascolto assistito',
    'Hearing Assistance': "Assistenza all'udito",
    'Booster Cushions': 'Cuscini di sostegno',
    Shop: 'Negozio',
    'Souvenir Shop': 'Negozio di souvenir',
    'Guide Dogs': 'Cani guida',
    'Baby Changing Facilities': 'Fasciatoio per bambini',
    'Security Check': 'Controllo di sicurezza',
    Ramp: 'Rampa',
    'Level Access': 'Accesso al piano',
  },
  CALENDAR: {
    FOOTNOTE: '* Tutti i prezzi sono in {0}',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Leggi la recensione originale in {0}',
    VIEW_ORIGINAL_NO_LANG: 'Questa recensione è tradotta. Mostra l’originale.',
    TRANSLATE: 'Traduci la recensione in {0}',
    LANGUAGES: {
      EN: 'inglese',
      ES: 'spagnolo',
      FR: 'francese',
      IT: 'italiano',
      DE: 'tedesco',
      PT: 'portoghese',
      NL: 'olandese',
    },
  },
  SHOW_PAGE_V2: {
    SELLING_OUT_FAST: 'In rapido esaurimento',
    MUST_DO_EXP: 'Da non perdere',
    INTERVAL: 'Intervallo',
    TWO_PART_SHOW: 'Spettacolo in due parti',
    READ_MORE_REVIEWS: 'Leggi altre recensioni',
    SHOW_MORE_REVIEWS: 'Mostra più recensioni',
    ALL_PHOTOS: 'Tutte le foto',
    MORE_DATES: 'Altre date',
    SELECT_TIME_SLOT: 'Seleziona una fascia oraria',
    SELECT_TIME_SLOT_ERROR: 'Seleziona una fascia oraria per continuare',
    PRICE_STARTING_FROM: 'Prezzo dei posti a partire da',
    SELECT_SEATS: 'Seleziona i posti',
    READ_MORE: 'Leggi di più',
    RATINGS_AND_REVIEWS: 'Valutazioni e recensioni',
    READ_DETAILED_REVIEWS: 'Leggi recensioni complete',
    UNTIL_DATE: 'Fino {0}',
    AVAILABLE_TIME: 'Orario disponibile',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      "Questa esperienza è disponibile solo nell'orario di seguito",
    CONTENT_TABS: {
      ABOUT: 'Dettagli',
      VENUE: 'Location',
      TICKETS: 'Biglietti',
      Reviews: 'Recensioni',
    },
    SELECT_SHOW_TIMMING: "Seleziona l'orario dello spettacolo",
    ONLY_ONE_SLOT: 'Un solo orario disponibile nella data selezionata',
    SIMILAR_SHOWS: 'Potrebbe piacerti anche...',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'La trama',
      AGE_SUITABILITY_AND_GUIDELINES: 'Età consigliata e altre linee guida',
      WHAT_CRITICS_THINK: 'Cosa dice la critica',
      CAST_AND_CREATIVES: 'Cast e troupe',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Domande frequenti',
    },
    TICKETS_UNAVAILABLE: 'I biglietti non sono disponibili',
    TICKETS_UNAVAILABLE_SUBTEXT:
      'Ma hai a disposizione tante altre opzioni tra cui scegliere.',
    MUST_SEE_SHOWS: 'Altri spettacoli imperdibili',
    SEE_ALL_SHOWS: 'Scopri tutti gli spettacoli',
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Guide multilingue esperte',
    STL: 'Accesso Salta la Coda',
    PERSONALIZED: 'Esperienze personalizzate',
    LOCAL_FOOD: 'Scopri il cibo e la cultura locale',
    MULTILINGUAL_GUIDES: 'Guide multilingue',
    CULINARY_EXPERTS: 'Incontra gli esperti di cucina',
    SIGHTSEEING: 'Visite e intrattenimento a bordo',
    SIGHTSEEING_MEAL: 'Visite turistiche e pasti a bordo',
    MULTILINGUAL_GT: 'Visite guidate multilingue',
    AUDIOGUIDE_COMMENTARY: 'Audio-guida e commenti',
    ALL_TOP_ATTRACTIONS_COVERED: 'Tutte le attrazioni principali',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Partenze regolari. Viaggi illimitati',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      ' Disponibilità Last Minute. Conferma immediata',
    MULTI_ROUTES: 'Itinerari multipli',
    HASSLE_FREE: 'Prenotazione semplice',
    FREQUENT_DEPARTURES: 'Partenze frequenti',
    ONBOARD_AMENITIES: 'I migliori servizi a bordo',
    FLEXI_TRAVEL: 'Viaggi flessibili su più percorsi',
    FLEXI_EXCHANGE_CANCEL: 'Cambi e cancellazioni flessibili',
    EXTRA_DISCOUNT: 'Sconti extra per giovani, anziani e famiglie',
    PREPAID: 'Comodità prepagata',
    EASY_ACTIVATION: 'Attivazione facile',
    INSTANT_CONNECTIVITY: 'Connettività istantanea e copertura globale',
    ROUND_TRIP: 'Trasferimenti di andata e ritorno',
    CULTURAL_EXPERIENCE: 'Esperienze culturali autentiche',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
    LUGGAGE_ASSISTANCE: 'Assistenza con i bagagli',
    TOP_ATTRACTIONS: 'Attrazioni principali incluse',
    FREQ_DEP_MULTI_ROUTE: 'Partenze frequenti su più percorsi',
    CHARGING: 'Stazione di ricarica',
    WIFI: 'Wi-Fi',
    FnB: 'Cibo e bevande',
    LUXURY: 'Esperienza di lusso',
    FOOD_DRINK: 'Cibo e bevande',
    PANAROMIC: 'Viste panoramiche sulle attrazioni principali',
    PANAROMIC_2: 'Viste panaromiche',
    PANAROMIC_3: 'Viste panoramiche a cielo aperto',
    BEVERAGES: 'Bevande a bordo',
    GOURMET: 'Cena gourmet',
    GOURMET_2: 'Bevande e cena gourmet',
    NIGHTTIME: 'Splendide vedute serali',
    ROMANTIC: 'Atmosfera romantica',
    TRANSFERS: 'Ritiro incluso',
    CERTIFIED_OP: 'Operazioni certificate',
    BIRD_EYE: 'Viste panoramiche garantite',
    MULTI_JUMP: 'Istruttori autorizzati',
    EXTREME_ADV: 'Esperienza fuori dagli schemi',
    PHOTO_OP: 'Opportunità di scattare foto sceniche',
    TOP_ATTRACTIONS_COVERED: 'Adatto alle famiglie',
    LOCAL_CULTURE: 'Punti di riferimento culturali',
    EXCLUSIVE_DISC: 'Approfondimenti',
    EFFICIENT_PUBLIC_TRANSIT: 'Trasporto pubblico efficiente',
    FREQUENT_SERVICE: 'Servizio frequente',
    PREBOOKING: 'Facile prenotazione anticipata',
    LOCAL_CULTURE_IMM: 'Scopri la cultura locale',
    DISCOVER_HIDDEN: 'Scopri luoghi nascosti',
    CITY_SIGHTSEEING: 'Scopri la cultura locale',
    OFFBEAT_ADV: 'Punti di riferimento storici',
    DRINK_DEALS: 'Ingresso garantito ai club/pub',
    OFFBEAT_EXP: 'Esperienza fuori dagli schemi',
    MULTIPLE_VARIETIES: 'Tour e degustazioni',
    HIDDEN_GEMS: 'Gemme nascoste e attrazioni fuori dagli schemi',
    EXPLORE_LOCAL: 'Esperienza culturale locale',
    CUSTOMIZED_TREATMENTS: 'Trattamenti personalizzati:',
    TRAINED_THERAPISTS: 'Terapisti qualificati',
    HOLISTIC_WELLNESS: 'Benessere olistico',
    FLEXIBLE_DURATION: 'Noleggio flessibile',
    MULTI_BOAT: 'Ampia scelta',
    SCENIC_ROUTES: 'Itinerari panoramici',
    HANDS_ON: 'Apprendimento pratico',
    CULTURAL_CULINARY: 'Approfondimenti culturali e culinari',
    EXPERT_HOSTS: 'Guide esperte',
    ADVENTURE_EXPERIENCE: 'Competenze ineguagliabili',
    EQUIPMENT: 'Adatto a chi è alle prime armi',
    SCENIC_FLYOVERS: 'Percorsi scenici',
    LIVE_COMMENTARY: 'Commenti dal vivo',
    BEST_AERIAL_VIEWS: "Le migliori viste dall'alto",
    SAFE_CERT_OP: 'Attività sicure e certificate',
    HANDPICKED: 'Tour e attività selezionate',
    EFFORTLESS: 'Facile pianificazione',
    EXPERT_GUIDES: "Guide professioniste per un'esperienza completa",
    ALL_ATTR_ONE_CARD: 'Tutte le attrazioni in una sola card',
    MULTI_CARD: 'Diverse opzioni',
    COST_EFF: 'Conveniente',
    EASY_BEST: 'Prenotazione semplice. Prezzi top',
    INSTANT_MOBILE: 'Conferma istantanea. Biglietti digitali',
    MULTI_TRANSPORT: 'Tante opzioni di trasporto',
    BEST_PRICES: 'I migliori prezzi',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Tutto',
    POPULAR_SUBCATEGORY: '{0}: di tendenza',
    TOP_CATEGORY: '{0}: il meglio',
    ATTRACTIONS: 'Attrazioni',
    ALL_SUBCATEGORY: '{0}: tutto',
    BROWSE_BY_CATEGORIES: 'Sfoglia per categoria',
    TICKETS_FROM: 'Biglietti a partire da',
    PRICE_LOW_HIGH: 'Prezzo (dal più basso al più alto)',
    PRICE_HIGH_LOW: 'Prezzo (dal più alto al più basso)',
    FILTERS: 'Filtri',
    RESET: 'Cancella',
    APPLY: 'Applica',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout utilizza i cookie per aiutarti a navigare meglio, un byte alla volta.',
    MOBILE: 'Usiamo cookie.',
    LEARN_MORE: 'Scopri di più.',
  },
  SHOW_UNAVAILABLE: 'Spettacolo non disponibile',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Novità in primo piano',
    ALL_NEWS: 'Tutte le novità',
    MORE_READS: 'Altre letture',
    LOAD_MORE: 'Carica altro',
    TRAILERS: 'Tutti i trailer',
    GET_YOUR_TICKETS: 'Acquista i biglietti',
    POPULAR_SHOWS: 'Spettacoli in voga',
    FEATURED: 'In evidenza',
    RECENT_NEWS: 'Novità',
    SHOW_MORE_ARTICLES: 'Mostra altri articoli',
    COLLAPSE_ALL: 'Riduci tutto',
    REVIEWS: 'Recensioni',
    SHOW_ALL_REVIEWS: 'Mostra tutte le recensioni',
    MAILER: {
      HEADING:
        'Le migliori offerte e novità sul teatro nella tua casella di posta',
      SUBHEADING: `Iscriviti alla nostra newsletter per ricevere le ultime notizie e le offerte più interessanti sugli spettacoli teatrali.`,
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: 'Recensioni su {0}',
    REVIEWS_COUNT: '{0} recensioni',
    AWESOME: 'Eccezionale',
    GOOD: 'Buono',
    AVERAGE: 'Medio',
    POOR: 'Scadente',
    TERRIBLE: 'Terribile',
    REVIEW_BY_HEADOUT: 'Ecco la recensione di Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Cosa dicono le persone',
    MOST_RELEVANT: 'Più pertinente',
    RATING_HIGH_TO_LOW: 'Prima le recensioni migliori',
    RATING_LOW_TO_HIGH: 'Prima le recensioni peggiori',
    CRITIC_REVIEWS: 'Recensioni della critica',
    USER_REVIEWS: 'Recensioni degli utenti',
    CONTRIBUTORS_REVIEW: 'Recensioni dei redattori',
  },
  HOHO: {
    HOHO: 'Biglietti Hop On Hop Off',
    BUS_ROUTES_DETAILS: 'Itinerari',
    TOUR_DETAILS: 'Dettagli del tour',
    ROUTES_SCHEDULES: 'Percorsi e orari',
    VALIDITY: 'Valido per 1 giorno',
    VALIDITY_NOTE:
      'La tua esperienza è valida per {0} giorno/i di calendario. Se prenoti il tuo biglietto per il 6 maggio 2023, sarà valido fino al 6 maggio 2023, alle 9:00 PM PST.',
    BESTSELLER: 'Il più venduto',
    SEE_ALL: 'Guarda tutto',
    TIMINGS: 'ORARI',
    FREQUENCY: 'FREQUENZA',
    DURATION: 'DURATA',
    STARTING_LOCATION: 'Partenza',
    CALENDAR_FOOTNOTE: '* Tutti i prezzi sono in {0}',
    GOT_IT: 'Capito',
    TOUR_TIMINGS: 'Orari',
    TOUR_FREQUENCY: 'Frequenza',
    SELECT_DATE: 'Select a date',
    SELECT_TOUR: 'Select Tour Type',
    VIEW_TOUR_DETAILS: 'View tour details',
    BUS_DETAILS: 'MORE DETAILS',
    VIEW_ROUTES: 'View all routes',
    BUS_ROUTES: 'BUS ROUTES',
    ATTRACTIONS_PREVIEW: 'Fastest way to view {0}+ top attractions including',
    ROUTES: 'Itinerari',
    COMBO_SUBTITLE: 'Risparmia di più con',
    COMBO_TITLE: 'Offerte combinate sul tour Hop-on Hop-off',
    COMBO_DWEB_TITLE:
      'Risparmia di più con le offerte combinate sul tuo tour Hop-on Hop-off',
    STOPS_AND_ATTRACTIONS: 'Fermate e attrazioni',
    HOP_ON_OFF_AT: 'Sali e scendi a qualsiasi di queste {0} fermate',
    TIMINGS_FREQUENCY: 'Orari e frequenza',
    TOUR_DURATION: 'Durata del tour',
    EVERY_X_MINS: 'Every {0}',
    VIEW_LOCATION: 'Guarda la posizione',
    BANNER_SUBTEXT:
      'Il modo più comodo e veloce per visitare tutte le principali attrazioni della città.',
    TOP_ATTRACTIONS: 'Attrazioni principali',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Prenotazione last minute',
        DESCRIPTION: 'Conferma istantanea sullo smartphone',
      },
      COST_EFF: {
        NAME: 'La massima convenienza',
        DESCRIPTION: 'Tante attrazioni, un solo biglietto',
      },
      DAILY_RIDES: {
        NAME: 'Tutte le corse che vuoi',
        DESCRIPTION: 'Scopri la città al tuo ritmo',
      },
      BOOK_RELAX: {
        NAME: 'Prenota e rilassati',
        DESCRIPTION: 'Scelto da {0} milioni di persone',
      },
    },
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Trasferimenti privati',
    SHARED_TRANSFERS: 'Trasferimenti condivisi',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Prenota online',
        DESCRIPTION:
          "Prenota i tuoi biglietti online per un'esperienza veloce e conveniente.",
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Conferma immediata',
        DESCRIPTION:
          'Ricevi una conferma immediata della prenotazione del tuo trasferimento aeroportuale.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Prelievo comodo',
        DESCRIPTION:
          'Evita il fastidio delle lunghe code perché il tuo veicolo di trasferimento ti aspetterà al punto di prelievo selezionato.',
      },
      DROP_OFF: {
        TITLE: 'Arrivo comodo',
        DESCRIPTION:
          'Raggiungi la tua destinazione in modo rapido e confortevole.',
      },
    },

    SHARED_TRANSFERS_IN: 'Trasferimenti condivisi a {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      "Un'opzione di trasporto confortevole ed economica per più passeggeri che viaggiano da o verso un aeroporto.",
    PRIVATE_TRANSFERS_IN: 'Trasferimenti privati a {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      'Un servizio di trasporto comodo e personalizzato per singoli o piccoli gruppi, che offre un viaggio comodo e diretto da e verso un aeroporto.',
    ANYWHERE_IN_THE_CITY: 'In qualsiasi punto della città',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Molteplici opzioni di veicoli',
      FREE_CANCELLATION: 'Cancellazione gratuita',
    },
    SEAMLESS_TRANSFERS:
      'Trasferimenti senza problemi e affidabili in tutto il mondo',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Scegli il trasferimento aeroportuale migliore per te',

    // New experiment (AT LP)
    EFFORT_LESS_AIRPORT_TRANSFERS:
      'Semplici trasferimenti aeroportuali a {0} in',
    BUSES: 'autobus',
    TRAINS: 'treno',
    PRIVATE_TAXIS: 'taxi',
    BUS_TRAIN: 'Bus/Treno',
    PRIVATE_TAXI: 'Taxi',

    FROM: 'Da',
    TO: 'A',
    SELECT_PICKUP: 'Partenza',

    SELECT_DROPOFF: 'Arrivo',
    ENTER_DESTINATION: 'Inserisci la destinazione',
    ENTER_PICKUP: 'Inserire il luogo di ritiro',
    PICKUP_DATE: 'Data prelievo',
    SELECT_DATE: 'Scegli data',
    PICKUP_TIME: 'Ora prelievo',
    SELECT_TIME: 'Scegli ora',
    GUESTS: 'Ospiti',
    GUEST: 'Ospite',
    ADD_GUESTS: 'Più ospiti',
    EXPLORE_TRANSFERS: 'Scopri i trasferimenti',
    COMBOS_AND_EXTRAS: 'Combinazioni e altro',

    YOUR_RIDE_DOORSTEP: 'Il tuo transfer privato',
    COMFORTABLE_RIDE:
      'Prenota un comodo taxi privato da e per i principali aeroporti di {0}',
    TRUSTED_DRIVERS: 'Autisti affidabili',
    RIDES_24_7: 'Disponibilità 24/7',
    FLIGHT_TRACKING: 'Tracciamento del volo',
    KNOW_MORE: 'Scopri di più',
    RESERVE_YOUR_RIDE: 'Prenota il transfer',
    TRANSFER_OPTIONS: 'Transfer disponibili per te',
    TRANSFERS_AVAILABLE_PLURAL: '{0} transfer disponibili',
    TRANSFERS_AVAILABLE_SINGULAR: '1 transfer disponibile',

    TRUSTED_PARTNERS: '35+ fidati partner, {0}',
    WORLDWIDE: 'globali',
    COMFORTABLE_RIDES: 'Corse comode',
    FREQUENT_DEPARTURES: 'Partenze frequenti',
    MULTIPLE_TRANSPORT_OPTIONS: 'Diverse opzioni disponibili',
    AND_MANY_MORE: 'E molti altri',

    ADD_PICKUP_LOCATION: 'Aggiungi luogo di partenza',
    ADD_DROPOFF_LOCATION: 'Aggiungi luogo di arrivo',
    SELECT_PICKUP_DATE_AND_TIME: 'Scegli data e ora di partenza',
    SELECT_A_DATE: 'Seleziona data',

    TRAIN_STATION: 'Stazione dei treni',
    BUS_STOP: 'Stazione dei bus',

    ADD_RETURN: 'Andata e ritorno?',
    HEADS_UP: 'Attenzione!',
    ADDED_RETURN_TRIP: 'Hai aggiunto un ritorno',
    RETURN_NOTE:
      'Ti mostreremo i dettagli del viaggio di ritorno nei prossimi passaggi',
    OKAY_I_UNDERSTAND: 'OK, ho capito',

    SERVING_GUESTS: 'Più di {0} in oltre {1} del mondo',
    GUESTS_COUNT: '220.000 viaggiatori',
    CITIES_COUNT: '55 città',
    PARNTER_WITH_BEST:
      "Collaboriamo solo con i migliori, per assicurarti un'esperienza indimenticabile. Ai dettagli ci pensiamo noi: tu dovrai solo approfittare del viaggio.",
  },
  PC_EXP: {
    SHOW_INCL: 'Inclusioni e informazioni importanti',
    CLEAR: 'Annulla',
    ALL_EXPERIENCES: 'Tutte le esperienze',
    FILTER_BY_CATEGORIES: 'Filtra per categoria',
    CATEGORIES: 'Categorie',
    COMBOS: {
      HEADING:
        'Le cose belle vengono sempre in coppia. Come le nostre offerte combinate.',
      DESCRIPTOR_1: 'Offerte convenienti',
      DESCRIPTOR_2: 'Pianifica al meglio il tuo viaggio',
    },
  },
  TOP: 'Il meglio di: {0}',
  VIEW_CALENDAR: 'Vedi il calendario',
  SHOWS_CALENDAR: 'Calendario degli spettacoli',
  IN: 'en',
  SEATS: 'Posti',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Guida ai contenuti',
    QUICK_INFORMATION: 'Informazioni rapide',
    PEAK: 'di punta',
    OFF_PEAK: 'non di punta',
    ADDRESS: 'INDIRIZZO',
    RECOMMENDED_DURATION: 'DURATA CONSIGLIATA',
    VISITORS_PER_YEAR: "VISITATORI ALL'ANNO",
    NUMBER_OF_ENTRANCES: 'NUMERO DI INGRESSI',
    EXPECTED_WAIT_TIME_STANDARD: 'TEMPO DI ATTESA PREVISTO - STANDARD',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE:
      'TEMPO DI ATTESA PREVISTO - SALTA LA CODA',
    UNESCO_YEAR: "ENTRATA NELL'UNESCO",
    ARCHITECTURE_STYLE: 'STILE ARCHITETTONICO',
    TIMINGS: 'Orari',
    SIZE_HEIGHT: 'DIMENSIONE/ALTEZZA',
    TICKETS: 'BIGLIETTI',
    FUN_FACTS: 'Curiosità divertenti',
    DID_YOU_KNOW: 'Lo sapevi?',
    MORE_INTERESTING_FACTS: 'Altri fatti interessanti',
    PLAN_YOUR_VISIT: 'Pianifica la tua visita',
    ALSO_KNOWN_AS: 'Conosciuto anche come',
    FOUNDED_ON: 'Fondato nel',
    FOUNDED_BY: 'Trovato da',
    FROM: 'A partire da',
    CLOSED_TODAY: 'Chiuso oggi',
    TODAY: 'Oggi',
    CLOSED: 'Chiuso',
    OPEN: 'Aprire',
    LAST_ADMISSION: 'Ultimo Ingresso',
    DAYS: 'Giorni',
    BEST_TIME_TO_VISIT: 'Miglior periodo per visitare',
    WEEKDAY_VS_WEEKEND: 'Giorno feriale vs Fine settimana',
    PEAK_VS_LOW_SEASON: 'Alta stagione vs Bassa stagione',
    PLEASANT: 'Gradevole',
    CROWDED: 'Affollato',
    VERY_CROWDED: 'Molto affollato',
    LOW_SEASON: 'Bassa stagione',
    MID_SEASON: 'Stagione media',
    PEAK_SEASON: 'Alta stagione',
    TO: 'AL',
    TO_LOWER: 'al',
    LAST_ENTRY: 'ultimo ingresso',
    SUBATTRACTIONS: 'Sotto-Attrazioni',
    INCLUDED_WITH_TICKETS: 'Incluso con i biglietti per {0}',
    INCLUDED_WITH_SOME_TICKETS: 'Incluso con alcuni biglietti per {0}',
    EXPLORE_ALL_POI_TICKETS: 'Scopri i biglietti e i tour per {0} & {1}',
    OPERATING_HOURS: 'Orari',
    SEE_MORE: 'Scopri di più',
    MORE_INSIGHTS: 'Altre informazioni',
    SELECT_YOUR_EXPERIENCE: 'Seleziona la tua esperienza',
  },
  OFF_PERCENT: '{0}% di sconto',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Mappa dei posti',
    CAPACITY: '{0} posti',
    WHATS_ON: 'In scena',
    CATEGORIES: 'Categorie',
  },
  NEXT: 'Continua',
  PREVIOUS: 'Precedente',
  ITINERARY: {
    TAB: 'Itinerario',
    HEADING: 'Il tuo itinerario',
    VIEW_ITINERARY: "Vedi l'itinerario",
    VIEW_DETAILS: 'Dettagli',
    PASSES_BY_SECTION_HEADING: 'Passa per',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'In primo piano',
      NEARBY_THINGS_TO_DO: 'Cosa fare nelle vicinanze',
      THINGS_TO_DO: 'Cosa fare',
    },
    STOP_CARD: {
      TITLE: {
        START: 'INIZIO',
        END: 'FINE',
        STARTING_POINT: 'INIZIO',
        STOP: 'FERMATA',
        ENDING_POINT: 'FINE',
        PASSING_BY: 'PERCORSO',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} punti di partenza disponibili',
        END: '{0} punti di arrivo disponibili',
      },
    },
    GET_DIRECTION: 'Come arrivare',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} ore {1} minuti',
        WITHOUT_HOURS: '{0} minuti',
        WITHOUT_MINS: '{0} ore',
      },
      ATTRACTIONS_COUNT: '{0} attrazioni',
      ACTIVITIES_COUNT: '{0} attività',
      TOTAL_DURATION: 'Durata',
      FREQUENCY: 'Frequenza',
      FIRST_DEPARTURE: 'Prima partenza',
      LAST_DEPARTURE: 'Ultima partenza',
      FIRST_DEPARTURE_TIME: 'Orario prima partenza',
      LAST_DEPARTURE_TIME: 'Orario ultima partenza',
      MODE_OF_TRANSPORT: 'Mezzo di trasporto',
      FOOD_AND_DRINKS: 'Cibo e bevande',
    },
    WALK_DURATION: '{0} a piedi',
    MORE: 'e {0} ancora',
    TIMELINE_VIEW: 'Orari',
    MAP_VIEW: 'Mappa',
    MAP_OVERLAY: 'Usa CTRL/⌘ + il cursore per spostarti',
    VIEW_EXPERIENCE_MAPPED_OUT: 'Guarda la tua esperienza sulla mappa.',
    OPEN_MAP_VIEW: 'Apri la mappa',
    START_POINT_SAME_AS_END_POINT:
      'Il punto di arrivo sarà lo stesso del punto di partenza',
  },
  CRUISES: {
    BANNER_HEADING: 'Scopri {0} in crociera: pasti, bevande e relax',
    FILTERS: {
      ALL: 'Tutte',
      SIGHTSEEING: 'Turistiche',
      LUNCH: 'Con pranzo',
      DINNER: 'Con cena',
      COMBOS: 'Combinazioni',
    },
    MAP_OVERLAY: 'Clicca o tocca per esplorare la mappa',
    SIGHTS_COVERED: 'Cosa vedrai',
    MENU: 'Menu',
    BOARD_AT: 'Imbarco: {0}',
    BOARDING_POINTS_AVAILABLE: 'Numero di punti di imbarco: {0}',
    VIEW_POPULAR_SIGHTS: 'Ammira attrazioni come {0} {1}',
    X_BOARDING_POINTS: '{0} punti di imbarco',
    BOARDING_POINT: 'Punto di imbarco',
    BOARDING_POINTS: 'Punti di imbarco',
    LANDMARKS: 'Attrazioni',
    GET_DIRECTIONS: 'Indicazioni',
    FOOD_MENU: 'Il menù',
    X_PAGE: '{0} pagine',
    X_PAGES: '{0} pagine',
    MORE: '+{0} altri',
    PDF: {
      ZOOM_IN: 'Ingrandisci',
      ZOOM_OUT: 'Riduci',
      FIT_TO_WIDTH: 'Adatta alla larghezza',
      RESET_ZOOM: 'Reimposta zoom',
    },
    COMBO_HEADING: 'Scopri di più e risparmia: offerte combinate e city card',
  },
  CUSTOM_CTA_EXPERIMENT_TEXT: 'Prenota',

  FLEXIBLE_CANCELLATION: {
    TOOLTIP_TEXT:
      'Se cancelli la tua esperienza con 24 ore di anticipo, riceverai un rimborso completo (al netto di una piccola commissione).',
    KNOW_MORE: 'Scopri di più',
    FULL_REFUND: 'Rimborso completo',
    INSTANT: 'Operazione immediata',
    NO_QUESTIONS: 'Nessuna domanda',
    TNC: 'Termini e condizioni',
    ELIGIBILITY:
      'Idoneità: la cancellazione flessibile deve essere selezionata e acquistata al momento della prenotazione.',
    CANCELLATION_DEADLINE:
      "Termine di cancellazione: la prenotazione può essere cancellata fino a 24 ore prima dell'inizio dell'esperienza.",
    REFUND_AMOUNT:
      "Importo del rimborso: riceverai un rimborso dell'importo della prenotazione originariamente pagato (meno la tassa di protezione per la cancellazione).",
    NON_TRANSFERABLE: 'Non trasferibile: vale solo per questa prenotazione.',
    GUIDELINES:
      "Linee guida: il piano si annulla se l'ospite riscatta o utilizza una parte del biglietto prima della cancellazione. In questi casi si applicano le politiche di cancellazione standard e non è previsto alcun rimborso aggiuntivo.",
  },
  TRUST_TOOLTIP_HEADER: 'Come raccogliamo le recensioni?',
  TRUST_TOOLTIP_CONTENT:
    'Le recensioni sono state scritte da clienti reali, che hanno prenotato la loro esperienza su Headout.',
  REVIEW_SECTION_HEADER: 'Cosa dicono i nostri clienti',
  TRUST_VB_TAG: 'Prenotazione verificata',
  SNAPSHOTS_SECTION_HEADER: 'Le istantanee dei nostri ospiti',
};
export default it;
