const nl = {
  AUDIO_GUIDE: {
    BANNER: 'Gratis audiotour',
    PRODUCT_SUFFIX: 'met Audiotour',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Geautoriseerde & betrouwbare partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Geautoriseerde verkooppartner',
    SUB_TEXT:
      'Authentieke ervaringen geleverd door geverifieerde en betrouwbare partners.',
  },
  AVAILABLE: 'Beschikbaar',
  BANNER_CTA: 'Koop kaartjes',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout is een merk vertrouwd door miljoenen gasten wereldwijd dat een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten.',
    NON_PARTNERED_SENSITIVE:
      'Headout is een merk vertrouwd door miljoenen gasten wereldwijd dat een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten. Dit is niet de website van de locatie.',
    PARTNERED_NON_SENSITIVE:
      'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biede van de beste ervaringen om van deze attractie te genieten.',
    PARTNERED_SENSITIVE:
      'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten. Dit is niet de website van de locatie.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten.',
  BOOK_NOW_CTA: 'Reserveer nu',
  BUY_TICKETS_CTA: 'Koop kaartjes',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Je annuleert deze tickets tot {0} uur voor de belevenis begint en krijgt een volledige terugbetaling.',
    CANCELLABLE_ANYTIME:
      'Gratis annulering op elk moment voor het begin van uw ervaring',
    CANCELLABLE_DAYS:
      'Je kunt deze tickets tot {0} dagen voor het begin van de ervaring annuleren en een volledige terugbetaling krijgen.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Deze tickets kunnen niet geannuleerd worden. Ze zijn echter voor een langere periode geldig.',
    HEADING: 'Wijzigingsbeleid',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Deze tickets kunnen niet geannuleerd worden. Ze kunnen echter verschoven worden tot {0} uur voor de belevenis begint.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Deze tickets kunnen niet geannuleerd of verschoven worden.',
    VALID_UNTIL_DATE:
      'Deze tickets kunnen niet geannuleerd worden. Je kunt ze echter op elk moment gebruiken tot {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Deze tickets kunnen niet geannuleerd worden. Je kunt ze echter op elk moment binnen de komende {0} dagen gebruiken.',
    VALID_WITHIN_NEXT_MONTHS:
      'Deze tickets kunnen niet geannuleerd worden. Je kunt ze echter op elk moment binnen de komende {0} maanden gebruiken.',
  },
  CANCELLATION_POLICY_HEADING: 'Annuleringsbeleid',
  CASHBACK: '{0}% cashback',
  CASHBACK_INFO:
    'Je krijgt <strong>{0}%</strong> cashback wanneer uw deze ervaring kiest. Je cashback zal automatisch worden bijgeschreven op je Headout account en kan worden gebruikt voor elke toekomstige reservering.',
  CATEGORY_SLIDER_HEADING: 'Bezoekers die deze show boekten, bekeken ook',
  CHECK_AVAIL: 'Controleer beschikbaarheid',
  CITY_PAGE: {
    BANNER_TITLE: 'Ervaar het beste van',
    TOP_ATTRACTIONS: 'Topbezienswaardigheden',
    GO_BEYOND: 'Uitstapjes van {0}',
    ALL_DAY_TRIPS: 'Alle dagtrips',
    CITIES_NEARBY: 'Steden in de buurt',
    POPULAR_CATEGORIES: 'Populaire categorieën',
    GO_TO_GUIDE: 'Jouw {0} gids',
    VIEW_TRAVEL_GUIDE: 'Reisgids bekijken',
    EXPLORE: 'Ontdek {0}',
    GUIDE_SUBHEADING:
      'Bezienswaardigheden in {0} ontdekken is nu makkelijker dan ooit! Onze {0} reisgids bevat alles wat je moet weten over de stad, van culinaire hotspots en accommodatie tot routebeschrijvingen naar populaire trekpleisters en meer!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Algemeen',
      WHERE_TO_EAT: 'Eten',
      WHERE_TO_STAY: 'Verblijf',
      THINGS_TO_DO: 'Activiteiten',
      WEATHER: 'Beste tijd voor een bezoek',
      NEIGHBOURHOODS: 'Omgeving',
      TRANSPORTATION: 'Vervoer',
      TRIP_PLANNER: 'Reisplan',
      FAMILY_TRAVEL: 'Reizen met kinderen',
      TRAVEL_TIPS: 'Reistips',
      SHOPPING: 'Winkelen',
      ART_AND_CULTURE: 'Kunst en cultuur',
    },
    MAILER: {
      HEADING: 'Inspiraties voor je reis naar {0} rechtstreeks in je inbox',
      SUBHEADING:
        'Topdingen om te doen, budgethacks, openbaar vervoer, beste restaurants & hotels, cultuur tips & veel meer!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Visumvereisten, geld wisselen, tijdzoneverschillen en meer - belangrijke informatie voor een vlotte aankomst en een aangenaam verblijf.',
    WHERE_TO_EAT:
      'Culinaire hoogstandjes, heerlijke smaken en lokale specialiteiten worden op iedere hoek van de straat aangeboden in {0}.',
    WHERE_TO_STAY:
      'Hier vind je de beste accommodatie voor een comfortabel en onvergetelijk verblijf in {0}.',
    THINGS_TO_DO:
      'Spannende activiteiten en attracties voor jong en oud zorgen voor een onvergetelijke tijd.',
    WEATHER:
      'Hier vind je belangrijke informatie voor je reisplanning, want {0} heeft het hele jaar door magische ervaringen te bieden.',
    NEIGHBOURHOODS:
      'Ontdek de diverse, levendige buurten die {0} zo speciaal maken.',
    TRANSPORTATION:
      'Met het openbaar vervoer in {0} kun je snel en gemakkelijk van de ene attractie naar de andere.',
    TRIP_PLANNER:
      'Met onze zorgvuldig geselecteerde routes haal je het meeste uit je tijd in {0} en geniet je optimaal van elk moment.',
    FAMILY_TRAVEL:
      'Gezinsvriendelijke avonturen wachten op je met tal van attracties, parken en entertainment voor alle leeftijden.',
    TRAVEL_TIPS:
      'Insidertips en reishacks zorgen voor een uitzonderlijke reis naar {0}.',
    SHOPPING:
      'Een paradijs voor shoppers met boetiekjes, markten en winkelcentra - van plaatselijke kunstnijverheid tot luxe mode.',
    ART_AND_CULTURE:
      'Verken de rijke kunst- en cultuurscène van {0} - van fascinerende musea tot levendige festivals.',
  },
  CLOSE: 'Sluit',
  COLLECTION_SLICE_HEADING: 'Topervaringen in {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Selecteer',
    SELECT_OPTION: 'Selecteer de gewenste optie',
    SELECT_TICKET: 'Selecteer je ticket',
  },
  COMPARE_ALL_DETAILS: 'Vergelijk Alle details',
  COVID19_ALERT: {
    KEY_TEXT: 'Update over COVID-19',
    LINK:
      'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT:
      'Jij bent onze prioriteit. Raadpleeg onze hulppagina voor de laatste updates over ons flexibele annuleringsbeleid',
  },
  CURRENCY: 'Valuta',
  CUSTOMER_REVIEW_HEADING: 'Beoordelingen',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audiogids',
    DURATION: 'Duur: {0}',
    EXTENDED_VALIDITY: 'Verlengde geldigheid',
    FLEXIBLE_DURATION: 'Flexibele duur',
    FREE_CANCELLATION: 'Gratis annuleren',
    GUIDED_TOUR: 'Rondleiding',
    HOTEL_PICKUP: 'Ophalen bij het Hotel',
    INSTANT_CONFIRMATION: 'Directe bevestiging',
    MEALS_INCLUDED: 'Inclusief maaltijden',
    MOBILE_TICKET: 'Tickets op je mobiel',
    SKIP_THE_LINE: 'Sla de rij over en bespaar tijd',
    TRANSFERS: 'Transfers inbegrepen',
  },
  DURATION: 'Looptijd',
  EARLIEST_AVAILABILITY: 'Vroegste beschikbaarheid',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Vul hier je e-mailadres in',
    SIGN_UP: 'Aanmelden',
    THANK_YOU: 'Bedankt!',
    SUBSCRIBED_MSG: 'Je bent nu ingeschreven',
    ERROR_MSG: 'Geef een geldig e-mailadres op',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Broadway Theater Tickets',
    },
    LTT: {
      MB_NAME: 'London Theater Tickets',
    },
  },
  EXCLUSIONS: 'Niet inbegrepen',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '10 miljoen +',
    HEADING_RATING: '4.4/5',
    HEADING_SAFE: '100% Veilig',
    HEADING_SUPPORT: '24/7 Ondersteuning',
    SUB_HEADING_CUSTOMER: 'Meer dan 10.000 tevreden bezoekers',
    SUB_HEADING_RATING:
      'Meer dan 5000 geverifieerde beoordelingen met een uitstekende score van 90%.',
    SUB_HEADING_SAFE: 'Alle buitenactiviteiten zijn 100% veilig',
    SUB_HEADING_SUPPORT:
      'Heb je vragen? Chat altijd en overal live met lokale experts',
  },
  FLEXIBLE: 'Flexibel',
  FOOTER: {
    CALL_US: 'Bel ons',
    CHAT_WITH_US: 'Chat met ons',
    COMPANY_DETAILS: 'Bedrijfsgegevens',
    DISCLAIMER:
      'Deze website is niet de officiële website van <attraction>. Hij wordt gerund door Headout dat samenwerkt met attracties en touroperators om met één druk op de knop ongelooflijke ervaringen aan te bieden.',
    EMAIL_US: 'Email ons',
    GET_HELP: 'Krijg hulp',
    LEGAL: 'Wettelijk',
    PRIVACY_POLICY: 'Privacybeleid',
    QUICK_LINKS: 'Snelle links',
    TERMS_AND_CONDITIONS: 'Algemene voorwaarden',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Met ',
    ALL_OVER_THE: ' gemaakt over de hele ',
  },
  FREE_CANCELLATION: 'Gratis annuleren',
  FREE_CANCELLATION_SUBTEXT: 'Je kunt tot 72 uur van tevoren annuleren.',
  FROM: 'Vanaf',
  GET_CASHBACK: 'Ontvang {0}% cashback',
  GROUP_TICKETS: 'Groepskaartjes',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '18+ Miljoen tevreden klanten',
    SUB_TEXT: 'Je tevredenheid is onze prioriteit. Sluit je bij ons aan.',
  },
  HELP_CENTER: {
    MAIN_TEXT: '24/7 ondersteuning',
    SUB_TEXT: 'We staan 24 uur per dag voor je klaar.',
  },
  INCLUSIONS: 'Inclusief',
  LANGUAGE: 'Taal',
  LISTICLES: {
    KNOW_MORE: 'Lees meer',
    SEATING_CHART: 'Stoelenschema',
    WHY_BOOK_FROM_US: 'Waarom bij ons reserveren?',
  },
  MORE_DETAILS: 'Meer info',
  MORE_CURRENCIES: 'Meer valuta',
  NEW: 'NEW',
  NEW_ARRIVAL: 'Nieuw',
  NEXT_AVAILABLE: 'Weer beschikbaar: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout is een merk waarop 15 miljoen gasten vertrouwen en dat een gecureerde selectie van unieke ervaringen biedt. Dit is niet de website van de locatie.',
  NO_RESULT_FOUND: 'Geen resulaten gevonden',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR: 'Boek met flexibiliteit - geen datumselectie nodig',
  OPENING_DATE: 'Openingsdatum',
  OPENING_ON: 'Première op',
  OPENS: 'Opent',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten. Dit is niet de website van de locatie.',
  POPULARITY: 'Populariteit',
  POPULAR_CURRENCIES: 'Populaire valuta',
  PRICE: 'Prijs',
  PRICES_STARTING: 'Prijzen',
  PROMO_CODES: {
    APPLIED: 'TOEGEPAST',
    APPLY_CODE: 'PAS CODE TOE',
    DESCRIPTION: {
      ABSOLUTE: 'Krijg {0} korting',
      CAPPED: 'Krijg {0}% korting, tot {1}',
      PERCENTAGE: 'Krijg {0}% korting',
    },
    REMOVE: 'VERWIJDEREN',
    TOOL_TIP_INFO: 'Deze korting wordt toegepast tijdens het afrekenen',
  },
  RATINGS: '{0} Waarderingen',
  READ_MORE: 'Meer Info',
  READ_MORE_TEXT: 'Meer Info',
  READ_LESS: 'Toon minder',
  VIEW_DETAILS: 'Toon details',
  REOPENING: 'Heropening',
  REOPENING_DATE: 'Heropeningsdatum',
  REOPENING_ON: 'Terugkeer op',
  REOPENS: 'Heropent',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT:
        'De 2G voorschriften zijn van toepassing: toegang tot accommodaties, culturele instellingen, restaurants/bars en andere plekken is alleen mogelijk met een bewijs van volledige vaccinatie of eerdere besmetting. Een negatieve Covid-19 test is niet langer voldoende.',
    },
    AU_DESCRIPTION: {
      TEXT:
        'Bezoekers van 16 jaar en ouder moeten een COVID-19 vaccinatiebewijs of medische vrijstelling kunnen tonen.',
    },
    BANNER_CTA: 'Lees meer',
    BERLIN_DESCRIPTION: {
      TEXT:
        'Het 2G-reglement is van toepassing: alleen volledig gevaccineerde en herstelde bezoekers met een bewijs van genezing krijgen toegang. Bezoekers jonger dan 18 jaar of zij die om medische redenen niet gevaccineerd kunnen worden, dienen bij de ingang een negatief resultaat van de COVID-test te overleggen. Personen die om medische redenen niet gevaccineerd kunnen worden, moeten bij de ingang tevens hun onmogelijkheid tot vaccinatie aantonen aan de hand van een medisch certificaat.',
    },
    CTA_TEXT: 'Details omtrent veiligheid',
    DESCRIPTION_CTA: 'Meer weten.',
    EU_DESCRIPTION: {
      TEXT:
        'Vanaf 21 juli 2021 moeten alle bezoekers van 12 jaar en ouder een EU COVID Certificaat kunnen tonen.',
    },
    EU_HEADING: 'EU Covid-certificaat vereist',
    EU_PREFIX: 'Opmerking: ',
    EXPERIENCE_DESCRIPTION:
      'Deze ervaring is geverifieerd om te voldoen aan de beste veiligheidsnormen in overeenstemming met lokale voorschriften en de WHO',
    FLAG_TEXT: 'Beste veiligheid',
    GENERAL_DESCRIPTION:
      'Elke ervaring met deze badge is geverifieerd om te voldoen aan de beste veiligheidsnormen volgens de gezondheidsrichtlijnen van de lokale overheid.',
    HEADING: 'Beste veiligheidsnormen',
    IT_DESCRIPTION: {
      TEXT:
        'Vanaf 6 augustus 2021 moeten alle bezoekers van 11 jaar en ouder een Green Pass of EU COVID Certificaat kunnen tonen.',
    },
    IT_PREFIX: 'Opmerking: ',
    MOBILE_HEADING: 'Veilige ervaringen',
    MODAL: {
      BADGE_DESCRIPTION:
        'Deze badge bij een ervaring bevestigt dat de veiligheidsnormen zijn geverifieerd door ons',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Alle apparatuur, voertuigen en veelvuldig aangeraakte oppervlakken worden na elk gebruik ontsmet. Leun lekker achterover en geniet van de ervaring.',
          HEADING: 'Alle apparatuur en oppervlakken worden ontsmet',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Alle apparatuur die tijdens je ervaring beschikbaar is, wordt na elk gebruik grondig ontsmet. Altijd.',
          HEADING: 'Alle apparatuur en oppervlakken worden ontsmet',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Alle voertuigen die tijdens je ervaring beschikbaar zijn, worden na elk gebruik grondig ontsmet. Altijd.',
          HEADING: 'Alle voertuigen worden ontsmet',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Bij een veilige ervaring heb je gedurende je hele verblijf hier toegang tot zeep en sanitaire stations. We staan voor je klaar! ',
          HEADING: 'Zeep en sanitaire voorzieningen zijn overal beschikbaar',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Mondkapjes zijn verplicht voor alle gasten die deelnemen aan deze ervaring. Dit helpt iedereen een geweldige tijd te hebben met de hoogst mogelijke veiligheid.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Partners die zijn geverifieerd als "Veilige ervaring" volgen de lokale voorschriften met betrekking tot mondkapjes. Indien verplicht, dragen alle gasten en personeelsleden mondkapjes. Ze doen er alles aan om jouw comfort en veiligheid te garanderen.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid.',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Mondkapjes zijn verplicht voor alle gasten die deelnemen aan deze ervaring. Dit helpt iedereen een geweldige tijd te hebben met de hoogst mogelijke veiligheid.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Alle medewerkers van deze ervaring dragen mondkapjes om ervoor te zorgen dat je een plezierige ervaring hebt zonder zorgen.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid.',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. Om dit te garanderen, gelden er capaciteitsbeperkingen.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. Om dit te garanderen, gelden er capaciteitsbeperkingen. In hetzelfde licht zijn er geen grote groepen toegestaan',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. Om dit te garanderen, kunnen er capaciteitsbeperkingen en groepslimieten gelden. Haal opgelucht adem.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. In hetzelfde licht zijn er geen grote groepen toegestaan.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Bij alle gasten wordt aan het begin van de ervaring hun temperatuur gecontroleerd om de veiligheid voor iedereen te garanderen. Alle medewerkers worden meerdere keren per dag gecontroleerd op hoge temperaturen.',
          HEADING: 'Temperatuurcontroles',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Bij alle gasten wordt aan het begin van de ervaring hun temperatuur gecontroleerd om de veiligheid voor iedereen te garanderen.',
          HEADING: 'Temperatuurcontroles',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Alle medewerkers worden meerdere keren gecontroleerd op hoge temperaturen. Toegang voor medewerkers met een temperatuur boven de voorgeschreven limiet is niet toegestaan en ze worden gevraagd thuis te blijven om te herstellen.',
          HEADING: 'Temperatuurcontroles',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Het personeel dat tijdens de hele ervaring aanwezig is, is getraind volgens de richtlijnen van de WHO en uitgerust om professioneel met elke noodsituatie om te gaan',
          HEADING:
            'Het personeel is getraind om de richtlijnen van het WHO te volgen',
        },
      },
      HEADING: 'Veilige ervaringen',
      SUB_HEADING:
        'We werken samen met onze partners over de hele wereld om de beste veiligheidsnormen te implementeren volgens de WHO-richtlijnen. Alle huidige maatregelen zijn geverifieerd en hier weergegeven. Het is tijd om weer te genieten van de wereld om ons heen.',
    },
    NL_DESCRIPTION: {
      TEXT:
        'Bezoekers van 13 jaar en ouder zijn verplicht een COVID Certificaat (digitaal of geprint) te tonen waaruit blijkt dat je gevaccineerd, negatief getest, of onlangs hersteld bent van COVID-19. Het dragen van een gezichtsmasker is verplicht.',
    },
    SG_DESCRIPTION: {
      TEXT:
        'Vanaf 13 oktober 2021 mogen alleen volledig gevaccineerde bezoekers in groepen van 2 naar binnen. Je moet voor binnenkomst een bewijs van vaccinatiestatus, een recent negatief COVID-19 testresultaat, en/of een documenten ter bewijs van herstel laten zien.',
    },
    SHORT_HEADING: 'Beste veiligheidsnormen',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Jouw veiligheid is onze prioriteit',
    TEXT:
      'We hebben belangrijke stappen genomen om de hygiëne te verbeteren met behulp van ontsmettingsmiddelen en uitgebreide en regelmatige oppervlaktereiniging. Groepen worden ook gecontroleerd om opstoppingen te voorkomen.',
  },
  SAVE: 'Bespaar {0}%',
  SAVE_PERCENT: 'Bespaar {0}%',
  SAVE_UPTO: 'Bespaar tot',
  SAVE_UPTO_PERCENT: 'Bespaar tot {0}%',
  SEARCH: 'Zoeken',
  SEE_ALL: 'See All',
  SEE_MORE_SHOWS: 'Zie meer shows',
  SELECT_CITY: 'Kies stad',
  SELECT_SECTION: 'Tribune kiezen',
  SEE_ALL_PHOTOS: "Alle foto's weergeven",
  SHOW_CLOSED: 'Show gesloten',
  SHOW_LESS_TEXT: 'Toon minder',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Over Show',
    ABOUT_THEATRE: 'Over theater',
    ADDITIONAL_INFORMATION: 'Extra informatie',
    AGE_LIMIT: 'Leeftijdsgrens',
    AGE_SUITABILITY: 'Geschiktheid voor de leeftijd',
    ANSWER: ['A-'],
    BLOG_SHOW_PAGE: 'Blog Toon Pagina',
    BLOG_SUMMARY: 'Blog Samenvatting',
    BLOG_THEATRE_PAGE: 'Blog Theater Pagina',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Theater Zitplan',
    CANCELLATION_AND_REFUNDS: 'Annulering en terugbetaling',
    CANCELLATION_POLICY: 'Annuleringsbeleid',
    CAST_AND_CREW: 'Cast & Crew',
    CLOSING_DATE: 'Sluitingsdatum',
    CLOSING_DATE_SPECIAL_OFFER: 'Sluitingsdatum Speciale Aanbieding',
    DURATION: 'Duur',
    FACILITIES_AND_ACCESSIBILITY: 'Faciliteiten & Toegankelijkheid',
    FREQUENTLY_ASKED_QUESTIONS: 'FAQs',
    GETTING_THERE: 'Bereikbaarheid',
    GETTING_THERE_MAP_LINK: 'Erheen gaan Kaart Link',
    GOOGLE_MAP: 'Google Kaart',
    HIGHLIGHTS: 'Hoogtepunten',
    LISTICLE_SHOW_SUMMARY: 'Listicle Samenvatting voorstelling',
    LISTICLE_SHOW_WHY_WATCH:
      'Listicle Waarom moet je deze voorstelling gaan zien?',
    OPENING_DATE: 'Openingsdatum',
    QUESTION: ['Q-', 'V-'],
    SAFETY_BANNER: 'Veiligheidsbanier',
    SHOW_DETAILS: 'Toon Details',
    SHOW_TIMINGS: 'Voorstellingstijden',
    SHOW_TYPE: 'Toon Type',
    SPECIAL_OFFER: 'Speciale aanbieding',
    THE_STORY: 'Het Verhaal',
    THEATRE_ADDRESS: 'Theater Adres',
    THEATRE_CAPACITY: 'Capaciteit van het theater',
    THEATRE_NAME: 'Naam van het theater',
    TICKETS: 'Tickets',
    TICKETS_REDEMPTION: 'Tickets Aflossen',
    TOP_SONGS: 'Top Songs',
    YOUR_TICKETS: 'Je tickets',
    ABOUT_CONCERT: 'Het Concert',
    PROGRAM: 'Programma',
  },
  SORT_BY: 'Sorteer',
  THEATRE: 'Theater',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Theaters in de buurt',
    NOW_PLAYING: 'Huidige shows',
    PAST_SHOWS: 'Afgelopen shows',
    FIND_BEST_SEATS: 'Vind de beste plaatsen',
  },
  SPECIAL_OFFER: 'Speciale aanbieding',
  TICKET_CAN_BE_CANCELED:
    'Je kunt tot {hours} uur van tevoren annuleren voor een volledige terugbetaling.',
  TICKET_CANNOT_BE_CANCELED:
    'Dit ticket kan niet worden geannuleerd, maar kan op verzoek worden verplaatst',
  TICKETS: 'Kaartjes',
  TIMINGS: 'Tijdstippen',
  SPECIAL_PRODUCT_HEADING: 'Sterk aanbevolen',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Ervaren gidsen',
    ENGAGING_STORIES: 'Boeiende verhalen',
    TOP_RATED: 'Top beoordeeld',
  },
  GUIDED_TOUR_REVIEWS: [
    'Onze gids Angela was geweldig en had veel kennis van de locatie',
    'De gids beantwoordde graag vragen over de tour',
    'Onze gids was geweldig en ze gaf ons zelfs een geweldige lunchaanbeveling',
    'De organisatie en onze gids maakten de ervaring zeer aangenaam',
    'Veel leerzame inhoud, ik zal het zeker nog eens doen met mijn kinderen',
    'De tour was goed georganiseerd en had precies de juiste tijdsduur',
    'Goede gids en goede organisatie! Zal aanraden!!!',
    'De leuke weetjes van onze gids hielden ons allemaal bezig en geïnteresseerd',
    'De tour ging in een goed tempo en voelde niet gehaast',
    'Onze gids Maria wist plekken te bemachtigen voor ons beste uitkijkpunt',
    'Onze gids heeft ons bezoek meer verrijkt dan we zelf hadden kunnen doen',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Engels',
    SPANISH: 'Spaans',
    FRENCH: 'Frans',
    ITALIAN: 'Italiaans',
    GERMAN: 'Duits',
    PORTUGUESE: 'Portugees',
    NEDERLANDS: 'Nederlands',
    POLISH: 'Pools',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Tour beschikbaar in {0}',
  GUIDES_BANNER: 'Authentieke ervaringen met onze populaire gidsen.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Haal het meeste uit je reis met rondleidingen. Onze deskundige gidsen zijn je vrienden ter plaatse en vertellen je verhalen, insidertips en reisaanbevelingen..',
    'Bezoek een stad niet alleen, ervaar het ook!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Onze gasten zeggen',
  TODAY: 'Vandaag',
  TOMORROW: 'Morgen',
  TOUR_LIST_HEADING: 'Kies je ervaring',
  TOUR_LIST_SUB_HEADING:
    'Kies uit meerdere kaartjes, tours en combo-opties van geverifieerde operators',
  UGC: {
    FOLLOW: 'Volgen',
    FOLLOW_IG: 'Volg op Instagram',
    HEADING: 'POV: Zo ziet je volgende avontuur eruit',
    SUB_HEADING: 'Samengesteld met 💜 door Headout',
  },
  UNAVAILABLE: 'Niet beschikbaar',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Deze tickets zijn geldig voor een langere duur. De precieze details staan op het ticket.',
    UNTIL_DATE: 'Deze tickets zijn geldig tot {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Deze tickets zijn geldig gedurende {0} dagen vanaf de datum van aankoop.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Deze tickets zijn geldig voor {0} maanden vanaf de datum van aankoop.',
  },
  TABLE_OF_CONTENTS: 'Overzicht',
  VIEW_LESS: 'Bekijk minder',
  VIEW_MORE: 'Meer Info',
  WHY_TAKE_THIS_DAY_TRIP: 'Waarom kiezen voor dit uitje?',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Hoofdmenu',
    EXPLORE: 'Ontdekken',
    VISIT: 'Bezoeken',
    THINGS_TO_DO: 'Dingen te doen',
    CITY_ATTRACTIONS: '{0} Bezienswaardigheden',
    TOP_THINGS_TO_DO: 'Topactiviteiten',
    CITY_TOURS: '{0} Tours',
    CITY_GUIDE: ' Stadsgids',
    ATTRACTIONS: 'Attracties',
    CRUISES: 'Boottochten',
    THEMES: "Thema's",
    ABOUT: 'Over',
    TOURS: 'Tours',
    SKIP_THE_LINE_TOURS: 'Toegang zonder wachtrijen',
    GUIDED_TOURS: 'Rondleidingen met gids',
    NIGHT_TOURS: "Rondleidingen 's nachts",
    FOOD_TOURS: 'Food tours',
    HISTORY: 'Geschiedenis',
    ARCHITECTURE: 'Architectuur',
    DESIGN: 'Design',
    INSIDE: 'Binnen',
    COLLECTIONS: 'Verzamelingen',
    PAINTINGS: 'Schilderijen',
    ANIMALS_EXHIBITS: 'Dieren en tentoonstellingen',
    HABITATS: 'Habitats',
    CONSERVATION: 'Conservatie',
    PROGRAMMES: "Programma's",
    A2_SIGHTSEEING_CRUISES: 'Sightseeing Rondvaart',
    A2_DINNER_CRUISES: 'Rondvaart met Diner',
    A2_EVENING_CRUISES: 'Avond Rondvaart',
    A2_LUNCH_CRUISES: 'Rondvaart met Lunch',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Plan je bezoek',
    TIMINGS: 'Openingstijden',
    DIRECTIONS: 'Routebeschrijving',
    PARKING: 'Parkeren',
    ROUTES: 'Routes',
    REQUIREMENTS: 'Voorwaarden',
    LOCATION: 'Locatie',
    RULES: 'Regels',
    FAQs: 'FAQ',
    ENTRANCES: 'Ingangen',
    RESTAURANTS: 'Restaurants',
    FACTS: 'Feiten',
    TIPS: 'Tips',
    MAP: 'Plattegrond',
    RIDES: 'Attracties',
    SHOWS: 'Shows',
    DINING: 'Dineren',
    SHOPPING: 'Shoppen',
    EVENTS: 'Events',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Kerstmis',
    NEW_YEARS_EVE: 'Nieuwjaar',
    TRAVEL_GUIDE: 'Gids',
    TRIP_PLANNER: 'Reisplanner',
    ITINERARY: 'Reisprogramma',
    TRAVEL_TIPS: 'Reistips',
    WEATHER: 'Weer',
    BEST_TIME_TO_VISIT: 'Beste tijd voor een bezoek',
    JANUARY: 'Januari',
    FEBRUARY: 'Februari',
    MARCH: 'Maart',
    APRIL: 'April',
    MAY: 'Mei',
    JUNE: 'Juni',
    JULY: 'Juli',
    AUGUST: 'Augustus',
    SEPTEMBER: 'September',
    OCTOBER: 'Oktober',
    NOVEMBER: 'November',
    DECEMBER: 'December',
    WHERE_TO_EAT: 'Eten',
    WHERE_TO_STAY: 'Verblijfplaats',
    NEIGHBOURHOODS: 'Buurten',
    FAMILY_TRAVEL: 'Gezinsreizen',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivals en events',
  },
  WHY_WATCH: 'Why kijken',
  FIND_ON_MAP: 'Kaart',
  LTT_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      INSTANT_TICKETS: {
        NAME: 'Instant tickets',
        DESCRIPTION: 'Bevestiging rechtstreeks van de kassa.',
      },
      PRICES_LOVE: {
        NAME: `Geweldige prijzen`,
        DESCRIPTION: 'Scherpe prijzen voor niet te missen shows.',
      },
      CHOOSE_SEATS: {
        NAME: 'Kies je plaatsen',
        DESCRIPTION: 'Vind de beste plaatsen voor elke show.',
      },
      OFFICIAL_LTT: {
        NAME: 'Officiële London Theatre Tickets',
        DESCRIPTION: 'Boek snel en veilig bij ons.',
      },
    },
    YOUR_PICK: 'Jouw keuze',
    BROWSE_BY_CATEGORIES: 'Zoek per categorie',
    TOP_WEST_END_SHOWS: 'Top West End shows',
    LAST_MINUTE_TICKETS: 'Last-minutetickets',
    LOVED_BY_MILLIONS: 'Geliefd door miljoenen',
    TODAY: 'Vandaag',
    TOMORROW: 'Morgen',
    SEE_ALL: 'Toon alles',
    GRAB_YOUR_TICKETS: 'Koop nu je tickets',
  },
  TAG_NAME: {
    BALLET: 'Ballet',
    CABARET: 'Cabaret',
    CHRISTMAS: 'Kerstmis',
    CIRCUS: 'Circus',
    CLASSIC: 'Klassiek',
    COMEDY: 'Komedie',
    COMING_SOON: 'Binnenkort verwacht',
    CRITICS_CHOICE: "Critics' Choice",
    DANCE: 'Dans',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasie',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Meeslepend Theater',
    JUKEBOX: 'Jukebox',
    KIDS: 'Kinderen',
    MAGIC: 'Magie',
    MUSICALS: 'Musicals',
    NEW_ARRIVAL: 'Nieuw',
    OFF_WEST_END: 'Off West End',
    OLIVIER_WINNER: 'Oliver winnaar',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomimes',
    PLAYS: 'Toneel',
    ROMANCE: 'Romantiek',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Sterren op het podium',
    THEATRICAL_CONCERT: 'Theaterconcert',
    TRUE_STORY: 'Waargebeurd verhaal',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Oh oh! We hebben een probleem',
    MESSAGE: `Sorry! Alle ervaringen op deze datum zijn uitverkocht of niet beschikbaar. Maar we hebben er wel heel veel beschikbaar op andere datums. We vragen je wel om flexibel te zijn.`,
    CTA: 'Bekijk alle datums',
  },
  ALL_DATES: 'Alle datums',
  BREADCRUMBS: {
    HOME: 'Home',
    TRAVEL_GUIDE: 'Reisgids',
    THINGS_TO_DO: 'Belevenissen in {0}',
    SHOW_NAME_TICKETS: '{0} - Tickets',
    LTT_HOME: 'London Theatre Tickets',
    LTT_VENUE_PAGE_HOME: 'Theaters in London',
    BROADWAY_HOME: 'Broadway Show Tickets',
    BROADWAY_VENUE_PAGE_HOME: 'Broadway Theaters',
    VIENNA_CONCERT_HOME: 'Concerttickets Wenen',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Concertzalen in Wenen',
    ATTRACTIONS: 'Attracties',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing Rondvaart',
    A2_DINNER_CRUISES: 'Rondvaart met Diner',
    A2_EVENING_CRUISES: 'Avond Rondvaart',
    A2_LUNCH_CRUISES: 'Rondvaart met Lunch',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'London Theatre nieuws',
    BROADWAY_SHOW_NEWS: 'Broadway Show nieuws',
    NEWS_PAGE: 'Nieuwspagina',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Café',
    'Dedicated Parking': 'Parkeerplaatsen beschikbaar',
    Elevators: 'Lift',
    Lift: 'Lift',
    'Wheelchair Accessible': 'Rolstoeltoegankelijk',
    Cloakroom: 'Garderobe',
    'Air Conditioning': 'Airconditioning',
    WiFi: 'Wifi',
    Bar: 'Bar',
    'Water Fountain': 'Drinkfontein',
    Washrooms: 'Toiletten',
    Toilets: 'Toiletten',
    Binoculars: 'Operaglazen',
    'Adapted Toilets': 'Barrièrevrije toiletten',
    'Accessible Toilets': 'Barrièrevrije toiletten',
    'Assistive Listening System': 'Hoorhulpmiddelen',
    'Hearing Assistance': 'Gehoorapparaten',
    'Booster Cushions': 'Zitkussens voor kinderen',
    Shop: 'Winkel',
    'Souvenir Shop': 'Souvenirwinkel',
    'Guide Dogs': 'Geschikt voor blindengeleidehonden',
    'Baby Changing Facilities': "Verzorgingsruimte voor baby's",
    'Security Check': 'Veiligheidscontrole',
    Ramp: 'Helling',
    'Level Access': 'Gelijkvloerse toegang',
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Deskundige meertalige gidsen',
    STL: 'Snelle toegang',
    PERSONALIZED: 'Persoonlijke ervaring',
    LOCAL_FOOD: 'Ervaar de lokale keuken en cultuur',
    MULTILINGUAL_GUIDES: 'Meertalige gidsen',
    CULINARY_EXPERTS: 'Ontmoet de culinaire experts',
    SIGHTSEEING: 'Sightseeing & amusement aan boord',
    MULTILINGUAL_GT: 'Meertalige rondleidingen',
    MULTI_ROUTES: 'Meerdere routeopties',
    HASSLE_FREE: 'Probleemloos boeken',
    FREQUENT_DEPARTURES: 'Regelmatig vertrek',
    ONBOARD_AMENITIES: 'Beste voorzieningen aan boord',
    FLEXI_TRAVEL: 'Flexibel reizen via meerdere routes',
    FLEXI_EXCHANGE_CANCEL: 'Flexibel omruilen en annuleren',
    EXTRA_DISCOUNT: 'Extra kortingen voor jongeren, senioren & gezinnen',
    PREPAID: 'Prepaid gemak',
    EASY_ACTIVATION: 'Eenvoudig activeren',
    INSTANT_CONNECTIVITY: 'Directe verbinding met wereldwijde dekking',
    ROUND_TRIP: 'Retourtransfers',
    CULTURAL_EXPERIENCE: 'Authentieke culturele ervaringen',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout gebruikt cookies om je een betere gebruikerservaring te bieden.',
    MOBILE: 'Wij gebruiken cookies.',
    LEARN_MORE: 'Meer info.',
  },
  SHOW_UNAVAILABLE: 'Show niet beschikbaar',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Uitgelicht',
    ALL_NEWS: 'Alle nieuws',
    MORE_READS: 'Meer lezen',
    LOAD_MORE: 'Toon meer',
    TRAILERS: 'Alle trailers',
    GET_YOUR_TICKETS: 'Koop je tickets',
    POPULAR_SHOWS: 'Populaire shows',
  },
};
export default nl;
