const nl = {
  AUDIO_GUIDE: {
    BANNER: 'Gratis audiotour',
    PRODUCT_SUFFIX: 'met Audiotour',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Geautoriseerde & betrouwbare partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Geautoriseerde verkooppartner',
    SUB_TEXT:
      'Authentieke ervaringen geleverd door geverifieerde en betrouwbare partners.',
  },
  AVAILABLE: 'Beschikbaar',
  BANNER_CTA: 'Koop kaartjes',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout is een merk vertrouwd door miljoenen gasten wereldwijd dat een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten.',
    NON_PARTNERED_SENSITIVE:
      'Headout is een merk vertrouwd door miljoenen gasten wereldwijd dat een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten. Dit is niet de website van de locatie.',
    PARTNERED_NON_SENSITIVE:
      'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biede van de beste ervaringen om van deze attractie te genieten.',
    PARTNERED_SENSITIVE:
      'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten. Dit is niet de website van de locatie.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten.',
  BOOK_NOW_CTA: 'Reserveer nu',
  BUY_TICKETS_CTA: 'Koop kaartjes',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Je annuleert deze tickets tot {0} uur voor de belevenis begint en krijgt een volledige terugbetaling.',
    CANCELLABLE_ANYTIME:
      'Gratis annulering op elk moment voor het begin van uw ervaring',
    CANCELLABLE_DAYS:
      'Je kunt deze tickets tot {0} dagen voor het begin van de ervaring annuleren en een volledige terugbetaling krijgen.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Deze tickets kunnen niet geannuleerd worden. Ze zijn echter voor een langere periode geldig.',
    HEADING: 'Wijzigingsbeleid',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Deze tickets kunnen niet geannuleerd worden. Ze kunnen echter verschoven worden tot {0} uur voor de belevenis begint.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Deze tickets kunnen niet geannuleerd of verschoven worden.',
    VALID_UNTIL_DATE:
      'Deze tickets kunnen niet geannuleerd worden. Je kunt ze echter op elk moment gebruiken tot {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Deze tickets kunnen niet geannuleerd worden. Je kunt ze echter op elk moment binnen de komende {0} dagen gebruiken.',
    VALID_WITHIN_NEXT_MONTHS:
      'Deze tickets kunnen niet geannuleerd worden. Je kunt ze echter op elk moment binnen de komende {0} maanden gebruiken.',
  },
  CANCELLATION_POLICY_HEADING: 'Annuleringsbeleid',
  CASHBACK: '{0}% cashback',
  CASHBACK_INFO:
    'Je krijgt <strong>{0}%</strong> cashback wanneer uw deze ervaring kiest. Je cashback zal automatisch worden bijgeschreven op je Headout account en kan worden gebruikt voor elke toekomstige reservering.',
  CATEGORY_SLIDER_HEADING: 'Bezoekers die deze show boekten, bekeken ook',
  CHECK_AVAIL: 'Controleer beschikbaarheid',
  CITY_PAGE: {
    BANNER_TITLE: 'Ervaar het beste van',
    TOP_ATTRACTIONS: 'Topbezienswaardigheden',
    GO_BEYOND: 'Uitstapjes van {0}',
    ALL_DAY_TRIPS: 'Alle dagtrips',
    CITIES_NEARBY: 'Steden in de buurt',
    POPULAR_CATEGORIES: 'Populaire categorieën',
    GO_TO_GUIDE: 'Jouw {0} gids',
    VIEW_TRAVEL_GUIDE: 'Reisgids bekijken',
    EXPLORE: 'Ontdek {0}',
    GUIDE_SUBHEADING:
      '{0} ontdekken was nog nooit zo makkelijk! Onze {0} reisgids omvat alles wat je moet weten over de stad – de hapjes die je moet proeven, bezienswaardigheden en hoe je ze bereikt, waar je kunt verblijven en nog veel meer!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Algemeen',
      WHERE_TO_EAT: 'Eten',
      WHERE_TO_STAY: 'Verblijf',
      THINGS_TO_DO: 'Activiteiten',
      WEATHER: 'Beste tijd voor een bezoek',
      NEIGHBOURHOODS: 'Omgeving',
      TRANSPORTATION: 'Vervoer',
      TRIP_PLANNER: 'Reisplan',
      FAMILY_TRAVEL: 'Reizen met kinderen',
      TRAVEL_TIPS: 'Reistips',
      SHOPPING: 'Winkelen',
      ART_AND_CULTURE: 'Kunst en cultuur',
    },
    MAILER: {
      HEADING: 'Reisinspiratie voor {0} direct in je inbox',
      SUBHEADING:
        'Ontdek nieuwe steden met zorgvuldig samengestelde ervaringen, directe cashback, exclusieve deals en essentiële reistips!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Visumvereisten, geld wisselen, tijdzoneverschillen en meer - belangrijke informatie voor een vlotte aankomst en een aangenaam verblijf.',
    WHERE_TO_EAT:
      'Culinaire hoogstandjes, heerlijke smaken en lokale specialiteiten worden op iedere hoek van de straat aangeboden in {0}.',
    WHERE_TO_STAY:
      'Hier vind je de beste accommodatie voor een comfortabel en onvergetelijk verblijf in {0}.',
    THINGS_TO_DO:
      'Spannende activiteiten en attracties voor jong en oud zorgen voor een onvergetelijke tijd.',
    WEATHER:
      'Hier vind je belangrijke informatie voor je reisplanning, want {0} heeft het hele jaar door magische ervaringen te bieden.',
    NEIGHBOURHOODS:
      'Ontdek de diverse, levendige buurten die {0} zo speciaal maken.',
    TRANSPORTATION:
      'Met het openbaar vervoer in {0} kun je snel en gemakkelijk van de ene attractie naar de andere.',
    TRIP_PLANNER:
      'Met onze zorgvuldig geselecteerde routes haal je het meeste uit je tijd in {0} en geniet je optimaal van elk moment.',
    FAMILY_TRAVEL:
      'Gezinsvriendelijke avonturen wachten op je met tal van attracties, parken en entertainment voor alle leeftijden.',
    TRAVEL_TIPS:
      'Insidertips en reishacks zorgen voor een uitzonderlijke reis naar {0}.',
    SHOPPING:
      'Een paradijs voor shoppers met boetiekjes, markten en winkelcentra - van plaatselijke kunstnijverheid tot luxe mode.',
    ART_AND_CULTURE:
      'Verken de rijke kunst- en cultuurscène van {0} - van fascinerende musea tot levendige festivals.',
  },
  CLOSE: 'Sluit',
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'We gebruiken cookies en soortgelijke technologieën voor een aantal doeleinden, waaronder het verbeteren van je ervaring op onze site en voor advertenties,.',
    MANAGE_PREFERENCES: 'Instellingen',
    PREFERNCES_SAVED: 'Je instellingen zijn opgeslagen',
    ACCEPT: 'Oké',
    ALLOW_ALL: 'Alles toestaan',
    DENY_ALL: 'Alles weigeren',
    COOKIES: 'Cookies',
    HEADING: 'We hechten altijd waarde aan uw privacy',
    DESCRIPTION: `*   Cookies zijn kleine bestanden die door een website/platform op Uw computer, mobiele apparaat of een ander apparaat worden geplaatst en die onder andere de details van Uw surfgeschiedenis bevatten.
*   Wij gebruiken verschillende soorten cookies om Uw gebruik van Ons Platform bij te houden en bepaalde informatie op te slaan die ons verder helpt om U meer gepersonaliseerde diensten aan te bieden. Bepaalde cookies kunnen op Uw Apparaat worden geplaatst vanwege Uw gebruik van diensten die beschikbaar zijn op Ons Platform.
*   In grote lijnen gebruiken we hiervoor twee verschillende soorten technologieën:
    *   **Cookies of Browser Cookies.** het is een klein bestand dat automatisch op Uw Apparaat wordt geplaatst wanneer U toegang krijgt tot Ons Platform. U kunt Uw browser opdracht geven om alle Cookies te weigeren. In het geval dat U onze Cookies niet accepteert, is het mogelijk dat U sommige delen van Ons Platform niet kunt gebruiken.
    *   **Webbakens.** Ook wel clear gifs, pixeltags en single-pixel gifs genoemd, die worden toegevoegd aan verschillende onderdelen van Ons Platform en Onze e-mails, zodat we de activiteiten van Gebruikers kunnen volgen en begrijpen.
*   Deze Cookies die zijn opgeslagen op Uw Apparaat kunnen "permanente" of "sessiecookies" zijn. Permanente Cookies blijven op Uw Apparaat staan, zelfs wanneer U offline gaat, terwijl Sessiecookies automatisch worden verwijderd zodra U Uw webbrowser afsluit.
*   We gebruiken zowel sessiecookies als permanente cookies voor de hieronder beschreven doeleinden:
    *   Noodzakelijke / essentiële cookies
        *   _Type:_ Sessiecookies
        *   _Doel:_ Deze cookies zijn essentieel voor U om toegang te krijgen tot verschillende secties van het Platform en als deze niet toegestaan zijn, kan het zijn dat U geen toegang krijgt tot de diensten die beschikbaar zijn op het Platform. Deze cookies helpen ons verder om de Gebruikers te verifiëren en elke vorm van frauduleuze activiteiten op het Platform te voorkomen.
    *   Cookiesbeleid / Kennisgeving Acceptatie Cookies
        *   _Type:_ Persistente cookies
        *   _Doel:_ Deze cookies identificeren of gebruikers het gebruik van cookies hebben geaccepteerd.
    *   Functionaliteit Cookies
        *   _Type:_ Persistente cookies
        *   _Doel:_ Deze Cookies laten ons toe om keuzes te onthouden die U maakt wanneer U het Platform gebruikt, zoals het onthouden van Uw inloggegevens of taalvoorkeur. Het grotere doel van deze Cookies is om U een meer gepersonaliseerde ervaring te bieden telkens U het Platform gebruikt.

_Alle met een hoofdletter geschreven termen die hierboven worden gebruikt, worden gedefinieerd in het Privacybeleid. Raadpleeg voor een gedetailleerd begrip_ [_het Privacybeleid_](/privacy-policy/)`,
  },
  COLLECTION_SLICE_HEADING: 'Topervaringen in {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Selecteer',
    SELECT_PREFERENCE: 'Selecteer je voorkeur',
    SELECT_OPTION: 'Selecteer de gewenste optie',
    SELECT_TICKET: 'Selecteer je ticket',
  },
  COMPARE_ALL_DETAILS: 'Vergelijk Alle details',
  COVID19_ALERT: {
    KEY_TEXT: 'Update over COVID-19',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Jij bent onze prioriteit. Raadpleeg onze hulppagina voor de laatste updates over ons flexibele annuleringsbeleid',
  },
  CURRENCY: 'Valuta',
  CUSTOMER_REVIEW_HEADING: 'Beoordelingen',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audiogids',
    DURATION: 'Duur: {0}',
    EXTENDED_VALIDITY: 'Verlengde geldigheid',
    FLEXIBLE_DURATION: 'Flexibele duur',
    FREE_CANCELLATION: 'Gratis annuleren',
    GUIDED_TOUR: 'Rondleiding',
    HOTEL_PICKUP: 'Ophalen bij het Hotel',
    INSTANT_CONFIRMATION: 'Directe bevestiging',
    MEALS_INCLUDED: 'Inclusief maaltijden',
    MOBILE_TICKET: 'Tickets op je mobiel',
    SKIP_THE_LINE: 'Sla de rij over en bespaar tijd',
    TRANSFERS: 'Transfers inbegrepen',
  },
  DURATION: 'Looptijd',
  EARLIEST_AVAILABILITY: 'Vroegste beschikbaarheid',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Vul hier je e-mailadres in',
    SIGN_UP: 'Aanmelden',
    THANK_YOU: 'Bedankt!',
    SUBSCRIBED_MSG: 'Je bent nu ingeschreven',
    ERROR_MSG: 'Geef een geldig e-mailadres op',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Broadway Theater Tickets',
    },
    LTT: {
      MB_NAME: 'London Theater Tickets',
    },
  },
  EXCLUSIONS: 'Niet inbegrepen',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '10 miljoen +',
    HEADING_RATING: '4.4/5',
    HEADING_SAFE: '100% Veilig',
    HEADING_SUPPORT: '24/7 Ondersteuning',
    SUB_HEADING_CUSTOMER: 'Meer dan 10.000 tevreden bezoekers',
    SUB_HEADING_RATING:
      'Meer dan 5000 geverifieerde beoordelingen met een uitstekende score van 90%.',
    SUB_HEADING_SAFE: 'Alle buitenactiviteiten zijn 100% veilig',
    SUB_HEADING_SUPPORT:
      'Heb je vragen? Chat altijd en overal live met lokale experts',
  },
  FLEXIBLE: 'Flexibel',
  FOOTER: {
    CALL_US: 'Bel ons',
    CHAT_WITH_US: 'Chat met ons',
    COMPANY_DETAILS: 'Bedrijfsgegevens',
    INFORMATION: 'informatie',
    GMAPS_DISCLAIMER:
      'Alle schermafbeeldingen van plattegronden op deze pagina zijn afkomstig van Google in overeenstemming met fair use. Alle rechten op dergelijke schermafbeeldingen liggen bij het specifieke platform en het gebruik is uitsluitend bedoeld als informatie of advies.',
    DISCLAIMER:
      'Deze website is niet de officiële website van <attraction>. Hij wordt gerund door Headout dat samenwerkt met attracties en touroperators om met één druk op de knop ongelooflijke ervaringen aan te bieden.',
    EMAIL_US: 'Email ons',
    GET_HELP: 'Krijg hulp',
    LEGAL: 'Wettelijk',
    PRIVACY_POLICY: 'Privacybeleid',
    QUICK_LINKS: 'Snelle links',
    TERMS_AND_CONDITIONS: 'Algemene voorwaarden',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Met ',
    ALL_OVER_THE: ' gemaakt over de hele ',
    TERMS_OF_USAGE: 'Gebruikersvoorwaarden',
    GET_HELP_24_7: 'Ondersteuning',
    HELP_CENTER: 'Helpcentrum',
    COMPANY: 'Bedrijf',
    WE_ACCEPT: 'Betalingsopties',
    DOWNLOAD_HEADOUT: 'Download de Headout app',
    SCAN_CODES: 'Scan Codes',
    STAR_VERIFIED: 'Klik om je registratie voor S.T.A.R. te verifiëren.',
    OFFICIAL_TICKET_RETAILER: 'OFFICIËLE TICKETVERKOPER',
  },
  FREE_CANCELLATION: 'Gratis annuleren',
  FREE_CANCELLATION_SUBTEXT: 'Je kunt tot 72 uur van tevoren annuleren.',
  FROM: 'Vanaf',
  GET_CASHBACK: 'Ontvang {0}% cashback',
  GROUP_TICKETS: 'Groepskaartjes',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '20+ Miljoen tevreden klanten',
    SUB_TEXT: 'Je tevredenheid is onze prioriteit. Sluit je bij ons aan.',
  },
  HELP_CENTER: {
    MAIN_TEXT: '24/7 ondersteuning',
    SUB_TEXT: 'We staan 24 uur per dag voor je klaar.',
  },
  INCLUSIONS: 'Inclusief',
  LANGUAGE: 'Taal',
  LISTICLES: {
    KNOW_MORE: 'Lees meer',
    SEATING_CHART: 'Stoelenschema',
    WHY_BOOK_FROM_US: 'Waarom bij ons reserveren?',
  },
  MORE_DETAILS: 'Meer info',
  MORE_CURRENCIES: 'Meer valuta',
  NEW: 'Nieuw',
  NEW_ARRIVAL: 'Nieuw',
  NEXT_AVAILABLE: 'Weer beschikbaar: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout is een merk waarop 15 miljoen gasten vertrouwen en dat een gecureerde selectie van unieke ervaringen biedt. Dit is niet de website van de locatie.',
  NO_RESULT_FOUND: 'Geen resulaten gevonden',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR: 'Boek met flexibiliteit - geen datumselectie nodig',
  OPENING_DATE: 'Openingsdatum',
  OPENING_ON: 'Première op',
  OPENS: 'Opent',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout is een erkende en vertrouwde partner van de locatie die een gecureerde selectie biedt van de beste ervaringen om van deze attractie te genieten. Dit is niet de website van de locatie.',
  POPULARITY: 'Populariteit',
  POPULAR_CURRENCIES: 'Populaire valuta',
  PRICE: 'Prijs',
  PRICES_STARTING: 'Prijzen',
  PROMO_CODES: {
    APPLIED: 'TOEGEPAST',
    APPLY_CODE: 'PAS CODE TOE',
    DESCRIPTION: {
      ABSOLUTE: 'Krijg {0} korting',
      CAPPED: 'Krijg {0}% korting, tot {1}',
      PERCENTAGE: 'Krijg {0}% korting',
    },
    REMOVE: 'VERWIJDEREN',
    TOOL_TIP_INFO: 'Deze korting wordt toegepast tijdens het afrekenen',
  },
  RATINGS: '{0} Waarderingen',
  READ_MORE: 'Meer Info',
  READ_MORE_TEXT: 'Meer Info',
  READ_LESS: 'Toon minder',
  VIEW_DETAILS: 'Toon details',
  REOPENING: 'Heropening',
  REOPENING_DATE: 'Heropeningsdatum',
  REOPENING_ON: 'Terugkeer op',
  REOPENS: 'Heropent',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT: 'De 2G voorschriften zijn van toepassing: toegang tot accommodaties, culturele instellingen, restaurants/bars en andere plekken is alleen mogelijk met een bewijs van volledige vaccinatie of eerdere besmetting. Een negatieve Covid-19 test is niet langer voldoende.',
    },
    AU_DESCRIPTION: {
      TEXT: 'Bezoekers van 16 jaar en ouder moeten een COVID-19 vaccinatiebewijs of medische vrijstelling kunnen tonen.',
    },
    BANNER_CTA: 'Lees meer',
    BERLIN_DESCRIPTION: {
      TEXT: 'Het 2G-reglement is van toepassing: alleen volledig gevaccineerde en herstelde bezoekers met een bewijs van genezing krijgen toegang. Bezoekers jonger dan 18 jaar of zij die om medische redenen niet gevaccineerd kunnen worden, dienen bij de ingang een negatief resultaat van de COVID-test te overleggen. Personen die om medische redenen niet gevaccineerd kunnen worden, moeten bij de ingang tevens hun onmogelijkheid tot vaccinatie aantonen aan de hand van een medisch certificaat.',
    },
    CTA_TEXT: 'Details omtrent veiligheid',
    DESCRIPTION_CTA: 'Meer weten.',
    EU_DESCRIPTION: {
      TEXT: 'Vanaf 21 juli 2021 moeten alle bezoekers van 12 jaar en ouder een EU COVID Certificaat kunnen tonen.',
    },
    EU_HEADING: 'EU Covid-certificaat vereist',
    EU_PREFIX: 'Opmerking: ',
    EXPERIENCE_DESCRIPTION:
      'Deze ervaring is geverifieerd om te voldoen aan de beste veiligheidsnormen in overeenstemming met lokale voorschriften en de WHO',
    FLAG_TEXT: 'Beste veiligheid',
    GENERAL_DESCRIPTION:
      'Elke ervaring met deze badge is geverifieerd om te voldoen aan de beste veiligheidsnormen volgens de gezondheidsrichtlijnen van de lokale overheid.',
    HEADING: 'Beste veiligheidsnormen',
    IT_DESCRIPTION: {
      TEXT: 'Vanaf 6 augustus 2021 moeten alle bezoekers van 11 jaar en ouder een Green Pass of EU COVID Certificaat kunnen tonen.',
    },
    IT_PREFIX: 'Opmerking: ',
    MOBILE_HEADING: 'Veilige ervaringen',
    MODAL: {
      BADGE_DESCRIPTION:
        'Deze badge bij een ervaring bevestigt dat de veiligheidsnormen zijn geverifieerd door ons',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Alle apparatuur, voertuigen en veelvuldig aangeraakte oppervlakken worden na elk gebruik ontsmet. Leun lekker achterover en geniet van de ervaring.',
          HEADING: 'Alle apparatuur en oppervlakken worden ontsmet',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Alle apparatuur die tijdens je ervaring beschikbaar is, wordt na elk gebruik grondig ontsmet. Altijd.',
          HEADING: 'Alle apparatuur en oppervlakken worden ontsmet',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Alle voertuigen die tijdens je ervaring beschikbaar zijn, worden na elk gebruik grondig ontsmet. Altijd.',
          HEADING: 'Alle voertuigen worden ontsmet',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Bij een veilige ervaring heb je gedurende je hele verblijf hier toegang tot zeep en sanitaire stations. We staan voor je klaar! ',
          HEADING: 'Zeep en sanitaire voorzieningen zijn overal beschikbaar',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Mondkapjes zijn verplicht voor alle gasten die deelnemen aan deze ervaring. Dit helpt iedereen een geweldige tijd te hebben met de hoogst mogelijke veiligheid.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Partners die zijn geverifieerd als "Veilige ervaring" volgen de lokale voorschriften met betrekking tot mondkapjes. Indien verplicht, dragen alle gasten en personeelsleden mondkapjes. Ze doen er alles aan om jouw comfort en veiligheid te garanderen.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid.',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Mondkapjes zijn verplicht voor alle gasten die deelnemen aan deze ervaring. Dit helpt iedereen een geweldige tijd te hebben met de hoogst mogelijke veiligheid.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Alle medewerkers van deze ervaring dragen mondkapjes om ervoor te zorgen dat je een plezierige ervaring hebt zonder zorgen.',
          HEADING: 'Iedereen draagt mondkapjes voor jouw veiligheid.',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. Om dit te garanderen, gelden er capaciteitsbeperkingen.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. Om dit te garanderen, gelden er capaciteitsbeperkingen. In hetzelfde licht zijn er geen grote groepen toegestaan',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. Om dit te garanderen, kunnen er capaciteitsbeperkingen en groepslimieten gelden. Haal opgelucht adem.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Social distancing richtlijnen worden tijdens deze ervaring te allen tijde nageleefd. In hetzelfde licht zijn er geen grote groepen toegestaan.',
          HEADING: 'Social distancing richtlijnen worden gevolgd',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Bij alle gasten wordt aan het begin van de ervaring hun temperatuur gecontroleerd om de veiligheid voor iedereen te garanderen. Alle medewerkers worden meerdere keren per dag gecontroleerd op hoge temperaturen.',
          HEADING: 'Temperatuurcontroles',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Bij alle gasten wordt aan het begin van de ervaring hun temperatuur gecontroleerd om de veiligheid voor iedereen te garanderen.',
          HEADING: 'Temperatuurcontroles',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Alle medewerkers worden meerdere keren gecontroleerd op hoge temperaturen. Toegang voor medewerkers met een temperatuur boven de voorgeschreven limiet is niet toegestaan en ze worden gevraagd thuis te blijven om te herstellen.',
          HEADING: 'Temperatuurcontroles',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Het personeel dat tijdens de hele ervaring aanwezig is, is getraind volgens de richtlijnen van de WHO en uitgerust om professioneel met elke noodsituatie om te gaan',
          HEADING:
            'Het personeel is getraind om de richtlijnen van het WHO te volgen',
        },
      },
      HEADING: 'Veilige ervaringen',
      SUB_HEADING:
        'We werken samen met onze partners over de hele wereld om de beste veiligheidsnormen te implementeren volgens de WHO-richtlijnen. Alle huidige maatregelen zijn geverifieerd en hier weergegeven. Het is tijd om weer te genieten van de wereld om ons heen.',
    },
    NL_DESCRIPTION: {
      TEXT: 'Bezoekers van 13 jaar en ouder zijn verplicht een COVID Certificaat (digitaal of geprint) te tonen waaruit blijkt dat je gevaccineerd, negatief getest, of onlangs hersteld bent van COVID-19. Het dragen van een gezichtsmasker is verplicht.',
    },
    SG_DESCRIPTION: {
      TEXT: 'Vanaf 13 oktober 2021 mogen alleen volledig gevaccineerde bezoekers in groepen van 2 naar binnen. Je moet voor binnenkomst een bewijs van vaccinatiestatus, een recent negatief COVID-19 testresultaat, en/of een documenten ter bewijs van herstel laten zien.',
    },
    SHORT_HEADING: 'Beste veiligheidsnormen',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Jouw veiligheid is onze prioriteit',
    TEXT: 'We hebben belangrijke stappen genomen om de hygiëne te verbeteren met behulp van ontsmettingsmiddelen en uitgebreide en regelmatige oppervlaktereiniging. Groepen worden ook gecontroleerd om opstoppingen te voorkomen.',
  },
  SAVE: 'Bespaar {0}%',
  SAVE_PERCENT: 'Bespaar {0}%',
  SAVE_UPTO: 'Bespaar tot',
  SAVE_UPTO_PERCENT: 'Bespaar tot {0}%',
  SEARCH: 'Zoeken',
  SEE_ALL: 'Toon alles',
  SEE_MORE_SHOWS: 'Zie meer shows',
  SELECT_CITY: 'Kies stad',
  SELECT_SECTION: 'Tribune kiezen',
  SEE_ALL_PHOTOS: "Alle foto's weergeven",
  SHOW_CLOSED: 'Show gesloten',
  SHOW_LESS_TEXT: 'Toon minder',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Over Show',
    ABOUT_THEATRE: 'Over theater',
    ADDITIONAL_INFORMATION: 'Extra informatie',
    AGE_LIMIT: 'Leeftijdsgrens',
    AGE_SUITABILITY: 'Geschiktheid voor de leeftijd',
    ANSWER: ['A-'],
    BLOG_SHOW_PAGE: 'Blog Toon Pagina',
    BLOG_SUMMARY: 'Blog Samenvatting',
    BLOG_THEATRE_PAGE: 'Blog Theater Pagina',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Theater Zitplan',
    CANCELLATION_AND_REFUNDS: 'Annulering en terugbetaling',
    CANCELLATION_POLICY: 'Annuleringsbeleid',
    CAST_AND_CREW: 'Cast & Crew',
    CLOSING_DATE: 'Sluitingsdatum',
    CLOSING_DATE_SPECIAL_OFFER: 'Sluitingsdatum Speciale Aanbieding',
    DURATION: 'Duur',
    FACILITIES_AND_ACCESSIBILITY: 'Faciliteiten & Toegankelijkheid',
    FREQUENTLY_ASKED_QUESTIONS: 'FAQs',
    GETTING_THERE: 'Bereikbaarheid',
    GETTING_THERE_MAP_LINK: 'Erheen gaan Kaart Link',
    GOOGLE_MAP: 'Google Kaart',
    HIGHLIGHTS: 'Hoogtepunten',
    LISTICLE_SHOW_SUMMARY: 'Listicle Samenvatting voorstelling',
    LISTICLE_SHOW_WHY_WATCH:
      'Listicle Waarom moet je deze voorstelling gaan zien?',
    OPENING_DATE: 'Openingsdatum',
    QUESTION: ['Q-', 'V-'],
    SAFETY_BANNER: 'Veiligheidsbanier',
    SHOW_DETAILS: 'Toon Details',
    SHOW_TIMINGS: 'Voorstellingstijden',
    SHOW_TYPE: 'Toon Type',
    SPECIAL_OFFER: 'Speciale aanbieding',
    THE_STORY: 'Het Verhaal',
    THEATRE_ADDRESS: 'Theater Adres',
    THEATRE_CAPACITY: 'Capaciteit van het theater',
    THEATRE_NAME: 'Naam van het theater',
    TICKETS: 'Tickets',
    TICKETS_REDEMPTION: 'Tickets Aflossen',
    TOP_SONGS: 'Top Songs',
    YOUR_TICKETS: 'Je tickets',
    ABOUT_CONCERT: 'Het Concert',
    PROGRAM: 'Programma',
  },
  SORT_BY: 'Sorteer',
  THEATRE: 'Theater',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Theaters in de buurt',
    NOW_PLAYING: 'Huidige shows',
    UPCOMING_SHOWS: 'Aankomende shows',
    PAST_SHOWS: 'Afgelopen shows',
    FIND_BEST_SEATS: 'Vind de beste plaatsen',
  },
  SPECIAL_OFFER: 'Speciale aanbieding',
  TICKET_CAN_BE_CANCELED:
    'Je kunt tot {hours} uur van tevoren annuleren voor een volledige terugbetaling.',
  TICKET_CANNOT_BE_CANCELED:
    'Dit ticket kan niet worden geannuleerd, maar kan op verzoek worden verplaatst',
  TICKETS: 'Kaartjes',
  TIMINGS: 'Tijdstippen',
  SPECIAL_PRODUCT_HEADING: 'Sterk aanbevolen',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Ervaren gidsen',
    ENGAGING_STORIES: 'Boeiende verhalen',
    TOP_RATED: 'Top beoordeeld',
  },
  GUIDED_TOUR_REVIEWS: [
    'Onze gids Angela was geweldig en had veel kennis van de locatie',
    'De gids beantwoordde graag vragen over de tour',
    'Onze gids was geweldig en ze gaf ons zelfs een geweldige lunchaanbeveling',
    'De organisatie en onze gids maakten de ervaring zeer aangenaam',
    'Veel leerzame inhoud, ik zal het zeker nog eens doen met mijn kinderen',
    'De tour was goed georganiseerd en had precies de juiste tijdsduur',
    'Goede gids en goede organisatie! Zal aanraden!!!',
    'De leuke weetjes van onze gids hielden ons allemaal bezig en geïnteresseerd',
    'De tour ging in een goed tempo en voelde niet gehaast',
    'Onze gids Maria wist plekken te bemachtigen voor ons beste uitkijkpunt',
    'Onze gids heeft ons bezoek meer verrijkt dan we zelf hadden kunnen doen',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Engels',
    SPANISH: 'Spaans',
    FRENCH: 'Frans',
    ITALIAN: 'Italiaans',
    GERMAN: 'Duits',
    PORTUGUESE: 'Portugees',
    NEDERLANDS: 'Nederlands',
    POLISH: 'Pools',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Tour beschikbaar in {0}',
  GUIDES_BANNER: 'Authentieke ervaringen met onze populaire gidsen.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Haal het meeste uit je reis met rondleidingen. Onze deskundige gidsen zijn je vrienden ter plaatse en vertellen je verhalen, insidertips en reisaanbevelingen..',
    'Bezoek een stad niet alleen, ervaar het ook!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Onze gasten zeggen',
  TODAY: 'Vandaag',
  TOMORROW: 'Morgen',
  TOUR_LIST_HEADING: 'Kies je ervaring',
  TOUR_LIST_SUB_HEADING:
    'Kies uit meerdere kaartjes, tours en combo-opties van geverifieerde operators',
  UGC: {
    FOLLOW: 'Volgen',
    FOLLOW_IG: 'Volg op Instagram',
    HEADING: 'POV: Zo ziet je volgende avontuur eruit',
    SUB_HEADING: 'Samengesteld met 💜 door Headout',
  },
  UNAVAILABLE: 'Niet beschikbaar',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Deze tickets zijn geldig voor een langere duur. De precieze details staan op het ticket.',
    UNTIL_DATE: 'Deze tickets zijn geldig tot {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Deze tickets zijn geldig gedurende {0} dagen vanaf de datum van aankoop.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Deze tickets zijn geldig voor {0} maanden vanaf de datum van aankoop.',
  },
  TABLE_OF_CONTENTS: 'Overzicht',
  VIEW_LESS: 'Bekijk minder',
  VIEW_MORE: 'Meer Info',
  WHY_TAKE_THIS_DAY_TRIP: 'Waarom kiezen voor dit uitje?',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Hoofdmenu',
    EXPLORE: 'Ontdekken',
    VISIT: 'Bezoeken',
    THINGS_TO_DO: 'Dingen te doen',
    CITY_ATTRACTIONS: '{0} Bezienswaardigheden',
    TOP_THINGS_TO_DO: 'Topactiviteiten',
    CITY_TOURS: '{0} Tours',
    CITY_GUIDE: ' Stadsgids',
    ATTRACTIONS: 'Attracties',
    CRUISES: 'Boottochten',
    THEMES: "Thema's",
    ABOUT: 'Over',
    TOURS: 'Tours',
    SKIP_THE_LINE: 'Toegang zonder wachtrijen',
    GUIDED_TOURS: 'Rondleidingen met gids',
    NIGHT_TOURS: "Rondleidingen 's nachts",
    FOOD_TOURS: 'Food tours',
    HISTORY: 'Geschiedenis',
    ARCHITECTURE: 'Architectuur',
    DESIGN: 'Design',
    INSIDE: 'Binnen',
    COLLECTIONS: 'Verzamelingen',
    PAINTINGS: 'Schilderijen',
    ANIMALS_EXHIBITS: 'Dieren en tentoonstellingen',
    HABITATS: 'Habitats',
    CONSERVATION: 'Conservatie',
    PROGRAMMES: "Programma's",
    A2_SIGHTSEEING_CRUISES: 'Sightseeing Rondvaart',
    A2_DINNER_CRUISES: 'Rondvaart met Diner',
    A2_EVENING_CRUISES: 'Avond Rondvaart',
    A2_LUNCH_CRUISES: 'Rondvaart met Lunch',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Plan je bezoek',
    TIMINGS: 'Openingstijden',
    DIRECTIONS: 'Routebeschrijving',
    PARKING: 'Parkeren',
    ROUTES: 'Routes',
    REQUIREMENTS: 'Voorwaarden',
    LOCATION: 'Locatie',
    RULES: 'Regels',
    FAQs: 'FAQ',
    ENTRANCES: 'Ingangen',
    RESTAURANTS: 'Restaurants',
    FACTS: 'Feiten',
    TIPS: 'Tips',
    MAP: 'Plattegrond',
    RIDES: 'Attracties',
    SHOWS: 'Shows',
    DINING: 'Dineren',
    SHOPPING: 'Shoppen',
    EVENTS: 'Events',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Kerstmis',
    NEW_YEARS_EVE: 'Nieuwjaar',
    TRAVEL_GUIDE: 'Gids',
    TRIP_PLANNER: 'Reisplanner',
    ITINERARY: 'Reisprogramma',
    TRAVEL_TIPS: 'Reistips',
    WEATHER: 'Weer',
    BEST_TIME_TO_VISIT: 'Beste tijd voor een bezoek',
    JANUARY: 'Januari',
    FEBRUARY: 'Februari',
    MARCH: 'Maart',
    APRIL: 'April',
    MAY: 'Mei',
    JUNE: 'Juni',
    JULY: 'Juli',
    AUGUST: 'Augustus',
    SEPTEMBER: 'September',
    OCTOBER: 'Oktober',
    NOVEMBER: 'November',
    DECEMBER: 'December',
    WHERE_TO_EAT: 'Eten',
    WHERE_TO_STAY: 'Verblijfplaats',
    NEIGHBOURHOODS: 'Buurten',
    FAMILY_TRAVEL: 'Gezinsreizen',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivals en events',
  },
  WHY_WATCH: 'Waarom naar {0} kijken?',
  FIND_ON_MAP: 'Kaart',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Tickets aan de kassa',
        DESCRIPTION: 'Direct bevestigd op je telefoon',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Kies je zitplaatsen`,
        DESCRIPTION: 'Altijd de gewenste zitjes',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Exclusieve deals en kortingen',
        DESCRIPTION: `De beste shows aan lage prijzen`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Eenvoudig boeken',
        DESCRIPTION: '25 miljoen tevreden klanten',
      },
    },
    YOUR_PICK: 'Jouw keuze',
    BROWSE_BY_CATEGORIES: 'Zoek per categorie',
    TOP_WEST_END_SHOWS: 'Top West End shows',
    TOP_THEATRE_SHOWS: ' Topshows op {0}',
    TOP_SHOWS: 'Topshows',
    SEE_MORE_SHOWS: 'Toon {0} meer shows',
    LAST_MINUTE_TICKETS: 'Last-minutetickets',
    LOVED_BY_MILLIONS: 'Geliefd door miljoenen',
    TODAY: 'Vandaag',
    TOMORROW: 'Morgen',
    SEE_ALL: 'Toon alles',
    GRAB_YOUR_TICKETS: 'Koop nu je tickets',
  },
  TAG_NAME: {
    BALLET: 'Ballet',
    CABARET: 'Cabaret',
    CHRISTMAS: 'Kerstmis',
    CIRCUS: 'Circus',
    CLASSIC: 'Klassiek',
    COMEDY: 'Komedie',
    COMING_SOON: 'Binnenkort verwacht',
    CRITICS_CHOICE: "Critics' Choice",
    DANCE: 'Dans',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasie',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Meeslepend Theater',
    JUKEBOX: 'Jukebox',
    KIDS: 'Kinderen',
    MAGIC: 'Magie',
    MUSICALS: 'Musicals',
    NEW_ARRIVAL: 'Nieuw',
    OFF_WEST_END: 'Off West End',
    OLIVIER_WINNER: 'Oliver winnaar',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomimes',
    PLAYS: 'Toneel',
    ROMANCE: 'Romantiek',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Sterren op het podium',
    THEATRICAL_CONCERT: 'Theaterconcert',
    TRUE_STORY: 'Waargebeurd verhaal',
    TONY_WINNER: 'Tony Award-winnaar',
    OFF_BROADWAY: 'Off Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Oh oh! We hebben een probleem',
    MESSAGE: `Sorry! Alle ervaringen op deze datum zijn uitverkocht of niet beschikbaar. Maar we hebben er wel heel veel beschikbaar op andere datums. We vragen je wel om flexibel te zijn.`,
    CTA: 'Bekijk alle datums',
  },
  ALL_DATES: 'Alle datums',
  BREADCRUMBS: {
    HOME: 'Home',
    TRAVEL_GUIDE: 'Reisgids',
    THINGS_TO_DO: 'Belevenissen in {0}',
    SHOW_NAME_TICKETS: '{0} - Tickets',
    LTT_HOME: 'London Theatre Tickets',
    LTT_VENUE_PAGE_HOME: 'Theaters in London',
    BROADWAY_HOME: 'Broadway Show Tickets',
    BROADWAY_VENUE_PAGE_HOME: 'Broadway Theaters',
    VIENNA_CONCERT_HOME: 'Concerttickets Wenen',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Concertzalen in Wenen',
    ATTRACTIONS: 'Attracties',
    A2_SIGHTSEEING_CRUISES: 'Sightseeing Rondvaart',
    A2_DINNER_CRUISES: 'Rondvaart met Diner',
    A2_EVENING_CRUISES: 'Avond Rondvaart',
    A2_LUNCH_CRUISES: 'Rondvaart met Lunch',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'London Theatre nieuws',
    BROADWAY_SHOW_NEWS: 'Broadway Show nieuws',
    NEWS_PAGE: 'Nieuwspagina',
    REVIEWS_PAGE_BANNER_HEADING: '{0} beoordelingen',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Café',
    'Dedicated Parking': 'Parkeerplaatsen beschikbaar',
    Elevators: 'Lift',
    Lift: 'Lift',
    'Wheelchair Accessible': 'Rolstoeltoegankelijk',
    Cloakroom: 'Garderobe',
    'Air Conditioning': 'Airconditioning',
    WiFi: 'Wifi',
    Bar: 'Bar',
    'Water Fountain': 'Drinkfontein',
    Washrooms: 'Toiletten',
    Toilets: 'Toiletten',
    Binoculars: 'Operaglazen',
    'Adapted Toilets': 'Barrièrevrije toiletten',
    'Accessible Toilets': 'Barrièrevrije toiletten',
    'Assistive Listening System': 'Hoorhulpmiddelen',
    'Hearing Assistance': 'Gehoorapparaten',
    'Booster Cushions': 'Zitkussens voor kinderen',
    Shop: 'Winkel',
    'Souvenir Shop': 'Souvenirwinkel',
    'Guide Dogs': 'Geschikt voor blindengeleidehonden',
    'Baby Changing Facilities': "Verzorgingsruimte voor baby's",
    'Security Check': 'Veiligheidscontrole',
    Ramp: 'Helling',
    'Level Access': 'Gelijkvloerse toegang',
  },
  CALENDAR: {
    FOOTNOTE: '* Alle prijzen zijn in {0}',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Bekijk originele review in het {0}',
    VIEW_ORIGINAL_NO_LANG: 'Deze review is vertaald. Toon originele review.',
    TRANSLATE: 'Vertaal review in het {0}',
    LANGUAGES: {
      EN: 'engels',
      ES: 'spaans',
      FR: 'frans',
      IT: 'italiaans',
      DE: 'duits',
      PT: 'portugees',
      NL: 'nederlands',
    },
  },
  SHOW_PAGE_V2: {
    SELLING_OUT_FAST: 'Snel uitverkocht',
    INTERVAL: 'Pauze',
    TWO_PART_SHOW: 'Voorstelling in twee delen',
    READ_MORE_REVIEWS: 'Meer beoordelingen lezen',
    SHOW_MORE_REVIEWS: 'Meer beoordelingen tonen',
    ALL_PHOTOS: "Alle foto's",
    MORE_DATES: 'Meer datums',
    SELECT_TIME_SLOT: 'Kies het tijdslot',
    SELECT_TIME_SLOT_ERROR: 'Kies tijdslot om door te gaan',
    price_starting_from: 'Zitplaatsen vanaf',
    SELECT_SEATS: 'Kies zitplaatsen',
    READ_MORE: 'Meer lezen',
    RATINGS_AND_REVIEWS: 'Beoordelingen en recensies',
    READ_DETAILED_REVIEWS: 'Lees gedetailleerde beoordelingen',
    UNTIL_DATE: 'Tot {0}',
    AVAILABLE_TIME: 'Beschikbare tijden',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Deze ervaring is alleen beschikbaar tijdens de volgende uren',
    CONTENT_TABS: {
      ABOUT: 'De show',
      VENUE: 'Locatie',
      TICKETS: 'Tickets',
      Reviews: 'Recensies',
    },
    SELECT_SHOW_TIMMING: 'Kies showtijden',
    ONLY_ONE_SLOT: 'Slechts 1 tijdslot beschikbaar op de gekozen datum',
    SIMILAR_SHOWS: 'Vergelijkbare shows',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Verhaallijn',
      AGE_SUITABILITY_AND_GUIDELINES:
        'Leeftijdsaanbeveling en andere richtlijnen',
      WHAT_CRITICS_THINK: 'Wat critici zeggen',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'FAQs',
      CAST_AND_CREATIVES: 'Cast & creatives',
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Deskundige meertalige gidsen',
    STL: 'Snelle toegang',
    PERSONALIZED: 'Persoonlijke ervaring',
    LOCAL_FOOD: 'Ervaar de lokale keuken en cultuur',
    MULTILINGUAL_GUIDES: 'Meertalige gidsen',
    CULINARY_EXPERTS: 'Ontmoet de culinaire experts',
    SIGHTSEEING: 'Sightseeing & amusement aan boord',
    SIGHTSEEING_MEAL: 'Sightseeing en maaltijdopties aan boord',
    MULTILINGUAL_GT: 'Meertalige rondleidingen',
    AUDIOGUIDE_COMMENTARY: 'Met audiogids en commentaar',
    ALL_TOP_ATTRACTIONS_COVERED: 'Met alle topbezienswaardigheden',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Regelmatige vertrektijden. Onbeperkt reizen',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Lastminute beschikbaarheid. Directe bevestiging',
    MULTI_ROUTES: 'Meerdere routeopties',
    HASSLE_FREE: 'Probleemloos boeken',
    FREQUENT_DEPARTURES: 'Regelmatig vertrek',
    ONBOARD_AMENITIES: 'Beste voorzieningen aan boord',
    FLEXI_TRAVEL: 'Flexibel reizen via meerdere routes',
    FLEXI_EXCHANGE_CANCEL: 'Flexibel omruilen en annuleren',
    EXTRA_DISCOUNT: 'Extra kortingen voor jongeren, senioren & gezinnen',
    PREPAID: 'Prepaid gemak',
    EASY_ACTIVATION: 'Eenvoudig activeren',
    INSTANT_CONNECTIVITY: 'Directe verbinding met wereldwijde dekking',
    ROUND_TRIP: 'Retourtransfers',
    CULTURAL_EXPERIENCE: 'Authentieke culturele ervaringen',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
    LUGGAGE_ASSISTANCE: 'Hulp met bagage',
    TOP_ATTRACTIONS: 'Topattracties inbegrepen',
    FREQ_DEP_MULTI_ROUTE: 'Regelmatig vertrek op meerdere routes',
    CHARGING: 'Oplaadstation',
    WIFI: 'Toegang tot wifi',
    FnB: 'Hapjes en drankjes beschikbaar',
    LUXURY: 'Luxe ervaring',
    FOOD_DRINK: 'Eten en drinken',
    PANAROMIC: 'Panoramisch uitzicht op topattracties',
    PANAROMIC_2: 'Panoramisch uitzicht',
    PANAROMIC_3: 'Panoramisch uitzicht in open lucht',
    BEVERAGES: 'Drankjes aan boord',
    GOURMET: 'Gastronomisch diner',
    GOURMET_2: 'Gastronomisch diner en drankjes',
    NIGHTTIME: 'Prachtig avonduitzicht',
    ROMANTIC: 'Romantische sfeer',
    TRANSFERS: 'Inclusief transfer',
    CERTIFIED_OP: 'Gecertificeerde werking',
    BIRD_EYE: 'Gegarandeerd prachtig uitzicht',
    MULTI_JUMP: 'Meerdere springmomenten',
    EXTREME_ADV: 'Extreem avontuur',
    PHOTO_OP: 'Fotomogelijkheden',
    TOP_ATTRACTIONS_COVERED: 'Topattracties',
    LOCAL_CULTURE: 'Ontdek de lokale cultuur',
    EXCLUSIVE_DISC: 'Exclusieve kortingen',
    EFFICIENT_PUBLIC_TRANSIT: 'Efficiënt openbaar vervoer',
    FREQUENT_SERVICE: 'Frequente service',
    PREBOOKING: 'Eenvoudig vooraf boeken',
    LOCAL_CULTURE_IMM: 'Culturele ervaring',
    DISCOVER_HIDDEN: 'Ontdek verborgen plekjes',
    CITY_SIGHTSEEING: 'Sightseeing in de stad',
    OFFBEAT_ADV: 'Bijzondere ervaring',
    DRINK_DEALS: 'Drankdeals',
    OFFBEAT_EXP: 'Bijzondere ervaring',
    MULTIPLE_VARIETIES: 'Inclusief lokale variëteiten',
    HIDDEN_GEMS: 'Verborgen pareltjes en bijzondere attracties',
    EXPLORE_LOCAL: 'Ontdek lokale buurtjes',
    CUSTOMIZED_TREATMENTS: 'Behandelingen op maat',
    TRAINED_THERAPISTS: 'Getrainde therapeuten',
    HOLISTIC_WELLNESS: 'Holistische wellness',
    FLEXIBLE_DURATION: 'Flexibele duur',
    MULTI_BOAT: 'Ruim aanbod',
    SCENIC_ROUTES: 'Mooie routes',
    HANDS_ON: 'Leren in de praktijk',
    CULTURAL_CULINARY: 'Culturele en culinaire inzichten',
    EXPERT_HOSTS: 'Deskundige hosts',
    ADVENTURE_EXPERIENCE: 'Avontuurlijke ervaring',
    EQUIPMENT: 'Uitrusting inbegrepen',
    SCENIC_FLYOVERS: 'Zorgeloze transfer',
    LIVE_COMMENTARY: 'Live commentaar',
    BEST_AERIAL_VIEWS: 'De beste uitzichten vanuit de lucht',
    SAFE_CERT_OP: 'Veilige en gecertificeerde activiteiten',
    HANDPICKED: 'Zorgvuldig gekozen tours en activiteiten',
    EFFORTLESS: 'Eenvoudige planning',
    EXPERT_GUIDES: 'Uitgebreide informatie van expertgidsen',
    ALL_ATTR_ONE_CARD: 'Alle bezienswaardigheden met 1 kaart',
    MULTI_CARD: 'Verschillende kaartopties',
    COST_EFF: 'Voordelig en handig',
    EASY_BEST: 'Gemakkelijk boeken. Beste prijzen',
    INSTANT_MOBILE: 'Directe bevestiging. Mobiele tickets',
    MULTI_TRANSPORT: 'Meerdere transportopties',
    BEST_PRICES: 'Beste prijzen',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Alles',
    POPULAR_SUBCATEGORY: 'Populaire {0}',
    TOP_CATEGORY: 'De beste {0}',
    ATTRACTIONS: 'Bezienswaardigheden',
    ALL_SUBCATEGORY: 'Alle {0}',
    BROWSE_BY_CATEGORIES: 'Zoek per categorie',
    TICKETS_FROM: 'Tickets vanaf',
    PRICE_LOW_HIGH: 'Prijs (laag naar hoog)',
    PRICE_HIGH_LOW: 'Prijs (hoog tot laag)',
    FILTERS: 'Filters',
    RESET: 'Reset',
    APPLY: 'Toepassen',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout gebruikt cookies om je een betere gebruikerservaring te bieden.',
    MOBILE: 'Wij gebruiken cookies.',
    LEARN_MORE: 'Meer info.',
  },
  SHOW_UNAVAILABLE: 'Show niet beschikbaar',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Uitgelicht',
    ALL_NEWS: 'Alle nieuws',
    MORE_READS: 'Meer lezen',
    LOAD_MORE: 'Toon meer',
    TRAILERS: 'Alle trailers',
    GET_YOUR_TICKETS: 'Koop je tickets',
    POPULAR_SHOWS: 'Populaire shows',
    FEATURED: 'Aanbevolen',
    RECENT_NEWS: 'Het laatste nieuws',
    SHOW_MORE_ARTICLES: 'Toon meer artikelen',
    COLLAPSE_ALL: 'Alles inklappen',
    REVIEWS: 'Recensies',
    SHOW_ALL_REVIEWS: 'Toon alle recensies',
    MAILER: {
      HEADING: ' Deals en nieuws van het theater rechtstreeks in je inbox',
      SUBHEADING: `Meld je aan voor onze nieuwsbrief en ontvang als eerste nieuws en aanbiedingen voor voorstellingen.`,
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: '{0} beoordelingen',
    BEOORDELINGEN_AANTAL: '{0} beoordelingen',
    AWESOME: ' Geweldig',
    GOED: 'Goed',
    AVERAGE: 'Matig',
    POOR: 'Slecht',
    TERRIBLE: 'Verschrikkelijk',
    REVIEW_BY_HEADOUT: 'Dit is wat wij ervan vinden: beoordeling door Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Wat anderen zeggen',
    MOST_RELEVANT: 'Meest relevant',
    RATING_HIGH_TO_LOW: 'Waardering: hoog naar laag',
    Waardering_LOW_TO_HIGH: 'Waardering: laag naar hoog',
    CRITICUS_RECENSIES: 'Beoordelingen van critici',
    USER_REVIEWS: 'Beoordelingen van gebruikers',
    CONTRIBUTORS_REVIEW: 'Beoordelingen van de redactie',
  },
  PC_EXP: {
    SHOW_INCL: 'Inclusies en belangrijke info',
    CLEAR: 'Terugzetten',
    ALL_EXPERIENCES: 'Alle ervaringen',
    FILTER_BY_CATEGORIES: 'Filter op categorieën',
    CATEGORIES: 'Categorieën',
    COMBOS: {
      HEADING: "Goede dingen komen in tweeën. Zoals onze spaarcombo's.",
      DESCRIPTOR_1: 'Voordelige deals',
      DESCRIPTOR_2: 'Plan je reis beter',
    },
  },
  HOHO: {
    HOHO: 'Hop-on hop-off Tickets',
    BUS_ROUTES_DETAILS: 'Routes',
    TOUR_DETAILS: 'Tourdetails',
    ROUTES_SCHEDULES: 'Routes en dienstregelingen',
    VALIDITY: 'Geldig voor 1 dag',
    VALIDITY_NOTE:
      'Je ervaring is geldig voor {0} kalenderdag(en). Als je je ticket boekt voor 6 mei 2023, is je ticket geldig tot 6 mei 2023, 21.00 uur PST.',
    BESTSELLER: 'Bestseller',
    SEE_ALL: 'Toon alles',
    TIMINGS: 'TIJDEN',
    FREQUENCY: 'FREQUENTIE',
    DURATION: 'DUUR',
    STARTING_LOCATION: 'Startpunt',
    CALENDAR_FOOTNOTE: '* Alle prijzen zijn in {0}',
    GOT_IT: 'Begrepen',
    TOUR_TIMINGS: 'Tijden',
    TOUR_FREQUENCY: 'Frequentie',
    SELECT_DATE: 'Select a date',
    SELECT_TOUR: 'Select Tour Type',
    VIEW_TOUR_DETAILS: 'View tour details',
    BUS_DETAILS: 'MORE DETAILS',
    VIEW_ROUTES: 'View all routes',
    BUS_ROUTES: 'BUS ROUTES',
    ATTRACTIONS_PREVIEW: 'Fastest way to view {0}+ top attractions including',
    ROUTES: 'Routes',
    COMBO_SUBTITLE: 'Bespaar meer met',
    COMBO_TITLE: 'Combideals op je Hop-on Hop-off tour',
    COMBO_DWEB_TITLE: 'Bespaar meer met combideals op je Hop-on Hop-off tour',
    STOPS_AND_ATTRACTIONS: 'Stops en attracties in de buurt',
    HOP_ON_OFF_AT: 'Stap in en uit bij elk elk van deze {0} stops',
    TIMINGS_FREQUENCY: 'Vertrektijden en frequentie',
    TOUR_DURATION: 'Duur van de tour',
    EVERY_X_MINS: 'Every {0}',
    VIEW_LOCATION: 'Bekijk locatie',
    BANNER_SUBTEXT:
      'De snelste en gemakkelijkste manier om alle populaire bezienswaardigheden te zien in de stad.',
    TOP_ATTRACTIONS: 'Topattracties die aan bod komen',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Last minute-reservering',
        DESCRIPTION: 'Directe bevestiging op je telefoon',
      },
      COST_EFF: {
        NAME: 'Kosteneffectief verkennen',
        DESCRIPTION: 'Meerdere bezienswaardigheden, één ticket',
      },
      DAILY_RIDES: {
        NAME: 'Onbeperkt aantal dagelijkse ritjes',
        DESCRIPTION: 'Ontdek de stad in jouw tempo',
      },
      BOOK_RELAX: {
        NAME: 'Boeken en ontspannen',
        DESCRIPTION: 'Vertrouwd door 22 miljoen gasten',
      },
    },
  },
  AIRPORT_TRANSFER: {
    // New experiment (AT LP)
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Zorgeloos luchthavenvervoer in {0} met de ',
    BUSES: 'bus',
    TRAINS: 'trein',
    PRIVATE_TAXIS: 'privétaxi',
    BUS_TRAIN: 'Bus/trein',
    PRIVATE_TAXI: 'Privétaxi',

    FROM: 'Van',
    TO: 'Naar',
    SELECT_PICKUP: 'Kies ophaalplaats',
    SELECT_DROPOFF: 'Kies afzetplaats',
    ENTER_DESTINATION: 'Voer je bestemming in',
    ENTER_PICKUP: 'Ophaallocatie invoeren',
    PICKUP_DATE: 'Ophaaldatum',
    SELECT_DATE: 'Datum kiezen',
    PICKUP_TIME: 'Ophaaltijd',
    SELECT_TIME: 'Tijd kiezen',
    GUESTS: 'Gasten',
    GUEST: 'Gast',
    ADD_GUESTS: 'Gasten toevoegen',
    ADULT_CHILD: 'Volwassenen/Kinderen',
    EXPLORE_TRANSFERS: 'Vervoer en meer',
    COMBOS_AND_EXTRAS: "Combo's en extra's",

    YOUR_RIDE_DOORSTEP: 'Je rit, voor de deur',
    COMFORTABLE_RIDE:
      'Boek een comfortabele privétaxi van en naar grote luchthavens in {0}',
    TRUSTED_DRIVERS: 'Betrouwbare chauffeurs',
    RIDES_24_7: 'Ritten 24/7 beschikbaar',
    FLIGHT_TRACKING: 'Vluchten volgen',
    KNOW_MORE: 'Meer',
    RESERVE_YOUR_RIDE: 'Boek je rit',
    TRANSFER_OPTIONS: 'Vervoersopties gevonden',
    TRANSFERS_AVAILABLE_PLURAL: '{0} transfers beschikbaar',
    TRANSFERS_AVAILABLE_SINGULAR: '1 transfer beschikbaar',

    TRUSTED_PARTNERS: '35+ trouwe partners, {0}',
    WORLDWIDE: 'wereldwijd',
    COMFORTABLE_RIDES: 'Comfortabele ritten',
    FREQUENT_DEPARTURES: 'Regelmatige ritten',
    MULTIPLE_TRANSPORT_OPTIONS: 'Meerdere vervoersopties',
    AND_MANY_MORE: 'En nog veel meer',

    ADD_PICKUP_LOCATION: 'Een ophaallocatie toevoegen',
    ADD_DROPOFF_LOCATION: 'Een afzetlocatie toevoegen',
    SELECT_PICKUP_DATE_AND_TIME: 'Kies een ophaaldatum en -tijd',
    SELECT_A_DATE: 'Datum kiezen',

    TRAIN_STATION: 'Treinstation',
    BUS_STOP: 'Bushalte',

    ADD_RETURN: 'Retour toevoegen',
    HEADS_UP: 'Let op!',
    ADDED_RETURN_TRIP: 'Je hebt een retourtje toegevoegd!',
    RETURN_NOTE:
      'Opmerking: de details van de terugreis worden in de volgende stappen weergegeven.',
    OKAY_I_UNDERSTAND: 'Oké, begrepen',

    SERVING_GUESTS: 'Service aan meer dan {0} in {1} wereldwijd',
    GUESTS_COUNT: '220.000 gasten',
    CITIES_COUNT: '55+ steden',
    PARNTER_WITH_BEST:
      'We werken alleen samen met de besten om je een onvergetelijke ervaring te bezorgen. Laat ons de details regelen, terwijl jij geniet van de rit.',
  },
  TOP: 'Top-{0}',
  VIEW_CALENDAR: 'Kalender weergeven',
  SHOWS_CALENDAR: 'Showkalender',
  IN: 'in',
  SEATS: 'Zitplaatsen',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Inhoudstafel',
    QUICK_INFORMATION: 'Snelle informatie',
    PEAK: 'piekuren',
    OFF_PEAK: 'buiten piekuren',
    ADDRESS: 'ADRES',
    RECOMMENDED_DURATION: 'AANBEVOLEN DUUR',
    VISITORS_PER_YEAR: 'BEZOEKERS PER JAAR',
    NUMBER_OF_ENTRANCES: 'AANTAL INGANGEN',
    EXPECTED_WAIT_TIME_STANDARD: 'VERWACHTE WACHTTIJD - STANDAARD',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE: 'VERWACHTE WACHTTIJD - VERSNELDE TOEGANG',
    UNESCO_YEAR: 'UNESCO JAAR',
    ARCHITECTURE_STYLE: 'ARCHITECTUURSTIJL',
    TIMINGS: 'Tijden',
    SIZE_HEIGHT: 'GROOTTE/HOOGTE',
    TICKETS: 'KAARTJES',
    FUN_FACTS: 'Leuke weetjes',
    DID_YOU_KNOW: 'Wist je dat?',
    MORE_INTERESTING_FACTS: 'Meer interessante feiten',
    PLAN_YOUR_VISIT: 'Plan je bezoek',
    ALSO_KNOWN_AS: 'Ook gekend als',
    FOUNDED_ON: 'Opgericht op',
    FOUNDED_BY: 'Opgericht door',
    FROM: 'Vanaf',
    CLOSED_TODAY: 'Vandaag gesloten',
    TODAY: 'Vandaag',
    CLOSED: 'Gesloten',
    OPEN: 'Openen',
    LAST_ADMISSION: 'Laatste Toegang',
    DAYS: 'Dagen',
    BEST_TIME_TO_VISIT: 'Beste tijd om te bezoeken',
    WEEKDAY_VS_WEEKEND: 'Weekdag vs Weekend',
    PEAK_VS_LOW_SEASON: 'Hoogseizoen vs Laagseizoen',
    PLEASANT: 'Aangenaam',
    CROWDED: 'Druk',
    VERY_CROWDED: 'Heel druk',
    LOW_SEASON: 'Laagseizoen',
    MID_SEASON: 'Middenseizoen',
    PEAK_SEASON: 'Hoogseizoen',
    TO: 'TOT',
    TO_LOWER: 'tot',
    LAST_ENTRY: 'laatste invoer',
    SUBATTRACTIONS: 'Sub-Attracties',
    INCLUDED_WITH_TICKETS: 'Inbegrepen in de {0} tickets',
    INCLUDED_WITH_SOME_TICKETS: 'Inbegrepen in sommige {0} tickets',
    EXPLORE_ALL_POI_TICKETS: '{0} & {1} tickets en rondleidingen',
    OPERATING_HOURS: 'Openingstijden',
    SEE_MORE: 'Toon meer',
    MORE_INSIGHTS: 'Meer informatie',
    SELECT_YOUR_EXPERIENCE: 'Selecteer uw ervaring',
  },
  OFF_PERCENT: '{0}% korting',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Zitplaatsindeling',
    CAPACITY: 'Capaciteit: {0} zitplaatsen',
    WHATS_ON: 'Programma',
    CATEGORIES: 'Categorieën',
  },
  NEXT: 'Volgende',
  PREVIOUS: 'Vorige',
  ITINERARY: {
    TAB: 'Reisplan',
    HEADING: 'Reisprogramma',
    VIEW_ITINERARY: 'Bekijk route',
    PASSES_BY_SECTION_HEADING: 'Komt langs',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Hoogtepunten',
      NEARBY_THINGS_TO_DO: 'Ervaringen in de buurt',
      THINGS_TO_DO: 'Ervaringen',
    },
    STOP_CARD: {
      TITLE: {
        START: 'STARTPUNT',
        END: 'EINDPUNT',
        STARTING_POINT: 'STARTPUNT',
        STOP: 'STOPPUNT',
        ENDING_POINT: 'EINDPUNT',
        PASSING_BY: 'ROUTEGEDEELTE',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} startpunten beschikbaar',
        END: '{0} eindpunten beschikbaar',
      },
    },
    GET_DIRECTION: 'Cómo llegar',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} uur {1} minuten',
        WITHOUT_HOURS: '{0} minuten',
        WITHOUT_MINS: '{0} uur',
      },
      ATTRACTIONS_COUNT: '{0} bezienswaardigheden',
      ACTIVITIES_COUNT: '{0} activiteiten',
      TOTAL_DURATION: 'Totale duur',
      FREQUENCY: 'Frequentie',
      FIRST_DEPARTURE: 'Eerste vertrek',
      LAST_DEPARTURE: 'Laatste vertrek',
      FIRST_DEPARTURE_TIME: 'Tijd eerste vertrek',
      LAST_DEPARTURE_TIME: 'Tijd laatste vertrek',
      MODE_OF_TRANSPORT: 'Vervoermiddel',
      FOOD_AND_DRINKS: 'Eten en drinken',
    },
    WALK_DURATION: '{0} lopen',
    MORE: '{0} meer',
    TIMELINE_VIEW: 'Planning',
    MAP_VIEW: 'Kaart',
    MAP_OVERLAY: 'Beweeg de kaart met CTRL/⌘ + scrolfunctie',
    VIEW_EXPERIENCE_MAPPED_OUT: 'Bekijk je ervaring op de kaart.',
    OPEN_MAP_VIEW: 'Kaart openen',
    START_POINT_SAME_AS_END_POINT: 'Je eindpunt is hetzelfde als je startpunt',
  },
  CRUISES: {
    BANNER_HEADING: 'Vaar door {0}: ontdek, eet en relax',
    FILTERS: {
      ALL: 'Alle',
      SIGHTSEEING: 'Sightseeing',
      LUNCH: 'Lunch',
      DINNER: 'Avondeten',
      COMBOS: 'Combitickets',
    },
    MAP_OVERLAY: 'Klik of tik om over de kaart te bewegen',
    SIGHTS_COVERED: 'Locaties',
    MENU: 'Menu',
    BOARD_AT: 'Opstapplaats: {0}',
    BOARDING_POINTS_AVAILABLE: '{0} mogelijke opstapplaatsen',
    VIEW_POPULAR_SIGHTS: 'Populaire bezienswaardigheden: {0} {1}',
    X_BOARDING_POINTS: '{0} opstapplaatsen',
    BOARDING_POINT: 'Opstapplaats',
    BOARDING_POINTS: 'Opstapplaatsen',
    LANDMARKS: 'Bezienswaardigheden',
    GET_DIRECTIONS: 'Routebeschrijving',
    FOOD_MENU: 'Menu',
    X_PAGE: '{0} pagina',
    X_PAGES: "{0} pagina's",
    MORE: '+{0} meer',
    PDF: {
      ZOOM_IN: 'Inzoomen',
      ZOOM_OUT: 'Uitzoomen',
      FIT_TO_WIDTH: 'Volledig scherm',
      RESET_ZOOM: 'Zoom terugzetten',
    },
    COMBO_HEADING: 'Meer voor minder: combideals en city cards',
  },
};
export default nl;
