const no = {
  AUDIO_GUIDE: {
    BANNER: 'Gratis lydguide',
    PRODUCT_SUFFIX: 'med lydguide',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Autorisert og betrodd partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Autorisert forhandler',
    SUB_TEXT: 'Autentiske opplevelser fra pålitelige og verifiserte partnere.',
  },
  REVIEWS: 'anmeldelser',
  AVAILABLE: 'Tilgjengelig',
  BACK: 'Tilbake',
  BANNER_CTA: 'Kjøp billetter',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout er et varemerke som millioner av gjester over hele verden bruker og stoler på, og som tilbyr kuraterte opplevelser for å gjøre besøket på denne attraksjonen best mulig.',
    NON_PARTNERED_SENSITIVE:
      'Headout er et varemerke som millioner av gjester over hele verden bruker og stoler på, og som tilbyr kuraterte opplevelser for å gjøre besøket på denne attraksjonen best mulig. Dette er ikke nettstedet til arrangementsstedet.',
    PARTNERED_NON_SENSITIVE:
      'Headout er en autorisert og betrodd partner for arrangementsstedet, og tilbyr kuraterte opplevelser for å gjøre besøket på denne attraksjonen best mulig.',
    PARTNERED_SENSITIVE:
      'Headout er en autorisert og betrodd partner for arrangementsstedet, og tilbyr kuraterte opplevelser for å gjøre besøket på denne attraksjonen best mulig. Dette er ikke nettstedet til arrangementsstedet.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout er en autorisert og betrodd partner for arrangementsstedet, og tilbyr kuraterte opplevelser for å gjøre besøket på denne attraksjonen best mulig.',
  BOOK_NOW_CTA: 'Bestill nå',
  BOOSTERS: {
    MOST_LOVED: 'Most loved',
    SPECIAL_DEAL: 'Special deal',
    HEADOUT_EXCLUSIVE: 'Eksklusivt hos Headout',
  },
  BUY_TICKETS_CTA: 'Kjøp billetter',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Du kan avbestille disse billettene frem til {0} timer før opplevelsen begynner og få full refusjon.',
    CANCELLABLE_ANYTIME:
      'Gratis avbestilling når som helst før opplevelsen starter',
    CANCELLABLE_DAYS:
      'Du kan avbestille disse billettene frem til {0} dager før opplevelsen begynner og få full refusjon.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Disse billettene kan ikke avbestilles. De er imidlertid gyldige i en lengre periode.',
    HEADING: 'Endringsregler',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Disse billettene kan ikke avbestilles. De kan imidlertid flyttes frem til {0} timer før opplevelsen begynner.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Disse billettene kan ikke avbestilles eller flyttes.',
    VALID_UNTIL_DATE:
      'Disse billettene kan ikke avbestilles. Du kan imidlertid bruke dem når som helst frem til {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Disse billettene kan ikke avbestilles. Du kan imidlertid bruke dem når som helst i løpet av de neste {0} dagene.',
    VALID_WITHIN_NEXT_MONTHS:
      'Disse billettene kan ikke avbestilles. Du kan imidlertid bruke dem når som helst i løpet av de neste {0} månedene.',
  },
  CANCELLATION_POLICY_HEADING: 'Avbestillingsregler',
  CASHBACK: '{0} % i cashback',
  CASHBACK_INFO:
    'Du vil motta <strong>{0} %</strong> i cashback når du bestiller denne opplevelsen. Cashback blir kreditert Headout-kontoen din automatisk og kan brukes til alle fremtidige bestillinger hos Headout.',
  CATEGORY_SLIDER_HEADING:
    'Kunder som bestilte denne forestillingen så også på',
  CHECK_AVAIL: 'Sjekk tilgjengelighet',
  SELECT_SEATS: 'Velg seter',
  CITY_PAGE: {
    BANNER_TITLE: 'Opplev det beste i',
    TOP_ATTRACTIONS: 'De beste attraksjonene',
    GO_BEYOND: 'I nærheten av {0}',
    ALL_DAY_TRIPS: 'Se alle dagsturer',
    CITIES_NEARBY: 'Nærliggende byer',
    POPULAR_CATEGORIES: 'Populære kategorier',
    GO_TO_GUIDE: 'Den ultimate guiden for {0}',
    VIEW_TRAVEL_GUIDE: 'Se reisehåndboken',
    EXPLORE: 'Utforsk {0}',
    GUIDE_SUBHEADING:
      'Det har aldri vært enklere å utforske {0}! Reiseguiden vår for {0} inneholder alt du trenger å vite om byen, fra hva du bør spise og hva du bør se, til hvordan du kommer deg dit, hvor du bør bo og mye mer!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Generell informasjon',
      WHERE_TO_EAT: 'Hva du bør spise',
      WHERE_TO_STAY: 'Hvor du bør bo',
      THINGS_TO_DO: 'Hva du bør gjøre',
      WEATHER: 'Beste tidspunkt å besøke',
      NEIGHBOURHOODS: 'Lokalsamfunn',
      TRANSPORTATION: 'Slik kommer du deg rundt',
      TRIP_PLANNER: 'Reiseplan',
      FAMILY_TRAVEL: 'Reise med barn',
      TRAVEL_TIPS: 'Reisetips og -triks',
      SHOPPING: 'Shopping',
      ART_AND_CULTURE: 'Kunst og kultur',
    },
    MAILER: {
      HEADING: 'Reiseinspirasjon for {0} rett i innboksen din',
      SUBHEADING:
        'Utforsk nye byer med kuraterte opplevelser, umiddelbar cashback, eksklusive tilbud og viktige reisetips!',
    },
  },
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Vi bruker informasjonskapsler og lignende teknologier til mange formål, blant annet for å forbedre opplevelsen din på nettstedet vårt og for annonser.',
    MANAGE_PREFERENCES: 'Administrer',
    PREFERNCES_SAVED: 'Innstillingene dine er lagret',
    COOKIES: 'Informasjonskapsler:',
    ACCEPT: 'OK',
    ALLOW_ALL: 'Tillat alle',
    DENY_ALL: 'Avslå alle',
    HEADING: 'Vi verdsetter personvernet ditt, alltid',
    DESCRIPTION:
      '*   Informasjonskapsler er små filer som plasseres på datamaskinen, mobilenheten eller andre enheter av nettstedet/plattformen, og som blant annet inneholder informasjon om nettleserloggen din.\n*   Vi bruker ulike typer informasjonskapsler for å spore bruken på plattformen vår og lagre visse opplysninger som hjelper oss med å gi deg mer tilpassede tjenester. Enkelte informasjonskapsler kan bli plassert på enheten din på grunn bruken din av tjenester som er tilgjengelige på plattformen vår.\n*   Vi bruker i hovedsak to ulike sett med teknologier:\n    *   **Informasjonskapsler** er små filer som blir plassert på enheten din automatisk når du går inn på plattformen vår. Du kan instruere nettleseren til å avvise alle informasjonskapsler. Hvis du ikke godtar informasjonskapslene våre, kan det hende at du ikke kan bruke enkelte deler av plattformen.\n    *   **Sporingsbilder.** Også kjent som «web beacons», «pikseltagger» og «sporingspiksler» som er vedlagt i ulike deler av plattformen og e-postene våre, og som gjør det mulig for oss å overvåke og forstå aktiviteten til brukerne.\n*   Disse informasjonskapslene som lagres på enheten din, kan være «faste»  eller «øktbaserte» informasjonskapsler. Faste informasjonskapsler er de som forblir på enheten din selv når du er frakoblet, mens øktinformasjonskapsler slettes automatisk så snart du lukker nettleseren.\n*   Vi bruker både øktinformasjonskapsler og faste informasjonskapsler for de formålene som er beskrevet nedenfor:\n    *   Nødvendige/essensielle informasjonskapsler\n        *   _Type:_ Øktinformasjonskapsler\n        *   _Purpose:_ Disse informasjonskapslene er avgjørende for at du skal få tilgang til ulike deler av plattformen, og hvis disse ikke er tillatt, kan det hende at du ikke får tilgang til tjenestene som er tilgjengelige på plattformen. Disse informasjonskapslene hjelper oss med å autentisere brukerne og forhindre enhver form for ulovlig aktivitet på plattformen.\n    *   Retningslinjer for informasjonskapsler / Samtykke til bruk av informasjonskapsler\n        *   _Type:_ Faste informasjonskapsler\n        *   _Purpose:_ Disse informasjonskapslene identifiserer om brukerne har godtatt bruk av informasjonskapsler.\n    *   Funksjonelle informasjonskapsler\n        *   _Type:_ Faste informasjonskapsler\n        *   _Purpose:_ Disse informasjonskapslene gjør det mulig for oss å huske valgene dine plattformen, for eksempel å huske påloggingsinformasjonen din eller språkpreferanser. Det overordnede formålet med disse informasjonskapslene er å gi deg en mer personlig tilpasset opplevelse hver gang du bruker plattformen.\n\nAlle begreper med store bokstaver som brukes ovenfor, er definert i personvernerklæringen. Se [personvernerklæringen](/privacy-policy/) for mer informasjon\n',
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Lær om visumkrav, valutaveksling, tidssoneforskjeller og mer for å sikre en problemfri ankomst og et hyggelig opphold.',
    WHERE_TO_EAT:
      'Fråts i herligheter fra den spennende kulinariske scenen, og nyt ulike smaker og lokale delikatesser i hvert hjørne av byen.',
    WHERE_TO_STAY:
      'Oppdag de beste overnattingsstedene i {0}, som tilbyr komfort, bekvemmelighet og en minneverdig opplevelse for oppholdet.',
    THINGS_TO_DO:
      'Opplev en rekke spennende aktiviteter og attraksjoner som tilfredsstiller alle interesser og sørger for en uforglemmelig opplevelse.',
    WEATHER:
      'Planlegg reisen med omhu og få mest mulig ut av besøket ditt, {0} byr på fantastiske opplevelser året rundt.',
    NEIGHBOURHOODS:
      'Bli kjent med de mangfoldige lokalsamfunnene og livlige nabolagene som gir {0} sin unike karakter.',
    TRANSPORTATION:
      'Det er enkelt å navigere {0} ved hjelp av det effektive transportsystemet, som gir deg praktiske alternativer for å utforske alle attraksjonene.',
    TRIP_PLANNER:
      'Maksimer tiden din i {0} med nøye utvalgte reiseplaner som sørger for at du får mest mulig ut av hvert øyeblikk.',
    FAMILY_TRAVEL:
      'Legg ut på et familievennlig eventyr med mange attraksjoner, parker og underholdningsmuligheter som passer for barn i alle aldre.',
    TRAVEL_TIPS:
      'Oppdag innsidetips og reisetriks for å forbedre reisen din, slik at besøket i {0} virkelig blir eksepsjonelt.',
    SHOPPING:
      'Utforsk et shoppingparadis med et bredt utvalg av butikker, markeder og kjøpesentre, som tilbyr alt fra lokalt håndverk til eksklusiv mote.',
    ART_AND_CULTURE:
      'Fordyp deg i den rike kunst- og kulturscenen, fra fengslende museer til livlige festivaler som feirer kulturarven til {0}.',
  },
  CLOSE: 'Lukk',
  COLLECTION_SLICE_HEADING: 'De beste tingene å gjøre i {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Velg',
    SELECT_PREFERENCE: 'Velg preferanser',
    SELECT_OPTION: 'Velg alternativet',
    SELECT_TICKET: 'Velg billetten din',
  },
  COMPARE_ALL_DETAILS: 'Sammenlign alle detaljer',
  COVID19_ALERT: {
    KEY_TEXT: 'Oppdatering om covid-19',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Du er vår prioritet. Sjekk hjelpesiden for å finne de siste oppdateringene om våre fleksible avbestillingsregler',
  },
  CURRENCY: 'Valuta',
  CUSTOMER_REVIEW_HEADING: 'Kundeanmeldelser',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Lydguide',
    DURATION: 'Varighet: {0}',
    EXTENDED_VALIDITY: 'Utvidet gyldighet',
    FLEXIBLE_DURATION: 'Fleksibel varighet',
    FREE_CANCELLATION: 'Gratis avbestilling',
    GUIDED_TOUR: 'Guidet tur',
    HOTEL_PICKUP: 'Henting på hotellet',
    INSTANT_CONFIRMATION: 'Øyeblikkelig bekreftelse',
    MEALS_INCLUDED: 'Måltider er inkludert',
    MOBILE_TICKET: 'Mobilbillett',
    SKIP_THE_LINE: 'Hopp over køen',
    TRANSFERS: 'Transport er inkludert',
  },
  DURATION: 'Varighet',
  EARLIEST_AVAILABILITY: 'Tidligste tilgjengelighet',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Skriv inn e-postadressen din her',
    SIGN_UP: 'Registrer deg',
    THANK_YOU: 'Tusen takk!',
    SUBSCRIBED_MSG: 'Du er nå registrert som abonnent',
    ERROR_MSG: 'Fyll inn en gyldig e-postadresse',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Broadway Theater-billetter',
    },
    LTT: {
      MB_NAME: 'London Theater-billetter',
    },
  },
  EXCLUSIONS: 'Unntak',
  FEATURE_CARD: {
    HEADING_CUSTOMER: 'Over {0} millioner',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100 % trygt',
    HEADING_SUPPORT: 'Døgnåpent hjelpesenter',
    SUB_HEADING_CUSTOMER:
      'Fornøyde kunder på tvers av mer enn 10 000 opplevelser',
    SUB_HEADING_RATING:
      'Mer enn 5000 verifiserte anmeldelser med 90 % utmerket score',
    SUB_HEADING_SAFE: 'Alle utendørsaktiviteter er 100 % trygge og sikre',
    SUB_HEADING_SUPPORT:
      'Har du et spørsmål? Live chat med lokale eksperter hvor som helst, når som helst',
  },
  FLEXIBLE: 'Fleksibelt',
  FOOTER: {
    CALL_US: 'Ring oss',
    ABOUT_US: 'Om oss',
    CHAT_WITH_US: 'Chat med oss',
    COMPANY_DETAILS: 'Detaljer om selskapet',
    INFORMATION: 'Informasjon',
    GMAPS_DISCLAIMER:
      'Alle skjermbilder av kart på denne siden er hentet fra Google i samsvar med «fair use» . Alle rettigheter til slike skjermbilder ligger hos den spesifikke plattformen, og bruken av dem er utelukkende for informasjons- eller veiledningsformål.',
    DISCLAIMER:
      'Dette nettstedet er ikke det offisielle nettstedet til <attraction>. Det drives av Headout, og samarbeider med attraksjoner og turoperatører for å tilby utrolige opplevelser raskt og enkelt.',
    EMAIL_US: 'Send oss en e-post',
    GET_HELP: 'Få hjelp',
    LEGAL: 'Juridisk informasjon',
    PRIVACY_POLICY: 'Personvern',
    QUICK_LINKS: 'Hurtiglenker',
    TERMS_AND_CONDITIONS: 'Vilkår',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Laget med ',
    ALL_OVER_THE: ' over hele ',
    TERMS_OF_USAGE: 'Bruksvilkår',
    GET_HELP_24_7: 'Få hjelp døgnet rundt',
    HELP_CENTER: 'Hjelpesenter',
    COMPANY: 'Selskap',
    WE_ACCEPT: 'Vi aksepterer',
    DOWNLOAD_HEADOUT: 'Last ned Headout-appen',
    SCAN_CODES: 'Skann kode',
    STAR_VERIFIED: 'klikk for å bekrefte S.T.A.R-medlemskap',
    OFFICIAL_TICKET_RETAILER: 'Offisiell billettforhandler',
  },
  FREE_CANCELLATION: 'Gratis avbestilling',
  FREE_CANCELLATION_SUBTEXT:
    'Vi forstår at planer kan endres, og det er gratis å avbestille frem til 72 timer før arrangementet.',
  FROM: 'Fra',
  GET_CASHBACK: 'Få {0} % i cashback',
  GROUP_TICKETS: 'Gruppebilletter',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: 'Mer enn {0} millioner fornøyde kunder',
    SUB_TEXT:
      'Kundetilfredshet er vår høyeste prioritet. Bli en av våre mange fornøyde kunder.',
  },
  HEADOUT: 'Headout',
  HELP_CENTER: {
    MAIN_TEXT: 'Døgnåpent hjelpesenter',
    SUB_TEXT:
      'Har du spørsmål eller bekymringer? Vi er her for å hjelpe deg døgnet rundt – på telefon, chat og e-post.',
  },
  INCLUSIONS: 'Inkluderinger',
  LANGUAGE: 'Språk',
  LANGUAGES: {
    ENGLISH: 'Engelsk',
    SPANISH: 'Spansk',
    FRENCH: 'Fransk',
    ITALIAN: 'Italiensk',
    GERMAN: 'Tysk',
    PORTUGUESE: 'Portugisisk',
    NEDERLANDS: 'Nederlandsk',
    POLISH: 'Polsk',
    RUSSIAN: 'Russisk',
    DANISH: 'Dansk',
    NORWEGIAN: 'Norsk',
    ROMANIAN: 'Rumensk',
    SWEDISH: 'Svensk',
    TURKISH: 'Tyrkisk',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Turen er tilgjengelig på {0}',
  LISTICLES: {
    KNOW_MORE: 'Finn ut mer',
    SEATING_CHART: 'Sittekart',
    WHY_BOOK_FROM_US: 'Hvorfor bestille fra oss?',
  },
  MORE_DETAILS: 'Flere detaljer',
  MORE_CURRENCIES: 'Flere valutaer',
  NEW: 'NYHET',
  NEW_ARRIVAL: 'Nytt',
  NEXT_AVAILABLE: 'Neste tilgjengelige: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout er et varemerke som over {0} millioner gjester stoler på, og som tilbyr et kuratert utvalg av de beste opplevelsene. Dette er ikke nettstedet til arrangementsstedet.',
  NO_RESULT_FOUND: 'Hmm, ingen resultater.',
  OFF: 'rabatt',
  OPEN_DATED_DESCRIPTOR:
    'Bestill med fleksibilitet – du trenger ikke velge en dato',
  OPENING_DATE: 'Premieredato',
  OPENING_ON: 'Åpner',
  OPENS: 'Åpner',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout er en autorisert og betrodd partner for arrangementsstedet, og tilbyr kuraterte opplevelser for å gjøre besøket på denne attraksjonen best mulig. Dette er ikke nettstedet til arrangementsstedet.',
  POI_COLLECTIONS_SECTION: {
    MAKE_THE_MOST_OF_CITY: 'Få mest mulig ut av {0}',
    TOP_EXPERIENCE_PICKS: 'Utvalgte populære opplevelser',
    EXPERIENCES: 'Mer enn {0} opplevelser',
    CITY_YOUR_WAY: '{0}, på din måte',
    DISCOVER_MORE: 'Oppdag mer',
  },
  POPULAR_CURRENCIES: 'Populære valutaer',
  PRICES_STARTING: 'Priser fra',
  PROMO_CODES: {
    APPLY_CODE: 'BRUK KODE',
    APPLIED: 'ANVENDT',
    TOOL_TIP_INFO: 'Denne rabatten legges til i kassen',
    DESCRIPTION: {
      ABSOLUTE: 'Få {0} rabatt',
      CAPPED: 'Få {0} % rabatt, opptil {1}',
      PERCENTAGE: 'Få {0} % rabatt',
    },
    REMOVE: 'FJERN',
  },
  RATINGS: '{0} vurderinger',
  READ_MORE: 'Les mer',
  READ_MORE_TEXT: 'Les mer',
  READ_LESS: 'Les mindre',
  VIEW_DETAILS: 'Vis detaljer',
  REOPENING: 'Gjenåpner',
  REOPENING_DATE: 'Gjenåpningsdato',
  REOPENING_ON: 'Gjenåpner den',
  REOPENS: 'Gjenåpner',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      CTA_URL:
        'https://www.austria.info/en/service-and-facts/coronavirus-information/entry-regulations',
      TEXT: '2G-bestemmelser gjelder: Adgang til blant annet overnattingssteder, kulturinstitusjoner og restauranter/barer er kun mulig med bevis på full vaksinasjon eller tidligere infeksjon. En negativ Covid-19-test er ikke lenger tilstrekkelig.',
    },
    AU_DESCRIPTION: {
      CTA_URL:
        'https://www.smartraveller.gov.au/COVID-19/COVID-19-vaccinations',
      TEXT: 'Besøkende over 16 år må fremvise bevis på covid-19-vaksinasjon eller medisinsk fritak. ',
    },
    BANNER_CTA: 'Finn ut mer',
    BERLIN_DESCRIPTION: {
      CTA_URL:
        'https://www.berlin.de/en/news/coronavirus/7081102-6098215-berlin-introduces-extensive-2G-rule.en.html',
      TEXT: '2G-bestemmelser gjelder: Kun fullvaksinerte og friske gjester med bevis vil få adgang. Gjester under 18 år eller de som ikke kan vaksineres av medisinske årsaker, må fremvise et negativt covid-testresultat ved inngangen. De som ikke kan vaksineres av medisinske årsaker, må også bevise at de ikke kan vaksineres ved hjelp av en legeerklæring ved inngangen.',
    },
    CTA_TEXT: 'Sikkerhetsinformasjon',
    DESCRIPTION_CTA: 'Finn ut mer.',
    EU_DESCRIPTION: {
      CTA_URL:
        'https://www.diplomatie.gouv.fr/en/coming-to-france/coronavirus-advice-for-foreign-nationals-in-france/coronavirus-statements/article/applying-for-a-covid-certificate-if-you-were-vaccinated-abroad-procedure-for',
      TEXT: 'Fra 21. juli 2021 må alle besøkende over 12 år fremvise et EU-koronasertifikat. ',
    },
    EU_HEADING: 'EU-koroniasertifikat er obligatorisk',
    EU_PREFIX: 'Merk: ',
    EXPERIENCE_DESCRIPTION:
      'Denne opplevelsen har blitt verifisert og følger de beste sikkerhetsstandardene i samsvar med lokale forskrifter og WHO',
    FLAG_TEXT: 'Førsteklasses sikkerhet',
    GENERAL_DESCRIPTION:
      'Alle opplevelser med dette merket er verifisert og følger de beste sikkerhetsstandardene i henhold til de lokale myndighetenes retningslinjer.',
    HEADING: 'De beste sikkerhetsstandardene',
    IT_DESCRIPTION: {
      CTA_URL: 'https://www.dgc.gov.it/web/per-cosa-serve.html#viaggi',
      TEXT: 'Fra 6. august 2021 må alle besøkende over 11 år fremvise et Green Pass eller EU-koronasertifikat. ',
    },
    IT_PREFIX: 'Merk: ',
    MOBILE_HEADING: 'Trygge opplevelser',
    MODAL: {
      BADGE_DESCRIPTION:
        'Dette merket på en opplevelse bekrefter at sikkerhetsstandardene har blitt verifisert av oss',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Alt utstyr, alle kjøretøy og alle områder med mye berøring desinfiseres etter hver eneste bruk. Bare len deg tilbake og nyt opplevelsen.',
          HEADING: 'Alt utstyr og alle overflater blir desinfisert',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Alt utstyret som er tilgjengelig under opplevelsen blir grundig desinfisert etter hver eneste bruk. Alltid.',
          HEADING: 'Alt utstyr og alle overflater blir desinfisert',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Alle kjøretøyene som er tilgjengelige under opplevelsen blir grundig desinfisert etter hver eneste bruk. Alltid',
          HEADING: 'Alle kjøretøy blir desinfisert',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Dette er en trygg opplevelse, og du vil ha tilgang til håndvask- og sanitærstasjoner under hele oppholdet. Vi har alt under kontroll. ',
          HEADING: 'Håndvask og sanitærfasiliteter er tilgjengelig overalt',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Masker er obligatorisk for alle gjester og ansatte under denne opplevelsen. Dette bidrar til at alle kan ha det gøy og trygt.',
          HEADING: 'Alle bruker masker for din sikkerhet',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Våre samarbeidspartnere som er verifisert som «Safe Experience», følger de lokale forskriftene som gjelder for munnbind. Hvis det er påbudt, skal alle gjester og ansatte bruke maske. De gjør alt de kan for å sikre din komfort og sikkerhet.',
          HEADING: 'Alle bruker masker for din sikkerhet',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Masker er obligatorisk for alle gjester under denne opplevelsen. Dette bidrar til at alle kan ha det gøy og trygt.',
          HEADING: 'Alle bruker masker for din sikkerhet',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Alle ansatte på denne opplevelsen bruker ansiktsmaske for å sikre at du kan ha det gøy uten å bekymre deg.',
          HEADING: 'Alle bruker masker for din sikkerhet',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Retningslinjene for sosial distansering gjelder under hele denne opplevelsen. Kapasitetsbegrensninger er på plass for å sikre sosial distansering.',
          HEADING: 'Retningslinjer for sosial distansering følges',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Retningslinjene for sosial distansering gjelder under hele denne opplevelsen. Kapasitetsbegrensninger er på plass for å sikre sosial distansering. På samme måte er det ikke tillatt med store grupper her.',
          HEADING: 'Retningslinjer for sosial distansering følges',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Retningslinjene for sosial distansering følges til enhver tid gjennom denne opplevelsen.',
          HEADING: 'Retningslinjer for sosial distansering følges',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Retningslinjene for sosial distansering følges til enhver tid gjennom denne opplevelsen. For å håndheve dette kan det innføres kapasitetsbegrensninger og gruppegrenser. Ta det med ro.',
          HEADING: 'Retningslinjer for sosial distansering følges',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Retningslinjene for sosial distansering følges til enhver tid gjennom denne opplevelsen. På samme måte er det ikke tillatt med store grupper her.',
          HEADING: 'Retningslinjer for sosial distansering følges',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Temperaturen til alle gjestene blir sjekket ved starten av opplevelsen for å sikre at alle er trygge. Alle ansatte sjekkes for høy temperatur flere ganger om dagen.',
          HEADING: 'Det utføres temperatursjekker',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Temperaturen til alle gjestene blir sjekket ved starten av opplevelsen for å sikre at alle er trygge. ',
          HEADING: 'Det utføres temperatursjekker',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Alle ansatte sjekkes for høy temperatur flere ganger. Adgang for de over den foreskrevne grensen er innskrenket, og de blir bedt om å holde seg hjemme for å bli friske.',
          HEADING: 'Det utføres temperatursjekker',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Personalet som er tilgjengelig under opplevelsen er opplært i henhold til WHOs retningslinjer og utstyrt for å håndtere enhver nødsituasjon som måtte oppstå',
          HEADING: 'Personalet får opplæring i WHOs retningslinjer',
        },
      },
      HEADING: 'Trygge opplevelser',
      SUB_HEADING:
        'Vi samarbeider med våre partnere over hele verden for å implementere de beste sikkerhetsstandardene i henhold til WHOs retningslinjer. Alle tiltakene som er iverksatt er verifisert og vises her. Det er på tide å utforske verden igjen.',
    },
    NL_DESCRIPTION: {
      CTA_URL:
        'https://www.government.nl/topics/coronavirus-covid-19/covid-certificate',
      TEXT: 'Besøkende over 13 år må ha med seg (digital eller utskrevet kopi av) et COVID-sertifikat som viser at du er vaksinert, har fått et negativt testresultat eller nylig har blitt frisk etter covid-19. Bruk av ansiktsmaske er obligatorisk. ',
    },
    SG_DESCRIPTION: {
      CTA_URL: 'https://safetravel.ica.gov.sg/health/vtsg',
      TEXT: 'Fra 13. oktober 2021 kan kun fullvaksinerte besøkende reise inn i grupper på to. Du må fremvise bevis på vaksinasjonsstatus, et nylig negativt COVID-19-testresultat og/eller eventuell friskmeldingsdokumentasjon før innreise. ',
    },
    SHORT_HEADING: 'De beste sikkerhetsstandardene er på plass',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Sikkerhetsinformasjon',
    EXPERIENCE_DESCRIPTION:
      'Denne opplevelsen har blitt verifisert og følger de beste sikkerhetsstandardene i samsvar med lokale forskrifter og WHO',
    FLAG_TEXT: 'Førsteklasses sikkerhet',
    GENERAL_DESCRIPTION:
      'Dette teateret er COVID-SIKRET og følger alle sikkerhetstiltak anbefalt av myndighetene for å sikre at du får en trygg og sosialt distansert teateropplevelse.',
    GENERAL_DESCRIPTION_V2:
      'Vi har utviklet det bransjeomfattende See it Safely-merket, slik at når teatrene åpner igjen, kan du føle deg trygg og sikker på at lokalet er COVID-sikret og følger de nyeste retningslinjene fra myndighetene og scenekunstbransjen.',
    HEADING: 'En trygg opplevelse',
    MOBILE_HEADING: 'Trygge opplevelser',
    MORE_CURRENCIES: 'Flere valutaer',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Kun printede billetter og e-billetter vil bli akseptert</li>',
          HEADING: 'Kontaktløse e-billetter',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Det er påbudt med smitteverneutstyr, for eksempel munnbind, for å komme inn til arrangementsstedet</li>\n            <li>Temperaturen til alle gjestene blir sjekket før de kan gå inn til arrangementsstedet</li>',
          HEADING: 'Forebyggende sikkerhetstiltak',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Det er påbudt med smitteverneutstyr, for eksempel munnbind, for å komme inn til arrangementsstedet</li>\n            <li>Temperaturen til alle gjestene blir sjekket før de kan gå inn til arrangementsstedet</li>',
          HEADING: 'Saneringstiltak',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Arrangementsstedet er redesignet for å minimere kontakten mellom alle tilskuerne</li>\n            <li>Ulike grupper vil sitte hver for seg</li>\n            <li>Det vil bli lagt til rette for forhåndsbestilling av pausesnacks der det er mulig</li>\n            <li>Kontantløse og papirløse transaksjoner anbefales.</li>\n            <li>Alle tilskuere bes om å ta med seg minst mulig eiendeler, siden garderobefasilitetene kan være stengt</li>\n            <li>Aktiviteter som å ta bilder med artistene eller signeringer kan være begrenset</li>\n            ',
          HEADING: 'Tiltak for sosial distansering',
        },
      },
      HEADING: 'En trygg opplevelse',
      SUB_HEADING:
        'Lurer du på hva som gjøres for å holde deg trygg? Finn ut mer om sikkerhetstiltakene og COVID-safe-protokollene som teatrene har implementert for å ivareta sikkerheten din.',
    },
    SHORT_HEADING: 'De beste sikkerhetsstandardene er på plass',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Din sikkerhet er vår prioritet',
    TEXT: 'Vi har tatt betydelige steg for å forbedre renholdet ved hjelp av desinfeksjonsmidler samt omfattende og hyppig rengjøring av overflater. Folkemengden blir også kontrollert for å forhindre opphopning.',
  },
  SAVE: 'Spar {0} %',
  SAVE_PERCENT: 'Spar {0} %',
  SAVE_UPTO_PERCENT: 'Spar opptil {0} %',
  SEE_ALL: 'Se alle',
  SEARCH: 'Søk',
  POPULARITY: 'Popularitet',
  PRICE: 'Pris',
  SEE_MORE_SHOWS: 'Se flere forestillinger',
  SELECT_CITY: 'Velg by',
  SELECT_SECTION: 'Velg seksjon',
  SEE_ALL_PHOTOS: 'Se alle bildene',
  SHOW_CLOSED: 'Forestillingen går ikke lenger',
  SHOW_LESS: 'Vis mindre',
  SHOW_LESS_TEXT: 'Vis mindre',
  SHOW_MORE: 'Vis mer',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Om forestillingen',
    ABOUT_THEATRE: 'Om teateret',
    ADDITIONAL_INFORMATION: 'Tilleggsinformasjon',
    AGE_LIMIT: 'Aldersgrense',
    AGE_SUITABILITY: 'Anbefalt aldersgrense',
    CRITIC_REVIEW: 'Dette sier kritikerne',
    ANSWER: ['A-'],
    BLOG_SHOW_PAGE: 'Blog Forestillingssiden',
    BLOG_SUMMARY: 'Blog Sammendrag',
    BLOG_THEATRE_PAGE: 'Blog Teatersiden',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Salkart for teateret',
    CANCELLATION_AND_REFUNDS: 'Avbestilling og refusjon',
    CANCELLATION_POLICY: 'Avbestillingsregler',
    CAST_AND_CREW: 'Rollebesetning og produksjonslag',
    CLOSING_DATE: 'Siste forestilling',
    CLOSING_DATE_SPECIAL_OFFER: 'Spesialtilbud for siste forestilling',
    DURATION: 'Varighet',
    FACILITIES_AND_ACCESSIBILITY: 'Fasiliteter og tilgjengelighet',
    FREQUENTLY_ASKED_QUESTIONS: 'Ofte stilte spørsmål',
    GETTING_THERE: 'Slik finner du frem',
    GETTING_THERE_MAP_LINK: 'Slik finner du frem – Kartlenke',
    GOOGLE_MAP: 'Google Maps-kart',
    HIGHLIGHTS: 'Høydepunkter',
    LISTICLE_SHOW_SUMMARY: 'Listicle Sammendrag av forestillingen',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Derfor bør du se forestillingen',
    OPENING_DATE: 'Premieredato',
    QUESTION: ['Q-'],
    SAFETY_BANNER: 'Sikkerhetsbanner',
    SHOW_DETAILS: 'Detaljer om forestillingen',
    SHOW_TIMINGS: 'Forestillingstider',
    SHOW_TYPE: 'Type forestilling',
    SPECIAL_OFFER: 'Spesialtilbud',
    THE_STORY: 'Handlingen',
    THEATRE_ADDRESS: 'Teaterets adresse',
    THEATRE_CAPACITY: 'Teaterets kapasitet',
    THEATRE_NAME: 'Teaterets navn',
    TICKETS: 'Billetter',
    TICKETS_REDEMPTION: 'Innløsning av billetter',
    TOP_SONGS: 'Populære sanger',
    YOUR_TICKETS: 'Billettene dine',
    ABOUT_CONCERT: 'Om konserten',
    PROGRAM: 'Program',
    PART_ONE: 'Del 1',
    PART_TWO: 'Del 2',
  },
  SORT_BY: 'Sorter etter',
  SPECIAL_OFFER: 'Spesialtilbud',
  THEATRE: 'Teater',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Teatre i nærheten',
    NOW_PLAYING: 'Spilles nå',
    UPCOMING_SHOWS: 'Kommende forestillinger',
    PAST_SHOWS: 'Tidligere forestillinger',
    FIND_BEST_SEATS: 'Finn de beste setene',
  },
  TICKET_CAN_BE_CANCELED:
    'Du kan avbestille frem til {timer} timer i forveien og få full refusjon.',
  TICKET_CANNOT_BE_CANCELED:
    'Denne billetten kan ikke avbestilles, men den kan flyttes på forespørsel.',
  TICKETS: 'Billetter',
  TIMINGS: 'Tidspunkter',
  SPECIAL_PRODUCT_HEADING: 'Mest populære',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Lokale ekspertguider',
    ENGAGING_STORIES: 'Engasjerende historier',
    TOP_RATED: 'Mest populære',
  },
  GUIDED_TOUR_REVIEWS: [
    'Guiden vår Angela var fantastisk og full av kunnskap om stedet',
    'Guiden svarte gjerne på spørsmål om turen',
    'Guiden vår var fantastisk, og hun ga oss til og med en god lunsjanbefaling!',
    'Organiseringen og guiden vår gjorde opplevelsen veldig bra',
    'Mye lærerikt innhold, jeg kommer garantert til å gjøre det igjen med barna mine',
    'Turen var godt organisert og akkurat passe lang',
    'Guiden vår kunne virkelig sakene sine, og lidenskapen for historie var tydelig',
    'Flink guide og god organisering! Jeg anbefaler!!!',
    'Guiden kom med små, morsomme fakta som holdt oss alle engasjerte og interesserte',
    'Turen gikk i et behagelig tempo og føltes ikke stresset',
    'Guiden vår Maria klarte å finne det beste utsiktspunktet for oss',
    'Guiden vår beriket besøket utover det vi ville ha oppnådd på egen hånd',
    'Detaljert og rørende omvisning ledet av en lidenskapelig guide',
    'Jeff viste oss sider ved arrangementsstedet som vi ellers ville ha gått glipp av',
  ],
  GUIDES_BANNER:
    'Utforsk som en lokal innbygger med våre populære superguider.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'En guidet omvisning er den beste måten å få mest mulig ut av dette reisemålet på. Våre ekspertguider fungerer som lokale venner, og deler historier, innsideperler og reiseanbefalinger.',
    'Ikke bare besøk – opplev!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Hør fra gjestene våre',
  GUIDES: 'Guider',
  TODAY: 'I dag',
  TOMORROW: 'I morgen',
  TOUR_LIST_HEADING: 'Velg opplevelsen din',
  TOUR_LIST_SUB_HEADING:
    'Velg mellom flere billetter, turer og kombinasjonsalternativer fra verifiserte operatører',
  UGC: {
    FOLLOW: 'Følg',
    FOLLOW_IG: 'Følg oss på Instagram',
    HEADING: 'POV: Det neste eventyret ditt ser slik ut',
    SUB_HEADING: 'Kuratert med 💜 av Headout',
  },
  UNAVAILABLE: 'Ikke tilgjengelig',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Disse billettene er gyldige i en lengre periode. De nøyaktige detaljene kan du finne på billetten.',
    UNTIL_DATE: 'Disse billettene er gyldige frem til {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Disse billettene er gyldige i {0} dager fra kjøpsdatoen.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Disse billettene er gyldige i {0} måneder fra kjøpsdatoen.',
  },
  TABLE_OF_CONTENTS: 'Innhold',
  VIEW_LESS: 'Vis mindre',
  VIEW_MORE: 'Vis mer',
  WHY_TAKE_THIS_DAY_TRIP: 'Hvorfor reise på denne dagsturen?',
  WHY_WATCH: 'Hvorfor se {0}?',
  FIND_ON_MAP: 'Finn på kartet',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Billetter fra billettkontor',
        DESCRIPTION: 'Umiddelbar bekreftelse sendt til mobilen din',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: 'Velg seter',
        DESCRIPTION: 'Utsikten du vil ha, hver gang',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Eksklusive tilbud og rabatter',
        DESCRIPTION: 'Spar stort på {0}s beste forestillinger',
      },
      BOOK_AND_RELAX: {
        NAME: 'Bestill og len deg tilbake',
        DESCRIPTION: '{0} millioner gjester har brukt oss så langt',
      },
    },
    YOUR_PICK: 'Ditt valg',
    BROWSE_BY_CATEGORIES: 'Bla gjennom etter kategorier',
    TOP_WEST_END_SHOWS: 'De beste West End-forestillingene',
    TOP_THEATRE_SHOWS: 'De {0} mest populære forestillingene',
    TOP_SHOWS: 'Mest populære forestillinger',
    SEE_MORE_SHOWS: 'Se {0} flere forestillinger',
    LAST_MINUTE_TICKETS: 'Siste liten-billetter',
    LOVED_BY_MILLIONS: 'Elsket av millioner',
    TODAY: 'I dag',
    TOMORROW: 'I morgen',
    SEE_ALL: 'Se alle',
    GRAB_YOUR_TICKETS: 'Sikre deg billetter nå',
  },
  TAG_NAME: {
    BALLET: 'Ballett',
    CABARET: 'Kabaret',
    CHRISTMAS: 'Jul',
    CIRCUS: 'Sirkus',
    CLASSIC: 'Klassiker',
    COMEDY: 'Komedie',
    COMING_SOON: 'Kommer snart',
    CRITICS_CHOICE: 'Kritikernes favoritter',
    DANCE: 'Dans',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasy',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Omsluttende teater',
    JUKEBOX: 'Jukeboks',
    KIDS: 'Barn',
    MAGIC: 'Magi',
    MUSICALS: 'Musikaler',
    NEW_ARRIVAL: 'Nytt',
    OFF_WEST_END: 'Utenfor West End',
    OLIVIER_WINNER: 'Olivier Winner',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomimer',
    PLAYS: 'Skuespill',
    ROMANCE: 'Romantikk',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Stars on Stage',
    THEATRICAL_CONCERT: 'Teaterkonsert',
    TRUE_STORY: 'Sann historie',
    TONY_WINNER: 'Tony-vinner',
    OFF_BROADWAY: 'Off Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Vi har støtt på et problem',
    MESSAGE:
      'Beklager! Alle opplevelser for denne datoen er enten utsolgt eller\n    utilgjengelige. Men flere av dem er tilgjengelige på andre datoer. Du\n    må bare være fleksibel',
    CTA: 'Se alle datoer',
  },
  ALL_DATES: 'Alle datoer',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Hovedmeny',
    EXPLORE: 'Utforsk',
    VISIT: 'Besøk',
    THINGS_TO_DO: 'Ting å gjøre',
    CITY_ATTRACTIONS: 'Attraksjoner i {0}',
    TOP_THINGS_TO_DO: 'De beste tingene å gjøre',
    CITY_TOURS: 'Turer i {0}',
    CITY_GUIDE: 'Byguide',
    ATTRACTIONS: 'Attraksjoner',
    CRUISES: 'Cruise',
    THEMES: 'Temaer',
    ABOUT: 'Om',
    TOURS: 'Turer',
    SKIP_THE_LINE: 'Turer hvor du kan hoppe over køen',
    GUIDED_TOURS: 'Guidede turer',
    NIGHT_TOURS: 'Natturer',
    FOOD_TOURS: 'Matturer',
    HISTORY: 'Historie',
    ARCHITECTURE: 'Arkitektur',
    DESIGN: 'Design',
    INSIDE: 'På innsiden',
    COLLECTIONS: 'Samlinger',
    PAINTINGS: 'Malerier',
    ANIMALS_EXHIBITS: 'Dyr og utstillingsgjenstander',
    HABITATS: 'Habitater',
    CONSERVATION: 'Bevaring',
    PROGRAMMES: 'Programmer',
    A2_SIGHTSEEING_CRUISES: 'Sightseeingscruise',
    A2_DINNER_CRUISES: 'Middagscruise',
    A2_EVENING_CRUISES: 'Kveldscruise',
    A2_LUNCH_CRUISES: 'Lunsjcruise',
    A2_YACHT_TOURS: 'Yachtcruise',
    PLAN_YOUR_VISIT: 'Planlegg besøket',
    TIMINGS: 'Tidspunkter',
    DIRECTIONS: 'Veibeskrivelse',
    PARKING: 'Parkering',
    ROUTES: 'Ruter',
    REQUIREMENTS: 'Krav',
    LOCATION: 'Beliggenhet',
    RULES: 'Regler',
    FAQs: 'Ofte stilte spørsmål',
    ENTRANCES: 'Innganger',
    RESTAURANTS: 'Restauranter',
    FACTS: 'Fakta',
    TIPS: 'Tips',
    MAP: 'Kart',
    RIDES: 'Attraksjoner',
    SHOWS: 'Forestillinger',
    DINING: 'Spisesteder',
    SHOPPING: 'Shopping',
    EVENTS: 'Arrangementer',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Jul',
    NEW_YEARS_EVE: 'Nyttårsaften',
    TRAVEL_GUIDE: 'Reiseguide',
    TRIP_PLANNER: 'Reiseplanlegger',
    ITINERARY: 'Reiseplan',
    TRAVEL_TIPS: 'Reisetips',
    WEATHER: 'Vær',
    BEST_TIME_TO_VISIT: 'Beste tidspunkt å besøke',
    JANUARY: 'Januar',
    FEBRUARY: 'Februar',
    MARCH: 'Mars',
    APRIL: 'April',
    MAY: 'Mai',
    JUNE: 'Juni',
    JULY: 'Juli',
    AUGUST: 'August',
    SEPTEMBER: 'September',
    OCTOBER: 'Oktober',
    NOVEMBER: 'November',
    DECEMBER: 'Desember',
    WHERE_TO_EAT: 'Hvor du bør spise',
    WHERE_TO_STAY: 'Hvor du bør bo',
    NEIGHBOURHOODS: 'Nabolag',
    FAMILY_TRAVEL: 'Familieturer',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivaler og arrangementer',
  },
  BREADCRUMBS: {
    HOME: 'Hjem',
    TRAVEL_GUIDE: 'Reiseguide',
    THINGS_TO_DO: 'Ting å gjøre i {0}',
    SHOW_NAME_TICKETS: '{0} - Billetter',
    LTT_HOME: 'London Theatre-billetter',
    LTT_VENUE_PAGE_HOME: 'Teatre i London',
    BROADWAY_HOME: 'Billetter til Broadway-forestillinger',
    BROADWAY_VENUE_PAGE_HOME: 'Broadway-teatre',
    VIENNA_CONCERT_HOME: 'Konsertbilletter til Wien',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Konsertsaler i Wien',
    ATTRACTIONS: 'Attraksjoner',
    A2_SIGHTSEEING_CRUISES: 'Sightseeingscruise',
    A2_DINNER_CRUISES: 'Middagscruise',
    A2_EVENING_CRUISES: 'Kveldscruise',
    A2_LUNCH_CRUISES: 'Lunsjcruise',
    A2_YACHT_TOURS: 'Yachtcruise',
    LONDON_THEATRE_NEWS: 'Nyheter om London Theatre',
    BROADWAY_SHOW_NEWS: 'Nyheter om Broadway-forestillinger',
    NEWS_PAGE: 'Nyhetsside',
    REVIEWS_PAGE_BANNER_HEADING: '{0} anmeldelser',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Kafé',
    'Dedicated Parking': 'Dedikert parkering',
    Elevators: 'Heiser',
    Lift: 'Heis',
    'Wheelchair Accessible': 'Rullestoltilgang',
    Cloakroom: 'Garderobe',
    'Air Conditioning': 'Klimaanlegg',
    WiFi: 'Wi-Fi',
    Bar: 'Bar',
    'Water Fountain': 'Vannfontene',
    Washrooms: 'Toaletter',
    Toilets: 'Toaletter',
    Binoculars: 'Kikkert',
    'Adapted Toilets': 'Tilpassede toaletter',
    'Accessible Toilets': 'Handikaptoaletter',
    'Assistive Listening System': 'Hørselshjelpemidler',
    'Hearing Assistance': 'Hørselshjelp',
    'Booster Cushions': 'Sitteputer',
    Shop: 'Butikk',
    'Souvenir Shop': 'Suvenirbutikk',
    'Guide Dogs': 'Førerhunder',
    'Baby Changing Facilities': 'Stellerom',
    'Security Check': 'Sikkerhetssjekk',
    Ramp: 'Rampe',
    'Level Access': 'Level Access',
  },
  CALENDAR: {
    FOOTNOTE: '* Alle priser er i ',
    PICK_DATE: 'Velg en dato',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Se den opprinnelige anmeldelsen på {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Denne anmeldelsen er oversatt. Vis den opprinnelige anmeldelsen.',
    TRANSLATE: 'Oversett anmeldelsen til {0}',
    LANGUAGES: {
      EN: 'Engelsk',
      ES: 'Spansk',
      FR: 'Fransk',
      IT: 'Italiensk',
      DE: 'Tysk',
      PT: 'Portugisisk',
      NL: 'Nederlandsk',
    },
  },
  SHOW_PAGE_V2: {
    READ_MORE_REVIEWS: 'Les flere anmeldelser',
    SHOW_MORE_REVIEWS: 'Vis flere anmeldelser',
    ALL_PHOTOS: 'Alle bilder',
    MORE_DATES: 'Flere datoer',
    SELLING_OUT_FAST: 'Selges raskt unna',
    SELECT_TIME_SLOT: 'Velg et klokkeslett',
    SELECT_TIME_SLOT_ERROR: 'Velg et klokkeslett for å fortsette',
    PRICE_STARTING_FROM: 'Setepriser starter fra',
    SELECT_SEATS: 'Velg seter',
    READ_MORE: 'Les mer',
    RATINGS_AND_REVIEWS: 'Vurderinger og anmeldelser',
    READ_DETAILED_REVIEWS: 'Les detaljerte anmeldelser',
    INTERVAL: 'Intervall',
    TWO_PART_SHOW: 'Forestilling i to deler',
    UNTIL_DATE: 'Frem til {0}',
    AVAILABLE_TIME: 'Tilgjengelig tidspunkt',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Denne opplevelsen er kun tilgjengelig for tidspunktet nedenfor',
    CONTENT_TABS: {
      ABOUT: 'Om',
      VENUE: 'Sted',
      TICKETS: 'Billetter',
      Reviews: 'Anmeldelser',
    },
    SELECT_SHOW_TIMMING: 'Velg tidspunkt for forestillingen',
    ONLY_ONE_SLOT: 'Kun 1 ledig tidspunkt på den valgte datoen',
    SIMILAR_SHOWS: 'Du vil kanskje også like',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Handlingen',
      WHAT_CRITICS_THINK: 'Hva sier kritikerne',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Ofte stilte spørsmål om {0}',
      AGE_SUITABILITY_AND_GUIDELINES: 'Guide for aldersegnethet og innhold',
      CAST_AND_CREATIVES: 'Rollebesetning og kreative medarbeidere',
    },
  },
  HOHO: {
    HOHO: 'Hopp-på-hopp-av-turer',
    BUS_ROUTES_DETAILS: 'Bussruter',
    TOUR_DETAILS: 'Detaljer om turen',
    ROUTES_SCHEDULES: 'Ruter og rutetabeller',
    VALIDITY: 'Gyldig i 1 dag',
    VALIDITY_NOTE:
      'Opplevelsen din er gyldig i {0} kalenderdag(er). Hvis du bestiller billetten for 6. mai, 2023, vil billetten være gyldig frem til 6. mai 2023, 21.00 BST.',
    BESTSELLER: 'Bestselger',
    SEE_ALL: 'Vis alle',
    TIMINGS: 'TIDSPUNKTER',
    FREQUENCY: 'HYPPIGHET',
    DURATION: 'VARIGHET',
    STARTING_LOCATION: 'Startsted',
    CALENDAR_FOOTNOTE: '* Alle priser er i {0}',
    TOUR_TIMINGS: 'Turtider',
    TOUR_FREQUENCY: 'Hyppighet av omvisninger',
    GOT_IT: 'Skjønner',
    SELECT_DATE: 'Velg en dato',
    SELECT_TOUR: 'Velg type tur',
    VIEW_TOUR_DETAILS: 'Se detaljer om turen',
    BUS_DETAILS: 'FLERE DETALJER',
    VIEW_ROUTES: 'Se alle ruter',
    BUS_ROUTES: 'Bussruter',
    ATTRACTIONS_PREVIEW:
      'Den raskeste måten å se mer enn {0} attraksjoner på, inkludert',
    ROUTES: 'Ruter',
    COMBO_SUBTITLE: 'Spar mer med',
    COMBO_TITLE: 'Kombinasjonstilbud på hopp-på-hopp-av-turen',
    COMBO_DWEB_TITLE: 'Kombinasjonstilbud på hopp-på-hopp-av-turen',
    STOPS_AND_ATTRACTIONS: 'Stoppesteder og attraksjoner i nærheten',
    HOP_ON_OFF_AT: 'Hopp på og hopp av på alle disse {0}-stoppestedene',
    TIMINGS_FREQUENCY: 'Tidspunkter og hyppighet',
    TOUR_DURATION: 'Turens varighet',
    EVERY_X_MINS: 'Hvert {0}',
    VIEW_LOCATION: 'Vis beliggenhet',
    BANNER_SUBTEXT:
      'Den raskeste og mest praktiske måten å se alle de mest populære attraksjonene i byen på.',
    TOP_ATTRACTIONS: 'Vi har de mest populære attraksjonene',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Siste liten-bestilling',
        DESCRIPTION: 'Umiddelbar bekreftelse sendt til mobilen din',
      },
      COST_EFF: {
        NAME: 'Kostnadseffektive reiser',
        DESCRIPTION: 'Mange landemerker, én billett',
      },
      DAILY_RIDES: {
        NAME: 'Daglige ubegrensede reiser',
        DESCRIPTION: 'Utforsk byen i ditt eget tempo',
      },
      BOOK_RELAX: {
        NAME: 'Bestill og len deg tilbake',
        DESCRIPTION: '{0} millioner gjester har brukt oss så langt',
      },
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Flerspråklige ekspertguider',
    STL: 'Hopp over køen',
    PERSONALIZED: 'Personlig tilpasset opplevelse',
    LOCAL_FOOD: 'Lokal mat og kultur',
    MULTILINGUAL_GUIDES: 'Flerspråklige guider',
    CULINARY_EXPERTS: 'Kulinariske eksperter',
    SIGHTSEEING: 'Sightseeing og underholdning om bord',
    SIGHTSEEING_MEAL: 'Sightseeing og måltidsalternativer om bord',
    MULTILINGUAL_GT: 'Flerspråklige guidede turer',
    AUDIOGUIDE_COMMENTARY: 'Lydguide og kommentarer er tilgjengelig',
    ALL_TOP_ATTRACTIONS_COVERED: 'Alle de største attraksjonene dekkes',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Vanlig timeplan. Ubegrenset antall turer',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Tilgjengelighet i siste liten. Øyeblikkelig bekreftelse.',
    MULTI_ROUTES: 'Flere rutealternativer',
    HASSLE_FREE: 'Enkel bestilling',
    FREQUENT_DEPARTURES: 'Hyppige avganger',
    ONBOARD_AMENITIES: 'De beste fasilitetene om bord',
    FLEXI_TRAVEL: 'Fleksible reiser på flere ruter',
    FLEXI_EXCHANGE_CANCEL: 'Fleksible bytter og avbestillinger',
    EXTRA_DISCOUNT: 'Ekstra rabatter for ungdom, eldre og familier',
    PREPAID: 'Forhåndsbetalt bekvemmelighet',
    EASY_ACTIVATION: 'Enkel aktivering',
    INSTANT_CONNECTIVITY: 'Øyeblikkelig tilkobling med global dekning',
    ROUND_TRIP: 'Transport tur-retur',
    CULTURAL_EXPERIENCE: 'Autentiske kulturopplevelser',
    GUARANTEED_SEAT: 'Garantert sete',
    ONBOARD_WIFI: 'Wi-Fi og ladekontakter om bord',
    LUGGAGE_ASSISTANCE: 'Bagasjehjelp',
    TOP_ATTRACTIONS: 'Populære attraksjoner er inkludert',
    FREQ_DEP_MULTI_ROUTE: 'Hyppige avganger på flere ruter',
    CHARGING: 'Ladestasjon',
    WIFI: 'Wi-Fi-tilgang',
    FnB: 'Mat og drikke',
    LUXURY: 'Luksusopplevelse',
    FOOD_DRINK: 'Mat og drikke',
    PANAROMIC: 'Panoramautsikt over de største attraksjonene',
    PANAROMIC_2: 'Panoramautsikt',
    PANAROMIC_3: 'Panoramautsikt, åpent tak',
    BEVERAGES: 'Drikkevarer om bord',
    GOURMET: 'Gourmetmiddag',
    GOURMET_2: 'Gourmetmiddag og drikke',
    NIGHTTIME: 'Fantastisk utsikt om natten',
    ROMANTIC: 'Romantisk atmosfære',
    TRANSFERS: 'Transport er inkludert',
    CERTIFIED_OP: 'Autorisert drift',
    BIRD_EYE: 'Fugleperspektiv',
    MULTI_JUMP: 'Flere hoppetider',
    EXTREME_ADV: 'Ekstremsport',
    PHOTO_OP: 'Naturskjønne fotomuligheter',
    TOP_ATTRACTIONS_COVERED: 'Vi har de mest populære attraksjonene',
    LOCAL_CULTURE: 'Opplev lokal kultur',
    EXCLUSIVE_DISC: 'Eksklusive rabatter',
    EFFICIENT_PUBLIC_TRANSIT: 'Effektiv kollektivtransport',
    FREQUENT_SERVICE: 'Hyppig service',
    PREBOOKING: 'Enkel forhåndsbestilling',
    LOCAL_CULTURE_IMM: 'Fordyp deg i lokal kultur',
    DISCOVER_HIDDEN: 'Oppdag skjulte perler',
    CITY_SIGHTSEEING: 'Bysightseeing',
    OFFBEAT_ADV: 'Uvanlige eventyr',
    DRINK_DEALS: 'Drikkepakker',
    OFFBEAT_EXP: 'Uvanlig opplevelse',
    MULTIPLE_VARIETIES: 'Flere varianter er inkludert',
    HIDDEN_GEMS: 'Skjulte perler og uvanlige attraksjoner',
    EXPLORE_LOCAL: 'Utforsk lokale nabolag',
    CUSTOMIZED_TREATMENTS: 'Skreddersydde behandlinger',
    TRAINED_THERAPISTS: 'Utdannede terapeuter',
    HOLISTIC_WELLNESS: 'Holistisk velvære',
    FLEXIBLE_DURATION: 'Fleksibel varighet',
    MULTI_BOAT: 'Flere båtalternativer',
    SCENIC_ROUTES: 'Naturskjønne ruter',
    HANDS_ON: 'Praktisk læring',
    CULTURAL_CULINARY: 'Kulturell og kulinarisk innsikt',
    EXPERT_HOSTS: 'Ekspertverter',
    ADVENTURE_EXPERIENCE: 'Eventyrlig opplevelse',
    EQUIPMENT: 'Utstyr inkludert',
    SCENIC_FLYOVERS: 'Naturskjønne overflygninger',
    LIVE_COMMENTARY: 'Direktekommentarer',
    BEST_AERIAL_VIEWS: 'Beste utsikt fra luften',
    SAFE_CERT_OP: 'Sikker og sertifisert drift',
    HANDPICKED: 'Håndplukkede turer',
    EFFORTLESS: 'Uanstrengt planlegging',
    EXPERT_GUIDES: 'Ekspertguider. Unik innsikt',
    ALL_ATTR_ONE_CARD: 'Alle attraksjoner, ett kort',
    MULTI_CARD: 'Flere kortalternativer',
    COST_EFF: 'Kostnadseffektivt og praktisk',
    BEST_PRICES: 'De beste prisene',
    MULTI_TRANSPORT: 'Flere transportalternativer',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Alle',
    POPULAR_SUBCATEGORY: 'Populært innen {0}',
    TOP_CATEGORY: 'Mest populært innen {0}',
    ATTRACTIONS: 'Attraksjoner',
    ALL_SUBCATEGORY: 'Alle {0}',
    BROWSE_BY_CATEGORIES: 'Bla gjennom etter kategorier',
    TICKETS_FROM: 'Billetter fra',
    PRICE_LOW_HIGH: 'Pris (lav til høy)',
    PRICE_HIGH_LOW: 'Pris (høy til lav)',
    FILTERS: 'Filtre',
    RESET: 'Tilbakestill',
    APPLY: 'Bruk',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout bruker informasjonskapsler for å forbedre opplevelsen på nettstedet, en byte om gangen.',
    MOBILE: 'Informasjonskapsler i bruk.',
    LEARN_MORE: 'Finn ut mer.',
  },
  SHOW_UNAVAILABLE: 'Forestillingen er ikke tilgjengelig',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Utvalgte nyheter',
    ALL_NEWS: 'Alle nyheter',
    MORE_READS: 'Les mer',
    LOAD_MORE: 'Se flere',
    TRAILERS: 'Trailere',
    GET_YOUR_TICKETS: 'Kjøp billetter',
    POPULAR_SHOWS: 'Populære forestillinger',
    FEATURED: 'Utvalgte',
    RECENT_NEWS: 'Nyheter',
    SHOW_MORE_ARTICLES: 'Vis flere artikler',
    COLLAPSE_ALL: 'Skjul alle',
    REVIEWS: 'Anmeldelser',
    SHOW_ALL_REVIEWS: 'Vis alle anmeldelser',
    MAILER: {
      HEADING: 'De beste teatertilbudene og nyhetene rett i innboksen din',
      SUBHEADING:
        'Meld deg på e-postlisten vår for å få de siste nyhetene og de beste tilbudene på teaterforestillinger.',
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: '{0} anmeldelser',
    REVIEWS_COUNT: '{0} anmeldelser',
    AWESOME: 'Fantastisk',
    GOOD: 'Bra',
    AVERAGE: 'Gjennomsnittlig',
    POOR: 'Dårlig',
    TERRIBLE: 'Forferdelig',
    REVIEW_BY_HEADOUT: 'Dette synes vi: Anmeldelse av Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Dette sier folk',
    MOST_RELEVANT: 'Mest relevant',
    RATING_HIGH_TO_LOW: 'Vurdering: Høy til lav',
    RATING_LOW_TO_HIGH: 'Vurdering: Lav til høy',
    CRITIC_REVIEWS: 'Dette sier kritikerne',
    USER_REVIEWS: 'Brukeranmeldelser',
    CONTRIBUTORS_REVIEW: 'Anmeldelser fra bidragsytere',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Privat transport',
    SHARED_TRANSFERS: 'Delt transport',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Bestill på nettet',
        DESCRIPTION:
          'Få en rask og praktisk bestillingsopplevelse ved å bestille billetter på nettet.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Øyeblikkelig bekreftelse.',
        DESCRIPTION:
          'Få øyeblikkelig bekreftelse på bestillingen av flyplasstransport.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Praktisk henting',
        DESCRIPTION:
          'Unngå lange køer – kjøretøyet venter på deg på det valgte hentestedet.',
      },
      DROP_OFF: {
        TITLE: 'Levering',
        DESCRIPTION: 'Kom frem til destinasjonen raskt og komfortabelt.',
      },
    },
    SHARED_TRANSFERS_IN: 'Delt transport i {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      ' Et komfortabelt og kostnadseffektivt transportalternativ for flere passasjerer som reiser til eller fra en flyplass.',
    PRIVATE_TRANSFERS_IN: 'Privat transport i {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      ' En praktisk, personlig transporttjeneste for enkeltpersoner eller små grupper, som tilbyr en komfortabel og direkte reise til og fra flyplassen.',
    ANYWHERE_IN_THE_CITY: 'Hvor som helst i byen',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Flere kjøretøyalternativer',
      FREE_CANCELLATION: 'Gratis avbestilling',
    },
    SEAMLESS_TRANSFERS: 'Sømløs og pålitelig transport over hele verden.',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Velg den beste flyplasstransporten for deg',
    HASSLE_FREE_TRANSFER: 'Problemfri flyplasstransport',
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Uanstrengt flyplasstransport i {0} fra',
    BUSES: 'busser',
    TRAINS: 'tog',
    PRIVATE_TAXIS: 'private taxier',
    BUS_TRAIN: 'Buss/tog',
    PRIVATE_TAXI: 'Privat taxi',
    FROM: 'Fra',
    SELECT_PICKUP: 'Velg henting',
    TO: 'Til',
    SELECT_DROPOFF: 'Velg avlevering',
    ENTER_DESTINATION: 'Skriv inn destinasjonen',
    ENTER_PICKUP: 'Skriv inn hentested',
    PICKUP_DATE: 'Dato for henting',
    SELECT_DATE: 'Velg dato',
    PICKUP_TIME: 'Tidspunkt for henting',
    SELECT_TIME: 'Velg tidspunkt',
    GUEST: 'Gjest',
    GUESTS: 'Gjester',
    ADD_GUESTS: 'Legg til gjester',
    ADULT_CHILD: 'Voksen/barn',
    EXPLORE_TRANSFERS: 'Utforsk transport og mer',
    COMBOS_AND_EXTRAS: 'Kombinasjoner og tillegg',
    YOUR_RIDE_DOORSTEP: 'Henting på dørstokken',
    COMFORTABLE_RIDE:
      'Bestill en komfortabel privat taxi til og fra større flyplasser i {0}',
    TRUSTED_DRIVERS: 'Sjåfører du kan stole på',
    RIDES_24_7: 'Tilgjengelige reiser døgnet rundt',
    FLIGHT_TRACKING: 'Flysporing',
    KNOW_MORE: 'Finn ut mer',
    RESERVE_YOUR_RIDE: 'Reserver reise',
    TRANSFER_OPTIONS: 'Fant transportalternativer',
    TRANSFERS_AVAILABLE_PLURAL: '{0} tilgjengelige reisermuligheter',
    TRANSFERS_AVAILABLE_SINGULAR: '1 tilgjengelig reisemulighet',
    TRUSTED_PARTNERS: 'Mer enn 35 betrodde partnere, {0}',
    WORLDWIDE: 'over hele verden',
    COMFORTABLE_RIDES: 'Komfortable reiser',
    FREQUENT_DEPARTURES: 'Hyppige avganger',
    MULTIPLE_TRANSPORT_OPTIONS: 'Flere transportalternativer',
    AND_MANY_MORE: 'Og mange flere',
    ADD_PICKUP_LOCATION: 'Legg til hentested',
    ADD_DROPOFF_LOCATION: 'Legg til avleveringssted',
    SELECT_PICKUP_DATE_AND_TIME: 'Velg dato og tidspunkt for henting',
    SELECT_A_DATE: 'Velg en dato',
    TRAIN_STATION: 'Togstasjon',
    BUS_STOP: 'Busstopp',
    ADD_RETURN: 'Legg til returreise',
    HEADS_UP: 'Advarsel!',
    ADDED_RETURN_TRIP: 'Du har lagt til en returreise!',
    RETURN_NOTE: 'Vi viser detaljene om returreisen i de neste stegene.',
    OKAY_I_UNDERSTAND: 'OK, jeg forstår',
    SERVING_GUESTS: 'Hjelper {0} av {1} verden over',
    GUESTS_COUNT: 'Mer enn 220,000 gjester',
    CITIES_COUNT: 'Mer enn 55 byer',
    PARNTER_WITH_BEST:
      'Vi samarbeider kun med de beste, for å sørge for at du får en uforglemmelig opplevelse Vi tar oss av detaljene, slik at du kan slappe av og nyte reisen',
  },
  PC_EXP: {
    SHOW_INCL: 'Vis inkluderinger og viktig informasjon',
    CLEAR: 'Tøm',
    ALL_EXPERIENCES: 'Alle opplevelser',
    FILTER_BY_CATEGORIES: 'Filtrer etter kategorier',
    CATEGORIES: 'Kategorier',
    COMBOS: {
      HEADING: 'Alle gode ting er to. Akkurat som sparekombinasjonene våre.',
      DESCRIPTOR_1: 'Pengesparende tilbud',
      DESCRIPTOR_2: 'Planlegg reisen din bedre',
    },
  },
  TOP: 'Mest populært innen {0}',
  VIEW_CALENDAR: 'Vis kalender',
  SHOWS_CALENDAR: 'Viser kalender',
  IN: 'i',
  SEATS: 'Seter',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Innholdsguide',
    QUICK_INFORMATION: 'Hurtiginformasjon',
    PEAK: 'Rushtid',
    OFF_PEAK: 'Utenfor rushtid',
    ADDRESS: 'ADRESSE',
    RECOMMENDED_DURATION: 'ANBEFALT VARIGHET',
    VISITORS_PER_YEAR: 'BESØKENDE PER ÅR',
    NUMBER_OF_ENTRANCES: 'ANTALL INNGANGER',
    EXPECTED_WAIT_TIME_STANDARD: 'FORVENTET VENTETID - NORMAL',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE: 'FORVENTET VENTETID - HOPP OVER KØEN',
    UNESCO_YEAR: 'UNESCO-ÅR',
    ARCHITECTURE_STYLE: 'ARKITEKTURSTIL',
    TIMINGS: 'Tidspunkter',
    SIZE_HEIGHT: 'STØRRELSE/HØYDE',
    TICKETS: 'BILLETTER',
    FUN_FACTS: 'Morsomme fakta',
    DID_YOU_KNOW: 'Visste du det?',
    MORE_INTERESTING_FACTS: 'Flere interessante fakta',
    PLAN_YOUR_VISIT: 'Planlegg besøket',
    ALSO_KNOWN_AS: 'Også kjent som',
    FOUNDED_ON: 'Grunnlagt i',
    FOUNDED_BY: 'Grunnlagt av',
    FROM: 'Fra',
    CLOSED_TODAY: 'Stengt i dag',
    TODAY: 'I dag',
    CLOSED: 'Stengt',
    OPEN: 'Åpent',
    LAST_ADMISSION: 'Seneste inngangstid',
    DAYS: 'Dager',
    BEST_TIME_TO_VISIT: 'Beste tidspunkt å besøke',
    WEEKDAY_VS_WEEKEND: 'Ukedag vs. helg',
    PEAK_VS_LOW_SEASON: 'Høysesong vs. lavsesong',
    PLEASANT: 'Hyggelig',
    CROWDED: 'Travelt',
    VERY_CROWDED: 'Svært travelt',
    LOW_SEASON: 'Utenfor sesong',
    MID_SEASON: 'Moderat sesong',
    PEAK_SEASON: 'Høysesong',
    TO: 'TIL',
    LOWER_TO: 'til',
    LAST_ENTRY: 'siste inngangstid',
    SUBATTRACTIONS: 'Underattraksjoner',
    INCLUDED_WITH_TICKETS: 'Inkludert med {0}-billetter',
    INCLUDED_WITH_SOME_TICKETS: 'Inkludert med noen {0}-billetter',
    EXPLORE_ALL_POI_TICKETS: 'Utforsk billetter og turer for {0} og {1}',
    EXPLORE_PARENT_TICKETS: 'Utforsk billetter og turer for {0}',
    SELECT_YOUR_EXPERIENCE: 'Velg opplevelsen din',
    OPERATING_HOURS: 'Åpningstider',
    SEE_MORE: 'Se mer',
    MORE_INSIGHTS: 'Mer innsikt',
  },
  OFF_PERCENT: '{0} % rabatt',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Seteplan',
    CAPACITY: 'Kapasitet: {0} seter',
    WHATS_ON: 'Hva skjer',
    CATEGORIES: 'Kategorier',
  },
  NEXT: 'Neste',
  PREVIOUS: 'Tidligere',
  ITINERARY: {
    TAB: 'Reiseplan',
    HEADING: 'Reiseplan for opplevelsen',
    VIEW_ITINERARY: 'Vis reiseplan',
    PASSES_BY_SECTION_HEADING: 'Reiser forbi',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Høydepunkter',
      NEARBY_THINGS_TO_DO: 'Ting å gjøre i nærheten',
      THINGS_TO_DO: 'Ting å gjøre',
    },
    STOP_CARD: {
      TITLE: {
        START: 'STARTSTED',
        END: 'ENDESTED',
        STARTING_POINT: 'STARTSTED',
        STOP: 'STOPP',
        ENDING_POINT: 'ENDESTED',
        PASSING_BY: 'REISER FORBI',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} startsteder tilgjengelig',
        END: '{0} endesteder tilgjengelig',
      },
    },
    GET_DIRECTION: 'Få veibeskrivelse',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} timer {1} minutter',
        WITHOUT_HOURS: '{0} minutter',
        WITHOUT_MINS: '{0} timer',
      },
      ATTRACTIONS_COUNT: '{0} attraksjoner',
      ACTIVITIES_COUNT: '{0} aktiviteter',
      TOTAL_DURATION: 'TOTAL VARIGHET',
      FREQUENCY: 'HYPPIGHET',
      FIRST_DEPARTURE: 'FØRSTE AVGANG',
      LAST_DEPARTURE: 'SISTE AVGANG',
      FIRST_DEPARTURE_TIME: 'FØRSTE AVGANG',
      LAST_DEPARTURE_TIME: 'SISTE AVGANG',
      MODE_OF_TRANSPORT: 'TRANSPORTMIDDEL',
      FOOD_AND_DRINKS: 'MAT OG DRIKKE',
    },
    WALK_DURATION: '{0} gange',
    MORE: '{0} mer',
    TIMELINE_VIEW: 'Tidslinje',
    MAP_VIEW: 'Kart',
    MAP_OVERLAY: 'Bruk CTRL/⌘ + skroll for å flytte kartet',
    VIEW_EXPERIENCE_MAPPED_OUT: 'Vis full oversikt over opplevelsen din.',
    OPEN_MAP_VIEW: 'Åpne kart',
    START_POINT_SAME_AS_END_POINT: 'Sluttstedet er det samme som startstedet',
  },

  CITY_AIRPORT_TRANSFERS: 'Flyplasstransport for {0}',
  BANNER_SUBTEXT:
    'Få en avslappet reise med pålitelig og forhåndsbestilt flyplasstransport.',
  BEST_PRICES: 'De beste prisene, ingen skjulte kostnader',
  BEST_PRICES_SUBTEXT:
    'Faste priser og ingen overraskelser. Vi tilbyr førsteklasses service til konkurransedyktige priser.',
  FREE_WAIT_TIME: 'Gratis ventetid, ingen grunn til å stresse',
  FREE_WAIT_TIME_SUBTEXT:
    'Du får 45 minutter med gratis ventetid mens du henter bagasjen',
  COMFORTABLE_RIDE: 'Komfortabel reise',
  COMFORTABLE_RIDE_SUBTEXT:
    'Reis i stil med et stort utvalg førsteklasses kjøretøy, kjørt av håndplukkede og erfarne sjåfører.',
  EXCELLENCE_HEADING: 'Kjent for utmerkethet og pålitelighet',
  ACTIVE_CITIES: 'aktive byer over hele verden',
  CUSTOMERS_SERVED: 'betjente kunder',
  YEARS_OF_SERVICE: 'år med utmerket service',
  FIND_YOUR_RIDE: 'Den perfekte reisemåten for deg',
  FIND_YOUR_RIDE_SUBTEXT:
    'Fra minibusser til sedaner. Velg en bil som rommer bagasjen og reisefølget.',
  TRUST_TOOLTIP_HEADER: 'Hvordan samler vi inn anmeldelser?',
  TRUST_TOOLTIP_CONTENT:
    'Disse vurderingene inkluderer verifiserte anmeldelser fra både Headout-gjester og de lokale partnerne våre som leder disse opplevelsene. Alle anmeldelsene kommer fra ekte reisende som har deltatt på opplevelsen.',
  REVIEW_SECTION_HEADER: 'Dette sier gjestene våre',
  TRUST_VB_TAG: 'Verifisert bestilling',
  SNAPSHOTS_SECTION_HEADER: 'Instantanee de la oaspeții noștri',
  AGGREGATED_COUNTRIES:
    'Gjester fra <strong>{0}</strong> og <strong>over {1} land</strong> har elsket denne opplevelsen',
  REVIEWS_SECTION: {
    SECTION_HEADING: 'Millioner av mennesker elsker å reise med oss',
    SORTING: {
      MOST_RELEVANT: 'Mest relevant',
      MOST_RECENT: 'Nyest',
      SORT_BY: 'Sorter etter',
    },
    FILTERING: {
      GREATER_THAN_4: '4+ stjerner',
      EQUAL_TO_3: '3 stjerner',
      LESS_THAN_3: '< 3 stjerner',
      WITH_IMAGES: 'Med bilder',
    },
    EMPTY_STATE: {
      SUB_HEADING:
        'Vi fant ingen anmeldelser som samsvarer med filtrene du valgte.',
      CTA: 'Vis alle anmeldelser',
    },
    VERIFIED_REVIEW: 'Verifisert partneranmeldelse',
    REVIEW_SECTION_HEADER: 'Dette sier gjestene våre',
    TRUST_VB_TAG: 'Verifisert bestilling',
    HEADING: 'Fra fornøyde kunder',
    HEADING_BOOSTER_TEXT: 'Elsket av over 35 millioner',
    SEE_MORE_BUTTON_TEXT: 'Show all {0} reviews',
    REVIEW_CARD_MODAL_TITLE: 'Review',
  },
  POWERED_BY: 'levert av',
  BOOKING_PAGE_TIME: {
    HOUR: ' time',
    HOURS: ' timer',
    MINUTE: ' minutt',
    MINUTES: ' minutter',
  },
  LTT_SPECIAL_OFFER: 'Spesialtilbudet',
};

export default no;
