const pl = {
  AUDIO_GUIDE: {
    BANNER: 'Darmowy audioprzewodnik',
    PRODUCT_SUFFIX: 'z audioprzewodnikiem',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Autoryzowany i zaufany partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Autoryzowany odsprzedawca',
    SUB_TEXT:
      'Autentyczne doświadczenia zaufanych i zweryfikowanych partnerów.',
  },
  REVIEWS: 'ocen(-y)',
  AVAILABLE: 'Dostępne',
  BANNER_CTA: 'Kup bilety',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout to marka, której zaufały miliony odwiedzających na całym świecie, oferująca niezwykłe aktywności, podczas których można poznać tę atrakcję.',
    NON_PARTNERED_SENSITIVE:
      'Headout to marka, której zaufały miliony odwiedzających na całym świecie, oferująca niezwykłe aktywności, podczas których można poznać tę atrakcję. To nie jest strona internetowa obiektu.',
    PARTNERED_NON_SENSITIVE:
      'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje niezwykłe aktywności, pozwalające Ci poznać tę atrakcję.',
    PARTNERED_SENSITIVE:
      'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje niezwykłe aktywności, pozwalające Ci poznać tę atrakcję. To nie jest strona internetowa obiektu.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje wybór najlepszych aktywności, pozwalających Ci poznać tę atrakcję.',
  BOOK_NOW_CTA: 'Zarezerwuj teraz',
  BUY_TICKETS_CTA: 'Kup bilety',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Możesz anulować te bilety do {0} godzin przed rozpoczęciem aktywności, aby uzyskać pełen zwrot.',
    CANCELLABLE_ANYTIME:
      'Darmowe anulowanie w dowolnym momencie przed rozpoczęciem aktywności',
    CANCELLABLE_DAYS:
      'Możesz anulować te bilety do {0} dni przed rozpoczęciem aktywności, aby uzyskać pełen zwrot.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Tych biletów nie można anulować. Jednak okres ich ważności został przedłużony.',
    HEADING: 'Zasady zmiany rezerwacji',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Tych biletów nie można anulować. Jednak można zmienić ich termin do {0} godz. przed rozpoczęciem aktywności.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Tych biletów nie można anulować ani przełożyć.',
    VALID_UNTIL_DATE:
      'Tych biletów nie można anulować. Jednak możesz użyć ich w dowolnym momencie do {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Tych biletów nie można anulować. Jednak możesz użyć ich w dowolnym momencie w ciągu następnych {0} dni.',
    VALID_WITHIN_NEXT_MONTHS:
      'Tych biletów nie można anulować. Jednak możesz użyć ich w dowolnym momencie w ciągu następnych {0} miesięcy.',
  },
  CANCELLATION_POLICY_HEADING: 'Zasady anulowania',
  CASHBACK: '{0}% cashbacku',
  CASHBACK_INFO:
    'Otrzymasz cashback <strong>{0}%</strong>, gdy zarezerwujesz tę aktywność. Twój cashback zostanie automatycznie przyznany Twojemu kontu Headout i&nbsp;będziesz móc wykorzystać go na dowolne zamówienie na Headout w&nbsp;przyszłości.',
  CATEGORY_SLIDER_HEADING:
    'Klienci, którzy zarezerwowali ten spektakl, wyświetlili również',
  CHECK_AVAIL: 'Sprawdź dostępność',
  CITY_PAGE: {
    BANNER_TITLE: 'Doświadcz tego, co do zaoferowania ma',
    TOP_ATTRACTIONS: 'Najpopularniejsze atrakcje',
    GO_BEYOND: 'Podróżuj dalej niż {0}',
    ALL_DAY_TRIPS: 'Zobacz wszystkie wycieczki całodzienne',
    CITIES_NEARBY: 'Miasta w pobliżu',
    POPULAR_CATEGORIES: 'Popularne kategorie',
    GO_TO_GUIDE: '{0}: przewodnik po mieście',
    VIEW_TRAVEL_GUIDE: 'Wyświetl przewodnik turystyczny',
    EXPLORE: 'Poznaj miasto {0}',
    GUIDE_SUBHEADING:
      'Odkrywanie atrakcji w mieście {0} nigdy nie było łatwiejsze! Nasz przewodnik turystyczny: {0} zawiera wszystko, co musisz wiedzieć o mieście – co jeść, gdzie iść, jak się tam dostać, gdzie się zatrzymać i wiele więcej!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Informacje ogólne',
      WHERE_TO_EAT: 'Jedzenie',
      WHERE_TO_STAY: 'Zakwaterowanie',
      THINGS_TO_DO: 'Atrakcje',
      WEATHER: 'Najlepsza pora na wizytę',
      NEIGHBOURHOODS: 'Lokalna społeczność',
      TRANSPORTATION: 'Poruszanie się',
      TRIP_PLANNER: 'Plan podróży',
      FAMILY_TRAVEL: 'Podróżowanie z dziećmi',
      TRAVEL_TIPS: 'Porady i wskazówki dla podróżujących',
      SHOPPING: 'Zakupy',
      ART_AND_CULTURE: 'Sztuka i kultura',
    },
    MAILER: {
      HEADING:
        '{0}: inspiracje podróżnicze prosto do Twojej skrzynki odbiorczej',
      SUBHEADING:
        'Popularne atrakcje, sposoby na budżetowe podróżowanie, transport publiczny, najlepsze restauracje i hotele, wskazówki dotyczące kultury i więcej!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Dowiedz się więcej o wymaganiach wizowych, wymianie walut, różnicach stref czasowych i nie tylko, by cieszyć się bezproblemową podróżą i przyjemnym pobytem.',
    WHERE_TO_EAT:
      'Poznaj tętniącą życiem scenę kulinarną, delektując się różnorodnymi smakami i próbując lokalnych przysmaków w każdym zakątku miasta {0}.',
    WHERE_TO_STAY:
      'Odkryj najlepsze zakwaterowanie w mieście {0}, oferujące komfort, wygodę i niezapomniane wrażenia podczas pobytu.',
    THINGS_TO_DO:
      'Weź udział w mnóstwie emocjonujących aktywności, które trafią we wszystkie gusta, zapewniając niezapomniany czas.',
    WEATHER:
      'Mądrze zaplanuj swoją wycieczkę i w pełni wykorzystaj swoją w wizytę, ponieważ {0} oferuje magiczne doświadczenia przez cały rok.',
    NEIGHBOURHOODS:
      'Poznaj różnorodne społeczności lokalne i tętniące życiem dzielnice, którym {0} zawdzięcza swój wyjątkowy charakter.',
    TRANSPORTATION:
      'Poruszaj się po mieście z łatwością, korzystając z wydajnego systemu transportowego, który oferuje {0} i wygodnie odkrywaj wszystkie atrakcja.',
    TRIP_PLANNER:
      'Wykorzystaj swój czas z dobrze przemyślanym planem podróży i ciesz się wszystkim, co do zaoferowania ma {0}.',
    FAMILY_TRAVEL:
      'Wyrusz na rodzinną przygodę z licznymi atrakcjami, parkami i innymi rozrywkami, które zaspokoją potrzeby dzieci w każdym wieku.',
    TRAVEL_TIPS:
      'Poznaj wskazówki lokalsów i triki podróżnicze, żeby Twoja wizyta w mieście {0} była naprawdę wyjątkowa.',
    SHOPPING:
      'Udaj się do raju dla kupujących z przeróżnymi butikami, targami i centrami handlowymi, oferującymi wszystko od lokalnego rzemiosła po luksusową modę.',
    ART_AND_CULTURE:
      'Zanurz się w bogatej scenie artystycznej i kulturalnej, od urzekających muzeów po tętniące życiem festiwale celebrujące dziedzictwo miasta {0}.',
  },
  CLOSE: 'Zamknij',
  COLLECTION_SLICE_HEADING: 'Popularne aktywności w mieście {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Wybierz',
    SELECT_OPTION: 'Wybierz opcję',
    SELECT_TICKET: 'Wybierz bilet',
    SELECT_PREFERENCE: 'Wybierz swoje preferencje',
  },
  COMPARE_ALL_DETAILS: 'Porównaj wszystkie szczegóły',
  COVID19_ALERT: {
    KEY_TEXT: 'Aktualności dotyczące COVID-19',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Jesteś naszym priorytetem. Zapoznaj się z naszą stroną pomocy, aby znaleźć najnowsze informacje na temat naszych elastycznych zasad anulowania rezerwacji',
  },
  CURRENCY: 'Waluta',
  CUSTOMER_REVIEW_HEADING: 'Opinie klientów',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioprzewodnik',
    DURATION: 'Czas trwania: {0}',
    EXTENDED_VALIDITY: 'Przedłużony okres ważności',
    FLEXIBLE_DURATION: 'Elastyczny czas trwania',
    FREE_CANCELLATION: 'Bezpłatne anulowanie',
    GUIDED_TOUR: 'Wycieczka z przewodnikiem',
    HOTEL_PICKUP: 'Odbiór z hotelu',
    INSTANT_CONFIRMATION: 'Natychmiastowe potwierdzenie',
    MEALS_INCLUDED: 'Posiłki wliczone w cenę',
    MOBILE_TICKET: 'Bilet mobilny',
    SKIP_THE_LINE: 'Omiń kolejkę',
    TRANSFERS: 'Transfery wliczone w cenę',
  },
  DURATION: 'Czas trwania',
  EARLIEST_AVAILABILITY: 'Najwcześniejszy dostępny termin',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Wpisz swój adres e-mail',
    SIGN_UP: 'Zapisz się',
    THANK_YOU: 'Dziękujemy!',
    SUBSCRIBED_MSG: 'Zasubskrybowano pomyślnie',
    ERROR_MSG: 'Podaj prawidłowy adres e-mail',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Bilety do teatru na Broadwayu',
    },
    LTT: {
      MB_NAME: 'Bilety do teatru w Londynie',
    },
  },
  EXCLUSIONS: 'Nie w cenie',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '10 milionów +',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100% bezpieczne',
    HEADING_SUPPORT: 'Centrum pomocy 24/7',
    SUB_HEADING_CUSTOMER: 'Klienci zadowoleni z 10 000+ aktywności',
    SUB_HEADING_RATING:
      '5000+ zweryfikowanych opinii z doskonałym wynikiem 90%',
    SUB_HEADING_SAFE:
      'Wszystkie aktywności na świeżym powietrzu są w 100% bezpieczne',
    SUB_HEADING_SUPPORT:
      'Masz pytanie? Czatuj na żywo z lokalnymi ekspertami, gdzie chcesz i kiedy chcesz',
  },
  FLEXIBLE: 'Elastyczność',
  FOOTER: {
    CALL_US: 'Zadzwoń do nas',
    CHAT_WITH_US: 'Czatuj z nami',
    COMPANY_DETAILS: 'Dane firmy',
    INFORMATION: 'Informacja',
    DISCLAIMER:
      'Ta strona nie jest oficjalną stroną internetową <attraction>. Jest prowadzona przez Headout, które współpracuje z operatorami atrakcji i wycieczek, aby zapewniać niezwykłe doświadczenia w kilku kliknięciach.',
    EMAIL_US: 'Napisz do nas',
    GET_HELP: 'Uzyskaj pomoc',
    LEGAL: 'Informacje prawne',
    GMAPS_DISCLAIMER:
      'Wszystkie zrzuty ekranu map znajdujące się na tej stronie są pozyskiwane z Google zgodnie z zasadami dozwolonego użytku. Wszelkie prawa do takich zrzutów ekranu należą do konkretnej platformy, a ich wykorzystanie służy wyłącznie celom informacyjnym lub orientacyjnym.',
    PRIVACY_POLICY: 'Polityka prywatności',
    QUICK_LINKS: 'Szybkie linki',
    TERMS_AND_CONDITIONS: 'Warunki korzystania',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Stworzone z ',
    ALL_OVER_THE: ' na całym ',
    TERMS_OF_USAGE: 'Warunki korzystania',
    GET_HELP_24_7: 'Wsparcie',
    HELP_CENTER: 'Centrum pomocy',
    COMPANY: 'Dane firmy',
    WE_ACCEPT: 'Opcje płatności',
    DOWNLOAD_HEADOUT: 'Pobierz aplikację Headout',
    SCAN_CODES: 'Skanuj kody',
  },
  FREE_CANCELLATION: 'Bezpłatne anulowanie',
  FREE_CANCELLATION_SUBTEXT:
    'Rozumiemy, że plany się zmieniają – anuluj bezpłatnie do 72 godzin przed wydarzeniem.',
  FROM: 'Od',
  GET_CASHBACK: 'Zdobądź {0}% cashbacku',
  GROUP_TICKETS: 'Bilety grupowe',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '18+ milionów zadowolonych klientów',
    SUB_TEXT:
      'Zadowolenie klientów jest naszym priorytetem. Dołącz do grona naszych szczęśliwych klientów.',
  },
  HELP_CENTER: {
    MAIN_TEXT: 'Centrum pomocy 24/7',
    SUB_TEXT:
      'Masz pytania lub obawy? Możesz liczyć na naszą pomoc 24/7 — przez telefon, czat oraz e-mail.',
  },
  INCLUSIONS: 'W cenie',
  LANGUAGE: 'Język',
  LANGUAGES: {
    ENGLISH: 'angielski',
    SPANISH: 'hiszpański',
    FRENCH: 'francuski',
    ITALIAN: 'włoski',
    GERMAN: 'niemiecki',
    PORTUGUESE: 'portugalski',
    NEDERLANDS: 'holenderski',
    POLISH: 'polski',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Wycieczka dostępna w języku: {0}',
  LISTICLES: {
    KNOW_MORE: 'Dowiedz się więcej',
    SEATING_CHART: 'Rozkład miejsc',
    WHY_BOOK_FROM_US: 'Czemu warto zarezerwować u nas?',
  },
  MORE_DETAILS: 'Więcej szczegółów',
  MORE_CURRENCIES: 'Więcej walut',
  NEW: 'NOWOŚĆ',
  NEW_ARRIVAL: 'Nowość',
  NEXT_AVAILABLE: 'Następne dostępne: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout to marka, której zaufało ponad 15 milionów odwiedzających, oferująca starannie dobraną selekcję najlepszych aktywności. To nie jest strona internetowa obiektu.',
  NO_RESULT_FOUND: 'Hmm, nie znaleziono wyników.',
  OFF: 'zniżki',
  OPEN_DATED_DESCRIPTOR: 'Rezerwuj z elastycznością - nie musisz wybierać daty',
  OPENING_DATE: 'Data premiery',
  OPENING_ON: 'Premiera',
  OPENS: 'Premiera',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje wybór najlepszych aktywności, pozwalających Ci poznać tę atrakcję. To nie jest strona internetowa obiektu.',
  POPULAR_CURRENCIES: 'Popularne waluty',
  PRICES_STARTING: 'Ceny od',
  PROMO_CODES: {
    APPLY_CODE: 'ZASTOSUJ KOD',
    APPLIED: 'ZASTOSOWANO',
    TOOL_TIP_INFO: 'Ta zniżka zostanie zastosowana przy finalizacji zamówienia',
    DESCRIPTION: {
      ABSOLUTE: 'Uzyskaj {0} zniżki',
      CAPPED: 'Uzyskaj {0}% zniżki, do {1}',
      PERCENTAGE: 'Uzyskaj {0}% zniżki',
    },
    REMOVE: 'USUŃ',
  },
  RATINGS: 'Oceny: {0}',
  READ_MORE: 'Czytaj więcej',
  READ_MORE_TEXT: 'Czytaj więcej',
  READ_LESS: 'Czytaj mniej',
  VIEW_DETAILS: 'Wyświetl szczegóły',
  REOPENING: 'Ponowne rozpoczęcie',
  REOPENING_DATE: 'Data ponownego rozpoczęcia',
  REOPENING_ON: 'Ponowne rozpoczęcie',
  REOPENS: 'Rozpoczyna się ponownie',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      CTA_URL:
        'https://www.austria.info/en/service-and-facts/coronavirus-information/entry-regulations',
      TEXT: 'Obowiązują przepisy dotyczące 2G: dostęp do zakwaterowania, instytucji kultury, restauracji/barów jest możliwy tylko z dowodem pełnego zaszczepienia lub przeszłego zakażenia. Ujemny wynik testu na obecność COVID-19 nie jest już wystarczający.',
    },
    AU_DESCRIPTION: {
      CTA_URL:
        'https://www.smartraveller.gov.au/COVID-19/COVID-19-vaccinations',
      TEXT: 'Odwiedzający w wieku 16 lat i starsi muszą zaprezentować dowód szczepienia przeciw COVID-19 lub zwolnienie ze szczepienia. ',
    },
    BANNER_CTA: 'Dowiedz się więcej',
    BERLIN_DESCRIPTION: {
      CTA_URL:
        'https://www.berlin.de/en/news/coronavirus/7081102-6098215-berlin-introduces-extensive-2G-rule.en.html',
      TEXT: 'Obowiązują zasady 2G: wstęp mają jedynie w pełni zaszczepieni odwiedzający i ozdrowieńcy, którzy przedstawią odpowiednie certyfikaty. Odwiedzający poniżej 18 roku życia lub ci, którzy nie mogą być zaszczepieni z powodów medycznych, muszą przedstawić przy wejściu negatywny wynik testu na COVID. Ci, którzy z powodów medycznych nie mogą się zaszczepić, również powinni to udowodnić, prezentując odpowiednie zwolnienie ze szczepienia przed wejściem.',
    },
    CTA_TEXT: 'Szczegóły bezpieczeństwa',
    DESCRIPTION_CTA: 'Dowiedz się więcej.',
    EU_DESCRIPTION: {
      CTA_URL:
        'https://www.diplomatie.gouv.fr/en/coming-to-france/coronavirus-advice-for-foreign-nationals-in-france/coronavirus-statements/article/applying-for-a-covid-certificate-if-you-were-vaccinated-abroad-procedure-for',
      TEXT: 'Od 21 lipca 2021 r. wszyscy odwiedzający w wieku 12 lat i starsi muszą zaprezentować unijny certyfikat COVID. ',
    },
    EU_HEADING: 'Wymagany unijny certyfikat COVID',
    EU_PREFIX: 'Uwaga: ',
    EXPERIENCE_DESCRIPTION:
      'Ta aktywność została zweryfikowana jako aktywność zgodna z najwyższymi standardami bezpieczeństwa według lokalnych przepisów oraz Światowej Organizacji Zdrowia',
    FLAG_TEXT: 'Największe bezpieczeństwo',
    GENERAL_DESCRIPTION:
      'Wszystkie aktywności z tą odznaką zostały zweryfikowane jako aktywności zgodne z najwyższymi standardami bezpieczeństwa według lokalnych przepisów dotyczących zdrowia.',
    HEADING: 'Najwyższe standardy bezpieczeństwa',
    IT_DESCRIPTION: {
      CTA_URL: 'https://www.dgc.gov.it/web/per-cosa-serve.html#viaggi',
      TEXT: 'Od 6 sierpnia 2021 r. wszyscy odwiedzający w wieku 11 lat i starsi muszą zaprezentować unijny certyfikat COVID, czyli tak zwany paszport covidowy. ',
    },
    IT_PREFIX: 'Uwaga: ',
    MOBILE_HEADING: 'Bezpieczne aktywności',
    MODAL: {
      BADGE_DESCRIPTION:
        'Ta odznaka na aktywności potwierdza, że standardy bezpieczeństwa zostały przez nas zweryfikowane',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Wszystkie sprzęty, pojazdy i często dotykane powierzchnie są odkażane po każdym użyciu. Po prostu usiądź wygodnie i ciesz się wydarzeniem.',
          HEADING: 'Wszystkie powierzchnie i sprzęty są odkażane',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Wszystkie sprzęty dostępne podczas aktywności są starannie odkażane po każdym użyciu. Zawsze.',
          HEADING: 'Wszystkie powierzchnie i sprzęty są odkażane',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Wszystkie pojazdy dostępne podczas aktywności są starannie odkażane po każdym użyciu. Zawsze',
          HEADING: 'Wszystkie pojazdy są odkażane',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Podczas tej bezpiecznej aktywności będziesz mieć dostęp do mydła i stacji sanitarnych. Bez obaw! ',
          HEADING: 'Mydło oraz stacje sanitarne dostępne w obiekcie',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Maski są obowiązkowe dla wszystkich odwiedzających oraz pracowników podczas tej aktywności. Dzięki temu wszyscy mogą bawić się przy zachowaniu bezpieczeństwa.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Nasi partnerzy, którzy zostali zweryfikowani jako „Bezpieczne aktywności”, przestrzegają lokalnych regulacji dotyczących noszenia maseczek. Jeśli jest to obowiązkowe, wszyscy odwiedzający i pracownicy noszą maseczki. Robią, co w ich mocy, by zapewnić Ci komfort i bezpieczeństwo.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Maski są obowiązkowe dla wszystkich odwiedzających podczas tej aktywności. Dzięki temu wszyscy mogą bawić się przy zachowaniu bezpieczeństwa.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Wszyscy pracownicy podczas tej aktywności noszą maseczki na twarzy, żeby zapewnić Ci maksymalną zabawę i minimalne zmartwienia.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Podczas tej wycieczki obowiązują zasady dotyczące dystansu społecznego. Obowiązują ograniczenia ilości osób, aby umożliwić przestrzeganie zasad dotyczących dystansu społecznego.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Podczas tej wycieczki obowiązują zasady dotyczące dystansu społecznego. Obowiązują ograniczenia ilości osób, aby umożliwić przestrzeganie zasad dotyczących dystansu społecznego. Aby to umożliwić, wizyty w dużych grupach nie są dozwolone.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Podczas tej aktywności cały czas przestrzega się zasad dotyczących dystansu społecznego.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Podczas tej aktywności cały czas przestrzega się zasad dotyczących dystansu społecznego. Aby to umożliwić, mogą obowiązywać ograniczenia dotyczące ilości osób. Oddychaj bez obaw.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Podczas tej aktywności cały czas przestrzega się zasad dotyczących dystansu społecznego. Aby to umożliwić, wizyty w dużych grupach nie są dozwolone.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Temperatura wszystkich odwiedzających zostanie sprawdzona na początku wycieczki, aby zapewnić wszystkim bezpieczeństwo. Temperatura wszystkich pracowników jest wielokrotnie sprawdzana każdego dnia.',
          HEADING: 'Obowiązuje sprawdzanie temperatury',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Temperatura wszystkich odwiedzających zostanie sprawdzona na początku wycieczki, aby zapewnić wszystkim bezpieczeństwo. ',
          HEADING: 'Obowiązuje sprawdzanie temperatury',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Temperatura wszystkich pracowników jest wielokrotnie sprawdzana. Pracownikom, których temperatura przekracza limit, zabrania się wstępu; są proszeni o zostanie w domu do momentu powrotu do zdrowia.',
          HEADING: 'Obowiązuje sprawdzanie temperatury',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Pracownicy obsługujący aktywność są przeszkoleni zgodnie z wytycznymi WHO i są w stanie poradzić sobie ze wszelkimi potencjalnymi wypadkami i sytuacjami',
          HEADING: 'Pracownicy są przeszkoleni z zakresu wytycznych WHO',
        },
      },
      HEADING: 'Bezpieczne aktywności',
      SUB_HEADING:
        'Pracujemy z naszymi partnerami z całego świata, aby wdrażać najwyższe standardy bezpieczeństwa zgodne z wytycznymi Światowej Organizacji Zdrowia. Wszystkie środki bezpieczeństwa podejmowane w miejscu aktywności zostały zweryfikowane i są tu wyświetlane. Czas znów cieszyć się światem wokół nas.',
    },
    NL_DESCRIPTION: {
      CTA_URL:
        'https://www.government.nl/topics/coronavirus-covid-19/covid-certificate',
      TEXT: 'Odwiedzający w wieku 13 lat i starsi muszą mieć (cyfrowy lub wydrukowany) certyfikat COVID, który potwierdza szczepienie, negatywny wynik niedawno zrobionego testu lub ważny certyfikat ozdrowieńca. Noszenie maseczki jest obowiązkowe. ',
    },
    SG_DESCRIPTION: {
      CTA_URL: 'https://safetravel.ica.gov.sg/health/vtsg',
      TEXT: 'Od 13 października 2021 r. tylko w pełni zaszczepieni odwiedzający mogą wchodzić w dwuosobowych grupach. Przed wejściem konieczne będzie zaprezentowanie dowodu szczepienia, negatywnego wyniku niedawno zrobionego testu przeciwko COVID-19 i/lub certyfikatu ozdrowieńca. ',
    },
    SHORT_HEADING: 'Obowiązują najwyższe standardy bezpieczeństwa',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Szczegóły bezpieczeństwa',
    EXPERIENCE_DESCRIPTION:
      'Ta aktywność została zweryfikowana jako aktywność zgodna z najwyższymi standardami bezpieczeństwa według lokalnych przepisów oraz Światowej Organizacji Zdrowia',
    FLAG_TEXT: 'Największe bezpieczeństwo',
    GENERAL_DESCRIPTION:
      'Ten obiekt jest ZABEZPIECZONY PRZED COVID i przestrzega wszystkich środków bezpieczeństwa zalecanych przez rząd w celu zapewnienia wszystkim bezpiecznej zabawy przy zachowaniu dystansu społecznego podczas wizyty w teatrze.',
    GENERAL_DESCRIPTION_V2:
      'Opracowaliśmy znany w całej branży symbol „Zobacz to bezpiecznie”, więc gdy teatry otworzą się ponownie, będziesz móc czuć się bezpiecznie, wiedząc, że obiekt został zabezpieczony przed COVID i przestrzega najnowszych wytycznych rządowych i wytycznych dotyczących sztuk widowiskowych.',
    HEADING: 'Zobacz to bezpiecznie',
    MOBILE_HEADING: 'Bezpieczne aktywności',
    MORE_CURRENCIES: 'Więcej walut',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Akceptowane są jedynie bilety wydrukowane w&nbsp;domu lub e-bilety</li>',
          HEADING: 'Bezdotykowe e-bilety',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Aby wejść do obiektu, konieczne jest noszenie środków ochrony osobistej takich jak maseczki</li>\n            <li>Przed wejściem do&nbsp;obiektu sprawdzona zostanie temperatura wszystkich widzów</li>',
          HEADING: 'Zapobiegawcze środki bezpieczeństwa',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Aby wejść do obiektu, konieczne jest noszenie środków ochrony osobistej takich jak maseczki</li>\n            <li>Przed wejściem do&nbsp;obiektu sprawdzona zostanie temperatura wszystkich widzów</li>',
          HEADING: 'Sanitaryzacja',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Obiekt został zmieniony, tak aby minimalizować kontakt między widzami</li>\n            <li>Różnym grupom przydzielane są oddzielne miejsca</li>\n            <li>W&nbsp;miarę możliwości zorganizowane zostanie wstępne zamawianie przekąsek na przerwę</li>\n            <li>Zalecane są bezdotykowe, elektroniczne transakcje.</li>\n            <li>Widzów prosi się o ograniczenie ilości zabieranych ze sobą przedmiotów osobistych, ponieważ szatnie mogą być zamknięte</li>\n            <li>Aktywności takie jak robienie zdjęć z&nbsp;artystami czy rozdawanie autografów mogą być ograniczone</li>\n            ',
          HEADING: 'Środki dystansu społecznego',
        },
      },
      HEADING: 'Zobacz to bezpiecznie',
      SUB_HEADING:
        'Zastanawiasz się, jakie kroki są podejmowane w celu zapewnienia bezpieczeństwa? Dowiedz się więcej o środkach bezpieczeństwa i protokołach bezpieczeństwa związanych z COVID, które zostały wprowadzone w teatrach w celu zapewnienia widzom bezpieczeństwa.',
    },
    SHORT_HEADING: 'Obowiązują najwyższe standardy bezpieczeństwa',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Twoje bezpieczeństwo jest naszym priorytetem',
    TEXT: 'Podjęliśmy istotne kroki w celu poprawy czystości i stosujemy środki dezynfekcyjne podczas kompleksowego i częstego czyszczenia powierzchni. Zapobiegamy też tłumom, kontrolując liczbę ludzi.',
  },
  SAVE: 'Zaoszczędź {0}%',
  SAVE_PERCENT: 'Zaoszczędź {0}%',
  SAVE_UPTO_PERCENT: 'Zaoszczędź do {0}%',
  SEE_ALL: 'Zobacz wszystko',
  SEARCH: 'Szukaj',
  POPULARITY: 'Popularność',
  PRICE: 'Cena',
  SEE_MORE_SHOWS: 'Zobacz więcej spektakli',
  SELECT_CITY: 'Wybierz miasto',
  SELECT_SECTION: 'Wybierz sekcję',
  SEE_ALL_PHOTOS: 'Zobacz wszystkie zdjęcia',
  SHOW_CLOSED: 'Spektakl zakończony',
  SHOW_LESS: 'Pokaż mniej',
  SHOW_LESS_TEXT: 'Pokaż mniej',
  SHOW_MORE: 'Pokaż więcej',
  SHOW_PAGE: {
    ABOUT_SHOW: 'O spektaklu',
    ABOUT_THEATRE: 'O teatrze',
    ADDITIONAL_INFORMATION: 'Informacje dodatkowe',
    AGE_LIMIT: 'Ograniczenie wiekowe',
    AGE_SUITABILITY: 'Odpowiedni wiek',
    ANSWER: ['Odpowiedź:'],
    BLOG_SHOW_PAGE: 'Blog: strona spektaklu',
    BLOG_SUMMARY: 'Blog: podsumowanie',
    BLOG_THEATRE_PAGE: 'Blog: strona teatru',
    BLOG_THEATRE_SEATING_PLAN: 'Blog: układ siedzeń teatru',
    CANCELLATION_AND_REFUNDS: 'Anulowanie i zwroty',
    CANCELLATION_POLICY: 'Zasady anulowania',
    CAST_AND_CREW: 'Obsada i ekipa',
    CLOSING_DATE: 'Data zakończenia',
    CLOSING_DATE_SPECIAL_OFFER: 'Oferta specjalna: ostatni termin',
    DURATION: 'Czas trwania',
    FACILITIES_AND_ACCESSIBILITY: 'Udogodnienia i dostępność',
    FREQUENTLY_ASKED_QUESTIONS: 'Często zadawane pytania',
    GETTING_THERE: 'Dojazd',
    GETTING_THERE_MAP_LINK: 'Dojazd: link do mapy',
    GOOGLE_MAP: 'Mapa Google',
    HIGHLIGHTS: 'Główne punkty',
    LISTICLE_SHOW_SUMMARY: 'Listicle Podsumowanie spektaklu',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Dlaczego warto obejrzeć',
    OPENING_DATE: 'Data premiery',
    QUESTION: ['Pytanie:'],
    SAFETY_BANNER: 'Baner bezpieczeństwa',
    SHOW_DETAILS: 'Szczegóły spektaklu',
    SHOW_TIMINGS: 'Terminy spektakli',
    SHOW_TYPE: 'Rodzaj spektaklu',
    SPECIAL_OFFER: 'Oferta specjalna',
    THE_STORY: 'Historia',
    THEATRE_ADDRESS: 'Adres teatru',
    THEATRE_CAPACITY: 'Pojemność teatru',
    THEATRE_NAME: 'Nazwa teatru',
    TICKETS: 'Bilety',
    TICKETS_REDEMPTION: 'Odbiór biletów',
    TOP_SONGS: 'Popularne utwory',
    YOUR_TICKETS: 'Twoje bilety',
    ABOUT_CONCERT: 'O koncercie',
    PROGRAM: 'Program',
    CRITIC_REVIEW: 'Recenzja krytyka',
  },
  SORT_BY: 'Sortuj według',
  SPECIAL_OFFER: 'Oferta specjalna',
  THEATRE: 'Teatr',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Pobliskie teatry',
    NOW_PLAYING: 'Aktualnie wystawiane',
    UPCOMING_SHOWS: 'Nadchodzące spektakle',
    PAST_SHOWS: 'Minione spektakle',
    FIND_BEST_SEATS: 'Znajdź najlepsze miejsca',
  },
  TICKET_CAN_BE_CANCELED:
    'Możesz anulować z wyprzedzeniem do {hours} godzin, aby uzyskać pełen zwrot pieniędzy.',
  TICKET_CANNOT_BE_CANCELED:
    'Tego biletu nie można anulować, ale na żądanie można przenieść go na inny termin.',
  TICKETS: 'Bilety',
  TIMINGS: 'Harmonogram',
  SPECIAL_PRODUCT_HEADING: 'Najbardziej uwielbiane',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Profesjonalni lokalni przewodnicy',
    ENGAGING_STORIES: 'Wciągające historie',
    TOP_RATED: 'Najwyżej oceniane',
  },
  GUIDED_TOUR_REVIEWS: [
    'Nasza przewodniczka Angela była wspaniała i bardzo dobrze znała obiekt',
    'Przewodnik chętnie odpowiadał na pytania dotyczące wycieczki',
    'Nasza przewodniczka była świetna, a nawet poleciła nam świetne miejsce na lunch!',
    'Dzięki dobrej organizacji i naszemu przewodnikowi doświadczenie było naprawdę przyjemne',
    'Dużo treści edukacyjnych, na pewno zrobię to ponownie z moimi dziećmi',
    'Wycieczka była dobrze zorganizowana i miała odpowiedni czas trwania',
    'Nasz przewodnik naprawdę znał się na rzeczy i czuło się jego pasję do historii',
    'Dobry przewodnik i organizacja! Polecam!!!',
    'Zabawne ciekawostki naszego przewodnika sprawiły, że wszyscy byliśmy aktywni i zainteresowani',
    'Wycieczka miała dobre tempo i mogliśmy zwiedzać bez pośpiechu',
    'Nasza przewodniczka Maria była w stanie zdobyć miejsca z najlepszym widokiem',
    'Nasz przewodnik wzbogacił naszą wizytę w sposób, który nie byłby możliwy bez niego',
    'Szczegółowa i poruszająca wycieczka prowadzona przez pełnego pasji przewodnika',
    'Jeff pokazał nam aspekty obiektu, które inaczej by nam umknęły',
  ],
  GUIDES_BANNER:
    'Zwiedzaj jak miejscowy z naszymi przewodnikami uwielbianymi przez odwiedzających.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Zwiedzanie z przewodnikiem to najlepszy sposób na poznanie tego miejsca. Nasi profesjonalni przewodnicy pełnią rolę Twoich lokalnych znajomych, dzieląc się historiami, ukrytymi perełkami i rekomendacjami podróżniczymi.',
    'Nie tylko odwiedzaj - doświadczaj!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Poznaj opinie naszych gości',
  GUIDES: 'Przewodniki',
  TODAY: 'Dzisiaj',
  TOMORROW: 'Jutro',
  TOUR_LIST_HEADING: 'Wybierz aktywność',
  TOUR_LIST_SUB_HEADING:
    'Wybieraj spośród wielu biletów, wycieczek i zestawów biletów sprawdzonych operatorów',
  UGC: {
    FOLLOW: 'Obserwuj',
    FOLLOW_IG: 'Obserwuj na Instagramie',
    HEADING: 'Wyobraź sobie: Tak wygląda Twoja kolejna przygoda',
    SUB_HEADING: 'Wybrane z 💜 przez Headout',
  },
  UNAVAILABLE: 'Niedostępne',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Ważność tych biletów została przedłużona. Na bilecie znajdziesz dokładne informacje.',
    UNTIL_DATE: 'Te bilety są ważne do {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Te bilety są ważne przez {0} dni od daty zakupu.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Te bilety są ważne przez {0} mies. od daty zakupu.',
  },
  TABLE_OF_CONTENTS: 'Zawartość',
  VIEW_LESS: 'Wyświetl mniej',
  VIEW_MORE: 'Wyświetl więcej',
  WHY_TAKE_THIS_DAY_TRIP:
    'Dlaczego warto wybrać się na tę wycieczkę jednodniową?',
  WHY_WATCH: 'Dlaczego warto to obejrzeć {0}?',
  FIND_ON_MAP: 'Znajdź na mapie',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Bilety z kas',
        DESCRIPTION: 'Natychmiastowe potwierdzenie na telefon',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Wybór miejsc`,
        DESCRIPTION: 'Widok, na jakim Ci zależy, zawsze',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Wyjątkowe oferty i zniżki',
        DESCRIPTION: `Zaoszczędź na najlepszych spektaklach, które do zaoferowania ma {0}`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Prosta rezerwacja',
        DESCRIPTION: 'Zaufało nam już ponad 25 miliony gości',
      },
    },
    YOUR_PICK: 'Twój wybór',
    BROWSE_BY_CATEGORIES: 'Przeglądaj według kategorii',
    TOP_WEST_END_SHOWS: 'Popularne spektakle na West Endzie',
    TOP_SHOWS: 'Melhores espetáculos',
    SEE_MORE_SHOWS: 'Ver mais {0} espetáculos',
    LAST_MINUTE_TICKETS: 'Bilety last minute',
    LOVED_BY_MILLIONS: 'Uwielbiane przez miliony',
    TODAY: 'Dzisiaj',
    TOMORROW: 'Jutro',
    SEE_ALL: 'Zobacz wszystko',
    GRAB_YOUR_TICKETS: 'Zdobądź bilety już teraz',
  },
  TAG_NAME: {
    BALLET: 'Balet',
    CABARET: 'Kabaret',
    CHRISTMAS: 'Boże Narodzenie',
    CIRCUS: 'Cyrk',
    CLASSIC: 'Klasyka',
    COMEDY: 'Komedie',
    COMING_SOON: 'Już wkrótce',
    CRITICS_CHOICE: 'Wybór krytyków',
    DANCE: 'Taniec',
    DISNEY: 'Disney',
    DRAMA: 'Dramaty',
    ENGLISH_NATIONAL_BALLET: 'Narodowy Balet Angielski',
    ENGLISH_NATIONAL_OPERA: 'Angielska Opera Narodowa',
    FANTASY: 'Fantasy',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Teatr immersyjny',
    JUKEBOX: 'Jukebox',
    KIDS: 'Dzieci',
    MAGIC: 'Magia',
    MUSICALS: 'Musicale',
    NEW_ARRIVAL: 'Nowość',
    OFF_WEST_END: 'Poza West Endem',
    OLIVIER_WINNER: 'Nagroda Oliviera',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomimy',
    PLAYS: 'Sztuki',
    ROMANCE: 'Romanse',
    SHAKESPEARE: 'Szekspir',
    STARS_ON_STAGE: 'Gwiazdy na scenie',
    THEATRICAL_CONCERT: 'Koncert teatralny',
    TRUE_STORY: 'Prawdziwe historie',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Ups, mamy problem',
    MESSAGE:
      'Przepraszamy! Wszystkie aktywności tego dnia są wyprzedane lub\n    niedostępne. Ale jest ich mnóstwo w innych terminach. Jedyne,\n    co musisz zrobić, to zachować elastyczność.',
    CTA: 'Wyświetl wszystkie daty',
  },
  ALL_DATES: 'Wszystkie daty',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Menu główne',
    EXPLORE: 'Odkrywaj',
    VISIT: 'Wizyta',
    THINGS_TO_DO: 'Atrakcje',
    CITY_ATTRACTIONS: 'Atrakcje: {0}',
    TOP_THINGS_TO_DO: 'Najpopularniejsze atrakcje',
    CITY_TOURS: 'Wycieczki: {0}',
    CITY_GUIDE: 'Przewodnik po mieście',
    ATTRACTIONS: 'Atrakcje',
    CRUISES: 'Rejsy',
    THEMES: 'Motywy',
    ABOUT: 'Informacje',
    TOURS: 'Wycieczki',
    SKIP_THE_LINE: 'Wycieczki „Omiń kolejkę”',
    GUIDED_TOURS: 'Wycieczki z przewodnikiem',
    NIGHT_TOURS: 'Wycieczki nocą',
    FOOD_TOURS: 'Wycieczki kulinarne',
    HISTORY: 'Historia',
    ARCHITECTURE: 'Architektura',
    DESIGN: 'Design',
    INSIDE: 'Wnętrze',
    COLLECTIONS: 'Kolekcje',
    PAINTINGS: 'Obrazy',
    ANIMALS_EXHIBITS: 'Zwierzęta i wystawy',
    HABITATS: 'Środowisko i siedliska',
    CONSERVATION: 'Ochrona przyrody',
    PROGRAMMES: 'Programy',
    A2_SIGHTSEEING_CRUISES: 'Rejsy wycieczkowe',
    A2_DINNER_CRUISES: 'Rejsy z kolacją',
    A2_EVENING_CRUISES: 'Rejsy nocą',
    A2_LUNCH_CRUISES: 'Rejsy z lunchem',
    A2_YACHT_TOURS: 'Wycieczki jachtem',
    PLAN_YOUR_VISIT: 'Zaplanuj wizytę',
    TIMINGS: 'Harmonogram',
    DIRECTIONS: 'Dojazd',
    PARKING: 'Parking',
    ROUTES: 'Trasy',
    REQUIREMENTS: 'Wymagania',
    LOCATION: 'Lokalizacja',
    RULES: 'Zasady',
    FAQs: 'Często zadawane pytania',
    ENTRANCES: 'Wejścia',
    RESTAURANTS: 'Restauracje',
    FACTS: 'Fakty',
    TIPS: 'Wskazówki',
    MAP: 'Mapa',
    RIDES: 'Przejazdy',
    SHOWS: 'Spektakle',
    DINING: 'Posiłki',
    SHOPPING: 'Zakupy',
    EVENTS: 'Wydarzenia',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Boże Narodzenie',
    NEW_YEARS_EVE: 'Sylwester',
    TRAVEL_GUIDE: 'Przewodnik turystyczny',
    TRIP_PLANNER: 'Planowanie podróży',
    ITINERARY: 'Plan podróży',
    TRAVEL_TIPS: 'Porady dotyczące podróży',
    WEATHER: 'Pogoda',
    BEST_TIME_TO_VISIT: 'Najlepsza pora na wizytę',
    JANUARY: 'Styczeń',
    FEBRUARY: 'Luty',
    MARCH: 'Marzec',
    APRIL: 'Kwiecień',
    MAY: 'Maj',
    JUNE: 'Czerwiec',
    JULY: 'Lipiec',
    AUGUST: 'Sierpień',
    SEPTEMBER: 'Wrzesień',
    OCTOBER: 'Październik',
    NOVEMBER: 'Listopad',
    DECEMBER: 'Grudzień',
    WHERE_TO_EAT: 'Jedzenie',
    WHERE_TO_STAY: 'Zakwaterowanie',
    NEIGHBOURHOODS: 'Dzielnice',
    FAMILY_TRAVEL: 'Podróże z rodziną',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festiwale i imprezy',
  },
  CALENDAR: {
    FOOTNOTE: '* Wszystkie ceny są podane w {0}',
    PICK_DATE: 'Wybierz datę',
  },
  SHOW_PAGE_V2: {
    READ_MORE_REVIEWS: 'Czytaj więcej recenzji',
    SHOW_MORE_REVIEWS: 'Pokaż więcej recenzji',
    ALL_PHOTOS: 'Wszystkie zdjęcia',
    MORE_DATES: 'Więcej dat',
    SELLING_OUT_FAST: 'Szybko się wyprzedaje',
    SELECT_TIME_SLOT: 'Wybierz przedział czasowy',
    SELECT_TIME_SLOT_ERROR: 'Wybierz przedział czasowy, aby kontynuować',
    PRICE_STARTING_FROM: 'Cena miejsc od',
    SELECT_SEATS: 'Wybierz miejsca',
    READ_MORE: 'Czytaj więcej',
    RATINGS_AND_REVIEWS: 'Oceny i recenzje',
    READ_DETAILED_REVIEWS: 'Przeczytaj szczegółowe recenzje',
    INTERVAL: 'Przerwa',
    TWO_PART_SHOW: 'Spektakl w dwóch częściach',
    UNTIL_DATE: 'Do {0}',
    AVAILABLE_TIME: 'Dostępny przedział czasowy',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Ta aktywność jest dostępna tylko o poniższej godzinie',
    CONTENT_TABS: {
      ABOUT: 'Informacje',
      VENUE: 'Obiekt',
      TICKETS: 'Bilety',
      Reviews: 'Recenzje',
    },
    SELECT_SHOW_TIMMING: 'Wybierz godzinę spektaklu',
    ONLY_ONE_SLOT: 'Tylko 1 przedział czasowy dostępny w wybranym dniu',
    SIMILAR_SHOWS: 'To też może Ci się spodobać',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Fabuła',
      AGE_SUITABILITY_AND_GUIDELINES: 'Odpowiedni wiek i dodatkowe wytyczne',
      WHAT_CRITICS_THINK: 'Co myślą krytycy',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Często zadawane pytania: {0}',
      CAST_AND_CREATIVES: 'Obsada i twórcy',
    },
  },
  BREADCRUMBS: {
    HOME: 'Strona główna',
    TRAVEL_GUIDE: 'Przewodnik turystyczny',
    THINGS_TO_DO: 'Aktywności w mieście {0}',
    SHOW_NAME_TICKETS: '{0} - bilety',
    LTT_HOME: 'Bilety do teatru w Londynie',
    LTT_VENUE_PAGE_HOME: 'Teatry w Londynie',
    BROADWAY_HOME: 'Bilety na spektakl na Broadwayu',
    BROADWAY_VENUE_PAGE_HOME: 'Teatry na Broadwayu',
    VIENNA_CONCERT_HOME: 'Bilety na koncert w Wiedniu',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Sale koncertowe w Wiedniu',
    ATTRACTIONS: 'Atrakcje',
    A2_SIGHTSEEING_CRUISES: 'Rejsy wycieczkowe',
    A2_DINNER_CRUISES: 'Rejsy z kolacją',
    A2_EVENING_CRUISES: 'Rejsy nocą',
    A2_LUNCH_CRUISES: 'Rejsy z lunchem',
    A2_YACHT_TOURS: 'Wycieczki jachtem',
    LONDON_THEATRE_NEWS: 'Aktualności z londyńskich teatrów',
    BROADWAY_SHOW_NEWS: 'Aktualności na temat spektakli na Broadwayu',
    NEWS_PAGE: 'Strona aktualności',
    REVIEWS_PAGE_BANNER_HEADING: 'Recenzje: {0}',
  },
  AMENITIES: {
    Restaurant: 'Restauracja',
    Cafe: 'Kawiarnia',
    'Dedicated Parking': 'Dedykowany parking',
    Elevators: 'Windy',
    Lift: 'Winda',
    'Wheelchair Accessible': 'Dostępne dla osób na wózków inwalidzkich',
    Cloakroom: 'Szatnia',
    'Air Conditioning': 'Klimatyzacja',
    WiFi: 'Wi-Fi',
    Bar: 'Bar',
    'Water Fountain': 'Wodotrysk z wodą pitną',
    Washrooms: 'Łazienki',
    Toilets: 'Toalety',
    Binoculars: 'Lornetki',
    'Adapted Toilets': 'Przystosowane toalety',
    'Accessible Toilets': 'Toalety dla niepełnosprawnych',
    'Assistive Listening System': 'System wspomagający słyszenie',
    'Hearing Assistance': 'Wspomaganie słuchu',
    'Booster Cushions': 'Poduszki podwyższające',
    Shop: 'Sklep',
    'Souvenir Shop': 'Sklep z pamiątkami',
    'Guide Dogs': 'Psy przewodnicy',
    'Baby Changing Facilities': 'Przebieralnia dla dzieci',
    'Security Check': 'Kontrola bezpieczeństwa',
    Ramp: 'Rampa',
    'Level Access': 'Wejście bez schodów',
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Profesjonalni wielojęzyczni przewodnicy',
    STL: 'Wstęp bez kolejki',
    PERSONALIZED: 'Spersonalizowane doświadczenie',
    LOCAL_FOOD: 'Lokalne jedzenie i kultura',
    MULTILINGUAL_GUIDES: 'Wielojęzyczni przewodnicy',
    CULINARY_EXPERTS: 'Specjaliści kulinarni',
    SIGHTSEEING: 'Zwiedzanie i rozrywka na pokładzie',
    MULTILINGUAL_GT: 'Wycieczki z przewodnikiem w wielu językach',
    ALL_TOP_ATTRACTIONS_COVERED: 'Obejmuje wszystkie popularne atrakcje',
    REG_SCHEDULE_UNLIMITED_RIDES:
      'Regularny harmonogram. Nielimitowane przejazdy',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Dostępność w ostatniej chwili. Natychmiastowe potwierdzenie',
    MULTI_ROUTES: 'Wiele opcji tras',
    HASSLE_FREE: 'Bezproblemowa rezerwacja',
    FREQUENT_DEPARTURES: 'Częste wyjazdy',
    ONBOARD_AMENITIES: 'Najlepsze udogodnienia na pokładzie',
    FLEXI_TRAVEL: 'Elastyczne podróże na wielu trasach',
    FLEXI_EXCHANGE_CANCEL: 'Elastyczne opcje zmiany i anulowania',
    EXTRA_DISCOUNT: 'Dodatkowe zniżki dla młodzieży, seniorów i rodzin',
    PREPAID: 'Wygodna wcześniejsza płatność',
    EASY_ACTIVATION: 'Łatwa aktywacja',
    INSTANT_CONNECTIVITY: 'Natychmiastowa łączność z globalnym zasięgiem',
    ROUND_TRIP: 'Transfery w obie strony',
    CULTURAL_EXPERIENCE: 'Autentyczne doświadczenia kulturowe',
    GUARANTEED_SEAT: 'Gwarantowane miejsce',
    ONBOARD_WIFI: 'Wbudowane porty Wi-Fi i ładowania',
    LUGGAGE_ASSISTANCE: 'Pomoc z bagażem',
    TOP_ATTRACTIONS: 'Popularne atrakcje wliczone w cenę',
    FREQ_DEP_MULTI_ROUTE: 'Częste odjazdy na wielu trasach',
    CHARGING: 'Stacja ładowania',
    WIFI: 'Dostęp do Wi-Fi',
    FnB: 'Dostęp do gastronomii',
    LUXURY: 'Luksusowe doświadczenie',
    FOOD_DRINK: 'Jedzenie i napoje',
    PANAROMIC: 'Panoramiczne widoki na popularne atrakcje',
    PANAROMIC_2: 'Panoramiczne widoki',
    BEVERAGES: 'Napoje na pokładzie',
    GOURMET: 'Wyszukana kolacja',
    TRANSFERS: 'Transfery wliczone w cenę',
    CERTIFIED_OP: 'Certyfikowani operatorzy',
    BIRD_EYE: 'Widok z lotu ptaka',
    MULTI_JUMP: 'Wiele godzin skoków',
    EXTREME_ADV: 'Ekstremalna przygoda',
    PHOTO_OP: 'Piękne kadry do zdjęć',
    TOP_ATTRACTIONS_COVERED: 'Obejmuje najpopularniejsze atrakcje',
    LOCAL_CULTURE: 'Poznaj lokalną kulturę',
    EXCLUSIVE_DISC: 'Wyjątkowe zniżki',
    EFFICIENT_PUBLIC_TRANSIT: 'Wydajny transport publiczny',
    FREQUENT_SERVICE: 'Częste odjazdy',
    PREBOOKING: 'Łatwa rezerwacja wstępna',
    LOCAL_CULTURE_IMM: 'Zanurz się w lokalnej kulturze',
    DISCOVER_HIDDEN: 'Poznaj ukryte miejsca',
    CITY_SIGHTSEEING: 'Zwiedzanie miasta',
    OFFBEAT_ADV: 'Przygoda poza utartym szlakiem',
    DRINK_DEALS: 'Oferty napojów',
    OFFBEAT_EXP: 'Wycieczka poza utartym szlakiem',
    MULTIPLE_VARIETIES: 'Dostępne wiele rodzajów',
    HIDDEN_GEMS: 'Ukryte perełki i atrakcje poza utartym szlakiem',
    EXPLORE_LOCAL: 'Odkryj lokalne dzielnice',
    CUSTOMIZED_TREATMENTS: 'Spersonalizowane zabiegi',
    TRAINED_THERAPISTS: 'Przeszkoleni terapeuci',
    HOLISTIC_WELLNESS: 'Holistyczne wellness',
    FLEXIBLE_DURATION: 'Elastyczny czas trwania',
    MULTI_BOAT: 'Wiele opcji statków',
    SCENIC_ROUTES: 'Trasy widokowe',
    HANDS_ON: 'Praktyczna nauka',
    CULTURAL_CULINARY: 'Zagłęb się w kulturę i kuchnię',
    EXPERT_HOSTS: 'Doświadczeni opiekunowie wycieczek',
    ADVENTURE_EXPERIENCE: 'Przygoda',
    EQUIPMENT: 'Sprzęt w cenie',
    SCENIC_FLYOVERS: 'Malownicze trasy',
    LIVE_COMMENTARY: 'Komentarz na żywo',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout wykorzystuje pliki cookie, aby usprawnić korzystanie ze strony internetowej, bajt po bajcie.',
    MOBILE: 'Wykorzystywane pliki cookie.',
    LEARN_MORE: 'Dowiedz się więcej.',
  },
  SHOW_UNAVAILABLE: 'Spektakl niedostępny',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Polecane aktualności',
    ALL_NEWS: 'Wszystkie aktualności',
    MORE_READS: 'Więcej artykułów',
    LOAD_MORE: 'Załaduj więcej',
    TRAILERS: 'Zwiastuny',
    GET_YOUR_TICKETS: 'Pobierz bilety',
    POPULAR_SHOWS: 'Popularne spektakle',
    FEATURED: 'Wyróżnione',
    RECENT_NEWS: 'Najnowsze wiadomości',
    SHOW_MORE_ARTICLES: 'Pokaż więcej artykułów',
    COLLAPSE_ALL: 'Zwiń wszystko',
    REVIEWS: 'Recenzje',
    SHOW_ALL_REVIEWS: 'Pokaż wszystkie recenzje',
    MAILER: {
      HEADING:
        'Najlepsze okazje i nowości teatralne prosto do Twojej skrzynki odbiorczej',
      SUBHEADING:
        'Dołącz do naszej listy mailingowej, żeby otrzymywać najnowsze wiadomości i najciekawsze oferty na spektakle teatralne.',
    },
  },
  HOHO: {
    MORE_DETAILS: 'Więcej szczegółów',
    HOHO: 'Wycieczki typu wskakuj/wyskakuj',
    BUS_ROUTES_DETAILS: 'Trasy autobusowe',
    TOUR_DETAILS: 'Szczegóły wycieczki',
    ROUTES_SCHEDULES: 'Trasy i harmonogramy',
    VALIDITY: 'Ważne przez 1 dzień',
    VALIDITY_NOTE:
      'Twoja wycieczka jest ważna przez {0} dzień/dni kalendarzowe. Jeśli zarezerwujesz bilet na 06.05.2023 r., bilet będzie ważny do 06.05.2023 r. do godz. 21:00 czasu pacyficznego.',
    BESTSELLER: 'Bestseller',
    SEE_ALL: 'Zobacz wszystko',
    TIMINGS: 'GODZINY',
    FREQUENCY: 'CZĘSTOTLIWOŚĆ',
    DURATION: 'CZAS TRWANIA',
    STARTING_LOCATION: 'Miejsce startu',
    TOP_ATTRACTIONS: 'Top attractions covered on route',
    CALENDAR_FOOTNOTE: '* Wszystkie ceny są podane w {0}',
    TOUR_TIMINGS: 'Godziny wycieczek',
    TOUR_FREQUENCY: 'Częstotliwość wycieczek',
    GOT_IT: 'Rozumiem',
    SELECT_DATE: 'Wybierz datę',
    SELECT_TOUR: 'Wybierz typ wycieczki',
    VIEW_TOUR_DETAILS: 'Wyświetl szczegóły wycieczki',
    BUS_DETAILS: 'WIĘCEJ SZCZEGÓŁÓW',
    VIEW_ROUTES: 'Wyświetl wszystkie trasy',
    BUS_ROUTES: 'TRASY AUTOBUSOWE',
    ATTRACTIONS_PREVIEW: 'Fastest way to view {0}+ top attractions including',
    STOPS_AND_ATTRACTIONS: 'Stops & nearby attractions',
    HOP_ON_OFF_AT: 'Hop on and hop off at any of these {0} stops',
    TIMINGS_FREQUENCY: 'Timings & frequency',
    TOUR_DURATION: 'Tour duration',
    EVERY_X_MINS: 'Every {0} mins',
    VIEW_LOCATION: 'View Location',
    BANNER_SUBTEXT: `Fastest and most convenient way to view
    <span> {0}+ top attractions </span> in all of {1}.`,
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Last minute availability',
        DESCRIPTION: 'Instantly confirmed to your phone',
      },
      DAILY_RIDES: {
        NAME: 'Daily unlimited rides',
        DESCRIPTION: "Experience {0}'s best in one tour",
      },
      DEALS_DISCOUNTS: {
        NAME: 'Exclusive deals & discounts',
        DESCRIPTION: 'Save big on hop on hop off tours',
      },
      BOOK_RELAX: {
        NAME: 'Book and relax',
        DESCRIPTION: 'Trusted by 22 million guests and counting',
      },
    },
  },
  PC_EXP: {
    SHOW_INCL: 'Zobacz, co wchodzi w cenę biletu i poznaj inne informacje',
    CLEAR: 'Wyczyść',
    ALL_EXPERIENCES: 'Wszystkie aktywności',
    FILTER_BY_CATEGORIES: 'Filtruj według kategorii',
    CATEGORIES: 'Kategorie',
    COMBOS: {
      HEADING:
        'Podobno im więcej, tym lepiej. Dlatego oferujemy zestawy biletów.',
      DESCRIPTOR_1: 'Zaoszczędź na biletach',
      DESCRIPTOR_2: 'Lepiej zaplanuj podróż',
    },
  },
  OFF_PERCENT: '{0}% zniżki',
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Używamy plików cookie i podobnych technologii do wielu celów, w tym w celu poprawy doświadczenia użytkownika na naszej stronie i dla reklam.',
    MANAGE_PREFERENCES: 'Zarządzaj preferencjami',
    PREFERNCES_SAVED: 'Twoje preferencje zostały zapisane',
    COOKIES: 'Pliki cookie:',
    ACCEPT: 'OK',
    ALLOW_ALL: 'Zezwalaj na wszystkie',
    DENY_ALL: 'Odrzuć wszystkie',
    HEADING: 'Zawsze cenimy Twoją prywatność',
    DESCRIPTION:
      '*   Pliki cookie to małe pliki umieszczane na Twoim komputerze, urządzeniu mobilnym lub innym urządzeniu przez Witrynę/Platformę. Zawierają one szczegóły historii przeglądania, wśród innych zastosowań.\n*   Używamy różnych rodzajów plików cookie, aby monitorować to, jak korzystasz z Naszej Platformy i przechowywać pewne informacje, które pomagają nam świadczyć bardziej spersonalizowane usługi. Niektóre pliki cookie mogą zostać umieszczone na Twoim Urządzeniu z powodu Korzystania przez Ciebie z usług dostępnych na naszej Platformie.\n*   Ogólnie rzecz biorąc, ten termin obejmuje dwa różne zestawy używanych przez nas technologii:\n    *   **Pliki cookie lub Pliki cookie przeglądarki.** Jest to mały plik, który automatycznie zostaje utworzony na Twoim Urządzeniu, gdy korzystasz z Naszej platformy. Możesz ustawić odrzucanie wszystkich Plików cookie w swojej przeglądarce. W tym przypadku, jeśli nie akceptujesz Naszych plików cookie, możesz nie być w stanie korzystać z niektórych części Naszej platformy.\n    *   **Pliki typu web beacon.** Są nazywane również znacznikami pikselowymi. Znajdują się w różnych sekcjach Naszej platformy oraz Naszych e-maili i pozwalają nam monitorować i rozumieć aktywność użytkowników.\n*   Te Pliki cookie przechowywane na Twoim urządzeniu mogą być „Trwałymi” lub „Sesyjnymi” plikami cookie. Trwałe pliki cookie to te, które pozostają na Twoim urządzeniu, nawet gdy przechodzisz do trybu offline, podczas gdy Sesyjne pliki cookie są automatycznie usuwane, gdy tylko zamkniesz Przeglądarkę internetową.\n*   Wykorzystujemy zarówno Sesyjne, jak i Trwałe pliki cookie do celów określonych poniżej:\n    *   Niezbędne / Kluczowe pliki cookie\n        *   _Typ:_ Sesyjne pliki cookie\n        *   _Cel:_ Te pliki cookie są niezbędne do korzystania z różnych sekcji Platformy, a jeśli są niedozwolone, możesz nie mieć dostępu do usług dostępnych na Platformie. Te pliki cookie pomagają nam uwierzytelniać użytkowników i zapobiegać wszelkim rodzajom nieuczciwych działań na Platformie.\n    *   Polityka plików cookie / Akceptacja plików cookies\n        *   _Typ:_ Trwałe pliki cookie\n        *   _Cel:_ Te Pliki cookie określają, czy Użytkownicy zaakceptowali korzystanie z Plików cookie.\n    *   Funkcjonalne pliki cookie\n        *   _Typ:_ Trwałe pliki cookie\n        *   _Cel:_ Te Pliki cookie pozwalają nam zapamiętać wybory, których dokonujesz podczas korzystania z Platformy, takie jak zapamiętanie Danych logowania lub preferencji językowych. Celem tych Plików cookie jest zapewnienie bardziej spersonalizowanej obsługi za każdym razem, gdy korzystasz z Platformy.\n\nWszystkie użyte powyżej terminy pisane wielką literą są zdefiniowane w Polityce prywatności. Aby uzyskać szczegółowe informacje, zapoznaj się z [Polityką prywatności](/privacy-policy/)\n',
  },

  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Wyświetl oryginalną recenzję: język {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Ta recenzja została przetłumaczona. Pokaż oryginalną recenzję.',
    TRANSLATE: 'Przetłumacz recenzję na język {0}',
    LANGUAGES: {
      EN: 'angielski',
      ES: 'hiszpański',
      FR: 'francuski',
      IT: 'włoski',
      DE: 'niemiecki',
      PT: 'portugalski',
      NL: 'holenderski',
    },
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Wszystko',
    POPULAR_SUBCATEGORY: 'Popularne: {0}',
    TOP_CATEGORY: 'Najpopularniejsze: {0}',
    ATTRACTIONS: 'Atrakcje',
    ALL_SUBCATEGORY: 'Wszystkie: {0}',
    BROWSE_BY_CATEGORIES: 'Przeglądaj według kategorii',
    TICKETS_FROM: 'Bilety od',
    PRICE_LOW_HIGH: 'Cena (od najniższej do najwyższej)',
    PRICE_HIGH_LOW: 'Cena (od najwyższej do najniższej)',
    FILTERS: 'Filtry',
    RESET: 'Resetuj',
    APPLY: 'Zastosuj',
  },

  REVIEWS_PAGE: {
    BANNER_HEADING: 'Recenzje: {0}',
    REVIEWS_COUNT: 'Recenzje: {0}',
    AWESOME: 'Super',
    GOOD: 'W porządku',
    AVERAGE: 'Średnio',
    POOR: 'Kiepsko',
    TERRIBLE: 'Fatalnie',
    REVIEW_BY_HEADOUT: 'Oto nasza opinia: recenzja od Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Co ludzie mówią',
    MOST_RELEVANT: 'Najistotniejsze',
    RATING_HIGH_TO_LOW: 'Ocena: od wysokiej do niskiej',
    RATING_LOW_TO_HIGH: 'Ocena: od niskiej do wysokiej',
    CRITIC_REVIEWS: 'Recenzje krytyków',
    USER_REVIEWS: 'Recenzje użytkowników',
    CONTRIBUTORS_REVIEW: 'Recenzja autora',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Prywatne transfery',
    SHARED_TRANSFERS: 'Współdzielone transfery',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Rezerwacja online',
        DESCRIPTION:
          'Zarezerwuj bilety online i ciesz się szybkim, wygodnym procesem.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Natychmiastowe potwierdzenie',
        DESCRIPTION:
          'Otrzymaj natychmiastowe potwierdzenie swojej rezerwacji transferu lotniskowego.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Wygodny odbiór',
        DESCRIPTION:
          'Uniknij czekania w długich kolejkach i wsiądź do pojazdu w wybranym miejscu odbioru.',
      },
      DROP_OFF: {
        TITLE: 'Bezproblemowy powrót',
        DESCRIPTION: 'Dostań się do swojego celu w szybki i komfortowy sposób.',
      },
    },
    SHARED_TRANSFERS_IN: 'Współdzielone transfery w: {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      ' Wygodna i ekonomiczna opcja transportu w przypadku wielu pasażerów podróżujących na lotnisko lub z niego.',
    PRIVATE_TRANSFERS_IN: 'Prywatne transfery w: {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      ' Wygodna, spersonalizowana usługa transportowa dla pojedynczych osób lub małych grup, oferująca wygodny i bezpośredni dojazd na lotnisko i z powrotem.',
    ANYWHERE_IN_THE_CITY: 'Gdziekolwiek w mieście',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Wiele opcji pojazdów',
      FREE_CANCELLATION: 'Bezpłatne anulowanie',
    },
    SEAMLESS_TRANSFERS:
      'Bezproblemowe transfery, którym zaufali ludzie na całym świecie',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Wybierz najlepszy transfer z lotniska dla siebie',
    HASSLE_FREE_TRANSFER: 'Bezproblemowy transfer z lotniska',
  },
  TOP: 'Najpopularniejsze: {0}',
  VIEW_CALENDAR: 'Wyświetl kalendarz',
  SHOWS_CALENDAR: 'Kalendarz spektakli',
  IN: 'w',
  SEATS: 'Miejsca',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Przewodnik po zawartości',
    QUICK_INFORMATION: 'Szybkie informacje',
    PEAK: 'Sezon',
    OFF_PEAK: 'Poza sezonem',
    ADDRESS: 'ADRES',
    RECOMMENDED_DURATION: 'ZALECANY CZAS TRWANIA',
    VISITORS_PER_YEAR: 'LICZBA ODWIEDZAJĄCYCH ROCZNIE',
    NUMBER_OF_ENTRANCES: 'LICZBA WEJŚĆ',
    EXPECTED_WAIT_TIME_STANDARD: 'SZACOWANY CZAS OCZEKIWANIA - STANDARDOWO',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE:
      'SZACOWANY CZAS OCZEKIWANIA - OMIŃ KOLEJKĘ',
    UNESCO_YEAR: 'ROK UNESCO',
    ARCHITECTURE_STYLE: 'STYL ARCHITEKTURY',
    TIMINGS: 'Godziny',
    SIZE_HEIGHT: 'ROZMIAR/WYSOKOŚĆ',
    TICKETS: 'BILETY',
    FUN_FACTS: 'Ciekawostki',
    DID_YOU_KNOW: 'Wiesz o tym?',
    MORE_INTERESTING_FACTS: 'Więcej ciekawostek',
    PLAN_YOUR_VISIT: 'Zaplanuj wizytę',
    ALSO_KNOWN_AS: 'Znane też jako',
    FOUNDED_ON: 'Założone',
    FOUNDED_BY: 'Założone przez',
    FROM: 'Od',
    CLOSED_TODAY: 'Dzisiaj zamknięte',
    TODAY: 'Dzisiaj',
    CLOSED: 'Zamknięte',
    OPEN: 'Otwarte',
    LAST_ADMISSION: 'Ostatni wstęp',
    DAYS: 'Dni',
    BEST_TIME_TO_VISIT: 'Najlepsza pora na wizytę:',
    WEEKDAY_VS_WEEKEND: 'Dzień tygodnia czy weekend',
    PEAK_VS_LOW_SEASON: 'W sezonie czy poza sezonem',
    PLEASANT: 'Przyjemnie',
    CROWDED: 'Dużo ludzi',
    VERY_CROWDED: 'Bardzo dużo ludzi',
    LOW_SEASON: 'Poza sezonem',
    MID_SEASON: 'Sezon umiarkowany',
    PEAK_SEASON: 'Szczyt sezonu',
    TO: 'DO',
    LAST_ENTRY: 'Ostatni wstęp',
  },
  NEXT: 'Następne',
  PREVIOUS: 'Poprzednie',
  ITINERARY: {
    TAB: 'Plan wycieczki',
    HEADING: 'Twoja wycieczka',
    VIEW_ITINERARY: 'Wyświetl plan podróży',
    PASSES_BY_SECTION_HEADING: 'Widok na:',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Główne punkty',
      NEARBY_THINGS_TO_DO: 'W okolicy',
      THINGS_TO_DO: 'Atrakcje',
    },
    STOP_CARD: {
      TITLE: {
        START: 'START POINT',
        END: 'END POINT',
      },
      MULTI_POINTS_AVAILABLE: {
        START: 'Dostępne punkty startowe ({0})',
        END: 'Dostępne punkty końcowe ({0})',
      },
    },
    GET_DIRECTION: 'Dojazd',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} godz. {1} min',
        WITHOUT_HOURS: '{0} min',
        WITHOUT_MINS: '{0} godz.',
      },
      ATTRACTIONS_COUNT: 'Atrakcje: {0}',
      ACTIVITIES_COUNT: 'Aktywności: {0}',
      TOTAL_DURATION: 'Całkowity czas trwania',
      FREQUENCY: 'Częstotliwość',
      FIRST_DEPARTURE: 'Pierwszy kurs',
      LAST_DEPARTURE: 'Ostatni kurs',
      FIRST_DEPARTURE_TIME: 'Pierwszy kurs',
      LAST_DEPARTURE_TIME: 'Ostatni kurs',
      MODE_OF_TRANSPORT: 'Rodzaj transferu',
      FOOD_AND_DRINKS: 'Jedzenie i napoje',
    },
    WALK_DURATION: '{0} walk',
    MORE: '{0} więcej',
    TIMELINE_VIEW: 'Widok osi czasu',
    MAP_VIEW: 'Widok mapy',
  },
};
export default pl;
