const pl = {
  AUDIO_GUIDE: {
    BANNER: 'Darmowy audioprzewodnik',
    PRODUCT_SUFFIX: 'z audioprzewodnikiem',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Autoryzowany i zaufany partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Autoryzowany odsprzedawca',
    SUB_TEXT:
      'Autentyczne doświadczenia zaufanych i zweryfikowanych partnerów.',
  },
  REVIEWS: 'ocen(-y)',
  AVAILABLE: 'Dostępne',
  BANNER_CTA: 'Kup bilety',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout to marka, której zaufały miliony odwiedzających na całym świecie, oferująca niezwykłe aktywności, podczas których można poznać tę atrakcję.',
    NON_PARTNERED_SENSITIVE:
      'Headout to marka, której zaufały miliony odwiedzających na całym świecie, oferująca niezwykłe aktywności, podczas których można poznać tę atrakcję. To nie jest strona internetowa obiektu.',
    PARTNERED_NON_SENSITIVE:
      'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje niezwykłe aktywności, pozwalające Ci poznać tę atrakcję.',
    PARTNERED_SENSITIVE:
      'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje niezwykłe aktywności, pozwalające Ci poznać tę atrakcję. To nie jest strona internetowa obiektu.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje wybór najlepszych aktywności, pozwalających Ci poznać tę atrakcję.',
  BOOK_NOW_CTA: 'Zarezerwuj teraz',
  BUY_TICKETS_CTA: 'Kup bilety',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Możesz anulować te bilety do {0} godzin przed rozpoczęciem aktywności, aby uzyskać pełen zwrot.',
    CANCELLABLE_ANYTIME:
      'Darmowe anulowanie w dowolnym momencie przed rozpoczęciem aktywności',
    CANCELLABLE_DAYS:
      'Możesz anulować te bilety do {0} dni przed rozpoczęciem aktywności, aby uzyskać pełen zwrot.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Tych biletów nie można anulować. Jednak okres ich ważności został przedłużony.',
    HEADING: 'Zasady zmiany rezerwacji',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Tych biletów nie można anulować. Jednak można zmienić ich termin do {0} godz. przed rozpoczęciem aktywności.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Tych biletów nie można anulować ani przełożyć.',
    VALID_UNTIL_DATE:
      'Tych biletów nie można anulować. Jednak możesz użyć ich w dowolnym momencie do {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Tych biletów nie można anulować. Jednak możesz użyć ich w dowolnym momencie w ciągu następnych {0} dni.',
    VALID_WITHIN_NEXT_MONTHS:
      'Tych biletów nie można anulować. Jednak możesz użyć ich w dowolnym momencie w ciągu następnych {0} miesięcy.',
  },
  CANCELLATION_POLICY_HEADING: 'Zasady anulowania',
  CASHBACK: '{0}% cashbacku',
  CASHBACK_INFO:
    'Otrzymasz cashback <strong>{0}%</strong>, gdy zarezerwujesz tę aktywność. Twój cashback zostanie automatycznie przyznany Twojemu kontu Headout i&nbsp;będziesz móc wykorzystać go na dowolne zamówienie na Headout w&nbsp;przyszłości.',
  CATEGORY_SLIDER_HEADING:
    'Klienci, którzy zarezerwowali ten spektakl, wyświetlili również',
  CHECK_AVAIL: 'Sprawdź dostępność',
  CITY_PAGE: {
    BANNER_TITLE: 'Doświadcz tego, co do zaoferowania ma',
    TOP_ATTRACTIONS: 'Najpopularniejsze atrakcje',
    GO_BEYOND: 'Podróżuj dalej niż {0}',
    ALL_DAY_TRIPS: 'Zobacz wszystkie wycieczki całodzienne',
    CITIES_NEARBY: 'Miasta w pobliżu',
    POPULAR_CATEGORIES: 'Popularne kategorie',
    GO_TO_GUIDE: '{0}: przewodnik po mieście',
    VIEW_TRAVEL_GUIDE: 'Wyświetl przewodnik turystyczny',
    EXPLORE: 'Poznaj miasto {0}',
    GUIDE_SUBHEADING:
      'Odkrywanie atrakcji w mieście {0} nigdy nie było łatwiejsze! Nasz przewodnik turystyczny: {0} zawiera wszystko, co musisz wiedzieć o mieście – co jeść, gdzie iść, jak się tam dostać, gdzie się zatrzymać i wiele więcej!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Informacje ogólne',
      WHERE_TO_EAT: 'Jedzenie',
      WHERE_TO_STAY: 'Zakwaterowanie',
      THINGS_TO_DO: 'Atrakcje',
      WEATHER: 'Najlepsza pora na wizytę',
      NEIGHBOURHOODS: 'Lokalna społeczność',
      TRANSPORTATION: 'Poruszanie się',
      TRIP_PLANNER: 'Plan podróży',
      FAMILY_TRAVEL: 'Podróżowanie z dziećmi',
      TRAVEL_TIPS: 'Porady i wskazówki dla podróżujących',
      SHOPPING: 'Zakupy',
      ART_AND_CULTURE: 'Sztuka i kultura',
    },
    MAILER: {
      HEADING:
        '{0}: inspiracje podróżnicze prosto do Twojej skrzynki odbiorczej',
      SUBHEADING:
        'Popularne atrakcje, sposoby na budżetowe podróżowanie, transport publiczny, najlepsze restauracje i hotele, wskazówki dotyczące kultury i więcej!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Dowiedz się więcej o wymaganiach wizowych, wymianie walut, różnicach stref czasowych i nie tylko, by cieszyć się bezproblemową podróżą i przyjemnym pobytem.',
    WHERE_TO_EAT:
      'Poznaj tętniącą życiem scenę kulinarną, delektując się różnorodnymi smakami i próbując lokalnych przysmaków w każdym zakątku miasta {0}.',
    WHERE_TO_STAY:
      'Odkryj najlepsze zakwaterowanie w mieście {0}, oferujące komfort, wygodę i niezapomniane wrażenia podczas pobytu.',
    THINGS_TO_DO:
      'Weź udział w mnóstwie emocjonujących aktywności, które trafią we wszystkie gusta, zapewniając niezapomniany czas.',
    WEATHER:
      'Mądrze zaplanuj swoją wycieczkę i w pełni wykorzystaj swoją w wizytę, ponieważ {0} oferuje magiczne doświadczenia przez cały rok.',
    NEIGHBOURHOODS:
      'Poznaj różnorodne społeczności lokalne i tętniące życiem dzielnice, którym {0} zawdzięcza swój wyjątkowy charakter.',
    TRANSPORTATION:
      'Poruszaj się po mieście z łatwością, korzystając z wydajnego systemu transportowego, który oferuje {0} i wygodnie odkrywaj wszystkie atrakcja.',
    TRIP_PLANNER:
      'Wykorzystaj swój czas z dobrze przemyślanym planem podróży i ciesz się wszystkim, co do zaoferowania ma {0}.',
    FAMILY_TRAVEL:
      'Wyrusz na rodzinną przygodę z licznymi atrakcjami, parkami i innymi rozrywkami, które zaspokoją potrzeby dzieci w każdym wieku.',
    TRAVEL_TIPS:
      'Poznaj wskazówki lokalsów i triki podróżnicze, żeby Twoja wizyta w mieście {0} była naprawdę wyjątkowa.',
    SHOPPING:
      'Udaj się do raju dla kupujących z przeróżnymi butikami, targami i centrami handlowymi, oferującymi wszystko od lokalnego rzemiosła po luksusową modę.',
    ART_AND_CULTURE:
      'Zanurz się w bogatej scenie artystycznej i kulturalnej, od urzekających muzeów po tętniące życiem festiwale celebrujące dziedzictwo miasta {0}.',
  },
  CLOSE: 'Zamknij',
  COLLECTION_SLICE_HEADING: 'Popularne aktywności w mieście {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Wybierz',
    SELECT_OPTION: 'Wybierz opcję',
    SELECT_TICKET: 'Wybierz bilet',
  },
  COMPARE_ALL_DETAILS: 'Porównaj wszystkie szczegóły',
  COVID19_ALERT: {
    KEY_TEXT: 'Aktualności dotyczące COVID-19',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Jesteś naszym priorytetem. Zapoznaj się z naszą stroną pomocy, aby znaleźć najnowsze informacje na temat naszych elastycznych zasad anulowania rezerwacji',
  },
  CURRENCY: 'Waluta',
  CUSTOMER_REVIEW_HEADING: 'Opinie klientów',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioprzewodnik',
    DURATION: 'Czas trwania: {0}',
    EXTENDED_VALIDITY: 'Przedłużony okres ważności',
    FLEXIBLE_DURATION: 'Elastyczny czas trwania',
    FREE_CANCELLATION: 'Bezpłatne anulowanie',
    GUIDED_TOUR: 'Wycieczka z przewodnikiem',
    HOTEL_PICKUP: 'Odbiór z hotelu',
    INSTANT_CONFIRMATION: 'Natychmiastowe potwierdzenie',
    MEALS_INCLUDED: 'Posiłki wliczone w cenę',
    MOBILE_TICKET: 'Bilet mobilny',
    SKIP_THE_LINE: 'Omiń kolejkę',
    TRANSFERS: 'Transfery wliczone w cenę',
  },
  DURATION: 'Czas trwania',
  EARLIEST_AVAILABILITY: 'Najwcześniejszy dostępny termin',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Wpisz swój adres e-mail',
    SIGN_UP: 'Zapisz się',
    THANK_YOU: 'Dziękujemy!',
    SUBSCRIBED_MSG: 'Zasubskrybowano pomyślnie',
    ERROR_MSG: 'Podaj prawidłowy adres e-mail',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Bilety do teatru na Broadwayu',
    },
    LTT: {
      MB_NAME: 'Bilety do teatru w Londynie',
    },
  },
  EXCLUSIONS: 'Nie w cenie',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '10 milionów +',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100% bezpieczne',
    HEADING_SUPPORT: 'Centrum pomocy 24/7',
    SUB_HEADING_CUSTOMER: 'Klienci zadowoleni z 10 000+ aktywności',
    SUB_HEADING_RATING:
      '5000+ zweryfikowanych opinii z doskonałym wynikiem 90%',
    SUB_HEADING_SAFE:
      'Wszystkie aktywności na świeżym powietrzu są w 100% bezpieczne',
    SUB_HEADING_SUPPORT:
      'Masz pytanie? Czatuj na żywo z lokalnymi ekspertami, gdzie chcesz i kiedy chcesz',
  },
  FLEXIBLE: 'Elastyczność',
  FOOTER: {
    CALL_US: 'Zadzwoń do nas',
    CHAT_WITH_US: 'Czatuj z nami',
    COMPANY_DETAILS: 'Dane firmy',
    INFORMATION: 'Informacja',
    DISCLAIMER:
      'Ta strona nie jest oficjalną stroną internetową <attraction>. Jest prowadzona przez Headout, które współpracuje z operatorami atrakcji i wycieczek, aby zapewniać niezwykłe doświadczenia w kilku kliknięciach.',
    EMAIL_US: 'Napisz do nas',
    GET_HELP: 'Uzyskaj pomoc',
    LEGAL: 'Informacje prawne',
    GMAPS_DISCLAIMER:
      'Wszystkie zrzuty ekranu map znajdujące się na tej stronie są pozyskiwane z Google zgodnie z zasadami dozwolonego użytku. Wszelkie prawa do takich zrzutów ekranu należą do konkretnej platformy, a ich wykorzystanie służy wyłącznie celom informacyjnym lub orientacyjnym.',
    PRIVACY_POLICY: 'Polityka prywatności',
    QUICK_LINKS: 'Szybkie linki',
    TERMS_AND_CONDITIONS: 'Warunki korzystania',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Stworzone z ',
    ALL_OVER_THE: ' na całym ',
    TERMS_OF_USAGE: 'Nutzungsbedingungen',
    LANGUAGE_CODE: 'en',
    GET_HELP_24_7: 'Support',
    HELP_CENTER: 'Hilfeseite',
    COMPANY: 'Unternehmen',
    WE_ACCEPT: 'Zahlungsoptionen',
    DOWNLOAD_HEADOUT: 'Pobierz aplikację Headout',
    SCAN_CODES: 'Skanuj kody',
  },
  FREE_CANCELLATION: 'Bezpłatne anulowanie',
  FREE_CANCELLATION_SUBTEXT:
    'Rozumiemy, że plany się zmieniają – anuluj bezpłatnie do 72 godzin przed wydarzeniem.',
  FROM: 'Od',
  GET_CASHBACK: 'Zdobądź {0}% cashbacku',
  GROUP_TICKETS: 'Bilety grupowe',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '18+ milionów zadowolonych klientów',
    SUB_TEXT:
      'Zadowolenie klientów jest naszym priorytetem. Dołącz do grona naszych szczęśliwych klientów.',
  },
  HELP_CENTER: {
    MAIN_TEXT: 'Centrum pomocy 24/7',
    SUB_TEXT:
      'Masz pytania lub obawy? Możesz liczyć na naszą pomoc 24/7 — przez telefon, czat oraz e-mail.',
  },
  INCLUSIONS: 'W cenie',
  LANGUAGE: 'Język',
  LANGUAGES: {
    ENGLISH: 'angielski',
    SPANISH: 'hiszpański',
    FRENCH: 'francuski',
    ITALIAN: 'włoski',
    GERMAN: 'niemiecki',
    PORTUGUESE: 'portugalski',
    NEDERLANDS: 'holenderski',
    POLISH: 'polski',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Wycieczka dostępna w języku: {0}',
  LISTICLES: {
    KNOW_MORE: 'Dowiedz się więcej',
    SEATING_CHART: 'Rozkład miejsc',
    WHY_BOOK_FROM_US: 'Czemu warto zarezerwować u nas?',
  },
  MORE_DETAILS: 'Więcej szczegółów',
  MORE_CURRENCIES: 'Więcej walut',
  NEW: 'NOWOŚĆ',
  NEW_ARRIVAL: 'Nowość',
  NEXT_AVAILABLE: 'Następne dostępne: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout to marka, której zaufało ponad 15 milionów odwiedzających, oferująca starannie dobraną selekcję najlepszych aktywności. To nie jest strona internetowa obiektu.',
  NO_RESULT_FOUND: 'Hmm, nie znaleziono wyników.',
  OFF: 'zniżki',
  OPEN_DATED_DESCRIPTOR: 'Rezerwuj z elastycznością - nie musisz wybierać daty',
  OPENING_DATE: 'Data premiery',
  OPENING_ON: 'Premiera',
  OPENS: 'Premiera',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout jest autoryzowanym i zaufanym partnerem obiektu, który oferuje wybór najlepszych aktywności, pozwalających Ci poznać tę atrakcję. To nie jest strona internetowa obiektu.',
  POPULAR_CURRENCIES: 'Popularne waluty',
  PRICES_STARTING: 'Ceny od',
  PROMO_CODES: {
    APPLY_CODE: 'ZASTOSUJ KOD',
    APPLIED: 'ZASTOSOWANO',
    TOOL_TIP_INFO: 'Ta zniżka zostanie zastosowana przy finalizacji zamówienia',
    DESCRIPTION: {
      ABSOLUTE: 'Uzyskaj {0} zniżki',
      CAPPED: 'Uzyskaj {0}% zniżki, do {1}',
      PERCENTAGE: 'Uzyskaj {0}% zniżki',
    },
    REMOVE: 'USUŃ',
  },
  RATINGS: 'Oceny: {0}',
  READ_MORE: 'Czytaj więcej',
  READ_MORE_TEXT: 'Czytaj więcej',
  READ_LESS: 'Czytaj mniej',
  VIEW_DETAILS: 'Wyświetl szczegóły',
  REOPENING: 'Ponowne rozpoczęcie',
  REOPENING_DATE: 'Data ponownego rozpoczęcia',
  REOPENING_ON: 'Ponowne rozpoczęcie',
  REOPENS: 'Rozpoczyna się ponownie',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      CTA_URL:
        'https://www.austria.info/en/service-and-facts/coronavirus-information/entry-regulations',
      TEXT: 'Obowiązują przepisy dotyczące 2G: dostęp do zakwaterowania, instytucji kultury, restauracji/barów jest możliwy tylko z dowodem pełnego zaszczepienia lub przeszłego zakażenia. Ujemny wynik testu na obecność COVID-19 nie jest już wystarczający.',
    },
    AU_DESCRIPTION: {
      CTA_URL:
        'https://www.smartraveller.gov.au/COVID-19/COVID-19-vaccinations',
      TEXT: 'Odwiedzający w wieku 16 lat i starsi muszą zaprezentować dowód szczepienia przeciw COVID-19 lub zwolnienie ze szczepienia. ',
    },
    BANNER_CTA: 'Dowiedz się więcej',
    BERLIN_DESCRIPTION: {
      CTA_URL:
        'https://www.berlin.de/en/news/coronavirus/7081102-6098215-berlin-introduces-extensive-2G-rule.en.html',
      TEXT: 'Obowiązują zasady 2G: wstęp mają jedynie w pełni zaszczepieni odwiedzający i ozdrowieńcy, którzy przedstawią odpowiednie certyfikaty. Odwiedzający poniżej 18 roku życia lub ci, którzy nie mogą być zaszczepieni z powodów medycznych, muszą przedstawić przy wejściu negatywny wynik testu na COVID. Ci, którzy z powodów medycznych nie mogą się zaszczepić, również powinni to udowodnić, prezentując odpowiednie zwolnienie ze szczepienia przed wejściem.',
    },
    CTA_TEXT: 'Szczegóły bezpieczeństwa',
    DESCRIPTION_CTA: 'Dowiedz się więcej.',
    EU_DESCRIPTION: {
      CTA_URL:
        'https://www.diplomatie.gouv.fr/en/coming-to-france/coronavirus-advice-for-foreign-nationals-in-france/coronavirus-statements/article/applying-for-a-covid-certificate-if-you-were-vaccinated-abroad-procedure-for',
      TEXT: 'Od 21 lipca 2021 r. wszyscy odwiedzający w wieku 12 lat i starsi muszą zaprezentować unijny certyfikat COVID. ',
    },
    EU_HEADING: 'Wymagany unijny certyfikat COVID',
    EU_PREFIX: 'Uwaga: ',
    EXPERIENCE_DESCRIPTION:
      'Ta aktywność została zweryfikowana jako aktywność zgodna z najwyższymi standardami bezpieczeństwa według lokalnych przepisów oraz Światowej Organizacji Zdrowia',
    FLAG_TEXT: 'Największe bezpieczeństwo',
    GENERAL_DESCRIPTION:
      'Wszystkie aktywności z tą odznaką zostały zweryfikowane jako aktywności zgodne z najwyższymi standardami bezpieczeństwa według lokalnych przepisów dotyczących zdrowia.',
    HEADING: 'Najwyższe standardy bezpieczeństwa',
    IT_DESCRIPTION: {
      CTA_URL: 'https://www.dgc.gov.it/web/per-cosa-serve.html#viaggi',
      TEXT: 'Od 6 sierpnia 2021 r. wszyscy odwiedzający w wieku 11 lat i starsi muszą zaprezentować unijny certyfikat COVID, czyli tak zwany paszport covidowy. ',
    },
    IT_PREFIX: 'Uwaga: ',
    MOBILE_HEADING: 'Bezpieczne aktywności',
    MODAL: {
      BADGE_DESCRIPTION:
        'Ta odznaka na aktywności potwierdza, że standardy bezpieczeństwa zostały przez nas zweryfikowane',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Wszystkie sprzęty, pojazdy i często dotykane powierzchnie są odkażane po każdym użyciu. Po prostu usiądź wygodnie i ciesz się wydarzeniem.',
          HEADING: 'Wszystkie powierzchnie i sprzęty są odkażane',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Wszystkie sprzęty dostępne podczas aktywności są starannie odkażane po każdym użyciu. Zawsze.',
          HEADING: 'Wszystkie powierzchnie i sprzęty są odkażane',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Wszystkie pojazdy dostępne podczas aktywności są starannie odkażane po każdym użyciu. Zawsze',
          HEADING: 'Wszystkie pojazdy są odkażane',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Podczas tej bezpiecznej aktywności będziesz mieć dostęp do mydła i stacji sanitarnych. Bez obaw! ',
          HEADING: 'Mydło oraz stacje sanitarne dostępne w obiekcie',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Maski są obowiązkowe dla wszystkich odwiedzających oraz pracowników podczas tej aktywności. Dzięki temu wszyscy mogą bawić się przy zachowaniu bezpieczeństwa.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Nasi partnerzy, którzy zostali zweryfikowani jako „Bezpieczne aktywności”, przestrzegają lokalnych regulacji dotyczących noszenia maseczek. Jeśli jest to obowiązkowe, wszyscy odwiedzający i pracownicy noszą maseczki. Robią, co w ich mocy, by zapewnić Ci komfort i bezpieczeństwo.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Maski są obowiązkowe dla wszystkich odwiedzających podczas tej aktywności. Dzięki temu wszyscy mogą bawić się przy zachowaniu bezpieczeństwa.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Wszyscy pracownicy podczas tej aktywności noszą maseczki na twarzy, żeby zapewnić Ci maksymalną zabawę i minimalne zmartwienia.',
          HEADING: 'Wszyscy noszą maski dla Twojego bezpieczeństwa',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Podczas tej wycieczki obowiązują zasady dotyczące dystansu społecznego. Obowiązują ograniczenia ilości osób, aby umożliwić przestrzeganie zasad dotyczących dystansu społecznego.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Podczas tej wycieczki obowiązują zasady dotyczące dystansu społecznego. Obowiązują ograniczenia ilości osób, aby umożliwić przestrzeganie zasad dotyczących dystansu społecznego. Aby to umożliwić, wizyty w dużych grupach nie są dozwolone.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Podczas tej aktywności cały czas przestrzega się zasad dotyczących dystansu społecznego.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Podczas tej aktywności cały czas przestrzega się zasad dotyczących dystansu społecznego. Aby to umożliwić, mogą obowiązywać ograniczenia dotyczące ilości osób. Oddychaj bez obaw.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Podczas tej aktywności cały czas przestrzega się zasad dotyczących dystansu społecznego. Aby to umożliwić, wizyty w dużych grupach nie są dozwolone.',
          HEADING: 'Przestrzega się zasad dotyczących dystansu społecznego',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Temperatura wszystkich odwiedzających zostanie sprawdzona na początku wycieczki, aby zapewnić wszystkim bezpieczeństwo. Temperatura wszystkich pracowników jest wielokrotnie sprawdzana każdego dnia.',
          HEADING: 'Obowiązuje sprawdzanie temperatury',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Temperatura wszystkich odwiedzających zostanie sprawdzona na początku wycieczki, aby zapewnić wszystkim bezpieczeństwo. ',
          HEADING: 'Obowiązuje sprawdzanie temperatury',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Temperatura wszystkich pracowników jest wielokrotnie sprawdzana. Pracownikom, których temperatura przekracza limit, zabrania się wstępu; są proszeni o zostanie w domu do momentu powrotu do zdrowia.',
          HEADING: 'Obowiązuje sprawdzanie temperatury',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Pracownicy obsługujący aktywność są przeszkoleni zgodnie z wytycznymi WHO i są w stanie poradzić sobie ze wszelkimi potencjalnymi wypadkami i sytuacjami',
          HEADING: 'Pracownicy są przeszkoleni z zakresu wytycznych WHO',
        },
      },
      HEADING: 'Bezpieczne aktywności',
      SUB_HEADING:
        'Pracujemy z naszymi partnerami z całego świata, aby wdrażać najwyższe standardy bezpieczeństwa zgodne z wytycznymi Światowej Organizacji Zdrowia. Wszystkie środki bezpieczeństwa podejmowane w miejscu aktywności zostały zweryfikowane i są tu wyświetlane. Czas znów cieszyć się światem wokół nas.',
    },
    NL_DESCRIPTION: {
      CTA_URL:
        'https://www.government.nl/topics/coronavirus-covid-19/covid-certificate',
      TEXT: 'Odwiedzający w wieku 13 lat i starsi muszą mieć (cyfrowy lub wydrukowany) certyfikat COVID, który potwierdza szczepienie, negatywny wynik niedawno zrobionego testu lub ważny certyfikat ozdrowieńca. Noszenie maseczki jest obowiązkowe. ',
    },
    SG_DESCRIPTION: {
      CTA_URL: 'https://safetravel.ica.gov.sg/health/vtsg',
      TEXT: 'Od 13 października 2021 r. tylko w pełni zaszczepieni odwiedzający mogą wchodzić w dwuosobowych grupach. Przed wejściem konieczne będzie zaprezentowanie dowodu szczepienia, negatywnego wyniku niedawno zrobionego testu przeciwko COVID-19 i/lub certyfikatu ozdrowieńca. ',
    },
    SHORT_HEADING: 'Obowiązują najwyższe standardy bezpieczeństwa',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Szczegóły bezpieczeństwa',
    EXPERIENCE_DESCRIPTION:
      'Ta aktywność została zweryfikowana jako aktywność zgodna z najwyższymi standardami bezpieczeństwa według lokalnych przepisów oraz Światowej Organizacji Zdrowia',
    FLAG_TEXT: 'Największe bezpieczeństwo',
    GENERAL_DESCRIPTION:
      'Ten obiekt jest ZABEZPIECZONY PRZED COVID i przestrzega wszystkich środków bezpieczeństwa zalecanych przez rząd w celu zapewnienia wszystkim bezpiecznej zabawy przy zachowaniu dystansu społecznego podczas wizyty w teatrze.',
    GENERAL_DESCRIPTION_V2:
      'Opracowaliśmy znany w całej branży symbol „Zobacz to bezpiecznie”, więc gdy teatry otworzą się ponownie, będziesz móc czuć się bezpiecznie, wiedząc, że obiekt został zabezpieczony przed COVID i przestrzega najnowszych wytycznych rządowych i wytycznych dotyczących sztuk widowiskowych.',
    HEADING: 'Zobacz to bezpiecznie',
    MOBILE_HEADING: 'Bezpieczne aktywności',
    MORE_CURRENCIES: 'Więcej walut',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Akceptowane są jedynie bilety wydrukowane w&nbsp;domu lub e-bilety</li>',
          HEADING: 'Bezdotykowe e-bilety',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Aby wejść do obiektu, konieczne jest noszenie środków ochrony osobistej takich jak maseczki</li>\n            <li>Przed wejściem do&nbsp;obiektu sprawdzona zostanie temperatura wszystkich widzów</li>',
          HEADING: 'Zapobiegawcze środki bezpieczeństwa',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Aby wejść do obiektu, konieczne jest noszenie środków ochrony osobistej takich jak maseczki</li>\n            <li>Przed wejściem do&nbsp;obiektu sprawdzona zostanie temperatura wszystkich widzów</li>',
          HEADING: 'Sanitaryzacja',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Obiekt został zmieniony, tak aby minimalizować kontakt między widzami</li>\n            <li>Różnym grupom przydzielane są oddzielne miejsca</li>\n            <li>W&nbsp;miarę możliwości zorganizowane zostanie wstępne zamawianie przekąsek na przerwę</li>\n            <li>Zalecane są bezdotykowe, elektroniczne transakcje.</li>\n            <li>Widzów prosi się o ograniczenie ilości zabieranych ze sobą przedmiotów osobistych, ponieważ szatnie mogą być zamknięte</li>\n            <li>Aktywności takie jak robienie zdjęć z&nbsp;artystami czy rozdawanie autografów mogą być ograniczone</li>\n            ',
          HEADING: 'Środki dystansu społecznego',
        },
      },
      HEADING: 'Zobacz to bezpiecznie',
      SUB_HEADING:
        'Zastanawiasz się, jakie kroki są podejmowane w celu zapewnienia bezpieczeństwa? Dowiedz się więcej o środkach bezpieczeństwa i protokołach bezpieczeństwa związanych z COVID, które zostały wprowadzone w teatrach w celu zapewnienia widzom bezpieczeństwa.',
    },
    SHORT_HEADING: 'Obowiązują najwyższe standardy bezpieczeństwa',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Twoje bezpieczeństwo jest naszym priorytetem',
    TEXT: 'Podjęliśmy istotne kroki w celu poprawy czystości i stosujemy środki dezynfekcyjne podczas kompleksowego i częstego czyszczenia powierzchni. Zapobiegamy też tłumom, kontrolując liczbę ludzi.',
  },
  SAVE: 'Zaoszczędź {0}%',
  SAVE_PERCENT: 'Zaoszczędź {0}%',
  SAVE_UPTO_PERCENT: 'Zaoszczędź do {0}%',
  SEE_ALL: 'Zobacz wszystko',
  SEARCH: 'Szukaj',
  POPULARITY: 'Popularność',
  PRICE: 'Cena',
  SEE_MORE_SHOWS: 'Zobacz więcej spektakli',
  SELECT_CITY: 'Wybierz miasto',
  SELECT_SECTION: 'Wybierz sekcję',
  SEE_ALL_PHOTOS: 'Zobacz wszystkie zdjęcia',
  SHOW_CLOSED: 'Spektakl zakończony',
  SHOW_LESS: 'Pokaż mniej',
  SHOW_LESS_TEXT: 'Pokaż mniej',
  SHOW_MORE: 'Pokaż więcej',
  SHOW_PAGE: {
    ABOUT_SHOW: 'O spektaklu',
    ABOUT_THEATRE: 'O teatrze',
    ADDITIONAL_INFORMATION: 'Informacje dodatkowe',
    AGE_LIMIT: 'Ograniczenie wiekowe',
    AGE_SUITABILITY: 'Odpowiedni wiek',
    ANSWER: ['Odpowiedź:'],
    BLOG_SHOW_PAGE: 'Blog: strona spektaklu',
    BLOG_SUMMARY: 'Blog: podsumowanie',
    BLOG_THEATRE_PAGE: 'Blog: strona teatru',
    BLOG_THEATRE_SEATING_PLAN: 'Blog: układ siedzeń teatru',
    CANCELLATION_AND_REFUNDS: 'Anulowanie i zwroty',
    CANCELLATION_POLICY: 'Zasady anulowania',
    CAST_AND_CREW: 'Obsada i ekipa',
    CLOSING_DATE: 'Data zakończenia',
    CLOSING_DATE_SPECIAL_OFFER: 'Oferta specjalna: ostatni termin',
    DURATION: 'Czas trwania',
    FACILITIES_AND_ACCESSIBILITY: 'Udogodnienia i dostępność',
    FREQUENTLY_ASKED_QUESTIONS: 'Często zadawane pytania',
    GETTING_THERE: 'Dojazd',
    GETTING_THERE_MAP_LINK: 'Dojazd: link do mapy',
    GOOGLE_MAP: 'Mapa Google',
    HIGHLIGHTS: 'Główne punkty',
    LISTICLE_SHOW_SUMMARY: 'Listicle Podsumowanie spektaklu',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Dlaczego warto obejrzeć',
    OPENING_DATE: 'Data premiery',
    QUESTION: ['Pytanie:'],
    SAFETY_BANNER: 'Baner bezpieczeństwa',
    SHOW_DETAILS: 'Szczegóły spektaklu',
    SHOW_TIMINGS: 'Terminy spektakli',
    SHOW_TYPE: 'Rodzaj spektaklu',
    SPECIAL_OFFER: 'Oferta specjalna',
    THE_STORY: 'Historia',
    THEATRE_ADDRESS: 'Adres teatru',
    THEATRE_CAPACITY: 'Pojemność teatru',
    THEATRE_NAME: 'Nazwa teatru',
    TICKETS: 'Bilety',
    TICKETS_REDEMPTION: 'Odbiór biletów',
    TOP_SONGS: 'Popularne utwory',
    YOUR_TICKETS: 'Twoje bilety',
    ABOUT_CONCERT: 'O koncercie',
    PROGRAM: 'Program',
  },
  SORT_BY: 'Sortuj według',
  SPECIAL_OFFER: 'Oferta specjalna',
  THEATRE: 'Teatr',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Pobliskie teatry',
    NOW_PLAYING: 'Aktualnie wystawiane',
    UPCOMING_SHOWS: 'Nadchodzące spektakle',
    PAST_SHOWS: 'Minione spektakle',
    FIND_BEST_SEATS: 'Znajdź najlepsze miejsca',
  },
  TICKET_CAN_BE_CANCELED:
    'Możesz anulować z wyprzedzeniem do {hours} godzin, aby uzyskać pełen zwrot pieniędzy.',
  TICKET_CANNOT_BE_CANCELED:
    'Tego biletu nie można anulować, ale na żądanie można przenieść go na inny termin.',
  TICKETS: 'Bilety',
  TIMINGS: 'Harmonogram',
  SPECIAL_PRODUCT_HEADING: 'Najbardziej uwielbiane',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Profesjonalni lokalni przewodnicy',
    ENGAGING_STORIES: 'Wciągające historie',
    TOP_RATED: 'Najwyżej oceniane',
  },
  GUIDED_TOUR_REVIEWS: [
    'Nasza przewodniczka Angela była wspaniała i bardzo dobrze znała obiekt',
    'Przewodnik chętnie odpowiadał na pytania dotyczące wycieczki',
    'Nasza przewodniczka była świetna, a nawet poleciła nam świetne miejsce na lunch!',
    'Dzięki dobrej organizacji i naszemu przewodnikowi doświadczenie było naprawdę przyjemne',
    'Dużo treści edukacyjnych, na pewno zrobię to ponownie z moimi dziećmi',
    'Wycieczka była dobrze zorganizowana i miała odpowiedni czas trwania',
    'Nasz przewodnik naprawdę znał się na rzeczy i czuło się jego pasję do historii',
    'Dobry przewodnik i organizacja! Polecam!!!',
    'Zabawne ciekawostki naszego przewodnika sprawiły, że wszyscy byliśmy aktywni i zainteresowani',
    'Wycieczka miała dobre tempo i mogliśmy zwiedzać bez pośpiechu',
    'Nasza przewodniczka Maria była w stanie zdobyć miejsca z najlepszym widokiem',
    'Nasz przewodnik wzbogacił naszą wizytę w sposób, który nie byłby możliwy bez niego',
    'Szczegółowa i poruszająca wycieczka prowadzona przez pełnego pasji przewodnika',
    'Jeff pokazał nam aspekty obiektu, które inaczej by nam umknęły',
  ],
  GUIDES_BANNER:
    'Zwiedzaj jak miejscowy z naszymi przewodnikami uwielbianymi przez odwiedzających.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Zwiedzanie z przewodnikiem to najlepszy sposób na poznanie tego miejsca. Nasi profesjonalni przewodnicy pełnią rolę Twoich lokalnych znajomych, dzieląc się historiami, ukrytymi perełkami i rekomendacjami podróżniczymi.',
    'Nie tylko odwiedzaj - doświadczaj!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Poznaj opinie naszych gości',
  GUIDES: 'Przewodniki',
  TODAY: 'Dzisiaj',
  TOMORROW: 'Jutro',
  TOUR_LIST_HEADING: 'Wybierz aktywność',
  TOUR_LIST_SUB_HEADING:
    'Wybieraj spośród wielu biletów, wycieczek i zestawów biletów sprawdzonych operatorów',
  UGC: {
    FOLLOW: 'Obserwuj',
    FOLLOW_IG: 'Obserwuj na Instagramie',
    HEADING: 'Wyobraź sobie: Tak wygląda Twoja kolejna przygoda',
    SUB_HEADING: 'Wybrane z 💜 przez Headout',
  },
  UNAVAILABLE: 'Niedostępne',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Ważność tych biletów została przedłużona. Na bilecie znajdziesz dokładne informacje.',
    UNTIL_DATE: 'Te bilety są ważne do {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Te bilety są ważne przez {0} dni od daty zakupu.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Te bilety są ważne przez {0} mies. od daty zakupu.',
  },
  TABLE_OF_CONTENTS: 'Zawartość',
  VIEW_LESS: 'Wyświetl mniej',
  VIEW_MORE: 'Wyświetl więcej',
  WHY_TAKE_THIS_DAY_TRIP:
    'Dlaczego warto wybrać się na tę wycieczkę jednodniową?',
  WHY_WATCH: 'Dlaczego warto to obejrzeć {0}?',
  FIND_ON_MAP: 'Znajdź na mapie',
  LTT_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Bilety z kas',
        DESCRIPTION: 'Natychmiastowe potwierdzenie na telefon',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Wybór miejsc`,
        DESCRIPTION: 'Widok, na jakim Ci zależy, zawsze',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Wyjątkowe oferty i zniżki',
        DESCRIPTION: `Londyńskie teatry w najlepszych cenach`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Prosta rezerwacja',
        DESCRIPTION: 'Zaufało nam już ponad 22 miliony gości',
      },
    },
    YOUR_PICK: 'Twój wybór',
    BROWSE_BY_CATEGORIES: 'Przeglądaj według kategorii',
    TOP_WEST_END_SHOWS: 'Popularne spektakle na West Endzie',
    TOP_SHOWS: 'Melhores espetáculos',
    SEE_MORE_SHOWS: 'Ver mais {0} espetáculos',
    LAST_MINUTE_TICKETS: 'Bilety last minute',
    LOVED_BY_MILLIONS: 'Uwielbiane przez miliony',
    TODAY: 'Dzisiaj',
    TOMORROW: 'Jutro',
    SEE_ALL: 'Zobacz wszystko',
    GRAB_YOUR_TICKETS: 'Zdobądź bilety już teraz',
  },
  TAG_NAME: {
    BALLET: 'Balet',
    CABARET: 'Kabaret',
    CHRISTMAS: 'Boże Narodzenie',
    CIRCUS: 'Cyrk',
    CLASSIC: 'Klasyka',
    COMEDY: 'Komedie',
    COMING_SOON: 'Już wkrótce',
    CRITICS_CHOICE: 'Wybór krytyków',
    DANCE: 'Taniec',
    DISNEY: 'Disney',
    DRAMA: 'Dramaty',
    ENGLISH_NATIONAL_BALLET: 'Narodowy Balet Angielski',
    ENGLISH_NATIONAL_OPERA: 'Angielska Opera Narodowa',
    FANTASY: 'Fantasy',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Teatr immersyjny',
    JUKEBOX: 'Jukebox',
    KIDS: 'Dzieci',
    MAGIC: 'Magia',
    MUSICALS: 'Musicale',
    NEW_ARRIVAL: 'Nowość',
    OFF_WEST_END: 'Poza West Endem',
    OLIVIER_WINNER: 'Nagroda Oliviera',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomimy',
    PLAYS: 'Sztuki',
    ROMANCE: 'Romanse',
    SHAKESPEARE: 'Szekspir',
    STARS_ON_STAGE: 'Gwiazdy na scenie',
    THEATRICAL_CONCERT: 'Koncert teatralny',
    TRUE_STORY: 'Prawdziwe historie',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Ups, mamy problem',
    MESSAGE:
      'Przepraszamy! Wszystkie aktywności tego dnia są wyprzedane lub\n    niedostępne. Ale jest ich mnóstwo w innych terminach. Jedyne,\n    co musisz zrobić, to zachować elastyczność.',
    CTA: 'Wyświetl wszystkie daty',
  },
  ALL_DATES: 'Wszystkie daty',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Menu główne',
    EXPLORE: 'Odkrywaj',
    VISIT: 'Wizyta',
    THINGS_TO_DO: 'Atrakcje',
    CITY_ATTRACTIONS: 'Atrakcje: {0}',
    TOP_THINGS_TO_DO: 'Najpopularniejsze atrakcje',
    CITY_TOURS: 'Wycieczki: {0}',
    CITY_GUIDE: 'Przewodnik po mieście',
    ATTRACTIONS: 'Atrakcje',
    CRUISES: 'Rejsy',
    THEMES: 'Motywy',
    ABOUT: 'Informacje',
    TOURS: 'Wycieczki',
    SKIP_THE_LINE_TOURS: 'Wycieczki „Omiń kolejkę”',
    GUIDED_TOURS: 'Wycieczki z przewodnikiem',
    NIGHT_TOURS: 'Wycieczki nocą',
    FOOD_TOURS: 'Wycieczki kulinarne',
    HISTORY: 'Historia',
    ARCHITECTURE: 'Architektura',
    DESIGN: 'Design',
    INSIDE: 'Wnętrze',
    COLLECTIONS: 'Kolekcje',
    PAINTINGS: 'Obrazy',
    ANIMALS_EXHIBITS: 'Zwierzęta i wystawy',
    HABITATS: 'Środowisko i siedliska',
    CONSERVATION: 'Ochrona przyrody',
    PROGRAMMES: 'Programy',
    A2_SIGHTSEEING_CRUISES: 'Rejsy wycieczkowe',
    A2_DINNER_CRUISES: 'Rejsy z kolacją',
    A2_EVENING_CRUISES: 'Rejsy nocą',
    A2_LUNCH_CRUISES: 'Rejsy z lunchem',
    A2_YACHT_TOURS: 'Wycieczki jachtem',
    PLAN_YOUR_VISIT: 'Zaplanuj wizytę',
    TIMINGS: 'Harmonogram',
    DIRECTIONS: 'Dojazd',
    PARKING: 'Parking',
    ROUTES: 'Trasy',
    REQUIREMENTS: 'Wymagania',
    LOCATION: 'Lokalizacja',
    RULES: 'Zasady',
    FAQs: 'Często zadawane pytania',
    ENTRANCES: 'Wejścia',
    RESTAURANTS: 'Restauracje',
    FACTS: 'Fakty',
    TIPS: 'Wskazówki',
    MAP: 'Mapa',
    RIDES: 'Przejazdy',
    SHOWS: 'Spektakle',
    DINING: 'Posiłki',
    SHOPPING: 'Zakupy',
    EVENTS: 'Wydarzenia',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Boże Narodzenie',
    NEW_YEARS_EVE: 'Sylwester',
    TRAVEL_GUIDE: 'Przewodnik turystyczny',
    TRIP_PLANNER: 'Planowanie podróży',
    ITINERARY: 'Plan podróży',
    TRAVEL_TIPS: 'Porady dotyczące podróży',
    WEATHER: 'Pogoda',
    BEST_TIME_TO_VISIT: 'Najlepsza pora na wizytę',
    JANUARY: 'Styczeń',
    FEBRUARY: 'Luty',
    MARCH: 'Marzec',
    APRIL: 'Kwiecień',
    MAY: 'Maj',
    JUNE: 'Czerwiec',
    JULY: 'Lipiec',
    AUGUST: 'Sierpień',
    SEPTEMBER: 'Wrzesień',
    OCTOBER: 'Październik',
    NOVEMBER: 'Listopad',
    DECEMBER: 'Grudzień',
    WHERE_TO_EAT: 'Jedzenie',
    WHERE_TO_STAY: 'Zakwaterowanie',
    NEIGHBOURHOODS: 'Dzielnice',
    FAMILY_TRAVEL: 'Podróże z rodziną',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festiwale i imprezy',
  },
  CALENDAR: {
    FOOTNOTE: '* Wszystkie ceny są podane w {0}',
  },
  LTT_SHOW_PAGE: {
    READ_MORE_REVIEWS: 'Czytaj więcej recenzji',
    SHOW_MORE_REVIEWS: 'Pokaż więcej recenzji',
    ALL_PHOTOS: 'Wszystkie zdjęcia',
    MORE_DATES: 'Więcej dat',
    SELLING_OUT_FAST: 'Szybko się wyprzedaje',
    SELECT_TIME_SLOT: 'Wybierz przedział czasowy',
    SELECT_TIME_SLOT_ERROR: 'Wybierz przedział czasowy, aby kontynuować',
    PRICE_STARTING_FROM: 'Cena miejsc od',
    SELECT_SEATS: 'Wybierz miejsca',
    READ_MORE: 'Czytaj więcej',
    RATINGS_AND_REVIEWS: 'Oceny i recenzje',
    READ_DETAILED_REVIEWS: 'Przeczytaj szczegółowe recenzje',
    INTERVAL: 'Przerwa',
    TWO_PART_SHOW: 'Spektakl w dwóch częściach',
    UNTIL_DATE: 'Do {0}',
    AVAILABLE_TIME: 'Dostępny przedział czasowy',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Ta aktywność jest dostępna tylko o poniższej godzinie',
    CONTENT_TABS: {
      ABOUT: 'Informacje',
      VENUE: 'Obiekt',
      TICKETS: 'Bilety',
      Reviews: 'Recenzje',
    },
    SELECT_SHOW_TIMMING: 'Wybierz godzinę spektaklu',
    ONLY_ONE_SLOT: 'Tylko 1 przedział czasowy dostępny w wybranym dniu',
    SIMILAR_SHOWS: 'To też może Ci się spodobać',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Fabuła',
      AGE_SUITABILITY_AND_GUIDELINES: 'Odpowiedni wiek i dodatkowe wytyczne',
      WHAT_CRITICS_THINK: 'Co myślą krytycy',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Często zadawane pytania: {0}',
    },
  },
  BREADCRUMBS: {
    HOME: 'Strona główna',
    TRAVEL_GUIDE: 'Przewodnik turystyczny',
    THINGS_TO_DO: 'Aktywności w mieście {0}',
    SHOW_NAME_TICKETS: '{0} - bilety',
    LTT_HOME: 'Bilety do teatru w Londynie',
    LTT_VENUE_PAGE_HOME: 'Teatry w Londynie',
    BROADWAY_HOME: 'Bilety na spektakl na Broadwayu',
    BROADWAY_VENUE_PAGE_HOME: 'Teatry na Broadwayu',
    VIENNA_CONCERT_HOME: 'Bilety na koncert w Wiedniu',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Sale koncertowe w Wiedniu',
    ATTRACTIONS: 'Atrakcje',
    A2_SIGHTSEEING_CRUISES: 'Rejsy wycieczkowe',
    A2_DINNER_CRUISES: 'Rejsy z kolacją',
    A2_EVENING_CRUISES: 'Rejsy nocą',
    A2_LUNCH_CRUISES: 'Rejsy z lunchem',
    A2_YACHT_TOURS: 'Wycieczki jachtem',
    LONDON_THEATRE_NEWS: 'Aktualności z londyńskich teatrów',
    BROADWAY_SHOW_NEWS: 'Aktualności na temat spektakli na Broadwayu',
    NEWS_PAGE: 'Strona aktualności',
  },
  AMENITIES: {
    Restaurant: 'Restauracja',
    Cafe: 'Kawiarnia',
    'Dedicated Parking': 'Dedykowany parking',
    Elevators: 'Windy',
    Lift: 'Winda',
    'Wheelchair Accessible': 'Dostępne dla osób na wózków inwalidzkich',
    Cloakroom: 'Szatnia',
    'Air Conditioning': 'Klimatyzacja',
    WiFi: 'Wi-Fi',
    Bar: 'Bar',
    'Water Fountain': 'Wodotrysk z wodą pitną',
    Washrooms: 'Łazienki',
    Toilets: 'Toalety',
    Binoculars: 'Lornetki',
    'Adapted Toilets': 'Przystosowane toalety',
    'Accessible Toilets': 'Toalety dla niepełnosprawnych',
    'Assistive Listening System': 'System wspomagający słyszenie',
    'Hearing Assistance': 'Wspomaganie słuchu',
    'Booster Cushions': 'Poduszki podwyższające',
    Shop: 'Sklep',
    'Souvenir Shop': 'Sklep z pamiątkami',
    'Guide Dogs': 'Psy przewodnicy',
    'Baby Changing Facilities': 'Przebieralnia dla dzieci',
    'Security Check': 'Kontrola bezpieczeństwa',
    Ramp: 'Rampa',
    'Level Access': 'Wejście bez schodów',
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Profesjonalni wielojęzyczni przewodnicy',
    STL: 'Wstęp bez kolejki',
    PERSONALIZED: 'Spersonalizowane doświadczenie',
    LOCAL_FOOD: 'Lokalne jedzenie i kultura',
    MULTILINGUAL_GUIDES: 'Wielojęzyczni przewodnicy',
    CULINARY_EXPERTS: 'Specjaliści kulinarni',
    SIGHTSEEING: 'Zwiedzanie i rozrywka na pokładzie',
    MULTILINGUAL_GT: 'Wycieczki z przewodnikiem w wielu językach',
    MULTI_ROUTES: 'Wiele opcji tras',
    HASSLE_FREE: 'Bezproblemowa rezerwacja',
    FREQUENT_DEPARTURES: 'Częste wyjazdy',
    ONBOARD_AMENITIES: 'Najlepsze udogodnienia na pokładzie',
    FLEXI_TRAVEL: 'Elastyczne podróże na wielu trasach',
    FLEXI_EXCHANGE_CANCEL: 'Elastyczne opcje zmiany i anulowania',
    EXTRA_DISCOUNT: 'Dodatkowe zniżki dla młodzieży, seniorów i rodzin',
    PREPAID: 'Wygodna wcześniejsza płatność',
    EASY_ACTIVATION: 'Łatwa aktywacja',
    INSTANT_CONNECTIVITY: 'Natychmiastowa łączność z globalnym zasięgiem',
    ROUND_TRIP: 'Transfery w obie strony',
    CULTURAL_EXPERIENCE: 'Autentyczne doświadczenia kulturowe',
    GUARANTEED_SEAT: 'Gwarantowane miejsce',
    ONBOARD_WIFI: 'Wbudowane porty Wi-Fi i ładowania',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout wykorzystuje pliki cookie, aby usprawnić korzystanie ze strony internetowej, bajt po bajcie.',
    MOBILE: 'Wykorzystywane pliki cookie.',
    LEARN_MORE: 'Dowiedz się więcej.',
  },
  SHOW_UNAVAILABLE: 'Spektakl niedostępny',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Polecane aktualności',
    ALL_NEWS: 'Wszystkie aktualności',
    MORE_READS: 'Więcej artykułów',
    LOAD_MORE: 'Załaduj więcej',
    TRAILERS: 'Zwiastuny',
    GET_YOUR_TICKETS: 'Pobierz bilety',
    POPULAR_SHOWS: 'Popularne spektakle',
  },
  HOHO: {
    ROUTE_DETAILS: 'Route Details',
    MORE_DETAILS: 'More Details',
    ROUTES_SCHEDULES: 'Routes & Schedules',
    TOP_ATTRACTIONS: 'Top attractions covered',
    TIMINGS: 'TIMINGS',
    FREQUENCY: 'FREQUENCY',
    DURATION: 'DURATION',
    CALENDAR_FOOTNOTE: '* Wszystkie ceny są podane w {0}',
  },
  PC_EXP: {
    SHOW_INCL: 'Zobacz, co wchodzi w cenę biletu i poznaj inne informacje',
  },
  OFF_PERCENT: '{0}% zniżki',
};
export default pl;
