const pt = {
  AUDIO_GUIDE: {
    BANNER: 'Guia de áudio gratuito',
    PRODUCT_SUFFIX: 'e Guia de Áudio',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Parceiro autorizado e de confiança',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Revendedor autorizado',
    SUB_TEXT: 'Experiências reais de parceiros confiáveis e verificados.',
  },
  AVAILABLE: 'Disponível',
  BANNER_CTA: 'Faça sua reserva',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout é uma marca que já conquistou a confiança de milhões de visitantes em todo o mundo oferecendo experiências selecionadas para esta atração.',
    NON_PARTNERED_SENSITIVE:
      'Headout é uma marca que já conquistou a confiança de milhões de visitantes em todo o mundo oferecendo experiências selecionadas para esta atração. Este não é website oficial do local.',
    PARTNERED_NON_SENSITIVE:
      'Headout é um parceiro autorizado e confiável que oferece experiências selecionadas para esta atração.',
    PARTNERED_SENSITIVE:
      'Headout é um parceiro autorizado e confiável que oferece experiências selecionadas para esta atração. Este não é o website oficial do local.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout é um parceiro de confiança da atração, autorizado a oferecer uma seleção das melhores experiências.',
  BOOK_NOW_CTA: 'Reserve agora',
  BUY_TICKETS_CTA: 'Faça sua reserva',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Você pode cancelar estes ingressos até {0} horas antes do início da experiência para obter um reembolso total.',
    CANCELLABLE_ANYTIME:
      'Cancelamento gratuito a qualquer momento antes do início da sua experiência',
    CANCELLABLE_DAYS:
      'Você pode cancelar estes ingressos até {0} dias antes do começo da experiência e receber um reembolso completo.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Estes ingressos não podem ser cancelados. No entanto, eles são válidos por um período estendido.',
    HEADING: 'Política de alteração',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Estes ingressos não podem ser cancelados. No entanto, eles podem ser alterados até {0} horas antes do início da experiência.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Estes ingressos não podem ser cancelados ou alterados.',
    VALID_UNTIL_DATE:
      'Estes ingressos não podem ser cancelados. No entanto, você pode utilizá-los a qualquer momento até {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Estes ingressos não podem ser cancelados. No entanto, você pode utilizá-los a qualquer momento dentro dos próximos {0} dias.',
    VALID_WITHIN_NEXT_MONTHS:
      'Estes ingressos não podem ser cancelados. No entanto, você pode utilizá-los a qualquer momento dentro dos próximos {0} meses.',
  },
  CANCELLATION_POLICY_HEADING: 'Política de cancelamento',
  CASHBACK: '{0}% de cashback',
  CASHBACK_INFO:
    'Você recebe <strong>{0}%</strong> em cashback ao comprar esta experiência. O valor em cashback será automaticamente adicionado a sua conta Headout e poderá ser utilizado em sua próxima reserva com a Headout.',
  CATEGORY_SLIDER_HEADING:
    'Os clientes que reservaram esta experiência também viram',
  CHECK_AVAIL: 'Verificar disponibilidade',
  CITY_PAGE: {
    BANNER_TITLE: 'Experimente o melhor de',
    TOP_ATTRACTIONS: 'Melhores atrações',
    GO_BEYOND: 'Vá além de {0}',
    ALL_DAY_TRIPS: 'Viagens de um dia',
    CITIES_NEARBY: 'Cidades próximas',
    POPULAR_CATEGORIES: 'Categorias populares',
    GO_TO_GUIDE: 'Guia de viagem: {0}',
    VIEW_TRAVEL_GUIDE: 'Ver o guia de viagem',
    EXPLORE: 'Explore {0}',
    GUIDE_SUBHEADING:
      'Explorar {0} nunca foi tão fácil! Nosso guia de viagem de {0} contém tudo que você precisa saber sobre a cidade, desde dicas gastronômicas até o que visitar, como chegar lá, onde se hospedar e muito mais!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Informações gerais',
      WHERE_TO_EAT: 'O que comer',
      WHERE_TO_STAY: 'Onde se hospedar',
      THINGS_TO_DO: 'O que fazer',
      WEATHER: 'Melhor época para visitar',
      NEIGHBOURHOODS: 'Comunidade local',
      TRANSPORTATION: 'Locomoção',
      TRIP_PLANNER: 'Planejamento da viagem',
      FAMILY_TRAVEL: 'Viajando com crianças',
      TRAVEL_TIPS: 'Dicas e truques de viagem',
      SHOPPING: 'Compras',
      ART_AND_CULTURE: 'Arte e cultura',
    },
    MAILER: {
      HEADING:
        'Inspirações para viajar a {0} diretamente na sua caixa de entrada',
      SUBHEADING:
        'Explore novas cidades com experiências selecionadas, cashback imediato, ofertas exclusivas e dicas de viagem essenciais!',
    },
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Saiba mais sobre requisitos de visto, câmbio, diferenças de fuso horário e muito mais para garantir uma chegada tranquila e uma estadia agradável.',
    WHERE_TO_EAT:
      '{0}: encante-se com a culinária local e prove delícias de todos os cantos da cidade.',
    WHERE_TO_STAY:
      '{0}: descubra as melhores opções de hospedagem com conforto e conveniência e tenha uma experiência inesquecível.',
    THINGS_TO_DO:
      'Experimente uma infinidade de atividades e atrações emocionantes que atendem a todos os gostos e garantem momentos inesquecíveis.',
    WEATHER:
      '{0}: planeje sua viagem e aproveite ao máximo sua visita curtindo experiências incríveis durante todo o ano.',
    NEIGHBOURHOODS:
      '{0}: conheça seus bairros vibrantes e as comunidades locais que tornam a cidade única.',
    TRANSPORTATION:
      '{0}: use o sistema de transporte e transite com facilidade com opções convenientes para explorar todas as atrações da cidade.',
    TRIP_PLANNER:
      '{0}: aproveite ao máximo o seu tempo na cidade com itinerários selecionados cuidadosamente para você curtir cada momento.',
    FAMILY_TRAVEL:
      'Curta em família e conheça atrações, parques e opções de entretenimento para crianças de todas as idades.',
    TRAVEL_TIPS:
      '{0}: descubra dicas e truques de viagem para melhorar sua visita e ter experiências inesquecíveis.',
    SHOPPING:
      'Explore um paraíso de compras com uma grande variedade de butiques, mercados e shoppings, oferecendo de tudo, de artesanato local a moda sofisticada.',
    ART_AND_CULTURE:
      '{0}: mergulhe na rica cena artística e cultural, de museus cativantes a festivais vibrantes que celebram o patrimônio local.',
  },
  CLOSE: 'Fechar',
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Utilizamos cookies e tecnologias semelhantes para muitas finalidades, inclusive para melhorar sua experiência em nosso site e para anúncios.',
    MANAGE_PREFERENCES: 'Configurações',
    PREFERNCES_SAVED: 'Suas preferências foram salvas',
    ACCEPT: 'Ok',
    ALLOW_ALL: 'Permitir tudo',
    DENY_ALL: 'Rejeitar tudo',
    COOKIES: 'Cookies:',
    HEADING: 'Valorizamos sempre a sua privacidade',
    DESCRIPTION: `*   Os cookies são pequenos ficheiros colocados no seu computador, dispositivo móvel ou qualquer outro dispositivo pelo Website/Plataforma, que contêm os detalhes do seu histórico de navegação entre as suas muitas utilizações.
*   Utilizamos diferentes tipos de cookies para controlar a sua utilização da nossa Plataforma e armazenar determinadas informações que nos ajudam a fornecer-lhe serviços mais personalizados. Certos cookies podem ser colocados no seu Dispositivo devido à sua utilização de quaisquer serviços disponíveis na nossa Plataforma.
*   Em termos gerais, utilizamos dois conjuntos diferentes de tecnologias neste âmbito:
    *   **Cookies ou Cookies de Navegador.** É um pequeno ficheiro que é automaticamente colocado no Seu Dispositivo quando acede à Nossa Plataforma. Pode dar instruções ao seu navegador para recusar todos os Cookies. No caso de não aceitar os nossos Cookies, poderá não conseguir utilizar algumas partes da nossa Plataforma.
    *   **Web Beacons.** Também designados por "clear gifs", "pixel tags" e "single-pixel gifs" que são anexados em várias secções da nossa Plataforma e dos nossos e-mails e que nos permitem monitorizar e compreender a atividade dos Utilizadores.
*   Estes cookies armazenados no seu dispositivo podem ser cookies "persistentes" ou de "sessão". Os Cookies persistentes são os que permanecem no seu Dispositivo mesmo quando está offline, enquanto que os Cookies de sessão são automaticamente eliminados assim que fecha o seu browser.
*   Utilizamos cookies de sessão e persistentes para os fins abaixo indicados:
    *   Cookies necessários / essenciais
        *   _Tipo:_ Cookies de sessão
        *   _Objetivo:_ Estes cookies são essenciais para que o Utilizador aceda a diferentes secções da Plataforma e, se não forem permitidos, poderá não conseguir aceder aos serviços disponíveis na Plataforma. Estes cookies ajudam-nos ainda a autenticar os Utilizadores e a prevenir qualquer tipo de atividade fraudulenta na Plataforma.
    *   Política de Cookies / Aviso Aceitação de Cookies
        *   _Tipo:_ Cookies persistentes
        *   _Objetivo:_ Estes cookies identificam se os utilizadores aceitaram a utilização de cookies.
    *   Cookies de funcionalidade
        *   _Tipo:_ Cookies persistentes
        *   _Objetivo:_ Estes Cookies permitem-nos recordar as escolhas que faz quando utiliza a Plataforma, tais como recordar os seus detalhes de início de sessão ou preferência de idioma. O objetivo principal destes Cookies é proporcionar ao Utilizador uma experiência mais personalizada sempre que utiliza a Plataforma.

_Todos os termos em maiúsculas utilizados acima estão definidos na Política de Privacidade. Para uma compreensão pormenorizada, consulte_ [_a Política de Privacidade_](/privacy-policy/)`,
  },
  COLLECTION_SLICE_HEADING: 'Melhores coisas para fazer em {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Selecionar',
    SELECT_PREFERENCE: 'Selecione uma opção',
    SELECT_OPTION: 'Selecione a opção deseja',
    SELECT_TICKET: 'Selecione seu bilhete',
  },
  COMPARE_ALL_DETAILS: 'Compare os detalhes',
  COVID19_ALERT: {
    KEY_TEXT: 'Atualização sobre a COVID-19',
    LINK: 'https://medium.com/headout/surto-coronav%C3%ADrus-pol%C3%ADtica-de-cancelamento-18a2fb65b25',
    TEXT: 'Você é nossa prioridade. Consulte nossa página de ajuda para encontrar as últimas atualizações sobre nossa política de cancelamento flexível.',
  },
  CURRENCY: 'Moeda',
  CUSTOMER_REVIEW_HEADING: 'Avaliações',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audioguia',
    DURATION: 'Duração: {0}',
    EXTENDED_VALIDITY: 'Validade prolongada',
    FLEXIBLE_DURATION: 'Duração flexível',
    FREE_CANCELLATION: 'Cancelamento gratuito',
    GUIDED_TOUR: 'Tour guiado',
    HOTEL_PICKUP: 'Traslado do hotel',
    INSTANT_CONFIRMATION: 'Confirmação imediata',
    MEALS_INCLUDED: 'Refeição incluída',
    MOBILE_TICKET: 'Ingressos eletrônicos',
    SKIP_THE_LINE: 'Sem filas',
    TRANSFERS: 'Inclui translado',
    MULTILINGUAL_AUDIO_GUIDE: 'Audioguia multilíngue',
    LIVE_GUIDE: 'Guia presencial',
    FLEXIBLE_CANCELLATION: 'Cancelamento flexível',
  },
  DURATION: 'Duração',
  EARLIEST_AVAILABILITY: 'Próxima disponível: ',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Insira seu e-mail aqui',
    SIGN_UP: 'Inscreva-se',
    THANK_YOU: 'Obrigada!',
    SUBSCRIBED_MSG: 'Você está inscrito agora',
    ERROR_MSG: 'Por favor, insira um e-mail válido',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Ingressos para teatro na Broadway',
    },
    LTT: {
      MB_NAME: 'Ingressos para teatro em Londres',
    },
  },
  EXCLUSIONS: 'Não inclui',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '+{0} milhões',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100% seguro',
    HEADING_SUPPORT: 'Atendimento ao cliente 24h',
    SUB_HEADING_CUSTOMER:
      'de clientes satisfeitos com mais de 10.000 experiências',
    SUB_HEADING_RATING: '+5.000 avaliações com 90% de pontuação excelente',
    SUB_HEADING_SAFE: 'Todas as experiências ao ar livre são 100% seguras',
    SUB_HEADING_SUPPORT:
      'Tem uma pergunta? Fale com nossos especialistas locais pelo chat a qualquer hora, de qualquer lugar.',
  },
  FLEXIBLE: 'Flexível',
  FOOTER: {
    CALL_US: 'Telefone',
    CHAT_WITH_US: 'Fale conosco',
    COMPANY_DETAILS: 'Sobre a empresa',
    ABOUT_US: 'Sobre nós',
    INFORMATION: 'Informações',
    GMAPS_DISCLAIMER:
      'Todas as imagens de mapas exibidas nesta página são provenientes do Google, de acordo com o uso justo. Todos os direitos sobre tais imagens pertencem à plataforma específica e seu uso destina-se exclusivamente a fins informativos ou orientativos.',
    DISCLAIMER:
      'O site não é a página oficial da atração <attraction>. O site é mantido pela Headout, que trabalha em colaboração com atrações e operadores locais para oferecer experiências incríveis com apenas um clique!',
    EMAIL_US: 'E-mail',
    GET_HELP: 'Ajuda',
    LEGAL: 'Termos Legais',
    PRIVACY_POLICY: 'Política de privacidade',
    QUICK_LINKS: 'Links diretos',
    TERMS_AND_CONDITIONS: 'Termos e condições',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Feito com ',
    ALL_OVER_THE: ' para todo o ',
    TERMS_OF_USAGE: 'Termos de uso',
    GET_HELP_24_7: 'ASSISTÊNCIA 24 H',
    HELP_CENTER: 'Central de atendimento',
    COMPANY: 'Empresa',
    WE_ACCEPT: 'Métodos de pagamento',
    DOWNLOAD_HEADOUT: 'Baixe o aplicativo da Headout',
    SCAN_CODES: 'Faça a leitura do código',
    STAR_VERIFIED: 'Clique para verificar afiliação à S.T.A.R.',
    OFFICIAL_TICKET_RETAILER: 'Distribuidor Oficial de Ingressos',
  },
  FREE_CANCELLATION: 'Cancelamento gratuito',
  FREE_CANCELLATION_SUBTEXT:
    'Se os planos mudarem, cancele gratuitamente até 72h antes do evento. ',
  FROM: 'a partir de',
  GET_CASHBACK: 'Garanta {0}% de cashback',
  GROUP_TICKETS: 'Ingressos para grupos',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '{0} Milhões de clientes felizes',
    SUB_TEXT:
      'A satisfação do cliente é nossa maior prioridade. Faça parte do nosso grupo.',
  },
  HELP_CENTER: {
    MAIN_TEXT: 'Suporte 24h/7',
    SUB_TEXT:
      'Tem alguma dúvida? Estamos disponíveis por telefone, chat e e-mail.',
  },
  INCLUSIONS: 'Inclusões',
  LANGUAGE: 'Idioma',
  LISTICLES: {
    KNOW_MORE: 'Saiba mais',
    SEATING_CHART: 'Mapa de assentos',
    WHY_BOOK_FROM_US: 'Por que reservar com a gente?',
  },
  MORE_DETAILS: 'Mais detalhes',
  MORE_CURRENCIES: 'Outras moedas',
  NEW: 'NOVO',
  NEW_ARRIVAL: 'Novidade',
  NEXT_AVAILABLE: 'Próxima disponível: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'A Headout já conquistou a confiança de mais de {0} milhões de clientes e oferece uma seleção das melhores experiências. Este não é o site oficial do local da experiência.',
  NO_RESULT_FOUND: 'Não foi encontrado nenhum resultado',
  OFF: 'Off',
  OPEN_DATED_DESCRIPTOR:
    'Reserve com flexibilidade - não é preciso selecionar uma data',
  OPENING_DATE: 'Data de estreia',
  OPENING_ON: 'Estreia em',
  OPENS: 'Abre',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout é um parceiro de confiança da atração, autorizado a oferecer uma seleção das melhores experiências. Este não é o site da atração.',
  POPULARITY: 'Popularidade',
  POPULAR_CURRENCIES: 'Moedas frequentes',
  PRICE: 'Preço',
  PRICES_STARTING: 'Preços a partir de',
  PROMO_CODES: {
    APPLIED: 'APLICADO',
    APPLY_CODE: 'APLICAR CÓDIGO',
    DESCRIPTION: {
      ABSOLUTE: 'Desconto de {0}',
      CAPPED: 'Desconto de {0}%, até {1}',
      PERCENTAGE: 'Desconto de {0}%',
    },
    REMOVE: 'REMOVER',
    TOOL_TIP_INFO: 'O desconto será aplicado no momento da compra',
  },
  RATINGS: '{0} Avaliações',
  READ_MORE: 'Saiba mais',
  READ_MORE_TEXT: 'Ver mais',
  READ_LESS: 'Ver menos',
  VIEW_DETAILS: 'Ver detalhes',
  REOPENING: 'Reestreia',
  REOPENING_DATE: 'Data de reestreia',
  REOPENING_ON: 'Reabre em',
  REOPENS: 'Reabre',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      TEXT: 'As normas 2G se aplicam: o acesso a acomodações, instituições culturais e restaurantes/bares, entre outros, só é possível com prova de vacinação total ou de infecção nos últimos 6 meses. Um teste Covid-19 negativo não é mais suficiente.',
    },
    AU_DESCRIPTION: {
      TEXT: 'Visitantes com idade igual ou superior a 16 anos devem apresentar prova de vacinação da COVID-19 ou isenção médica.',
    },
    BANNER_CTA: 'Saiba mais',
    BERLIN_DESCRIPTION: {
      TEXT: 'As normas 2G se aplicam: somente visitantes totalmente vacinados e recuperados com prova do mesmo terão acesso. Visitantes menores de 18 anos ou aqueles que não podem ser vacinados por razões médicas devem apresentar um resultado negativo de teste COVID na entrada. Aqueles que não podem ser vacinados por razões médicas também devem comprovar sua impossibilidade de serem vacinados por meio de um certificado médico na entrada.',
    },
    CTA_TEXT: 'Detalhes das medidas',
    DESCRIPTION_CTA: 'Saiba mais.',
    EU_DESCRIPTION: {
      TEXT: 'A partir de 21 de julho de 2021, todos os visitantes a partir de 12 anos de idade devem apresentar um Certificado de COVID da UE.',
    },
    EU_HEADING: 'Certificado Covid da UE necessário',
    EU_PREFIX: 'Atenção: ',
    EXPERIENCE_DESCRIPTION:
      'Esta experiência foi verificada para seguir as melhores medidas de segurança de acordo com os regulamentos locais e a OMS',
    FLAG_TEXT: 'Segurança verificada',
    GENERAL_DESCRIPTION:
      'Qualquer experiência com este selo foi verificada e segue as melhores medidas de segurança de acordo com as diretrizes de saúde dos governos locais.',
    HEADING: 'Melhores medidas de segurança',
    IT_DESCRIPTION: {
      TEXT: 'A partir de 6 de agosto de 2021, todos os visitantes com 11 anos ou mais devem apresentar um Passe Verde ou um Certificado de COVID da UE.',
    },
    IT_PREFIX: 'Atenção: ',
    MOBILE_HEADING: 'Experiências seguras',
    MODAL: {
      BADGE_DESCRIPTION:
        'O selo em uma experiência confirma que as medidas de segurança foram verificadas por nós.',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Todos os equipamentos, veículos e superfícies são higienizados após cada utilização. Basta relaxar e desfrutar.',
          HEADING: 'Todos os equipamentos e superfícies são higienizados',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Todos os equipamentos disponíveis durante a sua experiência são completamente higienizados após cada utilização. Sempre.',
          HEADING: 'Todos os equipamentos e superfícies são higienizados',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Todos os veículos disponíveis durante a sua experiência são completamente higienizados após cada utilização. Sempre.',
          HEADING: 'Todos os veículos são higienizados',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Como uma experiência segura, você terá acesso a estações para lavar as mãos e de saneamento durante o tempo de visita. Oferecemos todo o necessário. ',
          HEADING: 'Instalações disponíveis para lavagem das mãos e saneamento',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'As máscaras são obrigatórias para todos os visitantes e membros do pessoal desta experiência, oferecendo diversão com segurança máxima.',
          HEADING: 'Todos devem usar máscara para sua segurança',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Nossos parceiros, que foram verificados como Experiência Segura, seguem os regulamentos locais em vigor sobre as máscaras faciais. Se obrigatório, todos os visitantes e pessoal usarão máscaras. Todas as medidas possíveis são tomadas para garantir o seu conforto e segurança.',
          HEADING: 'Todos devem usar máscara para sua segurança',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'As máscaras são obrigatórias para todos os visitantes desta experiência, oferecendo diversão com segurança máxima.',
          HEADING: 'Todos devem usar máscara para sua segurança',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Todos os membros do pessoal desta experiência usam máscaras faciais para garantir que você possa se divertir sem se preocupar.',
          HEADING: 'Todos devem usar máscara para sua segurança',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Regras de distanciamento social são seguidas durante a experiência. Existem restrições de capacidade do local para garantir o distanciamento.',
          HEADING: 'Regras de distanciamento social são seguidas',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Regras de distanciamento social são seguidas durante a experiência. Existem restrições de capacidade no local para garantir o distanciamento e grandes grupos de visitantes não são permitidos.',
          HEADING: 'Regras de distanciamento social são seguidas',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Regras de distanciamento social estão sendo seguidas a todo momento durante a experiência.',
          HEADING: 'Regras de distanciamento social são seguidas',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Regras de distanciamento social estão sendo seguidas a todo momento durante a experiência. Para cumprí-las, pode haver restrições de capacidade e limites no tamanho dos grupos. Fique tranquilo(a).',
          HEADING: 'Regras de distanciamento social são seguidas',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Regras de distanciamento social estão sendo seguidas a todo momento durante a experiência. Portanto, grandes grupos de visitantes não são permitidos.',
          HEADING: 'Regras de distanciamento social são seguidas',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Os visitantes terão sua temperatura verificada no início da experiência para garantir a segurança de todos. Também é verificada várias vezes ao dia a temperatura dos membros do pessoal.',
          HEADING: 'Verificações de temperatura no local',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Os visitantes terão sua temperatura verificada no início da experiência para garantir a segurança de todos. ',
          HEADING: 'Verificações de temperatura no local',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'A temperatura dos membros do pessoal é verificada várias vezes ao dia. A entrada de pessoas com temperatura além do limite não é permitida e é solicitado que fiquem em casa para se recuperarem.',
          HEADING: 'Verificações de temperatura no local',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'O pessoal disponível durante a experiência é treinado de acordo com as diretrizes da OMS e equipado para lidar com qualquer emergência.',
          HEADING: 'A equipe é treinada de acordo com diretrizes da OMS',
        },
      },
      HEADING: 'Experiências seguras',
      SUB_HEADING:
        'Estamos trabalhando com nossos parceiros em todo o mundo para implementar as melhores medidas de segurança de acordo com as diretrizes da OMS. Todas as medidas tomadas foram verificadas e aqui apresentadas. Está na hora de explorar novamente o mundo à nossa volta!',
    },
    NL_DESCRIPTION: {
      TEXT: 'Visitantes com 13 anos ou mais devem ter (cópia digital ou impressa de) um Certificado COVID que confirme a vacinação, resultado negativo do teste, ou documento que comprove a recuperação da COVID-19. O uso de uma máscara facial é obrigatório.',
    },
    SG_DESCRIPTION: {
      TEXT: 'A partir de 13 de outubro de 2021, somente visitantes totalmente vacinados poderão entrar em grupos de 2. Você terá que apresentar prova do status de vacinação, um resultado recente negativo de teste COVID-19 e/ou qualquer documentação de recuperação antes da entrada.',
    },
    SHORT_HEADING: 'As melhores medidas de segurança em vigor',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Sua segurança é nossa prioridade',
    TEXT: 'Tomamos medidas significativas para melhorar a limpeza utilizando desinfetantes com uma limpeza frequente das superfícies. O volume de pessoas também está sendo controlado para evitar aglomerações.',
  },
  SAVE: 'Economize  {0}%',
  SAVE_PERCENT: 'Economize {0}%',
  SAVE_UPTO: 'Economize até',
  SAVE_UPTO_PERCENT: 'Economize até {0}%',
  SEARCH: 'Pesquisar',
  SEE_ALL: 'Ver todos',
  SEE_MORE_SHOWS: 'Ver mais {0} espetáculos',
  SELECT_CITY: 'Selecionar cidade',
  SELECT_SECTION: 'Escolher setor',
  SEE_ALL_PHOTOS: 'Ver todas as fotos',
  SHOW_CLOSED: 'Show encerrado',
  SHOW_LESS_TEXT: 'Ver menos',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Sobre o espetáculo',
    ABOUT_THEATRE: 'Sobre o teatro',
    ADDITIONAL_INFORMATION: 'Informações adicionais',
    AGE_LIMIT: 'Classificação indicativa',
    AGE_SUITABILITY: 'Faixa etária',
    ANSWER: ['R-'],
    BLOG_SHOW_PAGE: 'Blog Página oficial do espetáculo',
    BLOG_SUMMARY: 'Blog Resumo',
    BLOG_THEATRE_PAGE: 'Blog Página do Teatro',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Mapa de assentos do Teatro',
    CANCELLATION_AND_REFUNDS: 'Cancelamento e reembolso',
    CANCELLATION_POLICY: 'Política de cancelamento',
    CAST_AND_CREW: 'Elenco e equipe',
    CLOSING_DATE: 'Data de encerramento',
    CLOSING_DATE_SPECIAL_OFFER: 'Data de encerramento da oferta especial',
    DURATION: 'Duração',
    FACILITIES_AND_ACCESSIBILITY: 'Serviços e acessibilidade',
    FREQUENTLY_ASKED_QUESTIONS: 'Perguntas frequentes',
    GETTING_THERE: 'Como chegar',
    GETTING_THERE_MAP_LINK: 'Como chegar',
    GOOGLE_MAP: 'GoogleMaps',
    HIGHLIGHTS: 'Destaques',
    LISTICLE_SHOW_SUMMARY: 'Listicle Resumo do espetáculo',
    LISTICLE_SHOW_WHY_WATCH: 'Listicle Por que assistir',
    OPENING_DATE: 'Data de estreia',
    QUESTION: ['P-'],
    SAFETY_BANNER: 'Bandeira de segurança',
    SHOW_DETAILS: 'Detalhes do espetáculo',
    SHOW_TIMINGS: 'Horários do espetáculo',
    SHOW_TYPE: 'Tipo de espetáculo',
    SPECIAL_OFFER: 'Oferta especial',
    THE_STORY: 'A história',
    THEATRE_ADDRESS: 'Endereço do teatro',
    THEATRE_CAPACITY: 'Capacidade do teatro',
    THEATRE_NAME: 'Nome do teatro',
    TICKETS: 'Ingressos',
    TICKETS_REDEMPTION: 'Retirada de ingressos',
    TOP_SONGS: 'Principais canções',
    YOUR_TICKETS: 'Seus ingressos',
    ABOUT_CONCERT: 'Sobre o concerto',
    PROGRAM: 'Programa',
  },
  SORT_BY: 'Ordenar por',
  THEATRE: 'Teatro',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Teatros próximos',
    NOW_PLAYING: 'Em cartaz agora',
    UPCOMING_SHOWS: 'Próximos espetáculos',
    PAST_SHOWS: 'Espetáculos passados',
    FIND_BEST_SEATS: 'Encontre os melhores lugares',
  },
  SPECIAL_OFFER: 'Oferta especial',
  TICKET_CAN_BE_CANCELED:
    'Você pode cancelar com até {hours} horas de antecedência da experiência para um reembolso completo.',
  TICKET_CANNOT_BE_CANCELED:
    'Este ingresso não pode ser cancelado, mas pode ser reagendado mediante solicitação',
  TICKETS: 'Ingressos',
  TIMINGS: 'Horários',
  SPECIAL_PRODUCT_HEADING: 'Experiências amadas',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Guias especializados',
    ENGAGING_STORIES: 'Histórias envolventes',
    TOP_RATED: 'Bem avaliadas',
  },
  GUIDED_TOUR_REVIEWS: [
    'A nossa guia Angela era óptima e conhecia muito bem o local',
    'O guia teve todo o gosto em responder a perguntas sobre a visita',
    'A organização e o nosso guia tornaram a experiência muito agradável',
    'A excursão foi bem organizada e com a duração certa',
    'Bom guia e boa organização! Recomendo!!!',
    'A excursão decorreu a um bom ritmo e não nos sentimos apressados',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  LANGUAGES: {
    ENGLISH: 'Inglês',
    SPANISH: 'Espanhol',
    FRENCH: 'Francês',
    ITALIAN: 'Italiano',
    GERMAN: 'Alemão',
    PORTUGUESE: 'Português',
    NEDERLANDS: 'Holandês',
    POLISH: 'Polonês',
    RUSSIAN: 'Russo',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Tour disponível em {0}',
  GUIDES_BANNER: 'Explore como um local com guias favoritos pelos visitantes.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Fazer uma visita guiada é a melhor maneira de aproveitar. Nossos guias são como amigos locais compartilhando histórias, informações privilegiadas e recomendações de viagem.',
    'Não apenas visite - viva!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Opinião dos visitantes',
  TODAY: 'hoje',
  TOMORROW: 'amanhã',
  TOUR_LIST_HEADING: 'Selecione a experiência desejada',
  TOUR_LIST_SUB_HEADING:
    'Escolha entre diferentes opções de ingressos, excursões e combos de operadores verificados:',
  UGC: {
    FOLLOW: 'Seguir',
    FOLLOW_IG: 'Seguir no Instagram',
    HEADING: 'A sua próxima experiência pode ser assim',
    SUB_HEADING: 'Selecionada com 💜 pela Headout',
  },
  UNAVAILABLE: 'Indisponível',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Estes ingressos são válidos por uma duração estendida. Os detalhes exatos serão informados no ingresso.',
    UNTIL_DATE: 'Estes ingressos são válidos até o dia {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Estes ingressos são válidos por {0} dias a partir da data da compra.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Estes ingressos são válidos por {0} meses a partir da data da compra.',
  },
  TABLE_OF_CONTENTS: 'Conteúdo',
  VIEW_LESS: 'Mostrar menos',
  VIEW_MORE: 'Ver mais',
  WHY_TAKE_THIS_DAY_TRIP: 'Por que vale a pena fazer essa excursão de um dia?',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Menu principal',
    EXPLORE: 'Explore',
    VISIT: 'Visite',
    THINGS_TO_DO: 'Coisas para fazer',
    CITY_ATTRACTIONS: 'Atrações de {0}',
    TOP_THINGS_TO_DO: 'Principais coisas para fazer',
    CITY_TOURS: 'Tours em {0}',
    CITY_GUIDE: 'Guia da cidade',
    ATTRACTIONS: 'Atrações',
    CRUISES: 'Cruzeiros',
    THEMES: 'Temas',
    ABOUT: 'Sobre',
    TOURS: 'Passeios',
    SKIP_THE_LINE: 'Visitas sem fila',
    GUIDED_TOURS: 'Visitas guiadas',
    NIGHT_TOURS: 'Visitas à noite',
    FOOD_TOURS: 'Tours gastronômicos',
    HISTORY: 'História',
    ARCHITECTURE: 'Arquitetura',
    DESIGN: 'Design',
    INSIDE: 'Interior',
    COLLECTIONS: 'Coleções',
    PAINTINGS: 'Pinturas',
    ANIMALS_EXHIBITS: 'Animais e exposições',
    HABITATS: 'Habitats',
    CONSERVATION: 'Conservação',
    PROGRAMMES: 'Programas',
    A2_SIGHTSEEING_CRUISES: 'Cruzeiros Turísticos',
    A2_DINNER_CRUISES: 'Cruzeiros com jantar',
    A2_EVENING_CRUISES: 'Cruzeiros Noturnos',
    A2_LUNCH_CRUISES: 'Cruzeiros com almoço',
    A2_YACHT_TOURS: 'Yacht Tours',
    PLAN_YOUR_VISIT: 'Planeje sua visita',
    TIMINGS: 'Horários',
    DIRECTIONS: 'Direções',
    PARKING: 'Estacionamento',
    ROUTES: 'Rotas',
    REQUIREMENTS: 'Requisitos',
    LOCATION: 'Local',
    RULES: 'Regras',
    FAQs: 'Perguntas frequentes',
    ENTRANCES: 'Entradas',
    RESTAURANTS: 'Restaurantes',
    FACTS: 'Curiosidades',
    TIPS: 'Dicas',
    MAP: 'Mapa',
    RIDES: 'Atrações',
    SHOWS: 'Shows',
    DINING: 'Restaurantes',
    SHOPPING: 'Compras',
    EVENTS: 'Eventos',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Natal',
    NEW_YEARS_EVE: 'Virada do ano',
    TRAVEL_GUIDE: 'Guia de viagem',
    TRIP_PLANNER: 'Planejador de viagem',
    ITINERARY: 'Itinerário',
    TRAVEL_TIPS: 'Dicas de viagem',
    WEATHER: 'Clima',
    BEST_TIME_TO_VISIT: 'Quando visitar',
    JANUARY: 'Janeiro',
    FEBRUARY: 'Fevereiro',
    MARCH: 'Março',
    APRIL: 'Abril',
    MAY: 'Maio',
    JUNE: 'Junho',
    JULY: 'Julho',
    AUGUST: 'Agosto',
    SEPTEMBER: 'Setembro',
    OCTOBER: 'Outubro',
    NOVEMBER: 'Novembro',
    DECEMBER: 'Dezembro',
    WHERE_TO_EAT: 'Onde comer',
    WHERE_TO_STAY: 'Onde ficar',
    NEIGHBOURHOODS: 'Bairros',
    FAMILY_TRAVEL: 'Viagem em família',
    TRANSPORTATION: 'Transporte',
    FESTIVALS_EVENTS: 'Festivais e eventos',
  },
  WHY_WATCH: 'Por que assistir {0}?',
  FIND_ON_MAP: 'Ver no mapa',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Ingressos da bilheteria',
        DESCRIPTION: 'Confirmação imediata no seu celular',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: `Escolha seus assentos`,
        DESCRIPTION: 'Sempre com a visão que quiser',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Ofertas e descontos exclusivos',
        DESCRIPTION: `Economize nos melhores espetáculos`,
      },
      BOOK_AND_RELAX: {
        NAME: 'Reserve com tranquilidade',
        DESCRIPTION: '{0} milhões de clientes satisfeitos',
      },
    },
    YOUR_PICK: 'Sua escolha',
    BROWSE_BY_CATEGORIES: 'Navegue por categoria',
    TOP_WEST_END_SHOWS: 'Os melhores espetáculos West End',
    TOP_SHOWS: 'Melhores espetáculos',
    TOP_THEATRE_SHOWS: '{0}: os melhores espetáculos',
    LAST_MINUTE_TICKETS: 'Ingressos de última hora',
    LOVED_BY_MILLIONS: 'Favoritos de milhares',
    TODAY: 'Hoje',
    TOMORROW: 'Amanhã',
    SEE_ALL: 'Ver todos',
    SEE_MORE_SHOWS: 'Ver mais {0} espetáculos',
    GRAB_YOUR_TICKETS: 'Garanta seus ingressos agora',
  },
  TAG_NAME: {
    BALLET: 'Balés',
    CABARET: 'Cabaré',
    CHRISTMAS: 'Natal',
    CIRCUS: 'Circo',
    CLASSIC: 'Clássico',
    COMEDY: 'Comédia',
    COMING_SOON: 'Em breve',
    CRITICS_CHOICE: 'Aclamado pela crítica',
    DANCE: 'Dança',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasia',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Teatro imersivo',
    JUKEBOX: 'Jukebox',
    KIDS: 'Infantil',
    MAGIC: 'Mágica',
    MUSICALS: 'Musicais',
    NEW_ARRIVAL: 'Novidade',
    OFF_WEST_END: 'Fora do West End',
    OLIVIER_WINNER: 'Vencedor do Olivier',
    OPERA: 'Ópera',
    PANTOMIMES: 'Pantomima',
    PLAYS: 'Peças de teatro',
    ROMANCE: 'História de amor',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Estrelas no palco',
    THEATRICAL_CONCERT: 'Concerto teatral',
    TRUE_STORY: 'Baseado em uma história real',
    TONY_WINNER: 'Vencedor do Prêmio Tony',
    OFF_BROADWAY: 'Fora da Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Opa! Parece que temos um problema',
    MESSAGE: `Que pena! Todas as experiências estão esgotadas ou indisponíveis nesta data. Mas há muitas outras datas para escolher, confira!`,
    CTA: 'Ver datas disponíveis',
  },
  ALL_DATES: 'Todas as datas',
  BREADCRUMBS: {
    HOME: 'Página inicial',
    TRAVEL_GUIDE: 'Guia de viagem',
    THINGS_TO_DO: 'O que fazer em {0}',
    SHOW_NAME_TICKETS: '{0} - Ingressos',
    LTT_HOME: 'Ingressos para o London Theatre',
    LTT_VENUE_PAGE_HOME: 'Teatros em Londres',
    BROADWAY_HOME: 'Ingressos para shows da Broadway',
    BROADWAY_VENUE_PAGE_HOME: 'Teatros da Broadway',
    VIENNA_CONCERT_HOME: 'Ingressos para concertos em Viena',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Salas de concerto em Viena',
    ATTRACTIONS: 'Atrações',
    A2_SIGHTSEEING_CRUISES: 'Cruzeiros Turísticos',
    A2_DINNER_CRUISES: 'Cruzeiros com jantar',
    A2_EVENING_CRUISES: 'Cruzeiros Noturnos',
    A2_LUNCH_CRUISES: 'Cruzeiros com almoço',
    A2_YACHT_TOURS: 'Yacht Tours',
    LONDON_THEATRE_NEWS: 'Novidades do London Theatre',
    BROADWAY_SHOW_NEWS: 'Novidades da Broadway',
    NEWS_PAGE: 'Novidades',
    REVIEWS_PAGE_BANNER_HEADING: 'Avaliações de {0}',
  },
  AMENITIES: {
    Restaurant: 'Restaurante',
    Cafe: 'Cafeteria',
    'Dedicated Parking': 'Estacionamento exclusivo',
    Elevators: 'Elevador',
    Lift: 'Elevador',
    'Wheelchair Accessible': 'Acessível para cadeira de rodas',
    Cloakroom: 'Chapelaria',
    'Air Conditioning': 'Ar condicionado',
    WiFi: 'WiFi',
    Bar: 'Bar',
    'Water Fountain': 'Bebedouro',
    Washrooms: 'Banheiro',
    Toilets: 'Banheiro',
    Binoculars: 'Binóculos',
    'Adapted Toilets': 'Banheiros adaptados',
    'Accessible Toilets': 'Banheiros acessíveis',
    'Assistive Listening System': 'Sistema de audição assistida',
    'Hearing Assistance': 'Assistência auditiva',
    'Booster Cushions': 'Almofadas de reforço',
    Shop: 'Loja',
    'Souvenir Shop': 'Loja de lembranças',
    'Guide Dogs': 'Cães-guia',
    'Baby Changing Facilities': 'Fraldário para bebês',
    'Security Check': 'Verificação de segurança',
    Ramp: 'Rampa',
    'Level Access': 'Acesso ao local',
  },
  CALENDAR: {
    FOOTNOTE: '* Preços exibidos em {0}',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Ver a avaliação original em {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Esta avaliação foi traduzida. Ver a avaliação original.',
    TRANSLATE: 'Traduzir a avaliação para {0}',
    LANGUAGES: {
      EN: 'inglês',
      ES: 'espanhol',
      FR: 'francês',
      IT: 'italiano',
      DE: 'alemão',
      PT: 'português',
      NL: 'holandês',
    },
  },
  SHOW_PAGE_V2: {
    TWO_PART_SHOW: 'Espetáculo em duas partes',
    INTERVAL: 'Intervalo',
    SELLING_OUT_FAST: 'Esgota rápido',
    MUST_DO_EXP: 'Imperdível',
    READ_MORE_REVIEWS: 'Ler mais avaliações',
    SHOW_MORE_REVIEWS: 'Mostrar mais avaliações',
    ALL_PHOTOS: 'Todas as fotos',
    MORE_DATES: 'Mais datas',
    SELECT_TIME_SLOT: 'Selecione um horário',
    SELECT_TIME_SLOT_ERROR: 'Selecione um horário para continuar',
    PRICE_STARTING_FROM: 'Preço dos assentos a partir de',
    SELECT_SEATS: 'Selecionar assentos',
    READ_MORE: 'Ler mais',
    RATINGS_AND_REVIEWS: 'Avaliações e comentários',
    READ_DETAILED_REVIEWS: 'Ler comentários completos',
    UNTIL_DATE: 'Até {0}',
    AVAILABLE_TIME: 'Horário disponível',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Esta experiência somente está disponível no seguinte horário',
    CONTENT_TABS: {
      ABOUT: 'Sobre',
      VENUE: 'Local',
      TICKETS: 'Ingressos',
      Reviews: 'Comentários',
    },
    SELECT_SHOW_TIMMING: 'Selecione a hora do espetáculo',
    ONLY_ONE_SLOT: 'Apenas 1 horário disponível na data selecionada',
    SIMILAR_SHOWS: 'Você também pode gostar',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Enredo',
      AGE_SUITABILITY_AND_GUIDELINES:
        'Classificação indicativa e outras orientações',
      WHAT_CRITICS_THINK: 'Opinião dos críticos',
      CAST_AND_CREATIVES: 'Elenco e equipe',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Perguntas frequentes',
    },
    TICKETS_UNAVAILABLE: 'Ingressos indisponíveis',
    TICKETS_UNAVAILABLE_SUBTEXT:
      'Por sorte, temos muitas outras opções para você escolher aqui.',
    MUST_SEE_SHOWS: 'Mais espetáculos imperdíveis',
    SEE_ALL_SHOWS: 'Ver todos espetáculos',
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Guias especializados e multilíngues',
    STL: 'Acesso sem fila',
    PERSONALIZED: 'Experiência personalizada',
    LOCAL_FOOD: 'Experiência gastronômica e cultural',
    MULTILINGUAL_GUIDES: 'Guias multilíngues',
    CULINARY_EXPERTS: 'Conheça especialistas culinários',
    SIGHTSEEING: 'Passeio turístico e entretenimento a bordo',
    SIGHTSEEING_MEAL: 'Passeio turístico e refeições a bordo',
    MULTILINGUAL_GT: 'Visitas guiadas multilíngues',
    AUDIOGUIDE_COMMENTARY: 'Audioguia e comentários disponíveis',
    ALL_TOP_ATTRACTIONS_COVERED: 'All top attractions covered',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Regular schedule. Unlimited rides',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Last minute availability. Instant confirmation',
    MULTI_ROUTES: 'Diversas opções de rotas',
    HASSLE_FREE: 'Reserva sem complicações',
    FREQUENT_DEPARTURES: 'Partidas frequentes',
    ONBOARD_AMENITIES: 'Melhores comodidades a bordo',
    FLEXI_TRAVEL: 'Viagens flexíveis em várias rotas',
    FLEXI_EXCHANGE_CANCEL: 'Trocas e cancelamentos flexíveis',
    EXTRA_DISCOUNT: 'Descontos extras para jovens, idosos e famílias',
    PREPAID: 'Conveniências pré-pagas',
    EASY_ACTIVATION: 'Fácil ativação',
    INSTANT_CONNECTIVITY: 'Conexão instantânea com cobertura global',
    ROUND_TRIP: 'Transfer de ida e volta',
    CULTURAL_EXPERIENCE: 'Experiências culturais autênticas',
    GUARANTEED_SEAT: 'Guaranteed Seat',
    ONBOARD_WIFI: 'Onboard Wi-Fi & Charging Ports',
    LUGGAGE_ASSISTANCE: 'Assistência com bagagens',
    TOP_ATTRACTIONS: 'Melhores atrações inclusas',
    FREQ_DEP_MULTI_ROUTE: 'Partidas frequentes para diversas rotas',
    CHARGING: 'Estação de carregamento',
    WIFI: 'Acesso ao wi-fi',
    FnB: 'Refeições e bebidas disponíveis',
    LUXURY: 'Experiência de luxo',
    FOOD_DRINK: 'Comidas e bebidas',
    PANAROMIC: 'Vistas panorâmicas das principais atrações',
    PANAROMIC_2: 'Vistas panorâmicas',
    PANAROMIC_3: 'Vistas panorâmicas a céu aberto',
    BEVERAGES: 'Bebidas a bordo',
    GOURMET: 'Refeição gourmet',
    GOURMET_2: 'Jantar gourmet e bebidas',
    NIGHTTIME: 'Vistas noturnas incríveis',
    ROMANTIC: 'Atmosfera romântica',
    TRANSFERS: 'Inclui traslado',
    CERTIFIED_OP: 'Empresas certificadas',
    BIRD_EYE: 'Vistas panorâmicas',
    MULTI_JUMP: 'Múltiplas horas de salto',
    EXTREME_ADV: 'Aventura extrema',
    PHOTO_OP: 'Oportunidade de tirar fotos espetaculares',
    TOP_ATTRACTIONS_COVERED: 'Principais atrações inclusas',
    LOCAL_CULTURE: 'Conheça a cultura local',
    EXCLUSIVE_DISC: 'Descontos exclusivos',
    EFFICIENT_PUBLIC_TRANSIT: 'Transporte público eficiente',
    FREQUENT_SERVICE: 'Serviço frequente',
    PREBOOKING: 'Pré-reserva facilitada',
    LOCAL_CULTURE_IMM: 'Imersão na cultura local',
    DISCOVER_HIDDEN: 'Descubra lugares secretos',
    CITY_SIGHTSEEING: 'Passeios turísticos',
    OFFBEAT_ADV: 'Experiência inigualável',
    DRINK_DEALS: 'Ofertas em drinks',
    OFFBEAT_EXP: 'Experiência inigualável',
    MULTIPLE_VARIETIES: 'Variedades locais inclusas',
    HIDDEN_GEMS: 'Locais escondidos e atrações incomuns',
    EXPLORE_LOCAL: 'Conheça bairros locais',
    CUSTOMIZED_TREATMENTS: 'Tratamentos personalizados',
    TRAINED_THERAPISTS: 'Terapeutas treinadoss',
    HOLISTIC_WELLNESS: 'Bem-estar holístico',
    FLEXIBLE_DURATION: 'Duração flexível',
    MULTI_BOAT: 'Ampla variedade de barcos',
    SCENIC_ROUTES: 'Rotas panorâmicas',
    HANDS_ON: 'Aprendizado prático',
    CULTURAL_CULINARY: 'Informações culturais e gastronômicas',
    EXPERT_HOSTS: 'Guias especializados',
    ADVENTURE_EXPERIENCE: 'Experiência de aventura',
    EQUIPMENT: 'Equipamento incluso',
    SCENIC_FLYOVERS: 'Sobrevoos cênicos',
    LIVE_COMMENTARY: 'Comentários ao vivo',
    BEST_AERIAL_VIEWS: 'As melhores vistas aéreas',
    SAFE_CERT_OP: 'Atividades seguras e certificadas',
    HANDPICKED: 'Tours e opções escolhidos a dedo',
    EFFORTLESS: 'Fácil planejamento',
    EXPERT_GUIDES: 'Guias profissionais. Perspectivas únicas',
    ALL_ATTR_ONE_CARD: 'Todas as atrações em apenas um cartão',
    MULTI_CARD: 'Diversas opções',
    COST_EFF: 'Econômico e prático',
    EASY_BEST: 'Fácil de reservar. Os melhores preços',
    INSTANT_MOBILE: 'Confirmação imediata. Ingressos digitais',
    MULTI_TRANSPORT: 'Diversas opções de transporte',
    BEST_PRICES: 'Os melhores preços',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Tudo',
    POPULAR_SUBCATEGORY: '{0} mais populares',
    TOP_CATEGORY: '{0}: as melhores experiências',
    ATTRACTIONS: 'Atrações',
    ALL_SUBCATEGORY: '{0}: todas as experiências',
    BROWSE_BY_CATEGORIES: 'Buscar por categorias',
    TICKETS_FROM: 'Ingressos a partir de',
    PRICE_LOW_HIGH: 'Preço (do menor ao maior)',
    PRICE_HIGH_LOW: 'Preço (do maior ao menor)',
    FILTERS: 'Filtros',
    RESET: 'Limpar',
    APPLY: 'Aplicar',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'A Headout usa cookies para aprimorar sua navegação no site, com um byte por vez.',
    MOBILE: 'O trabalho dos cookies.',
    LEARN_MORE: 'Saiba mais.',
  },
  SHOW_UNAVAILABLE: 'Espetáculos indisponíveis',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Novidades em destaque',
    ALL_NEWS: 'Todas as novidades',
    MORE_READS: 'Mais leituras',
    LOAD_MORE: 'Carregar mais',
    TRAILERS: 'Todos os trailers',
    GET_YOUR_TICKETS: 'Garanta seus ingressos',
    POPULAR_SHOWS: 'Espetáculos populares',
    FEATURED: 'Destaques',
    RECENT_NEWS: 'Notícias',
    SHOW_MORE_ARTICLES: 'Ver mais artigos',
    COLLAPSE_ALL: 'Ocultar todos',
    REVIEWS: 'Comentários',
    SHOW_ALL_REVIEWS: 'Ver todos os comentários',
    MAILER: {
      HEADING:
        'As melhores ofertas e novidades do teatro diretamente na sua caixa de entrada',
      SUBHEADING: `Inscreva-se na nossa newsletter para receber as últimas novidades e ofertas incríveis dos espetáculos teatrais.`,
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: 'Avaliações de {0}',
    REVIEWS_COUNT: '{0} avaliações',
    AWESOME: 'Incrível',
    GOOD: 'Bom',
    AVERAGE: 'Mediano',
    POOR: 'Ruim',
    TERRIBLE: 'Péssimo',
    REVIEW_BY_HEADOUT: 'Nossa opinião: avaliação da Headout',
    WHAT_PEOPLE_ARE_SAYING: 'O que dizem por aí',
    MOST_RELEVANT: 'Mais relevantes',
    RATING_HIGH_TO_LOW: 'Avaliação: da melhor à pior',
    RATING_LOW_TO_HIGH: 'Avaliação: da pior à melhor',
    CRITIC_REVIEWS: 'Avaliações da crítica',
    USER_REVIEWS: 'Avaliações dos usuários',
    CONTRIBUTORS_REVIEW: 'Avaliação da redação',
  },
  HOHO: {
    HOHO: 'Bilhetes hop-on hop-off',
    BUS_ROUTES_DETAILS: 'Rotas',
    TOUR_DETAILS: 'Detalhes do tour',
    ROUTES_SCHEDULES: 'Rotas e horários',
    VALIDITY: 'Válido por 1 dia',
    VALIDITY_NOTE:
      'Sua experiência é valida por {0} dia(s) corrido(s). Se você reservar seu bilhete para 6 de maio de 2023, ele será válido até 6 de maio de 2023, 21:00 PST',
    BESTSELLER: 'Mais vendido',
    SEE_ALL: 'Ver tudo',
    TIMINGS: 'HORÁRIO',
    FREQUENCY: 'FREQUÊNCIA',
    DURATION: 'DURAÇÃO',
    STARTING_LOCATION: 'Local de partida',
    CALENDAR_FOOTNOTE: '* Preços exibidos em {0}',
    GOT_IT: 'Entendido',
    TOUR_TIMINGS: 'Horário',
    TOUR_FREQUENCY: 'Frequência',
    SELECT_DATE: 'Select a date',
    SELECT_TOUR: 'Select Tour Type',
    VIEW_TOUR_DETAILS: 'View tour details',
    BUS_DETAILS: 'MORE DETAILS',
    VIEW_ROUTES: 'View all routes',
    BUS_ROUTES: 'BUS ROUTES',
    ATTRACTIONS_PREVIEW: 'Fastest way to view {0}+ top attractions including',
    ROUTES: 'Rotas',
    COMBO_SUBTITLE: 'Poupe mais com',
    COMBO_TITLE: 'Ofertas combinadas na sua excursão Hop-on Hop-off',
    COMBO_DWEB_TITLE:
      'Poupe mais com ofertas combinadas na sua excursão Hop-on Hop-off',
    STOPS_AND_ATTRACTIONS: 'Paradas e atrações ao redor',
    HOP_ON_OFF_AT: 'Embarque e desembarque em {0} paradas',
    TIMINGS_FREQUENCY: 'Horários e frequência',
    TOUR_DURATION: 'Duração do tour',
    EVERY_X_MINS: 'Every {0}',
    VIEW_LOCATION: 'Ver a localização',
    BANNER_SUBTEXT:
      'A forma mais rápida e prática de ver todas as atrações da cidade.',
    TOP_ATTRACTIONS: 'Atrações principais',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Reserva de última hora',
        DESCRIPTION: 'Confirmação imediata no seu celular',
      },
      COST_EFF: {
        NAME: 'Passeio econômico',
        DESCRIPTION: 'Várias atrações, um só bilhete',
      },
      DAILY_RIDES: {
        NAME: 'Trajetos diários ilimitados',
        DESCRIPTION: 'Explore a cidade no seu próprio ritmo',
      },
      BOOK_RELAX: {
        NAME: 'Reserve e relaxe',
        DESCRIPTION: '{0} milhões de viajantes satisfeitos',
      },
    },
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Traslados privados',
    SHARED_TRANSFERS: 'Traslados compartilhados',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Reserve online',
        DESCRIPTION:
          'Tenha uma experiência de reserva rápida e conveniente ao reservar suas passagens online.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Confirmação imediata',
        DESCRIPTION:
          'Receba uma confirmação imediata ao reservar sua passagem de traslado de/para o aeroporto.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Embarque conveniente',
        DESCRIPTION:
          'Evite o incômodo de longas filas, pois o veículo do traslado estará à sua espera no seu ponto de embarque.',
      },
      DROP_OFF: {
        TITLE: 'Desembarque',
        DESCRIPTION: 'Chegue ao seu destino de forma rápida e confortável.',
      },
    },

    SHARED_TRANSFERS_IN: 'Traslados compartilhados em {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      'Uma opção de transporte confortável e econômica para vários passageiros partindo de ou para um aeroporto.',
    PRIVATE_TRANSFERS_IN: 'Traslados privados em {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      'Um serviço de transporte conveniente e personalizado para indivíduos e pequenos grupos, que oferece uma viagem confortável e direta partindo de ou para um aeroporto.',
    ANYWHERE_IN_THE_CITY: 'Qualquer lugar da cidade',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Diversas opções de veículos',
      FREE_CANCELLATION: 'Cancelamento grátis',
    },
    SEAMLESS_TRANSFERS: 'Traslados cômodos e confiáveis em todo mundo',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Escolha o melhor traslado de/para o aeroporto',
    HASSLE_FREE_TRANSFER: 'Traslado de/para o aeroporto sem complicações',

    // New experiment (AT LP)
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Traslados de/para aeroportos em {0} de',
    BUSES: 'ônibus',
    TRAINS: 'trem',
    PRIVATE_TAXIS: 'táxi privado',
    BUS_TRAIN: 'Ônibus/Trem',
    PRIVATE_TAXI: 'Táxi privado',

    FROM: 'Partida',
    TO: 'Chegada',
    SELECT_PICKUP: 'Selecionar ponto de partida',
    SELECT_DROPOFF: 'Selecionar destino',
    ENTER_DESTINATION: 'Insira o seu destino',
    ENTER_PICKUP: 'Introduzir o local de recolha',
    PICKUP_DATE: 'Data de partida',
    SELECT_DATE: 'Escolher data',
    PICKUP_TIME: 'Hora de partida',
    SELECT_TIME: 'Escolher hora',
    GUESTS: 'Hóspedes',
    GUEST: 'Hóspede',
    ADD_GUESTS: 'Somar hóspedes',
    EXPLORE_TRANSFERS: 'Traslados e outras experiências',
    COMBOS_AND_EXTRAS: 'Combos e adicionais',

    YOUR_RIDE_DOORSTEP: 'Sua viagem de porta a porta',
    COMFORTABLE_RIDE:
      'Reserve um táxi privado confortável de/para os principais aeroportos de {0}',
    TRUSTED_DRIVERS: 'Motoristas confiáveis',
    RIDES_24_7: 'Traslados 24 h por dia',
    FLIGHT_TRACKING: 'Rastreamento dos voos',
    KNOW_MORE: 'Saiba mais',
    RESERVE_YOUR_RIDE: 'Reserve seu traslado',
    TRANSFER_OPTIONS: 'Opções de traslados encontradas',
    TRANSFERS_AVAILABLE_PLURAL: '{0} traslados disponíveis',
    TRANSFERS_AVAILABLE_SINGULAR: '1 traslado disponível',

    TRUSTED_PARTNERS: 'Mais de 35 parceiros confiáveis {0}',
    WORLDWIDE: 'no mundo',
    COMFORTABLE_RIDES: 'Traslados confortáveis',
    FREQUENT_DEPARTURES: 'Partidas frequentes',
    MULTIPLE_TRANSPORT_OPTIONS: 'Várias opções de transporte',
    AND_MANY_MORE: 'E muito mais',

    ADD_PICKUP_LOCATION: 'Adicionar local de partida',
    ADD_DROPOFF_LOCATION: 'Adicionar local de destino',
    SELECT_PICKUP_DATE_AND_TIME: 'Selecionar data e hora da partida',
    SELECT_A_DATE: 'Selecionar data',

    TRAIN_STATION: 'Estação de trem',
    BUS_STOP: 'Ponto de ônibus',

    ADD_RETURN: 'Adicionar volta',
    HEADS_UP: 'Atenção!',
    ADDED_RETURN_TRIP: 'Você adicionou uma viagem de volta.',
    RETURN_NOTE:
      'Os detalhes da sua viagem de volta serão exibidos nas próximas etapas',
    OKAY_I_UNDERSTAND: 'Entendi!',

    SERVING_GUESTS: 'Servindo {0} em {1} no mundo',
    GUESTS_COUNT: 'mais de 220 mil viajantes',
    CITIES_COUNT: 'mais de 55 cidades',
    PARNTER_WITH_BEST:
      'Temos parceria apenas com os melhores para que você tenha uma experiência inesquecível. Nós cuidamos dos detalhes enquanto você se senta, relaxa e aproveita a viagem.',
  },
  PC_EXP: {
    SHOW_INCL: 'O que inclui e informações importantes',
    CLEAR: 'Limpar',
    ALL_EXPERIENCES: 'Todas experiências',
    FILTER_BY_CATEGORIES: 'Filtrar por categorias',
    CATEGORIES: 'Categorias',
    COMBOS: {
      HEADING: 'Tudo que é bom vem em dobro. Como nossos combos econômicos.',
      DESCRIPTOR_1: 'Ofertas para economizar',
      DESCRIPTOR_2: 'Planeje melhor sua viagem',
    },
  },
  TOP: 'As melhores atrações em {0}',
  VIEW_CALENDAR: 'Ver o calendário',
  SHOWS_CALENDAR: 'Calendário de espetáculos',
  IN: 'em',
  SEATS: 'Assentos',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Guia do conteúdo',
    QUICK_INFORMATION: 'Informações gerais',
    PEAK: 'horário de pico',
    OFF_PEAK: 'fora do horário de pico',
    ADDRESS: 'ENDEREÇO',
    RECOMMENDED_DURATION: 'DURAÇÃO RECOMENDADA',
    VISITORS_PER_YEAR: 'VISITANTES POR ANO',
    NUMBER_OF_ENTRANCES: 'NÚMERO DE ENTRADAS',
    EXPECTED_WAIT_TIME_STANDARD: 'TEMPO DE ESPERA PREVISTO - PADRÃO',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE:
      'TEMPO DE ESPERA PREVISTO - ENTRADA SEM FILA',
    UNESCO_YEAR: 'ANO DE INSCRIÇÃO NA UNESCO',
    ARCHITECTURE_STYLE: 'ESTILO ARQUITETÔNICO',
    TIMINGS: 'Horários',
    SIZE_HEIGHT: 'TAMANHO/ALTURA',
    TICKETS: 'INGRESSOS',
    FUN_FACTS: 'Curiosidades',
    DID_YOU_KNOW: 'Você sabia?',
    MORE_INTERESTING_FACTS: 'Mais fatos interessantes',
    PLAN_YOUR_VISIT: 'Planeje sua visita',
    ALSO_KNOWN_AS: 'Também conhecido como',
    FOUNDED_ON: 'Fundado em',
    FOUNDED_BY: 'Fundado por',
    FROM: 'A partir de',
    CLOSED_TODAY: 'Fechado hoje',
    TODAY: 'Hoje',
    CLOSED: 'Fechado',
    OPEN: 'Abrir',
    LAST_ADMISSION: 'Última Admissão',
    DAYS: 'Dias',
    BEST_TIME_TO_VISIT: 'Melhor época para visitar',
    WEEKDAY_VS_WEEKEND: 'Dia útil vs Fim de semana',
    PEAK_VS_LOW_SEASON: 'Temporada alta vs Temporada baixa',
    PLEASANT: 'Agradável',
    CROWDED: 'Lotado',
    VERY_CROWDED: 'Muito lotado',
    LOW_SEASON: 'Baixa temporada',
    MID_SEASON: 'Temporada moderada',
    PEAK_SEASON: 'Alta temporada',
    TO: 'ATÉ',
    TO_LOWER: 'até',
    LAST_ENTRY: 'última entrada',
    SUBATTRACTIONS: 'Subatrações',
    INCLUDED_WITH_TICKETS: 'Incluído nos ingressos para {0}',
    INCLUDED_WITH_SOME_TICKETS: 'Incluído em alguns ingressos para {0}',
    EXPLORE_ALL_POI_TICKETS: 'Explorar os ingressos e tours para {0} & {1}',
    OPERATING_HOURS: 'Horário de funcionamento',
    SEE_MORE: 'Ver mais',
    MORE_INSIGHTS: 'Mais informações',
    SELECT_YOUR_EXPERIENCE: 'Selecione sua experiência',
  },
  OFF_PERCENT: '{0}% de desconto',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Mapa de assentos',
    CAPACITY: 'Capacidade: {0} assentos',
    WHATS_ON: 'Em cartaz',
    CATEGORIES: 'Categorias',
  },
  NEXT: 'Continuar',
  PREVIOUS: 'Anterior',
  ITINERARY: {
    TAB: 'Itinerário',
    HEADING: 'Itinerário da experiência',
    VIEW_ITINERARY: 'Ver itinerário',
    VIEW_DETAILS: 'Ver detalhes',
    PASSES_BY_SECTION_HEADING: 'Passa por',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Destaques',
      NEARBY_THINGS_TO_DO: 'O que fazer nas proximidades',
      THINGS_TO_DO: 'O que fazer',
    },
    STOP_CARD: {
      TITLE: {
        START: 'PONTO DE PARTIDA',
        END: 'PONTO FINAL',
        STARTING_POINT: 'PONTO DE PARTIDA',
        STOP: 'PARADA',
        ENDING_POINT: 'PONTO FINAL',
        PASSING_BY: 'PASSA POR',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} pontos de partida disponíveis',
        END: '{0} pontos finais disponíveis',
      },
    },
    GET_DIRECTION: 'Como chegar',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} horas e {1} minutos',
        WITHOUT_HOURS: '{0} minutos',
        WITHOUT_MINS: '{0} horas',
      },
      ATTRACTIONS_COUNT: '{0} atrações',
      ACTIVITIES_COUNT: '{0} atividades',
      TOTAL_DURATION: 'Duração total',
      FREQUENCY: 'Frequência',
      FIRST_DEPARTURE: 'Primeira partida',
      LAST_DEPARTURE: 'Última partida',
      FIRST_DEPARTURE_TIME: 'Hora da primeira partida',
      LAST_DEPARTURE_TIME: 'Hora da última partida',
      MODE_OF_TRANSPORT: 'Meio de transporte',
      FOOD_AND_DRINKS: 'Alimentos e bebidas',
    },
    WALK_DURATION: '{0} a pé',
    MORE: 'mais {0}',
    TIMELINE_VIEW: 'Cronograma',
    MAP_VIEW: 'Mapa',
    MAP_OVERLAY: 'Use CTRL/⌘ + cursor para mover o mapa',
    VIEW_EXPERIENCE_MAPPED_OUT: 'Confira sua experiência mapeada.',
    OPEN_MAP_VIEW: 'Abrir o mapa',
    START_POINT_SAME_AS_END_POINT: 'O ponto final será o ponto de partida',
  },
  CRUISES: {
    BANNER_HEADING:
      'Descubra {0} em um cruzeiro: refeições, bebidas e tranquilidade',
    FILTERS: {
      ALL: 'Todos',
      SIGHTSEEING: 'Passeio turístico',
      LUNCH: 'Almoço',
      DINNER: 'Jantar',
      COMBOS: 'Combos',
    },
    MAP_OVERLAY: 'Clique ou toque para mover o mapa',
    SIGHTS_COVERED: 'Atrações no caminho',
    MENU: 'Menu',
    BOARD_AT: 'Embarque em {0}',
    BOARDING_POINTS_AVAILABLE: '{0} disponíveis',
    VIEW_POPULAR_SIGHTS: 'Veja pontos turísticos famosos como {0} {1}',
    X_BOARDING_POINTS: '{0} pontos de embarque',
    BOARDING_POINT: 'Ponto de embarque',
    BOARDING_POINTS: 'Pontos de embarque',
    LANDMARKS: 'Pontos turísticos',
    GET_DIRECTIONS: 'Como chegar',
    FOOD_MENU: 'Menu',
    X_PAGE: '{0} página',
    X_PAGES: '{0} páginas',
    MORE: 'e mais {1}',
    PDF: {
      ZOOM_IN: 'Ampliar zoom',
      ZOOM_OUT: 'Diminuir zoom',
      FIT_TO_WIDTH: 'Ajustar à largura',
      RESET_ZOOM: 'Redefinir zoom',
    },
    COMBO_HEADING: 'Veja mais por menos: ofertas em combos e city cards',
    TRUST_TOOLTIP_HEADER: 'Como obtemos as avaliações?',
    TRUST_TOOLTIP_CONTENT:
      'As avaliações são enviadas por usuários reais que reservaram e tiveram uma experiência com a Headout.',
    REVIEW_SECTION_HEADER: 'Avaliações de participantes',
    TRUST_VB_TAG: 'Reserva verificada',
    SNAPSHOTS_SECTION_HEADER: 'Fotos para os nossos clientes',
  },

  FLEXIBLE_CANCELLATION: {
    TOOLTIP_TEXT:
      'Receba reembolso total por uma pequena taxa se você cancelar dentro de 24 horas antes do início da experiência.',
    KNOW_MORE: 'Saiba mais',
    FULL_REFUND: 'Reembolso total',
    INSTANT: 'Em instantes',
    NO_QUESTIONS: 'Sem questionamentos',
    TNC: 'Termos e condições',
    ELIGIBILITY:
      'Elegibilidade: o plano de cancelamento flexível deve ser selecionado e comprado no momento da reserva.',
    CANCELLATION_DEADLINE:
      'Prazo de cancelamento: a reserva pode ser cancelada até 24 horas antes do início da experiência.',
    REFUND_AMOUNT:
      'Valor do reembolso: você receberá o reembolso do valor original pago na reserva (subtraindo a taxa de proteção em caso de cancelamento).',
    NON_TRANSFERABLE: 'Intransferível: válido apenas para esta reserva.',
    GUIDELINES:
      'Diretrizes: o plano se torna inválido se o cliente validar ou utilizar qualquer parte do ingresso antes do cancelamento. Nesses casos, aplicam-se as políticas de cancelamento padrão e nenhum reembolso adicional será concedido.',
  },
};
export default pt;
