const ro = {
  AUDIO_GUIDE: {
    BANNER: 'Audio ghid gratuit',
    PRODUCT_SUFFIX: 'cu Audio ghid',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Partener autorizat și de încredere',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Revânzător autorizat',
    SUB_TEXT:
      'Experiențe autentice de la parteneri de încredere și verificați.',
  },
  REVIEWS: 'recenzii',
  AVAILABLE: 'Disponibil',
  BACK: 'Înapoi',
  BANNER_CTA: 'Cumpărați bilete',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout este un brand de încredere pentru milioane de oaspeți din întreaga lume, oferind experiențe curatoriate pentru a vă bucura de această atracție.',
    NON_PARTNERED_SENSITIVE:
      'Headout este un brand de încredere pentru milioane de oaspeți din întreaga lume, oferind experiențe curatoriate pentru a vă bucura de această atracție Acesta nu este site-ul web al locației.',
    PARTNERED_NON_SENSITIVE:
      'Headout este un partener autorizat și de încredere al locației, oferind experiențe curatoriate pentru a vă bucura de această atracție.',
    PARTNERED_SENSITIVE:
      'Headout este un partener autorizat și de încredere al locației, oferind experiențe curatoriate pentru a vă bucura de această atracție. Acesta nu este site-ul web al locației.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout este un partener autorizat și de încredere al locației, oferind o selecție curatorială a celor mai bune experiențe pentru a vă bucura de această atracție.',
  BOOK_NOW_CTA: 'Rezervați acum',
  BOOSTERS: {
    MOST_LOVED: 'Most loved',
    SPECIAL_DEAL: 'Special deal',
    HEADOUT_EXCLUSIVE: 'Exclusiv Headout',
  },
  BUY_TICKETS_CTA: 'Cumpărați bilete',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Puteți anula aceste bilete cu până la {0} ore înainte de începerea experienței și veți primi o rambursare integrală.',
    CANCELLABLE_ANYTIME:
      'Anulare gratuită în orice moment înainte de începerea experienței.',
    CANCELLABLE_DAYS:
      'Puteți anula aceste bilete cu până la {0} zile înainte de începerea experienței și veți primi o rambursare integrală.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Aceste bilete nu pot fi anulate. Cu toate acestea, ele sunt valabile pentru o perioadă de timp extinsă.',
    HEADING: 'Politica de modificare',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Aceste bilete nu pot fi anulate. Cu toate acestea, ele pot fi reprogramate cu până la {0} ore înainte de începerea experienței.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Aceste bilete nu pot fi anulate sau reprogramate.',
    VALID_UNTIL_DATE:
      'Aceste bilete nu pot fi anulate. Cu toate acestea, le puteți utiliza oricând până la {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Aceste bilete nu pot fi anulate. Cu toate acestea, le puteți folosi oricând în următoarele {0} zile.',
    VALID_WITHIN_NEXT_MONTHS:
      'Aceste bilete nu pot fi anulate. Cu toate acestea, le puteți utiliza oricând în următoarele {0} luni.',
  },
  CANCELLATION_POLICY_HEADING: 'Politica de anulare',
  CASHBACK: '{0}% cashback',
  CASHBACK_INFO:
    'Veți primi <strong>%</strong> cashback atunci când rezervați această experiență. Cashback-ul va fi creditat automat în contul dumneavoastră Headout și poate fi utilizat pentru orice rezervare viitoare cu Headout.',
  CATEGORY_SLIDER_HEADING:
    'Clienții care au rezervat acest spectacol au mai explorat și...',
  CHECK_AVAIL: 'Verificați disponibilitatea',
  SELECT_SEATS: 'Selectați locurile',
  CITY_PAGE: {
    BANNER_TITLE: 'Descoperă cele mai bune experiențe din',
    TOP_ATTRACTIONS: 'Atracții de top',
    GO_BEYOND: 'Treceți dincolo de {0}',
    ALL_DAY_TRIPS: 'Vedeți toate excursiile de o zi',
    CITIES_NEARBY: 'Orașe apropiate',
    POPULAR_CATEGORIES: 'Categorii populare',
    GO_TO_GUIDE: 'Ghidul esențial pentru {0}',
    VIEW_TRAVEL_GUIDE: 'Vedeți ghidul de călătorie',
    EXPLORE: 'Explorați {0}',
    GUIDE_SUBHEADING:
      'Explorarea {0} nu a fost niciodată mai ușoară! Ghidul nostru de călătorie {0} conține tot ce trebuie să știți despre oraș, de la ce să mâncați și ce să vedeți, la cum să ajungeți acolo, unde să vă cazați și multe altele!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Informații generale',
      WHERE_TO_EAT: 'Ce să mâncați',
      WHERE_TO_STAY: 'Unde să stați',
      THINGS_TO_DO: 'Ce să faceți',
      WEATHER: 'Cel mai bun moment pentru a vizita',
      NEIGHBOURHOODS: 'Comunitatea locală',
      TRANSPORTATION: 'Deplasare',
      TRIP_PLANNER: 'Plan de călătorie',
      FAMILY_TRAVEL: 'Călătorind cu copiii',
      TRAVEL_TIPS: 'Sfaturi și trucuri de călătorie',
      SHOPPING: 'Cumpărături',
      ART_AND_CULTURE: 'Artă și cultură',
    },
    MAILER: {
      HEADING:
        '{0} inspirație de călătorie direct în căsuța dumneavoastră poștală',
      SUBHEADING:
        'Explorați noi orașe cu experiențe curatoriate, cashback instantaneu, oferte exclusive și sfaturi de călătorie esențiale!',
    },
  },
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Utilizăm cookie-uri și tehnologii similare în mai multe scopuri, inclusiv pentru a vă îmbunătăți experiența pe site-ul nostru și pentru reclame.',
    MANAGE_PREFERENCES: 'Gestionați',
    PREFERNCES_SAVED: 'Preferințele dumneavoastră au fost salvate',
    COOKIES: 'Cookie-uri:',
    ACCEPT: 'Okay',
    ALLOW_ALL: 'Permiteți toate',
    DENY_ALL: 'Refuzați toate',
    HEADING: 'Prețuim confidențialitatea dumneavoastră, întotdeauna',
    DESCRIPTION:
      '*   Modulele cookie sunt fișiere de mici dimensiuni plasate pe computerul, dispozitivul mobil sau orice alt dispozitiv al dumneavoastră de către site-ul web/platformă, care conțin detaliile istoricului navigării dumneavoastră între alte utilizări.\n*   Utilizăm diferite tipuri de cookie-uri pentru a urmări utilizarea de către dvs. a Platformei noastre și pentru a stoca anumite informații care ne ajută să vă oferim servicii mai personalizate. Anumite odule cookie pot fi plasate pe dispozitivul dumneavoastră ca urmare a utilizării de către dumneavoastră a oricăror servicii disponibile pe platforma noastră.\n*   În general, folosim două seturi diferite de tehnologii în această categorie:\n    *   **Cookie-uri sau Cookie-uri de browser.** sunt fișiere mici care sunt plasate automat pe dispozitivul dumneavoastră când accesați platforma noastră. Puteți să vă instruiți browserul să refuze toate modulele cookie. În cazul în care nu acceptați modulele noastre cookie, este posibil să nu puteți utiliza anumite părți ale platformei noastre.\n    *   **Semnalizatoare web.** Denumite și gif-uri transparente, etichete de pixeli și imagini pixelizate, acestea sunt atașate în diverse secțiuni ale platformei noastre și ale e-mailurilor noastre, permițându-ne să monitorizăm și să înțelegem activitatea utilizatorilor.\n*   Aceste module cookie stocate pe dispozitivul dumneavoastră pot fi „persistente” sau „de sesiune”. Modulele cookie persistente sunt cele care rămân pe dispozitivul dumneavoastră chiar și atunci când nu sunteți conectat la internet, în timp ce modulele cookie de sesiune sunt șterse automat de îndată ce închideți browserul web.\n*   Utilizăm atât cookie-uri de sesiune, cât și cookie-uri persistente în scopurile stabilite mai jos:\n    *   Cookie-uri necesare / esențiale\n        *   _Tip:_ Cookie-uri de sesiune\n        *   _Scop:_ Aceste cookie-uri sunt esențiale pentru a vă permite să accesați diferite secțiuni ale Platformei și, dacă acestea nu sunt permise, este posibil să nu puteți accesa serviciile disponibile pe Platformă. Aceste cookie-uri ne ajută în continuare să autentificăm utilizatorii și să prevenim orice fel de activitate frauduloasă pe platformă.\n    *   Politica privind modulele cookie / Modulele cookie de acceptare a notificărilor\n        *   _Tip:_ Cookie-uri persistente\n        *   _Scop:_ Aceste module cookie identifică dacă utilizatorii au acceptat utilizarea modulelor cookie.\n    *   Cookie-uri de funcționalitate\n        *   _Tip:_ Cookie-uri persistente\n        *   _Scop:_ Aceste module cookie ne permit să ne amintim alegerile pe care le faceți atunci când utilizați platforma, cum ar fi detaliile de conectare sau preferințele dvs. de limbă. Scopul principal al acestor module cookie este de a vă oferi o experiență mai personalizată de fiecare dată când utilizați Platforma.\n\nToți termenii cu majuscule utilizați mai sus sunt definiți în Politica de confidențialitate. Pentru o înțelegere detaliată, vă rugăm să consultați [Politica de confidențialitate](/privacy-policy/)\n',
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Aflați despre cerințele de viză, schimbul valutar, diferențele de fus orar și multe altele pentru a vă asigura o sosire ușoară și un sejur plăcut.',
    WHERE_TO_EAT:
      'Bucurați-vă de scena culinară vibrantă, savurând diverse arome și savurând delicatese locale în fiecare colț al {0}.',
    WHERE_TO_STAY:
      'Descoperiți cele mai bune unități de cazare {0}, care oferă confort, comoditate și o experiență memorabilă pentru șederea dumneavoastră.',
    THINGS_TO_DO:
      'Experimentați o multitudine de activități și atracții captivante, care răspund tuturor intereselor și vă asigură un timp de neuitat.',
    WEATHER:
      'Planificați-vă călătoria cu înțelepciune și profitați la maximum de vizita dumneavoastră, deoarece {0} oferă experiențe încântătoare pe tot parcursul anului.',
    NEIGHBOURHOODS:
      'Descoperiți diversele comunități locale și cartierele pline de viață, care conferă {0} caracterul său unic.',
    TRANSPORTATION:
      'Navigați cu ușurință în {0} folosind sistemul său eficient de transport, oferind opțiuni convenabile pentru a explora toate atracțiile sale.',
    TRIP_PLANNER:
      'Maximizați-vă timpul în {0} cu itinerarii atent alese, asigurându-vă că profitați la maximum de fiecare moment.',
    FAMILY_TRAVEL:
      'Porniți într-o aventură de familie cu numeroase atracții, parcuri și opțiuni de divertisment care se adresează copiilor de toate vârstele.',
    TRAVEL_TIPS:
      'Descoperiți sfaturi de inițiați și trucuri de călătorie pentru a vă îmbunătăți călătoria, făcând vizita dumneavoastră în {0} cu adevărat excepțională.',
    SHOPPING:
      'Explorați un paradis al cumpărătorilor, cu o gamă largă de buticuri, piețe și centre comerciale, care oferă de toate, de la obiecte de artizanat local la modă de lux.',
    ART_AND_CULTURE:
      'Cufundați-vă în bogata scenă artistică și culturală, de la muzee captivante la festivaluri vibrante care celebrează patrimoniul {0}.',
  },
  CLOSE: 'Închideți',
  COLLECTION_SLICE_HEADING: 'Cele mai bune lucruri de făcut în {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Selectați',
    SELECT_PREFERENCE: 'Selectați preferințele',
    SELECT_OPTION: 'Selectați opțiunea',
    SELECT_TICKET: 'Selectați biletul',
  },
  COMPARE_ALL_DETAILS: 'Comparați toate detaliile',
  COVID19_ALERT: {
    KEY_TEXT: 'Actualizare privind COVID-19',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Sunteți prioritatea noastră. Vă rugăm să consultați pagina noastră de ajutor pentru a găsi cele mai recente actualizări privind politicile noastre de anulare flexibile',
  },
  CURRENCY: 'Monedă',
  CUSTOMER_REVIEW_HEADING: 'Recenzii ale clienților',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Audio ghid',
    DURATION: 'Durata: {0}',
    EXTENDED_VALIDITY: 'Valabilitate extinsă',
    FLEXIBLE_DURATION: 'Durată flexibilă',
    FREE_CANCELLATION: 'Anulare gratuită',
    GUIDED_TOUR: 'Tur ghidat',
    HOTEL_PICKUP: 'Ridicare de la hotel',
    INSTANT_CONFIRMATION: 'Confirmare instantanee',
    MEALS_INCLUDED: 'Mese incluse',
    MOBILE_TICKET: 'Bilet mobil',
    SKIP_THE_LINE: 'Skip the Line',
    TRANSFERS: 'Transferuri incluse',
  },
  DURATION: 'Durata',
  EARLIEST_AVAILABILITY: 'Cea mai apropiată disponibilitate',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Introduceți adresa de e-mail aici',
    SIGN_UP: 'Înscrieți-vă',
    THANK_YOU: 'Mulțumim!',
    SUBSCRIBED_MSG: 'Acum sunteți abonat',
    ERROR_MSG: 'Vă rugăm să introduceți o adresă de e-mail valabilă',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Bilete pentru teatrul de pe Broadway ',
    },
    LTT: {
      MB_NAME: 'Bilete pentru teatrul din Londra ',
    },
  },
  EXCLUSIONS: 'Elemente excluse',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '{0} milioane +',
    HEADING_RATING: '4.4/5',
    HEADING_SAFE: '100% sigur',
    HEADING_SUPPORT: 'Centrul de asistență 24/7',
    SUB_HEADING_CUSTOMER: 'Clienți mulțumiți în peste 10.000 de experiențe',
    SUB_HEADING_RATING: '5.000+ recenzii verificate cu un scor excelent de 90%',
    SUB_HEADING_SAFE:
      'Toate activitățile în aer liber sunt 100% sigure și securizate',
    SUB_HEADING_SUPPORT:
      'Aveți o întrebare? Chat live cu experții locali, oriunde și oricând',
  },
  FLEXIBLE: 'Flexibil',
  FOOTER: {
    CALL_US: 'Sunați-ne',
    CHAT_WITH_US: 'Intrați pe chat cu noi',
    COMPANY_DETAILS: 'Detalii companie',
    INFORMATION: 'Informații',
    ABOUT_US: 'Despre noi',
    GMAPS_DISCLAIMER:
      'Toate capturile de ecran ale hărților de pe această pagină provin de la Google, în conformitate cu principiul utilizării corecte. Toate drepturile pentru astfel de capturi de ecran aparțin platformei respective, iar utilizarea lor este exclusiv în scop informativ sau orientativ.',
    DISCLAIMER:
      'Acest site nu este site-ul oficial al <attraction>. Este administrat de Headout și colaborează cu atracții și operatori de turism pentru a oferi experiențe incredibile printr-o simplă apăsare de buton.',
    EMAIL_US: 'Trimiteți-ne un e-mail',
    GET_HELP: 'Obțineți ajutor',
    LEGAL: 'Aspecte legale',
    PRIVACY_POLICY: 'Politica de confidențialitate',
    QUICK_LINKS: 'Legături rapide',
    TERMS_AND_CONDITIONS: 'Termeni și condiții',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Realizat cu ',
    ALL_OVER_THE: ' peste tot în ',
    TERMS_OF_USAGE: 'Termeni de utilizare',
    GET_HELP_24_7: 'Obțineți ajutor 24/7',
    HELP_CENTER: 'Centrul de ajutor',
    COMPANY: 'Compania',
    WE_ACCEPT: 'Acceptăm',
    DOWNLOAD_HEADOUT: 'Descărcați aplicația Headout',
    SCAN_CODES: 'Scanare cod',
    STAR_VERIFIED: 'click pentru a verifica apartenența la S.T.A.R',
    OFFICIAL_TICKET_RETAILER: 'Distribuitor oficial de bilete',
  },
  FREE_CANCELLATION: 'Anulare gratuită',
  FREE_CANCELLATION_SUBTEXT:
    'Înțelegem că planurile se schimbă, puteți anula gratuit cu până la 72 de ore înainte de eveniment.',
  FROM: 'De la',
  GET_CASHBACK: 'Obțineți {0}% Cashback',
  GROUP_TICKETS: 'Bilete pentru grupuri',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '{0}+ milioane de clienți mulțumiți',
    SUB_TEXT:
      'Satisfacția clienților este prioritatea noastră principală. Alăturați-vă bazei noastre de clienți fericiți.',
  },
  HEADOUT: 'Headout',
  HELP_CENTER: {
    MAIN_TEXT: 'Centrul de asistență 24/7',
    SUB_TEXT:
      'Aveți întrebări sau preocupări? Suntem aici pentru a vă ajuta 24 de ore din 24, 7 zile din 7 - la telefon, chat și e-mail.',
  },
  INCLUSIONS: 'Elemente incluse',
  LANGUAGE: 'Limba',
  LANGUAGES: {
    ENGLISH: 'Engleză',
    SPANISH: 'Spaniolă',
    FRENCH: 'Franceză',
    ITALIAN: 'Italiană',
    GERMAN: 'Germană',
    PORTUGUESE: 'Portugheză',
    NEDERLANDS: 'Olandeză',
    POLISH: 'Poloneză',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Tur disponibil în {0}',
  LISTICLES: {
    KNOW_MORE: 'Aflați mai multe',
    SEATING_CHART: 'Graficul locurilor',
    WHY_BOOK_FROM_US: 'De ce să rezervați de la noi?',
  },
  MORE_DETAILS: 'Mai multe detalii',
  MORE_CURRENCIES: 'Mai multe monede',
  NEW: 'NOU',
  NEW_ARRIVAL: 'Noutăți',
  NEXT_AVAILABLE: 'Următoarea opțiune disponibilă: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout este un brand de încredere pentru pese {0} milioane de oaspeți din întreaga lume, oferind experiențe curatoriate pentru a vă bucura de cele mai bune experiențe. Acesta nu este site-ul web al locației.',
  NO_RESULT_FOUND: 'Hmm, nu am găsit niciun rezultat.',
  OFF: 'Reducere',
  OPEN_DATED_DESCRIPTOR:
    'Rezervați cu flexibilitate - nu este necesară selectarea datei',
  OPENING_DATE: 'Data deschiderii',
  OPENING_ON: 'Deschidere pe',
  OPENS: 'Se deschide',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout este un partener autorizat și de încredere al locației, oferind o selecție curatorială a celor mai bune experiențe pentru a vă bucura de această atracție. Acesta nu este site-ul web al locației.',
  POPULAR_CURRENCIES: 'Monede populare',
  PRICES_STARTING: 'Prețuri începând de la',
  PROMO_CODES: {
    APPLY_CODE: 'APLICAȚI CODUL',
    APPLIED: 'APLICAT',
    TOOL_TIP_INFO: 'Această reducere se aplică la finalizarea comenzii',
    DESCRIPTION: {
      ABSOLUTE: 'Obțineți o reducere de {0}',
      CAPPED: 'Obțineți o reducere de {0}%, până la {1}',
      PERCENTAGE: 'Obțineți {0} off',
    },
    REMOVE: 'REMOVE ',
  },
  RATINGS: '{0} Evaluări',
  READ_MORE: 'Citiți mai mult',
  READ_MORE_TEXT: 'Citește mai mult',
  READ_LESS: 'Citește mai puțin',
  VIEW_DETAILS: 'Vezi detalii',
  REOPENING: 'Redeschidere',
  REOPENING_DATE: 'Data redeschiderii',
  REOPENING_ON: 'Redeschidere pe',
  REOPENS: 'Se redeschide',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      CTA_URL:
        'https://www.austria.info/en/service-and-facts/coronavirus-information/entry-regulations',
      TEXT: 'Se aplică reglementările 2G: accesul la cazare, la instituțiile culturale și la restaurante/baruri, printre altele, este posibil numai cu dovada vaccinării complete sau a unei infecții anterioare. Un test Covid-19 negativ nu mai este suficient.',
    },
    AU_DESCRIPTION: {
      CTA_URL:
        'https://www.smartraveller.gov.au/COVID-19/COVID-19-vaccinations',
      TEXT: 'Vizitatorii cu vârsta de peste 16 ani trebuie să prezinte dovada vaccinării COVID-19 sau o scutire medicală. ',
    },
    BANNER_CTA: 'Aflați mai multe',
    BERLIN_DESCRIPTION: {
      CTA_URL:
        'https://www.berlin.de/en/news/coronavirus/7081102-6098215-berlin-introduces-extensive-2G-rule.en.html',
      TEXT: 'Se aplică reglementările 2G: accesul este permis doar oaspeților complet vaccinați și celori recuperați, cu dovada respectivă. Oaspeții sub 18 ani sau cei care nu pot fi vaccinați din motive medicale trebuie să prezinte un rezultat negativ al testului COVID la intrare. Cei care nu pot fi vaccinați din motive medicale trebuie să dovedească, de asemenea, că nu pot fi vaccinați prin intermediul unui certificat medical la intrare.',
    },
    CTA_TEXT: 'Detalii de siguranță',
    DESCRIPTION_CTA: 'Aflați mai multe.',
    EU_DESCRIPTION: {
      CTA_URL:
        'https://www.diplomatie.gouv.fr/en/coming-to-france/coronavirus-advice-for-foreign-nationals-in-france/coronavirus-statements/article/applying-for-a-covid-certificate-if-you-were-vaccinated-abroad-procedure-for',
      TEXT: 'Începând cu 21 iulie 2021, toți vizitatorii cu vârsta de 12 ani și peste trebuie să prezinte un certificat al UE privind COVID. ',
    },
    EU_HEADING: 'Certificat al UE privind COVID necesar',
    EU_PREFIX: 'Notă: ',
    EXPERIENCE_DESCRIPTION:
      'Această experiență a fost verificată pentru a respecta cele mai bune standarde de siguranță în conformitate cu reglementările locale și cu OMS',
    FLAG_TEXT: 'Cea mai bună siguranță',
    GENERAL_DESCRIPTION:
      'Orice experiență cu această insignă a fost verificată pentru a respecta cele mai bune standarde de siguranță, în conformitate cu orientările de sănătate ale guvernului local.',
    HEADING: 'Cele mai bune standarde de siguranță',
    IT_DESCRIPTION: {
      CTA_URL: 'https://www.dgc.gov.it/web/per-cosa-serve.html#viaggi',
      TEXT: 'Începând cu 6 august 2021, toți vizitatorii cu vârsta de 11 ani și peste trebuie să prezinte un Certificat verde sau un Certificat al UE privind COVID. ',
    },
    IT_PREFIX: 'Notă: ',
    MOBILE_HEADING: 'Experiențe sigure',
    MODAL: {
      BADGE_DESCRIPTION:
        'Această insignă de pe o experiență confirmă faptul că standardele de siguranță au fost verificate de noi',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Toate echipamentele, vehiculele și zonele de contact sunt dezinfectate după fiecare utilizare. Stați liniștit și bucurați-vă.',
          HEADING: 'Toate echipamentele și suprafețele sunt dezinfectate',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Toate echipamentele disponibile în timpul experienței dumneavoastră sunt dezinfectate temeinic după fiecare utilizare. Întotdeauna.',
          HEADING: 'Toate echipamentele și suprafețele sunt dezinfectate',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Toate vehiculele disponibile în timpul experienței dvs. sunt dezinfectate temeinic după fiecare utilizare. Întotdeauna',
          HEADING: 'Toate vehiculele sunt dezinfectate',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Pentru o experiență sigură, veți avea acces la stații de spălare a mâinilor și de igienizare pe tot parcursul perioadei petrecute aici. Suntem aici pentru dumneavoastră. ',
          HEADING:
            'Facilități de spălare a mâinilor și instalații sanitare disponibile în întreaga zonă',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Măștile sunt obligatorii pentru toți oaspeții și membrii personalului în această experiență. Acest lucru îi ajută pe toți să se distreze în condiții de siguranță maximă.',
          HEADING: 'Toată lumea poartă măști pentru siguranța dumneavoastră',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Partenerii noștri, care au fost verificați ca Experiențe Sigure, respectă regulile locale privind măștile. Dacă este obligatoriu, toți oaspeții și membrii personalului vor purta măști. Aceștia iau toate măsurile posibile pentru a vă asigura confortul și siguranța.',
          HEADING: 'Toată lumea poartă măști pentru siguranța dumneavoastră',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Măștile sunt obligatorii pentru toți oaspeții în această experiență. Acest lucru îi ajută pe toți să se distreze în condiții de siguranță maximă.',
          HEADING: 'Toată lumea poartă măști pentru siguranța dumneavoastră',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Toți membrii personalului de la această experiență poartă măști pentru a vă asigura că vă puteți distra fără să vă faceți griji.',
          HEADING: 'Toată lumea poartă măști pentru siguranța dumneavoastră',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Orientările privind distanțarea socială se aplică pe tot parcursul acestei experiențe. Există restricții de capacitate pentru a asigura distanțarea socială.',
          HEADING: 'Se respectă orientările privind distanțarea socială.',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Orientările privind distanțarea socială se aplică pe tot parcursul acestei experiențe. Există restricții de capacitate pentru a asigura distanțarea socială. În aceeași ordine de idei, nu sunt permise grupurile mari.',
          HEADING: 'Se respectă orientările privind distanțarea socială.',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'În cadrul acestei experiențe, se respectă în permanență orientările privind distanțarea socială.',
          HEADING: 'Se respectă orientările privind distanțarea socială.',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'În cadrul acestei experiențe, se respectă în permanență orientările privind distanțarea socială. Pentru a impune acest lucru, pot exista restricții de capacitate și limite de grup. Puteți respira ușurat.',
          HEADING: 'Se respectă orientările privind distanțarea socială.',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'În cadrul acestei experiențe, se respectă în permanență orientările privind distanțarea socială. În aceeași ordine de idei, nu sunt permise grupurile mari.',
          HEADING: 'Se respectă orientările privind distanțarea socială.',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Toți oaspeții își vor verifica temperatura la începutul experienței pentru a asigura siguranța tuturor. Toți membrii personalului sunt verificați de mai multe ori pe zi pentru temperatură ridicată.',
          HEADING: 'Sunt efectuate verificări ale temperaturii',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Toți oaspeții își vor verifica temperatura la începutul experienței pentru a asigura siguranța tuturor. ',
          HEADING: 'Sunt efectuate verificări ale temperaturii',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Toți membrii personalului sunt verificați de mai multe ori dacă au temperatură ridicată. Intrarea pentru orice membru care depășește limita prescrisă este restricționată și li se cere să rămână acasă pentru a se recupera.',
          HEADING: 'Sunt efectuate verificări ale temperaturii',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Personalul disponibil pe tot parcursul experienței este instruit în conformitate cu orientările OMS și echipat pentru a face față oricărei urgențe care le iese în cale',
          HEADING: 'Personalul este instruit cu privire la orientările OMS',
        },
      },
      HEADING: 'Experiențe sigure',
      SUB_HEADING:
        'Colaborăm cu partenerii noștri din întreaga lume pentru a pune în aplicare cele mai bune standarde de siguranță, în conformitate cu orientările OMS. Toate măsurile luate pe teren au fost verificate și afișate aici. Este timpul să ne bucurăm din nou de lumea din jurul nostru.',
    },
    NL_DESCRIPTION: {
      CTA_URL:
        'https://www.government.nl/topics/coronavirus-covid-19/covid-certificate',
      TEXT: 'Vizitatorii cu vârsta de 13 ani și peste trebuie să aibă (o copie digitală sau tipărită a) un Certificat COVID care arată că ați fost vaccinat, ați primit un rezultat negativ la test sau v-ați recuperat recent de la COVID-19. Purtarea unei măști de protecție este obligatorie. ',
    },
    SG_DESCRIPTION: {
      CTA_URL: 'https://safetravel.ica.gov.sg/health/vtsg',
      TEXT: 'Începând cu 13 octombrie 2021, doar vizitatorii complet vaccinați pot intra în grupuri de 2. Va trebui să prezentați dovada stării de vaccinare, un rezultat negativ recent al testului COVID-19 și/sau orice documentație de recuperare înainte de intrare. ',
    },
    SHORT_HEADING: 'Cele mai bune standarde de siguranță în vigoare',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Detalii de siguranță',
    EXPERIENCE_DESCRIPTION:
      'Această experiență a fost verificată pentru a respecta cele mai bune standarde de siguranță în conformitate cu reglementările locale și cu OMS',
    FLAG_TEXT: 'Cea mai bună siguranță',
    GENERAL_DESCRIPTION:
      'Această locație este SIGURĂ ÎN CONTEXTUL COVID-19 și respectă toate măsurile de siguranță recomandate de guvern pentru a vă asigura că aveți o experiență la teatru în siguranță și cu distanțare socială.',
    GENERAL_DESCRIPTION_V2:
      'Am dezvoltat marca larg răspândită „See it Safely”, astfel încât, atunci când teatrele se redeschid,  să vă puteți simți încrezători și în siguranță, știind că locația este sigură în contextul COVID-19 și va urma cele mai recente recomandări guvernamentale și ghidurile din domeniul artelor spectacolului.',
    HEADING: 'See it Safely',
    MOBILE_HEADING: 'Experiențe sigure',
    MORE_CURRENCIES: 'Mai multe monede',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Vor fi acceptate doar bilete tipărite la domiciliu și biletele electronice</li>',
          HEADING: 'Bilete electronice fără contact',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Echipamentele de protecție, cum ar fi măștile, sunt obligatorii pentru a intra în incintă</li>\n            <li>Toți spectatorii vor fi supuși unui control al temperaturii înainte de a intra în sală</li>',
          HEADING: 'Măsuri preventive de siguranță',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Echipamentele de protecție, cum ar fi măștile, sunt obligatorii pentru a intra în incintă</li>\n            <li>Toți spectatorii vor fi supuși unui control al temperaturii înainte de a intra în sală</li>',
          HEADING: 'Măsuri de igienizare',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Locul de desfășurare a fost reproiectat pentru a minimiza contactul între toți spectatorii</li>\n            <li>Grupurile diferite vor fi așezate separat</li>\n            <li>Comenzile prealabile pentru gustările de la pauză vor fi facilitate ori de câte ori este posibil</li>\n            <li>Se recomandă tranzacțiile fără numerar și fără hârtie.</li>\n            <li>Se solicită tuturor spectatorilor să aibă cât mai puține obiecte personale, deoarece facilitățile pentru depozitare ar putea fi închise.</li>\n            <li>Activitățile precum fotografierea cu artiștii sau semnarea de autografe pot fi restricționate</li>\n            ',
          HEADING: 'Măsuri de distanțare socială',
        },
      },
      HEADING: 'See it Safely',
      SUB_HEADING:
        'Vă întrebați ce se face pentru a vă menține în siguranță? Aflați mai multe despre măsurile de siguranță și protocoalele anti-COVID pe care teatrele le-au implementat pentru a vă asigura siguranța.',
    },
    SHORT_HEADING: 'Cele mai bune standarde de siguranță în vigoare',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Siguranța dumneavoastră este prioritatea noastră',
    TEXT: 'Am luat măsuri semnificative pentru a îmbunătăți curățenia folosind dezinfectanți și curățând frecvent și în profunzime suprafețele. Mulțimile sunt, de asemenea, controlate pentru a preveni aglomerația.',
  },
  SAVE: 'Economisiți {0}%',
  SAVE_PERCENT: 'Economisiți {0}%',
  SAVE_UPTO_PERCENT: 'Economisiți până la {0}%',
  SEE_ALL: 'Vezi toate',
  SEARCH: 'Căutare',
  POPULARITY: 'Popularitate',
  PRICE: 'Preț',
  SEE_MORE_SHOWS: 'Vedeți mai multe spectacole',
  SELECT_CITY: 'Selectați orașul',
  SELECT_SECTION: 'Selectați secțiunea',
  SEE_ALL_PHOTOS: 'Vedeți toate fotografiile',
  SHOW_CLOSED: 'Spectacol închis',
  SHOW_LESS: 'Arată mai puțin',
  SHOW_LESS_TEXT: 'Arată mai puțin',
  SHOW_MORE: 'Arată mai mult',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Despre spectacol',
    ABOUT_THEATRE: 'Despre teatru',
    ADDITIONAL_INFORMATION: 'Informații suplimentare',
    AGE_LIMIT: 'Limita de vârstă',
    AGE_SUITABILITY: 'Vârsta recomandată',
    CRITIC_REVIEW: 'Recenzie critică',
    ANSWER: ['A-'],
    BLOG_SHOW_PAGE: 'Blog Pagina spectacolului',
    BLOG_SUMMARY: 'Blog Rezumat',
    BLOG_THEATRE_PAGE: 'Blog Pagina teatrului',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Planul de așezare în teatru',
    CANCELLATION_AND_REFUNDS: 'Anulare și rambursări',
    CANCELLATION_POLICY: 'Politica de anulare',
    CAST_AND_CREW: 'Distribuție și echipă',
    CLOSING_DATE: 'Data de închidere',
    CLOSING_DATE_SPECIAL_OFFER: 'Ofertă specială pentru data de închidere',
    DURATION: 'Durata',
    FACILITIES_AND_ACCESSIBILITY: 'Facilități și accesibilitate',
    FREQUENTLY_ASKED_QUESTIONS: 'Întrebări frecvente',
    GETTING_THERE: 'Cum să ajungeți',
    GETTING_THERE_MAP_LINK: 'Cum să ajungeți Link la hartă',
    GOOGLE_MAP: 'Harta Google',
    HIGHLIGHTS: 'Repere',
    LISTICLE_SHOW_SUMMARY: 'Rezumatul spectacolului sub formă de listă',
    LISTICLE_SHOW_WHY_WATCH: 'Motive pentru a urmări sub formă de listă',
    OPENING_DATE: 'Data deschiderii',
    QUESTION: ['Q-'],
    SAFETY_BANNER: 'Banner de siguranță',
    SHOW_DETAILS: 'Arată detalii',
    SHOW_TIMINGS: 'Orele de spectacol',
    SHOW_TYPE: 'Tipul spectacolului',
    SPECIAL_OFFER: 'Ofertă specială',
    THE_STORY: 'Povestea',
    THEATRE_ADDRESS: 'Adresa teatrului',
    THEATRE_CAPACITY: 'Capacitatea teatrului',
    THEATRE_NAME: 'Numele teatrului',
    TICKETS: 'Bilete',
    TICKETS_REDEMPTION: 'Revendicarea biletelor',
    TOP_SONGS: 'Top melodii',
    YOUR_TICKETS: 'Biletele dumneavoastră',
    ABOUT_CONCERT: 'Despre Concert',
    PROGRAM: 'Program',
  },
  SORT_BY: 'Sortează după',
  SPECIAL_OFFER: 'Ofertă specială',
  THEATRE: 'Teatru',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Teatrele din apropiere',
    NOW_PLAYING: 'Acum rulează',
    UPCOMING_SHOWS: 'Spectacole viitoare',
    PAST_SHOWS: 'Spectacole anterioare',
    FIND_BEST_SEATS: 'Găsiți cele mai bune locuri',
  },
  TICKET_CAN_BE_CANCELED:
    'Puteți anula cu până la {ore} ore în avans pentru o rambursare integrală.',
  TICKET_CANNOT_BE_CANCELED:
    'Acest bilet nu poate fi anulat, dar poate fi reprogramat la cerere.',
  TICKETS: 'Bilete',
  TIMINGS: 'Ore',
  SPECIAL_PRODUCT_HEADING: 'Cel mai popular',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Ghid local specializat',
    ENGAGING_STORIES: 'Povești captivante',
    TOP_RATED: 'Recomandat',
  },
  GUIDED_TOUR_REVIEWS: [
    'Ghidul nostru, Angela, a fost minunată și foarte bine informată despre locație',
    'Ghidul a fost foarte bucuros să răspundă la întrebări despre tur',
    'Ghidul nostru a fost grozav și chiar ne-a dat o recomandare excelentă pentru prânz!',
    'Experiența a fost foarte plăcută datorită organizării și ghidului nostru',
    'Au fost multe informații educative, cu siguranță voi repeta experiența cu copiii mei.',
    'Turul a fost bine organizat și a avut o durată potrivită',
    'Ghidul nostru știa foarte bine ce are de spus și pasiunea sa pentru istorie era evidentă',
    'Ghid bun și organizare excelentă! Voi recomanda!!!!',
    'Detaliile interesante oferite de ghid ne-au ținut pe toți captivați și interesați.',
    'Turul a decurs într-un ritm bun și nu m-am simțit grăbit',
    'Ghidul nostru, Maria, a reușit să obțină locuri pentru cel mai bun punct de vizionare.',
    'Vizita noastră a fost îmbogățită de ghidul nostru dincolo de ceea ce am fi realizat pe cont propriu',
    'Tur detaliat și profund emoționant condus de un ghid pasionat',
    'Jeff ne-a arătat aspecte ale locației pe care altfel le-am fi ratat.',
  ],
  GUIDES_BANNER:
    'Explorați ca un localnic alături de ghizii noștri iubiți de oaspeți.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Cel mai bun mod de a profita la maximum de această destinație este să participați la un tur ghidat. Ghizii noștri specializați sunt aici să vă fie alături ca niște prieteni locali, împărtășind povești, secrete bine păstrate și recomandări de călătorie.',
    'Nu vă rezumați la vizită - trăiți experiența!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Ascultați opiniile oaspeților noștri',
  GUIDES: 'Ghizi',
  TODAY: 'Astăzi',
  TOMORROW: 'Mâine',
  TOUR_LIST_HEADING: 'Selectați experiența dumneavoastră',
  TOUR_LIST_SUB_HEADING:
    'Alegeți din mai multe opțiuni de bilete, tururi și pachete oferite de operatori verificați.',
  UGC: {
    FOLLOW: 'Urmăriți',
    FOLLOW_IG: 'Urmăriți pe Instagram',
    HEADING: 'POV: Așa arata următoarea ta aventură',
    SUB_HEADING: 'Selectată cu 💜 de Headout',
  },
  UNAVAILABLE: 'Indisponibil',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Aceste bilete sunt valabile pe o durată extinsă. Detaliile exacte vor fi menționate pe bilet.',
    UNTIL_DATE: 'Aceste bilete sunt valabile până la {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Aceste bilete sunt valabile timp de {0} zile de la data cumpărării.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Aceste bilete sunt valabile timp de {0} luni de la data cumpărării.',
  },
  TABLE_OF_CONTENTS: 'Cuprins',
  VIEW_LESS: 'Vezi mai puțin',
  VIEW_MORE: 'Vezi mai mult',
  WHY_TAKE_THIS_DAY_TRIP: 'De ce să faceți această excursie de o zi?',
  WHY_WATCH: 'De ce să urmăriți {0}?',
  FIND_ON_MAP: 'Găsiți pe hartă',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Bilete la casa de bilete',
        DESCRIPTION: 'Confirmatre instantanee pe telefon',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: 'Alegeți-vă locurile',
        DESCRIPTION: 'Vederea pe care o doriți, de fiecare dată',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Oferte și reduceri exclusive',
        DESCRIPTION:
          'Obțineți reduceri considerabile la cele mai tari spectacole din {0}.',
      },
      BOOK_AND_RELAX: {
        NAME: 'Rezervați și relaxați-vă',
        DESCRIPTION:
          'Încredere acordată de {0} de milioane de oaspeți și în continuă creștere.',
      },
    },
    YOUR_PICK: 'Alegerea dumneavoastră',
    BROWSE_BY_CATEGORIES: 'Navigați pe categorii',
    TOP_WEST_END_SHOWS: 'Cele mai bune spectacole din West End',
    TOP_THEATRE_SHOWS: 'Cele mai bune spectacole {0}',
    TOP_SHOWS: 'Cele mai bune spectacole',
    SEE_MORE_SHOWS: 'Vedeți {0} mai multe spectacole',
    LAST_MINUTE_TICKETS: 'Bilete de ultim moment',
    LOVED_BY_MILLIONS: 'Îndrăgit de milioane de oameni',
    TODAY: 'Astăzi',
    TOMORROW: 'Mâine',
    SEE_ALL: 'Vezi toate',
    GRAB_YOUR_TICKETS: 'Cumpărați bilete acum',
  },
  TAG_NAME: {
    BALLET: 'Balet',
    CABARET: 'Cabaret',
    CHRISTMAS: 'Crăciun',
    CIRCUS: 'Circ',
    CLASSIC: 'Clasic',
    COMEDY: 'Comedie',
    COMING_SOON: 'În curând',
    CRITICS_CHOICE: 'Alegerea criticilor',
    DANCE: 'Dans',
    DISNEY: 'Disney',
    DRAMA: 'Dramă',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantezie',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Teatru imersiv',
    JUKEBOX: 'Jukebox',
    KIDS: 'Copii',
    MAGIC: 'Magiie',
    MUSICALS: 'Musicaluri',
    NEW_ARRIVAL: 'Noutăți',
    OFF_WEST_END: 'Spectacole în afara West End',
    OLIVIER_WINNER: 'Câștigător alor premiilor Olivier',
    OPERA: 'Operă',
    PANTOMIMES: 'Pantomime',
    PLAYS: 'Teatru',
    ROMANCE: 'Romantism',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Vedete pe scenă',
    THEATRICAL_CONCERT: 'Concert teatral',
    TRUE_STORY: 'Poveste adevărată',
    TONY_WINNER: 'Câștigător al premiilor Tony',
    OFF_BROADWAY: 'Off Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Ups, avem o problemă',
    MESSAGE:
      'Ne pare rău! Toate experiențele pentru această dată sunt fie epuizate, fie\n    indisponibile. Dar avem o mulțime de alte spectacole disponibile la alte date. Tot\n    ce trebuie să faci este să fii flexibil.',
    CTA: 'Vedeți toate datele',
  },
  ALL_DATES: 'Toate datele',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Meniul principal',
    EXPLORE: 'Explorați',
    VISIT: 'Vizitați',
    THINGS_TO_DO: 'Lucruri de făcut',
    CITY_ATTRACTIONS: '{0} Atracții',
    TOP_THINGS_TO_DO: 'Cele mai bune lucruri de făcut',
    CITY_TOURS: '{0} Tururi',
    CITY_GUIDE: 'Ghidul orașului',
    ATTRACTIONS: 'Atracții',
    CRUISES: 'Croaziere',
    THEMES: 'Teme',
    ABOUT: 'Despre',
    TOURS: 'Tururi',
    SKIP_THE_LINE: 'Tururi skip-the-line',
    GUIDED_TOURS: 'Tururi ghidate',
    NIGHT_TOURS: 'Tururi de noapte',
    FOOD_TOURS: 'Tururi alimentare',
    HISTORY: 'Istorie',
    ARCHITECTURE: 'Arhitectură',
    DESIGN: 'Design',
    INSIDE: 'Interior',
    COLLECTIONS: 'Colecții',
    PAINTINGS: 'Picturi',
    ANIMALS_EXHIBITS: 'Animale și exponate',
    HABITATS: 'Habitate',
    CONSERVATION: 'Conservare',
    PROGRAMMES: 'Programe',
    A2_SIGHTSEEING_CRUISES: 'Croaziere de vizitare a obiectivelor turistice',
    A2_DINNER_CRUISES: 'Croaziere cu cină',
    A2_EVENING_CRUISES: 'Croaziere de seară',
    A2_LUNCH_CRUISES: 'Croaziere de prânz',
    A2_YACHT_TOURS: 'Excursii cu iahtul',
    PLAN_YOUR_VISIT: 'Planificați-vă vizita',
    TIMINGS: 'Ore',
    DIRECTIONS: 'Indicații',
    PARKING: 'Parcare',
    ROUTES: 'Rute',
    REQUIREMENTS: 'Cerințe',
    LOCATION: 'Locație',
    RULES: 'Reguli',
    FAQs: 'Întrebări frecvente',
    ENTRANCES: 'Intrări',
    RESTAURANTS: 'Restaurante',
    FACTS: 'Informații',
    TIPS: 'Sfaturi',
    MAP: 'Hartă',
    RIDES: 'Atracții',
    SHOWS: 'Spectacole',
    DINING: 'Mese',
    SHOPPING: 'Cumpărături',
    EVENTS: 'Evenimente',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Crăciun',
    NEW_YEARS_EVE: 'Ajunul Anului Nou',
    TRAVEL_GUIDE: 'Ghid de călătorie',
    TRIP_PLANNER: 'Planificator de călătorii',
    ITINERARY: 'Itinerar',
    TRAVEL_TIPS: 'Sfaturi de călătorie',
    WEATHER: 'Vremea',
    BEST_TIME_TO_VISIT: 'Cel mai bun moment pentru a vizita',
    JANUARY: 'Ianuarie',
    FEBRUARY: 'Februarie',
    MARCH: 'Martie',
    APRIL: 'Aprilie',
    MAY: 'Mai',
    JUNE: 'Iunie',
    JULY: 'Iulie',
    AUGUST: 'August',
    SEPTEMBER: 'Septembrie',
    OCTOBER: 'Octombrie',
    NOVEMBER: 'Noiembrie',
    DECEMBER: 'Decembrie',
    WHERE_TO_EAT: 'Unde să mâncați',
    WHERE_TO_STAY: 'Unde să stați',
    NEIGHBOURHOODS: 'Cartiere',
    FAMILY_TRAVEL: 'Călătorii de familie',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivaluri și evenimente',
  },
  BREADCRUMBS: {
    HOME: 'Acasă',
    TRAVEL_GUIDE: 'Ghid de călătorie',
    THINGS_TO_DO: 'Lucruri de făcut în {0}',
    SHOW_NAME_TICKETS: '{0} - Bilete',
    LTT_HOME: 'Bilete London Theatre',
    LTT_VENUE_PAGE_HOME: 'Teatre în Londra',
    BROADWAY_HOME: 'Bilete spectacole Broadway',
    BROADWAY_VENUE_PAGE_HOME: 'Teatre Broadway',
    VIENNA_CONCERT_HOME: 'Bilete concert Viena',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Săli de concerte în Viena',
    ATTRACTIONS: 'Atracții',
    A2_SIGHTSEEING_CRUISES: 'Croaziere de vizitare a obiectivelor turistice',
    A2_DINNER_CRUISES: 'Croaziere cu cină',
    A2_EVENING_CRUISES: 'Croaziere de seară',
    A2_LUNCH_CRUISES: 'Croaziere de prânz',
    A2_YACHT_TOURS: 'Excursii cu iahtul',
    LONDON_THEATRE_NEWS: 'Știri London Theatre',
    BROADWAY_SHOW_NEWS: 'Știri spectacole Broadway',
    NEWS_PAGE: 'Pagina de știri',
    REVIEWS_PAGE_BANNER_HEADING: '{0} comentarii',
  },
  AMENITIES: {
    Restaurant: 'Restaurant',
    Cafe: 'Cafenea',
    'Dedicated Parking': 'Parcare dedicată',
    Elevators: 'Ascensoare',
    Lift: 'Lift',
    'Wheelchair Accessible': 'Accesibil pentru scaune cu rotile',
    Cloakroom: 'Vestiar',
    'Air Conditioning': 'Aer condiționat',
    WiFi: 'WiFi',
    Bar: 'Bar',
    'Water Fountain': 'Fântână cu apă',
    Washrooms: 'Băi',
    Toilets: 'Toalete',
    Binoculars: 'Binoclu',
    'Adapted Toilets': 'Toalete adaptate',
    'Accessible Toilets': 'Toalete accesibile',
    'Assistive Listening System': 'Sistem de ascultare asistivă',
    'Hearing Assistance': 'Asistență auditivă',
    'Booster Cushions': 'Perne suplimentare',
    Shop: 'Magazin',
    'Souvenir Shop': 'Magazin de suveniruri',
    'Guide Dogs': 'Câini-ghid',
    'Baby Changing Facilities': 'Facilități pentru schimbarea bebelușilor',
    'Security Check': 'Control de securitate',
    Ramp: 'Rampă',
    'Level Access': 'Level Access',
  },
  CALENDAR: {
    FOOTNOTE: '* Toate prețurile sunt în {0}',
    PICK_DATE: 'Alegeți o dată',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Vedeți recenzia originală în {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Această recenzie este tradusă. Afișați recenzia originală.',
    TRANSLATE: 'Traducere recenzie în {0}',
    LANGUAGES: {
      EN: 'Engleză',
      ES: 'Spaniolă',
      FR: 'Franceză',
      IT: 'Italiană',
      DE: 'Germană',
      PT: 'Portugheză',
      NL: 'Olandeză',
    },
  },
  SHOW_PAGE_V2: {
    READ_MORE_REVIEWS: 'Citiți mai multe recenzii',
    SHOW_MORE_REVIEWS: 'Afișați mai multe recenzii',
    ALL_PHOTOS: 'Toate fotografiile',
    MORE_DATES: 'Mai multe date',
    SELLING_OUT_FAST: 'Vânzare rapidă',
    SELECT_TIME_SLOT: 'Selectați un interval orar',
    SELECT_TIME_SLOT_ERROR: 'Selectați un interval orar pentru a continua',
    PRICE_STARTING_FROM: 'Prețul locurilor începând de la',
    SELECT_SEATS: 'Selectați locurile',
    READ_MORE: 'Citiți mai mult',
    RATINGS_AND_REVIEWS: 'Evaluări și recenzii',
    READ_DETAILED_REVIEWS: 'Citiți recenzii detaliate',
    INTERVAL: 'Interval',
    TWO_PART_SHOW: 'Spectacol în două părți',
    UNTIL_DATE: 'Până la {0}',
    AVAILABLE_TIME: 'Interval orar disponibil',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Această experiență este disponibilă doar în perioada de mai jos',
    CONTENT_TABS: {
      ABOUT: 'Despre',
      VENUE: 'Locație',
      TICKETS: 'Bilete',
      Reviews: 'Recenzii',
    },
    SELECT_SHOW_TIMMING: 'Selectați ora spectacolului',
    ONLY_ONE_SLOT: 'Doar un singur interval orar disponibil la data selectată',
    SIMILAR_SHOWS: 'S-ar putea să vă placă și',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Povestea',
      WHAT_CRITICS_THINK: 'Ce cred criticii',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Întrebări frecvente despre {0}',
      AGE_SUITABILITY_AND_GUIDELINES: 'Ghid de vârstă și conținut',
      CAST_AND_CREATIVES: 'Distribuție și creatori',
    },
  },
  HOHO: {
    HOHO: 'Tururi Hop On Hop Off',
    BUS_ROUTES_DETAILS: 'Rute de autobuz',
    TOUR_DETAILS: 'Detalii despre tur',
    ROUTES_SCHEDULES: 'Rute și orare',
    VALIDITY: 'Valabil pentru 1 zi',
    VALIDITY_NOTE:
      'Experiența dumneavoastră este valabilă pentru {0} zi(e) calendaristică(e). Dacă vă rezervați biletul pentru 6 mai 2023, biletul va fi valabil până la 6 mai 2023, ora 21:00 PST.',
    BESTSELLER: 'Cel mai bine vândut',
    SEE_ALL: 'Vedeți toate',
    TIMINGS: 'ORE',
    FREQUENCY: 'FRECVENȚĂ',
    DURATION: 'DURATĂ',
    STARTING_LOCATION: 'Locația de pornire',
    CALENDAR_FOOTNOTE: '* Toate prețurile sunt în {0}',
    TOUR_TIMINGS: 'Orarul excursiilor',
    TOUR_FREQUENCY: 'Frecvența tururilor',
    GOT_IT: 'Am înțeles',
    SELECT_DATE: 'Selectați o dată',
    SELECT_TOUR: 'Selectați tipul de tur',
    VIEW_TOUR_DETAILS: 'Vedeți detaliile turului',
    BUS_DETAILS: 'Mai multe detalii',
    VIEW_ROUTES: 'Vedeți toate rutele',
    BUS_ROUTES: 'Rute de autobuz',
    ATTRACTIONS_PREVIEW:
      'Cea mai rapidă modalitate de a vedea {0}+ atracții de top, inclusiv',
    ROUTES: 'Rute',
    COMBO_SUBTITLE: 'Economisiți mai mult cu',
    COMBO_TITLE: 'Oferte combo pentru turul Hop-on Hop-off',
    COMBO_DWEB_TITLE:
      'Economisiți mai mult cu ofertele combo pentru turul Hop-on Hop-off',
    STOPS_AND_ATTRACTIONS: 'Opriri și atracții din apropiere',
    HOP_ON_OFF_AT: 'Urcați și coborâți la oricare dintre aceste {0} opriri',
    TIMINGS_FREQUENCY: 'Orar și frecvență ',
    TOUR_DURATION: 'Durata turului',
    EVERY_X_MINS: 'La fiecare {0}',
    VIEW_LOCATION: 'Vedeți locația',
    BANNER_SUBTEXT:
      'Cea mai convenabilă și rapidă modalitate de a vedea toate atracțiile de top din oraș.',
    TOP_ATTRACTIONS: 'Sunt acoperite atracțiile principale',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Rezervare de ultim moment',
        DESCRIPTION: 'Confirmatre instantanee pe telefon',
      },
      COST_EFF: {
        NAME: 'Explorare la cost redus',
        DESCRIPTION: 'Mai multe obiective turistice, un singur bilet ',
      },
      DAILY_RIDES: {
        NAME: 'Curse zilnice nelimitate',
        DESCRIPTION: 'Descoperiți orașul în ritmul dumneavoastră',
      },
      BOOK_RELAX: {
        NAME: 'Rezervați și relaxați-vă',
        DESCRIPTION: 'De încredere pentru {0} de milioane de oaspeți',
      },
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Ghizi specializați, multilingvi',
    STL: 'Acces skip-the-line',
    PERSONALIZED: 'Experiență personalizată',
    LOCAL_FOOD: 'Mâncare și cultură locală',
    MULTILINGUAL_GUIDES: 'Ghizi multilingvi',
    CULINARY_EXPERTS: 'Experți culinari',
    SIGHTSEEING: 'Vizitarea obiectivelor turistice și divertisment la bord',
    SIGHTSEEING_MEAL:
      'Opțiuni de vizitare a obiectivelor turistice și mese la bord',
    MULTILINGUAL_GT: 'Tururi ghidate în mai multe limbi',
    AUDIOGUIDE_COMMENTARY: 'Audioghid și comentarii disponibile',
    ALL_TOP_ATTRACTIONS_COVERED: 'Sunt acoperite toate atracțiile principale',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Program normal. Călătorii nelimitate',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Disponibilitate de ultim moment. Confirmare instantanee',
    MULTI_ROUTES: 'Opțiuni multiple de traseu',
    HASSLE_FREE: 'Rezervare fără probleme',
    FREQUENT_DEPARTURES: 'Plecări frecvente',
    ONBOARD_AMENITIES: 'Cele mai bune facilități la bord',
    FLEXI_TRAVEL: 'Călătorii flexibile pe rute multiple',
    FLEXI_EXCHANGE_CANCEL: 'Schimburi și anulări flexibile',
    EXTRA_DISCOUNT: 'Reduceri suplimentare pentru tineri, seniori și familii',
    PREPAID: 'Confort preplătit',
    EASY_ACTIVATION: 'Activare ușoară',
    INSTANT_CONNECTIVITY: 'Conectivitate instantanee cu acoperire globală',
    ROUND_TRIP: 'Transferuri dus-întors',
    CULTURAL_EXPERIENCE: 'Experiențe culturale autentice',
    GUARANTEED_SEAT: 'Scaun garantat',
    ONBOARD_WIFI: 'Wi-Fi și porturi de încărcare la bord',
    LUGGAGE_ASSISTANCE: 'Asistență pentru bagaje',
    TOP_ATTRACTIONS: 'Principalele atracții incluse',
    FREQ_DEP_MULTI_ROUTE: 'Plecări frecvente pe mai multe rute',
    CHARGING: 'Stație de încărcare',
    WIFI: 'Acces Wi-Fi',
    FnB: 'Disponibilitate F&B',
    LUXURY: 'Experiență de lux',
    FOOD_DRINK: 'Mâncare și băuturi',
    PANAROMIC: 'Priveliști panoramice ale atracțiilor principale',
    PANAROMIC_2: 'Priveliști panoramice',
    PANAROMIC_3: 'Priveliști panoramice, acoperiș deschis',
    BEVERAGES: 'Băuturi la bord',
    GOURMET: 'Cină gourmet',
    GOURMET_2: 'Cină gourmet și băuturi',
    NIGHTTIME: 'Priveliști uimitoare pe timp de noapte',
    ROMANTIC: 'Atmosferă romantică',
    TRANSFERS: 'Transferuri incluse',
    CERTIFIED_OP: 'Operațiuni certificate',
    BIRD_EYE: 'Priveliște de la înălțime',
    MULTI_JUMP: 'Timpuri de salt multiple',
    EXTREME_ADV: 'Aventură extremă',
    PHOTO_OP: 'Oportunități pentru fotografii pitorești',
    TOP_ATTRACTIONS_COVERED: 'Sunt acoperite atracțiile principale',
    LOCAL_CULTURE: 'Experimentați cultura locală',
    EXCLUSIVE_DISC: 'Reduceri exclusive',
    EFFICIENT_PUBLIC_TRANSIT: 'Transport în comun eficient',
    FREQUENT_SERVICE: 'Servicii frecvente',
    PREBOOKING: 'Pre-rezervare ușoară',
    LOCAL_CULTURE_IMM: 'Imersiune în cultura locală',
    DISCOVER_HIDDEN: 'Descoperiți locuri ascunse',
    CITY_SIGHTSEEING: 'Vizitarea orașului',
    OFFBEAT_ADV: 'Aventură neconvențională',
    DRINK_DEALS: 'Oferte pentru băuturi',
    OFFBEAT_EXP: 'Experiență neconvențională',
    MULTIPLE_VARIETIES: 'Diverse varietăți incluse',
    HIDDEN_GEMS: 'Comori ascunse și atracții neconvenționale',
    EXPLORE_LOCAL: 'Explorați cartierele locale',
    CUSTOMIZED_TREATMENTS: 'Tratamente personalizate',
    TRAINED_THERAPISTS: 'Terapeuți instruiți',
    HOLISTIC_WELLNESS: 'Wellness holistic',
    FLEXIBLE_DURATION: 'Durată flexibilă',
    MULTI_BOAT: 'Mai multe opțiuni de bărci',
    SCENIC_ROUTES: 'Rute pitorești',
    HANDS_ON: 'Învățare practică',
    CULTURAL_CULINARY: 'Perspective culturale și culinare',
    EXPERT_HOSTS: 'Gazde specializate',
    ADVENTURE_EXPERIENCE: 'Experiență de aventură',
    EQUIPMENT: 'Echipament inclus',
    SCENIC_FLYOVERS: 'Pasarele panoramice',
    LIVE_COMMENTARY: 'Comentariu în direct',
    BEST_AERIAL_VIEWS: 'Cele mai bune priveliști aeriene',
    SAFE_CERT_OP: 'Operațiuni sigure și certificate',
    HANDPICKED: 'Tururi alese cu grijă',
    EFFORTLESS: 'Planificare fără efort',
    EXPERT_GUIDES: 'Ghizi specializați. Perspective unice',
    ALL_ATTR_ONE_CARD: 'Toate atracțiile, un singur card',
    MULTI_CARD: 'Opțiuni multiple de carduri',
    COST_EFF: 'Rentabil și convenabil',
    BEST_PRICES: 'Cele mai bune prețuri',
    MULTI_TRANSPORT: 'Opțiuni multiple de transport',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Toate',
    POPULAR_SUBCATEGORY: 'Populare {0}',
    TOP_CATEGORY: 'Top {0}',
    ATTRACTIONS: 'Atracții',
    ALL_SUBCATEGORY: 'Toate {0}',
    BROWSE_BY_CATEGORIES: 'Răsfoiți pe categorii',
    TICKETS_FROM: 'Bilete de la',
    PRICE_LOW_HIGH: 'Preț (de la cel mai mic la cel mai mare)',
    PRICE_HIGH_LOW: 'Preț (de la cel mai mare la cel mai mic)',
    FILTERS: 'Filtre',
    RESET: 'Resetare',
    APPLY: 'Aplicați',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout folosește cookie-uri pentru a vă îmbunătăți experiența pe site, octet cu octet.',
    MOBILE: 'Modulele cookie funcționează',
    LEARN_MORE: 'Aflați mai multe.',
  },
  SHOW_UNAVAILABLE: 'Arată indisponibil',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Știri recomandate',
    ALL_NEWS: 'Toate știrile',
    MORE_READS: 'Citiți mai mult',
    LOAD_MORE: 'Încărcați mai mult',
    TRAILERS: 'Trailere',
    GET_YOUR_TICKETS: 'Cumpărați biletele',
    POPULAR_SHOWS: 'Spectacole populare',
    FEATURED: 'Recomandate',
    RECENT_NEWS: 'Știri recente',
    SHOW_MORE_ARTICLES: 'Arată mai multe articole',
    COLLAPSE_ALL: 'Închideți tot',
    REVIEWS: 'Recenzii',
    SHOW_ALL_REVIEWS: 'Afișați toate recenziile',
    MAILER: {
      HEADING:
        'Cele mai bune oferte de teatru și știri direct în căsuța ta de e-mail',
      SUBHEADING:
        'Înscrieți-vă pe lista noastră de corespondență pentru a primi cele mai recente știri și cele mai tari oferte la spectacolele de teatru.',
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: '{0} comentarii',
    REVIEWS_COUNT: '{0} recenzii',
    AWESOME: 'Minunat',
    GOOD: 'Bun',
    AVERAGE: 'Mediu',
    POOR: 'Slab',
    TERRIBLE: 'Teribil',
    REVIEW_BY_HEADOUT: 'Iată ce credem noi: Recenzia Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Ce spun oamenii',
    MOST_RELEVANT: 'Cele mai relevante',
    RATING_HIGH_TO_LOW: 'Rating: De la mare la mic',
    RATING_LOW_TO_HIGH: 'Rating: De la mic la mare',
    CRITIC_REVIEWS: 'Recenzii ale criticilor',
    USER_REVIEWS: 'Recenzii ale utilizatorilor',
    CONTRIBUTORS_REVIEW: 'Recenzia colaboratorului',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Transferuri private',
    SHARED_TRANSFERS: 'Transferuri în comun',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Rezervați online',
        DESCRIPTION:
          'Bucurați-vă de o experiență de rezervare rapidă și convenabilă prin rezervarea biletelor online.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Confirmare instantanee',
        DESCRIPTION:
          'Obțineți o confirmare instantanee la rezervarea biletului de transfer de la aeroport.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Ridicare convenabilă',
        DESCRIPTION:
          'Evitați problemele legate de cozile lungi, deoarece vehiculul de transfer vă va aștepta la punctul de preluare selectat.',
      },
      DROP_OFF: {
        TITLE: 'Punct de coborâre',
        DESCRIPTION: 'Ajungeți la destinație într-un mod rapid și confortabil.',
      },
    },
    SHARED_TRANSFERS_IN: 'Transferuri în comun în {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      ' O opțiune de transport confortabilă și rentabilă pentru mai mulți pasageri care călătoresc spre sau de la un aeroport.',
    PRIVATE_TRANSFERS_IN: 'Transferuri private în {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      ' Un serviciu de transport convenabil și personalizat pentru persoane fizice sau grupuri mici, care oferă o călătorie confortabilă și directă către și de la un aeroport.',
    ANYWHERE_IN_THE_CITY: 'Oriunde în oraș',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Opțiuni multiple pentru vehicule',
      FREE_CANCELLATION: 'Anulare gratuită',
    },
    SEAMLESS_TRANSFERS:
      'Transferuri fără întreruperi, de încredere în întreaga lume',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Alegeți transferul de la aeroport care vi se potrivește',
    HASSLE_FREE_TRANSFER: 'Experiență de transfer de la aeroport fără probleme',
    EFFORT_LESS_AIRPORT_TRANSFERS:
      'Transferuri ușoare de la aeroport în {0} cu ',
    BUSES: 'autobuzul',
    TRAINS: 'trenul',
    PRIVATE_TAXIS: 'taxi privat',
    BUS_TRAIN: 'Autobuz/tren',
    PRIVATE_TAXI: 'taxi privat',
    FROM: 'De la',
    SELECT_PICKUP: 'Selectați punctul de preluare',
    TO: 'La',
    SELECT_DROPOFF: 'Selectați punctul de destinație',
    ENTER_DESTINATION: 'Introduceți destinația',
    ENTER_PICKUP: 'Introduceți locația de preluare',
    PICKUP_DATE: 'Data preluării',
    SELECT_DATE: 'Selectați o dată',
    PICKUP_TIME: 'Ora preluării',
    SELECT_TIME: 'Selectați ora',
    GUEST: 'Oaspete',
    GUESTS: 'Oaspeți',
    ADD_GUESTS: 'Adăugați oaspeți',
    ADULT_CHILD: 'Adult/copil',
    EXPLORE_TRANSFERS: 'Explorați transferuri și altele',
    COMBOS_AND_EXTRAS: 'Pachete combo și extraopțiuni',
    YOUR_RIDE_DOORSTEP: 'Cursa vă așteaptă la ușă',
    COMFORTABLE_RIDE:
      'Rezervați un taxi privat confortabil care să vă ducă către aeroporturile principale din {0} ',
    TRUSTED_DRIVERS: 'Șoferi de încredere',
    RIDES_24_7: 'Curse disponibile 24/7',
    FLIGHT_TRACKING: 'Urmărirea zborului',
    KNOW_MORE: 'Aflați mai multe',
    RESERVE_YOUR_RIDE: 'Rezervați cursa',
    TRANSFER_OPTIONS: 'Opțiuni de transfer găsite',
    TRANSFERS_AVAILABLE_PLURAL: '{0} transferuri disponibile',
    TRANSFERS_AVAILABLE_SINGULAR: '1 transfer disponibil',
    TRUSTED_PARTNERS: '35+ parteneri de încredere, {0}',
    WORLDWIDE: 'la nivel mondial',
    COMFORTABLE_RIDES: 'Curse confortabile',
    FREQUENT_DEPARTURES: 'Plecări frecvente',
    MULTIPLE_TRANSPORT_OPTIONS: 'Opțiuni multiple de transport',
    AND_MANY_MORE: 'Și multe altele',
    ADD_PICKUP_LOCATION: 'Adăugați locația de preluare',
    ADD_DROPOFF_LOCATION: 'Adăugați locația de destinație',
    SELECT_PICKUP_DATE_AND_TIME: 'Selectați data și ora',
    SELECT_A_DATE: 'Selectați o dată',
    TRAIN_STATION: 'Stația de tren',
    BUS_STOP: 'Stația de autobuz',
    ADD_RETURN: 'Adăugați retur',
    HEADS_UP: 'Atenție!',
    ADDED_RETURN_TRIP: 'Ați adăugat un drum retur!',
    RETURN_NOTE:
      'Vă rugăm să rețineți, vom afișa detaliile drumului retur în pașii următori. ',
    OKAY_I_UNDERSTAND: 'Ok, am înțeles',
    SERVING_GUESTS: 'Servim {0} în {1} la nivel global',
    GUESTS_COUNT: 'Peste 220.000 de oaspeți',
    CITIES_COUNT: 'Peste 55 de orașe',
    PARNTER_WITH_BEST:
      'Colaborăm doar cu cei mai buni, pentru a ne asigura că veți avea o experiență de neuitat. Lăsați-ne să ne ocupăm de detalii — în timp ce dumneavoastră vă relaxați și vă bucurați de călătorie',
  },
  PC_EXP: {
    SHOW_INCL: 'Afișează includerile și informații importante',
    CLEAR: 'Ștergeți',
    ALL_EXPERIENCES: 'Toate experiențele',
    FILTER_BY_CATEGORIES: 'Filtrați după categorii',
    CATEGORIES: 'Categorii',
    COMBOS: {
      HEADING:
        'Toate lucrurile bune vin în perechi. La fel și pachetele noastre economice.',
      DESCRIPTOR_1: 'Oferte',
      DESCRIPTOR_2: 'Planificați-vă mai bine călătoria',
    },
  },
  TOP: 'Cele mai bune {0}',
  VIEW_CALENDAR: 'Vizualizare calendar',
  SHOWS_CALENDAR: 'Afișare calendar',
  IN: 'în',
  SEATS: 'Locuri',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Ghid de conținut',
    QUICK_INFORMATION: 'Informații rapide',
    PEAK: 'Vârf',
    OFF_PEAK: 'În afara orelor de vârf',
    ADDRESS: 'ADRESA',
    RECOMMENDED_DURATION: 'DURATA RECOMANDATĂ',
    VISITORS_PER_YEAR: 'VIZITATORI PE AN',
    NUMBER_OF_ENTRANCES: 'NUMĂRUL DE INTRĂRI',
    EXPECTED_WAIT_TIME_STANDARD: 'TIMPUL DE AȘTEPTARE PRECONIZAT - STANDARD',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE:
      'TIMPUL DE AȘTEPTARE PRECONIZAT - SKIP THE LINE',
    UNESCO_YEAR: 'ANUL UNESCO',
    ARCHITECTURE_STYLE: 'STIL DE ARHITECTURĂ',
    TIMINGS: 'Ore',
    SIZE_HEIGHT: 'DIMENSIUNE/ÎNĂLȚIME',
    TICKETS: 'BILETE',
    FUN_FACTS: 'Detalii interesante',
    DID_YOU_KNOW: 'Știați că?',
    MORE_INTERESTING_FACTS: 'Mai multe informații interesante',
    PLAN_YOUR_VISIT: 'Planificați-vă vizita',
    ALSO_KNOWN_AS: 'De asemenea, cunoscut sub numele de',
    FOUNDED_ON: 'Fondat la data de',
    FOUNDED_BY: 'Fondat de către',
    FROM: 'De la',
    CLOSED_TODAY: 'Închis astăzi',
    TODAY: 'Astăzi',
    CLOSED: 'Închis',
    OPEN: 'Deschis',
    LAST_ADMISSION: 'Ultima admitere',
    DAYS: 'Zile',
    BEST_TIME_TO_VISIT: 'Cel mai bun moment pentru a vizita',
    WEEKDAY_VS_WEEKEND: 'În timpul săptămânii vs. weekend',
    PEAK_VS_LOW_SEASON: 'Sezonul de vârf vs. extrasezon',
    PLEASANT: 'Plăcut',
    CROWDED: 'Aglomerat',
    VERY_CROWDED: 'Foarte aglomerat',
    LOW_SEASON: 'Extrasezon',
    MID_SEASON: 'Sezon moderat',
    PEAK_SEASON: 'Sezon de vârf',
    TO: 'CĂTRE',
    LOWER_TO: 'către',
    LAST_ENTRY: 'ultima intrare',
    SUBATTRACTIONS: 'Subatracții',
    INCLUDED_WITH_TICKETS: 'Inclus cu biletele {0}',
    INCLUDED_WITH_SOME_TICKETS: 'Inclus cu anumite bilete {0}',
    EXPLORE_ALL_POI_TICKETS: 'Explorați bilete și tururi pentru {0} și {1}',
    EXPLORE_PARENT_TICKETS: 'Explorați bilete și tururi',
    SELECT_YOUR_EXPERIENCE: 'Selectați experiența',
    OPERATING_HOURS: 'Ore de funcționare',
    SEE_MORE: 'Vedeți mai multe',
    MORE_INSIGHTS: 'Mai multe informații',
  },
  OFF_PERCENT: 'reducere de {0}%',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Planul de locuri',
    CAPACITY: 'Capacitate: {0} locuri',
    WHATS_ON: 'Ce rulează',
    CATEGORIES: 'Categorii',
  },
  NEXT: 'Înainte',
  PREVIOUS: 'Înapoi',
  ITINERARY: {
    TAB: 'Itinerar',
    HEADING: 'Itinerariul experienței',
    VIEW_ITINERARY: 'Vizualizare itinerariu',
    PASSES_BY_SECTION_HEADING: 'Trece pe lângă',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Repere',
      NEARBY_THINGS_TO_DO: 'Lucruri de făcut în apropiere',
      THINGS_TO_DO: 'Lucruri de făcut',
    },
    STOP_CARD: {
      TITLE: {
        START: 'PUNCT DE PORNIRE',
        END: 'PUNCT DE OPRIRE',
        STARTING_POINT: 'PUNCT DE PORNIRE',
        STOP: 'OPRIRE',
        ENDING_POINT: 'PUNCT DE OPRIRE',
        PASSING_BY: 'TRECE PE LÂNGĂ',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} puncte de pornire disponibile',
        END: '{0} puncte de oprire disponibile',
      },
    },
    GET_DIRECTION: 'Obțineți indicații',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} ore {1} minute',
        WITHOUT_HOURS: '{0} minute',
        WITHOUT_MINS: '{0} ore',
      },
      ATTRACTIONS_COUNT: '{0} atracții',
      ACTIVITIES_COUNT: '{0} activități',
      TOTAL_DURATION: 'DURATA TOTALĂ',
      FREQUENCY: 'FRECVENȚĂ',
      FIRST_DEPARTURE: 'PRIMA PLECARE',
      LAST_DEPARTURE: 'ULTIMA PLECARE',
      FIRST_DEPARTURE_TIME: 'ORA PRIMEI PLECĂRI',
      LAST_DEPARTURE_TIME: 'ORA ULTIMEI PLECĂRI',
      MODE_OF_TRANSPORT: 'MODALITATEA DE TRANSFER',
      FOOD_AND_DRINKS: 'MÂNCARE ȘI BĂUTURI',
    },
    WALK_DURATION: '{0} plimbare',
    MORE: '{0} altele',
    TIMELINE_VIEW: 'Cronologie',
    MAP_VIEW: 'Hartă',
    MAP_OVERLAY: 'Folosiți CTRL/⌘ + derulare pentru a mișca harta',
    VIEW_EXPERIENCE_MAPPED_OUT: 'Vizualizați întreaga experiență pe hartă.',
    OPEN_MAP_VIEW: 'Deschidere hartă',
    START_POINT_SAME_AS_END_POINT:
      'Punctul de oprire va fi același cu punctul de pornire ',
  },

  CITY_AIRPORT_TRANSFERS: 'Transferuri de la aeroport {0}',
  BANNER_SUBTEXT:
    'Bucurați-vă de o călătorie fără stres cu un transfer de la aeroport de încredere, rezervat în prealabil.',
  BEST_PRICES: 'Cele mai bune prețuri, fără taxe ascunse.',
  BEST_PRICES_SUBTEXT:
    'Prețuri fixe, fără surprize, care vă oferă tarife competitive pentru servicii premium.',
  FREE_WAIT_TIME: 'Timp de așteptare gratuit, fără grabă',
  FREE_WAIT_TIME_SUBTEXT:
    'Beneficiați de un timp de așteptare gratuit de 45 de minute în timp ce vă revendicați bagajele',
  COMFORTABLE_RIDE: 'Curse confortabile',
  COMFORTABLE_RIDE_SUBTEXT:
    'Călătoriți cu stil cu o flotă de vehicule de clasă superioară, conduse de șoferi atent selecționați și instruiți.',
  EXCELLENCE_HEADING: 'Un palmares de excelență și încredere',
  ACTIVE_CITIES: 'orașe active, din toată lumea',
  CUSTOMERS_SERVED: 'clienți deserviți',
  YEARS_OF_SERVICE: 'ani de servicii excelente',
  FIND_YOUR_RIDE: 'Găsiți mașina perfectă',
  FIND_YOUR_RIDE_SUBTEXT:
    'De la microbuze pentru familii până la berline de lux, alegeți mașina care se potrivește cu bagajele și mărimea grupului dvs.',
  TRUST_TOOLTIP_HEADER: 'Cum colectăm recenziile?',
  TRUST_TOOLTIP_CONTENT:
    'Aceste evaluări includ recenzii verificate atât de la oaspeții Headout, cât și de la partenerii noștri de încredere la nivel local. Toate recenziile provin de la călători reali.',
  REVIEW_SECTION_HEADER: 'Ce spun oaspeții noștri',
  TRUST_VB_TAG: 'Rezervare verificată',
  AGGREGATED_COUNTRIES:
    'Oaspeții din <strong>{0}</strong> și <strong>peste {1} țări</strong> au apreciat această experiență',
  REVIEW_SECTION: {
    HEADING: 'Millions love heading out with us',
    SORTING: {
      MOST_RELEVANT: 'Cel mai relevant',
      MOST_RECENT: 'Cel mai recent',
      SORT_BY: 'Sortare după',
    },
    FILTERING: {
      GREATER_THAN_4: '4+ stele',
      EQUAL_TO_3: '3 stele',
      LESS_THAN_3: '< 3 stele',
      WITH_IMAGES: 'Cu imagini',
    },
    EMPTY_STATE: {
      SUB_HEADING: 'Nu am găsit recenzii care să corespundă filtrelor.',
      CTA: 'Toate recenziile',
    },
    VERIFIED_REVIEW: 'Recenzie verificată a partenerului',
  },
  POWERED_BY: 'furnizat de',
};

export default ro;
