const sv = {
  AUDIO_GUIDE: {
    BANNER: 'Kostnadsfri ljudguide',
    PRODUCT_SUFFIX: 'med ljudguide',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Auktoriserad och pålitlig partner',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Auktoriserad återförsäljare',
    SUB_TEXT: 'Autentiska upplevelser från pålitliga och verifierade partners.',
  },
  REVIEWS: 'recensioner',
  AVAILABLE: 'Tillgänglig',
  BACK: 'Tillbaka',
  BANNER_CTA: 'Köp biljetter',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout är varumärket som miljontals resenärer över hela världen litar på och som erbjuder skräddarsydda upplevelser.',
    NON_PARTNERED_SENSITIVE:
      'Headout är varumärket som miljontals resenärer över hela världen litar på och som erbjuder skräddarsydda upplevelser. Detta är inte resmålets webbplats.',
    PARTNERED_NON_SENSITIVE:
      'Headout är en auktoriserad och pålitlig partner till resmålet och erbjuder skräddarsydda sätt att uppleva det på.',
    PARTNERED_SENSITIVE:
      'Headout är en auktoriserad och pålitlig partner till resmålet och erbjuder skräddarsydda sätt att uppleva det på. Detta är inte resmålets webbplats.',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout är en auktoriserad och pålitlig partner till resmålet och erbjuder ett urval av de bästa sätten att uppleva sevärdheterna på.',
  BOOK_NOW_CTA: 'Boka nu',
  BOOSTERS: {
    MOST_LOVED: 'Most loved',
    SPECIAL_DEAL: 'Special deal',
    HEADOUT_EXCLUSIVE: 'Endast hos Headout',
  },
  BUY_TICKETS_CTA: 'Köp biljetter',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Du kan avboka dessa biljetter fram till {0} timmar innan upplevelsen börjar och få full återbetalning.',
    CANCELLABLE_ANYTIME: 'Fri avbokning när som helst innan upplevelsen börjar',
    CANCELLABLE_DAYS:
      'Du kan avboka dessa biljetter fram till {0} dagar innan upplevelsen börjar och få full återbetalning.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Dessa biljetter kan inte avbokas. De är dock giltiga under en längre tidsperiod.',
    HEADING: 'Policy för ändringar',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Dessa biljetter kan inte avbokas. De kan dock ombokas upp till {0} timmar innan upplevelsen börjar.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Dessa biljetter kan inte ställas in eller flyttas.',
    VALID_UNTIL_DATE:
      'Dessa biljetter kan inte avbokas. Du kan dock använda dem när som helst fram till {0}.',
    VALID_WITHIN_NEXT_DAYS:
      'Dessa biljetter kan inte avbokas eller flyttas. Du kan dock använda dem när som helst inom de närmaste {0} dagarna.',
    VALID_WITHIN_NEXT_MONTHS:
      'Dessa biljetter kan inte avbokas eller flyttas. Du kan dock använda dem när som helst inom de närmaste {0} månaderna.',
  },
  CANCELLATION_POLICY_HEADING: 'Avbokningsregler',
  CASHBACK: '{0} % återbetalning',
  CASHBACK_INFO:
    'Du får <strong>{0} %</strong> tillbaka när du bokar upplevelsen. Din återbetalning krediteras automatiskt till ditt Headout-konto och kan användas för framtida bokningar på Headout.',
  CATEGORY_SLIDER_HEADING:
    'Kunder som bokade denna föreställning tittade också på',
  CHECK_AVAIL: 'Kontrollera tillgänglighet',
  SELECT_SEATS: 'Välj platser',
  CITY_PAGE: {
    BANNER_TITLE: 'Upplev det bästa av',
    TOP_ATTRACTIONS: 'De bästa sevärdheterna',
    GO_BEYOND: 'Gå bortom {0}',
    ALL_DAY_TRIPS: 'Se alla dagsutflykter',
    CITIES_NEARBY: 'Närliggande städer',
    POPULAR_CATEGORIES: 'Populära kategorier',
    GO_TO_GUIDE: 'Din bästa guide till {0}',
    VIEW_TRAVEL_GUIDE: 'Visa reseguiden',
    EXPLORE: 'Utforska {0}',
    GUIDE_SUBHEADING:
      'Det har aldrig varit enklare att utforska {0}! Vår reseguide i {0} vet allt du behöver veta om staden – från vad du ska äta och vad som är sevärt till hur du tar dig dit, var du ska bo och mycket mer!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Allmän information',
      WHERE_TO_EAT: 'Vad ska jag äta?',
      WHERE_TO_STAY: 'Var ska jag bo?',
      THINGS_TO_DO: 'Vad ska jag göra?',
      WEATHER: 'Bästa tiden att besöka',
      NEIGHBOURHOODS: 'Lokalsamhället',
      TRANSPORTATION: 'Hur tar jag mig runt?',
      TRIP_PLANNER: 'Reseplan',
      FAMILY_TRAVEL: 'Resa med barn',
      TRAVEL_TIPS: 'Restips och knep',
      SHOPPING: 'Shopping',
      ART_AND_CULTURE: 'Konst och kultur',
    },
    MAILER: {
      HEADING: 'Reseinspiration för {0} direkt i din inkorg',
      SUBHEADING:
        'Utforska nya städer med skräddarsydda upplevelser, omedelbar cashback, exklusiva erbjudanden och viktiga restips!',
    },
  },
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Vi använder cookies och liknande teknik för många ändamål, bland annat i syfte att förbättra din upplevelse på vår webbplats och för annonser.',
    MANAGE_PREFERENCES: 'Hantera',
    PREFERNCES_SAVED: 'Dina inställningar har sparats',
    COOKIES: 'Cookies:',
    ACCEPT: 'Okej',
    ALLOW_ALL: 'Tillåt alla',
    DENY_ALL: 'Avvisa alla',
    HEADING: 'Vi värdesätter alltid din integritet',
    DESCRIPTION:
      '*   Cookies är små filer som placeras på din dator, mobila enhet eller någon annan enhet av webbplatsen/plattformen och som innehåller information om din webbhistorik och många andra användningsområden.\n*   Vi använder olika typer av cookies till att spåra din användning av vår plattform och lagra viss information som hjälper oss att ge dig mer personliga tjänster. Vissa cookies kan placeras på din enhet till följd av din användning av tjänster som är tillgängliga på vår plattform.\n*   I stort sett använder vi två olika uppsättningar teknik under denna rubrik:\n    *   **Cookies eller webbläsarcookies.** Det är en liten fil som placeras automatiskt på din enhet när du går in på vår plattform. Du kan instruera din webbläsare att neka alla cookies. Om du inte accepterar våra cookies kan det hända att du inte kan använda vissa delar av vår plattform.\n    *   **Webbfyrar.** Även kallade clear gifs, pixeltaggar och single-pixel gifs som bifogas i olika delar av vår plattform och våra e-postmeddelanden. Dessa gör det möjligt för oss att övervaka och förstå användarnas aktivitet.\n*   Cookies som lagras på din enhet kan vara permanenta eller sessionscookies. Permanenta cookies är de som finns kvar på din enhet även när du går offline, medan sessionscookies tags bort automatiskt så snart du stänger webbläsaren.\n*   Vi använder både sessionscookies och permanenta cookies för de ändamål som anges nedan:\n    *   Nödvändiga cookies\n        *   _Typ:_ Sessionscookies\n        *   _Syfte:_ Dessa cookies är nödvändiga för att du ska få tillgång till olika delar av plattformen och om dessa inte tillåts kanske du inte kan få tillgång till våra plattformstjänster. Dessa cookies hjälper oss vidare att autentisera användarna och förhindra alla typer av bedräglig aktivitet på plattformen.\n    *   Cookiepolicy/Meddelande om godkännande av cookies\n        *   _Typ:_ Permanenta cookies\n        *   _Syfte:_ Dessa cookies identifierar om användare har accepterat användningen av cookies.\n    *   Cookies för funktionalitet\n        *   _Typ:_ Permanenta cookies\n        *   _Syfte:_ Dessa cookies gör det möjligt för oss att komma ihåg val du gör när du använder plattformen, till exempel dina inloggningsuppgifter eller språkpreferenser. Det övergripande syftet med dessa cookies är att ge dig en mer personlig upplevelse varje gång du använder plattformen.\n\nAlla termer med versaler som används ovan definieras i integritetspolicyn. Besök [Integritetspolicy](/integritetspolicy/) för en detaljerad beskrivning\n',
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Lär dig mer om visumkrav, valutaväxling, skillnader i tidszoner och mycket mer så att du får en smidig ankomst och en trevlig vistelse.',
    WHERE_TO_EAT:
      'Njut av den livliga kulinariska matkulturen, prova på olika smaker och njut av lokala delikatesser överallt i {0}.',
    WHERE_TO_STAY:
      'Upptäck de bästa boendena i {0} som erbjuder komfort, bekvämlighet och en minnesvärd upplevelse för din vistelse.',
    THINGS_TO_DO:
      'Upplev en uppsjö av spännande aktiviteter och sevärdheter som tillgodoser alla intressen och garanterar en oförglömlig tid.',
    WEATHER:
      'Planera resan klokt och få ut det mesta av ditt besök. {0} erbjuder trots allt förtrollande upplevelser året runt.',
    NEIGHBOURHOODS:
      'Lär känna lokalkulturen och de levande stadsdelar som ger {0} dess unika karaktär.',
    TRANSPORTATION:
      'Navigera i {0} med lätthet med hjälp av dess effektiva transportsystem som ger bekväma alternativ när du vill utforska dess många sevärdheter.',
    TRIP_PLANNER:
      'Maximera din tid i {0} med noggrant kurerade resplaner så att du får ut det mesta av varje ögonblick.',
    FAMILY_TRAVEL:
      'Ge dig ut på ett familjevänligt äventyr med många sevärdheter, parker och underhållningsalternativ som passar barn i alla åldrar.',
    TRAVEL_TIPS:
      'Få experttips och reseknep för att förbättra din resa, så att ditt besök i {0} verkligen blir exceptionellt.',
    SHOPPING:
      'Utforska shopparnas paradis med ett brett utbud av butiker, marknader och gallerior som erbjuder allt från lokalt hantverk till avancerat mode.',
    ART_AND_CULTURE:
      'Fördjupa dig i den rika konst- och kulturscenen, med alltifrån fängslande museer till livliga festivaler som firar {0}-årsjubiléum.',
  },
  CLOSE: 'Nära',
  COLLECTION_SLICE_HEADING: 'De bästa upplevelserna i {0}',
  COMBO_VARIANT: {
    SELECT_CTA: 'Välj',
    SELECT_PREFERENCE: 'Välj dina preferenser',
    SELECT_OPTION: 'Välj ditt alternativ',
    SELECT_TICKET: 'Välj din biljett',
  },
  COMPARE_ALL_DETAILS: 'Jämför all information',
  COVID19_ALERT: {
    KEY_TEXT: 'Uppdatering om covid-19',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Vi prioriterar dig. Besök vår hjälpsida för de senaste uppdateringarna om våra flexibla avbokningsregler',
  },
  CURRENCY: 'Valuta',
  CUSTOMER_REVIEW_HEADING: 'Kundrecensioner',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Ljudguide',
    DURATION: 'Varaktighet: {0}',
    EXTENDED_VALIDITY: 'Utökad giltighet',
    FLEXIBLE_DURATION: 'Flexibel varaktighet',
    FREE_CANCELLATION: 'Fri avbokning',
    BOOK_NOW_PAY_LATER: 'Boka nu och betala senare',
    GUIDED_TOUR: 'Guidad rundtur',
    HOTEL_PICKUP: 'Upphämtning på hotellet',
    INSTANT_CONFIRMATION: 'Omedelbar bekräftelse',
    MEALS_INCLUDED: 'Måltider ingår',
    MOBILE_TICKET: 'Mobilbiljett',
    SKIP_THE_LINE: 'Skippa kön',
    TRANSFERS: 'Transfer ingår',
  },
  BOOK_NOW_PAY_LATER_DESCRIPTOR_SUBTEXT:
    'Boka nu utan att betala någonting. Avboka kostnadsfritt om dina planer ändras.',
  DURATION: 'Varaktighet',
  EARLIEST_AVAILABILITY: 'Tidigaste tillgänglighet',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'Ange din e-postadress här',
    SIGN_UP: 'Registrera dig',
    THANK_YOU: 'Tack så mycket!',
    SUBSCRIBED_MSG: 'Du är nu registrerad',
    ERROR_MSG: 'Ange en giltig e-postadress',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Biljetter till Broadway',
    },
    LTT: {
      MB_NAME: 'Biljetter till Londons teaterdistrikt',
    },
  },
  EXCLUSIONS: 'Undantag',
  FEATURE_CARD: {
    HEADING_CUSTOMER: 'Över {0} miljoner',
    HEADING_RATING: '4,4/5',
    HEADING_SAFE: '100 % säker',
    HEADING_SUPPORT: 'Kundtjänst dygnet runt',
    SUB_HEADING_CUSTOMER: 'Nöjda kunder från över 10 000 upplevelser',
    SUB_HEADING_RATING:
      'Över 5 000 verifierade recensioner med 90 % utmärkt betyg',
    SUB_HEADING_SAFE: 'Alla utomhusaktiviteter är 100 % säkra och trygga',
    SUB_HEADING_SUPPORT:
      'Har du någon fråga? Livechatta med lokala experter var som helst, när som helst',
  },
  FLEXIBLE: 'Flexibel',
  FOOTER: {
    CALL_US: 'Ring oss',
    CHAT_WITH_US: 'Chatta med oss',
    COMPANY_DETAILS: 'Information om företaget',
    INFORMATION: 'Information om',
    ABOUT_US: 'Om oss',
    GMAPS_DISCLAIMER:
      'Alla skärmdumpar av kartor som finns på denna sida kommer från Google i enlighet med rättvis användning. Alla rättigheter till sådana skärmdumpar ligger hos den specifika plattformen och de får endast användas i informations- eller vägledningssyfte.',
    DISCLAIMER:
      'Denna webbplats är inte den officiella webbplatsen för <attraction>. Den drivs av Headout och samarbetar med resmål och arrangörer för att erbjuda otroliga upplevelser med en enkel knapptryckning.',
    EMAIL_US: 'Skicka e-post till oss',
    GET_HELP: 'Få hjälp',
    LEGAL: 'Juridisk',
    PRIVACY_POLICY: 'Integritetspolicy',
    QUICK_LINKS: 'Snabblänkar',
    TERMS_AND_CONDITIONS: 'Villkor och anvisningar',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Skapad med ',
    ALL_OVER_THE: ' över hela världen ',
    TERMS_OF_USAGE: 'Användarvillkor',
    GET_HELP_24_7: 'Få hjälp 24/7',
    HELP_CENTER: 'Kundtjänst',
    COMPANY: 'Företag',
    WE_ACCEPT: 'Vi accepterar',
    DOWNLOAD_HEADOUT: 'Ladda ner Headout-appen',
    SCAN_CODES: 'Skanna kod',
    STAR_VERIFIED: 'Klicka för att verifiera S.T.A.R-medlemskap',
    OFFICIAL_TICKET_RETAILER: 'Officiell biljettåterförsäljare',
  },
  FREE_CANCELLATION: 'Fri avbokning',
  FREE_CANCELLATION_SUBTEXT:
    'Vi förstår att planer kan ändras. Avboka kostnadsfritt upp till 72 timmar före evenemanget.',
  FROM: 'Från',
  GET_CASHBACK: 'Få {0} % tillbaka',
  GROUP_TICKETS: 'Gruppbiljetter',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: 'Över {0} miljoner nöjda kunder',
    SUB_TEXT:
      'Kundnöjdhet är vår högsta prioritet. Bli en del av vår nöjda kundbas.',
  },
  HEADOUT: 'Headout',
  HELP_CENTER: {
    MAIN_TEXT: 'Kundtjänst dygnet runt',
    SUB_TEXT:
      'Frågor eller funderingar? Vi finns här för att hjälpa dig dygnet runt – på telefon, chatt och e-post.',
  },
  INCLUSIONS: 'Inkluderingar',
  LANGUAGE: 'Språk',
  LANGUAGES: {
    ENGLISH: 'Engelska',
    SPANISH: 'Spanska',
    FRENCH: 'Franska',
    ITALIAN: 'Italienska',
    GERMAN: 'Tyska',
    PORTUGUESE: 'Portugisiska',
    NEDERLANDS: 'Holländska',
    POLISH: 'Polska',
    RUSSIAN: 'Ryska',
    DANISH: 'Danska',
    NORWEGIAN: 'Norska',
    ROMANIAN: 'Rumänska',
    SWEDISH: 'Svenska',
    TURKISH: 'Turkiska',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Turen finns tillgänglig på {0}',
  LISTICLES: {
    KNOW_MORE: 'Ta reda på mer',
    SEATING_CHART: 'Platsöversikt',
    WHY_BOOK_FROM_US: 'Varför ska du boka via oss?',
  },
  MORE_DETAILS: 'Mer information',
  MORE_CURRENCIES: 'Fler valutor',
  NEW: 'NYHET',
  NEW_ARRIVAL: 'Nyheter',
  NEXT_AVAILABLE: 'Nästa tillgängliga: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout är varumärket som över {0} miljoner resenärer litar på och som erbjuder ett skräddarsytt urval av de bästa upplevelserna. Detta är inte resmålets webbplats.',
  NO_RESULT_FOUND: 'Hmm, inga resultat hittades.',
  OFF: 'Av',
  OPEN_DATED_DESCRIPTOR: 'Boka med flexibilitet – du behöver inte välja datum',
  OPENING_DATE: 'Premiärdatum',
  OPENING_ON: 'Öppnar den',
  OPENS: 'Öppnar',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout är en auktoriserad och pålitlig partner till resmålet och erbjuder ett urval av de bästa sätten att uppleva sevärdheterna på. Detta är inte resmålets webbplats.',
  POI_COLLECTIONS_SECTION: {
    MAKE_THE_MOST_OF_CITY: 'Få ut det mesta av {0}',
    TOP_EXPERIENCE_PICKS: 'Utvalda upplevelser',
    EXPERIENCES: 'Över {0} upplevelser',
    CITY_YOUR_WAY: '{0}, på ditt sätt!',
    DISCOVER_MORE: 'Upptäck mer',
  },
  POPULAR_CURRENCIES: 'Populära valutor',
  PRICES_STARTING: 'Priser från',
  PROMO_CODES: {
    APPLY_CODE: 'TILLÄMPA KOD',
    APPLIED: 'TILLÄMPAD',
    TOOL_TIP_INFO: 'Rabatten tillämpas i kassan',
    DESCRIPTION: {
      ABSOLUTE: 'Få {0} rabatt',
      CAPPED: 'Få {0} % rabatt upp till {1}',
      PERCENTAGE: 'Få {0} rabatt',
    },
    REMOVE: 'TA BORT',
  },
  RATINGS: '{0} betyg',
  READ_MORE: 'Läs mer',
  READ_MORE_TEXT: 'Läs mer',
  READ_LESS: 'Visa mindre',
  VIEW_DETAILS: 'Visa information',
  REOPENING: 'Öppnar igen',
  REOPENING_DATE: 'Öppnar igen den',
  REOPENING_ON: 'Öppnar igen den',
  REOPENS: 'Öppnar igen',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      CTA_URL:
        'https://www.austria.info/en/service-and-facts/coronavirus-information/entry-regulations',
      TEXT: '2G-regler gäller: Visst tillträde till boenden, kulturinstitutioner och restauranger/barer är endast möjligt med bevis på fullständig vaccination eller tidigare infektion. Ett negativt covid-19-test är inte längre tillräckligt.',
    },
    AU_DESCRIPTION: {
      CTA_URL:
        'https://www.smartraveller.gov.au/COVID-19/COVID-19-vaccinations',
      TEXT: 'Besökare som är 16 år eller äldre måste uppvisa bevis på covid-19-vaccination eller medicinsk dispens. ',
    },
    BANNER_CTA: 'Ta reda på mer',
    BERLIN_DESCRIPTION: {
      CTA_URL:
        'https://www.berlin.de/en/news/coronavirus/7081102-6098215-berlin-introduces-extensive-2G-rule.en.html',
      TEXT: '2G-regler gäller: Endast fullt vaccinerade och tillfrisknade gäster med bevis på detsamma har tillträde. Gäster under 18 år eller de som inte kan vaccineras av medicinska skäl måste uppvisa ett negativt COVID-testresultat vid entrén. De som av medicinska skäl inte kan vaccineras ska också styrka detta med ett läkarintyg vid entrén.',
    },
    CTA_TEXT: 'Säkerhetsinformation',
    DESCRIPTION_CTA: 'Ta reda på mer.',
    EU_DESCRIPTION: {
      CTA_URL:
        'https://www.diplomatie.gouv.fr/en/coming-to-france/coronavirus-advice-for-foreign-nationals-in-france/coronavirus-statements/article/applying-for-a-covid-certificate-if-you-were-vaccinated-abroad-procedure-for',
      TEXT: 'Från och med den 21 juli 2021 måste alla besökare som är 12 år eller äldre uppvisa ett EU-covidintyg. ',
    },
    EU_HEADING: 'EU-covidintyg krävs',
    EU_PREFIX: 'Obs! ',
    EXPERIENCE_DESCRIPTION:
      'Denna upplevelse följer bästa säkerhetsstandarder i enlighet med lokala föreskrifter och WHO',
    FLAG_TEXT: 'Bästa säkerhet',
    GENERAL_DESCRIPTION:
      'Alla upplevelser med detta märke följer de bästa säkerhetsstandarderna enligt de lokala myndigheternas hälsoriktlinjer.',
    HEADING: 'Bästa säkerhetsstandarder',
    IT_DESCRIPTION: {
      CTA_URL: 'https://www.dgc.gov.it/web/per-cosa-serve.html#viaggi',
      TEXT: 'Från och med den 6 augusti 2021 måste besökare från 11 år och uppåt uppvisa ett Green Pass eller ett EU-covidintyg. ',
    },
    IT_PREFIX: 'Obs! ',
    MOBILE_HEADING: 'Trygga upplevelser',
    MODAL: {
      BADGE_DESCRIPTION:
        'När en upplevelse har det här märket intygare det att säkerhetsstandarderna har verifierats av oss',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'All utrustning, alla fordon och alla områden där många människor kommer i kontakt med utrustningen rengörs efter varje användning. Det är bara att luta sig tillbaka och njuta.',
          HEADING: 'All utrustning och alla ytor är desinficerade',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'All utrustning som är tillgänglig under din upplevelse är noggrant desinficerad efter varje användning. Alltid.',
          HEADING: 'All utrustning och alla ytor är desinficerade',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Alla fordon som är tillgängliga under din upplevelse är noggrant desinficerade efter varje användning. Alltid',
          HEADING: 'Alla fordon är desinficerade',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Som en trygghetsåtgärd har du tillgång till handtvätt- och sanitetsstationer under hela din tid här. Vi har koll på läget. ',
          HEADING:
            'Handtvätt och sanitära anläggningar finns tillgängliga överallt',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Masker är obligatoriska för alla gäster och personal som deltar i denna upplevelse. Detta bidrar till att alla kan ha en trevlig stund med största möjliga säkerhet.',
          HEADING: 'Alla bär masker för din säkerhet',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Våra partner som är verifierade som en säker upplevelse följer lokala bestämmelser om ansiktsmasker. Om det är obligatoriskt kommer alla gäster och all personal att bära mask. De vidtar alla tänkbara åtgärder för att säkerställa din komfort och säkerhet.',
          HEADING: 'Alla bär masker för din säkerhet',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Masker är obligatoriska för alla gäster i denna upplevelse. Detta bidrar till att alla kan ha en trevlig stund med största möjliga säkerhet.',
          HEADING: 'Alla bär masker för din säkerhet',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'All personal i denna upplevelse bär ansiktsmasker för att säkerställa att du kan ha roligt utan att behöva oroa dig.',
          HEADING: 'Alla bär masker för din säkerhet',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Riktlinjer för fysisk distansering gäller under hela upplevelsen. Kapacitetsbegränsningar finns på plats i syfte att säkerställa fysisk distansering.',
          HEADING: 'Riktlinjer för fysisk distansering följs',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Riktlinjer för fysisk distansering gäller under hela upplevelsen. Kapacitetsbegränsningar finns på plats i syfte att säkerställa fysisk distansering. Därför är stora grupper inte tillåtna här.',
          HEADING: 'Riktlinjer för fysisk distansering följs',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Riktlinjerna för fysisk distansering följs hela tiden under den här upplevelsen.',
          HEADING: 'Riktlinjer för fysisk distansering följs',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Riktlinjerna för fysisk distansering följs hela tiden under den här upplevelsen. Det kan därför finnas kapacitetsbegränsningar och gruppbegränsningar på plats. Andas lugnt.',
          HEADING: 'Riktlinjer för fysisk distansering följs',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Riktlinjerna för fysisk distansering följs hela tiden under den här upplevelsen. Därför är stora grupper inte tillåtna här.',
          HEADING: 'Riktlinjer för fysisk distansering följs',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Alla gäster får kontrollera sin temperatur i början av upplevelsen för allas säkerhet. Alla medarbetares temperatur kollas flera gånger om dagen.',
          HEADING: 'Temperaturkontroller på plats',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Alla gäster får kontrollera sin temperatur i början av upplevelsen för allas säkerhet. ',
          HEADING: 'Temperaturkontroller på plats',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Alla medarbetares temperatur kollas flera gånger. Alla medlemmar som hamnar över den föreskrivna gränsen ombeds att stanna hemma för att återhämta sig.',
          HEADING: 'Temperaturkontroller på plats',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Alla medarbetare som är tillgänglig under hela upplevelsen är utbildad enligt WHO:s riktlinjer och är utrustad för att hantera alla potentiella nödsituationer.',
          HEADING: 'Medarbetarna utbildas i WHO:s riktlinjer',
        },
      },
      HEADING: 'Trygga upplevelser',
      SUB_HEADING:
        'Vi arbetar tillsammans med våra partner över hela världen för att implementera de bästa säkerhetsstandarderna enligt WHO:s riktlinjer. Alla åtgärder som vidtagits på plats är verifierade och visas här. Det är dags att njuta av världen omkring oss igen.',
    },
    NL_DESCRIPTION: {
      CTA_URL:
        'https://www.government.nl/topics/coronavirus-covid-19/covid-certificate',
      TEXT: 'Besökare över 13 år måste ha med sig (digital eller utskriven kopia av) ett covidintyg som visar att du har vaccinerats, fått ett negativt testresultat eller nyligen återhämtat dig från covid-19. Det är obligatoriskt att bära ansiktsmask. ',
    },
    SG_DESCRIPTION: {
      CTA_URL: 'https://safetravel.ica.gov.sg/health/vtsg',
      TEXT: 'Från och med den 13 oktober 2021 kan endast fullt vaccinerade besökare komma in i grupper om två. Du måste visa bevis på vaccinationsstatus, ett nyligen negativt covid-19-testresultat och/eller eventuell återhämtningsdokumentation före inresa. ',
    },
    SHORT_HEADING: 'Bästa tänkbara säkerhetsstandarder på plats',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Säkerhetsinformation',
    EXPERIENCE_DESCRIPTION:
      'Denna upplevelse följer bästa säkerhetsstandarder i enlighet med lokala föreskrifter och WHO',
    FLAG_TEXT: 'Bästa säkerhet',
    GENERAL_DESCRIPTION:
      'Detta resmål är COVIDSÄKERT och följer alla myndighetsrekommendationer som säkerställer att du får en trygg upplevelse med fysisk distansering.',
    GENERAL_DESCRIPTION_V2:
      'Vi har utvecklat den branschomfattande See it Safely-märkningen, så när teatrarna öppnar igen kan du känna dig trygg med att platsen är covidsäker och följer de senaste riktlinjerna från myndigheterna och scenkonsten.',
    HEADING: 'See it Safely',
    MOBILE_HEADING: 'Trygga upplevelser',
    MORE_CURRENCIES: 'Fler valutor',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Endast biljetter som skrivs ut hemma och e-biljetter kommer att accepteras</li>',
          HEADING: 'Kontaktlösa e-biljetter',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Skyddsutrustning såsom masker är obligatoriska för att få tillträde till lokalen</li>\n            <li>Alla i publiken genomgår temperaturkontroller innan de får tillträde till lokalen</li>',
          HEADING: 'Förebyggande säkerhetsåtgärder',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Skyddsutrustning såsom masker är obligatoriska för att få tillträde till lokalen</li>\n            <li>Alla i publiken genomgår temperaturkontroller innan de får tillträde till lokalen</li>',
          HEADING: 'Saneringsåtgärder',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Lokalen har omformats för att minimera kontakten mellan alla i publiken</li>\n            <li>Olika grupper kommer att sitta separat</li>\n            <li>Förbeställning av pausmellanmål underlättas när så är möjligt</li>\n            <li>Kontantlösa och papperslösa transaktioner rekommenderas.</li>\n            <li>Alla i publiken ombeds att ta med sig så lite som möjligt eftersom garderoberna kan vara stängda</li>\n            <li>Aktiviteter som att ta foton med artisterna eller skriva autografer kan vara begränsade</li>\n',
          HEADING: 'Åtgärder för fysisk distansering',
        },
      },
      HEADING: 'See it Safely',
      SUB_HEADING:
        'Funderar du på vad som görs för din säkerhet? Ta reda på mer om de säkerhetsåtgärder och covidsäkra protokoll som teatrarna har infört för att garantera din säkerhet.',
    },
    SHORT_HEADING: 'Bästa tänkbara säkerhetsstandarder på plats',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Din säkerhet är vår prioritet',
    TEXT: 'Vi har vidtagit betydande åtgärder för att förbättra renligheten med hjälp av desinfektionsmedel och omfattande och frekvent ytrengöring. Folkmassorna kontrolleras också för att förhindra trafikstockningar.',
  },
  SAVE: 'Spara {0} %',
  SAVE_PERCENT: 'Spara {0} %',
  SAVE_UPTO_PERCENT: 'Spara upp till {0} %',
  SEE_ALL: 'Visa alla',
  SEARCH: 'Sök',
  POPULARITY: 'Popularitet',
  PRICE: 'Pris',
  SEE_MORE_SHOWS: 'Visa fler föreställningar',
  SELECT_CITY: 'Välj stad',
  SELECT_SECTION: 'Välj sektion',
  SEE_ALL_PHOTOS: 'Visa alla bilder',
  SHOW_CLOSED: 'Visa stängd',
  SHOW_LESS: 'Visa mindre',
  SHOW_LESS_TEXT: 'Visa mindre',
  SHOW_MORE: 'Visa mer',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Om föreställningen',
    ABOUT_THEATRE: 'Om teatern',
    ADDITIONAL_INFORMATION: 'Ytterligare information',
    AGE_LIMIT: 'Åldersgräns',
    AGE_SUITABILITY: 'Lämplig ålder',
    CRITIC_REVIEW: 'Recension',
    ANSWER: ['S-'],
    BLOG_SHOW_PAGE: ' Blogg: Föreställningen',
    BLOG_SUMMARY: 'Sammanfattning av bloggen',
    BLOG_THEATRE_PAGE: 'Blogg: Teatern',
    BLOG_THEATRE_SEATING_PLAN: 'Blogg: Salongsplan',
    CANCELLATION_AND_REFUNDS: 'Avbokning och återbetalning',
    CANCELLATION_POLICY: 'Avbokningsregler',
    CAST_AND_CREW: 'Medverkande team',
    CLOSING_DATE: 'Sista ansökningsdag',
    CLOSING_DATE_SPECIAL_OFFER: 'Slutdatum – specialerbjudande',
    DURATION: 'Varaktighet',
    FACILITIES_AND_ACCESSIBILITY: 'Faciliteter och tillgänglighet',
    FREQUENTLY_ASKED_QUESTIONS: 'Vanliga frågor och svar',
    GETTING_THERE: 'Hitta hit',
    GETTING_THERE_MAP_LINK: 'Hitta hit – karta',
    GOOGLE_MAP: 'Google Maps',
    HIGHLIGHTS: 'Höjdpunkter',
    LISTICLE_SHOW_SUMMARY: 'Sammanfattning av föreställningen',
    LISTICLE_SHOW_WHY_WATCH:
      'Sammanfattning – Varför ska jag se föreställningen?',
    OPENING_DATE: 'Premiärdatum',
    QUESTION: ['F-'],
    SAFETY_BANNER: 'Säkerhetsbanner',
    SHOW_DETAILS: 'Visa information',
    SHOW_TIMINGS: 'Tidpunkter för visning',
    SHOW_TYPE: 'Visa typ',
    SPECIAL_OFFER: 'Specialerbjudande',
    THE_STORY: 'Berättelsen',
    THEATRE_ADDRESS: 'Teaterns adress',
    THEATRE_CAPACITY: 'Teaterns kapacitet',
    THEATRE_NAME: 'Teaterns namn',
    TICKETS: 'Biljetter',
    TICKETS_REDEMPTION: 'Inlösen av biljetter',
    TOP_SONGS: 'De bästa låtarna',
    YOUR_TICKETS: 'Dina biljetter',
    ABOUT_CONCERT: 'Om konserten',
    PROGRAM: 'Program',
    PART_ONE: 'Del 1',
    PART_TWO: 'Del 2',
  },
  SORT_BY: 'Sortera efter',
  SPECIAL_OFFER: 'Specialerbjudande',
  THEATRE: 'Teater',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Närliggande teatrar',
    NOW_PLAYING: 'Spelar nu',
    UPCOMING_SHOWS: 'Kommande föreställningar',
    PAST_SHOWS: 'Tidigare föreställningar',
    FIND_BEST_SEATS: 'Hitta de bästa platserna',
  },
  TICKET_CAN_BE_CANCELED:
    'Du kan avboka upp till {hours} timmar i förväg och få full återbetalning.',
  TICKET_CANNOT_BE_CANCELED:
    'Biljetten kan inte avbokas men kan ombokas på begäran.',
  TICKETS: 'Biljetter',
  TIMINGS: 'Tider',
  SPECIAL_PRODUCT_HEADING: 'Mest älskade',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Lokala expertguider',
    ENGAGING_STORIES: 'Engagerande berättelser',
    TOP_RATED: 'Topprankad',
  },
  GUIDED_TOUR_REVIEWS: [
    'Vår guide Angela var fantastisk och hade så mycket kunskap om platsen',
    'Guiden svarade mer än gärna på frågor om turen',
    'Vår guide var fantastisk och hon gav oss till och med en bra lunchrekommendation!',
    'Organisationen och vår guide gjorde upplevelsen mycket trevlig',
    'Mycket pedagogiskt innehåll. Jag kommer säkert att göra det här igen med mina barn',
    'Turen var välorganiserad och varade lagom länge',
    'Vår guide var verkligen påläst och visade tydligt sin passion för historia',
    'Bra guide och organisation! Jag rekommenderar detta !!!',
    'Vår guide bjöd på små roliga fakta som höll oss alla engagerade och intresserade',
    'Turen gick i bra tempo och kändes inte stressad',
    'Vår guide Maria lyckades hitta platser åt oss på den bästa utsiktsplatsen',
    'Vår guide berikade vårt besök mer än vad vi skulle ha gjort på egen hand',
    'Detaljerad och djupt rörande tur ledd av passionerad guide',
    'Jeff visade oss delar av platsen som vi annars skulle ha missat',
  ],
  GUIDES_BANNER: 'Utforska som en lokalbo med våra älskade superguider.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'En guidad tur är det bästa sättet att få ut mesta möjliga av resmålet. Våra expertguider fungerar som dina lokala kompisar och delar med sig av historier, experttips och reserekommendationer.',
    'Besök inte bara – upplev!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Hör mer från våra gäster',
  GUIDES: 'Guider',
  TODAY: 'Idag',
  TOMORROW: 'I morgon',
  TOUR_LIST_HEADING: 'Välj upplevelse',
  TOUR_LIST_SUB_HEADING:
    'Välj bland flera biljetter, turer och kombinationsalternativ av verifierade operatörer',
  UGC: {
    FOLLOW: 'Följ',
    FOLLOW_IG: 'Följ oss på Instagram',
    HEADING: 'POV: Ditt nästa äventyr ser ut så här',
    SUB_HEADING: 'En samling ur 💜 av Headout',
  },
  UNAVAILABLE: 'Ej tillgänglig',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Dessa biljetter är giltiga under en längre tid. Exakt information kommer att finnas på biljetten.',
    UNTIL_DATE: 'Dessa biljetter är giltiga till och med {0}.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Dessa biljetter är giltiga i {0} dagar från inköpsdatumet.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Dessa biljetter är giltiga i {0} månader från inköpsdatumet.',
  },
  TABLE_OF_CONTENTS: 'Innehåll',
  VIEW_LESS: 'Visa mindre',
  VIEW_MORE: 'Visa mer',
  WHY_TAKE_THIS_DAY_TRIP: 'Varför ska jag göra denna dagsutflykt?',
  WHY_WATCH: 'Varför ska jag titta på {0}?',
  FIND_ON_MAP: 'Hitta på kartan',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Biljetter till biljettkassan',
        DESCRIPTION: 'Omedelbart bekräftelse till din telefon',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: 'Välj dina platser',
        DESCRIPTION: 'Den vy du vill ha, varje gång',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Exklusiva erbjudanden och rabatter',
        DESCRIPTION: 'Spara pengar på {0}s bästa föreställningar',
      },
      BOOK_AND_RELAX: {
        NAME: 'Boka och koppla av',
        DESCRIPTION: 'Uppskattade av {0} miljoner gäster och fler därtill',
      },
    },
    YOUR_PICK: 'Ditt val',
    BROWSE_BY_CATEGORIES: 'Bläddra efter kategori',
    TOP_WEST_END_SHOWS: 'De bästa föreställningarna i West End',
    TOP_THEATRE_SHOWS: 'De bästa {0} föreställningarna',
    TOP_SHOWS: 'De bästa föreställningarna',
    SEE_MORE_SHOWS: 'Visa {0} fler föreställningar',
    LAST_MINUTE_TICKETS: 'Biljetter i sista minuten',
    LOVED_BY_MILLIONS: 'Älskad av miljoner',
    TODAY: 'Idag',
    TOMORROW: 'I morgon',
    SEE_ALL: 'Visa alla',
    GRAB_YOUR_TICKETS: 'Skaffa dina biljetter nu',
  },
  TAG_NAME: {
    BALLET: 'Balett',
    CABARET: 'Kabaré',
    CHRISTMAS: 'Julen',
    CIRCUS: 'Cirkus',
    CLASSIC: 'Klassisk',
    COMEDY: 'Komedi',
    COMING_SOON: 'Kommer snart',
    CRITICS_CHOICE: 'Kritikernas val',
    DANCE: 'Dans',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'English National Ballet',
    ENGLISH_NATIONAL_OPERA: 'English National Opera',
    FANTASY: 'Fantasi',
    HALLOWEEN: 'Halloween',
    IMMERSIVE_THEATRE: 'Interaktiv teater',
    JUKEBOX: 'Jukebox',
    KIDS: 'Barn',
    MAGIC: 'Magi',
    MUSICALS: 'Musikaler',
    NEW_ARRIVAL: 'Nyheter',
    OFF_WEST_END: 'Off West End',
    OLIVIER_WINNER: 'Vinnare av Olivier Awards',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomimer',
    PLAYS: 'Pjäser',
    ROMANCE: 'Romantik',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Stjärnor på scen',
    THEATRICAL_CONCERT: 'Teaterkonsert',
    TRUE_STORY: 'Sann historia',
    TONY_WINNER: 'Vinnare av Tony Awards',
    OFF_BROADWAY: 'Off-Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Oj då! Vi har ett problem',
    MESSAGE:
      'Ursäkta! Alla upplevelser på detta datum är antingen slutsålda eller\n    inte tillgängliga. Men vi har massor av dem på andra datum. Allt\n    du behöver vara är flexibel.',
    CTA: 'Visa alla datum',
  },
  ALL_DATES: 'Alla datum',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Huvudmeny',
    EXPLORE: 'Utforska',
    VISIT: 'Besök',
    THINGS_TO_DO: 'Saker att göra',
    CITY_ATTRACTIONS: '{0} Sevärdheter',
    TOP_THINGS_TO_DO: 'De bästa sakerna att göra',
    CITY_TOURS: '{0} Turer',
    CITY_GUIDE: 'Stadsguide',
    ATTRACTIONS: 'Sevärdheter',
    CRUISES: 'Kryssningar',
    THEMES: 'Teman',
    ABOUT: 'Om',
    TOURS: 'Rundturer',
    SKIP_THE_LINE: 'Skippa-kön-turer',
    GUIDED_TOURS: 'Guidade turer',
    NIGHT_TOURS: 'Nattvandringar',
    FOOD_TOURS: 'Matturer',
    HISTORY: 'Historia',
    ARCHITECTURE: 'Arkitektur',
    DESIGN: 'Design',
    INSIDE: 'Inredning',
    COLLECTIONS: 'Samlingar',
    PAINTINGS: 'Målningar',
    ANIMALS_EXHIBITS: 'Djur och utställningar',
    HABITATS: 'Livsmiljöer',
    CONSERVATION: 'Bevarande',
    PROGRAMMES: 'Program',
    A2_SIGHTSEEING_CRUISES: 'Sightseeingkryssningar',
    A2_DINNER_CRUISES: 'Middagskryssningar',
    A2_EVENING_CRUISES: 'Kvällskryssningar',
    A2_LUNCH_CRUISES: 'Lunchkryssningar',
    A2_YACHT_TOURS: 'Yachtturer',
    PLAN_YOUR_VISIT: 'Planera ditt besök',
    TIMINGS: 'Tider',
    DIRECTIONS: 'Vägbeskrivning',
    PARKING: 'Parkering',
    ROUTES: 'Rutter',
    REQUIREMENTS: 'Krav och önskemål',
    LOCATION: 'Plats',
    RULES: 'Regler',
    FAQs: 'Vanliga frågor',
    ENTRANCES: 'Entréer',
    RESTAURANTS: 'Restauranger',
    FACTS: 'Fakta',
    TIPS: 'Tips',
    MAP: 'Karta',
    RIDES: 'Färdmedel',
    SHOWS: 'Program',
    DINING: 'Mat',
    SHOPPING: 'Shopping',
    EVENTS: 'Evenemang',
    HALLOWEEN: 'Halloween',
    CHRISTMAS: 'Julen',
    NEW_YEARS_EVE: 'Nyårsafton',
    TRAVEL_GUIDE: 'Reseguide',
    TRIP_PLANNER: 'Reseplanerare',
    ITINERARY: 'Reseplan',
    TRAVEL_TIPS: 'Restips',
    WEATHER: 'Väder',
    BEST_TIME_TO_VISIT: 'Bästa tiden att besöka',
    JANUARY: 'Januari',
    FEBRUARY: 'Februari',
    MARCH: 'Mars',
    APRIL: 'April',
    MAY: 'Maj',
    JUNE: 'Juni',
    JULY: 'Juli',
    AUGUST: 'Augusti',
    SEPTEMBER: 'September',
    OCTOBER: 'Oktober',
    NOVEMBER: 'November',
    DECEMBER: 'December',
    WHERE_TO_EAT: 'Var ska jag äta?',
    WHERE_TO_STAY: 'Var ska jag bo?',
    NEIGHBOURHOODS: 'Grannskap',
    FAMILY_TRAVEL: 'Resor med familjen',
    TRANSPORTATION: 'Transport',
    FESTIVALS_EVENTS: 'Festivaler och evenemang',
  },
  BREADCRUMBS: {
    HOME: 'Hem',
    TRAVEL_GUIDE: 'Reseguide',
    THINGS_TO_DO: 'Saker att göra i {0}',
    SHOW_NAME_TICKETS: '{0} Biljetter',
    LTT_HOME: 'Biljetter till Londons teaterdistrikt',
    LTT_VENUE_PAGE_HOME: 'Teatrar i London',
    BROADWAY_HOME: 'Biljetter till Broadway-föreställning',
    BROADWAY_VENUE_PAGE_HOME: 'Teatrar på Broadway',
    VIENNA_CONCERT_HOME: 'Konsertbiljetter i Wien',
    VIENNA_CONCERT_VENUE_PAGE_HOME: 'Konserthus i Wien',
    ATTRACTIONS: 'Sevärdheter',
    A2_SIGHTSEEING_CRUISES: 'Sightseeingkryssningar',
    A2_DINNER_CRUISES: 'Middagskryssningar',
    A2_EVENING_CRUISES: 'Kvällskryssningar',
    A2_LUNCH_CRUISES: 'Lunchkryssningar',
    A2_YACHT_TOURS: 'Yachtturer',
    LONDON_THEATRE_NEWS: 'Nyheter från Londons teaterdistrikt',
    BROADWAY_SHOW_NEWS: 'Nyheter från Broadway',
    NEWS_PAGE: 'Nyhetssida',
    REVIEWS_PAGE_BANNER_HEADING: '{0} recensioner',
  },
  AMENITIES: {
    Restaurant: 'Restaurang',
    Cafe: 'Café',
    'Dedicated Parking': 'Särskild parkering',
    Elevators: 'Hissar',
    Lift: 'Lyft',
    'Wheelchair Accessible': 'Tillgänglig för rullstolsburna',
    Cloakroom: 'Garderob',
    'Air Conditioning': 'Luftkonditionering',
    WiFi: 'Wifi',
    Bar: 'Bar',
    'Water Fountain': 'Vattenfontän',
    Washrooms: 'Tvättrum',
    Toilets: 'Toaletter',
    Binoculars: 'Kikare',
    'Adapted Toilets': 'Anpassade toaletter',
    'Accessible Toilets': 'Tillgängliga toaletter',
    'Assistive Listening System': 'Hörseltekniska hjälpmedel',
    'Hearing Assistance': 'Hörselhjälp',
    'Booster Cushions': 'Boosterkuddar',
    Shop: 'Butik',
    'Souvenir Shop': 'Souvenirbutik',
    'Guide Dogs': 'Ledarhundar',
    'Baby Changing Facilities': 'Skötbord',
    'Security Check': 'Säkerhetskontroll',
    Ramp: 'Ramp',
    'Level Access': 'Nivåtillgänglighet',
  },
  CALENDAR: {
    FOOTNOTE: '* Alla priser är i {0}',
    PICK_DATE: 'Välj ett datum',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Visa originalrecensionen på {0}',
    VIEW_ORIGINAL_NO_LANG:
      'Denna recension är översatt. Visa originalrecension.',
    TRANSLATE: 'Översätt recensionen på {0}',
    LANGUAGES: {
      EN: 'Engelska',
      ES: 'Spanska',
      FR: 'Franska',
      IT: 'Italienska',
      DE: 'Tyska',
      PT: 'Portugisiska',
      NL: 'Holländska',
    },
  },
  SHOW_PAGE_V2: {
    READ_MORE_REVIEWS: 'Läs fler recensioner',
    SHOW_MORE_REVIEWS: 'Visa fler recensioner',
    ALL_PHOTOS: 'Alla foton',
    MORE_DATES: 'Fler datum',
    SELLING_OUT_FAST: 'Säljer slut snabbt',
    SELECT_TIME_SLOT: 'Välj en tid',
    SELECT_TIME_SLOT_ERROR: 'Välj en tid för att fortsätta',
    PRICE_STARTING_FROM: 'Priser för sittplatserna börjar från',
    SELECT_SEATS: 'Välj sittplatser',
    READ_MORE: 'Läs mer',
    RATINGS_AND_REVIEWS: 'Betyg och recensioner',
    READ_DETAILED_REVIEWS: 'Läs detaljerade recensioner',
    INTERVAL: 'Paus',
    TWO_PART_SHOW: 'Program i två delar',
    UNTIL_DATE: 'Tills {0}',
    AVAILABLE_TIME: 'Tillgänglig tid',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Denna upplevelse är endast tillgänglig vid tidpunkterna nedan',
    CONTENT_TABS: {
      ABOUT: 'Om',
      VENUE: 'Plats',
      TICKETS: 'Biljetter',
      Reviews: 'Recensioner',
    },
    SELECT_SHOW_TIMMING: 'Välj en visningstid',
    ONLY_ONE_SLOT: 'Endast en tid tillgänglig på det valda datumet',
    SIMILAR_SHOWS: 'Du kanske också gillar',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Handling',
      WHAT_CRITICS_THINK: 'Vad kritikerna tycker',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: 'Vanliga frågor och svar om {0}',
      AGE_SUITABILITY_AND_GUIDELINES: 'Ålders- och innehållsguide',
      CAST_AND_CREATIVES: 'Medverkande team',
    },
  },
  HOHO: {
    HOHO: 'Hop On Hop Off-turer',
    BUS_ROUTES_DETAILS: 'Busslinjer',
    TOUR_DETAILS: 'Reseinformation',
    ROUTES_SCHEDULES: 'Rutter och tidtabeller',
    VALIDITY: 'Gäller för 1 dag',
    VALIDITY_NOTE:
      'Din upplevelse är giltig i {0} kalenderdag(ar). Om du bokar din biljett för 6 maj 2023 är din biljett giltig fram till 6 maj 2023, 19.00 PST.',
    BESTSELLER: 'Bästsäljare',
    SEE_ALL: 'Visa alla',
    TIMINGS: 'TIDER',
    FREQUENCY: 'FREKVENS',
    DURATION: 'VARAKTIGHET',
    STARTING_LOCATION: 'Startplats',
    CALENDAR_FOOTNOTE: '* Alla priser är i {0}',
    TOUR_TIMINGS: 'Turtider',
    TOUR_FREQUENCY: 'Turfrekvens',
    GOT_IT: 'Ok',
    SELECT_DATE: 'Välj ett datum',
    SELECT_TOUR: 'Välj typ av resa',
    VIEW_TOUR_DETAILS: 'Visa information om turen',
    BUS_DETAILS: 'Mer information',
    VIEW_ROUTES: 'Visa alla rutter',
    BUS_ROUTES: 'BUSSLINJER',
    ATTRACTIONS_PREVIEW:
      'Snabbaste sättet att besöka över {0} toppsevärdheter, däribland',
    ROUTES: 'Rutter',
    COMBO_SUBTITLE: 'Spara mer med',
    COMBO_TITLE: 'Komboerbjudanden på din hoppa på/hoppa av-tur',
    COMBO_DWEB_TITLE:
      'Spara mer med komboerbjudanden på din hoppa på/hoppa av-tur',
    STOPS_AND_ATTRACTIONS: 'Stopp och närliggande sevärdheter',
    HOP_ON_OFF_AT: 'Hoppa på och av vid dessa {0} hållplatser',
    TIMINGS_FREQUENCY: 'Tider och frekvenser',
    TOUR_DURATION: 'Turens längd',
    EVERY_X_MINS: 'Var {0}',
    VIEW_LOCATION: 'Visa plats',
    BANNER_SUBTEXT:
      'Det bekvämaste och snabbaste sättet att se alla toppsevärdheter i staden.',
    TOP_ATTRACTIONS: 'Vi har samlat de bästa sevärdheterna',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Sista minuten-bokning',
        DESCRIPTION: 'Omedelbart bekräftelse till din telefon',
      },
      COST_EFF: {
        NAME: 'Kostnadseffektivt utforskande',
        DESCRIPTION: 'Flera landmärken, en biljett',
      },
      DAILY_RIDES: {
        NAME: 'Obegränsat antal resor varje dag',
        DESCRIPTION: 'Utforska staden i din egen takt',
      },
      BOOK_RELAX: {
        NAME: 'Boka och koppla av',
        DESCRIPTION: 'Betrodd av {0} miljoner gäster',
      },
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Flerspråkiga expertguider',
    STL: 'Skippa-kön-turer',
    PERSONALIZED: 'Personlig upplevelse',
    LOCAL_FOOD: 'Lokal mat och kultur',
    MULTILINGUAL_GUIDES: 'Flerspråkiga guider',
    CULINARY_EXPERTS: 'Kulinariska experter',
    SIGHTSEEING: 'Sightseeing och underhållning ombord',
    SIGHTSEEING_MEAL: 'Sightseeing och måltidsalternativ ombord',
    MULTILINGUAL_GT: 'Flerspråkiga guidade turer',
    AUDIOGUIDE_COMMENTARY: 'Ljudguide och kommentarer tillgängliga',
    ALL_TOP_ATTRACTIONS_COVERED: 'Vi har samlat de bästa sevärdheterna',
    REG_SCHEDULE_UNLIMITED_RIDES: 'Regelbundet schema. Obegränsat antal resor',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION:
      'Tillgänglighet i sista minuten. Omedelbar bekräftelse',
    MULTI_ROUTES: 'Flera olika ruttalternativ',
    HASSLE_FREE: 'Bekymmersfri bokning',
    FREQUENT_DEPARTURES: 'Frekventa avgångar',
    ONBOARD_AMENITIES: 'De bästa bekvämligheterna ombord',
    FLEXI_TRAVEL: 'Flexibelt resande på flera rutter',
    FLEXI_EXCHANGE_CANCEL: 'Flexibla byten och avbokningar',
    EXTRA_DISCOUNT: 'Extra rabatter för ungdomar, seniorer och familjer',
    PREPAID: 'Förbetald bekvämlighet',
    EASY_ACTIVATION: 'Enkel aktivering',
    INSTANT_CONNECTIVITY: 'Omedelbar anslutning med global täckning',
    ROUND_TRIP: 'Transfer tur och retur',
    CULTURAL_EXPERIENCE: 'Autentiska kulturupplevelser',
    GUARANTEED_SEAT: 'Garanterad plats',
    ONBOARD_WIFI: 'Wifi och laddningsuttag ombord',
    LUGGAGE_ASSISTANCE: 'Hjälp med bagage',
    TOP_ATTRACTIONS: 'De främsta attraktionerna ingår',
    FREQ_DEP_MULTI_ROUTE: 'Frekventa avgångar på flera rutter',
    CHARGING: 'Laddningsstation',
    WIFI: 'Wifi-nätverk',
    FnB: 'Tillgång till mat och dryck',
    LUXURY: 'Lyxig upplevelse',
    FOOD_DRINK: 'Mat och dryck',
    PANAROMIC: 'Panoramautsikt över de största sevärdheterna',
    PANAROMIC_2: 'Panoramautsikt',
    PANAROMIC_3: 'Panoramautsikt, utsikt utan tak',
    BEVERAGES: 'Drycker ombord',
    GOURMET: 'Gourmetmiddag',
    GOURMET_2: 'Gourmetmiddag och drycker',
    NIGHTTIME: 'Fantastiska vyer nattetid',
    ROMANTIC: 'Romantisk atmosfär',
    TRANSFERS: 'Transfer ingår',
    CERTIFIED_OP: 'Certifierad verksamhet',
    BIRD_EYE: 'Fågelperspektiv',
    MULTI_JUMP: 'Flera flexibla tider',
    EXTREME_ADV: 'Extremäventyr',
    PHOTO_OP: 'Natursköna fotomöjligheter',
    TOP_ATTRACTIONS_COVERED: 'De bästa sevärdheterna',
    LOCAL_CULTURE: 'Upplev den lokala kulturen',
    EXCLUSIVE_DISC: 'Exklusiva rabatter',
    EFFICIENT_PUBLIC_TRANSIT: 'Effektiv kollektivtrafik',
    FREQUENT_SERVICE: 'Frekvent service',
    PREBOOKING: 'Enkel förbokning',
    LOCAL_CULTURE_IMM: 'Lokal kulturell fördjupning',
    DISCOVER_HIDDEN: 'Upptäck dolda platser',
    CITY_SIGHTSEEING: 'Sightseeing i staden',
    OFFBEAT_ADV: 'Ovanliga äventyr',
    DRINK_DEALS: 'Dryckeserbjudanden',
    OFFBEAT_EXP: 'Ovanliga upplevelser',
    MULTIPLE_VARIETIES: 'Flera olika sorter ingår',
    HIDDEN_GEMS: 'Dolda pärlor och ovanliga sevärdheter',
    EXPLORE_LOCAL: 'Utforska lokala stadsdelar',
    CUSTOMIZED_TREATMENTS: 'Skräddarsydda behandlingar',
    TRAINED_THERAPISTS: 'Utbildade terapeuter',
    HOLISTIC_WELLNESS: 'Holistisk välbefinnande',
    FLEXIBLE_DURATION: 'Flexibel varaktighet',
    MULTI_BOAT: 'Flera båtalternativ',
    SCENIC_ROUTES: 'Natursköna rutter',
    HANDS_ON: 'Praktiskt lärande',
    CULTURAL_CULINARY: 'Kulturella och kulinariska insikter',
    EXPERT_HOSTS: 'Expertvärdar',
    ADVENTURE_EXPERIENCE: 'Äventyrsupplevelse',
    EQUIPMENT: 'Utrustning ingår',
    SCENIC_FLYOVERS: 'Natursköna flygningar',
    LIVE_COMMENTARY: 'Livekommentering',
    BEST_AERIAL_VIEWS: 'De bästa vyerna från ovan',
    SAFE_CERT_OP: 'Säker och certifierad verksamhet',
    HANDPICKED: 'Specialutvalda turer',
    EFFORTLESS: 'Smidig planering',
    EXPERT_GUIDES: 'Expertguider. Unik inblick',
    ALL_ATTR_ONE_CARD: 'Alla sevärdheter, ett kort',
    MULTI_CARD: 'Flera kortalternativ',
    COST_EFF: 'Kostnadseffektivt och bekvämt',
    BEST_PRICES: 'De bästa priserna',
    MULTI_TRANSPORT: 'Flera transportalternativ',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Alla',
    POPULAR_SUBCATEGORY: 'Populära {0}',
    TOP_CATEGORY: 'Topp {0}',
    ATTRACTIONS: 'Sevärdheter',
    ALL_SUBCATEGORY: 'Alla {0}',
    BROWSE_BY_CATEGORIES: 'Bläddra efter kategori',
    TICKETS_FROM: 'Biljetter från',
    PRICE_LOW_HIGH: 'Pris (lågt till högt)',
    PRICE_HIGH_LOW: 'Pris (högt till lågt)',
    FILTERS: 'Filter',
    RESET: 'Återställning',
    APPLY: 'Tillämpa',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout använder cookies för att förbättra din webbplatsresa, en megabit i taget.',
    MOBILE: 'Cookies gör jobbet.',
    LEARN_MORE: 'Ta reda på mer.',
  },
  SHOW_UNAVAILABLE: 'Inte tillgänglig',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Utvalda nyheter',
    ALL_NEWS: 'Alla nyheter',
    MORE_READS: 'Fler artiklar',
    LOAD_MORE: 'Ladda fler',
    TRAILERS: 'Trailers',
    GET_YOUR_TICKETS: 'Köp dina biljetter',
    POPULAR_SHOWS: 'Populära föreställningar',
    FEATURED: 'Utvalda',
    RECENT_NEWS: 'Senaste nytt',
    SHOW_MORE_ARTICLES: 'Visa fler artiklar',
    COLLAPSE_ALL: 'Visa mindre',
    REVIEWS: 'Recensioner',
    SHOW_ALL_REVIEWS: 'Visa alla recensioner',
    MAILER: {
      HEADING:
        'De bästa teatererbjudandena och nyheterna direkt till din inkorg',
      SUBHEADING:
        'Preumerera på vårt nyhetsbrev för de senaste nyheterna och de hetaste erbjudandena på föreställningar.',
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: '{0} recensioner',
    REVIEWS_COUNT: '{0} recensioner',
    AWESOME: 'Fantastiskt',
    GOOD: 'Bra',
    AVERAGE: 'Genomsnitt',
    POOR: 'Dålig',
    TERRIBLE: 'Fruktansvärt',
    REVIEW_BY_HEADOUT: 'Det här tycker vi: Recension av Headout',
    WHAT_PEOPLE_ARE_SAYING: 'Vad folk säger',
    MOST_RELEVANT: 'Mest relevant',
    RATING_HIGH_TO_LOW: 'Betyg: högt till lågt',
    RATING_LOW_TO_HIGH: 'Betyg: lågt till högt',
    CRITIC_REVIEWS: 'Recensioner',
    USER_REVIEWS: 'Användarrecensioner',
    CONTRIBUTORS_REVIEW: 'Bidragsgivarens recension',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Privat transfer',
    SHARED_TRANSFERS: 'Gemensam transfer',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Boka online',
        DESCRIPTION:
          'Boka dina biljetter online och njut av en snabb och smidig bokningsupplevelse.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Omedelbar bekräftelse',
        DESCRIPTION:
          'Få omedelbar bekräftelse på bokningen av din flygplatstransfer.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Bekväm upphämtning',
        DESCRIPTION:
          'Undvik besväret med långa köer eftersom ditt transferfordon väntar på dig vid din valda upphämtningsplats.',
      },
      DROP_OFF: {
        TITLE: 'Avlämning',
        DESCRIPTION:
          'Ta dig till din destination på ett snabbt och bekvämt sätt.',
      },
    },
    SHARED_TRANSFERS_IN: 'Gemensam transfer i {0}',
    SHARED_TRANSFERS_DESCRIPTION:
      ' Ett bekvämt och kostnadseffektivt transportalternativ för flera passagerare som reser till eller från en flygplats.',
    PRIVATE_TRANSFERS_IN: 'Privat transfer i {0}',
    PRIVATE_TRANSFERS_DESCRIPTION:
      ' En bekväm, personlig transporttjänst för enskilda personer eller små grupper som erbjuder en bekväm direktresa till och från en flygplats.',
    ANYWHERE_IN_THE_CITY: 'Var som helst i staden',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Flera fordonsalternativ',
      FREE_CANCELLATION: 'Fri avbokning',
    },
    SEAMLESS_TRANSFERS: 'Sömlös transfer som är betrodd över hela världen',
    PICK_THE_BEST_AIRPORT_TRANSFER: 'Välj den bästa flygplatstransfern för dig',
    HASSLE_FREE_TRANSFER: 'Problemfri flygplatstransfer',
    EFFORT_LESS_AIRPORT_TRANSFERS: 'Enkel flygplatstransfer i {0} med',
    BUSES: 'bussar',
    TRAINS: 'tåg',
    PRIVATE_TAXIS: 'privat taxi',
    BUS_TRAIN: 'Buss/tåg',
    PRIVATE_TAXI: 'Privat taxi',
    FROM: 'Från',
    SELECT_PICKUP: 'Välj upphämtning',
    TO: 'Till',
    SELECT_DROPOFF: 'Välj avlämning',
    ENTER_DESTINATION: 'Ange din destination',
    ENTER_PICKUP: 'Ange plats för upphämtning',
    PICKUP_DATE: 'Datum för upphämtning',
    SELECT_DATE: 'Välj datum',
    PICKUP_TIME: 'Tid för upphämtning',
    SELECT_TIME: 'Välj tid',
    GUEST: 'Gäst',
    GUESTS: 'Gäster',
    ADD_GUESTS: 'Lägg till gäster',
    ADULT_CHILD: 'Vuxen/barn',
    EXPLORE_TRANSFERS: 'Utforska transfers med mera',
    COMBOS_AND_EXTRAS: 'Komboerbjudanden och extrarabatter',
    YOUR_RIDE_DOORSTEP: 'Din skjuts utanför dörren',
    COMFORTABLE_RIDE:
      'Boka en bekväm privat taxi till och från större flygplatser i {0}',
    TRUSTED_DRIVERS: 'Betrodda förare',
    RIDES_24_7: 'Skjuts tillgänglig dygnet runt',
    FLIGHT_TRACKING: 'Flygspårning',
    KNOW_MORE: 'Ta reda på mer',
    RESERVE_YOUR_RIDE: 'Reservera din skjuts',
    TRANSFER_OPTIONS: 'Transferalternativ har hittats',
    TRANSFERS_AVAILABLE_PLURAL: '{0} transfers är tillgängliga',
    TRANSFERS_AVAILABLE_SINGULAR: '1 transfer är tillgänglig',
    TRUSTED_PARTNERS: 'Över 35 betrodda partner, {0}',
    WORLDWIDE: 'över hela världen',
    COMFORTABLE_RIDES: 'Bekväma turer',
    FREQUENT_DEPARTURES: 'Frekventa avgångar',
    MULTIPLE_TRANSPORT_OPTIONS: 'Flera transportalternativ',
    AND_MANY_MORE: 'Och mycket mer',
    ADD_PICKUP_LOCATION: 'Ange plats för upphämtning',
    ADD_DROPOFF_LOCATION: 'Ange plats för avlämning',
    SELECT_PICKUP_DATE_AND_TIME: 'Välj datum och tid för upphämtning',
    SELECT_A_DATE: 'Välj ett datum',
    TRAIN_STATION: 'Tågstation',
    BUS_STOP: 'Busshållplats',
    ADD_RETURN: 'Lägg till retur',
    HEADS_UP: 'Obs!',
    ADDED_RETURN_TRIP: 'Du har lagt till en returresa!',
    RETURN_NOTE:
      'Observera att vi visar informationen om returresan i kommande steg.',
    OKAY_I_UNDERSTAND: 'Okej, jag förstår',
    SERVING_GUESTS: 'Betjänar {0} i {1} runt om i världen',
    GUESTS_COUNT: 'Över 220 000 gäster',
    CITIES_COUNT: 'Över 55 städer',
    PARNTER_WITH_BEST:
      'Vi samarbetar bara med de bästa för att se till att du får en oförglömlig upplevelse. Låt oss hantera detaljerna medan du lutar dig tillbaka, varvar ner och njuter av resan',
  },
  PC_EXP: {
    SHOW_INCL: 'Visa inkluderingar och viktig information',
    CLEAR: 'Rensa',
    ALL_EXPERIENCES: 'Alla upplevelser',
    FILTER_BY_CATEGORIES: 'Filtrera efter kategori',
    CATEGORIES: 'Kategorier',
    COMBOS: {
      HEADING:
        'Allt som är gott kommer i par. Precis som våra sparkombinationer.',
      DESCRIPTOR_1: 'Rabatterbjudanden',
      DESCRIPTOR_2: 'Planera din resa bättre',
    },
  },
  TOP: 'Topp {0}',
  VIEW_CALENDAR: 'Visa kalender',
  SHOWS_CALENDAR: 'Föreställningskalender',
  IN: 'i',
  SEATS: 'Sittplatser',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'Innehållsguide',
    QUICK_INFORMATION: 'Snabb information',
    PEAK: 'Hög efterfrågan',
    OFF_PEAK: 'Låg efterfrågan',
    ADDRESS: 'ADRESS',
    RECOMMENDED_DURATION: 'REKOMMENDERAD VARAKTIGHET',
    VISITORS_PER_YEAR: 'BESÖKARE PER ÅR',
    NUMBER_OF_ENTRANCES: 'ANTAL INGÅNGAR',
    EXPECTED_WAIT_TIME_STANDARD: 'FÖRVÄNTAD VÄNTETID - STANDARD',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE: 'FÖRVÄNTAD VÄNTETID SKIPPA KÖN',
    UNESCO_YEAR: 'UNESCO ÅR',
    ARCHITECTURE_STYLE: 'ARKITEKTUR',
    TIMINGS: 'Tider',
    SIZE_HEIGHT: 'STORLEK/HÖJD',
    TICKETS: 'BILJETTER',
    FUN_FACTS: 'Roliga fakta',
    DID_YOU_KNOW: 'Visste du det?',
    MORE_INTERESTING_FACTS: 'Mer intressanta fakta',
    PLAN_YOUR_VISIT: 'Planera ditt besök',
    ALSO_KNOWN_AS: 'Även känd som',
    FOUNDED_ON: 'Grundat på',
    FOUNDED_BY: 'Grundat av',
    FROM: 'Från',
    CLOSED_TODAY: 'Stängt idag',
    TODAY: 'Idag',
    CLOSED: 'Stängt',
    OPEN: 'Öppet',
    LAST_ADMISSION: 'Insläpp senast',
    DAYS: 'Dagar',
    BEST_TIME_TO_VISIT: 'Bästa tiden att besöka',
    WEEKDAY_VS_WEEKEND: 'Veckodag kontra helg',
    PEAK_VS_LOW_SEASON: 'Högsäsong kontra lågsäsong',
    PLEASANT: 'Trevligt',
    CROWDED: 'Trångt',
    VERY_CROWDED: 'Mycket trångt',
    LOW_SEASON: 'Lågsäsong',
    MID_SEASON: 'Måttlig säsong',
    PEAK_SEASON: 'Högsäsong',
    TO: 'TILL',
    LOWER_TO: 'till',
    LAST_ENTRY: 'inträde senast',
    SUBATTRACTIONS: 'Mindre sevärdheter',
    INCLUDED_WITH_TICKETS: 'Ingår i {0} biljetter',
    INCLUDED_WITH_SOME_TICKETS: 'Ingår i vissa {0} biljetter',
    EXPLORE_ALL_POI_TICKETS: 'Utforska {0} samt {1} biljetter och rundturer',
    EXPLORE_PARENT_TICKETS: 'Utforska {0} biljetter och rundturer',
    SELECT_YOUR_EXPERIENCE: 'Välj din upplevelse',
    OPERATING_HOURS: 'Öppettider',
    SEE_MORE: 'Visa mer',
    MORE_INSIGHTS: 'Mer statistik',
  },
  OFF_PERCENT: '{0} % rabatt',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Platsöversikt',
    CAPACITY: 'Kapacitet: {0} platser',
    WHATS_ON: 'Vad är på gång',
    CATEGORIES: 'Kategorier',
  },
  NEXT: 'Nästa',
  PREVIOUS: 'Föregående',
  ITINERARY: {
    TAB: 'Resplan',
    HEADING: 'Resplan för upplevelsen',
    VIEW_ITINERARY: 'Visa resplan',
    PASSES_BY_SECTION_HEADING: 'Passerar',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Höjdpunkter',
      NEARBY_THINGS_TO_DO: 'Saker att göra i närheten',
      THINGS_TO_DO: 'Saker att göra',
    },
    STOP_CARD: {
      TITLE: {
        START: 'STARTPUNKT',
        END: 'SLUTPUNKT',
        STARTING_POINT: 'STARTPUNKT',
        STOP: 'STOPP',
        ENDING_POINT: 'SLUTPUNKT',
        PASSING_BY: 'PASSERAR',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} tillgängliga startpunkter',
        END: '{0} tillgängliga slutpunkter',
      },
    },
    GET_DIRECTION: 'Få vägbeskrivning',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} timmar {1} minuter',
        WITHOUT_HOURS: '{0} minuter',
        WITHOUT_MINS: '{0} timmar',
      },
      ATTRACTIONS_COUNT: '{0} sevärdheter',
      ACTIVITIES_COUNT: '{0} aktiviteter',
      TOTAL_DURATION: 'TOTAL VARAKTIGHET',
      FREQUENCY: 'FREKVENS',
      FIRST_DEPARTURE: 'FÖRSTA AVGÅNG',
      LAST_DEPARTURE: 'SISTA AVGÅNG',
      FIRST_DEPARTURE_TIME: 'FÖRSTA AVGÅNGSTID',
      LAST_DEPARTURE_TIME: 'SISTA AVGÅNGSTID',
      MODE_OF_TRANSPORT: 'TRANSFERSÄTT',
      FOOD_AND_DRINKS: 'MAT OCH DRYCK',
    },
    WALK_DURATION: '{0} promenad',
    MORE: 'Ytterligare {0}',
    TIMELINE_VIEW: 'Tidslinje',
    MAP_VIEW: 'Karta',
    MAP_OVERLAY: 'Använd CTRL/⌘ + skrolla för att flytta kartan',
    VIEW_EXPERIENCE_MAPPED_OUT:
      'Se den fullständiga planen för din upplevelse.',
    OPEN_MAP_VIEW: 'Öppna kartan',
    START_POINT_SAME_AS_END_POINT: 'Din slutpunkt är samma som din startpunkt',
    ROUTES: 'Rutter',
    SIGHTS_COVERED: 'Aktuella sevärdheter',
    BOARDING_POINT: 'Ombordstigningsplats',
    BOARDING_POINTS: 'Ombordstigningsplatser',
    LANDMARKS: 'Landmärken',
    VIEW_IN_MAPS: 'Visa i kartor',
  },
  CITY_AIRPORT_TRANSFERS: '{0} Flygplatstransfer',
  BANNER_SUBTEXT:
    'Njut av stressfria resor med en pålitlig, förbokad flygplatstransfer.',
  BEST_PRICES: 'De bästa priserna, utan dolda avgifter',
  BEST_PRICES_SUBTEXT:
    'Fasta avgifter utan överraskningar. Vi erbjuder konkurrenskraftiga priser för förstklassig service.',
  FREE_WAIT_TIME: 'Fri väntetid, ingen brådska',
  FREE_WAIT_TIME_SUBTEXT:
    'Njut av din fria väntetid på 45 minuter när du hämtar ditt bagage',
  COMFORTABLE_RIDE: 'Bekväma turer',
  COMFORTABLE_RIDE_SUBTEXT:
    'Sitt bekvämt i förstklassiga fordon, körda av noggrant utvalda och utbildade förare.',
  EXCELLENCE_HEADING: 'En meritlista av spetskompetens och förtroende',
  ACTIVE_CITIES: 'aktiva städer över hela världen',
  CUSTOMERS_SERVED: 'antal betjänade kunder',
  YEARS_OF_SERVICE: 'antal år av förstklassig service',
  FIND_YOUR_RIDE: 'Hitta ditt perfekta fordon',
  FIND_YOUR_RIDE_SUBTEXT:
    'Välj den bil som passar dig, ditt bagage och gruppstorleken. Vi har alltifrån familjevänliga minibussar till lyxiga sedaner.',
  TRUST_TOOLTIP_HEADER: 'Hur samlar vi in recensioner?',
  TRUST_TOOLTIP_CONTENT:
    'Betygen innefattar verifierade recensioner från både Headouts gäster och våra betrodda partners som driver upplevelserna lokalt. Alla recensioner kommer från verkliga resenärer som har deltagit i upplevelsen.',
  REVIEW_SECTION_HEADER: 'Så här säger våra gäster',
  TRUST_VB_TAG: 'Verifierad bokning',
  SNAPSHOTS_SECTION_HEADER: 'Ögonblicksbilder från våra gäster',
  AGGREGATED_COUNTRIES:
    'Gäster från <strong>{0}</strong> och <strong>över {1} länder</strong> har älskat denna upplevelse',
  REVIEWS_SECTION: {
    SECTION_HEADING: 'Miljontals älskar att resa med oss',
    SORTING: {
      MOST_RELEVANT: 'Mest relevant',
      MOST_RECENT: 'Senaste',
      SORT_BY: 'Sortera efter',
    },
    FILTERING: {
      GREATER_THAN_4: '4+ stjärnor',
      EQUAL_TO_3: '3 stjärnor',
      LESS_THAN_3: '< 3 stjärnor',
      WITH_IMAGES: 'Med bilder',
    },
    EMPTY_STATE: {
      SUB_HEADING:
        'Vi kunde inte hitta recensioner som matchar ditt valda filter.',
      CTA: 'Visa alla recensioner',
    },
    VERIFIED_REVIEW: 'Verifierad partnerrecension',
    REVIEW_SECTION_HEADER: 'Så här säger våra gäster',
    TRUST_VB_TAG: 'Verifierad bokning',
    HEADING: 'Från nöjda kunder',
    HEADING_BOOSTER_TEXT: 'Älskad av 35 miljoner+',
    SEE_MORE_BUTTON_TEXT: 'Show all {0} reviews',
    REVIEW_CARD_MODAL_TITLE: 'Review',
  },
  POWERED_BY: 'drivs av',
  BOOKING_PAGE_TIME: {
    HOUR: ' tim',
    HOURS: ' timmar',
    MINUTE: ' min',
    MINUTES: ' min',
  },
  LTT_SPECIAL_OFFER: 'Erbjudande',
};

export default sv;
