const tr = {
  AUDIO_GUIDE: {
    BANNER: 'Ücretsiz Sesli Rehber',
    PRODUCT_SUFFIX: 'Sesli Rehberli',
  },
  AUTHORISED_AND_TRUSTED_PARTNER: 'Yetkili ve Güvenilir Ortak',
  AUTHORISED_RESELLER: {
    MAIN_TEXT: 'Yetkili satıcı',
    SUB_TEXT: 'Güvenilir ve doğrulanmış ortaklardan eşsiz deneyimler.',
  },
  REVIEWS: 'yorumlar',
  AVAILABLE: 'Mevcut',
  BANNER_CTA: 'Bilet satın al',
  BANNER_FOOTER_SUBTEXT: {
    NON_PARTNERED_NON_SENSITIVE:
      'Headout, bu turistik mekanın keyfini çıkarmanız için sizlere özel deneyimler sunan, dünya çapında milyonlarca ziyaretçinin güvenini kazanmış bir markadır.',
    NON_PARTNERED_SENSITIVE:
      'Headout, bu turistik mekanın keyfini çıkarmanız için sizlere özel deneyimler sunan, dünya çapında milyonlarca ziyaretçinin güvenini kazanmış bir markadır. Bu web sitesi, ziyaret alanının web sitesi değildir. ',
    PARTNERED_NON_SENSITIVE:
      'Headout, bu turistik mekanın yetkili ve güvenilir bir ortağıdır ve ziyaretçilerine bu mekanın keyfini çıkarmaları için özel deneyimler sunmaktadır.',
    PARTNERED_SENSITIVE:
      'Headout, bu turistik mekanın yetkili ve güvenilir bir ortağıdır ve ziyaretçilerine bu mekanın keyfini çıkarmaları için özel deneyimler sunmaktadır. Bu web sitesi, ziyaret alanının web sitesi değildir. ',
  },
  BANNER_SUBTEXT_DEFAULT_DISCLAIMER:
    'Headout, bu turistik mekanın tadını çıkarmanız için en iyi deneyimlerden oluşan bir seçki sunan tesisin yetkili ve güvenilir bir ortağıdır.',
  BOOK_NOW_CTA: 'Hemen rezervasyon yapın',
  BUY_TICKETS_CTA: 'Bilet Satın Al',
  CANCELLATION_POLICY: {
    CANCELLABLE:
      'Bu biletleri deneyim başlamadan {0} saat öncesine kadar iptal edebilir ve paranızın tamamını geri alabilirsiniz.',
    CANCELLABLE_ANYTIME:
      'Deneyiminiz başlamadan önce dilediğiniz zaman ücretsiz iptal etme fırsatı',
    CANCELLABLE_DAYS:
      'Bu biletleri deneyim başlamadan {0} gün öncesine kadar iptal edebilir ve paranızın tamamını geri alabilirsiniz.',
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Bu biletler iptal edilemez. Ancak, biletler uzun süre geçerlidir.',
    HEADING: 'Değişim Politikası',
    NON_CANCELLABLE_BUT_RESCHEDULABLE:
      'Bu biletler iptal edilemez. Ancak, deneyim başlamadan {0} saat öncesine kadar biletler yeniden planlanabilir.',
    NON_CANCELLABLE_NON_RESCHEDULABLE:
      'Bu biletler iptal edilemez veya yeniden planlanamaz.',
    VALID_UNTIL_DATE:
      'Bu biletler iptal edilemez. Ancak, bu biletleri {0} tarihine kadar istediğiniz zaman kullanabilirsiniz.',
    VALID_WITHIN_NEXT_DAYS:
      'Bu biletler iptal edilemez. Ancak, bu biletleri önümüzdeki {0} gün içinde istediğiniz zaman kullanabilirsiniz.',
    VALID_WITHIN_NEXT_MONTHS:
      'Bu biletler iptal edilemez. Ancak, bu biletleri önümüzdeki {0} ay içinde istediğiniz zaman kullanabilirsiniz.',
  },
  CANCELLATION_POLICY_HEADING: 'İptal Politikası',
  CASHBACK: '%{0} para iadesi',
  CASHBACK_INFO:
    'Bu deneyim için rezervasyon yaptığınızda <strong>%{0}</strong> para iadesi alacaksınız. Para iadeniz otomatik olarak Headout hesabınıza yatırılır ve Headout ile gelecekte yapacağınız rezervasyonlarda kullanılabilir.',
  CATEGORY_SLIDER_HEADING: 'Bu Gösteriyi Seçen Müşterilerin İnceledikleri',
  CHECK_AVAIL: 'Rezervasyon ara',
  CITY_PAGE: {
    BANNER_TITLE: 'En iyi deneyimleri yaşayacağınız adres',
    TOP_ATTRACTIONS: 'En Popüler Yerler',
    GO_BEYOND: '{0} ötesine geçin',
    ALL_DAY_TRIPS: 'Tüm Günübirlik Gezileri Görüntüle',
    CITIES_NEARBY: 'Yakındaki Şehirler',
    POPULAR_CATEGORIES: 'Popüler Kategoriler',
    GO_TO_GUIDE: 'İhtiyacınız olan {0} rehberi',
    VIEW_TRAVEL_GUIDE: 'Gezi Rehberini Görüntüle',
    EXPLORE: '{0} Keşfedin',
    GUIDE_SUBHEADING:
      '{0} keşfi hiç bu kadar kolay olmamıştı! {0} gezi rehberimizde şehir hakkında bilmeniz gereken her şey bulunmaktadır; neler yenir, nereler görülür, nasıl gidilir, nerede kalınır ve çok daha fazlası!',
    GUIDE_ITEM_HEADINGS: {
      TRAVEL_GUIDE: 'Genel bilgi',
      WHERE_TO_EAT: 'Lezzet durakları',
      WHERE_TO_STAY: 'Konaklama seçenekleri',
      THINGS_TO_DO: 'Yapılacak aktiviteler',
      WEATHER: 'Ziyaret etmek için en iyi zaman',
      NEIGHBOURHOODS: 'Yerel Halk',
      TRANSPORTATION: 'Ulaşım',
      TRIP_PLANNER: 'Seyahat planı',
      FAMILY_TRAVEL: 'Çocuklarla Seyahat',
      TRAVEL_TIPS: 'Seyahat ipuçları ve pratik bilgiler',
      SHOPPING: 'Alışveriş',
      ART_AND_CULTURE: 'Kültür ve Sanat',
    },
    MAILER: {
      HEADING: '{0} seyahat ilhamı doğrudan gelen kutunuzda',
      SUBHEADING:
        'Özenle seçilmiş deneyimler, anında para iadesi, özel fırsatlar ve önemli seyahat ipuçları ile yeni şehirler keşfedin!',
    },
  },
  COOKIE_CONSENT: {
    BASIC_DESCRIPTION:
      'Çerezleri ve benzer teknolojileri, sitemizdeki deneyiminizi iyileştirmek ve reklamlar da dahil olmak üzere birçok amaçla kullanıyoruz.',
    MANAGE_PREFERENCES: 'Yönet',
    PREFERNCES_SAVED: 'Tercihleriniz kaydedildi',
    COOKIES: 'Çerezler:',
    ACCEPT: 'Tamam',
    ALLOW_ALL: 'Tümüne izin ver',
    DENY_ALL: 'Tümünü reddet',
    HEADING: 'Gizliliğinize her zaman değer veriyoruz',
    DESCRIPTION:
      '*   Çerezler, Web Sitesi/Platform tarafından bilgisayarınıza, mobil cihazınıza veya başka bir cihaza depolanan ve birçok kullanımının yanı sıra tarama geçmişinizin ayrıntılarını içeren küçük dosyalardır.\n*   Platformumuzu kullanım biçiminizi izlemek ve size daha kişiselleştirilmiş hizmetler sunmamıza yardımcı olan belirli bilgileri saklamak için farklı çerez türleri kullanmaktayız. Platformumuzda bulunan herhangi bir hizmeti kullanmanız nedeniyle Cihazınıza belirli çerezler yerleştirilebilir.\n*   Genel olarak, bu başlık altında iki farklı teknoloji kullanıyoruz:\n    *   **Çerezler veya Tarayıcı Çerezleri.** Platformumuza eriştiğinizde Cihazınıza otomatik olarak yerleştirilen küçük bir dosyadır. Tarayıcınıza tüm Çerezleri reddetme talimatı verebilirsiniz. Çerezlerimizi kabul etmemeniz durumunda, Platformumuzun bazı bölümlerini kullanamayabilirsiniz.\n    *   **Web İşaretçileri.** Platformumuzun ve e-postalarımızın çeşitli bölümlerine eklenen ve Kullanıcıların faaliyetlerini izlememize ve anlamamıza olanak tanıyan net gifler, piksel etiketleri ve tek pikselli gifler olarak da adlandırılır.\n*   Cihazınızda depolanan bu Çerezler "Kalıcı" veya "Oturum" Çerezleri olabilir. Kalıcı Çerezler, çevrimdışı olduğunuzda bile Cihazınızda kalan çerezlerdir, oysa Oturum Çerezleri, web tarayıcınızı kapattığınız anda otomatik olarak silinir.\n*   Aşağıda belirtilen amaçlar doğrultusunda hem Oturum Çerezlerini hem de Kalıcı Çerezleri kullanmaktayız:\n    *   Gerekli / Temel Çerezler\n        *   _Tür:_ Oturum Çerezleri\n        *   _Amaç:_ Bu Çerezler, Platformun farklı bölümlerine erişebilmeniz için gereklidir ve bunlara izin verilmezse Platformda bulunan hizmetlere erişemeyebilirsiniz. Bu çerezler ayrıca Kullanıcıların kimliğini doğrulamamıza ve Platform üzerinde her türlü hileli faaliyeti önlememize yardımcı olmaktadır.\n    *   Çerez Politikası / Bildirim Kabul Çerezleri\n        *   _Tür:_ Kalıcı Çerezler\n        *   _Amaç:_ Bu Çerezler, Kullanıcıların Çerez kullanımını kabul edip etmediğini belirler.\n    *   İşlevsellik Çerezleri\n        *   _Tür:_ Kalıcı Çerezler\n        *   _Amaç:_ Bu Çerezler, Platformu kullanırken yaptığınız giriş bilgilerinizi veya dil tercihinizi hatırlamak gibi seçimleri hatırlamamızı sağlar. Bu Çerezlerin daha büyük amacı, Platformu her kullandığınızda Size daha kişiselleştirilmiş bir deneyim sunmaktır.\n\nYukarıda büyük harf ile yazılmış tüm terimler Gizlilik Politikasında tanımlanmıştır. Ayrıntılı bilgi için lütfen [Gizlilik Politikası](/privacy-policy/) bölümünü inceleyin\n',
  },
  CITY_GUIDE_DESCRIPTIONS: {
    TRAVEL_GUIDE:
      'Sorunsuz bir ziyaret ve keyifli bir konaklama sağlamak için vize gereksinimleri, döviz bozdurma, saat dilimi farklılıkları ve daha fazlası hakkında bilgi edinin.',
    WHERE_TO_EAT:
      '{0} şehrinin her köşesinde farklı lezzetler tadarak ve yerel yemeklerin zevkine vararak muhteşem bir gastronomi deneyimi yaşayın. ',
    WHERE_TO_STAY:
      '{0} seyahatiniz boyunca konfor, rahatlık ve unutulmaz bir deneyim sunacak en iyi konaklama tesislerini keşfedin.',
    THINGS_TO_DO:
      'Her ilgi alanına hitap eden ve unutulmaz bir zaman geçirmenizi sağlayacak çok sayıda heyecan verici etkinlik ve cazibe merkezini deneyimleyin.',
    WEATHER:
      'Ziyaretinizi en iyi şekilde değerlendirin; {0}, yıl boyunca büyüleyici deneyimler sunar.',
    NEIGHBOURHOODS:
      '{0} bölgesine eşsiz bir hava katan zengin yerel toplulukları ve canlı sokakları keşfedin.',
    TRANSPORTATION:
      'Tüm cazibe merkezlerini keşfetmek için uygun seçenekler sunan verimli ulaşım sistemini kullanarak {0} şehrini rahatlıkla gezin.',
    TRIP_PLANNER:
      'Özenle hazırlanmış seyahat programlarıyla {0} gezinizdeki vaktinizi en verimli şekilde değerlendirin.',
    FAMILY_TRAVEL:
      'Her yaştan çocuğa hitap eden çok sayıda gezi noktası, park ve çeşitli etkinlik seçenekleriyle aile dostu bir maceraya atılın.',
    TRAVEL_TIPS:
      'Seyahatinizi geliştirmek ve {0} ziyaretinizi benzersiz bir deneyime dönüştürmek için size sunduğumuz özel bilgileri ve seyahat tüyolarını keşfedin.',
    SHOPPING:
      'Yerel el işlerinden lüks giyim ürünlerine kadar pek çok seçenek sunan çok sayıda butik, pazar ve alışveriş merkezini bünyesinde barındıran bu alışveriş cennetini keşfedin.',
    ART_AND_CULTURE:
      'Etkileyici müzelerden {0} mirasını kutlayan renkli festivallere uzanan zengin sanat ve kültür sahnesinin büyüsüne kapılın.',
  },
  CLOSE: 'Kapat',
  COLLECTION_SLICE_HEADING: '{0} gezisinde yapılacak en iyi aktiviteler',
  COMBO_VARIANT: {
    SELECT_CTA: 'Seç',
    SELECT_PREFERENCE: 'Tercihinizi seçin',
    SELECT_OPTION: 'Seçeneğinizi belirleyin',
    SELECT_TICKET: 'Biletinizi seçin',
  },
  COMPARE_ALL_DETAILS: 'Tüm Detayları Karşılaştırın',
  COVID19_ALERT: {
    KEY_TEXT: 'COVID-19 Hakkında Güncelleme',
    LINK: 'https://medium.com/headout/coronavirus-outbreak-cancellation-policy-8fe8e1104b83',
    TEXT: 'Önceliğimiz sizsiniz. Esnek iptal politikalarımızla hakkında en son güncellemeler için lütfen yardım sayfamızı inceleyin',
  },
  CURRENCY: 'Para Birimi',
  CUSTOMER_REVIEW_HEADING: 'Müşteri Yorumları',
  DESCRIPTORS: {
    AUDIO_GUIDE: 'Sesli rehber',
    DURATION: 'Süre: {0}',
    EXTENDED_VALIDITY: 'Uzatılmış geçerlilik süresi',
    FLEXIBLE_DURATION: 'Esnek süre',
    FREE_CANCELLATION: 'Ücretsiz iptal',
    GUIDED_TOUR: 'Rehberli tur',
    HOTEL_PICKUP: 'Otelden araç servisi',
    INSTANT_CONFIRMATION: 'Anında onay',
    MEALS_INCLUDED: 'Yemekler dahildir',
    MOBILE_TICKET: 'Mobil bilet',
    SKIP_THE_LINE: 'Sırayı atla',
    TRANSFERS: 'Transferler dahildir',
  },
  DURATION: 'Süre',
  EARLIEST_AVAILABILITY: 'En erken rezervasyon',
  EMAIL_SUBSCRIPTION: {
    EMAIL_FIELD_PLACEHOLDER: 'E-postanızı buraya girin',
    SIGN_UP: 'Kaydol',
    THANK_YOU: 'Teşekkür ederiz!',
    SUBSCRIBED_MSG: 'Abone oldunuz',
    ERROR_MSG: 'Lütfen geçerli bir e-posta girin',
  },
  ENTERTAINMENT_MB: {
    BROADWAY: {
      MB_NAME: 'Broadway Tiyatro Biletleri',
    },
    LTT: {
      MB_NAME: 'Londra Tiyatro Biletleri',
    },
  },
  EXCLUSIONS: 'Kapsam Dışındakiler',
  FEATURE_CARD: {
    HEADING_CUSTOMER: '{0} milyondan fazla',
    HEADING_RATING: '4.4/5',
    HEADING_SAFE: '%100 Güvenli',
    HEADING_SUPPORT: '7/24 Destek Merkezi',
    SUB_HEADING_CUSTOMER: "10.000'den fazla deneyime katılmış mutlu müşteriler",
    SUB_HEADING_RATING:
      "%90 oranında yüksek puan elde ettiğimiz 5.000'den fazla doğrulanmış yorum",
    SUB_HEADING_SAFE: 'Tüm açık hava etkinlikleri %100 güvenli ve emniyetlidir',
    SUB_HEADING_SUPPORT:
      'Bir sorunuz mu var? Yerel uzmanlarla her yerde, her zaman canlı destek üzerinden iletişime geçin',
  },
  FLEXIBLE: 'Esnek',
  FOOTER: {
    CALL_US: 'Bizi Arayın',
    ABOUT_US: 'Hakkımızda',
    CHAT_WITH_US: 'Bize Chat Üzerinden Ulaşın',
    COMPANY_DETAILS: 'Şirket Bilgileri',
    INFORMATION: 'Bilgi',
    GMAPS_DISCLAIMER:
      "Bu sayfada bulunan tüm harita ekran görüntüleri adil kullanıma uygun olarak Google'dan alınmıştır. Bu ekran görüntülerinin tüm hakları ilgili platforma aittir ve kullanımları yalnızca bilgilendirme veya rehberlik amaçlıdır.",
    DISCLAIMER:
      'Bu web sitesi, <attraction> resmi web sitesi değildir. Bu hizmet Headout tarafından yürütülmektedir ve tek bir tıkla inanılmaz deneyimler yaşatmak üzere turistik yerler ve tur operatörleriyle birlikte çalışılmaktadır.',
    EMAIL_US: 'Bize E-posta Gönderin',
    GET_HELP: 'Yardım Alın',
    LEGAL: 'Yasal',
    PRIVACY_POLICY: 'Gizlilik Politikası',
    QUICK_LINKS: 'Hızlı Bağlantılar',
    TERMS_AND_CONDITIONS: 'Şartlar ve Koşullar',
    COPYRIGHT: '© Headout Inc.',
    MADE_WITH: 'Sevgiyle ',
    ALL_OVER_THE: ' dünyanın dört bir yanında hazırlandı ',
    TERMS_OF_USAGE: 'Kullanım Koşulları',
    GET_HELP_24_7: '7/24 Yardım Alın',
    HELP_CENTER: 'Yardım Merkezi',
    COMPANY: 'Şirket',
    WE_ACCEPT: 'Ödeme Yöntemleri',
    DOWNLOAD_HEADOUT: 'Headout uygulamasını indirin',
    SCAN_CODES: 'Kodu tarayın',
    STAR_VERIFIED: 'S.T.A.R üyeliğini doğrulamak için tıklayın',
    OFFICIAL_TICKET_RETAILER: 'Resmi Bilet Bayisi',
  },
  FREE_CANCELLATION: 'Ücretsiz İptal',
  FREE_CANCELLATION_SUBTEXT:
    'Planlar değişebilir; etkinlikten 72 saat öncesine kadar ücretsiz iptal etme fırsatı.',
  FROM: 'Kalkış noktası',
  GET_CASHBACK: '%{0} Para İadesi Alın',
  GROUP_TICKETS: 'Grup Biletleri',
  HAPPY_CUSTOMER: {
    MAIN_TEXT: '{0} milyondan fazla mutlu müşteri',
    SUB_TEXT:
      'Müşteri memnuniyeti en büyük önceliğimizdir. Mutlu müşterilerimizden biri olun.',
  },
  HEADOUT: 'Headout',
  HELP_CENTER: {
    MAIN_TEXT: '7/24 destek merkezi',
    SUB_TEXT:
      'Sorularınız veya endişeleriniz mi var? Telefon, canlı destek ve e-posta yoluyla 7/24 yardım etmek için hizmetinizdeyiz.',
  },
  INCLUSIONS: 'Hizmet Kapsamındakiler',
  LANGUAGE: 'Dil',
  LANGUAGES: {
    ENGLISH: 'İngilizce',
    SPANISH: 'İspanyolca',
    FRENCH: 'Fransızca',
    ITALIAN: 'İtalyanca',
    GERMAN: 'Almanca',
    PORTUGUESE: 'Portekizce',
    NEDERLANDS: 'Flemenkçe',
    POLISH: 'Lehçe',
    RUSSIAN: 'Rusça',
    DANISH: 'Danca',
    NORWEGIAN: 'Norveççe',
    ROMANIAN: 'Rumence',
    SWEDISH: 'İsveççe',
    TURKISH: 'Türkçe',
  },
  TOUR_AVAILABLE_LANGUAGES: 'Turda {0} dil seçeneği',
  LISTICLES: {
    KNOW_MORE: 'Daha fazla bilgi edinin',
    SEATING_CHART: 'Oturma Planı',
    WHY_BOOK_FROM_US: 'Neden Bizi Tercih Etmelisiniz?',
  },
  MORE_DETAILS: 'Daha detaylı bilgi',
  MORE_CURRENCIES: 'Daha Fazla Para Birimi',
  NEW: 'YENİ',
  NEW_ARRIVAL: 'Yeni Gelenler',
  NEXT_AVAILABLE: 'En yakın tarih: ',
  NON_PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout, {0} milyondan fazla misafir tarafından güvenilen ve en iyi deneyimlerden seçilmiş bir seçki sunan bir markadır. Bu web sitesi, ziyaret alanının web sitesi değildir. ',
  NO_RESULT_FOUND: 'Maalesef bir sonuç bulunamadı.',
  OFF: 'İndirim',
  OPEN_DATED_DESCRIPTOR:
    'Esnek rezervasyon fırsatı - tarih seçimi gerekli değil',
  OPENING_DATE: 'Açılış Tarihi',
  OPENING_ON: 'Açılış Günü',
  OPENS: 'Açık',
  PARTNERED_BANNER_SUBTEXT_DISCLAIMER:
    'Headout, bu turistik mekanın tadını çıkarmanız için en iyi deneyimlerden oluşan bir seçki sunan tesisin yetkili ve güvenilir bir ortağıdır. Bu web sitesi, ziyaret alanının web sitesi değildir. ',
  POPULAR_CURRENCIES: 'Popüler Para Birimleri',
  PRICES_STARTING: 'Başlangıç Fiyatları',
  PROMO_CODES: {
    APPLY_CODE: 'KODU UYGULA',
    APPLIED: 'UYGULANDI',
    TOOL_TIP_INFO: 'Bu indirim ödeme sırasında uygulanacaktır',
    DESCRIPTION: {
      ABSOLUTE: '{0} indirim kazanın',
      CAPPED: '{1} değerine kadar %{0} indirim kazanın',
      PERCENTAGE: '%{0} indirim kazanın',
    },
    REMOVE: 'KALDIR',
  },
  RATINGS: '{0} Değerlendirmeler',
  READ_MORE: 'Devamını oku',
  READ_MORE_TEXT: 'Devamını oku',
  READ_LESS: 'Daha az görüntüle',
  VIEW_DETAILS: 'Detayları Görüntüle',
  REOPENING: 'Yeniden Açılıyor',
  REOPENING_DATE: 'Yeniden Açılış Tarihi',
  REOPENING_ON: 'Yeniden Açılış Günü',
  REOPENS: 'Yeniden Açılış',
  SAFE_EXPERIENCE: {
    AT_DESCRIPTION: {
      CTA_URL:
        'https://www.austria.info/en/service-and-facts/coronavirus-information/entry-regulations',
      TEXT: '2G yönetmelikleri yürürlüktedir: konaklama yerlerine, kültürel kurumlara ve restoranlara/barlara ve diğer birçok yere erişim yalnızca eksiksiz aşılanma veya geçirilmiş enfeksiyon kanıtı ile mümkündür. Negatif Covid-19 testi artık yeterli değildir.',
    },
    AU_DESCRIPTION: {
      CTA_URL:
        'https://www.smartraveller.gov.au/COVID-19/COVID-19-vaccinations',
      TEXT: '16 yaş ve üzeri ziyaretçiler COVID-19 aşısı veya tıbbi muafiyet belgesi göstermek zorundadır. ',
    },
    BANNER_CTA: 'Daha Fazla Bilgi Edinin',
    BERLIN_DESCRIPTION: {
      CTA_URL:
        'https://www.berlin.de/en/news/coronavirus/7081102-6098215-berlin-introduces-extensive-2G-rule.en.html',
      TEXT: '2G yönetmelikleri yürürlüktedir: yalnızca eksiksiz aşılanmış ve hastalığı atlattığını kanıtlayan konuklara giriş izni verilecektir. 18 yaşından küçük veya tıbbi nedenlerle aşı olamayan misafirlerin girişte negatif COVID testi sonucu ibraz etmeleri gerekmektedir. Tıbbi nedenlerle aşı olamayan kişilerin de girişte sağlık raporu ile aşı olamadıklarını kanıtlamaları gerekmektedir.',
    },
    CTA_TEXT: 'Güvenlik Ayrıntıları',
    DESCRIPTION_CTA: 'Daha fazlasını öğrenin.',
    EU_DESCRIPTION: {
      CTA_URL:
        'https://www.diplomatie.gouv.fr/en/coming-to-france/coronavirus-advice-for-foreign-nationals-in-france/coronavirus-statements/article/applying-for-a-covid-certificate-if-you-were-vaccinated-abroad-procedure-for',
      TEXT: '21 Temmuz 2021 tarihinden itibaren 12 yaş ve üzeri tüm ziyaretçilerin AB COVID Sertifikası ibraz etmeleri gerekmektedir. ',
    },
    EU_HEADING: 'AB Covid Sertifikası Gereklidir',
    EU_PREFIX: 'Not: ',
    EXPERIENCE_DESCRIPTION:
      "Bu deneyimde yerel yönetmeliklere ve DSÖ'ye uygun olarak en iyi güvenlik standartlarının uygulandığı teyit edilmiştir",
    FLAG_TEXT: 'En İyi Güvenlik Önlemleri',
    GENERAL_DESCRIPTION:
      'Bu rozete sahip tüm deneyimlerin, yerel yönetimlerin sağlık yönergelerine göre en iyi güvenlik standartlarını takip ettiği doğrulanmıştır.',
    HEADING: 'En İyi Güvenlik Önlemleri',
    IT_DESCRIPTION: {
      CTA_URL: 'https://www.dgc.gov.it/web/per-cosa-serve.html#viaggi',
      TEXT: '6 Ağustos 2021 tarihinden itibaren 11 yaş ve üzeri tüm ziyaretçilerin Yeşil Kart veya AB COVID Sertifikası ibraz etmesi gerekmektedir. ',
    },
    IT_PREFIX: 'Not: ',
    MOBILE_HEADING: 'Güvenli Deneyimler',
    MODAL: {
      BADGE_DESCRIPTION:
        'Bu rozetin bulunduğu deneyimler, güvenlik standartlarının tarafımızca doğrulandığını teyit eder',
      DETAILS: {
        SAFETY_CLEANED_DEFAULT: {
          DESCRIPTION:
            'Tüm ekipmanlar, araçlar ve temasın yoğun olduğu alanlar her kullanımdan sonra dezenfekte edilmektedir. Arkanıza yaslanın ve keyfinize bakın.',
          HEADING: 'Tüm ekipmanlar ve yüzeyler dezenfekte edilmektedir',
        },
        SAFETY_CLEANED_EQUIPMENTS: {
          DESCRIPTION:
            'Deneyiminiz sırasında mevcut olan tüm ekipmanlar her kullanımdan sonra detaylı şekilde dezenfekte edilmektedir. Her zaman.',
          HEADING: 'Tüm ekipmanlar ve yüzeyler dezenfekte edilmektedir',
        },
        SAFETY_CLEANED_VEHICLES: {
          DESCRIPTION:
            'Deneyiminiz sırasında mevcut olan tüm araçlar her kullanımdan sonra detaylı şekilde dezenfekte edilmektedir. Her zaman',
          HEADING: 'Tüm araçlar dezenfekte edilmektedir',
        },
        SAFETY_HANDWASH: {
          DESCRIPTION:
            'Bu güvenli deneyimin tadını çıkartırken, el yıkama ve dezenfeksiyon istasyonlarına erişiminiz olacaktır. Sizin için her şeyi düşündük. ',
          HEADING:
            'El yıkama ve dezenfeksiyon tesisleri tesis genelinde mevcuttur',
        },
        SAFETY_MASK_BOTH: {
          DESCRIPTION:
            'Bu deneyimde tüm konuklar ve personel için maske takmak zorunludur. Bu, herkesin en üst düzey güvenlikle harika vakit geçirmesine yardımcı olmaktadır.',
          HEADING: 'Güvenliğiniz için herkes maske takmaktadır',
        },
        SAFETY_MASK_DEFAULT: {
          DESCRIPTION:
            'Güvenli Deneyim olarak onaylanan ortaklarımız, yüz maskeleriyle ilgili yerel düzenlemelere uymaktadır. Zorunlu olması halinde, tüm konuklar ve personel maske takacaktır. Konforunuzu ve güvenliğinizi sağlamak için mümkün olan her türlü önlemi almaktadırlar.',
          HEADING: 'Güvenliğiniz için herkes maske takmaktadır',
        },
        SAFETY_MASK_GUEST: {
          DESCRIPTION:
            'Tüm konuklar için maske takmak zorunludur. Bu, herkesin en üst düzey güvenlikle harika vakit geçirmesine yardımcı olmaktadır.',
          HEADING: 'Güvenliğiniz için herkes maske takmaktadır',
        },
        SAFETY_MASK_STAFF: {
          DESCRIPTION:
            'Bu deneyimdeki personelin tamamı, tüm endişelerden arınmış bir şekilde eğlenmeniz için yüz maskesi takmaktadır.',
          HEADING: 'Güvenliğiniz için herkes maske takmaktadır',
        },
        SAFETY_RESTRICTED_CAPACITY: {
          DESCRIPTION:
            'Sosyal mesafe kuralları bu deneyim boyunca geçerlidir. Sosyal mesafeyi sağlamak için kapasite kısıtlamaları uygulanmaktadır.',
          HEADING: 'Sosyal mesafe kurallarına uyulmaktadır',
        },
        SAFETY_RESTRICTED_CAPACITY_NO_GROUPS: {
          DESCRIPTION:
            'Sosyal mesafe kuralları bu deneyim boyunca geçerlidir. Sosyal mesafeyi sağlamak için kapasite kısıtlamaları uygulanmaktadır. Ayrıca, büyük grupların ziyaretine de izin verilmemektedir.',
          HEADING: 'Sosyal mesafe kurallarına uyulmaktadır',
        },
        SAFETY_SOCIAL_DISTANCING: {
          DESCRIPTION:
            'Bu deneyim boyunca sosyal mesafe kurallarına uyulmaktadır.',
          HEADING: 'Sosyal mesafe kurallarına uyulmaktadır',
        },
        SAFETY_SOCIAL_DISTANCING_DEFAULT: {
          DESCRIPTION:
            'Bu deneyim boyunca sosyal mesafe kurallarına uyulmaktadır. Bunu mümkün kılmak için kontenjan kısıtlamaları ve grup limitleri uygulanabilir. Rahat bir nefes alın.',
          HEADING: 'Sosyal mesafe kurallarına uyulmaktadır',
        },
        SAFETY_SOCIAL_DISTANCING_NO_GROUPS: {
          DESCRIPTION:
            'Bu deneyim boyunca sosyal mesafe kurallarına uyulmaktadır. Ayrıca, büyük grupların ziyaretine de izin verilmemektedir.',
          HEADING: 'Sosyal mesafe kurallarına uyulmaktadır',
        },
        SAFETY_TEMPERATURE_DEFAULT: {
          DESCRIPTION:
            'Herkesin güvenliğini sağlamak için deneyimin başlangıcında tüm ziyaretçilerin ateşi kontrol edilecektir. Tüm personel günde birçok kez ateş ölçümü kontrolünden geçirilmektedir.',
          HEADING: 'Ateş ölçümü yapılmaktadır',
        },
        SAFETY_TEMPERATURE_GUEST: {
          DESCRIPTION:
            'Herkesin güvenliğini sağlamak için deneyimin başlangıcında tüm ziyaretçilerin ateşi kontrol edilecektir. ',
          HEADING: 'Ateş ölçümü yapılmaktadır',
        },
        SAFETY_TEMPERATURE_STAFF: {
          DESCRIPTION:
            'Tüm personel birçok kez ateş ölçümü kontrolünden geçirilmektedir. Öngörülen sınırın üzerindeki kişilerin girişleri kısıtlanır ve iyileşmeleri için evde kalmaları istenir.',
          HEADING: 'Ateş ölçümü yapılmaktadır',
        },
        SAFETY_TRAINED_STAFF: {
          DESCRIPTION:
            'Deneyim boyunca hizmet verecek personel, DSÖ yönergeleri uyarınca eğitim almıştır ve önlerine çıkan her türlü acil durumla başa çıkabilecek donanıma sahiptir',
          HEADING:
            'Personel, DSÖ yönergeleri hakkında eğitime tabi tutulmuştur',
        },
      },
      HEADING: 'Güvenli Deneyimler',
      SUB_HEADING:
        'DSÖ yönergeleri uyarınca en iyi güvenlik standartlarını uygulamak için dünyanın dört bir yanındaki ortaklarımızla birlikte çalışıyoruz. Sahada alınan tüm tedbirler doğrulanmış ve burada paylaşılmıştır. Yeniden dünyanın tadını çıkarma zamanı.',
    },
    NL_DESCRIPTION: {
      CTA_URL:
        'https://www.government.nl/topics/coronavirus-covid-19/covid-certificate',
      TEXT: '13 yaş ve üzeri ziyaretçiler, aşı olduklarına, negatif test sonucu aldıklarına veya yakın zamanda COVID-19 atlattıklarına dair COVID Belgesi (dijital veya basılı kopyası) bulundurmalıdır. Yüz maskesi takmak zorunludur. ',
    },
    SG_DESCRIPTION: {
      CTA_URL: 'https://safetravel.ica.gov.sg/health/vtsg',
      TEXT: '13 Ekim 2021 tarihinden itibaren sadece aşıları tam olan ziyaretçiler 2 kişilik gruplar halinde giriş yapabilecektir. Girişten önce aşı durumunuzu kanıtlamanız, yakın zamanda yapılmış negatif bir COVID-19 test sonucu ve/veya iyileşme belgelerini göstermeniz gerekecektir. ',
    },
    SHORT_HEADING: 'En iyi güvenlik standartları uygulanmaktadır',
  },
  SAFE_EXPERIENCE_NEW: {
    CTA_TEXT: 'Güvenlik Ayrıntıları',
    EXPERIENCE_DESCRIPTION:
      "Bu deneyimde yerel yönetmeliklere ve DSÖ'ye uygun olarak en iyi güvenlik standartlarının uygulandığı teyit edilmiştir",
    FLAG_TEXT: 'En İyi Güvenlik Önlemleri',
    GENERAL_DESCRIPTION:
      'Bu mekân, COVID ÖNLEMLERİ ALIR ve sizlerin güvenli ve sosyal mesafe kurallarına uygun bir tiyatro deneyimi yaşamanızı sağlamak için hükümet tarafından tavsiye edilen tüm güvenlik önlemlerini uygulamaktadır.',
    GENERAL_DESCRIPTION_V2:
      'Sektör çapında Güvenle Gezin (See it Safely) işaretini geliştirdik, böylece tiyatrolar yeniden açıldığında, mekanın COVID açısından güvenli olduğunu ve en güncel hükümet ve sahne sanatları kılavuzuna uyacağını bilerek kendinizi güvende hissedebilirsiniz.',
    HEADING: 'Güvenle Gezin',
    MOBILE_HEADING: 'Güvenli Deneyimler',
    MORE_CURRENCIES: 'Daha Fazla Para Birimi',
    MODAL: {
      DETAILS: {
        CONTACTLESS_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Sadece evde yazdırdığınız biletler ve e-biletler kabul edilecektir</li>',
          HEADING: 'Temassız E-Biletler',
        },
        PREVENTIVE_SAFETY_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Mekâna girmek için maske gibi koruyucu ekipmanların kullanılması zorunludur</li>\n            <li>Tüm izleyiciler mekâna girmeden önce ateş ölçümüne tabi tutulacaktır</li>',
          HEADING: 'Önleyici Güvenlik Tedbirleri',
        },
        SANITIZATION_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Mekâna girmek için maske gibi koruyucu ekipmanların kullanılması zorunludur</li>\n            <li>Tüm izleyiciler mekâna girmeden önce ateş ölçümüne tabi tutulacaktır</li>',
          HEADING: 'Dezenfeksiyon Önlemleri',
        },
        SOCIAL_DISTANCING_MEASURES_DEFAULT: {
          DESCRIPTION:
            '<li>Tesis, tüm katılımcıların birbirleriyle temasını en aza indirecek şekilde yeniden tasarlanmıştır</li>\n            <li>Gruplar birbirinden ayrı şekilde oturacaktır</li>\n            <li>Mümkün olduğu durumlarda ara atıştırmalıkları önceden sipariş edilebilecektir</li>\n            <li>Nakitsiz ve evraksız işlem gerçekleştirmeniz tavsiye edilmektedir.</li>\n            <li>Vestiyerler hizmet dışı olabileceği için tüm katılımcılardan yanlarında minimum düzeyde eşya bulundurmaları rica olunur</li>\n            <li>Sanatçılar ile fotoğraf çektirme veya imza alma gibi faaliyetler sınırlandırılabilir</li>\n            ',
          HEADING: 'Sosyal Mesafe Önlemleri',
        },
      },
      HEADING: 'Güvenle Gezin',
      SUB_HEADING:
        'Güvenliğiniz için neler yapıldığını merak mı ediyorsunuz? Güvenliğinizi sağlamak için tiyatrolarda uygulanan güvenlik önlemleri ve COVID protokolleri hakkında daha fazla bilgi edinin.',
    },
    SHORT_HEADING: 'En iyi güvenlik standartları uygulanmaktadır',
  },
  SANITARY_ALERT: {
    KEY_TEXT: 'Güvenliğiniz bizim önceliğimizdir',
    TEXT: 'Dezenfektanlar ile kapsamlı ve sık yüzey temizliği yaparak hijyeni artırmak için önemli adımlar attık. Kalabalık oluşmaması için tedbirler de alınmaktadır.',
  },
  SAVE: '%{0} Tasarruf Edin',
  SAVE_PERCENT: '%{0} Tasarruf Edin',
  SAVE_UPTO_PERCENT: '%{0} oranına varan tasarruf imkanı',
  SEE_ALL: 'Tümünü Gör',
  SEARCH: 'Ara',
  POPULARITY: 'Popülarite',
  PRICE: 'Fiyat',
  SEE_MORE_SHOWS: 'Daha fazla etkinlik görüntüle',
  SELECT_CITY: 'Şehir seç',
  SELECT_SECTION: 'Bölüm Seç',
  SEE_ALL_PHOTOS: 'Tüm fotoğrafları görüntüle',
  SHOW_CLOSED: 'Gösterimde Değil',
  SHOW_LESS: 'Daha az görüntüle',
  SHOW_LESS_TEXT: 'Daha az görüntüle',
  SHOW_MORE: 'Daha fazla görüntüle',
  SHOW_PAGE: {
    ABOUT_SHOW: 'Etkinlik Hakkında',
    ABOUT_THEATRE: 'Tiyatro Hakkında',
    ADDITIONAL_INFORMATION: 'Ek Bilgi',
    AGE_LIMIT: 'Yaş Sınırı',
    AGE_SUITABILITY: 'Yaş Uygunluğu',
    CRITIC_REVIEW: 'Eleştirmen Yorumu',
    ANSWER: ['A-'],
    BLOG_SHOW_PAGE: 'Blog Gösteri Sayfası',
    BLOG_SUMMARY: 'Blog Özeti',
    BLOG_THEATRE_PAGE: 'Blog Tiyatro Sayfası',
    BLOG_THEATRE_SEATING_PLAN: 'Blog Tiyatro Oturma Planı',
    CANCELLATION_AND_REFUNDS: 'İptal ve İadeler',
    CANCELLATION_POLICY: 'İptal Politikası',
    CAST_AND_CREW: 'Oyuncu Kadrosu ve Ekip',
    CLOSING_DATE: 'Kapanış Tarihi',
    CLOSING_DATE_SPECIAL_OFFER: 'Kapanış Tarihi Özel Teklifi',
    DURATION: 'Süre',
    FACILITIES_AND_ACCESSIBILITY: 'Tesisler & Erişilebilirlik',
    FREQUENTLY_ASKED_QUESTIONS: 'Sıkça Sorulan Sorular',
    GETTING_THERE: 'Ulaşım',
    GETTING_THERE_MAP_LINK: 'Ulaşım Harita Bağlantısı',
    GOOGLE_MAP: 'Google Haritalar',
    HIGHLIGHTS: 'Öne Çıkanlar',
    LISTICLE_SHOW_SUMMARY: 'Gösteri Özeti Listesi',
    LISTICLE_SHOW_WHY_WATCH: 'Gösteri Neden İzlenmeli Listesi',
    OPENING_DATE: 'Açılış Tarihi',
    QUESTION: ['Q-'],
    SAFETY_BANNER: 'Güvenlik Afişi',
    SHOW_DETAILS: 'Gösteri Detayları',
    SHOW_TIMINGS: 'Gösteri Saatleri',
    SHOW_TYPE: 'Gösteri Türü',
    SPECIAL_OFFER: 'Özel Teklif',
    THE_STORY: 'Hikaye',
    THEATRE_ADDRESS: 'Tiyatro Adresi',
    THEATRE_CAPACITY: 'Tiyatro Kapasitesi',
    THEATRE_NAME: 'Tiyatro Adı',
    TICKETS: 'Biletler',
    TICKETS_REDEMPTION: 'Biletlerin Teslimi',
    TOP_SONGS: 'En İyi Şarkılar',
    YOUR_TICKETS: 'Biletleriniz',
    ABOUT_CONCERT: 'Konser Hakkında',
    PROGRAM: 'Program',
  },
  SORT_BY: 'Sırala',
  SPECIAL_OFFER: 'Özel Teklif',
  THEATRE: 'Tiyatro',
  THEATRE_PAGE: {
    NEARBY_THEATRES: 'Yakındaki Tiyatrolar',
    NOW_PLAYING: 'Şimdi Oynuyor',
    UPCOMING_SHOWS: 'Yaklaşan Gösteriler',
    PAST_SHOWS: 'Geçmiş Gösteriler',
    FIND_BEST_SEATS: 'En İyi Koltukları Bulun',
  },
  TICKET_CAN_BE_CANCELED:
    'Tam para iadesi için {hours} saat öncesine kadar iptal edebilirsiniz.',
  TICKET_CANNOT_BE_CANCELED:
    'Bu bilet iptal edilemez ancak talep üzerine yeniden planlanabilir.',
  TICKETS: 'Biletler',
  TIMINGS: 'Saatler',
  SPECIAL_PRODUCT_HEADING: 'En Sevilenler',
  SPECIAL_PRODUCT_DESCRIPTORS: {
    LOCAL_GUIDES: 'Uzman Yerel Rehberler',
    ENGAGING_STORIES: 'İlgi Çekici Hikayeler',
    TOP_RATED: 'En Yüksek Puanlılar',
  },
  GUIDED_TOUR_REVIEWS: [
    'Rehberimiz Angela harikaydı ve mekan hakkında çok bilgiliydi',
    'Rehber, turla ilgili soruları memnuniyetle cevapladı',
    'Rehberimiz harikaydı ve bize harika bir öğle yemeği önerisi bile verdi!',
    'Organizasyon ve rehberimiz deneyimi çok keyifli hale getirdi',
    'Eğitici bir çok içerik vardı, çocuklarımla birlikte mutlaka tekrar katılacağım',
    'Tur iyi organize edilmişti ve süresi de çok iyi ayarlanmıştı.',
    'Rehberimiz gerçekten işini iyi yapıyor ve tarihe karşı büyük bir ilgisi vardı',
    'Rehber ve organizasyon iyiydi! Tavsiye ederim!!!',
    'Rehberimiz, eğlenceli bilgilerle ilgimizi çekmeyi başardı',
    'Tur oldukça iyi bir tempoda ilerledi ve hiç aceleye getirilmiş gibi hissettirmedi',
    'Rehberimiz Maria en iyi izleme noktası için yer bulmayı başardı',
    'Rehberimiz, ziyaretimizi kendi başımıza yapamayacağımız kadar zenginleştirdi',
    'Deneyimli bir rehber eşliğinde detaylı ve etkileyici bir tur',
    'Jeff bize mekanın gözden kaçırabileceğimiz yönlerini gösterdi',
  ],
  GUIDES_BANNER:
    'Konuklarımızın sevdiği muhteşem rehberlerimizle bir bölge sakini gibi gezin.',
  SPECIAL_GUIDED_TOUR_PRODUCT_SUMMARY: [
    'Rehberli bir tura katılmak, bu ziyaret alanından en iyi şekilde yararlanmanın en iyi yoludur. Uzman rehberlerimiz yerel dostlarınız olarak hizmet vererek sizlere hikayeler, bölgeden değerli bilgiler ve seyahat önerileri paylaşmaktadırlar.',
    'Sadece ziyaret etmekle kalmayın - deneyimleyin!',
  ],
  HEAR_FROM_OUR_GUESTS: 'Konuklarımızın görüşleri',
  GUIDES: 'Rehberler',
  TODAY: 'Bugün',
  TOMORROW: 'Yarın',
  TOUR_LIST_HEADING: 'Deneyiminizi Seçin',
  TOUR_LIST_SUB_HEADING:
    'Doğrulanmış operatörler tarafından sunulan çoklu bilet, tur ve kombo seçenekleri arasından seçiminizi yapın',
  UGC: {
    FOLLOW: 'Takip edin',
    FOLLOW_IG: "Instagram'da takip edin",
    HEADING: 'POV: Bir sonraki maceranız şöyle görünüyor',
    SUB_HEADING: 'Headout tarafından sevgi ile hazırlanmıştır 💜',
  },
  UNAVAILABLE: 'Kullanılamıyor',
  VALIDITY: {
    EXTENDED_BUT_UNKNOWN_VALIDITY:
      'Bu biletler, uzun bir süre için geçerlidir. Ayrıntılı bilgiler bilette belirtilecektir.',
    UNTIL_DATE: 'Bu biletler, {0} tarihine kadar geçerlidir.',
    UNTIL_DAYS_FROM_PURCHASE:
      'Bu biletler, satın alma tarihinden itibaren {0} gün boyunca geçerlidir.',
    UNTIL_MONTHS_FROM_PURCHASE:
      'Bu biletler, satın alma tarihinden itibaren {0} ay boyunca geçerlidir.',
  },
  TABLE_OF_CONTENTS: 'İçerikler',
  VIEW_LESS: 'Daha az görüntüle',
  VIEW_MORE: 'Daha Fazla Görüntüle',
  WHY_TAKE_THIS_DAY_TRIP: 'Bu Günlük Geziye Neden Katılmalısınız?',
  WHY_WATCH: 'Neden {0} İzlemelisiniz?',
  FIND_ON_MAP: 'Haritada Bul',
  ENTERTAINMENT_MB_LANDING_PAGE: {
    TRUST_BOOSTERS: {
      BOX_OFFICE_TICKETS: {
        NAME: 'Gişe biletleri',
        DESCRIPTION: 'Anında telefonunuz üzerinden onaylanır',
      },
      CHOOSE_YOUR_SEATS: {
        NAME: 'Koltuklarınızı seçin',
        DESCRIPTION: 'Her seferinde istediğiniz görüş açısı',
      },
      EXCLUSIVE_DEALS: {
        NAME: 'Özel fırsatlar ve indirimler',
        DESCRIPTION: 'En iyi {0} etkinliklerinde tasarruf edin',
      },
      BOOK_AND_RELAX: {
        NAME: 'Rezervasyon yapın ve keyfini çıkarın',
        DESCRIPTION:
          '{0} milyon ziyaretçinin güvenini kazandık ve kazanmaya devam ediyoruz',
      },
    },
    YOUR_PICK: 'Seçiminiz',
    BROWSE_BY_CATEGORIES: 'Kategorilere göre ara',
    TOP_WEST_END_SHOWS: 'En iyi West End gösterileri',
    TOP_THEATRE_SHOWS: 'En iyi {0} gösterileri',
    TOP_SHOWS: 'En iyi gösteriler',
    SEE_MORE_SHOWS: 'Daha fazla gösteri incele {0}',
    LAST_MINUTE_TICKETS: 'Son dakika biletleri',
    LOVED_BY_MILLIONS: 'Milyonlarca insan hayran kaldı',
    TODAY: 'Bugün',
    TOMORROW: 'Yarın',
    SEE_ALL: 'Tümünü Gör',
    GRAB_YOUR_TICKETS: 'Biletlerinizi hemen alın',
  },
  TAG_NAME: {
    BALLET: 'Bale',
    CABARET: 'Kabare',
    CHRISTMAS: 'Noel',
    CIRCUS: 'Sirk',
    CLASSIC: 'Klasik',
    COMEDY: 'Komedi',
    COMING_SOON: 'Çok Yakında',
    CRITICS_CHOICE: 'Eleştirmen Seçimi',
    DANCE: 'Dans',
    DISNEY: 'Disney',
    DRAMA: 'Drama',
    ENGLISH_NATIONAL_BALLET: 'İngiliz Ulusal Balesi',
    ENGLISH_NATIONAL_OPERA: 'İngiliz Ulusal Operası',
    FANTASY: 'Fantastik',
    HALLOWEEN: 'Cadılar Bayramı',
    IMMERSIVE_THEATRE: 'Sürükleyici Tiyatro',
    JUKEBOX: 'Jukebox',
    KIDS: 'Çocuklar',
    MAGIC: 'Sihirbazlık',
    MUSICALS: 'Müzikaller',
    NEW_ARRIVAL: 'Yeni Gelenler',
    OFF_WEST_END: 'Off West End',
    OLIVIER_WINNER: 'Olivier Ödüllü',
    OPERA: 'Opera',
    PANTOMIMES: 'Pantomim',
    PLAYS: 'Tiyatro',
    ROMANCE: 'Romantik',
    SHAKESPEARE: 'Shakespeare',
    STARS_ON_STAGE: 'Yıldızlar Sahnede',
    THEATRICAL_CONCERT: 'Tiyatral Konser',
    TRUE_STORY: 'Gerçek Hikaye',
    TONY_WINNER: 'Tony Ödüllü',
    OFF_BROADWAY: 'Off Broadway',
  },
  INVENTORY_UNAVAILABLE: {
    HEADING: 'Maalesef, bir sorunla karşı karşıyayız',
    MESSAGE:
      'Üzgünüz! Bu tarih için tüm deneyimler ya tükenmiştir ya da\n    erişime kapatılmıştır. Fakat diğer tarihler için birçok seçeneğimiz mevcuttur.  Tümü\n    yapmanız gereken esnek olmak.',
    CTA: 'Tüm tarihleri görüntüle',
  },
  ALL_DATES: 'Tüm tarihler',
  CATEGORY_HEADER: {
    MAIN_MENU: 'Ana Menü',
    EXPLORE: 'Keşfet',
    VISIT: 'Gezi',
    THINGS_TO_DO: 'Yapılacak aktiviteler',
    CITY_ATTRACTIONS: '{0} Gezilecek Yerler',
    TOP_THINGS_TO_DO: 'Yapılacak En İyi Aktiviteler',
    CITY_TOURS: '{0} Turları',
    CITY_GUIDE: 'Şehir Rehberi',
    ATTRACTIONS: 'Gezilecek Yerler',
    CRUISES: 'Gemi Turları',
    THEMES: 'Temalar',
    ABOUT: 'Hakkında',
    TOURS: 'Turlar',
    SKIP_THE_LINE: 'Sıra Atlama Turları',
    GUIDED_TOURS: 'Rehberli Turlar',
    NIGHT_TOURS: 'Gece Turları',
    FOOD_TOURS: 'Yemek Turları',
    HISTORY: 'Tarih',
    ARCHITECTURE: 'Mimari Yapılar',
    DESIGN: 'Tasarım',
    INSIDE: 'İç Mekan',
    COLLECTIONS: 'Koleksiyonlar',
    PAINTINGS: 'Tablolar',
    ANIMALS_EXHIBITS: 'Hayvanlar ve Sergiler',
    HABITATS: 'Yaşam Alanları',
    CONSERVATION: 'Doğal Yaşamı Koruma',
    PROGRAMMES: 'Programlar',
    A2_SIGHTSEEING_CRUISES: 'Gemi Şehir Turları',
    A2_DINNER_CRUISES: 'Akşam Yemekli Gemi Turları',
    A2_EVENING_CRUISES: 'Akşam Gemi Turları',
    A2_LUNCH_CRUISES: 'Öğle Yemekli Gemi Turları',
    A2_YACHT_TOURS: 'Yat Turları',
    PLAN_YOUR_VISIT: 'Seyahatinizi Planlayın',
    TIMINGS: 'Saatler',
    DIRECTIONS: 'Yol Tarifi',
    PARKING: 'Otopark',
    ROUTES: 'Rotalar',
    REQUIREMENTS: 'Gereksinimler',
    LOCATION: 'Konum',
    RULES: 'Kurallar',
    FAQs: 'SSS',
    ENTRANCES: 'Girişler',
    RESTAURANTS: 'Restoranlar',
    FACTS: 'Bilgiler',
    TIPS: 'İpuçları',
    MAP: 'Harita',
    RIDES: 'Lunapark Oyuncakları',
    SHOWS: 'Gösteriler',
    DINING: 'Yemek Deneyimi',
    SHOPPING: 'Alışveriş',
    EVENTS: 'Etkinlikler',
    HALLOWEEN: 'Cadılar Bayramı',
    CHRISTMAS: 'Noel',
    NEW_YEARS_EVE: 'Yılbaşı Gecesi',
    TRAVEL_GUIDE: 'Seyahat Rehberi',
    TRIP_PLANNER: 'Gezi Planlayıcısı',
    ITINERARY: 'Seyahat Programı',
    TRAVEL_TIPS: 'Seyahat İpuçları',
    WEATHER: 'Hava Durumu',
    BEST_TIME_TO_VISIT: 'Ziyaret Etmek için En İyi Zaman',
    JANUARY: 'Ocak',
    FEBRUARY: 'Şubat',
    MARCH: 'Mart',
    APRIL: 'Nisan',
    MAY: 'Mayıs',
    JUNE: 'Haziran',
    JULY: 'Temmuz',
    AUGUST: 'Ağustos',
    SEPTEMBER: 'Eylül',
    OCTOBER: 'Ekim',
    NOVEMBER: 'Kasım',
    DECEMBER: 'Aralık',
    WHERE_TO_EAT: 'Lezzet Durakları',
    WHERE_TO_STAY: 'Konaklama Seçenekleri',
    NEIGHBOURHOODS: 'Semtler',
    FAMILY_TRAVEL: 'Aile Seyahati',
    TRANSPORTATION: 'Ulaşım',
    FESTIVALS_EVENTS: 'Festivaller ve Etkinlikler',
  },
  BREADCRUMBS: {
    HOME: 'Ev',
    TRAVEL_GUIDE: 'Seyahat Rehberi',
    THINGS_TO_DO: '{0} gezisinde yapılacaklar',
    SHOW_NAME_TICKETS: '{0} - Biletler',
    LTT_HOME: 'Londra Tiyatro Biletleri',
    LTT_VENUE_PAGE_HOME: "Londra'daki Tiyatrolar",
    BROADWAY_HOME: 'Broadway Gösteri Biletleri',
    BROADWAY_VENUE_PAGE_HOME: 'Broadway Tiyatroları',
    VIENNA_CONCERT_HOME: 'Viyana Konser Biletleri',
    VIENNA_CONCERT_VENUE_PAGE_HOME: "Viyana'daki Konser Salonları",
    ATTRACTIONS: 'Gezilecek Yerler',
    A2_SIGHTSEEING_CRUISES: 'Gemi Şehir Turları',
    A2_DINNER_CRUISES: 'Akşam Yemekli Gemi Turları',
    A2_EVENING_CRUISES: 'Akşam Gemi Turları',
    A2_LUNCH_CRUISES: 'Öğle Yemekli Gemi Turları',
    A2_YACHT_TOURS: 'Yat Turları',
    LONDON_THEATRE_NEWS: 'Londra Tiyatro Haberleri',
    BROADWAY_SHOW_NEWS: 'Broadway Gösteri Haberleri',
    NEWS_PAGE: 'Haber Sayfası',
    REVIEWS_PAGE_BANNER_HEADING: '{0} yorum',
  },
  AMENITIES: {
    Restaurant: 'Restoran',
    Cafe: 'Kafe',
    'Dedicated Parking': 'Özel Otopark',
    Elevators: 'Asansörler',
    Lift: 'Asansör',
    'Wheelchair Accessible': 'Tekerlekli Sandalye Erişimine Uygun',
    Cloakroom: 'Vestiyer',
    'Air Conditioning': 'Klima',
    WiFi: 'WiFi',
    Bar: 'Bar',
    'Water Fountain': 'Su Çeşmesi',
    Washrooms: 'Tuvaletler',
    Toilets: 'Tuvaletler',
    Binoculars: 'Dürbünler',
    'Adapted Toilets': 'Adaptif Tuvaletler',
    'Accessible Toilets': 'Erişilebilir Tuvaletler',
    'Assistive Listening System': 'Yardımcı Dinleme Cihazları Sistemi',
    'Hearing Assistance': 'İşitme Cihazı Desteği',
    'Booster Cushions': 'Yükseltici Minderler',
    Shop: 'Mağaza',
    'Souvenir Shop': 'Hediyelik Eşya Dükkanı',
    'Guide Dogs': 'Rehber Köpekler',
    'Baby Changing Facilities': 'Bebek Alt Değiştirme Olanakları',
    'Security Check': 'Güvenlik Kontrolü',
    Ramp: 'Rampa',
    'Level Access': 'Seviye Erişim',
  },
  CALENDAR: {
    FOOTNOTE: '* Tüm fiyatlar {0} cinsindendir',
    PICK_DATE: 'Bir tarih seçin',
  },
  REVIEW_LOC: {
    VIEW_ORIGINAL: 'Orijinal yorumu {0} dilinde görüntüle',
    VIEW_ORIGINAL_NO_LANG:
      'Bu yorum çevrilmiştir. Orijinal değerlendirmeyi görüntüle.',
    TRANSLATE: 'Değerlendirmeyi {0} diline çevir',
    LANGUAGES: {
      EN: 'İngilizce',
      ES: 'İspanyolca',
      FR: 'Fransızca',
      IT: 'İtalyanca',
      DE: 'Almanca',
      PT: 'Portekizce',
      NL: 'Flemenkçe',
    },
  },
  SHOW_PAGE_V2: {
    READ_MORE_REVIEWS: 'Daha fazla yorum',
    SHOW_MORE_REVIEWS: 'Daha fazla yorum görüntüle',
    ALL_PHOTOS: 'Tüm fotoğraflar',
    MORE_DATES: 'Daha fazla tarih görüntüle',
    SELLING_OUT_FAST: 'Hızla tükeniyor',
    SELECT_TIME_SLOT: 'Bir zaman aralığı seçin',
    SELECT_TIME_SLOT_ERROR: 'Devam etmek için bir zaman aralığı seçin',
    PRICE_STARTING_FROM: 'Koltukların başlangıç fiyatları:',
    SELECT_SEATS: 'Koltuk seçin',
    READ_MORE: 'Devamını oku',
    RATINGS_AND_REVIEWS: 'Değerlendirmeler ve Yorumlar',
    READ_DETAILED_REVIEWS: 'Detaylı değerlendirmeleri oku',
    INTERVAL: 'Ara',
    TWO_PART_SHOW: 'İki bölümlük gösteri',
    UNTIL_DATE: '{0} tarihine kadar',
    AVAILABLE_TIME: 'Uygun saat aralığı',
    EXPERIENCE_AVAILABLE_ONLY_AT:
      'Bu deneyim sadece aşağıdaki saatlerde mevcuttur',
    CONTENT_TABS: {
      ABOUT: 'Hakkında',
      VENUE: 'Mekan',
      TICKETS: 'Biletler',
      Reviews: 'Yorumlar',
    },
    SELECT_SHOW_TIMMING: 'Gösteri saatini seçin',
    ONLY_ONE_SLOT: 'Seçilen tarihte yalnızca 1 zaman aralığı mevcuttur',
    SIMILAR_SHOWS: 'Bunları da beğenebilirsiniz',
    CONTENT_SECTION_HEADERS: {
      STORYLINE: 'Hikaye',
      WHAT_CRITICS_THINK: 'Eleştirmenlerin düşünceleri',
      FREQUENTLY_ASKED_QUESTIONS_ABOUT: '{0} hakkında sıkça sorulan sorular',
      AGE_SUITABILITY_AND_GUIDELINES: 'Yaş ve içerik kılavuzu',
      CAST_AND_CREATIVES: 'Oyuncu kadrosu ve yaratıcı ekip ',
    },
  },
  HOHO: {
    HOHO: 'Hop On Hop Off Turları',
    BUS_ROUTES_DETAILS: 'Otobüs güzergahları',
    TOUR_DETAILS: 'Tur detayları',
    ROUTES_SCHEDULES: 'Rotalar ve Programlar',
    VALIDITY: '1 gün için geçerlidir',
    VALIDITY_NOTE:
      "Deneyiminiz {0} takvim günü/günleri için geçerlidir. Biletinizi 6 Mayıs 2023 için rezerve ederseniz, 6 Mayıs 2023, 07:00 GMT'ye kadar biletiniz geçerli olacaktır.",
    BESTSELLER: 'En Çok Satanlar',
    SEE_ALL: 'Tümünü gör',
    TIMINGS: 'SAATLER',
    FREQUENCY: 'SIKLIK',
    DURATION: 'SÜRE',
    STARTING_LOCATION: 'Başlangıç konumu',
    CALENDAR_FOOTNOTE: '* Tüm fiyatlar {0} cinsindendir',
    TOUR_TIMINGS: 'Tur Saatleri',
    TOUR_FREQUENCY: 'Tur Sıklığı',
    GOT_IT: 'Anladım',
    SELECT_DATE: 'Bir tarih seçin',
    SELECT_TOUR: 'Tur Türü Seçiniz',
    VIEW_TOUR_DETAILS: 'Tur detaylarını görüntüle',
    BUS_DETAILS: 'DAHA FAZLA BİLGİ',
    VIEW_ROUTES: 'Tüm rotaları görüntüle',
    BUS_ROUTES: 'OTOBÜS GÜZERGAHLARI',
    ATTRACTIONS_PREVIEW:
      '{0}+ en gözde cazibe merkezlerini görmenin en hızlı yolu.',
    ROUTES: 'Rotalar',
    COMBO_SUBTITLE: 'Daha fazla tasarruf edin',
    COMBO_TITLE: 'Hop-on Hop-off turunuz için kombinasyon fırsatları',
    COMBO_DWEB_TITLE:
      'Hop-on Hop-off turu kombinasyon fırsatları ile daha fazla tasarruf edin',
    STOPS_AND_ATTRACTIONS: 'Duraklar ve yakınlardaki gezilecek yerler',
    HOP_ON_OFF_AT: '{0} durak arasında istediğiniz gibi inin ve binin',
    TIMINGS_FREQUENCY: 'Sefer saatleri ve sıklığı',
    TOUR_DURATION: 'Tur süresi',
    EVERY_X_MINS: 'Her {0}',
    VIEW_LOCATION: 'Konumu Görüntüle',
    BANNER_SUBTEXT:
      'Şehirdeki tüm gözde turistik yerleri görmenin en uygun ve en hızlı yolu.',
    TOP_ATTRACTIONS: 'Gezilecek gözde turistik yerler',
    TRUST_BOOSTERS: {
      LAST_MIN: {
        NAME: 'Son dakika rezervasyonu',
        DESCRIPTION: 'Anında telefonunuz üzerinden onaylanır',
      },
      COST_EFF: {
        NAME: 'Uygun maliyetli keşif',
        DESCRIPTION: 'Çok sayıda turistik simge, tek bilet',
      },
      DAILY_RIDES: {
        NAME: 'Gün içinde sınırsız şekilde lunapark oyuncaklarına binin',
        DESCRIPTION: 'Şehri dilediğiniz hızda keşfedin',
      },
      BOOK_RELAX: {
        NAME: 'Rezervasyon yapın ve keyfini çıkarın',
        DESCRIPTION: '{0} milyon konuk bize güveniyor',
      },
    },
  },
  BANNER_DESCRIPTORS: {
    EXPERT_MULTILINGUAL_GUIDES: 'Çok Dilli Uzman Rehberler',
    STL: 'Sıra Atlama Erişimi',
    PERSONALIZED: 'Kişiselleştirilmiş Deneyim',
    LOCAL_FOOD: 'Yerel Yemekler ve Kültür',
    MULTILINGUAL_GUIDES: 'Çok Dilli Rehberler',
    CULINARY_EXPERTS: 'Gastronomi Uzmanları',
    SIGHTSEEING: 'Şehir Turu ve Aktiviteler',
    SIGHTSEEING_MEAL: 'Şehir Turu ve Gemide Yemek Seçenekleri',
    MULTILINGUAL_GT: 'Çok Dilli Rehberli Turlar',
    AUDIOGUIDE_COMMENTARY: 'Sesli Rehber ve Bilgilendirici Yorum mevcut',
    ALL_TOP_ATTRACTIONS_COVERED:
      'Tüm gözde turistik yerler ziyaret edilmektedir',
    REG_SCHEDULE_UNLIMITED_RIDES:
      'Normal program. Sınırsız şekilde lunapark oyuncaklarına binin',
    LAST_MIN_AVAIL_INSTANT_CONFIRMATION: 'Son dakika rezervasyonu. Anında onay',
    MULTI_ROUTES: 'Çoklu Rota Seçenekleri',
    HASSLE_FREE: 'Kolay Rezervasyon',
    FREQUENT_DEPARTURES: 'Sık Kalkışlar',
    ONBOARD_AMENITIES: 'En İyi Taşıt İçi Olanakları',
    FLEXI_TRAVEL: 'Birden Fazla Güzergahta Esnek Seyahat',
    FLEXI_EXCHANGE_CANCEL: 'Esnek Değişimler ve İptaller',
    EXTRA_DISCOUNT: 'Gençler, yaşlılar ve aileler için ekstra indirimler',
    PREPAID: 'Ön Ödeme Kolaylığı',
    EASY_ACTIVATION: 'Kolay Aktivasyon',
    INSTANT_CONNECTIVITY: 'Küresel Kapsama Alanı ile Anında Bağlantı',
    ROUND_TRIP: 'Gidiş-Dönüş Transferler',
    CULTURAL_EXPERIENCE: 'Eşsiz Kültürel Deneyimler',
    GUARANTEED_SEAT: 'Garantili Koltuk',
    ONBOARD_WIFI: 'Wi-Fi ve Şarj Bağlantı Noktaları',
    LUGGAGE_ASSISTANCE: 'Bagaj Yardımı',
    TOP_ATTRACTIONS: 'En Gözde Yerler Gezi Kapsamında',
    FREQ_DEP_MULTI_ROUTE: 'Birden Fazla Güzergahta Sık Seferler',
    CHARGING: 'Şarj İstasyonu',
    WIFI: 'Wi-Fi Erişimi',
    FnB: 'Yiyecek ve İçecek Hizmeti',
    LUXURY: 'Lüks deneyim',
    FOOD_DRINK: 'Yiyecek ve İçecekler',
    PANAROMIC: 'En gözde turistik yerlerde panoramik manzaralar',
    PANAROMIC_2: 'Panoramik Manzaralar',
    PANAROMIC_3: 'Panoramik, açık hava manzaraları',
    BEVERAGES: 'İçecek seçenkleri',
    GOURMET: 'Gurme akşam yemeği',
    GOURMET_2: 'Gurme akşam yemeği ve içecekler',
    NIGHTTIME: 'Büyüleyici gece manzaraları',
    ROMANTIC: 'Romantik atmosfer',
    TRANSFERS: 'Transferler Dahildir',
    CERTIFIED_OP: 'Sertifikalı Faaliyetler',
    BIRD_EYE: 'Kuşbakışı manzara',
    MULTI_JUMP: 'Farklı Atlama Zamanları',
    EXTREME_ADV: 'Ekstrem Macera',
    PHOTO_OP: 'Fotoğraf çekimi için harika manzaralar',
    TOP_ATTRACTIONS_COVERED: 'Gezilecek gözde turistik yerler',
    LOCAL_CULTURE: 'Yerel kültürü deneyimleyin',
    EXCLUSIVE_DISC: 'Özel İndirimler',
    EFFICIENT_PUBLIC_TRANSIT: 'Verimli Toplu Taşıma',
    FREQUENT_SERVICE: 'Sık Seferler',
    PREBOOKING: 'Kolay Ön Rezervasyon',
    LOCAL_CULTURE_IMM: 'Bölgeye Özgü Kültürel Etkileşim',
    DISCOVER_HIDDEN: 'Gizli Yerleri Keşfedin',
    CITY_SIGHTSEEING: 'Şehir Turu',
    OFFBEAT_ADV: 'Sıra Dışı Macera',
    DRINK_DEALS: 'İçecek Fırsatları',
    OFFBEAT_EXP: 'Sıra Dışı Deneyim',
    MULTIPLE_VARIETIES: 'Birçok Farklı Seçenek Mevcut',
    HIDDEN_GEMS: 'Saklı Güzellikler ve Gezilecek Sıra Dışı Yerler',
    EXPLORE_LOCAL: 'Yerel sokakları keşfedin',
    CUSTOMIZED_TREATMENTS: 'Kişiye Özel Bakımlar',
    TRAINED_THERAPISTS: 'Eğitimli Terapistler',
    HOLISTIC_WELLNESS: 'Holistik Sağlık',
    FLEXIBLE_DURATION: 'Esnek süre',
    MULTI_BOAT: 'Farklı gemi seçenekleri',
    SCENIC_ROUTES: 'Manzaralı Rotalar',
    HANDS_ON: 'Uygulamalı Öğrenme',
    CULTURAL_CULINARY: 'Kültürel ve Gastronomik İçerikler',
    EXPERT_HOSTS: 'Uzman Mihmandarlar',
    ADVENTURE_EXPERIENCE: 'Macera deneyimi',
    EQUIPMENT: 'Ekipman dahildir',
    SCENIC_FLYOVERS: 'Manzaralı geçitler',
    LIVE_COMMENTARY: 'Canlı Yorum',
    BEST_AERIAL_VIEWS: 'En iyi gökyüzü manzaraları',
    SAFE_CERT_OP: 'Güvenli ve sertifikalı faaliyetler',
    HANDPICKED: 'Özenle seçilmiş turlar',
    EFFORTLESS: 'Zahmetsiz planlama',
    EXPERT_GUIDES: 'Uzman rehberler. Derinlemesine bilgiler',
    ALL_ATTR_ONE_CARD: 'Tüm turistik yerler, tek kart',
    MULTI_CARD: 'Çoklu kart seçenekleri',
    COST_EFF: 'Uygun maliyetli ve kullanışlı',
    BEST_PRICES: 'En iyi fiyatlar',
    MULTI_TRANSPORT: 'Çoklu ulaşım aracı seçenekleri',
  },
  CAT_SUBCAT_PAGE: {
    ALL: 'Tümü',
    POPULAR_SUBCATEGORY: 'Popüler {0}',
    TOP_CATEGORY: 'Sık Tercih Edilen {0}',
    ATTRACTIONS: 'Gezilecek Yerler',
    ALL_SUBCATEGORY: 'Tümü {0}',
    BROWSE_BY_CATEGORIES: 'Kategorilere Göre Ara',
    TICKETS_FROM: 'Biletlerin başlangıç fiyatı',
    PRICE_LOW_HIGH: 'Fiyat (düşükten yükseğe)',
    PRICE_HIGH_LOW: 'Fiyat (yüksekten düşüğe)',
    FILTERS: 'Filtreler',
    RESET: 'Sıfırla',
    APPLY: 'Uygula',
  },
  COOKIE_BANNER: {
    DESKTOP:
      'Headout, web sitesi yolculuğunuzu geliştirmek için çerezleri kullanır.',
    MOBILE: 'Çerezler çalışıyor.',
    LEARN_MORE: 'Daha fazla bilgi edinin.',
  },
  SHOW_UNAVAILABLE: 'Gösteri Bulunamadı',
  NEWS_PAGE: {
    FEATURED_NEWS: 'Öne çıkan haberler',
    ALL_NEWS: 'Tüm Haberler',
    MORE_READS: 'Daha fazla içerik',
    LOAD_MORE: 'Daha fazla yükle',
    TRAILERS: 'Fragmanlar',
    GET_YOUR_TICKETS: 'Bilet alın',
    POPULAR_SHOWS: 'Popüler Gösteriler',
    FEATURED: 'Öne Çıkanlar',
    RECENT_NEWS: 'Son Haberler',
    SHOW_MORE_ARTICLES: 'Daha fazla makale görüntüle',
    COLLAPSE_ALL: 'Tümünü Daralt',
    REVIEWS: 'Yorumlar',
    SHOW_ALL_REVIEWS: 'Tüm yorumları görüntüle',
    MAILER: {
      HEADING:
        'En iyi tiyatro fırsatları ve haberleri doğruca gelen kutunuza gelsin',
      SUBHEADING:
        'Tiyatro gösterileriyle ilgili en son haberleri ve en cazip fırsatları almak için e-posta listemize katılın.',
    },
  },
  REVIEWS_PAGE: {
    BANNER_HEADING: '{0} yorum',
    REVIEWS_COUNT: '{0} Yorum',
    AWESOME: 'Harika',
    GOOD: 'İyi',
    AVERAGE: 'Ortalama',
    POOR: 'Kötü',
    TERRIBLE: 'Korkunç',
    REVIEW_BY_HEADOUT:
      'İşte bizim düşüncemiz: Headout Tarafından Bir Değerlendirme',
    WHAT_PEOPLE_ARE_SAYING: 'Geri bildirimler',
    MOST_RELEVANT: 'En alakalı',
    RATING_HIGH_TO_LOW: 'Değerlendirme: Yüksekten Düşüğe',
    RATING_LOW_TO_HIGH: 'Değerlendirme: Düşükten Yükseğe',
    CRITIC_REVIEWS: 'Eleştirmen yorumları',
    USER_REVIEWS: 'Kullanıcı yorumları',
    CONTRIBUTORS_REVIEW: 'Katılımcının yorumu',
  },
  AIRPORT_TRANSFER: {
    PRIVATE_TRANSFERS: 'Özel transferler',
    SHARED_TRANSFERS: 'Paylaşımlı transferler',
    BOOKING_STEPS: {
      BOOK_ONLINE: {
        TITLE: 'Online Rezervasyon',
        DESCRIPTION:
          'Online bilet alarak hızlı ve konforlu bir rezervasyon deneyimi yaşayın.',
      },
      INSTANT_CONFIRMATION: {
        TITLE: 'Anında Onay',
        DESCRIPTION:
          'Havaalanı transfer bileti rezervasyonunuzda anında onay alın.',
      },
      CONVENIENT_PICKUP: {
        TITLE: 'Araçla Servis Konforu',
        DESCRIPTION:
          'Uzun kuyruklarla uğraşmayın, çünkü transfer aracınız seçtiğiniz karşılanma noktasında sizi bekliyor olacak.',
      },
      DROP_OFF: {
        TITLE: 'Servisle Bırakma',
        DESCRIPTION: 'Gideceğiniz yere hızlı ve konforlu bir şekilde ulaşın.',
      },
    },
    SHARED_TRANSFERS_IN: '{0} konumunda paylaşımlı transferler',
    SHARED_TRANSFERS_DESCRIPTION:
      ' Havaalanına giden veya havaalanından gelen farklı yolcular için konforlu ve uygun maliyetli bir ulaşım seçeneği.',
    PRIVATE_TRANSFERS_IN: '{0} konumunda özel transferler',
    PRIVATE_TRANSFERS_DESCRIPTION:
      ' Bireyler veya küçük gruplar için havalimanına giderken ve havalimanından gelirken konforlu ve aktarmasız bir yolculuk sunan kullanışlı, kişiselleştirilmiş bir ulaşım hizmeti.',
    ANYWHERE_IN_THE_CITY: 'Şehrin herhangi bir yerine',
    DESCRIPTORS: {
      MULTIPLE_VEHICLE: 'Farklı araç seçenekleri',
      FREE_CANCELLATION: 'Ücretsiz iptal',
    },
    SEAMLESS_TRANSFERS: 'Dünya çapında güvenilir, sorunsuz transferler',
    PICK_THE_BEST_AIRPORT_TRANSFER:
      'Sizin için en uygun havalimanı transferini seçin',
    HASSLE_FREE_TRANSFER: 'Sorunsuz havalimanı transfer deneyimi',
    EFFORT_LESS_AIRPORT_TRANSFERS:
      '{0} içinde en kolay havaalanı transfer seçenekleri:',
    BUSES: 'otobüs',
    TRAINS: 'tren',
    PRIVATE_TAXIS: 'özel taksi',
    BUS_TRAIN: 'Otobüs/Tren',
    PRIVATE_TAXI: 'Özel Taksi',
    FROM: 'Kalkış noktası',
    SELECT_PICKUP: 'Servis kalkış noktası seçin',
    TO: 'Varış noktası',
    SELECT_DROPOFF: 'Servis varış noktası seçin',
    ENTER_DESTINATION: 'Varış noktanızı girin',
    ENTER_PICKUP: 'Araç servisi konumu girin',
    PICKUP_DATE: 'Araç servis tarihi',
    SELECT_DATE: 'Tarih seçin',
    PICKUP_TIME: 'Servis kalkış saati',
    SELECT_TIME: 'Saat seçin',
    GUEST: 'Konuk',
    GUESTS: 'Konuklar',
    ADD_GUESTS: 'Ziyaretçi ekle',
    ADULT_CHILD: 'Yetişkin/Çocuk',
    EXPLORE_TRANSFERS: 'Transferleri ve daha fazlasını keşfedin',
    COMBOS_AND_EXTRAS: 'Kombinasyonlar ve ekstralar',
    YOUR_RIDE_DOORSTEP: 'Araç hizmeti kapınızda',
    COMFORTABLE_RIDE:
      '{0} bölgesinde büyük havaalanlarına gidiş dönüş için konforlu özel taksi hizmeti rezervasyonu yapın.',
    TRUSTED_DRIVERS: 'Güvenilir sürücüler',
    RIDES_24_7: '7/24 hizmet veren araçlar mevcut',
    FLIGHT_TRACKING: 'Uçuş takibi',
    KNOW_MORE: 'Daha fazla bilgi edinin',
    RESERVE_YOUR_RIDE: 'Araç rezerve edin',
    TRANSFER_OPTIONS: 'Transfer seçenekleri bulundu',
    TRANSFERS_AVAILABLE_PLURAL: '{0} transfer mevcut',
    TRANSFERS_AVAILABLE_SINGULAR: '1 transfer mevcut',
    TRUSTED_PARTNERS: "35'ten fazla güvenilir ortak, {0}",
    WORLDWIDE: 'dünya geneli',
    COMFORTABLE_RIDES: 'Rahat araçlar',
    FREQUENT_DEPARTURES: 'Sık seferler',
    MULTIPLE_TRANSPORT_OPTIONS: 'Çoklu ulaşım aracı seçenekleri',
    AND_MANY_MORE: 'Ve çok daha fazlası',
    ADD_PICKUP_LOCATION: 'Araç servisi konumu',
    ADD_DROPOFF_LOCATION: 'Varış noktası ekleyin',
    SELECT_PICKUP_DATE_AND_TIME: 'Araç servisi tarih ve saati seçin',
    SELECT_A_DATE: 'Bir tarih seçin',
    TRAIN_STATION: 'Tren istasyonu',
    BUS_STOP: 'Otobüs durağı',
    ADD_RETURN: 'Dönüş ekle',
    HEADS_UP: 'Dikkat!',
    ADDED_RETURN_TRIP: 'Dönüş seferi eklediniz!',
    RETURN_NOTE:
      'Dönüş yolculuğu ayrıntılarını sonraki adımlarda paylaşacağımızı lütfen unutmayın.',
    OKAY_I_UNDERSTAND: 'Tamam, anladım',
    SERVING_GUESTS: 'Dünyanın dört bir yanında {1} ile {0} hizmet veriyoruz',
    GUESTS_COUNT: '220 binden fazla konuk',
    CITIES_COUNT: "55'ten fazla şehir",
    PARNTER_WITH_BEST:
      'Unutulmaz bir deneyim yaşamanızı sağlamak için yalnızca en iyilerle ortaklık kuruyoruz. Arkanıza yaslanın, yolculuğun tadını çıkarın ve detayları bize bırakın.',
  },
  PC_EXP: {
    SHOW_INCL: 'Gösteriye dahil olanlar & önemli bilgiler',
    CLEAR: 'Temizle',
    ALL_EXPERIENCES: 'Tüm deneyimler',
    FILTER_BY_CATEGORIES: 'Kategorilere göre filtrele',
    CATEGORIES: 'Kategoriler',
    COMBOS: {
      HEADING:
        'Her şey çift halinde güzeldir. Tıpkı tasarruf ettiren kombinasyonlarımız gibi.',
      DESCRIPTOR_1: 'Para tasarrufu sağlayan fırsatlar',
      DESCRIPTOR_2: 'Seyahatinizi daha iyi planlayın',
    },
  },
  TOP: 'Sık Tercih Edilen {0}',
  VIEW_CALENDAR: 'Takvimi görüntüle',
  SHOWS_CALENDAR: 'Etkinlik takvimi',
  IN: 'konum',
  SEATS: 'Koltuklar',
  CONTENT_PAGE: {
    CONTENT_GUIDE: 'İçerik Kılavuzu',
    QUICK_INFORMATION: 'Bilgilendirme',
    PEAK: 'Yüksek',
    OFF_PEAK: 'Düşük',
    ADDRESS: 'ADRES',
    RECOMMENDED_DURATION: 'ÖNERİLEN SÜRE',
    VISITORS_PER_YEAR: 'YILLIK ZİYARETÇİ SAYISI',
    NUMBER_OF_ENTRANCES: 'GİRİŞ SAYISI',
    EXPECTED_WAIT_TIME_STANDARD: 'TAHMİNİ BEKLEME SÜRESİ - STANDART',
    EXPECTED_WAIT_TIME_SKIP_THE_LINE: 'TAHMİNİ BEKLEME SÜRESİ - SIRAYI ATLA',
    UNESCO_YEAR: 'UNESCO YILI',
    ARCHITECTURE_STYLE: 'MİMARİ TARZLAR',
    TIMINGS: 'Saatler',
    SIZE_HEIGHT: 'BOYUT/YÜKSEKLİK',
    TICKETS: 'BİLETLER',
    FUN_FACTS: 'İlginç bilgiler',
    DID_YOU_KNOW: 'Biliyor muydunuz?',
    MORE_INTERESTING_FACTS: 'Daha fazla ilginç bilgi',
    PLAN_YOUR_VISIT: 'Seyahatinizi planlayın',
    ALSO_KNOWN_AS: 'Diğer Adıyla',
    FOUNDED_ON: 'Kurulma Tarihi',
    FOUNDED_BY: 'Kurucusu',
    FROM: 'Kalkış noktası',
    CLOSED_TODAY: 'Bugün kapalı',
    TODAY: 'Bugün',
    CLOSED: 'Kapalı',
    OPEN: 'Açık',
    LAST_ADMISSION: 'Son Giriş',
    DAYS: 'Günler',
    BEST_TIME_TO_VISIT: 'Ziyaret etmek için en iyi zaman',
    WEEKDAY_VS_WEEKEND: 'Hafta İçi ve Hafta Sonu',
    PEAK_VS_LOW_SEASON: 'Yüksek sezon / Düşük sezon',
    PLEASANT: 'Hoş',
    CROWDED: 'Kalabalık',
    VERY_CROWDED: 'Çok Kalabalık',
    LOW_SEASON: 'Sezon Dışı',
    MID_SEASON: 'Orta Sezon',
    PEAK_SEASON: 'Yüksek Sezon',
    TO: 'İÇİN',
    LOWER_TO: 'için',
    LAST_ENTRY: 'son giriş',
    SUBATTRACTIONS: 'Yan Aktiviteler',
    INCLUDED_WITH_TICKETS: '{0} biletlerine dahildir',
    INCLUDED_WITH_SOME_TICKETS: 'Bazı {0} biletlerine dahildir',
    EXPLORE_ALL_POI_TICKETS: '{0} ve {1} biletlerini ve turlarını keşfedin',
    EXPLORE_PARENT_TICKETS: '{0} biletlerini ve turlarını keşfedin',
    SELECT_YOUR_EXPERIENCE: 'Deneyiminizi seçin',
    OPERATING_HOURS: 'Çalışma saatleri',
    SEE_MORE: 'Daha fazla görüntüle',
    MORE_INSIGHTS: 'Daha fazla bilgi',
  },
  OFF_PERCENT: '%{0} indirim',
  THEATRE_LANDING_PAGE: {
    SEAT_PLAN: 'Oturma planı',
    CAPACITY: 'Kapasite: {0} koltuk',
    WHATS_ON: 'Güncel etkinlikler',
    CATEGORIES: 'Kategoriler',
  },
  NEXT: 'Sonraki',
  PREVIOUS: 'Önceki',
  ITINERARY: {
    TAB: 'Seyahat Programı',
    HEADING: 'Deneyim programı',
    VIEW_ITINERARY: 'Programı Görüntüle',
    PASSES_BY_SECTION_HEADING: 'Geçiş Rotaları',
    SUB_SECTION_HEADING: {
      HIGHLIGHTS: 'Öne Çıkanlar',
      NEARBY_THINGS_TO_DO: 'Yakınlarda yapılacak aktiviteler',
      THINGS_TO_DO: 'Yapılacak aktiviteler',
    },
    STOP_CARD: {
      TITLE: {
        START: 'BAŞLANGIÇ NOKTASI',
        END: 'VARIŞ NOKTASI',
        STARTING_POINT: 'BAŞLANGIÇ NOKTASI',
        STOP: 'DURUŞ NOKTASI',
        ENDING_POINT: 'VARIŞ NOKTASI',
        PASSING_BY: 'GEÇİŞ ROTALARI',
      },
      MULTI_POINTS_AVAILABLE: {
        START: '{0} başlangıç noktası mevcut',
        END: '{0} varış noktası mevcut',
      },
    },
    GET_DIRECTION: 'Yol tarifi al',
    DESCRIPTORS: {
      DURATION: {
        FULL: '{0} saat {1} dakika',
        WITHOUT_HOURS: '{0} dakika',
        WITHOUT_MINS: '{0} saat',
      },
      ATTRACTIONS_COUNT: '{0} cazibe merkezi',
      ACTIVITIES_COUNT: '{0} aktivite',
      TOTAL_DURATION: 'TOPLAM SÜRE',
      FREQUENCY: 'SIKLIK',
      FIRST_DEPARTURE: 'İLK KALKIŞ',
      LAST_DEPARTURE: 'SON KALKIŞ',
      FIRST_DEPARTURE_TIME: 'İLK KALKIŞ SAATİ',
      LAST_DEPARTURE_TIME: 'SON KALKIŞ SAATİ',
      MODE_OF_TRANSPORT: 'TRANSFER YÖNTEMİ',
      FOOD_AND_DRINKS: 'YİYECEK VE İÇECEKLER',
    },
    WALK_DURATION: '{0} yürüyüş',
    MORE: '{0} daha fazla',
    TIMELINE_VIEW: 'Zaman çizelgesi',
    MAP_VIEW: 'Harita',
    MAP_OVERLAY: 'Haritada gezinmek için CTRL/⌘ + kaydırma tuşlarını kullanın',
    VIEW_EXPERIENCE_MAPPED_OUT: 'Deneyiminizi harita üzerinde görüntüleyin.',
    OPEN_MAP_VIEW: 'Haritayı aç',
    START_POINT_SAME_AS_END_POINT:
      'Bitiş noktanız başlangıç noktanızla aynıdır',
  },
  CITY_AIRPORT_TRANSFERS: '{0} Havalimanı Transferleri',
  BANNER_SUBTEXT:
    'Güvenli ve ön rezervasyonlu bir havalimanı transferiyle stresten uzak seyahatin keyfini çıkarın.',
  BEST_PRICES: 'Gizli ücret içermeyen en iyi fiyatlar',
  BEST_PRICES_SUBTEXT:
    'Premium hizmet için sürprizsiz sabit fiyatlandırma ve rekabetçi fiyatlar sunuyoruz.',
  FREE_WAIT_TIME: 'Ücretsiz bekleme süresi, acele etmenize gerek kalmaz',
  FREE_WAIT_TIME_SUBTEXT:
    'Bagajınızı teslim alırken 45 dakikalık ücretsiz bekleme süresinden yararlanın',
  COMFORTABLE_RIDE: 'Rahat araç',
  COMFORTABLE_RIDE_SUBTEXT:
    'Özenle seçilmiş eğitimli sürücülerin kullandığı birinci sınıf araçlardan oluşan filoyla konforlu bir yolculuk yapın.',
  EXCELLENCE_HEADING: 'Başarı ve güven dolu bir geçmiş',
  ACTIVE_CITIES: 'dünya çapında hareketli şehirler',
  CUSTOMERS_SERVED: 'hizmet verilen müşteriler',
  YEARS_OF_SERVICE: 'yıllardır devam eden üstün hizmet',
  FIND_YOUR_RIDE: 'En uygun aracı bulun',
  FIND_YOUR_RIDE_SUBTEXT:
    'Aile boyu minivanlardan lüks sedan otomobillere kadar geniş araç seçeneklerin arasında bagajınıza ve grup büyüklüğünüze uygun aracı seçin',
  TRUST_TOOLTIP_HEADER: 'Değerlendirmeleri nasıl topluyoruz?',
  TRUST_TOOLTIP_CONTENT:
    "Değerlendirmeler, Headout'tan rezervasyon yaparak deneyimlerini tamamlayan gerçek kullanıcılar tarafından sağlanır.",
  REVIEW_SECTION_HEADER: 'Konuklarımızın görüşleri',
  TRUST_VB_TAG: 'Doğrulanmış rezervasyon',
};

export default tr;
