export const MAX_DESCRIPTORS_DISPLAYED = 6;

export const DESCRIPTOR_RANKING_LOGIC = [
  'MOBILE_TICKET',
  'INSTANT_CONFIRMATION',
  'DURATION',
  'AUDIO_GUIDE',
  'FREE_CANCELLATION',
  'SKIP_THE_LINE',
  'GUIDED_TOUR',
  'RETURN_TRANSFERS',
  'HOTEL_PICKUP',
  'MEALS_INCLUDED',
  'EXTENDED_VALIDITY',
];
