export const MAX_DESCRIPTORS_DISPLAYED = 5;

export const DESCRIPTOR_RANKING_LOGIC = [
  'FREE_CANCELLATION',
  'EXTENDED_VALIDITY',
  'INSTANT_CONFIRMATION',
  'MOBILE_TICKET',
  'DURATION',
  'AUDIO_GUIDE',
  'GUIDED_TOUR',
  'TRANSFERS',
  'HOTEL_PICKUP',
  'MEALS_INCLUDED',
];
