defaults.url=https://sentry.io/
defaults.org=headout
defaults.project=mystique
auth.token=9b8686a50fc046dd960848d55fcd445066b17916de064745b64efdf55f3b67ee
cli.executable=../../.npm/_npx/a8388072043b4cbc/node_modules/@sentry/cli/bin/sentry-cli
