export const MARKET_WISE_COUNTRIES: Record<string, string[]> = {
  MENA: ['United Arab Emirates', 'Turkey', 'Egypt', 'Morocco'],
  APAC: [
    'Indonesia',
    'Thailand',
    'Vietnam',
    'Japan',
    'Hong Kong',
    'Malaysia',
    'South Korea',
    'Singapore',
  ],
  EUROPE: [
    'France',
    'Italy',
    'Portugal',
    'Netherlands',
    'Greece',
    'Spain',
    'United Kingdom',
    'Germany',
    'Belgium',
    'Romania',
    'Hungary',
    'Switzerland',
    'Ireland',
    'Croatia',
    'Poland',
    'Malta',
    'Austria',
    'Andorra',
    'Norway',
    'Czech Republic',
    'Finland',
    'Iceland',
  ],
  AMERICA: ['United States', 'Mexico', 'Canada', 'Argentina', 'Peru', 'Brazil'],
  OCEANIA: ['Australia', 'New Zealand'],
};
