# .github/workflows/ci.yml
name: NowCI (non prod)
on:
  pull_request:
    branches:
      - master

jobs:
  ci_non_prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Use Yarn
        uses: 'borales/actions-yarn@v2.0.0'
      - name: prepare now build ready for aliasing
        timeout-minutes: 10
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          GIT_BRANCH: ${{ github.head_ref }}
          GIT_ACTOR: ${{ github.actor }}
        run: |
          sudo rm /usr/local/bin/now
          sudo npm i -g now@16.6.0
          sudo yarn
          now --version
          node ./deployment/stage
          now --token ${ZEIT_TOKEN} -A now.stage.1.json --scope headout -e GIT_BRANCH=${GIT_BRANCH} -e GIT_ACTOR=${GIT_ACTOR} --no-clipboard --debug
