name: CD

on:
  push:
    tags:
      - "*"

# [TODO] [fail the rollout step if tests fail]
# [HOW] add a test step which'll pull all domains from `now.production.json`
# then add a `stage.` to all of them, and hit the testing API with these domains
# only if that responds back with success, we'll let `rollout` happen
jobs:
  rollout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: now deploy
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: |
          sudo rm /usr/local/bin/now
          sudo npm i -g now@16.3.1
          now --version
          now --token ${ZEIT_TOKEN} -A now.production.json --scope headout --prod
