name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: rollout to stage
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          GIT_BRANCH: ${{ github.head_ref }}
          GIT_ACTOR: ${{ github.actor }}
        run: |
          sudo rm /usr/local/bin/now
          sudo npm i -g now@16.3.1
          now --version
          now --token ${ZEIT_TOKEN} --scope headout --prod -e GIT_BRANCH=${GIT_BRANCH} -e GIT_ACTOR=${GIT_ACTOR}
          now --token ${ZEIT_TOKEN} -A now.2.json --scope headout --prod -e GIT_BRANCH=${GIT_BRANCH} -e GIT_ACTOR=${GIT_ACTOR}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Use Yarn
        uses: "nuxt/actions-yarn@master"
      - name: run tests
        run: |
          yarn
          node ./tests/stage.js
