name: CI

on: ["deployment"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      # - name: "Deployment pending"
      #   uses: "deliverybot/deployment-status@master"
      #   with:
      #     state: "pending"
      #     token: "${{ github.token }}"

      - name: Use Yarn
        uses: "borales/actions-yarn@v2.0.0"

      - name: rollout to ${{ github.event.deployment.environment }}
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          GIT_BRANCH: ${{ github.head_ref }}
          GIT_ACTOR: ${{ github.actor }}
        run: |
          sudo rm /usr/local/bin/now
          sudo npm i -g now@16.3.1
          sudo yarn
          now --version
          node ./deployment/${{ github.event.deployment.environment }}
          find now.*.json | xargs -n1 -I {} /bin/bash -c 'now --token ${ZEIT_TOKEN} -A {} --scope headout --prod -e GIT_BRANCH=${GIT_BRANCH} -e GIT_ACTOR=${GIT_ACTOR}'

      # - name: "Deployment success"
      #   if: success()
      #   uses: "deliverybot/deployment-status@master"
      #   with:
      #     state: "success"
      #     token: "${{ github.token }}"
      # - name: "Deployment failure"
      #   if: failure()
      #   uses: "deliverybot/deployment-status@master"
      #   with:
      #     state: "failure"
      #     token: "${{ github.token }}"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Use Yarn
        uses: "borales/actions-yarn@v2.0.0"
      - name: run tests
        run: |
          yarn
          node ./tests/${{ github.event.deployment.environment }}.js
