name: Pull Request Sanity
on:
  pull_request:
    types: ['opened', 'edited']

jobs:
  name-lint:
    name: Name Lint
    uses: headout/arsenal/.github/workflows/pr-sanity.yaml@main
    secrets:
      MEDUSA_TEST_URL: ${{ secrets.MEDUSA_TEST_URL }}
      MEDUSA_API_KEY: ${{ secrets.MEDUSA_API_KEY }}
