name: Prod MB Status

on:
  schedule:
    - cron: "30 5/* * * *"

jobs:
  ensurer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Use Yarn
        uses: "nuxt/actions-yarn@master"
      - name: Mystique tests
        run: |
          yarn
          node ./tests/slack.js
